package targets

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/gomodule"
)

// packTimeout bounds `npm pack --dry-run`, which fetches nothing.
const packTimeout = 2 * time.Minute

// UploadListing is what one target's published upload of a directory would
// carry.
type UploadListing struct {
	// Label names the upload in a finding.
	Label string
	// Files are relative to the listed directory, "/"-separated.
	Files []string
	// Fix says how a nested member's file is kept out of the upload.
	Fix string
	// PrivatePathFix says how a private path is kept out of it, in the
	// ecosystem's own exclusion.
	PrivatePathFix func(rel, rule, directory string) string
}

// zipExcludedDirs are the directories a Go module zip never carries
// (golang.org/x/mod/zip).
var zipExcludedDirs = map[string]bool{"vendor": true, ".git": true, ".hg": true, ".svn": true, ".bzr": true}

// Scratch is the command's scratch directory (strictcli's
// Context.ScratchDir): a directory outside the repository, made by the
// framework on the first call and removed when the command ends, for what
// a program the listing runs writes for itself.
type Scratch func() (string, error)

// ListUpload lists the files the upload of t's package in dir (absolute,
// inside repo) would carry, without the network: the Go module zip from the
// tracked files, the npm tarball from `npm pack --dry-run`, whose cache is
// in scratch. found is false for pypi, whose upload has to be built, which
// needs the network; the pypi CI workflow builds and checks it instead.
func ListUpload(h Handle, repo git.Repo, t Target, dir string, scratch Scratch) (UploadListing, bool, error) {
	switch t.Name() {
	case Go:
		l, err := goModuleZip(repo, dir)
		return l, err == nil, err
	case NPM:
		l, err := npmPack(h, dir, scratch)
		return l, err == nil, err
	}
	return UploadListing{}, false, nil
}

// goModuleZip is the zip the module proxy would build: the tracked files
// (the proxy zips the tagged commit), less any directory holding a go.mod
// of its own (another module) and the version-control and vendor
// directories.
func goModuleZip(repo git.Repo, dir string) (UploadListing, error) {
	rel, err := filepath.Rel(repo.Dir(), dir)
	if err != nil || rel == ".." || strings.HasPrefix(rel, "../") {
		return UploadListing{}, fmt.Errorf("%s is not inside the repository %s", dir, repo.Dir())
	}
	rel = filepath.ToSlash(rel)
	tracked, err := repo.TrackedFiles()
	if err != nil {
		return UploadListing{}, err
	}
	var inModule []string
	for _, f := range tracked {
		if rel == "." {
			inModule = append(inModule, f)
		} else if strings.HasPrefix(f, rel+"/") {
			inModule = append(inModule, f[len(rel)+1:])
		}
	}
	nested := map[string]bool{}
	for _, f := range inModule {
		if path.Base(f) == gomodule.FileName && path.Dir(f) != "." {
			nested[path.Dir(f)] = true
		}
	}
	var files []string
	for _, f := range inModule {
		parts := strings.Split(f, "/")
		excluded := false
		for _, p := range parts[:len(parts)-1] {
			if zipExcludedDirs[p] {
				excluded = true
			}
		}
		if excluded || insideAnyDir(f, nested) {
			continue
		}
		files = append(files, f)
	}
	return UploadListing{
		Label: "the Go module zip",
		Files: files,
		Fix:   "The module proxy keeps a zip permanently. Move the nested member out of the module's directory, or give it a go.mod of its own, which Go leaves out of the zip.",
		PrivatePathFix: func(rel, rule, directory string) string {
			return goPrivatePathFix(dir, rel, directory)
		},
	}, nil
}

// insideAnyDir reports whether rel lies inside one of dirs.
func insideAnyDir(rel string, dirs map[string]bool) bool {
	for d := range dirs {
		if strings.HasPrefix(rel, d+"/") {
			return true
		}
	}
	return false
}

// SelfdocGeneratedHeader is what the first line of a file selfdoc generated
// from a template starts with; a CLAUDE.md carrying it is selfdoc's to move.
const SelfdocGeneratedHeader = "<!-- Auto-generated by selfdoc from "

// goPrivatePathFix keeps a private path out of the Go module zip of the
// module in moduleDir. Go leaves out only whole directories holding a go.mod
// of their own, so a private directory gets a stub module, and a private
// file moves into such a directory or stops being committed. A CLAUDE.md
// selfdoc generated is moved by selfdoc's own migration.
func goPrivatePathFix(moduleDir, rel, directory string) string {
	if directory != "" {
		written := ""
		if !strings.Contains(directory, "/") {
			written = " (`rlsbl scaffold` writes it)"
		}
		return fmt.Sprintf("put a stub go.mod in %s/%s; any `module` line does, and Go leaves a directory holding its own go.mod out of the zip", directory, written)
	}
	parent := path.Dir(rel)
	if parent == "." {
		parent = ""
	}
	if path.Base(rel) == "CLAUDE.md" {
		home := ".claude"
		if parent != "" {
			home = parent + "/.claude"
		}
		if selfdocGenerated(filepath.Join(moduleDir, filepath.FromSlash(rel))) {
			stub := "run `rlsbl scaffold`, which writes the stub go.mod in .claude/"
			if parent != "" {
				stub = "put a stub go.mod in " + home + "/"
			}
			return fmt.Sprintf("selfdoc generated it, and a current selfdoc generates it under .claude/ instead: upgrade selfdoc, run `selfdoc layout migrate --dry-run`, then `selfdoc layout migrate` where selfdoc.json is, which moves it to %s/CLAUDE.md and commits, then %s", home, stub)
		}
		return fmt.Sprintf("Go cannot leave a single file out of the zip: move it to %s/CLAUDE.md, which Claude Code reads, and put a stub go.mod in %s/", home, home)
	}
	return fmt.Sprintf("Go cannot leave a single file out of the zip: stop committing it (`git rm --cached %s` and add it to .gitignore), or move it into a directory that holds a stub go.mod", rel)
}

// selfdocGenerated reports whether the file opens with selfdoc's
// generated-file header; a file that cannot be read does not.
func selfdocGenerated(file string) bool {
	data, err := os.ReadFile(file)
	if err != nil {
		return false
	}
	first, _, _ := strings.Cut(string(data), "\n")
	return strings.HasPrefix(first, SelfdocGeneratedHeader)
}

// npmPack lists the tarball `npm pack` would publish without packing it:
// --dry-run packs nothing, --ignore-scripts runs no lifecycle script, and
// --offline fetches nothing. npm still writes its cache and logs, so its
// cache is in the command's scratch directory, which the command removes
// when it ends.
func npmPack(h Handle, dir string, scratch Scratch) (listing UploadListing, err error) {
	p, err := readManifest(dir)
	if err != nil {
		return UploadListing{}, err
	}
	_, hasFiles, err := p.member("files")
	if err != nil {
		return UploadListing{}, err
	}
	if scratch == nil {
		return UploadListing{}, fmt.Errorf("listing the npm upload of %s runs npm, which writes its cache, and the command gave no scratch directory for it", dir)
	}
	root, err := scratch()
	if err != nil {
		return UploadListing{}, err
	}
	cache := filepath.Join(root, "npm-cache")
	res, err := h.Run([]interface{}{"npm", "pack", "--dry-run", "--json", "--ignore-scripts", "--offline", "--logs-max=0"},
		strictcli.Cwd(dir), strictcli.Check(false), strictcli.Timeout(packTimeout),
		strictcli.EffectEnv(map[string]string{"npm_config_cache": cache}))
	if err != nil {
		return UploadListing{}, err
	}
	if res.ExitCode() != 0 {
		out := strings.TrimSpace(res.Stderr())
		if out == "" {
			out = strings.TrimSpace(res.Stdout())
		}
		return UploadListing{}, fmt.Errorf("`npm pack --dry-run` failed in %s: %s", dir, out)
	}
	var packed []struct {
		Files []struct {
			Path string `json:"path"`
		} `json:"files"`
	}
	if err := json.Unmarshal([]byte(res.Stdout()), &packed); err != nil || len(packed) != 1 {
		return UploadListing{}, fmt.Errorf("`npm pack --dry-run --json` in %s printed something that is not one package's listing", dir)
	}
	var files []string
	for _, f := range packed[0].Files {
		files = append(files, f.Path)
	}
	fix := func(rel, rule, directory string) string { return "add \"" + rule + "\" to .npmignore" }
	if hasFiles {
		// npm reads .npmignore only for what "files" does not name, so the
		// field itself has to stop covering the path.
		fix = func(rel, rule, directory string) string {
			what := rel
			if directory != "" {
				what = directory
			}
			return "narrow the \"files\" field in package.json so that it no longer covers " + what
		}
	}
	return UploadListing{
		Label:          "`npm pack`",
		Files:          files,
		Fix:            "List only the member's own files in package.json's \"files\" field (or exclude the nested member in .npmignore).",
		PrivatePathFix: fix,
	}, nil
}
