package historyrewrite_test

import (
	"os"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/historyrewrite"
	"github.com/stricttools/rlsbl/internal/releaserecord"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

// unarchived is portal with 0.1.0 released (its changelog file committed
// in R, tagged v0.1.0 when tagged is true) and no archive.
type unarchived struct {
	repo *testsupport.Repo
	A, R string
}

func newUnarchived(t *testing.T, tagged bool, releaseMessage string) *unarchived {
	t.Helper()
	repo := testsupport.NewRepo(t)
	base := map[string]string{declarationsPath: portalDeclarations, "package.json": packageJSON("0.1.0"), "notes.txt": "notes\n"}
	for _, m := range manifests {
		base[m] = "owner = \"rlsbl\"\n"
	}
	a := commitAll(t, repo, base, "the project")
	r := commitAll(t, repo, map[string]string{changelogFilePath: entryLine(1, a)}, releaseMessage)
	if tagged {
		repo.Git("tag", "v0.1.0", r)
	}
	return &unarchived{repo: repo, A: a, R: r}
}

func backfill(t *testing.T, dir, overrides string, dryRun bool) strictcli.Result {
	t.Helper()
	return run(t, dryRun, func(ctx *strictcli.Context) error {
		return historyrewrite.Backfill(ctx, dir, historyrewrite.BackfillRequest{Overrides: overrides, AutoCommit: true})
	})
}

// noRelease answers that v0.1.0 carries no GitHub Release.
func noRelease(t *testing.T) *testsupport.GH {
	t.Helper()
	return gh(t, testsupport.GHAnswer{Args: ghExists, Stderr: "release not found", Exit: 1})
}

func readArchive(t *testing.T, repo *testsupport.Repo, v string) releaserecord.Archive {
	t.Helper()
	version, err := semver.Parse(v)
	if err != nil {
		t.Fatal(err)
	}
	a, err := releaserecord.ReadArchive(repo.Dir, releaserecord.ArchiveDir("portal"), version)
	if err != nil {
		t.Fatal(err)
	}
	return a
}

func TestAReleasedVersionWithNoArchiveIsMaterializedFromItsTag(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	newSafegit(t, "0.31.0")
	noRelease(t)

	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "materialize") || exists(f.repo, archivePath) {
		t.Fatalf("the dry run did not plan the archive, or wrote it:\n%s", r.Stdout)
	}

	r = backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 0)
	a := readArchive(t, f.repo, "0.1.0")
	if a.Fate != releaserecord.FateRecorded || a.ReleaseCommit.Commit != f.R || a.ReleaseCommit.Trees["."] != f.repo.Git("rev-parse", f.R+"^{tree}") {
		t.Fatalf("the archive records %+v", a)
	}
	if a.Bump != semver.Minor || !strings.HasPrefix(a.Description, "Reconstructed from this version's commit subjects") {
		t.Fatalf("the archive's reconstructed fields are %q and %q", a.Bump, a.Description)
	}
	text := readFile(t, f.repo, archivePath)
	if !strings.Contains(text, "Materialized by `rlsbl release backfill`") || !strings.Contains(text, "came from: commit-subjects:") {
		t.Fatalf("the archive does not say it was materialized and where its description came from:\n%s", text)
	}
	if !strings.Contains(f.repo.Git("log", "-1", "--format=%B"), "Autogenerated: true") {
		t.Fatal("the archive was not committed with the Autogenerated trailer")
	}
	r = backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "Nothing to do") {
		t.Fatalf("a second run was not settled:\n%s", r.Stdout)
	}
}

func TestAnArchiveWithBlankFieldsIsCompletedNamingEachSource(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	tree := f.repo.Git("rev-parse", f.R+"^{tree}")
	f.repo.Write(archivePath, "format_version = 2\nbump = \"\"\ninclude = [\"npm\"]\nexclude = []\ndescription = \"\"\nrelease_commit = \""+f.R+"\"\n\n[released_trees]\n\".\" = \""+tree+"\"\n")
	f.repo.Git("add", "-A")
	f.repo.Git("commit", "-q", "-m", "an archive nobody filled in")
	newSafegit(t, "0.31.0")
	gh(t, testsupport.GHAnswer{Args: ghExists, Stdout: "v0.1.0"},
		testsupport.GHAnswer{Args: ghBody, Stdout: "## What changed\n\nThe notes are fixed.\n\n**Full Changelog**: https://github.com/acme/portal/commits/v0.1.0"})

	requireExit(t, backfill(t, f.repo.Dir, "", false), 0)
	a := readArchive(t, f.repo, "0.1.0")
	if a.Bump != semver.Minor || a.Description != "The notes are fixed." || a.ReleaseCommit.Commit != f.R {
		t.Fatalf("the completed archive holds %+v", a)
	}
	text := readFile(t, f.repo, archivePath)
	for _, want := range []string{"bump reconstructed by `rlsbl release backfill` from version arithmetic against 0.0.0", "description reconstructed by `rlsbl release backfill` from github-release:v0.1.0"} {
		if !strings.Contains(text, want) {
			t.Fatalf("the archive lacks %q:\n%s", want, text)
		}
	}
	r := backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "Nothing to do") {
		t.Fatalf("a second run was not settled:\n%s", r.Stdout)
	}
}

func TestANeverReleasedArchiveIsLeftAsItIs(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, false, "the changelog")
	content := "format_version = 2\nbump = \"minor\"\ninclude = []\nexclude = []\ndescription = \"An attempt\"\nnever_released = true\n"
	f.repo.Write(archivePath, content)
	f.repo.Git("add", "-A")
	f.repo.Git("commit", "-q", "-m", "declare the fate")
	newSafegit(t, "0.31.0")
	gh(t)
	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "never_released = true") || !strings.Contains(r.Stdout, "0 archive(s) would be written") {
		t.Fatalf("the settled fate was not reported:\n%s", r.Stdout)
	}
	r = backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "Nothing to do") {
		t.Fatalf("an apply had something to do:\n%s", r.Stdout)
	}
	if readFile(t, f.repo, archivePath) != content {
		t.Fatal("the never-released archive was rewritten")
	}
}

func TestATaglessVersionIsRecordedFromItsVersionBumpCommit(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, false, "v0.1.0")
	newSafegit(t, "0.31.0")
	gh(t)
	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "version-bump commit") || !strings.Contains(r.Stdout, "never_released = true") {
		t.Fatalf("the plan does not name the bump commit and how to declare a version never released:\n%s", r.Stdout)
	}
	requireExit(t, backfill(t, f.repo.Dir, "", false), 0)
	if a := readArchive(t, f.repo, "0.1.0"); a.ReleaseCommit.Commit != f.R {
		t.Fatalf("the archive records %+v, want the version-bump commit %s", a.ReleaseCommit, f.R)
	}
}

func TestAVersionWithNoTagAndNoBumpCommitIsUnrecoverable(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, false, "the changelog")
	newSafegit(t, "0.31.0")
	gh(t)
	requireExit(t, backfill(t, f.repo.Dir, "", false), 0)
	if a := readArchive(t, f.repo, "0.1.0"); a.Fate != releaserecord.FateUnrecoverable {
		t.Fatalf("the archive's fate is %s, want unrecoverable", a.Fate)
	}
}

func TestATagNoRecordNamesIsAdoptedAsReleased(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	later := f.repo.CommitFile("notes.txt", "later\n", "later work")
	f.repo.Git("tag", "v0.2.0", later)
	newSafegit(t, "0.31.0")
	noRelease(t)
	tag020 := []string{"release", "view", "v0.2.0", "--repo", "acme/portal", "--json", "tagName", "--jq", ".tagName"}
	gh(t, testsupport.GHAnswer{Args: ghExists, Stderr: "release not found", Exit: 1}, testsupport.GHAnswer{Args: tag020, Stderr: "release not found", Exit: 1})

	r := backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 0)
	a := readArchive(t, f.repo, "0.2.0")
	if a.ReleaseCommit.Commit != later || a.Bump != semver.Minor {
		t.Fatalf("the adopted archive holds %+v", a)
	}
}

func TestAnUnexplainedTagRefusesTheApplyUntilResolved(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	f.repo.Git("tag", "nightly", f.A)
	newSafegit(t, "0.31.0")
	noRelease(t)

	// The preview shows the whole plan, the blocker first, and exits 1.
	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 1)
	if i, j := strings.Index(r.Stdout, "tag nightly"), strings.Index(r.Stdout, "portal 0.1.0"); i < 0 || j < 0 || i > j {
		t.Fatalf("the unexplained tag is not listed before the versions:\n%s", r.Stdout)
	}
	r = backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 1)
	requireStderr(t, r, "refusing to backfill", "shipped_as = \"nightly\"", "rlsbl transition unversioned-tag --tag nightly", "git tag -d nightly")
	if exists(f.repo, archivePath) {
		t.Fatal("the refused apply wrote an archive")
	}

	// Recording it outside the version model clears the refusal.
	f.repo.Write(".strictmetadata/lifecycle-and-license/lifecycle-and-license.toml", "format_version = 1\n\n[[unversioned_tags]]\ntag = \"nightly\"\nreason = \"a moving marker\"\nrecorded = 2026-01-01\n")
	requireExit(t, backfill(t, f.repo.Dir, "", true), 0)
	if err := os.Remove(f.repo.Path(".strictmetadata/lifecycle-and-license/lifecycle-and-license.toml")); err != nil {
		t.Fatal(err)
	}

	// Deleting it clears the refusal too.
	f.repo.Git("tag", "-d", "nightly")
	requireExit(t, backfill(t, f.repo.Dir, "", true), 0)
}

func TestAnOldSpellingIsExplainedOnceItsArchiveRecordsShippedAs(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, false, "the changelog")
	f.repo.Git("tag", "portal-0.1.0", f.R)
	newSafegit(t, "0.31.0")
	gh(t)
	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 1)
	requireStderr(t, r, "portal-0.1.0", "shipped_as = \"portal-0.1.0\"")

	// The archive recording the spelling the version shipped under adopts the
	// tag's commit.
	f.repo.Write(archivePath, "format_version = 2\nbump = \"minor\"\ninclude = [\"npm\"]\nexclude = []\ndescription = \"The first release\"\nshipped_as = \"portal-0.1.0\"\n")
	portal := []string{"release", "view", "portal-0.1.0", "--repo", "acme/portal", "--json", "tagName", "--jq", ".tagName"}
	gh(t, testsupport.GHAnswer{Args: portal, Stderr: "release not found", Exit: 1})
	r = backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 0)
	if a := readArchive(t, f.repo, "0.1.0"); a.ReleaseCommit.Commit != f.R || a.ShippedAs != "portal-0.1.0" {
		t.Fatalf("the archive holds %+v", a)
	}
}

func TestReviewedDescriptionsComeFirst(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	newSafegit(t, "0.31.0")
	noRelease(t)
	overrides := f.repo.Path("experiments/overrides.toml")
	testsupport.WriteFile(t, overrides, "[versions.\"0.1.0\"]\ndescription = \"The first release, reviewed.\"\ncontext = \"Why it was made.\"\n")
	requireExit(t, backfill(t, f.repo.Dir, overrides, false), 0)
	a := readArchive(t, f.repo, "0.1.0")
	if a.Description != "The first release, reviewed." || a.Context != "Why it was made." {
		t.Fatalf("the archive holds %q and %q", a.Description, a.Context)
	}
	r := backfill(t, f.repo.Dir, overrides, false)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "Nothing to do") {
		t.Fatalf("a second run with the same file was not settled:\n%s", r.Stdout)
	}
}

func TestAnOverrideOfAVersionTheRepositoryLacksIsRefused(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	newSafegit(t, "0.31.0")
	noRelease(t)
	overrides := f.repo.Path("experiments/overrides.toml")
	testsupport.WriteFile(t, overrides, "[versions.\"9.9.9\"]\ndescription = \"Nothing\"\n")
	r := backfill(t, f.repo.Dir, overrides, true)
	requireExit(t, r, 1)
	requireStderr(t, r, "does not have: 9.9.9")

	testsupport.WriteFile(t, overrides, "[versions.\"0.1.0\"]\ndescription = \"Reviewed\"\n")
	requireExit(t, backfill(t, f.repo.Dir, overrides, true), 0)
}

func TestAStashRefusesTheApplyUntilDropped(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	newSafegit(t, "0.31.0")
	noRelease(t)
	f.repo.Write("notes.txt", "work in progress\n")
	f.repo.Git("stash", "push", "-q")
	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 0)
	if !strings.Contains(r.Stdout, "stash") {
		t.Fatalf("the preview does not report the stash:\n%s", r.Stdout)
	}
	r = backfill(t, f.repo.Dir, "", false)
	requireExit(t, r, 1)
	requireStderr(t, r, "refusing to backfill", "git stash drop")

	f.repo.Git("stash", "drop", "-q")
	requireExit(t, backfill(t, f.repo.Dir, "", false), 0)
}

func TestAnArchiveOfTheFirstFormatIsRefusedNamingTheMigration(t *testing.T) {
	hygiene.Isolate(t)
	f := newUnarchived(t, true, "v0.1.0")
	f.repo.Write(archivePath, "format_version = 1\nbump = \"minor\"\ninclude = []\nexclude = []\ndescription = \"old\"\ncandidate_sha = \""+f.R+"\"\n")
	newSafegit(t, "0.31.0")
	noRelease(t)
	r := backfill(t, f.repo.Dir, "", true)
	requireExit(t, r, 1)
	requireStderr(t, r, "rlsbl migrate records")
}
