package git

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/stricttools/strictcli/go/strictcli"
)

// CommitRequest is one commit of named paths.
type CommitRequest struct {
	// Message is the commit message.
	Message string
	// Paths are the paths the commit carries, relative to the repository
	// root. A path git reports no change for is left out (naming it would
	// make safegit refuse the whole commit); a path that is untracked and
	// ignored is refused.
	Paths []string
	// Autogenerated adds the Autogenerated: true trailer, which exempts the
	// commit from changelog coverage.
	Autogenerated bool
	// RequireChange refuses a commit none of whose paths changed, for a
	// caller whose change must have materialized.
	RequireChange bool
}

// PartitionStageable splits paths into those git reports some change for
// (modified, staged, deleted, or untracked: stageable) and those that are
// untracked and ignored, keeping the given order. A path git reports nothing
// for is in neither list, and so is a path whose working tree matches HEAD
// while its index does not (a staged deletion of a file written back
// unchanged): staging it leaves HEAD's tree as it is, which safegit refuses.
func (r Repo) PartitionStageable(paths []string) (stageable, ignored []string, err error) {
	for _, p := range paths {
		out, err := r.output("--no-optional-locks", "status", "--porcelain", "-z", "--ignored=matching", "--untracked-files=normal", "--", p)
		if err != nil {
			return nil, nil, err
		}
		records := ParseStatusRecords(out)
		if len(records) == 0 {
			continue
		}
		allIgnored := true
		for _, rec := range records {
			if !strings.HasPrefix(rec, "!!") {
				allIgnored = false
			}
		}
		if allIgnored {
			ignored = append(ignored, p)
			continue
		}
		same, err := r.workingTreeMatchesHead(p)
		if err != nil {
			return nil, nil, err
		}
		if !same {
			stageable = append(stageable, p)
		}
	}
	return stageable, ignored, nil
}

// workingTreeMatchesHead reports whether staging path would leave HEAD's
// entry for it as it is: both absent, or a regular file whose mode and
// content, as git would store it, equal HEAD's blob. A directory, a symlink,
// and a repository without a HEAD commit are reported as differing, which
// keeps them stageable as git status reported them.
func (r Repo) workingTreeMatchesHead(path string) (bool, error) {
	if _, found, err := r.ResolveCommit("HEAD"); err != nil || !found {
		return false, err
	}
	listing, err := r.output("ls-tree", "-z", "--full-tree", "HEAD", "--", path)
	if err != nil {
		return false, err
	}
	var headMode, headType, headID string
	if entry, _, _ := strings.Cut(listing, "\x00"); entry != "" {
		meta, name, ok := strings.Cut(entry, "\t")
		fields := strings.Fields(meta)
		if !ok || name != path || len(fields) != 3 {
			return false, nil
		}
		headMode, headType, headID = fields[0], fields[1], fields[2]
	}
	info, err := os.Lstat(filepath.Join(r.dir, filepath.FromSlash(path)))
	if errors.Is(err, os.ErrNotExist) {
		return headID == "", nil
	}
	if err != nil {
		return false, err
	}
	if headType != "blob" || !info.Mode().IsRegular() {
		return false, nil
	}
	mode := "100644"
	if info.Mode().Perm()&0o111 != 0 {
		mode = "100755"
	}
	if mode != headMode {
		return false, nil
	}
	id, err := r.output("hash-object", "--", path)
	if err != nil {
		return false, err
	}
	return strings.TrimSpace(id) == headID, nil
}

// planCommit checks the request and narrows its paths to the stageable ones.
// ok is false when nothing is left to commit and the request allows that.
func (r Repo) planCommit(req CommitRequest) (paths []string, ok bool, err error) {
	if strings.TrimSpace(req.Message) == "" {
		return nil, false, errors.New("refusing to commit: the commit message is empty")
	}
	if len(req.Paths) == 0 {
		return nil, false, fmt.Errorf("refusing to commit %q: no path was named", req.Message)
	}
	if err := r.RequireToplevel(); err != nil {
		return nil, false, err
	}
	stageable, ignored, err := r.PartitionStageable(req.Paths)
	if err != nil {
		return nil, false, err
	}
	if len(ignored) > 0 {
		verb := "are"
		if len(ignored) == 1 {
			verb = "is"
		}
		return nil, false, fmt.Errorf("refusing to commit %q: %s %s untracked and ignored, so the commit would carry nothing for it; stop naming it in this commit or change the ignore rule that matches it", req.Message, strings.Join(ignored, ", "), verb)
	}
	if len(stageable) == 0 {
		if req.RequireChange {
			return nil, false, fmt.Errorf("refusing to commit %q: none of the named paths changed (%s), so the change this commit exists to record did not happen", req.Message, strings.Join(req.Paths, ", "))
		}
		return nil, false, nil
	}
	manifests, _, err := r.PartitionStageable(ownershipManifests(req.Paths))
	if err != nil {
		return nil, false, err
	}
	return append(stageable, manifests...), true, nil
}

// MetadataDir is the directory at a repository's root that holds every
// family tool's records, each directory directly under it owned through its
// OwnershipManifest.
const MetadataDir = ".strictmetadata"

// OwnershipManifest is the file naming a record directory's owner.
const OwnershipManifest = "manifest.toml"

// ownershipManifests is the ownership manifest of each record directory a
// path lies in, other than the paths themselves. A commit carries the
// changed ones, so a writer that created a directory's manifest along with a
// record never leaves the manifest out of the record's commit.
func ownershipManifests(paths []string) []string {
	named := make(map[string]bool, len(paths))
	for _, p := range paths {
		named[p] = true
	}
	var manifests []string
	for _, p := range paths {
		rest, ok := strings.CutPrefix(p, MetadataDir+"/")
		if !ok {
			continue
		}
		dir, _, nested := strings.Cut(rest, "/")
		if !nested {
			continue
		}
		m := MetadataDir + "/" + dir + "/" + OwnershipManifest
		if !named[m] {
			named[m] = true
			manifests = append(manifests, m)
		}
	}
	return manifests
}

// Commit commits the request's changed paths through safegit, which stages
// and commits named paths safely while other sessions share the worktree.
// committed is false when none of the paths changed and the request allows
// that. safegit missing from PATH is an error: there is no fallback to git.
// The repository's directory must be the root of its own working tree.
func (r Repo) Commit(req CommitRequest) (committed bool, err error) {
	paths, ok, err := r.planCommit(req)
	if err != nil || !ok {
		return false, err
	}
	if _, err := exec.LookPath("safegit"); err != nil {
		return false, errors.New("safegit is not on PATH: rlsbl commits through safegit so a commit never takes another session's staged work with it; install safegit and run this again")
	}
	args := []interface{}{"safegit", "commit"}
	if req.Autogenerated {
		args = append(args, "--trailer", AutogeneratedTrailer+": true")
	}
	args = append(args, "-m", req.Message, "--")
	for _, p := range paths {
		args = append(args, p)
	}
	if _, err := r.e.Run(args, strictcli.Cwd(r.dir), strictcli.Timeout(localTimeout), strictcli.Stream(true)); err != nil {
		return false, fmt.Errorf("safegit commit in %s: %w", r.dir, err)
	}
	return true, nil
}

// CommitDetached commits the request's changed paths with git itself. It is
// for the release checkout alone: a detached checkout no other session
// shares, whose commits reach the branch only through the release's
// compare-and-swap advance, and where safegit, which commits onto a branch,
// refuses the detached HEAD.
func (r Repo) CommitDetached(req CommitRequest) (committed bool, err error) {
	paths, ok, err := r.planCommit(req)
	if err != nil || !ok {
		return false, err
	}
	addable, err := r.addable(paths)
	if err != nil {
		return false, err
	}
	if len(addable) > 0 {
		if err := r.mutate(localTimeout, append([]string{"add", "--"}, addable...)...); err != nil {
			return false, err
		}
	}
	args := []string{"commit", "-q"}
	if req.Autogenerated {
		args = append(args, "--trailer", AutogeneratedTrailer+": true")
	}
	args = append(args, "-m", req.Message)
	if err := r.mutate(localTimeout, args...); err != nil {
		return false, err
	}
	return true, nil
}

// addable is the paths `git add` can take: every path except a deletion the
// index already carries (saferm stages a tracked file's removal, and git add
// of a path gone from both the tree and the index fails).
func (r Repo) addable(paths []string) ([]string, error) {
	var missing []string
	for _, p := range paths {
		if _, err := os.Lstat(filepath.Join(r.dir, filepath.FromSlash(p))); errors.Is(err, os.ErrNotExist) {
			missing = append(missing, p)
		} else if err != nil {
			return nil, err
		}
	}
	if len(missing) == 0 {
		return paths, nil
	}
	out, err := r.output(append([]string{"ls-files", "-z", "--"}, missing...)...)
	if err != nil {
		return nil, err
	}
	indexed := nulFields(out)
	inIndex := func(p string) bool {
		clean := filepath.ToSlash(filepath.Clean(p))
		for _, f := range indexed {
			if f == clean || strings.HasPrefix(f, clean+"/") {
				return true
			}
		}
		return false
	}
	isMissing := map[string]bool{}
	for _, p := range missing {
		isMissing[p] = true
	}
	var kept []string
	for _, p := range paths {
		if !isMissing[p] || inIndex(p) {
			kept = append(kept, p)
		}
	}
	return kept, nil
}
