package git_test

import (
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

// committedFiles lists the files HEAD changed.
func committedFiles(repo *testsupport.Repo) []string {
	out := repo.Git("diff-tree", "--no-commit-id", "--name-only", "-r", "--root", "HEAD")
	if out == "" {
		return nil
	}
	return strings.Split(out, "\n")
}

func TestPartitionStageable(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	repo.Write(".gitignore", "ignored.txt\n")
	repo.Write("same.txt", "s\n")
	repo.Write("changed.txt", "c\n")
	repo.Write("deleted.txt", "d\n")
	repo.Commit("seed", ".gitignore", "same.txt", "changed.txt", "deleted.txt")
	repo.Write("changed.txt", "c2\n")
	repo.Write("new.txt", "n\n")
	repo.Write("ignored.txt", "i\n")
	if err := os.Remove(repo.Path("deleted.txt")); err != nil {
		t.Fatal(err)
	}
	reading(t, repo.Dir, func(r git.Repo) error {
		stageable, ignored, err := r.PartitionStageable([]string{"same.txt", "new.txt", "ignored.txt", "changed.txt", "deleted.txt", "missing.txt"})
		if err != nil {
			return err
		}
		if !slices.Equal(stageable, []string{"new.txt", "changed.txt", "deleted.txt"}) || !slices.Equal(ignored, []string{"ignored.txt"}) {
			return fmt.Errorf("stageable %q, ignored %q", stageable, ignored)
		}
		return nil
	})
}

// A named path that did not change is left out of the commit, so safegit is
// never asked to stage a no-op.
func TestCommitCarriesOnlyTheChangedPaths(t *testing.T) {
	hygiene.Isolate(t)
	safegit := testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	repo.Write("CHANGELOG.md", "# Changelog\n")
	repo.Write("VERSION", "0.1.0\n")
	repo.Commit("seed", "CHANGELOG.md", "VERSION")
	repo.Write("VERSION", "0.2.0\n")
	_, err := writing(t, repo.Dir, false, func(r git.Repo) error {
		committed, err := r.Commit(git.CommitRequest{Message: "Release 0.2.0", Paths: []string{"CHANGELOG.md", "VERSION"}, Autogenerated: true})
		if err != nil {
			return err
		}
		if !committed {
			return errors.New("a changed path was not committed")
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if files := committedFiles(repo); !slices.Equal(files, []string{"VERSION"}) {
		t.Fatalf("committed %q", files)
	}
	if calls := safegit.Calls(); len(calls) != 1 || calls[0] != "commit --trailer Autogenerated: true -m Release 0.2.0 -- VERSION" {
		t.Fatalf("safegit calls = %q", calls)
	}
	if v := repo.Git("log", "-1", "--format=%(trailers:key=Autogenerated,valueonly)"); v != "true" {
		t.Fatalf("the commit carries no Autogenerated trailer: %q", v)
	}
}

func TestCommitOfUnchangedPathsCommitsNothingOrRefuses(t *testing.T) {
	hygiene.Isolate(t)
	safegit := testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	head := repo.CommitFile("VERSION", "0.1.0\n", "seed")
	_, err := writing(t, repo.Dir, false, func(r git.Repo) error {
		committed, err := r.Commit(git.CommitRequest{Message: "noop", Paths: []string{"VERSION"}})
		if err != nil || committed {
			return fmt.Errorf("committed %v, %v", committed, err)
		}
		_, err = r.Commit(git.CommitRequest{Message: "must change", Paths: []string{"VERSION"}, RequireChange: true})
		if err == nil || !strings.Contains(err.Error(), "did not happen") {
			return fmt.Errorf("a required change that did not happen: %v", err)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if repo.Head() != head || len(safegit.Calls()) != 0 {
		t.Fatal("a commit of unchanged paths ran")
	}
}

func TestCommitRefusesAnIgnoredPathAndBadRequests(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	repo.CommitFile(".gitignore", "build.log\n", "seed")
	repo.Write("build.log", "x\n")
	repo.Write("real.txt", "x\n")
	_, err := writing(t, repo.Dir, false, func(r git.Repo) error {
		_, err := r.Commit(git.CommitRequest{Message: "m", Paths: []string{"real.txt", "build.log"}})
		if err == nil || !strings.Contains(err.Error(), "build.log is untracked and ignored") {
			return fmt.Errorf("an ignored path: %v", err)
		}
		if _, err := r.Commit(git.CommitRequest{Message: " ", Paths: []string{"real.txt"}}); err == nil {
			return errors.New("an empty message was accepted")
		}
		if _, err := r.Commit(git.CommitRequest{Message: "m"}); err == nil {
			return errors.New("a commit naming no path was accepted")
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

// The refusal names the fix (install safegit); installing it clears it.
func TestCommitRefusesAMissingSafegitAndInstallingItClearsTheRefusal(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	repo.CommitFile("a.txt", "a\n", "seed")
	repo.Write("a.txt", "b\n")
	testsupport.PathOnly(t, "git")
	_, err := writing(t, repo.Dir, false, func(r git.Repo) error {
		_, err := r.Commit(git.CommitRequest{Message: "m", Paths: []string{"a.txt"}})
		return err
	})
	if err == nil || !strings.Contains(err.Error(), "safegit is not on PATH") {
		t.Fatalf("err = %v", err)
	}
	testsupport.FakeSafegit(t)
	_, err = writing(t, repo.Dir, false, func(r git.Repo) error {
		_, err := r.Commit(git.CommitRequest{Message: "m", Paths: []string{"a.txt"}})
		return err
	})
	if err != nil {
		t.Fatalf("with safegit installed: %v", err)
	}
}

// A directory that is not the root of its own repository is refused, so a
// commit never lands in an enclosing repository.
func TestCommitRefusesADirectoryThatIsNotARepositoryRoot(t *testing.T) {
	hygiene.Isolate(t)
	safegit := testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	repo.CommitFile("sub/a.txt", "a\n", "seed")
	repo.Write("sub/a.txt", "b\n")
	_, err := writing(t, repo.Path("sub"), false, func(r git.Repo) error {
		_, err := r.Commit(git.CommitRequest{Message: "m", Paths: []string{"a.txt"}})
		return err
	})
	if err == nil || !strings.Contains(err.Error(), "not the root") {
		t.Fatalf("err = %v", err)
	}
	if len(safegit.Calls()) != 0 {
		t.Fatal("safegit ran")
	}
}

// In the detached release checkout the commit is made with git, and a
// deletion the index already carries is committed without an add.
func TestCommitDetachedCommitsWithGitIncludingAStagedDeletion(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	repo.Write("keep.txt", "k\n")
	repo.Write("gone.txt", "g\n")
	head := repo.Commit("seed", "keep.txt", "gone.txt")
	repo.Git("checkout", "-q", "--detach", head)
	repo.Git("rm", "-q", "gone.txt")
	repo.Write("keep.txt", "k2\n")
	testsupport.PathOnly(t, "git")
	_, err := writing(t, repo.Dir, false, func(r git.Repo) error {
		committed, err := r.CommitDetached(git.CommitRequest{Message: "detached", Paths: []string{"keep.txt", "gone.txt"}, Autogenerated: true})
		if err != nil || !committed {
			return fmt.Errorf("committed %v, %v", committed, err)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	files := committedFiles(repo)
	slices.Sort(files)
	if !slices.Equal(files, []string{"gone.txt", "keep.txt"}) {
		t.Fatalf("committed %q", files)
	}
	if v := repo.Git("log", "-1", "--format=%(trailers:key=Autogenerated,valueonly)"); v != "true" {
		t.Fatalf("trailer = %q", v)
	}
}

func TestADryRunRecordsTheCommitInsteadOfCommitting(t *testing.T) {
	hygiene.Isolate(t)
	safegit := testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	head := repo.CommitFile("a.txt", "a\n", "seed")
	repo.Write("a.txt", "b\n")
	res, err := writing(t, repo.Dir, true, func(r git.Repo) error {
		_, err := r.Commit(git.CommitRequest{Message: "m", Paths: []string{"a.txt"}})
		return err
	})
	if err != nil || res.ExitCode != 0 {
		t.Fatalf("exit %d: %v", res.ExitCode, err)
	}
	if repo.Head() != head || len(safegit.Calls()) != 0 {
		t.Fatal("a dry run committed")
	}
}
