package migration

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle/index"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/saferm"
)

// removalDescription is the saferm audit trail of every removal.
const removalDescription = "rlsbl migrate records: the old layout's records, converted into .strictmetadata/ by the same run"

// checkUncommitted refuses an uncommitted change to any path the plan
// writes or removes, naming each, and lists every other uncommitted change,
// which the run leaves alone.
func (b *builder) checkUncommitted() error {
	changed, err := b.repo.ChangedPaths(nil, git.UntrackedAll)
	if err != nil {
		return err
	}
	touched := map[string]bool{}
	for _, p := range b.plan.Paths() {
		touched[p] = true
	}
	var refused []string
	for _, c := range changed {
		hit := touched[c]
		for _, r := range b.plan.removals {
			if c == r.dir || strings.HasPrefix(c, r.dir+"/") {
				hit = true
			}
		}
		if hit {
			refused = append(refused, c)
		} else {
			b.plan.dirty = append(b.plan.dirty, c)
		}
	}
	if len(refused) > 0 {
		return &RefusedError{Problems: []string{fmt.Sprintf("these paths, which the migration writes or removes, have uncommitted changes: %s. Commit or discard them first; the migration commits exactly the paths it writes or removes and must not carry anyone else's change", strings.Join(refused, ", "))}}
	}
	return nil
}

// checkIgnored refuses a path the plan writes and commits that git's ignore
// rules match, naming each with its rule: the commit could not carry it, and
// the old layout would already be removed when the commit refused it.
func (b *builder) checkIgnored() error {
	var paths []string
	for _, w := range b.plan.writes {
		if !w.ignored {
			paths = append(paths, w.path)
		}
	}
	paths = append(paths, b.plan.generated...)
	rules, err := b.repo.IgnoreRules(paths)
	if err != nil {
		return err
	}
	var named []string
	for _, p := range paths {
		if rule, ok := rules[p]; ok {
			named = append(named, fmt.Sprintf("%s (%s)", p, rule))
		}
	}
	if len(named) > 0 {
		return &RefusedError{Problems: []string{fmt.Sprintf("these paths, which the migration writes and commits, are ignored by git, so the commit could not carry them: %s. Hand edit: narrow each ignore rule named so it no longer matches them (anchor it with a leading /, for example), commit that, then migrate", strings.Join(named, ", "))}}
	}
	return nil
}

// effectsWriter is the lifecycle library's writer, backed by the effects
// handle.
type effectsWriter struct {
	e *strictcli.Effects
}

func (w effectsWriter) WriteFile(path string, data []byte) error {
	_, err := w.e.Write(path, data)
	return err
}

func (w effectsWriter) MkdirAll(path string) error {
	_, err := w.e.Mkdir(path)
	return err
}

// Apply performs a plan: it writes every converted record, regenerates the
// changelogs from them, updates the confidential-name index, removes the old
// layout through saferm, and commits exactly the paths it wrote or removed
// with the Autogenerated trailer. It returns what it committed.
func Apply(e *strictcli.Effects, req Request, plan *Plan) (string, error) {
	root := req.Root
	for _, w := range plan.writes {
		if err := writePlanned(e, root, w); err != nil {
			return "", fmt.Errorf("writing %s (nothing is removed or committed yet; the old layout is intact): %w", w.path, err)
		}
	}
	if plan.d != nil {
		for _, r := range plan.d.Releasables {
			if _, err := changelog.Regenerate(e, root, plan.d, r.Name, nil); err != nil {
				return "", fmt.Errorf("regenerating the changelog of %s from the converted records (the old layout is intact): %w", r.Name, err)
			}
		}
	}
	if plan.index != nil {
		idx, err := index.Load(req.IndexPath)
		if err != nil {
			return "", err
		}
		if err := idx.Apply(effectsWriter{e: e}, *plan.index); err != nil {
			return "", fmt.Errorf("updating the confidential-name index %s: %w", req.IndexPath, err)
		}
	}
	for _, r := range plan.removals {
		if err := saferm.Delete(e, root, saferm.Request{Path: r.dir, Description: removalDescription, Recursive: true}); err != nil {
			return "", err
		}
	}
	repo, err := git.Open(e, root)
	if err != nil {
		return "", err
	}
	ignored := map[string]bool{}
	for _, w := range plan.writes {
		if w.ignored {
			ignored[w.path] = true
		}
	}
	var paths []string
	for _, p := range plan.Paths() {
		if !ignored[p] {
			paths = append(paths, p)
		}
	}
	committed, err := repo.Commit(git.CommitRequest{Message: CommitMessage, Paths: paths, Autogenerated: true})
	if err != nil {
		return "", err
	}
	if !committed {
		return "Nothing changed, so nothing was committed.", nil
	}
	return fmt.Sprintf("Committed %q with the Autogenerated trailer, naming only the paths the migration wrote or removed.", CommitMessage), nil
}

// writePlanned writes one planned file atomically: a sibling temporary file
// with the final mode, renamed over the target.
func writePlanned(e *strictcli.Effects, root string, w write) error {
	if w.writer != nil {
		return w.writer(e, root)
	}
	target := filepath.Join(root, filepath.FromSlash(w.path))
	if _, err := e.Mkdir(filepath.Dir(target)); err != nil {
		return err
	}
	temporary := target + ".rlsbl-migrating"
	if _, err := e.Write(temporary, w.data, strictcli.Mode(w.mode)); err != nil {
		return err
	}
	_, err := e.Rename(temporary, target)
	return err
}
