package migration

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle"
	"github.com/stricttools/strictspec/go/lifecycle/index"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/scaffold"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestAStandaloneProjectMigratesAndCommitsOnce(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	r := f.migrate()
	contains(t, r.Stdout, "Committed")

	d, err := declarations.Load(f.repo.Dir)
	if err != nil {
		t.Fatal(err)
	}
	if d.Layout != declarations.LayoutStandalone || len(d.Releasables) != 1 || d.Releasables[0].Name != "portal" || d.Releasables[0].TagFormat != "v{version}" {
		t.Fatalf("declarations: %+v", d)
	}
	if d.Timeouts.PushSeconds != 120 || strings.Join(d.ReleaseBranches, ",") != "main,master" {
		t.Fatalf("repository values: %+v", d)
	}
	root := d.RootMember()
	if len(root.Pipelines) != 1 || root.Pipelines[0].Artifact != declarations.ArtifactPackage {
		t.Fatalf("pipelines: %+v", root.Pipelines)
	}

	unreleased, err := changelog.ReadUnreleased(f.repo.Dir, changelog.Dir("portal"))
	if err != nil {
		t.Fatal(err)
	}
	if len(unreleased.Entries()) != 1 || !isEntryID(unreleased.Entries()[0].ID) {
		t.Fatalf("the unreleased entry: %+v", unreleased.Entries())
	}
	released, err := changelog.ReadVersion(f.repo.Dir, changelog.Dir("portal"), semver.Version{Minor: 1})
	if err != nil {
		t.Fatal(err)
	}
	if released.Entries()[0].ID != someID {
		t.Fatalf("an id the old line carried was replaced: %+v", released.Entries())
	}
	info, err := os.Stat(f.repo.Path(".strictmetadata/changelog/portal/0.1.0.jsonl"))
	if err != nil || info.Mode().Perm() != 0o444 {
		t.Fatalf("the released changelog file: %v %v", info, err)
	}
	archive := f.read(".strictmetadata/releases/portal/v0.1.0.toml")
	contains(t, archive, "format_version = 2")
	contains(t, archive, "release_commit = ")
	contains(t, archive, "[released_trees]")
	lacks(t, archive, "candidate_sha =")

	state, found, err := scaffold.ReadState(f.repo.Dir)
	if err != nil || !found {
		t.Fatalf("the scaffold state: %v %v", found, err)
	}
	if state.RlsblVersion != "0.130.0" || state.Files[".github/workflows/ci.yml"] != someHash || len(state.Files) != 1 {
		t.Fatalf("the scaffold state: %+v", state)
	}
	if f.read(".strictmetadata/.scaffold-bases/.github/workflows/ci.yml") != "name: ci\n" {
		t.Fatal("the merge base was not carried")
	}

	rec, err := lifecycle.Load(f.repo.Dir)
	if err != nil {
		t.Fatal(err)
	}
	if l, ok := rec.LicenseOn("portal", testNow); !ok || l.License != "MIT" {
		t.Fatalf("the license period: %+v %v", l, ok)
	}
	if p, ok := rec.LifecycleOn("portal", testNow); !ok || p.Status != lifecycle.StatusActive {
		t.Fatalf("the lifecycle period: %+v %v", p, ok)
	}
	names := rec.RegistryNames()
	if len(names) != 1 || names[0].Registry != "npm" || names[0].Name != "portal" {
		t.Fatalf("the registry names: %+v", names)
	}
	ids := rec.Identities()
	if len(ids) != 1 || ids[0].Facet != lifecycle.FacetReleasableName || ids[0].Value != "portal" || strings.Join(ids[0].TagPatterns, ",") != "v*" {
		t.Fatalf("the identities: %+v", ids)
	}

	contains(t, f.read("CHANGELOG.md"), "# Changelog")
	contains(t, f.read("CHANGELOG.md"), "The first feature")
	if f.exists(".rlsbl") {
		t.Fatal("the old layout is still there")
	}
	if status := f.repo.Git("status", "--porcelain"); status != "" {
		t.Fatalf("the migration left uncommitted changes:\n%s", status)
	}
	message := f.repo.Git("log", "-1", "--format=%B")
	contains(t, message, CommitMessage)
	contains(t, message, "Autogenerated: true")

	again := f.migrate()
	contains(t, again.Stdout, "already in the .strictmetadata layout")
}

func TestADryRunWritesNothing(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	before := f.repo.Git("status", "--porcelain", "--ignored")
	head := f.repo.Head()
	r := testsupport.RunCommand(t, commandOptions(true), func(ctx *strictcli.Context) error { return Run(ctx, f.request()) })
	if r.ExitCode != 0 {
		t.Fatalf("the dry run exited %d:\n%s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
	contains(t, r.Stdout, "Would write .strictmetadata/releasables/releasables.toml")
	contains(t, r.Stdout, "Would remove .rlsbl through saferm")
	if f.exists(".strictmetadata") || !f.exists(".rlsbl/config.json") {
		t.Fatal("the dry run wrote or removed something")
	}
	if after := f.repo.Git("status", "--porcelain", "--ignored"); after != before || f.repo.Head() != head {
		t.Fatalf("the dry run changed the repository:\n%s\n%s", before, after)
	}
	if _, err := os.Stat(f.indexPath); err == nil {
		t.Fatal("the dry run wrote the confidential-name index")
	}
}

func TestTheCommitCarriesOnlyThePathsTheMigrationTouched(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write("notes.txt", "kept\n")
	f.commit("an unrelated file")
	f.write("notes.txt", "another session's edit\n")
	f.write("draft.txt", "another session's new file\n")
	r := f.migrate()
	contains(t, r.Stdout, "Left alone (uncommitted, not a path the migration touches): notes.txt")
	committed := strings.Split(f.repo.Git("show", "--name-only", "--format=", "HEAD"), "\n")
	for _, p := range committed {
		if p == "notes.txt" || p == "draft.txt" {
			t.Fatalf("the commit carries %s:\n%s", p, strings.Join(committed, "\n"))
		}
		if !strings.HasPrefix(p, ".strictmetadata/") && !strings.HasPrefix(p, ".rlsbl/") && p != "CHANGELOG.md" {
			t.Fatalf("the commit carries %s, which the migration did not write or remove", p)
		}
	}
	sort.Strings(committed)
	for _, want := range []string{".rlsbl/config.json", ".strictmetadata/releasables/releasables.toml", "CHANGELOG.md", ".strictmetadata/lifecycle-and-license/lifecycle-and-license.toml"} {
		if i := sort.SearchStrings(committed, want); i == len(committed) || committed[i] != want {
			t.Fatalf("the commit does not carry %s:\n%s", want, strings.Join(committed, "\n"))
		}
	}
	if status := f.repo.Git("status", "--porcelain"); !strings.Contains(status, "notes.txt") || !strings.Contains(status, "draft.txt") {
		t.Fatalf("the unrelated changes were not left alone:\n%s", status)
	}
	if f.read("notes.txt") != "another session's edit\n" {
		t.Fatal("the unrelated edit was touched")
	}
}

func TestAnUncommittedChangeToAPathTheMigrationWritesRefusesTheRun(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write("CHANGELOG.md", "# Changelog\n\nan edit nobody committed\n")
	f.write(".rlsbl/changes/unreleased.jsonl", `{"format_version":1,"commits":["`+someCommit+`"],"user_facing":false}`+"\n"+`{"format_version":1,"commits":["`+otherSHA+`"],"user_facing":false}`+"\n")
	refusal := f.refused("CHANGELOG.md")
	contains(t, refusal, ".rlsbl/changes/unreleased.jsonl")
	if f.exists(".strictmetadata") {
		t.Fatal("a refused run wrote something")
	}
	f.commit("commit the edits")
	f.mustPlan()
}

func TestEveryConvertedLayoutGetsALifecycleAndLicenseRecord(t *testing.T) {
	hygiene.Isolate(t)
	for name, build := range map[string]func(*testing.T) *fixture{
		"standalone":         standalone,
		"workspace":          workspaceFixture,
		"root-only":          rootOnlyWorkspace,
		"retired":            withClosedHistory,
		"standalone unnamed": standaloneWithoutManifestName,
	} {
		t.Run(name, func(t *testing.T) {
			hygiene.Isolate(t)
			f := build(t)
			plan := f.mustPlan()
			if _, err := lifecycle.Parse([]byte(planned(t, plan, lifecycle.RecordFile))); err != nil {
				t.Fatal(err)
			}
			contains(t, planned(t, plan, lifecycle.ManifestFile), `owner = "strictspec"`)
		})
	}
}

func TestAPrivateRepositoryWithoutAProprietaryReleasableIsRefusedUntilOneIsDeclared(t *testing.T) {
	hygiene.Isolate(t)
	f := newFixture(t, "portal", "private")
	f.write("package.json", `{"name": "portal", "version": "0.1.0", "license": "MIT"}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "none", "targets": ["npm"], "pipelines": {}}`+"\n")
	f.commit("the old layout")
	refusal := f.refused("GitHub reports owner/portal private")
	contains(t, refusal, `portal = "proprietary"`)

	f.licenses = map[string]string{"portal": "proprietary"}
	r := f.migrate()
	contains(t, r.Stdout, "Committed")
	rec, err := lifecycle.Load(f.repo.Dir)
	if err != nil {
		t.Fatal(err)
	}
	if !rec.Confidential(testNow) {
		t.Fatal("the record does not make the repository confidential")
	}
	idx, err := index.Load(f.indexPath)
	if err != nil {
		t.Fatal(err)
	}
	if names := strings.Join(idx.Names(), ","); !strings.Contains(names, "portal") {
		t.Fatalf("the confidential-name index holds %s", names)
	}
}

func TestTheStandaloneNameIsThePythonsAndIsRecorded(t *testing.T) {
	hygiene.Isolate(t)
	t.Run("the first target's package name", func(t *testing.T) {
		hygiene.Isolate(t)
		f := standalone(t)
		plan := f.mustPlan()
		contains(t, planned(t, plan, declarations.ReleasablesFile), `name = "portal"`)
		if !hasNote(plan, `the standalone releasable is named "portal"`) {
			t.Fatalf("no note says where the name came from: %v", plan.notes)
		}
	})
	t.Run("the directory's name without a package name", func(t *testing.T) {
		hygiene.Isolate(t)
		f := standaloneWithoutManifestName(t)
		contains(t, planned(t, f.mustPlan(), declarations.ReleasablesFile), `name = "repo"`)
	})
	t.Run("releasable.toml's name", func(t *testing.T) {
		hygiene.Isolate(t)
		f := standalone(t)
		f.write(".rlsbl/releasable.toml", "name = \"gizmo\"\ntag_format = \"gizmo-v{version}\"\n")
		f.commit("name the releasable")
		text := planned(t, f.mustPlan(), declarations.ReleasablesFile)
		contains(t, text, `name = "gizmo"`)
		contains(t, text, `tag_format = "gizmo-v{version}"`)
	})
}

func TestARemovedTargetIsRefusedUntilTheHandEditRemovesItAndItsPipeline(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write(".rlsbl/config.json", `{"publish_mode": "ci", "targets": ["npm", "zig"], "pipelines": {"npm": {"type": "npm", "target": "npm", "local": false}, "zig": {"type": "zig", "target": "zig", "local": false}}}`+"\n")
	f.commit("a removed target")
	refusal := f.refused(`the target "zig" was removed from rlsbl`)
	contains(t, refusal, "Hand edit: delete \"zig\" from targets")
	f.write(".rlsbl/config.json", `{"publish_mode": "ci", "targets": ["npm"], "pipelines": {"npm": {"type": "npm", "target": "npm", "local": false}}}`+"\n")
	f.commit("the hand edit")
	f.mustPlan()
}

func TestAWorkspaceMigrates(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	plan := f.mustPlan()
	text := planned(t, plan, declarations.ReleasablesFile)
	contains(t, text, `repository_layout = "workspace"`)
	contains(t, text, `tag_format = "{name}@v{version}"`)
	contains(t, text, `depends_on = ["widget"]`)
	if !hasNote(plan, "[layers] section is dropped") || !hasNote(plan, "snapshot.json is deleted") {
		t.Fatalf("notes: %v", plan.notes)
	}
	if planned(t, plan, declarations.VersionFile("widget")) != "0.3.0\n" {
		t.Fatal("the releasable's version file was not carried")
	}
	entries := planned(t, plan, ".strictmetadata/changelog/widget/unreleased.jsonl")
	contains(t, entries, `"packages":["widget"]`)
	contains(t, entries, `"format_version":2`)
	contains(t, planned(t, plan, StrictcodeFile), "[python_tools.lint]")
	code := planned(t, plan, ".strictmetadata/options/code.toml")
	contains(t, code, `id = "strictcode:lint"`)
	contains(t, code, `scope = "gadget"`)
	if strings.Join(plan.generated, ",") != ".strictmetadata/changelog/widget/CHANGELOG.md,.strictmetadata/changelog/gadget/CHANGELOG.md,CHANGELOG.md" {
		t.Fatalf("the regenerated changelogs: %v", plan.generated)
	}
	f.migrate()
	if f.exists(".rlsbl-monorepo") || f.exists("widget/.rlsbl") || f.exists("gadget/.rlsbl") {
		t.Fatal("the old layout is still there")
	}
	contains(t, f.read("CHANGELOG.md"), "## widget")
	contains(t, f.read(".strictmetadata/changelog/widget/CHANGELOG.md"), "A widget feature")
}

// standaloneWithoutManifestName is a standalone project whose config lists
// no targets, so the Python named its releasable after the directory.
func standaloneWithoutManifestName(t *testing.T) *fixture {
	t.Helper()
	f := newFixture(t, "portal", "public")
	f.write("package.json", `{"version": "0.1.0", "license": "MIT"}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "none", "pipelines": {}}`+"\n")
	f.commit("the old layout")
	return f
}

// rootOnlyWorkspace is a workspace whose only member is the root member.
func rootOnlyWorkspace(t *testing.T) *fixture {
	t.Helper()
	f := newFixture(t, "portal", "public")
	f.write(".rlsbl-monorepo/workspace.toml", "[[releasables]]\nname = \"portal\"\ntag_format = \"v{version}\"\n\n[[projects]]\npath = \".\"\nreleasable = \"portal\"\n")
	f.write(".rlsbl-monorepo/releasables/portal/config.json", `{"publish_mode": "none", "targets": ["npm"], "pipelines": {}}`+"\n")
	f.write(".rlsbl-monorepo/releasables/portal/version", "0.2.0\n")
	f.write("package.json", `{"name": "portal", "version": "0.2.0", "license": "MIT"}`+"\n")
	f.commit("the old layout")
	return f
}

func TestAWorkspaceWhoseOnlyMemberIsTheRootStaysAWorkspace(t *testing.T) {
	hygiene.Isolate(t)
	f := rootOnlyWorkspace(t)
	plan := f.mustPlan()
	text := planned(t, plan, declarations.ReleasablesFile)
	contains(t, text, `repository_layout = "workspace"`)
	contains(t, text, `name = "root"`)
	if plan.Layout != declarations.LayoutWorkspace {
		t.Fatalf("layout %s", plan.Layout)
	}
}

func TestMemberConfigsMergeOverTheirReleasablesConfig(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	f.write(".rlsbl-monorepo/releasables/widget/config.json", `{"publish_mode": "ci", "check_timeout": 300, "hooks": {"pre_release": ["make check"]}}`+"\n")
	f.write("widget/.rlsbl/config.json", `{"targets": ["npm"], "pipelines": {"npm": {"type": "npm", "target": "npm", "local": false}}, "hooks": {"post_release": [{"cmd": "make announce", "dir": "docs"}]}, "internal_dep_floors": ["gadget"], "external_checks": [{"name": "docs-build", "`+externalCheckFormKey+`": "freeform", "command": "make docs", "tag": "preflight"}]}`+"\n")
	f.write("widget/docs/README.md", "docs\n")
	f.commit("configs that merge")
	d, err := declarations.Parse([]byte(planned(t, f.mustPlan(), declarations.ReleasablesFile)))
	if err != nil {
		t.Fatal(err)
	}
	widget, _ := d.Member("widget")
	if d.Timeouts.CheckSeconds != 300 || len(widget.Pipelines) != 1 || strings.Join(widget.InternalDepFloors, ",") != "gadget" {
		t.Fatalf("widget: %+v, timeouts %+v", widget, d.Timeouts)
	}
	if len(widget.Hooks.PostRelease) != 1 || widget.Hooks.PostRelease[0].Dir != "docs" || len(widget.ExternalChecks) != 1 {
		t.Fatalf("widget's own declarations: %+v", widget)
	}
	r, _ := d.Releasable("widget")
	if len(r.Hooks.PreRelease) != 1 || r.Hooks.PreRelease[0].Command != "make check" {
		t.Fatalf("the releasable's hooks: %+v", r.Hooks)
	}
}

// withClosedHistory is a workspace whose transition record closes the
// release history of conformance, whose state is still on disk, renames a
// releasable, and records an identity transition not yet released.
func withClosedHistory(t *testing.T) *fixture {
	t.Helper()
	f := workspaceFixture(t)
	f.write(".rlsbl-monorepo/releasables/conformance/version", "0.4.0\n")
	f.write(".rlsbl-monorepo/releasables/conformance/config.json", `{"publish_mode": "ci"}`+"\n")
	f.write(".rlsbl-monorepo/releasables/conformance/changes/0.4.0.jsonl", `{"format_version":1,"commits":["`+someCommit+`"],"user_facing":true,"description":"Cases","type":"feature"}`+"\n")
	f.write(".rlsbl-monorepo/releasables/conformance/releases/v0.4.0.toml", oldArchive(someCommit, otherSHA, "conformance"))
	f.write(".rlsbl-monorepo/transitions.jsonl",
		`{"format_version":1,"`+oldKey+`":"release-history-closed","id":"a1","recorded_at":"2026-09-05T14:11:39+02:00","subject":"conformance","reason":"the suite stopped versioning separately"}`+"\n"+
			`{"format_version":1,"`+oldKey+`":"releasable-rename","id":"a2","recorded_at":"2026-09-24T17:24:37+02:00","old_name":"gizmo","new_name":"gadget","reason":"renamed"}`+"\n"+
			`{"format_version":1,"`+oldKey+`":"non-version-tag","id":"a3","recorded_at":"2026-09-25T10:00:00+02:00","tag":"nightly","reason":"a moving tag"}`+"\n")
	f.write(".rlsbl-monorepo/releasables/widget/transitions.jsonl",
		`{"format_version":1,"`+oldKey+`":"identity-transition","id":"b1","recorded_at":"2026-09-30T10:00:00+02:00","facet":"package-name","old":"widget","new":"widget-client","effective_version":"0.4.0"}`+"\n"+
			`{"format_version":1,"`+oldKey+`":"boundary-alias","id":"b2","recorded_at":"2026-09-30T11:00:00+02:00","aliases":[{"alias_tag":"widget@v0.3.0","aliased_tag":"gizmo@v0.3.0","commit":"`+someCommit+`"}]}`+"\n")
	f.commit("transitions")
	return f
}

func TestTransitionsSplitBetweenTheRecordsAndAClosedHistoryRetires(t *testing.T) {
	hygiene.Isolate(t)
	f := withClosedHistory(t)
	plan := f.mustPlan()
	surgery := planned(t, plan, declarations.TransitionsFile)
	contains(t, surgery, `"event":"boundary-alias"`)
	contains(t, surgery, `"releasable":"widget"`)
	lacks(t, surgery, oldKey)
	lacks(t, surgery, "identity-transition")
	lacks(t, surgery, "release-history-closed")

	if planned(t, plan, ".strictmetadata/retired-release-histories/conformance/releases/version") != "0.4.0\n" {
		t.Fatal("the retired subject's version was not moved")
	}
	contains(t, planned(t, plan, ".strictmetadata/retired-release-histories/conformance/changelog/0.4.0.jsonl"), `"format_version":2`)
	contains(t, planned(t, plan, ".strictmetadata/retired-release-histories/conformance/releases/v0.4.0.toml"), "release_commit")
	contains(t, planned(t, plan, ".strictmetadata/retired-release-histories/conformance/config.json"), `"publish_mode": "ci"`)

	rec, err := lifecycle.Parse([]byte(planned(t, plan, lifecycle.RecordFile)))
	if err != nil {
		t.Fatal(err)
	}
	if p, ok := rec.LifecycleOn("conformance", testNow); !ok || p.Status != lifecycle.StatusRetired {
		t.Fatalf("conformance: %+v %v", p, ok)
	}
	var gizmo, gadget, pending bool
	for _, id := range rec.Identities() {
		switch {
		case id.Subject == "gadget" && id.Value == "gizmo" && !id.Open():
			gizmo = true
		case id.Subject == "gadget" && id.Value == "gadget" && id.Open():
			gadget = true
		case id.Subject == "widget" && id.Value == "widget-client" && id.Pending() && id.EffectiveVersion == "0.4.0":
			pending = true
		}
	}
	if !gizmo || !gadget || !pending {
		t.Fatalf("the identities: %+v", rec.Identities())
	}
	tags := rec.UnversionedTags()
	if len(tags) != 1 || tags[0].Tag != "nightly" {
		t.Fatalf("the unversioned tags: %+v", tags)
	}
}

func TestCustomizedHookScriptsMoveAndAreDeclared(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	f.write(".rlsbl-monorepo/releasables/widget/hooks/pre-release.sh", "#!/usr/bin/env bash\nmake verify\n")
	f.write("gadget/.rlsbl/hooks/post-release.sh", "#!/usr/bin/env bash\n./announce\n")
	f.write("gadget/.rlsbl/hooks/pre-checks.sh", shippedPreChecks)
	f.commit("hook scripts")
	plan := f.mustPlan()
	if planned(t, plan, ".strictmetadata/release-hooks/widget/pre-release.sh") != "#!/usr/bin/env bash\nmake verify\n" {
		t.Fatal("the releasable's script was not moved")
	}
	if writes(plan, ".strictmetadata/release-hooks/gadget/pre-checks.sh") {
		t.Fatal("a shipped script was moved instead of deleted")
	}
	d, err := declarations.Parse([]byte(planned(t, plan, declarations.ReleasablesFile)))
	if err != nil {
		t.Fatal(err)
	}
	r, _ := d.Releasable("widget")
	if len(r.Hooks.PreRelease) != 1 || r.Hooks.PreRelease[0].Command != "bash ../.strictmetadata/release-hooks/widget/pre-release.sh" {
		t.Fatalf("the releasable's hooks: %+v", r.Hooks)
	}
	gadget, _ := d.Member("gadget")
	if len(gadget.Hooks.PostRelease) != 1 || gadget.Hooks.PostRelease[0].Command != "bash ../.strictmetadata/release-hooks/gadget/post-release.sh" {
		t.Fatalf("the member's hooks: %+v", gadget.Hooks)
	}
}

func TestDeadModulesBecomeStrictcodeSuppressions(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	f.write("gadget/.rlsbl/dead-modules.toml", "[[known_non_entry]]\npath = \"hatch_build.py\"\nreason = \"the build backend imports it\"\n")
	f.commit("dead modules")
	text := planned(t, f.mustPlan(), StrictcodeFile)
	contains(t, text, "[[rules.dead-modules.suppressions]]")
	contains(t, text, `path = "gadget/hatch_build.py"`)
	contains(t, text, `reason = "the build backend imports it"`)
}

func TestEntriesWithoutAnIdGetOneMintedAndExclusionsBecomeBatchReasons(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	commits := `"a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1","b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2","c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3","d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4","e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5","f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6"`
	f.write(".rlsbl/changes/unreleased.jsonl",
		`{"commits":["`+someCommit+`"],"user_facing":false}`+"\n"+
			`{"format_version":1,"id":"0123456789abcdef0123456789abcdef","commits":[`+commits+`],"user_facing":false}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "ci", "targets": ["npm"], "pipelines": {"npm": {"type": "npm", "target": "npm", "local": false}}, "batch_limits": {"max_commits_per_entry": 5, "exclusions": [{"reason": "one feature in six commits", "entries": [{"version": "unreleased", "line": 2}]}, {"reason": "gone", "entries": [{"version": "unreleased", "line": 9}]}]}}`+"\n")
	f.commit("entries without ids")
	plan := f.mustPlan()
	lines := strings.Split(strings.TrimSpace(planned(t, plan, ".strictmetadata/changelog/portal/unreleased.jsonl")), "\n")
	if len(lines) != 2 {
		t.Fatalf("lines: %v", lines)
	}
	for _, line := range lines {
		e, err := changelog.ParseLine(line)
		if err != nil {
			t.Fatal(err)
		}
		if !isEntryID(e.ID) || e.ID == "0123456789abcdef0123456789abcdef" {
			t.Fatalf("the entry kept no valid id: %s", line)
		}
	}
	contains(t, lines[1], `"batch_reason":"one feature in six commits"`)
	if !hasNote(plan, "2 entries carried no id") || !hasNote(plan, "line 9 of unreleased.jsonl is dropped") || !hasNote(plan, "max_commits_per_entry is dropped") {
		t.Fatalf("notes: %v", plan.notes)
	}
}

func TestTheOptionsMoveToTheirNewHomes(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write(".strictmetadata/options/manifest.toml", "owner = \"strictspec\"\n")
	f.write(".strictmetadata/options/code.toml", "format_version = 1\n\n[[entry]]\nid = \"rlsbl:lint\"\ncurrent = \"error\"\nideal = \"error\"\nreason = \"clean\"\n")
	f.write(".strictmetadata/options/dependencies.toml", "format_version = 1\n\n[[entry]]\nid = \"rlsbl:deps-unused\"\ncurrent = \"warn\"\nideal = \"error\"\nreason = \"later\"\n")
	f.write(".strictmetadata/options/changelog.toml", "format_version = 1\n\n[[entry]]\nid = \"rlsbl:changelog-format-version-gate\"\ncurrent = \"warn\"\nideal = \"error\"\nreason = \"later\"\n")
	f.write(".strictmetadata/options/tests.toml", "format_version = 1\n\n[[entry]]\nid = \"rlsbl:test-sandbox\"\ncurrent = \"on\"\nideal = \"on\"\nreason = \"sandboxed\"\n")
	f.edit(".rlsbl/config.json", `"push_timeout": 120,`, `"push_timeout": 120, "tag": false, "checks": {"lint": {"paths": ["src", "tests"]}}, "test_sandbox": {"runner_path": "scripts/test.sh", "command": "uv run pytest", "caches": ["uv"]},`)
	f.commit("options")
	plan := f.mustPlan()
	contains(t, planned(t, plan, ".strictmetadata/options/code.toml"), `id = "strictcode:lint"`)
	contains(t, planned(t, plan, ".strictmetadata/options/dependencies.toml"), `id = "strictcode:deps-unused"`)
	contains(t, planned(t, plan, ".strictmetadata/options/changelog.toml"), `id = "rlsbl:changelog-format-version"`)
	contains(t, planned(t, plan, ".strictmetadata/options/project.toml"), `id = "rlsbl:ecosystem-tagging"`)
	if writes(plan, ".strictmetadata/options/tests.toml") {
		t.Fatal("an entry of a kept option was rewritten")
	}
	tools := planned(t, plan, StrictcodeFile)
	contains(t, tools, "[python_tools.lint]")
	contains(t, tools, `paths = ["src", "tests"]`)
	runner := planned(t, plan, declarations.TestRunnerFile)
	contains(t, runner, `runner_path = "scripts/test.sh"`)
	if _, err := declarations.ParseTestRunner([]byte(runner)); err != nil {
		t.Fatal(err)
	}
}

func TestThePrivateModuleStubMovesIntoStrictmetadata(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	stub, err := scaffold.PrivateModuleStub()
	if err != nil {
		t.Fatal(err)
	}
	f.write(".rlsbl/go.mod", stub)
	f.commit("the old stub")
	if planned(t, f.mustPlan(), declarations.PrivateModuleFile) != stub {
		t.Fatal("the stub was not written into .strictmetadata/")
	}
}

func TestBatchReleaseFilesAndUndoAuditsConvert(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	f.write(".rlsbl-monorepo/releases/unreleased.toml", "[releasables.widget]\nbump = \"minor\"\ndescription = \"More widgets\"\ninclude = [\"npm\"]\nexclude = []\n")
	f.write(".rlsbl-monorepo/releases/batch-20260924-173247.toml", "[packages.widget]\nbump = \"patch\"\ndescription = \"Fixes\"\ninclude = [\"npm\"]\nexclude = []\n")
	f.write(".rlsbl-monorepo/releases/batch-20260924-173247.plan.json", "{}\n")
	f.write(".rlsbl-monorepo/releases/unreleased.plan.json", `{"items": [{"base_version": "0.3.0", "bump": "minor", "name": "widget", "registry": "npm", "tag": "widget@v0.4.0", "target_version": "0.4.0"}], "section_type": "releasables"}`+"\n")
	f.write(".rlsbl-monorepo/releasables/widget/undo-audit.json", `[{"version": "0.2.0", "tag": "widget@v0.2.0", "verdict": "cleared"}]`+"\n")
	f.commit("batch files")
	plan := f.mustPlan()
	contains(t, planned(t, plan, ".strictmetadata/batch-releases/unreleased.toml"), "format_version = 2")
	var archive string
	for _, w := range plan.writes {
		if strings.HasPrefix(w.path, ".strictmetadata/batch-releases/batch-") {
			archive = string(w.data)
		}
	}
	contains(t, archive, "[releasables.widget]")
	lacks(t, archive, "[packages")
	contains(t, planned(t, plan, ".strictmetadata/.release-state/batch-plan.toml"), `tag = "widget@v0.4.0"`)
	contains(t, planned(t, plan, ".strictmetadata/.release-state/.gitignore"), "!.gitignore")
	contains(t, planned(t, plan, ".strictmetadata/releases/widget/undo-audits.jsonl"), `{"format_version":1,"version":"0.2.0","tag":"widget@v0.2.0","verdict":"cleared"}`)
}

func TestAnUnrecognizedFileOfTheOldLayoutIsRefusedUntilRemoved(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write(".rlsbl/notes.txt", "what is this\n")
	f.commit("a stray file")
	f.refused(".rlsbl/notes.txt is a file of the old layout the migration does not recognize")
	f.remove(".rlsbl/notes.txt")
	f.commit("remove it")
	f.mustPlan()
}

func TestAMissingLicenseIsRefusedUntilTheLicensesFileDeclaresIt(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write("package.json", `{"name": "portal", "version": "0.1.0"}`+"\n")
	f.commit("no license")
	f.refused("no license can be read from the manifests of portal")
	file := filepath.Join(t.TempDir(), "licenses.toml")
	if err := os.WriteFile(file, []byte("portal = \"Apache-2.0\"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	licenses, err := ReadLicenses(file)
	if err != nil {
		t.Fatal(err)
	}
	f.licenses = licenses
	contains(t, planned(t, f.mustPlan(), lifecycle.RecordFile), `license = "Apache-2.0"`)
}

func TestAnInProgressReleaseIsRefused(t *testing.T) {
	hygiene.Isolate(t)
	f := standalone(t)
	f.write(".rlsbl/releases/in-progress.json", "{}\n")
	f.commit("a release in progress")
	f.refused("records a release in progress")
}

func TestDisagreeingTimeoutsAreRefusedListingTheValues(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	f.write(".rlsbl-monorepo/releasables/widget/config.json", `{"publish_mode": "ci", "push_timeout": 60}`+"\n")
	f.write(".rlsbl-monorepo/releasables/gadget/config.json", `{"publish_mode": "ci", "push_timeout": 90}`+"\n")
	f.commit("disagreeing timeouts")
	refusal := f.refused("disagree on push_timeout")
	contains(t, refusal, "60 in .rlsbl-monorepo/releasables/widget/config.json")
	contains(t, refusal, "90 in .rlsbl-monorepo/releasables/gadget/config.json")
}

func TestDisagreeingPublishModesWithinAReleasableAreRefused(t *testing.T) {
	hygiene.Isolate(t)
	f := workspaceFixture(t)
	f.write(".rlsbl-monorepo/releasables/widget/config.json", `{"publish_mode": "none"}`+"\n")
	f.commit("disagreeing publish modes")
	f.refused("disagree on publish_mode")
}

func TestAConfidentialRepositoryWithoutAnOriginIsRefusedUntilOneIsAdded(t *testing.T) {
	hygiene.Isolate(t)
	f := newFixture(t, "portal", "private")
	f.repo.Git("remote", "remove", "origin")
	f.write("package.json", `{"name": "portal", "version": "0.1.0", "license": "MIT"}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "none", "targets": ["npm"], "pipelines": {}, "github_repo": "owner/portal"}`+"\n")
	f.commit("the old layout")
	f.licenses = map[string]string{"portal": "proprietary"}
	contains(t, f.refused("origin remote"), "git remote add origin")

	f.repo.Git("remote", "add", "origin", "git@github.com:owner/portal.git")
	f.migrate()
	idx, err := index.Load(f.indexPath)
	if err != nil {
		t.Fatal(err)
	}
	if entries := idx.Entries(); len(entries) != 1 || entries[0].Origin != "github.com/owner/portal" {
		t.Fatalf("the confidential-name index entries: %+v", entries)
	}
}

func TestAPublicRepositoryWithoutAnOriginHasNoIndexEntryToRemove(t *testing.T) {
	hygiene.Isolate(t)
	f := newFixture(t, "portal", "public")
	f.repo.Git("remote", "remove", "origin")
	f.write("package.json", `{"name": "portal", "version": "0.1.0", "license": "MIT"}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "none", "targets": ["npm"], "pipelines": {}, "github_repo": "owner/portal"}`+"\n")
	f.commit("the old layout")
	if plan := f.mustPlan(); plan.index != nil {
		t.Fatalf("the plan changes the index under a synthesized origin: %+v", plan.index)
	}
}

func TestARepositoryNamingNoGitHubRepositoryIsRefusedUntilTheOriginIsAdded(t *testing.T) {
	hygiene.Isolate(t)
	f := newFixture(t, "portal", "public")
	f.repo.Git("remote", "remove", "origin")
	f.write("package.json", `{"name": "portal", "version": "0.1.0", "license": "MIT"}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "none", "targets": ["npm"], "pipelines": {}}`+"\n")
	f.commit("the old layout")
	f.refused("Add the origin remote, then migrate")

	f.repo.Git("remote", "add", "origin", "git@github.com:owner/portal.git")
	f.mustPlan()
}

// retiredAfterPublishing is a workspace in which conformance was a
// releasable publishing @acme/conformance to npm from CI, released 0.4.0
// with the archive archive gives the release commit, and then had its
// release history closed and its member removed.
func retiredAfterPublishing(t *testing.T, archive func(releaseCommit string) string) *fixture {
	t.Helper()
	f := workspaceFixture(t)
	workspaceToml := f.read(".rlsbl-monorepo/workspace.toml")
	f.edit(".rlsbl-monorepo/workspace.toml", "[layers]", "[[releasables]]\nname = \"conformance\"\n\n[[projects]]\npath = \"conformance\"\nname = \"conformance\"\nreleasable = \"conformance\"\n\n[layers]")
	f.write(".rlsbl-monorepo/releasables/conformance/config.json", `{"publish_mode": "ci"}`+"\n")
	f.write("conformance/.rlsbl/config.json", `{"targets": ["npm"], "pipelines": {"npm": {"type": "npm", "target": "npm", "local": false}}}`+"\n")
	f.write("conformance/package.json", `{"name": "@acme/conformance", "version": "0.4.0", "license": "MIT"}`+"\n")
	releaseCommit := f.commit("conformance releases 0.4.0")
	f.write(".rlsbl-monorepo/workspace.toml", workspaceToml)
	f.remove("conformance")
	f.write(".rlsbl-monorepo/releasables/conformance/version", "0.4.0\n")
	f.write(".rlsbl-monorepo/releasables/conformance/releases/v0.4.0.toml", archive(releaseCommit))
	f.write(".rlsbl-monorepo/transitions.jsonl", eventLine("release-history-closed", `"subject":"conformance","reason":"the suite stopped versioning separately"`))
	f.commit("conformance retires")
	return f
}

func TestARetiredSubjectThatPublishedKeepsItsRegistryNames(t *testing.T) {
	hygiene.Isolate(t)
	f := retiredAfterPublishing(t, func(c string) string { return oldArchive(c, otherSHA, "conformance") })
	rec, err := lifecycle.Parse([]byte(planned(t, f.mustPlan(), lifecycle.RecordFile)))
	if err != nil {
		t.Fatal(err)
	}
	for _, n := range rec.RegistryNames() {
		if n.Registry == "npm" && n.Name == "@acme/conformance" && n.Subject == "conformance" {
			return
		}
	}
	t.Fatalf("the retired subject's registry name was dropped: %+v", rec.RegistryNames())
}

func TestARetiredSubjectWhoseReleasesRecordNoCommitIsRefusedUntilOneIsRestored(t *testing.T) {
	hygiene.Isolate(t)
	var releaseCommit string
	f := retiredAfterPublishing(t, func(c string) string {
		releaseCommit = c
		return "format_version = 1\nbump = \"minor\"\ndescription = \"Cases\"\ninclude = [\"npm\"]\nexclude = []\nunrecoverable = true\n"
	})
	contains(t, f.refused(`the retired subject "conformance" released`), "rlsbl release backfill")

	// The fix: the release commit is restored to the archive.
	f.write(".rlsbl-monorepo/releasables/conformance/releases/v0.4.0.toml", oldArchive(releaseCommit, otherSHA, "conformance"))
	f.commit("the release commit restored")
	f.mustPlan()
}

func TestAnIdentityBeginsAtTheEarliestCommitterDateWhereverItSitsInTheHistory(t *testing.T) {
	hygiene.Isolate(t)
	f := newFixture(t, "portal", "public")
	for _, date := range []string{"2026-03-01T12:00:00Z", "2026-01-01T12:00:00Z"} {
		t.Setenv("GIT_COMMITTER_DATE", date)
		f.commit("a commit dated " + date)
	}
	t.Setenv("GIT_COMMITTER_DATE", "2026-05-01T12:00:00Z")
	f.write("package.json", `{"name": "portal", "version": "0.1.0", "license": "MIT"}`+"\n")
	f.write(".rlsbl/config.json", `{"publish_mode": "none", "targets": ["npm"], "pipelines": {}}`+"\n")
	f.commit("the old layout")
	rec, err := lifecycle.Parse([]byte(planned(t, f.mustPlan(), lifecycle.RecordFile)))
	if err != nil {
		t.Fatal(err)
	}
	for _, id := range rec.Identities() {
		if id.Subject == "portal" && id.Facet == lifecycle.FacetReleasableName {
			if got := id.From.Format("2006-01-02"); got != "2026-01-01" {
				t.Fatalf("the identity begins %s, not at the earliest committer date 2026-01-01", got)
			}
			return
		}
	}
	t.Fatalf("no releasable-name identity for portal: %+v", rec.Identities())
}
