// Package options is rlsbl's side of the options model: the registry of the
// options rlsbl offers, a repository's entries for them under
// .strictmetadata/options/, the value each option has for one member, the
// check values the check framework runs with, the agreement between an
// adoption option and the declaration it governs, and the writer behind
// `rlsbl options set`.
//
// Every rlsbl check is an option, rlsbl:<check name>, and a few options are
// not checks. A repository deviates from an option's default only by filing
// an entry; strictspec validates the entries' shape and every rule of the
// options model, and rlsbl adds the rule of its own scope type: a path scope
// names a workspace member by its path.
//
// Loading refuses on any diagnostic (a document strictspec cannot read, an
// entry of rlsbl's namespace strictspec refuses, a scope naming no member),
// so every check run and every release stops on invalid entries rather than
// running with some of them.
package options

import (
	_ "embed"
	"fmt"
	"strings"
	"sync"

	"github.com/stricttools/strictspec/go/strictspec"
)

// The namespace of rlsbl's options.
const (
	// Tool is the tool name of rlsbl's options namespace.
	Tool = "rlsbl"
	// Prefix starts every option id of the namespace.
	Prefix = Tool + ":"
)

// The values and scopes the options model gives meaning to.
const (
	// Off switches an option off.
	Off = "off"
	// PathScope is the scope of an option a workspace may set for one
	// member: an entry's scope names the member's path.
	PathScope = "path"
	// NoScope is the scope of an option that takes none.
	NoScope = "none"
)

// registryDocument is internal/options/registry.toml, generated by
// internal/options/gen from internal/checks/checks.toml.
//
//go:embed registry.toml
var registryDocument []byte

// Registry is an options registry strictspec accepted: every option's
// declaration and ranking.
type Registry struct {
	document []byte
	checked  *strictspec.CheckedOptionsRegistry
}

// ParseRegistry reads an options registry document and applies the registry
// rules. A document strictspec refuses is an error listing every diagnostic.
func ParseRegistry(document []byte) (*Registry, error) {
	reg, diags := strictspec.ReadOptionsRegistry(document)
	if len(diags) == 0 {
		var checked *strictspec.CheckedOptionsRegistry
		checked, diags = strictspec.ValidateOptionsRegistry(reg)
		if len(diags) == 0 {
			return &Registry{document: append([]byte(nil), document...), checked: checked}, nil
		}
	}
	lines := make([]string, 0, len(diags))
	for _, d := range diags {
		lines = append(lines, fmt.Sprintf("%s at %s: %s", d.Code, d.Path, d.Message))
	}
	return nil, fmt.Errorf("the options registry is refused by strictspec:\n  %s", strings.Join(lines, "\n  "))
}

var (
	shippedOnce sync.Once
	shipped     *Registry
	shippedErr  error
)

// Shipped is the registry rlsbl ships. A shipped registry strictspec refuses
// is a defect of rlsbl, never a repository's condition; the error says so.
func Shipped() (*Registry, error) {
	shippedOnce.Do(func() {
		shipped, shippedErr = ParseRegistry(registryDocument)
		if shippedErr != nil {
			shippedErr = fmt.Errorf("rlsbl's shipped options registry (internal/options/registry.toml) is invalid, a defect of this rlsbl build: %w", shippedErr)
		}
	})
	return shipped, shippedErr
}

// Document is the registry document, byte for byte.
func (r *Registry) Document() []byte { return append([]byte(nil), r.document...) }

// Names are the registry's option names, without the prefix, in
// declaration order.
func (r *Registry) Names() []string { return r.checked.Names() }

// Declaration is the declaration of rlsbl's option name (without the
// prefix), and false when the registry declares none.
func (r *Registry) Declaration(name string) (strictspec.OptionDeclaration, bool) {
	o, ok := r.checked.Option(name)
	return o.Declaration, ok
}

// Strongest is the strongest value the declared option name ranks ("error",
// or "on").
func (r *Registry) Strongest(name string) string {
	o, ok := r.checked.Option(name)
	if !ok || len(o.Ranking.Values) == 0 {
		return ""
	}
	return o.Ranking.Values[0]
}

// checkedRegistry is the strictspec form the namespace validator takes.
func (r *Registry) checkedRegistry() *strictspec.CheckedOptionsRegistry { return r.checked }
