"""Integration tests for the release flow against a real git repo.

Uses a real git repository with minimal mocking: only `gh` CLI calls and
`git push` / `git fetch` are intercepted. Everything else (git operations,
changelog validation, version bumping) runs for real.

Follows the pattern from test_release_finalize_md.py.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


def _rc(bump="patch", include=None, exclude=None):
    """Shorthand for creating a ReleaseConfig with sensible defaults."""
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_output(repo, *args):
    result = subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _git_head(repo):
    return _git_output(repo, "rev-parse", "HEAD")


def _setup_releasable_npm_project(repo):
    """Create an npm project at v1.0.0 with one unreleased commit, ready to release.

    Returns the SHA of the unreleased feature commit.
    """
    # package.json at v1.0.0
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )

    # CHANGELOG.md with 1.0.0 section
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ — do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )

    # .rlsbl scaffolding
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"private": False}) + "\n"
    )

    _git(repo, "add",
         "package.json",
         "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl",
         ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    # Make an unreleased feature commit
    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    # Cover it with a JSONL entry (with Autogenerated trailer to self-exempt)
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(
        repo, "commit", "-q", "-m", "changelog: add feature entry",
        "--trailer", "Autogenerated: true",
    )

    # Create the release file
    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "unreleased.toml").write_text(
        'bump = "patch"\ninclude = ["npm"]\nexclude = []\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")

    return feature_sha


def _make_ctx(repo):
    """Build a ProjectContext pointing at repo."""
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config={"private": False, "pipelines": {}},
    )


def _fake_run_factory():
    """Create a fake_run that intercepts gh/push/fetch, passes everything else through."""
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


class TestReleaseDryRunFullFlow:
    """Test 1: dry-run release prints expected version without modifying files."""

    def test_release_dry_run_full_flow(self, mock_git_repo, capsys):
        _setup_releasable_npm_project(mock_git_repo)

        # Snapshot file state before dry-run
        pkg_before = (mock_git_repo / "package.json").read_text()
        changelog_before = (mock_git_repo / "CHANGELOG.md").read_text()
        jsonl_before = (mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl").read_text()

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
        ):
            run_cmd(
                _rc(),
                {"dry-run": True, "yes": True, "quiet": False},
                ctx=_make_ctx(mock_git_repo),
            )

        captured = capsys.readouterr()

        # Dry-run should print the target version
        assert "1.0.1" in captured.out, (
            f"Expected '1.0.1' in dry-run output, got:\n{captured.out}"
        )

        # Release-relevant files should not be modified
        assert (mock_git_repo / "package.json").read_text() == pkg_before
        assert (mock_git_repo / "CHANGELOG.md").read_text() == changelog_before
        assert (mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl").read_text() == jsonl_before

        # No new tags
        tags = _git_output(mock_git_repo, "tag", "-l", "v1.0.1")
        assert tags == "", "Dry-run should not create a tag"


class TestReleaseFullFlowRealGit:
    """Test 2: full release with real git, intercepting only gh/push/fetch."""

    def test_release_full_flow_real_git(self, mock_git_repo):
        _setup_releasable_npm_project(mock_git_repo)

        fake_run = _fake_run_factory()

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
        ):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # 1. package.json has version 1.0.1
        pkg = json.loads((mock_git_repo / "package.json").read_text())
        assert pkg["version"] == "1.0.1", f"Expected version 1.0.1, got {pkg['version']}"

        # 2. git tag v1.0.1 exists
        tag_output = _git_output(mock_git_repo, "tag", "-l", "v1.0.1")
        assert "v1.0.1" in tag_output, "Tag v1.0.1 should exist"

        # 3. CHANGELOG.md contains ## 1.0.1
        changelog = (mock_git_repo / "CHANGELOG.md").read_text()
        assert "## 1.0.1" in changelog, (
            f"CHANGELOG.md should contain '## 1.0.1', got:\n{changelog}"
        )

        # 4. .rlsbl/changes/1.0.1.jsonl exists
        assert (mock_git_repo / ".rlsbl" / "changes" / "1.0.1.jsonl").exists(), (
            "Finalized JSONL file 1.0.1.jsonl should exist"
        )

        # 5. unreleased.jsonl exists and is empty (fresh)
        unreleased = mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl"
        assert unreleased.exists(), "unreleased.jsonl should exist after release"
        assert unreleased.read_text().strip() == "", (
            "unreleased.jsonl should be empty after release"
        )

        # 6. Working tree is clean
        status = _git_output(mock_git_repo, "status", "--porcelain")
        # The advisory lock file may be present; filter it out
        dirty = [
            line for line in status.splitlines()
            if line.strip() and "lock" not in line
        ]
        assert dirty == [], f"Working tree should be clean, got: {dirty}"


class TestReleaseVpathRelativePaths:
    """Test 3: verify that files_to_commit uses relative paths (not absolute)."""

    def test_release_vpath_produces_relative_paths(self, mock_git_repo):
        _setup_releasable_npm_project(mock_git_repo)

        fake_run = _fake_run_factory()

        # Track all commit_files calls to inspect the paths
        committed_file_lists = []
        original_commit_files = None

        # We need to import the real commit_files to capture and delegate
        from rlsbl.utils import commit_files as real_commit_files
        original_commit_files = real_commit_files

        def capturing_commit_files(message, files, allow_failure=False, autogenerated=True, cwd=None):
            committed_file_lists.append(list(files))
            return original_commit_files(message, files, allow_failure=allow_failure, autogenerated=autogenerated, cwd=cwd)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.commit_files", side_effect=capturing_commit_files),
        ):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # Verify we captured some commit calls
        assert len(committed_file_lists) > 0, "Expected at least one commit_files call"

        # The first commit is the version-bump commit (files_to_commit built
        # via vpath()). All its paths must be relative to the git root --
        # absolute paths would have been the vpath bug.
        version_bump_files = committed_file_lists[0]
        assert len(version_bump_files) > 0, "Version bump commit should include files"
        for fpath in version_bump_files:
            assert not os.path.isabs(fpath), (
                f"Version-bump commit contains absolute path: {fpath}\n"
                f"Full list: {version_bump_files}\n"
                "vpath() should produce paths relative to the git root."
            )
