"""A release whose lockfile re-lock fails stops before anything is pushed.

After the version bump the release re-locks each lockfile (``npm install
--package-lock-only`` for package-lock.json, ``uv lock`` for uv.lock) so the
release commit carries a lockfile that matches it. A failed re-lock used to be
a warning, and the release went on to push a candidate with a stale lockfile.
It is a refusal now: nothing is pushed or tagged, the refusal names the fix for
the cause the tool printed, and once the fix is in, re-running the release
ships it.

Real git and the real release flow; npm and uv are stand-ins on PATH that
print what the real tools print for each cause (an unreachable registry, a
required version the registry never published), so no registry is contacted.
Only gh is stubbed; the remote is a bare repository.
"""

import json
import os
import subprocess
from unittest.mock import patch

import pytest

from githarness import add_remote, git, init_repo, record_release

from rlsbl import app

# What the real tools print, captured from npm 10 and uv 0.9.
NPM_UNREACHABLE = """\
npm error code ECONNREFUSED
npm error syscall connect
npm error errno ECONNREFUSED
npm error FetchError: request to http://127.0.0.1:9/sib failed, reason: connect ECONNREFUSED 127.0.0.1:9
"""
NPM_UNPUBLISHED = """\
npm error code ETARGET
npm error notarget No matching version found for sib@0.3.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
"""
UV_UNREACHABLE = """\
error: Failed to fetch: `http://127.0.0.1:9/simple/sib/`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (http://127.0.0.1:9/simple/sib/)
  Caused by: client error (Connect)
  Caused by: tcp connect error
  Caused by: Connection refused (os error 111)
"""
UV_UNPUBLISHED = """\
  x No solution found when resolving dependencies:
  `-> Because there is no version of sib==0.3.0 and your project depends
      on sib==0.3.0, we can conclude that your project's requirements are
      unsatisfiable.
"""
UV_LOCK = """\
version = 1
requires-python = ">=3.11"

[[package]]
name = "app"
version = "1.0.0"
source = { editable = "." }
dependencies = [{ name = "sib" }]

[package.metadata]
requires-dist = [{ name = "sib", specifier = "==0.3.0" }]

[package.metadata.requires-dev]
dev = [{ name = "pytest" }]

[[package]]
name = "sib"
version = "0.3.0"
source = { registry = "https://pypi.org/simple" }
"""
OTHER_FAILURE = "error: the lockfile is locked by another process\n"

ECOSYSTEMS = {
    "npm": {
        "tool": "npm", "relock": "--package-lock-only", "lockfile": "package-lock.json",
        "unreachable": NPM_UNREACHABLE, "unpublished": NPM_UNPUBLISHED,
    },
    "pypi": {
        "tool": "uv", "relock": "lock", "lockfile": "uv.lock",
        "unreachable": UV_UNREACHABLE, "unpublished": UV_UNPUBLISHED,
    },
}


class World:
    """The registry the stand-in tool sees: reachable or not, what is published."""

    def __init__(self, root):
        self.root = root
        root.mkdir()
        (root / "published").write_text("")

    def offline(self, on=True):
        self._marker("offline", on)

    def slow(self, on=True):
        self._marker("slow", on)

    def broken(self, on=True):
        self._marker("broken", on)

    def publish(self, spec):
        with open(self.root / "published", "a") as f:
            f.write(spec + "\n")

    def _marker(self, name, on):
        path = self.root / name
        if on:
            path.write_text("")
        elif path.exists():
            path.unlink()


def _stand_in(bin_dir, world, eco):
    """A `npm` or `uv` that fails the re-lock the way the world says to."""
    e = ECOSYSTEMS[eco]
    for name, text in (("unreachable", e["unreachable"]),
                       ("unpublished", e["unpublished"]),
                       ("other", OTHER_FAILURE)):
        (world.root / f"{name}.txt").write_text(text)
    w = world.root
    script = f"""#!/bin/sh
case " $* " in
  *" {e["relock"]} "*)
    [ -e "{w}/slow" ] && exec sleep 30
    [ -e "{w}/offline" ] && {{ cat "{w}/unreachable.txt" >&2; exit 1; }}
    [ -e "{w}/broken" ] && {{ cat "{w}/other.txt" >&2; exit 1; }}
    grep -qx "sib@0.3.0" "{w}/published" || {{ cat "{w}/unpublished.txt" >&2; exit 1; }}
    # The re-lock records the bumped version, as the real tool does.
    sed -i 's/"1.0.0"/"1.0.1"/' {e["lockfile"]}
    exit 0 ;;
esac
exit 0
"""
    bin_dir.mkdir()
    (bin_dir / e["tool"]).write_text(script)
    (bin_dir / e["tool"]).chmod(0o755)


def _write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _commit_all(repo, message, *, autogenerated=False):
    git(repo, "add", "-A")
    args = ["commit", "-q", "-m", message]
    if autogenerated:
        args += ["--trailer", "Autogenerated: true"]
    git(repo, *args)
    return git(repo, "rev-parse", "HEAD")


def _project(tmp_path, eco):
    """A project at 1.0.0 with a lockfile, one covered commit and a remote."""
    repo = tmp_path / "repo"
    init_repo(repo)
    if eco == "npm":
        _write(repo / "package.json", json.dumps(
            {"name": "app", "version": "1.0.0", "dependencies": {"sib": "0.3.0"}},
            indent=2) + "\n")
        _write(repo / "package-lock.json", json.dumps({
            "name": "app", "version": "1.0.0", "lockfileVersion": 3,
            "requires": True,
            "packages": {
                "": {"name": "app", "version": "1.0.0",
                     "dependencies": {"sib": "0.3.0"}},
                "node_modules/sib": {"version": "0.3.0"},
            },
        }, indent=2) + "\n")
    else:
        _write(repo / "pyproject.toml",
               '[project]\nname = "app"\nversion = "1.0.0"\n'
               'requires-python = ">=3.11"\ndependencies = ["sib==0.3.0"]\n\n'
               '[dependency-groups]\ndev = ["pytest"]\n')
        _write(repo / "uv.lock", UV_LOCK)
    _write(repo / "CHANGELOG.md",
           "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
           "# Changelog\n\n## 1.0.0\n\n- Initial release.\n")
    _write(repo / ".rlsbl" / "config.json",
           json.dumps({"publish_mode": "ci", "targets": [eco], "tag": False,
                       "pipelines": {}}) + "\n")
    _write(repo / ".rlsbl" / "changes" / "unreleased.jsonl", "")
    _commit_all(repo, "initial")
    record_release(repo, "v1.0.0")
    _write(repo / "feature.txt", "a feature\n")
    feature = _commit_all(repo, "add feature")
    _write(repo / ".rlsbl" / "changes" / "unreleased.jsonl", json.dumps({
        "format_version": 1, "commits": [feature], "user_facing": True,
        "description": "**A feature.** It does a thing.", "type": "feature",
    }) + "\n")
    _commit_all(repo, "changelog: add feature entry", autogenerated=True)
    _write(repo / ".rlsbl" / "releases" / "unreleased.toml",
           f'format_version = 1\nbump = "patch"\ninclude = ["{eco}"]\n'
           'exclude = []\ndescription = "a patch release"\n')
    _commit_all(repo, "add release file", autogenerated=True)
    add_remote(repo, tmp_path / "remote")
    return repo


def _fake_gh(args, **_kwargs):
    if args[:2] == ["release", "view"]:
        raise subprocess.CalledProcessError(1, ["gh", *args])
    return ""


def _release(repo, monkeypatch, verb="run"):
    """`rlsbl release <verb>` through the CLI; git and the remote are real."""
    from rlsbl import utils

    monkeypatch.chdir(repo)
    with (
        patch("rlsbl.commands.release.validate_gh_cli"),
        patch("rlsbl.commands.release.validate_gh_push_access"),
        patch("rlsbl.commands.release.run_gh", side_effect=_fake_gh),
        patch("rlsbl.commands.release.run", utils.run),
        patch("rlsbl.commands.release.push_if_needed", utils.push_if_needed),
        patch("rlsbl.commands.release.resolve_tag_push_plan",
              utils.resolve_tag_push_plan),
    ):
        return app.test(["release", verb, "--no-watch", "--approve-consequential"])


@pytest.fixture(params=sorted(ECOSYSTEMS))
def project(request, tmp_path, monkeypatch):
    eco = request.param
    world = World(tmp_path / "world")
    world.publish("sib@0.2.0")
    _stand_in(tmp_path / "bin", world, eco)
    monkeypatch.setenv("PATH", f"{tmp_path / 'bin'}{os.pathsep}{os.environ['PATH']}")
    return _project(tmp_path, eco), eco, world


def _refused(repo, eco, monkeypatch):
    pin = git(repo, "rev-parse", "refs/heads/main")
    origin = git(repo, "ls-remote", "origin")
    result = _release(repo, monkeypatch)
    assert result.exit_code == 1, result.stderr + result.stdout
    # Nothing pushed or tagged, the branch and the working tree where they
    # were, no release state left behind: re-running the release starts over.
    assert git(repo, "ls-remote", "origin") == origin
    assert git(repo, "tag", "-l", "v1.0.1") == ""
    assert git(repo, "rev-parse", "refs/heads/main") == pin
    assert git(repo, "status", "--porcelain") == ""
    assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()
    lockfile = ECOSYSTEMS[eco]["lockfile"]
    assert f"re-locking {lockfile} after the version bump" in result.stderr
    assert "Warning" not in result.stderr
    return result.stderr


def _ships(repo, monkeypatch):
    result = _release(repo, monkeypatch)
    assert result.exit_code == 0, result.stderr + result.stdout
    assert git(repo, "rev-parse", "v1.0.1^{commit}")
    head = git(repo, "rev-parse", "refs/heads/main")
    assert git(repo, "ls-remote", "origin", "refs/heads/main").split()[0] == head


def test_an_unreachable_registry_refuses_and_restoring_it_ships(project, monkeypatch):
    repo, eco, world = project
    world.publish("sib@0.3.0")
    world.offline()
    err = _refused(repo, eco, monkeypatch)
    assert "The package registry could not be reached" in err
    assert "Restore this machine's network access to the registry" in err
    assert "re-run `rlsbl release run`" in err

    world.offline(False)
    _ships(repo, monkeypatch)


def test_an_unpublished_sibling_version_refuses_and_releasing_it_ships(project, monkeypatch):
    repo, eco, world = project
    err = _refused(repo, eco, monkeypatch)
    assert "sib 0.3.0 is required but the registry does not have it" in err
    assert "release it first" in err

    world.publish("sib@0.3.0")
    _ships(repo, monkeypatch)


def test_a_relock_that_times_out_refuses_and_restoring_the_registry_ships(
    project, monkeypatch,
):
    repo, eco, world = project
    monkeypatch.setattr("rlsbl.commands.release.execute._LOCKFILE_SYNC_TIMEOUT", 2)
    world.publish("sib@0.3.0")
    world.slow()
    err = _refused(repo, eco, monkeypatch)
    assert "did not finish within 2s" in err
    assert "Restore this machine's network access to the registry" in err

    world.slow(False)
    _ships(repo, monkeypatch)


def test_any_other_relock_failure_refuses_naming_what_the_tool_printed(project, monkeypatch):
    repo, eco, world = project
    world.publish("sib@0.3.0")
    world.broken()
    err = _refused(repo, eco, monkeypatch)
    assert OTHER_FAILURE.strip() in err
    assert f"Fix the error {ECOSYSTEMS[eco]['tool']} printed" in err

    world.broken(False)
    _ships(repo, monkeypatch)


def test_a_resume_whose_relock_fails_keeps_the_state_and_names_the_resume(
    project, tmp_path, monkeypatch,
):
    repo, eco, world = project
    world.publish("sib@0.3.0")
    # A first attempt whose candidate push is refused while another commit
    # lands on top of the release commit: the attempt is kept for a resume.
    hook = tmp_path / "remote" / "hooks" / "pre-receive"
    hook.write_text(
        "#!/bin/sh\n"
        f"cd '{repo}' && unset GIT_DIR GIT_QUARANTINE_PATH GIT_OBJECT_DIRECTORY "
        "GIT_ALTERNATE_OBJECT_DIRECTORIES && "
        "printf 'x\\n' >> feature.txt && git add feature.txt && "
        "git commit -q -m 'chore: on top' --trailer 'Autogenerated: true'\n"
        "exit 1\n"
    )
    hook.chmod(0o755)
    assert _release(repo, monkeypatch).exit_code != 0
    state = repo / ".rlsbl" / "releases" / "in-progress.json"
    assert state.exists()
    hook.unlink()

    world.offline()
    refused = _release(repo, monkeypatch, "resume")
    assert refused.exit_code == 1, refused.stderr + refused.stdout
    assert "The package registry could not be reached" in refused.stderr
    assert "then run `rlsbl release resume`" in refused.stderr
    assert state.exists()

    world.offline(False)
    resumed = _release(repo, monkeypatch, "resume")
    assert resumed.exit_code == 0, resumed.stderr + resumed.stdout
    assert git(repo, "rev-parse", "v1.0.1^{commit}")
    assert not state.exists()
