"""One CI gate for a whole batch release (C4, batch path).

`rlsbl monorepo release run` releases each member in two passes: every
member's version-bump commit is first pushed to the release branch untagged
(the per-member CI gate is deferred), then ONE gate waits for CI on the
resulting branch tip, and only then is each member finalized, tagged on that
verified commit, and released.

The properties under test are the batch mirror of the standalone ones:

- exactly one CI wait, whatever the batch size;
- exactly one candidate PUSH, whose diff matches every participating member's
  generated paths filter (see TestBatchSingleCandidatePush);
- every member's tag points at the single CI-verified commit;
- a red batch leaves no tag, no GitHub Release and no finalized changelog for
  any member, so no version number is burnt.
"""

import json
from pathlib import Path
import os
import subprocess
from unittest.mock import patch

import pytest

from githarness import git

from rlsbl.commands.monorepo import batch_release
from rlsbl.commands.monorepo.batch_release import _cmd_batch_release
from rlsbl.router_filters import RouterFilters, any_path_matches
from rlsbl.commands.release.release_state import get_state_path, load_release_state
from rlsbl.release_file import get_batch_release_file_path
from rlsbl.utils import run as real_run
from rlsbl.workspace import (
    Releasable,
    get_releasable_changes_dir,
    get_releasable_dir,
    load_releasables,
    load_workspace,
    save_workspace,
    write_releasable_version,
)

from conftest import (
    archive_release,
    declared_members,
    make_releasable_state,
    make_workspace,
    with_root_member,
)


BATCH_TOML = (
    '[releasables.alpha]\n'
    'bump = "patch"\ndescription = "Alpha patch"\n'
    'include = ["npm"]\nexclude = []\n'
    '\n'
    '[releasables.beta]\n'
    'bump = "patch"\ndescription = "Beta patch"\n'
    'include = ["npm"]\nexclude = []\n'
)


def _make_pkg(root, name):
    d = root / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "package.json").write_text(
        json.dumps({"name": name, "version": "1.0.0"}, indent=2) + "\n"
    )
    (d / ".rlsbl").mkdir(exist_ok=True)
    (d / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"], "pipelines": {}}) + "\n"
    )
    changes = d / ".rlsbl" / "changes"
    changes.mkdir(exist_ok=True)
    (changes / "unreleased.jsonl").write_text("")
    return d


def _setup_batch_workspace(root):
    """Two independently-versioned npm packages in an implicit-mode workspace."""
    git(root, "init", "-q", "-b", "main")
    git(root, "config", "user.email", "test@test.local")
    git(root, "config", "user.name", "Test")

    for name in ("alpha", "beta"):
        _make_pkg(root, name)
    make_workspace(str(root), [
        {"path": "alpha", "name": "alpha"},
        {"path": "beta", "name": "beta"},
    ])
    # make_workspace derives one releasable per member; each needs its state.
    for name in ("alpha", "beta"):
        make_releasable_state(root, name, version="1.0.0")
    _write_batch_file(root)

    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "initial")
    git(root, "tag", "alpha@v1.0.0")
    git(root, "tag", "beta@v1.0.0")
    # ...and each releasable's RELEASE RECORD entry: the unreleased range is measured
    # from the archived release, not from the tag.
    _tagged = git(root, "rev-parse", "HEAD")
    for name in ("alpha", "beta"):
        archive_release(
            os.path.join(get_releasable_dir(str(root), name), "releases"),
            "1.0.0", _tagged,
        )
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "release archives",
        "--trailer", "Autogenerated: true")

    # One covered feature commit per package.
    for name in ("alpha", "beta"):
        (root / name / "feature.txt").write_text("feature\n")
        git(root, "add", f"{name}/feature.txt")
        git(root, "commit", "-q", "-m", f"{name}: add feature")
        sha = git(root, "rev-parse", "HEAD")
        entry = json.dumps({
            "commits": [sha],
            "user_facing": True,
            "description": f"**{name} feature.** It works.",
            "type": "feature",
        }) + "\n"
        (root / name / ".rlsbl" / "changes" / "unreleased.jsonl").write_text(entry)
        Path(
            get_releasable_changes_dir(str(root), name), "unreleased.jsonl",
        ).write_text(entry)
        git(root, "add", "-A")
        git(root, "commit", "-q", "-m", f"changelog: {name} feature")


def _write_batch_file(root, content=BATCH_TOML):
    path = get_batch_release_file_path(str(root))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


RELEASABLE_BATCH_TOML = (
    '[releasables.alpha]\n'
    'bump = "patch"\ndescription = "Alpha patch"\n'
    'include = ["npm"]\nexclude = []\n'
    '\n'
    '[releasables.beta]\n'
    'bump = "patch"\ndescription = "Beta patch"\n'
    'include = ["npm"]\nexclude = []\n'
)


def _setup_releasable_batch_workspace(root):
    """Two single-member releasables (explicit mode), npm targets.

    The shape the two half-published releases were observed on: several
    releasables, each of whose CI job is path-filtered onto its own member's
    directory.
    """
    git(root, "init", "-q", "-b", "main")
    git(root, "config", "user.email", "test@test.local")
    git(root, "config", "user.name", "Test")

    for name in ("alpha", "beta"):
        d = root / name
        d.mkdir(parents=True, exist_ok=True)
        (d / "package.json").write_text(
            json.dumps({"name": name, "version": "1.0.0"}, indent=2) + "\n"
        )

    save_workspace(
        str(root),
        with_root_member([
            {"path": "alpha", "name": "alpha-pkg", "releasable": "alpha"},
            {"path": "beta", "name": "beta-pkg", "releasable": "beta"},
        ]),
        releasables=[Releasable(name="alpha"), Releasable(name="beta")],
    )

    for name in ("alpha", "beta"):
        write_releasable_version(str(root), name, "1.0.0")
        changes_dir = get_releasable_changes_dir(str(root), name)
        os.makedirs(changes_dir, exist_ok=True)
        with open(os.path.join(changes_dir, "unreleased.jsonl"), "w") as f:
            f.write("")
        with open(
            os.path.join(get_releasable_dir(str(root), name), "config.json"), "w"
        ) as f:
            json.dump(
                {"publish_mode": "ci", "targets": ["npm"], "pipelines": {}}, f,
            )

    _write_batch_file(root, RELEASABLE_BATCH_TOML)

    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "initial")
    git(root, "tag", "alpha@v1.0.0")
    git(root, "tag", "beta@v1.0.0")
    # ...and each releasable's RELEASE RECORD entry: the unreleased range is measured
    # from the archived release, not from the tag.
    _tagged = git(root, "rev-parse", "HEAD")
    for name in ("alpha", "beta"):
        archive_release(
            os.path.join(get_releasable_dir(str(root), name), "releases"),
            "1.0.0", _tagged,
        )
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "release archives",
        "--trailer", "Autogenerated: true")

    for name in ("alpha", "beta"):
        (root / name / "feature.txt").write_text("feature\n")
        git(root, "add", f"{name}/feature.txt")
        git(root, "commit", "-q", "-m", f"{name}: add feature")
        sha = git(root, "rev-parse", "HEAD")
        jsonl = os.path.join(
            get_releasable_changes_dir(str(root), name), "unreleased.jsonl",
        )
        with open(jsonl, "w") as f:
            f.write(json.dumps({
                "commits": [sha],
                "user_facing": True,
                "description": f"**{name} feature.** It works.",
                "type": "feature",
            }) + "\n")
        git(root, "add", os.path.relpath(jsonl, str(root)))
        git(root, "commit", "-q", "-m", f"changelog: {name} feature")


def _fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
    if cmd == "gh":
        return ""
    if cmd == "git" and args and args[0] in ("push", "fetch"):
        return ""
    if (cmd == "git" and args and args[:2] == ["rev-list", "--count"]
            and any("origin/" in a for a in args)):
        return "0"
    return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)


def _batch_patches(ci_return=None, ci_side_effect=None, push_side_effect=None):
    ci_kwargs = (
        {"side_effect": ci_side_effect} if ci_side_effect is not None
        else {"return_value": ci_return}
    )
    push_kwargs = (
        {"side_effect": push_side_effect} if push_side_effect is not None else {}
    )
    return [
        patch("rlsbl.commands.monorepo.batch_release.validate_gh_cli"),
        patch("rlsbl.commands.monorepo.batch_release.validate_gh_push_access"),
        patch("rlsbl.commands.monorepo.batch_release.validate_clean_tree",
              return_value=set()),
        patch("rlsbl.commands.monorepo.batch_release.validate_branch_and_remote",
              return_value="main"),
        patch("rlsbl.commands.release.check_gh_installed", return_value=True),
        patch("rlsbl.commands.release.check_gh_auth", return_value=True),
        # The batch orchestrator's own candidate push resolves through this
        # same package namespace (late-bound, like the release flow's), so one
        # patch covers every push site in the batch.
        patch("rlsbl.commands.release.push_if_needed", **push_kwargs),
        patch("rlsbl.commands.release.run_gh", return_value=""),
        patch("rlsbl.commands.release.run", side_effect=_fake_run),
        patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
        patch("rlsbl.commands.monorepo.batch_release.wait_for_ci_green", **ci_kwargs),
    ]


def _run_batch(root, *, ci_return=None, ci_side_effect=None, push_side_effect=None):
    patches = _batch_patches(
        ci_return=ci_return, ci_side_effect=ci_side_effect,
        push_side_effect=push_side_effect,
    )
    for p in patches:
        p.start()
    try:
        _cmd_batch_release({"quiet": True}, project_root=str(root))
    finally:
        for p in patches:
            p.stop()


class TestBatchCandidateGate:

    def test_one_gate_for_the_batch_and_every_tag_on_the_verified_commit(
        self, tmp_project,
    ):
        _setup_batch_workspace(tmp_project)
        calls = []

        def fake_wait(sha, **kwargs):
            calls.append(sha)
            return "green", []

        _run_batch(tmp_project, ci_side_effect=fake_wait)

        assert len(calls) == 1, (
            f"a batch must run exactly ONE CI gate, got {len(calls)}"
        )
        verified = calls[0]

        tags = git(tmp_project, "tag", "-l").split()
        assert "alpha@v1.0.1" in tags and "beta@v1.0.1" in tags

        for tag in ("alpha@v1.0.1", "beta@v1.0.1"):
            assert git(tmp_project, "rev-list", "-n", "1", tag) == verified, (
                f"{tag} must point at the single CI-verified batch candidate"
            )

        # The gate saw a commit that already carried BOTH version bumps.
        for name in ("alpha", "beta"):
            blob = git(tmp_project, "show", f"{verified}:{name}/package.json")
            assert json.loads(blob)["version"] == "1.0.1", (
                f"the verified candidate must contain {name}'s version bump"
            )

        # Both changelogs finalized, both state files cleared.
        for name in ("alpha", "beta"):
            # A member's finalized changelog lands under its releasable.
            changes = Path(get_releasable_changes_dir(str(tmp_project), name))
            assert (changes / "1.0.1.jsonl").exists()
            assert load_release_state(
                get_state_path(str(tmp_project / name))
            ) is None

    def test_a_red_batch_gate_leaves_no_tag_and_no_finalization(self, tmp_project):
        _setup_batch_workspace(tmp_project)

        with pytest.raises(SystemExit) as exc:
            _run_batch(
                tmp_project,
                ci_return=("red", [{"name": "test", "passed": False}]),
            )
        assert exc.value.code == 1

        tags = git(tmp_project, "tag", "-l").split()
        assert "alpha@v1.0.1" not in tags and "beta@v1.0.1" not in tags, (
            "a red batch gate must leave every member untagged"
        )

        for name in ("alpha", "beta"):
            changes = Path(get_releasable_changes_dir(str(tmp_project), name))
            assert not (changes / "1.0.1.jsonl").exists(), (
                f"{name}'s changelog must not be finalized while CI is red"
            )
            assert os.path.getsize(changes / "unreleased.jsonl") > 0
            # Resumable at the same version -- no number was burnt.
            state = load_release_state(get_state_path(
                str(tmp_project / name),
                releasable_dir=get_releasable_dir(str(tmp_project), name),
            ))
            assert state is not None and state["new_version"] == "1.0.1"

        # The batch file is not archived while the batch is incomplete.
        assert os.path.exists(get_batch_release_file_path(str(tmp_project)))

    def test_the_candidates_are_pushed_before_the_gate(self, tmp_project):
        """Both members' candidates must be on the branch when CI is asked."""
        _setup_batch_workspace(tmp_project)
        observed = {}

        def fake_wait(sha, **kwargs):
            observed["tags_at_gate"] = git(tmp_project, "tag", "-l").split()
            observed["sha"] = sha
            return "green", []

        _run_batch(tmp_project, ci_side_effect=fake_wait)

        assert "alpha@v1.0.1" not in observed["tags_at_gate"], (
            "nothing may be tagged before the gate reports"
        )
        assert "beta@v1.0.1" not in observed["tags_at_gate"]
        assert subprocess.run(
            ["git", "merge-base", "--is-ancestor", observed["sha"], "HEAD"],
            cwd=str(tmp_project),
        ).returncode == 0


class TestBatchGateRideInWindow:
    """The batch tip must carry only commits the batch itself created.

    Regression: the gate took HEAD with no foreign-commit guard at all. Every
    member's per-release guard only covers that member's own call, so a commit
    landing between the last candidate push and the gate -- a concurrent
    session sharing the worktree -- was gated, tagged and released under every
    member's version without ever being reviewed.
    """

    def _ride_in_at_gate(self, root):
        """Wrap the trail computation so a foreign commit lands just before it.

        _batch_release_trail() is evaluated as an argument to _batch_ci_gate,
        i.e. exactly in the window between the last candidate push and the
        gate's guard.
        """
        real_trail = batch_release._batch_release_trail

        def _wrapped(pending, inline_commits):
            (root / "rider.txt").write_text("rider\n")
            git(root, "add", "rider.txt")
            git(root, "commit", "-q", "-m", "concurrent session: unrelated work")
            return real_trail(pending, inline_commits)

        return _wrapped

    def test_a_ride_in_before_the_gate_is_a_hard_error(self, tmp_project, capsys):
        _setup_batch_workspace(tmp_project)
        gate_calls = []

        def fake_wait(sha, **kwargs):
            gate_calls.append(sha)
            return "green", []

        with patch.object(batch_release, "_batch_release_trail",
                          side_effect=self._ride_in_at_gate(tmp_project)):
            with pytest.raises(SystemExit) as exc:
                _run_batch(tmp_project, ci_side_effect=fake_wait)
        assert exc.value.code == 1

        rider = git(tmp_project, "rev-parse", "HEAD")
        err = capsys.readouterr().err
        assert rider[:12] in err, "the foreign commit must be named by SHA"
        assert "concurrent session: unrelated work" in err, (
            "the foreign commit's subject must be shown"
        )

        assert gate_calls == [], "a ride-in must abort BEFORE the CI wait"
        tags = git(tmp_project, "tag", "-l").split()
        assert "alpha@v1.0.1" not in tags and "beta@v1.0.1" not in tags

    def test_the_ride_in_is_never_rolled_back(self, tmp_project):
        """The guard refuses to SHIP foreign work, never to destroy it."""
        _setup_batch_workspace(tmp_project)

        with patch.object(batch_release, "_batch_release_trail",
                          side_effect=self._ride_in_at_gate(tmp_project)):
            with pytest.raises(SystemExit):
                _run_batch(tmp_project, ci_return=("green", []))

        assert (tmp_project / "rider.txt").exists()
        subjects = git(tmp_project, "log", "--format=%s", "-n", "1")
        assert subjects == "concurrent session: unrelated work"

    def test_a_clean_batch_is_not_flagged(self, tmp_project):
        """Every commit the batch itself creates must stay off the foreign list."""
        _setup_batch_workspace(tmp_project)
        _run_batch(tmp_project, ci_return=("green", []))
        tags = git(tmp_project, "tag", "-l").split()
        assert "alpha@v1.0.1" in tags and "beta@v1.0.1" in tags


class TestBatchGateTimeoutVerdict:
    """A CI-wait TIMEOUT is not a red batch."""

    def test_timeout_reports_unresolved_not_failed(self, tmp_project, capsys):
        _setup_batch_workspace(tmp_project)

        with pytest.raises(SystemExit) as exc:
            _run_batch(tmp_project, ci_return=("timeout", [
                {"name": "ci", "passed": False, "timed_out": True},
            ]))
        assert exc.value.code == 1

        err = capsys.readouterr().err
        assert "ran out of time" in err
        assert "may still be in progress" in err
        assert "NOT a CI failure" in err
        assert "did not pass" not in err, (
            "a timeout must not be reported as a CI failure"
        )
        assert "rlsbl watch" in err, "the operator must be told how to check"

        tags = git(tmp_project, "tag", "-l").split()
        assert "alpha@v1.0.1" not in tags and "beta@v1.0.1" not in tags

    def test_a_real_failure_alongside_a_timeout_is_still_red(self, tmp_project, capsys):
        _setup_batch_workspace(tmp_project)

        with pytest.raises(SystemExit):
            _run_batch(tmp_project, ci_return=("red", [
                {"name": "lint", "passed": False},
                {"name": "slow-matrix", "passed": False, "timed_out": True},
            ]))

        err = capsys.readouterr().err
        assert "CI did not pass" in err
        assert "lint" in err
        assert "slow-matrix" not in err, (
            "an unresolved run must not be listed as a failing workflow"
        )


class TestBatchNoCiNotice:
    """The 'proceeding without a CI gate' notice must survive --quiet."""

    def test_notice_reaches_stderr_under_quiet(self, tmp_project, capsys):
        _setup_batch_workspace(tmp_project)
        _run_batch(tmp_project, ci_return=("no-ci", []))
        err = capsys.readouterr().err
        assert "without a CI gate" in err, (
            "--quiet must not swallow the no-CI-gate notice"
        )


def _covers(paths, patterns):
    """Would a push touching *paths* trigger a job filtered by *patterns*?

    Deliberately the production matcher, not a local approximation: this file
    used to carry its own, which could agree with the router generator while
    both disagreed with the action. Conformance to the real action is proved
    once, in tests/test_router_filters.py, against captured verdicts.
    """
    return any_path_matches(paths, patterns)


class _PushRecorder:
    """Records every candidate push as the (before, after) window it publishes.

    ``before`` is what the remote branch held prior to that push, so a
    window's diff is exactly the diff GitHub Actions hands
    ``dorny/paths-filter`` on the resulting push event.
    """

    def __init__(self, root, base):
        self.root = root
        self.remote = base
        self.windows = []

    def __call__(self, branch, *, config=None, cwd=None, sha=None):
        pushed = sha or git(self.root, "rev-parse", "HEAD")
        self.windows.append((self.remote, pushed))
        self.remote = pushed

    def window_ending_at(self, sha):
        for before, after in self.windows:
            if after == sha:
                return before, after
        raise AssertionError(
            f"no push published {sha[:12]}; pushes were "
            f"{[(b[:12], a[:12]) for b, a in self.windows]}"
        )

    def paths_in(self, window):
        before, after = window
        out = git(self.root, "diff", "--name-only", f"{before}..{after}")
        return [line for line in out.splitlines() if line.strip()]


class TestBatchSingleCandidatePush:
    """A batch publishes ONE candidate push, and every member's CI runs on it.

    Regression (two confirmed half-published releases). Pass 1 used to push
    each member's candidate SEPARATELY, then gate CI on the LAST candidate and
    tag every member there. The generated router filters paths against the
    push's own before-SHA, so each push only ever triggered the one project it
    touched: on the commit every tag pointed at, all the OTHER projects' CI
    jobs concluded ``skipped``. Their publish gates then refused (correctly --
    a skipped check proves nothing), so tags and GitHub Releases existed for
    versions that never reached their registries, with no retry that could
    ever go green.

    The property the engine must hold: the batch's tagged commit arrives in a
    single push whose diff matches EVERY participating member's paths filter.
    """

    def _gate_and_push(self, root, setup):
        setup(root)
        base = git(root, "rev-parse", "HEAD")
        recorder = _PushRecorder(root, base)
        gate = {}

        def fake_wait(sha, **kwargs):
            gate["sha"] = sha
            gate["pushes_at_gate"] = list(recorder.windows)
            return "green", []

        _run_batch(root, ci_side_effect=fake_wait, push_side_effect=recorder)
        return recorder, gate

    def test_exactly_one_candidate_push_precedes_the_gate(self, tmp_project):
        recorder, gate = self._gate_and_push(tmp_project, _setup_batch_workspace)

        assert len(gate["pushes_at_gate"]) == 1, (
            "a batch must publish ONE candidate; a push per member gives each "
            "push a diff covering only that member, so every other member's "
            "CI job is skipped on the commit the batch tags. Pushes: "
            f"{[(b[:12], a[:12]) for b, a in gate['pushes_at_gate']]}"
        )
        assert gate["pushes_at_gate"][0][1] == gate["sha"], (
            "the gated commit must be the one the candidate push published"
        )

    def test_the_gated_push_matches_every_members_paths_filter(self, tmp_project):
        recorder, gate = self._gate_and_push(tmp_project, _setup_batch_workspace)

        window = recorder.window_ending_at(gate["sha"])
        paths = recorder.paths_in(window)
        # The root member's router filter is derived from its residual
        # territory, which is a separate matter from what a candidate push
        # must touch for each declared member's CI job to run.
        all_members = load_workspace(str(tmp_project))
        filters = RouterFilters(str(tmp_project), all_members)
        for project in declared_members(all_members):
            patterns = filters.patterns_for(project)
            assert _covers(paths, patterns), (
                f"the CI-gated push does not touch anything matching "
                f"{project['name']}'s router filter {patterns}; its CI job "
                f"would be skipped on the very commit its tag points at. "
                f"Pushed paths: {paths}"
            )

    def test_releasable_mode_gates_one_push_covering_every_releasable(
        self, tmp_project,
    ):
        """The shape both real half-published releases had."""
        recorder, gate = self._gate_and_push(
            tmp_project, _setup_releasable_batch_workspace,
        )

        assert len(gate["pushes_at_gate"]) == 1, (
            "a releasable batch must publish ONE candidate; pushes: "
            f"{[(b[:12], a[:12]) for b, a in gate['pushes_at_gate']]}"
        )

        window = recorder.window_ending_at(gate["sha"])
        paths = recorder.paths_in(window)
        projects = load_workspace(str(tmp_project))
        releasables = load_releasables(str(tmp_project), projects)
        filters = RouterFilters(str(tmp_project), projects, releasables)
        for project in declared_members(projects):
            patterns = filters.patterns_for(project)
            assert _covers(paths, patterns), (
                f"the CI-gated push does not touch anything matching "
                f"{project['name']}'s router filter {patterns}. "
                f"Pushed paths: {paths}"
            )

        # And the tags really do land on that verified commit.
        for tag in ("alpha@v1.0.1", "beta@v1.0.1"):
            assert git(tmp_project, "rev-list", "-n", "1", tag) == gate["sha"]
