"""A monorepo batch confirms every released member's publish runs started.

The batch's watch tail confirmed only the members that had a registry probe
spec, and built that spec from each member's in-progress state before pass 2.
A member whose release ran to completion inside its own pass-1 call never got
a spec, and neither did one whose targets could not be resolved, so neither
was ever start-confirmed. The confirmation now reads each released member's
release from the release record, which every completed release writes, and
needs no probe spec. The workflows expected to start are the ones at the git
root's ``.github/workflows/``, which a workspace nested below the git root
used to miss.
"""

import json
import subprocess
from io import StringIO
from unittest.mock import patch

import pytest

from githarness import record_release
from rlsbl import publish_workflows
from rlsbl.commands.monorepo import batch_release

PUBLISH = """\
name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo publish
"""


def _git(cwd, *args):
    return subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True,
    ).stdout.strip()


def _commit_workflow(git_root):
    wf = git_root / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    (wf / "publish.yml").write_text(PUBLISH)
    _git(git_root, "add", ".github/workflows/publish.yml")
    _git(git_root, "commit", "-q", "-m", "publish workflow",
         "--trailer", "Autogenerated: true")


class FakeGitHub:
    def __init__(self, runs=()):
        self.runs = list(runs)

    def __call__(self, args, *_a, **_k):
        args = list(args)
        if args[:2] == ["release", "view"]:
            if "publishedAt" in args:
                from datetime import datetime, timezone
                return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            return "smm-h"
        if args[:3] == ["api", "--method", "GET"]:
            path = args[3]
            if path.endswith("/actions/permissions"):
                return json.dumps({"enabled": True})
            if "/runs?" in path:
                return json.dumps({"workflow_runs": self.runs})
            if "/actions/workflows/" in path:
                return "active"
        return ""


_REAL_CONFIRM_OR_EXIT = publish_workflows.confirm_or_exit
_REAL_CONFIRM_PUBLISH_STARTS = batch_release._confirm_publish_starts


@pytest.fixture(autouse=True)
def _real_confirmation(monkeypatch):
    """The real confirmation (conftest neutralizes it), with no wait."""
    monkeypatch.setattr(publish_workflows, "confirm_or_exit",
                        _REAL_CONFIRM_OR_EXIT)
    monkeypatch.setattr(batch_release, "_confirm_publish_starts",
                        _REAL_CONFIRM_PUBLISH_STARTS)
    monkeypatch.setattr(publish_workflows, "DISCOVERY_SECONDS", 0)


def _tail(started, workspace_root, gh, *, probe_specs=()):
    """The batch tail under --no-watch, as the batch loop calls it."""
    err = StringIO()
    with (
        patch("rlsbl.utils.run_gh", side_effect=gh),
        patch("sys.stderr", err),
        patch("sys.stdout", new_callable=StringIO),
    ):
        try:
            batch_release._watch_and_verify_batch(
                {"watch": False}, "0" * 40, list(probe_specs), started,
                str(workspace_root), lambda _line: None,
            )
        except SystemExit as exc:
            return exc.code, err.getvalue()
    return 0, err.getvalue()


class TestAMemberWithoutAProbeSpec:

    def test_is_confirmed_from_the_release_record(
        self, multi_releasable_monorepo_factory,
    ):
        ns = multi_releasable_monorepo_factory()
        _commit_workflow(ns.root)
        record_release(ns.root, "alpha@v0.2.0")
        alpha = str(ns.root / "libs" / "alpha-core")

        code, err = _tail([("alpha", alpha)], ns.root, FakeGitHub())
        assert code == 1
        assert "no run of .github/workflows/publish.yml started" in err
        assert "alpha@v0.2.0" in err

        started = FakeGitHub([{"event": "release",
                               "head_branch": "alpha@v0.2.0", "id": 1}])
        code, err = _tail([("alpha", alpha)], ns.root, started)
        assert code == 0, err

    def test_an_unreadable_release_record_is_a_hard_error(
        self, multi_releasable_monorepo_factory,
    ):
        ns = multi_releasable_monorepo_factory(write_initial_release_state=False)
        _commit_workflow(ns.root)
        alpha = str(ns.root / "libs" / "alpha-core")
        code, err = _tail([("alpha", alpha)], ns.root, FakeGitHub())
        assert code == 1
        assert "alpha is released, but whether its Release started" in err


class TestAWorkspaceBelowTheGitRoot:

    def test_the_git_roots_workflows_are_the_ones_expected(self, tmp_path):
        repo = tmp_path / "repo"
        repo.mkdir()
        _git(repo, "init", "-q", "-b", "main")
        _git(repo, "config", "user.email", "t@t.local")
        _git(repo, "config", "user.name", "T")
        (repo / "ws").mkdir()
        (repo / "ws" / "README.md").write_text("ws\n")
        _git(repo, "add", ".")
        _git(repo, "commit", "-q", "-m", "workspace")
        _commit_workflow(repo)
        sha = _git(repo, "rev-parse", "HEAD")

        from types import SimpleNamespace
        member = SimpleNamespace(config={})
        with patch.object(batch_release, "_release_to_confirm",
                          return_value=("pkg@v1.0.0", sha, "1.0.0", member)):
            code, err = _tail([("pkg", str(repo / "ws"))], repo / "ws",
                              FakeGitHub())
        assert code == 1
        assert "no run of .github/workflows/publish.yml started" in err


def test_the_inline_completion_joins_the_confirmed_members():
    """A member that completed inside its own pass-1 call is recorded as
    started, beside the members pass 2 completes."""
    import inspect

    source = inspect.getsource(batch_release._batch_release_releasables)
    assert source.count("started.append((rel_name, project_dir))") == 2
    assert ("_watch_and_verify_batch(flags, last_sha, probe_specs, started,"
            in source)
