"""Regression tests: release finalization must leave a clean working tree.

Two related bugs in the release finalization path:

1. The new version's per-version .md was generated without the release
   description/context (the archived v{version}.toml doesn't exist yet when
   generate_version_file() runs during finalization).
2. generate_changelog() backfills description/context into OLDER per-version
   .md files (read from archived .rlsbl/releases/v{version}.toml), but the
   finalization commit only included the new version's files -- leaving the
   backfilled older .md files dirty after the release.

Uses a real git repository with minimal mocking (only gh and git push/fetch
are intercepted), following tests/test_release_integration.py.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.changelog.generate import generate_version_file
from rlsbl.commands.release import run_cmd
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_output(repo, *args):
    result = subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _git_head(repo):
    return _git_output(repo, "rev-parse", "HEAD")


def _setup_released_project_with_stale_md(repo):
    """Create an npm project with a released v1.0.0 whose per-version .md
    lacks the release description, plus one unreleased commit ready to release.

    State after this fixture:
    - .rlsbl/changes/1.0.0.jsonl (chmod 444, released)
    - .rlsbl/changes/1.0.0.md generated WITHOUT description (stale)
    - .rlsbl/releases/v1.0.0.toml with description = "First release" (archived)
    - git tag v1.0.0
    - one unreleased feature commit covered by unreleased.jsonl
    - .rlsbl/releases/unreleased.toml describing the next release
    """
    initial_sha = _git_head(repo)

    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )

    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    released_entry = {
        "commits": [initial_sha],
        "user_facing": True,
        "description": "**Initial.** First version of the package.",
        "type": "feature",
    }
    (changes_dir / "1.0.0.jsonl").write_text(json.dumps(released_entry) + "\n")
    # Generate 1.0.0.md WITHOUT description -- this reproduces the historical
    # state where the release flow didn't thread release metadata through.
    generate_version_file(str(changes_dir), "1.0.0")
    os.chmod(changes_dir / "1.0.0.jsonl", 0o444)
    (changes_dir / "unreleased.jsonl").write_text("")

    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"private": False}) + "\n"
    )

    # Archived release file for v1.0.0 carrying the description that
    # generate_changelog() backfills into 1.0.0.md during the next release.
    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "v1.0.0.toml").write_text(
        'bump = "patch"\n'
        'include = ["npm"]\n'
        'exclude = []\n'
        'description = "First release"\n'
    )
    os.chmod(releases_dir / "v1.0.0.toml", 0o444)

    # Stale CHANGELOG.md (fully regenerated during release)
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ — do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n### Features\n\n"
        "- **Initial.** First version of the package.\n"
    )

    _git(repo, "add",
         "package.json",
         "CHANGELOG.md",
         ".rlsbl/changes/1.0.0.jsonl",
         ".rlsbl/changes/1.0.0.md",
         ".rlsbl/changes/unreleased.jsonl",
         ".rlsbl/config.json",
         ".rlsbl/releases/v1.0.0.toml")
    _git(repo, "commit", "-q", "-m", "release state v1.0.0")
    _git(repo, "tag", "v1.0.0")

    # One unreleased feature commit
    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    # Cover it with a JSONL entry (Autogenerated trailer self-exempts)
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(
        repo, "commit", "-q", "-m", "changelog: add feature entry",
        "--trailer", "Autogenerated: true",
    )

    # Release file for the upcoming 1.0.1 release
    (releases_dir / "unreleased.toml").write_text(
        'bump = "patch"\n'
        'include = ["npm"]\n'
        'exclude = []\n'
        'description = "Second release"\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")


def _make_ctx(repo):
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config={"private": False, "pipelines": {}},
    )


def _fake_run_factory():
    """Intercept gh/push/fetch, pass everything else through to real run()."""
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


class TestReleaseLeavesCleanPerVersionMd:
    """Releasing 1.0.1 must commit the backfilled 1.0.0.md and put the new
    release's description into 1.0.1.md."""

    def _run_release(self, repo):
        fake_run = _fake_run_factory()
        rc = ReleaseConfig(
            bump="patch",
            include=["npm"],
            exclude=[],
            description="Second release",
        )
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
        ):
            run_cmd(rc, {"yes": True, "quiet": True}, ctx=_make_ctx(repo))

    def test_release_commits_backfilled_md_and_threads_metadata(self, mock_git_repo):
        _setup_released_project_with_stale_md(mock_git_repo)
        changes_dir = mock_git_repo / ".rlsbl" / "changes"

        # Sanity: stale state before release
        assert "First release" not in (changes_dir / "1.0.0.md").read_text()

        self._run_release(mock_git_repo)

        # 1. Working tree is clean (advisory lock file is removed on release;
        # filter any residual lock line for parity with other release tests)
        status = _git_output(mock_git_repo, "status", "--porcelain")
        dirty = [
            line for line in status.splitlines()
            if line.strip() and "lock" not in line
        ]
        assert dirty == [], f"Working tree should be clean after release, got: {dirty}"

        # 2. 1.0.0.md was backfilled with the archived release description
        # AND committed (no diff vs HEAD)
        md_100 = (changes_dir / "1.0.0.md").read_text()
        assert "First release" in md_100, (
            f"1.0.0.md should contain the backfilled description, got:\n{md_100}"
        )
        diff = _git_output(
            mock_git_repo, "diff", "HEAD", "--", ".rlsbl/changes/1.0.0.md"
        )
        assert diff == "", (
            f"1.0.0.md should be committed (no diff vs HEAD), got:\n{diff}"
        )

        # 3. The new 1.0.1.md contains the new release's description
        md_101_path = changes_dir / "1.0.1.md"
        assert md_101_path.exists(), "1.0.1.md should be generated during release"
        md_101 = md_101_path.read_text()
        assert "Second release" in md_101, (
            f"1.0.1.md should contain the release description, got:\n{md_101}"
        )
        assert "New feature" in md_101, (
            f"1.0.1.md should contain the feature entry, got:\n{md_101}"
        )
