"""Tests for post-release step tracking: markers, fatality classes, and
incremental resume of the post-release phase.

Covers:
- A fully successful release records a marker for EVERY canonical step
  before the state file is cleared (provable completeness).
- Pipeline publish failure is FATAL: state preserved, resumable (it used
  to be downgraded to a warning -- silent degradation for local pipelines).
- Resume re-attempts publish after a publish failure.
- Resume skips already-completed post-release steps (e.g. does not
  re-upload assets when ASSETS_UPLOADED is marked).
- Deploy and post-release hook failures are non-fatal but recorded as
  failure markers and loudly named in the completion summary.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from githarness import record_release

from rlsbl.commands.release import resume_cmd, run_cmd
from rlsbl.commands.release.release_state import (
    MUTATING_STEPS,
    RELEASE_STEPS,
    get_state_path,
    load_release_state,
    save_release_state,
)
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run

from conftest import with_root_member, make_workspace


# ---------------------------------------------------------------------------
# Helpers (conventions follow tests/test_release_resume.py)
# ---------------------------------------------------------------------------


def _rc(bump="patch", include=None, exclude=None, description="test release"):
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
        description=description,
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_head(repo):
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _setup_npm_project(repo):
    """Create an npm project at v1.0.0 with one unreleased commit."""
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"]}) + "\n"
    )
    _git(repo, "add",
         "package.json", "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    record_release(repo, "v1.0.0")

    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(repo, "commit", "-q", "-m", "changelog: add feature entry",
         "--trailer", "Autogenerated: true")


def _make_ctx(repo, config=None):
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config=config or {"publish_mode": "ci", "pipelines": {}},
    )


def _fake_run_factory():
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


_RUN_CMD_PATCHES = (
    ("rlsbl.commands.release.check_gh_installed", {"return_value": True}),
    ("rlsbl.commands.release.check_gh_auth", {"return_value": True}),
    ("rlsbl.commands.release.remote_branch_exists", {"return_value": True}),
)


def _make_in_progress_state(repo, *, completed_steps=None, failed_steps=None,
                            version="1.0.1", branch="main"):
    """Write an in-progress.json state file and return its path."""
    state_path = get_state_path(str(repo))
    pre_sha = _git_head(repo)
    state = {
        "new_version": version,
        "tag": f"v{version}",
        "branch": branch,
        "pre_release_sha": pre_sha,
        "bump_type": "patch",
        "registry": "npm",
        "completed_steps": completed_steps or [],
        "failed_steps": failed_steps or {},
        "companion_tags": [],
        "monorepo_name": None,
        "releasable_name": None,
        "commit_msg": f"v{version}",
        "description": "test release",
        "context": "",
        "include": ["npm"],
        "exclude": [],
        "preid": "",
        "blog": False,
    }
    save_release_state(state_path, state)
    return state_path


def _bump_and_tag(repo, version="1.0.1"):
    """Simulate the mutating phase already done: bump, commit, tag."""
    pkg = json.loads((repo / "package.json").read_text())
    pkg["version"] = version
    (repo / "package.json").write_text(json.dumps(pkg, indent=2) + "\n")
    _git(repo, "add", "package.json")
    _git(repo, "commit", "-q", "-m", f"v{version}")
    record_release(repo, f"v{version}")


def _setup_subtree_monorepo(repo, project_path="packages/mylib", name="mylib",
                            version="1.0.1"):
    """A monorepo whose only project declares a ``subtree_remote``, staged at
    the point a resume re-enters the post-GitHub-Release phase.

    Returns the project directory. The release is already tagged and its
    state file records every mutating step, so the resume goes straight to
    the subtree/mirror publishing block.
    """
    from rlsbl.workspace import save_workspace

    proj_dir = repo / project_path
    proj_dir.mkdir(parents=True)
    (proj_dir / "package.json").write_text(
        json.dumps({"name": name, "version": version}, indent=2) + "\n"
    )
    (proj_dir / ".rlsbl").mkdir()
    (proj_dir / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "none", "targets": ["npm"]}) + "\n"
    )
    make_workspace(str(repo), [{
        "path": project_path,
        "name": name,
        "subtree_remote": "https://github.com/example/mylib.git",
    }])
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", f"{name}@v{version}")
    tag = f"{name}@v{version}"
    _git(repo, "tag", tag)

    from rlsbl.commands.release.release_state import resolve_releasable_dir
    state_path = get_state_path(
        str(proj_dir),
        releasable_dir=resolve_releasable_dir(str(proj_dir), str(repo)),
    )
    save_release_state(state_path, {
        "new_version": version,
        "tag": tag,
        "branch": "main",
        "pre_release_sha": _git_head(repo),
        "candidate_sha": _git_head(repo),
        "pin_sha": _git_head(repo),
        "bump_type": "patch",
        "registry": "npm",
        "completed_steps": list(MUTATING_STEPS),
        "failed_steps": {},
        "companion_tags": [],
        "monorepo_name": name,
        # make_workspace derives one releasable per member, named after it.
        "releasable_name": name,
        "commit_msg": tag,
        "description": "test release",
        "context": "",
        "include": ["npm"],
        "exclude": [],
        "preid": "",
        "blog": False,
    })
    return str(proj_dir)


def _make_subtree_ctx(repo, project_dir):
    return ProjectContext(
        project_root=Path(project_dir),
        workspace_root=Path(str(repo)),
        config={"publish_mode": "none", "pipelines": {}},
    )


class _RecordingPipeline:
    """Fake pipeline that records publish calls; optionally fails."""

    # validate_pipeline_config checks .local for required-env validation
    local = False

    def __init__(self, fail=False):
        self.fail = fail
        self.publish_calls = []

    def publish(self, path, version, *, ctx):
        self.publish_calls.append((path, version))
        if self.fail:
            raise RuntimeError("registry rejected the upload")


# ---------------------------------------------------------------------------
# Provable completeness on success
# ---------------------------------------------------------------------------


class TestSuccessMarksAllSteps:
    """A fully successful release marks every canonical step before the
    state file is cleared."""

    def test_all_steps_marked_before_clear(self, mock_git_repo):
        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        from rlsbl.commands.release.release_state import (
            clear_release_state as real_clear,
        )

        snapshots = []

        def capturing_clear(path):
            state = load_release_state(path)
            if state is not None:
                snapshots.append(state)
            real_clear(path)

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.release.execute.clear_release_state",
                  side_effect=capturing_clear),
        ):
            run_cmd(
                _rc(),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        assert not os.path.exists(state_path)
        assert len(snapshots) == 1, "state should be cleared exactly once"
        final = snapshots[0]
        assert set(final["completed_steps"]) == set(RELEASE_STEPS), (
            "every canonical step must have a success marker on a fully "
            f"successful release; got {sorted(final['completed_steps'])}"
        )
        assert not final.get("failed_steps")


# ---------------------------------------------------------------------------
# Pipeline publish fatality
# ---------------------------------------------------------------------------


class TestPublishFailureIsFatal:
    """Pipeline publish failure aborts the release with preserved state
    (previously it was downgraded to a warning and the release completed)."""

    def test_publish_failure_preserves_state_and_aborts(
        self, mock_git_repo, capsys,
    ):
        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        failing = _RecordingPipeline(fail=True)
        fake_run = _fake_run_factory()
        with pytest.raises(SystemExit) as exc_info:
            with (
                patch("rlsbl.commands.release.check_gh_installed", return_value=True),
                patch("rlsbl.commands.release.check_gh_auth", return_value=True),
                patch("rlsbl.commands.release.push_if_needed"),
                patch("rlsbl.commands.release.run_gh", return_value=""),
                patch("rlsbl.commands.release.run", side_effect=fake_run),
                patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
                patch("rlsbl.commands.release.load_pipelines",
                      return_value={"npm": failing}),
            ):
                run_cmd(
                    _rc(),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code == 1
        assert failing.publish_calls, "publish must have been attempted"

        # State preserved and resumable
        assert os.path.exists(state_path), (
            "publish failure must preserve in-progress.json for resume"
        )
        state = load_release_state(state_path)
        assert "PUSHED" in state["completed_steps"]
        assert "PIPELINES_PUBLISHED" not in state["completed_steps"]
        assert "PIPELINES_PUBLISHED" in state.get("failed_steps", {})

        captured = capsys.readouterr()
        assert "publish failed" in captured.err
        assert "resume" in captured.err

    def test_resume_reattempts_publish(self, mock_git_repo):
        """After a publish failure, resume re-attempts the publish step."""
        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS) + ["ASSETS_UPLOADED"],
            failed_steps={"PIPELINES_PUBLISHED": "registry rejected the upload"},
        )

        recording = _RecordingPipeline()
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.load_pipelines",
                  return_value={"npm": recording}),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        assert recording.publish_calls, (
            "resume must re-attempt the failed publish step"
        )
        assert not os.path.exists(state_path)


# ---------------------------------------------------------------------------
# Incremental resume of post-release steps
# ---------------------------------------------------------------------------


class TestIncrementalPostReleaseResume:

    def test_resume_skips_uploaded_assets_and_proceeds_to_publish(
        self, mock_git_repo,
    ):
        """ASSETS_UPLOADED success marker gates resume-skip: assets are not
        re-uploaded, and the flow proceeds to publish."""
        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS) + ["ASSETS_UPLOADED"],
        )

        recording = _RecordingPipeline()
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.upload_release_assets") as mock_upload,
            patch("rlsbl.commands.release.load_pipelines",
                  return_value={"npm": recording}),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        mock_upload.assert_not_called()
        assert recording.publish_calls, "resume must proceed to publish"
        assert not os.path.exists(state_path)

    def test_resume_after_kill_during_assets(self, mock_git_repo):
        """State with only the mutating steps (killed during asset upload)
        is resumable: assets are uploaded and the release completes."""
        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS),
        )

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.upload_release_assets") as mock_upload,
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        mock_upload.assert_called_once()
        assert not os.path.exists(state_path)


# ---------------------------------------------------------------------------
# Non-fatal failures: deploy, post-release hooks
# ---------------------------------------------------------------------------


class TestNonFatalFailures:
    """"Non-fatal" means the release is NOT rolled back and stays resumable.

    It never meant "exit 0". A release that ends with a failed step reports
    that failure through its exit code and keeps its state file, so
    `rlsbl release resume` can re-attempt the step. The single decision
    point is the completion epilogue: any failure marker => nonzero, state
    preserved.
    """

    def test_deploy_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """A deploy failure does not roll the release back, but it must not
        be reported as success either: nonzero exit, state preserved."""
        from rlsbl.deploy import DeployResult

        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        deploy_cfg = [{"name": "prod", "type": "ssh"}]
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.release.read_deploy_config",
                  return_value=(deploy_cfg, [])),
            patch("rlsbl.commands.release.deploy_target",
                  return_value=DeployResult("prod", False, "ssh timed out")),
        ):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    _rc(),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path), (
            "a failed step must leave the state file behind so "
            "`rlsbl release resume` stays reachable"
        )
        state = load_release_state(state_path)
        assert "DEPLOYED" in state.get("failed_steps", {})

        captured = capsys.readouterr()
        assert "DEPLOYED" in captured.err
        assert "ssh timed out" in captured.err

    def test_post_hook_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """A post-release hook failure is not fatal to the published release,
        but it is still a failed step: nonzero exit, state preserved."""
        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        from rlsbl.commands.release.hooks import (
            run_release_hook as real_run_release_hook,
        )

        def failing_post_hook(hook_name, *args, **kwargs):
            if hook_name == "post-release":
                raise RuntimeError("hook exploded")
            return real_run_release_hook(hook_name, *args, **kwargs)

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.release.hooks.run_release_hook",
                  side_effect=failing_post_hook),
        ):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    _rc(),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path)
        state = load_release_state(state_path)
        assert "POST_HOOKS_RUN" in state.get("failed_steps", {})

        captured = capsys.readouterr()
        assert "POST_HOOKS_RUN" in captured.err
        assert "hook exploded" in captured.err

    def test_subtree_push_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """A failed subtree push used to print a bare warning and let the
        release exit 0. It is a tracked step now: nonzero exit, marker
        recorded, state preserved."""
        project_dir = _setup_subtree_monorepo(mock_git_repo)
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        state_path = get_state_path(
            project_dir,
            releasable_dir=resolve_releasable_dir(project_dir, str(mock_git_repo)),
        )

        def failing_subtree_run(cmd, args=None, timeout=120, env=None, cwd=None):
            if cmd == "git" and args and args[0] == "subtree":
                raise RuntimeError("subtree split exploded")
            return _fake_run_factory()(cmd, args=args, timeout=timeout,
                                       env=env, cwd=cwd)

        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=failing_subtree_run),
        ):
            with pytest.raises(SystemExit) as exc_info:
                resume_cmd(
                    load_release_state(state_path),
                    {"quiet": True, "skip-lock": True},
                    ctx=_make_subtree_ctx(mock_git_repo, project_dir),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path)
        state = load_release_state(state_path)
        assert "SUBTREE_PUBLISHED" in state.get("failed_steps", {})
        assert "subtree split exploded" in state["failed_steps"]["SUBTREE_PUBLISHED"]

        err = capsys.readouterr().err
        assert "SUBTREE_PUBLISHED" in err

    def test_mirror_release_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """Same for the mirror GitHub Release: a warning is not an outcome."""
        project_dir = _setup_subtree_monorepo(mock_git_repo)
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        state_path = get_state_path(
            project_dir,
            releasable_dir=resolve_releasable_dir(project_dir, str(mock_git_repo)),
        )

        def failing_mirror(*args, **kwargs):
            raise RuntimeError("mirror repo not found")

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped",
                  side_effect=failing_mirror),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
        ):
            with pytest.raises(SystemExit) as exc_info:
                resume_cmd(
                    load_release_state(state_path),
                    {"quiet": True, "skip-lock": True},
                    ctx=_make_subtree_ctx(mock_git_repo, project_dir),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path)
        state = load_release_state(state_path)
        assert "MIRROR_RELEASED" in state.get("failed_steps", {})

        err = capsys.readouterr().err
        assert "MIRROR_RELEASED" in err

    def test_resume_after_nonfatal_failure_completes_and_clears_state(
        self, mock_git_repo,
    ):
        """The preserved state is genuinely resumable: a resume that
        re-attempts the failed step successfully clears the failure marker,
        completes the release, and removes the state file."""
        from rlsbl.deploy import DeployResult

        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS)
            + ["ASSETS_UPLOADED", "PIPELINES_PUBLISHED"],
            failed_steps={"DEPLOYED": "deploy to prod failed: ssh timed out"},
        )

        deploy_cfg = [{"name": "prod", "type": "ssh"}]
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.read_deploy_config",
                  return_value=(deploy_cfg, [])),
            patch("rlsbl.commands.release.deploy_target",
                  return_value=DeployResult("prod", True, "deployed")),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        assert not os.path.exists(state_path), (
            "a resume that clears every failure marker must complete the "
            "release and remove the state file"
        )
