"""The Phase-A / Phase-B seam of `rlsbl release run`, pinned.

`release run --dry-run` is the flagship preview: the deepest and most
consequential command in rlsbl, previewed by RECORDING the first half of a real
release rather than by describing it. Four properties make that honest, and
each is pinned here because each is one refactor away from being lost:

1. **The boundary exists, and it is in the right place.** The preview reports
   Phase A -- everything through the candidate push, whose effects really were
   recorded -- then the boundary line, then Phase B as a DECLARED table. A
   reader must never mistake the second for the first, and the ordering is what
   says which is which.
2. **The executor reads only through declared result captures.** The plan
   builder does the reading; the executor issues effects. If the executor
   starts asking questions of its own, the preview is back to truncating at the
   first observe after a recorded mutation -- the exact defect this design
   removed.
3. **The threading is what the design says it is.** Exactly one value crosses
   the seam (``candidate_sha``), produced by one step and consumed by two.
4. **A preview cannot push, by construction.** Not by a flag check that a
   future edit could invert: `git push` is a recorded effect like any other,
   and no observe allowlist prefix exists that could make it execute.
"""

import ast
import inspect
from pathlib import Path

import pytest

from rlsbl.commands.release import phase_a
from rlsbl.commands.release.validate import (
    BOUNDARY_LINE,
    print_release_preview,
    _phase_b_rows,
)


# ---------------------------------------------------------------------------
# Fixture plan: a hand-built Phase-A plan of the canonical shape.
#
# Built rather than derived from a repo so the seam assertions describe the
# SEAM and not whatever a fixture project happens to contain. The end-to-end
# rendering of a real preview is exercised by the release integration tests.
# ---------------------------------------------------------------------------


def _fixture_plan():
    return phase_a.PhaseAPlan(
        steps=[
            phase_a.PlanStep(
                kind=phase_a.WRITE_TARGET_VERSION,
                release_step="VERSION_BUMPED",
                summary="bump npm version in . -> 1.2.0",
                payload={"target": "npm", "path": ".", "version": "1.2.0",
                         "primary": True},
            ),
            phase_a.PlanStep(
                kind=phase_a.COMMIT,
                release_step="COMMITTED",
                summary="commit 2 file(s) as 'v1.2.0'",
                payload={"message": "v1.2.0", "files": ["package.json"],
                         "cwd": ".", "autogenerated": False},
                produces=phase_a.CANDIDATE_SHA,
                capture=(phase_a.CANDIDATE_SHA, ["git", "rev-parse", "HEAD"], "."),
                marks=("COMMITTED",),
            ),
            phase_a.PlanStep(
                kind=phase_a.RECORD_CANDIDATE,
                release_step="BRANCH_PUSHED",
                summary="record the candidate in in-progress.json",
                payload={"path": "in-progress.json",
                         "ref": phase_a.StepRef(phase_a.CANDIDATE_SHA)},
            ),
            phase_a.PlanStep(
                kind=phase_a.PUSH_CANDIDATE,
                release_step="BRANCH_PUSHED",
                summary="run git push --no-verify origin <candidate_sha>:refs/heads/main",
                payload={
                    "argv": ["git", "push", "--no-verify", "origin",
                             phase_a.StepRef(
                                 phase_a.CANDIDATE_SHA,
                                 template=phase_a.SLOT + ":refs/heads/main",
                             )],
                    "timeout": 300,
                },
                marks=("BRANCH_PUSHED",),
            ),
        ],
        files_to_commit=["package.json", "CHANGELOG.md"],
    )


class _FixtureState:
    """The slice of ReleaseState the preview renderer reads."""

    new_version = "1.2.0"
    tag = "v1.2.0"
    branch = "main"
    changes_dir = ".rlsbl/changes"
    monorepo_name = None
    monorepo_project_path = None


# ---------------------------------------------------------------------------
# 1. The boundary sits between the recorded log and the declared table
# ---------------------------------------------------------------------------


class TestPreviewBoundary:

    def _render(self):
        lines = []
        print_release_preview(
            lines.append, _fixture_plan(), _FixtureState(),
            registry="npm", files_to_commit=["package.json", "CHANGELOG.md"],
        )
        return "\n".join(lines)

    def test_the_boundary_line_is_rendered(self):
        assert BOUNDARY_LINE in self._render()

    def test_the_boundary_names_ci_as_what_everything_below_waits_on(self):
        assert "CI" in BOUNDARY_LINE
        assert "below" in BOUNDARY_LINE

    def test_the_recorded_phase_a_log_is_above_the_boundary(self):
        text = self._render()
        # Every Phase-A step the plan issued must appear before the line.
        for step in _fixture_plan().steps:
            assert step.summary in text, f"missing Phase-A step: {step.summary}"
            assert text.index(step.summary) < text.index(BOUNDARY_LINE), (
                f"Phase-A step rendered BELOW the boundary: {step.summary!r}. "
                "Everything above the line is recorded fact; everything below "
                "it waits on CI. A recorded effect under the line reads as a "
                "promise instead of a record."
            )

    def test_the_declared_phase_b_table_is_below_the_boundary(self):
        text = self._render()
        rows = _phase_b_rows(_FixtureState(), registry="npm")
        assert rows, "Phase B must declare its steps"
        for step, _what in rows:
            assert step in text, f"missing Phase-B row: {step}"
            assert text.index(BOUNDARY_LINE) < text.rindex(step), (
                f"Phase-B row rendered ABOVE the boundary: {step!r}. Nothing "
                "below the line was recorded, and the line is the only thing "
                "saying so."
            )

    def test_phase_b_is_labelled_as_not_recorded(self):
        assert "NOT recorded" in self._render()

    def test_phase_b_covers_the_whole_remaining_release(self):
        """Every canonical step after BRANCH_PUSHED is declared."""
        from rlsbl.commands.release.release_state import RELEASE_STEPS

        declared = {step for step, _ in _phase_b_rows(
            # Monorepo state: the subtree/mirror rows are only owed there.
            type("S", (_FixtureState,), {
                "monorepo_name": "pkg", "monorepo_project_path": "pkg",
            })(),
            registry="npm",
        )}
        after_push = RELEASE_STEPS[RELEASE_STEPS.index("BRANCH_PUSHED") + 1:]
        missing = [s for s in after_push if s not in declared]
        assert not missing, (
            f"Phase B does not declare {missing}. A step the preview omits is "
            "a step the operator does not know is coming."
        )


# ---------------------------------------------------------------------------
# 2. The executor's reads are only the whitelisted result captures
# ---------------------------------------------------------------------------


# The ONLY function in the executor that may read. Everything the executor
# needs beyond the plan arrives through it.
_EXECUTOR_READ_WHITELIST = {"_capture"}

# Bare helper names that read the world. An executor method calling one of
# these is asking a question the builder was supposed to have answered.
_READ_CALLS = {"run", "run_gh", "head_sha", "_git_read", "_git_answer"}

# Binaries whose reads the framework really executes under --dry-run (they are
# on the observe allowlist). An ``effects.run`` in the executor with one of
# these as a LITERAL first operand is an observe -- a read wearing the
# chokepoint's clothes. A run whose argv comes from the plan is fine: that is
# the step's own effect.
_OBSERVE_BINARIES = {"git", "gh"}


def _is_literal_observe(call):
    """True when *call* is ``effects.run(["git", ...])`` with a literal argv."""
    func = call.func
    if not (isinstance(func, ast.Attribute) and func.attr == "run"):
        return False
    if not (isinstance(func.value, ast.Name)
            and func.value.id in ("effects", "_effects")):
        return False
    if not call.args:
        return False
    argv = call.args[0]
    if not isinstance(argv, (ast.List, ast.Tuple)) or not argv.elts:
        return False
    first = argv.elts[0]
    return isinstance(first, ast.Constant) and first.value in _OBSERVE_BINARIES


def _executor_methods():
    """(name, ast.FunctionDef) for every method of the Phase-A executor."""
    tree = ast.parse(inspect.getsource(phase_a))
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "_Executor":
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    yield item.name, item


class TestExecutorReads:

    def test_the_executor_class_is_there_to_scan(self):
        names = [name for name, _ in _executor_methods()]
        assert names, "no _Executor methods found -- the scan below is vacuous"
        assert "_capture" in names

    def test_only_the_result_capture_issues_a_read(self):
        offenders = []
        for name, fn in _executor_methods():
            if name in _EXECUTOR_READ_WHITELIST:
                continue
            for node in ast.walk(fn):
                if not isinstance(node, ast.Call):
                    continue
                func = node.func
                if isinstance(func, ast.Name) and func.id in _READ_CALLS:
                    offenders.append(f"{name}() calls {func.id}()")
                elif _is_literal_observe(node):
                    offenders.append(f"{name}() issues a literal git/gh observe")
        assert not offenders, (
            "the Phase-A executor derives nothing and asks nothing: its only "
            "permitted read is the per-step declared result capture "
            f"(_capture). Found: {offenders}. Move the read into "
            "build_phase_a_plan, or declare it as the step's capture."
        )

    def test_the_capture_is_declared_per_step_not_improvised(self):
        """Every capture the executor runs was named by the builder."""
        for step in _fixture_plan().steps:
            if step.produces:
                assert step.capture is not None, (
                    f"step {step.kind!r} produces {step.produces!r} without a "
                    "declared capture: the executor would have to invent the "
                    "read."
                )
                name, argv, _cwd = step.capture
                assert name == step.produces
                assert argv and argv[0] == "git"


# ---------------------------------------------------------------------------
# 3. Value threading: one producer, two consumers, one value
# ---------------------------------------------------------------------------


class TestValueThreading:

    def test_exactly_one_value_crosses_the_seam(self):
        plan = _fixture_plan()
        assert plan.produced_names == [phase_a.CANDIDATE_SHA]

    def test_the_commit_step_produces_it(self):
        plan = _fixture_plan()
        producers = [s for s in plan.steps if s.produces == phase_a.CANDIDATE_SHA]
        assert len(producers) == 1
        assert producers[0].kind in (phase_a.COMMIT, phase_a.SNAPSHOT)

    def test_the_state_save_and_the_push_consume_it(self):
        plan = _fixture_plan()
        consumers = plan.consumers_of(phase_a.CANDIDATE_SHA)
        assert [s.kind for s in consumers] == [
            phase_a.RECORD_CANDIDATE, phase_a.PUSH_CANDIDATE,
        ], (
            "Phase A threads exactly three edges: the commit yields "
            "candidate_sha, the state-save and the push consume it."
        )

    def test_a_step_ref_renders_its_template_in_the_plan_table(self):
        ref = phase_a.StepRef(
            phase_a.CANDIDATE_SHA, template=phase_a.SLOT + ":refs/heads/main",
        )
        assert ref.render() == "<candidate_sha>:refs/heads/main"

    def test_the_plan_table_names_the_produced_value(self):
        table = phase_a.render_plan_table(_fixture_plan())
        assert "-> candidate_sha" in table


# ---------------------------------------------------------------------------
# 4. A preview cannot push, by construction
# ---------------------------------------------------------------------------


class TestPreviewCannotPush:

    def test_no_observe_prefix_would_let_a_git_push_execute(self):
        """`git push` must never match the observe allowlist.

        An observe really runs under ``--dry-run``. A bare ``["git"]`` prefix
        -- or any prefix ``git push`` starts with -- would turn the release's
        candidate push into a real push during a preview. strictcli separately
        bans single-token prefixes; this pins the rlsbl-side consequence.
        """
        from rlsbl import app

        for prefix in app._proc_observe_allowlist:
            assert len(prefix) >= 2, (
                f"single-token observe prefix {list(prefix)!r}: it would make "
                "EVERY subcommand of that binary execute under --dry-run"
            )
            push = ("git", "push", "--no-verify", "origin", "HEAD:refs/heads/main")
            assert push[:len(prefix)] != tuple(prefix), (
                f"observe allowlist prefix {list(prefix)!r} matches `git push`: "
                "a preview would push for real"
            )

    def test_the_push_step_goes_through_the_effects_chokepoint(self):
        """The push is issued as an effect, so preview mode records it."""
        source = inspect.getsource(phase_a._Executor._do_push_candidate)
        assert "effects.run(" in source, (
            "the candidate push must be issued on the effects chokepoint; a "
            "direct subprocess would execute under --dry-run"
        )

    def test_the_chokepoint_exemption_list_does_not_cover_phase_a(self):
        """phase_a.py is not exempt from the chokepoint scan."""
        chokepoint = Path(__file__).with_name("test_effects_chokepoint.py")
        text = chokepoint.read_text()
        assert "phase_a" not in text, (
            "phase_a.py appears in the chokepoint test -- if it was added to "
            "the exemption list, the executor can bypass effects entirely"
        )


# ---------------------------------------------------------------------------
# 5. Rollback is an executor concern, never a plan step
# ---------------------------------------------------------------------------


class TestRollbackIsNotAPlanStep:

    def test_no_step_kind_undoes_anything(self):
        kinds = {
            v for k, v in vars(phase_a).items()
            if k.isupper() and isinstance(v, str) and not k.startswith("_")
        }
        forbidden = [
            k for k in kinds
            if any(word in k for word in ("rollback", "revert", "reset", "undo"))
        ]
        assert not forbidden, (
            f"Phase A declares undo steps {forbidden}. Rollback belongs to the "
            "executor's caller -- reset to the pre-release pin plus orphan "
            "cleanup -- so that a failure at any step unwinds the same way, "
            "and so a preview (which executes nothing) needs none."
        )

    def test_the_executor_never_resets(self):
        source = inspect.getsource(phase_a._Executor)
        assert "reset --hard" not in source
        assert '"reset"' not in source
        assert "tag -d" not in source


# ---------------------------------------------------------------------------
# 6. The preflight is OUTSIDE the plan
# ---------------------------------------------------------------------------


class TestPreflightIsOutsideThePlan:

    def test_the_builder_does_not_schedule_preflight_work(self):
        """Hooks, selfdoc and the schema dump are not Phase-A steps.

        The preflight keeps executing its observes and recording its mutations
        exactly as it always has, and its recorded effects render FIRST. Pulling
        it into the plan would put reads (its own checks) after the plan's
        writes, which is the arrangement the split exists to prevent.
        """
        source = inspect.getsource(phase_a.build_phase_a_plan)
        for helper in (
            "run_release_hook", "run_releasable_hooks",
            "_run_selfdoc_gen", "_run_selfdoc_check",
            "_run_strictcli_schema_dump", "_run_selfblog_post_generate",
            "run_checks",
        ):
            assert helper not in source, (
                f"the Phase-A plan builder calls {helper}(): the preflight "
                "stays outside the plan, executing its observes and recording "
                "its mutations as it always has, so that its effects render "
                "first and the plan's reads all happen before the plan's writes"
            )

    def test_no_hand_rolled_would_run_prints_remain_in_the_preflight(self):
        """The preflight's children are effects; recording is automatic.

        The resume preview's ``Would run: <remaining steps>`` line is a
        different thing and stays: it names STEPS, not an argv, and nothing
        records it. What must not come back is a hand-written restatement of a
        command the chokepoint already reports.
        """
        from rlsbl.commands.release import publish, validate

        for module in (validate, publish):
            source = inspect.getsource(module)
            for banned in (
                "Would run: selfdoc", "Would run: selfblog",
                "Would run: {' '.join(cmd)}",
            ):
                assert banned not in source, (
                    f"{module.__name__} hand-rolls {banned!r}. Its children go "
                    "through effects.run, so the framework's would-do log "
                    "already reports the real argv -- a second, hand-written "
                    "copy can only drift from it."
                )


@pytest.mark.parametrize("kind", sorted({
    v for k, v in vars(phase_a).items()
    if k.isupper() and isinstance(v, str) and not k.startswith("_")
    and k not in ("CANDIDATE_SHA", "SLOT")
}))
def test_every_step_kind_has_an_executor_handler(kind):
    """A plan step nothing can issue is a step that silently does nothing."""
    assert kind in phase_a._HANDLERS, (
        f"step kind {kind!r} has no handler: build_phase_a_plan could emit it "
        "and the executor would raise KeyError mid-release"
    )
