"""Integration tests for the pre-release flow against a real git repo.

Exercises the full release flow with preid="alpha" and bump="minor",
verifying that version files get PEP 440 format (e.g. 0.43.0a0), the
git tag uses semver format (v0.43.0-alpha.0), the GitHub Release is
created with --prerelease, and the JSONL changelog is finalized under
the semver version name.

Follows the pattern from test_release_integration.py.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


def _rc_prerelease(bump="minor", preid="alpha"):
    """Create a ReleaseConfig for a pre-release."""
    return ReleaseConfig(
        bump=bump,
        include=["pypi"],
        exclude=[],
        preid=preid,
        description="First alpha",
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_output(repo, *args):
    result = subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _git_head(repo):
    return _git_output(repo, "rev-parse", "HEAD")


def _setup_releasable_pypi_project(repo):
    """Create a PyPI project at v0.42.0 with one unreleased commit, ready for pre-release.

    Returns the SHA of the unreleased feature commit.
    """
    # pyproject.toml at v0.42.0
    (repo / "pyproject.toml").write_text(
        '[project]\nname = "test-pkg"\nversion = "0.42.0"\n\n'
        '[dependency-groups]\ndev = ["pytest"]\n'
    )

    # Package __init__.py with __version__
    pkg_dir = repo / "test_pkg"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text('__version__ = "0.42.0"\n')

    # Minimal passing test so preflight pytest check succeeds
    tests_dir = repo / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_dummy.py").write_text("def test_pass(): pass\n")

    # Ignore build artifacts created by uv run pytest
    (repo / ".gitignore").write_text("*.egg-info/\n.venv/\n__pycache__/\n")

    # CHANGELOG.md with 0.42.0 section
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 0.42.0\n\n- Initial release.\n"
    )

    # .rlsbl scaffolding
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"targets": ["pypi"], "private": False, "pipelines": {}}) + "\n"
    )

    _git(repo, "add",
         "pyproject.toml",
         "test_pkg/__init__.py",
         "tests/test_dummy.py",
         ".gitignore",
         "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl",
         ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v0.42.0")

    # Make an unreleased feature commit
    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    # Cover it with a JSONL entry (with Autogenerated trailer to self-exempt)
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(
        repo, "commit", "-q", "-m", "changelog: add feature entry",
        "--trailer", "Autogenerated: true",
    )

    # Create the release file with preid
    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "unreleased.toml").write_text(
        'bump = "minor"\npreid = "alpha"\n'
        'description = "First alpha"\n'
        'include = ["pypi"]\nexclude = []\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")

    return feature_sha


def _make_ctx(repo):
    """Build a ProjectContext pointing at repo."""
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config={"private": False, "pipelines": {}},
    )


def _fake_run_factory(gh_calls=None):
    """Create a fake_run that intercepts gh/push/fetch, passes everything else through.

    If gh_calls is provided (a list), appends (cmd, args) tuples for gh calls.
    """
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            if gh_calls is not None:
                gh_calls.append((cmd, list(args) if args else []))
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


class TestPrereleaseFullFlowRealGit:
    """Full pre-release with real git, intercepting only gh/push/fetch."""

    def test_prerelease_full_flow(self, mock_git_repo):
        _setup_releasable_pypi_project(mock_git_repo)

        gh_calls = []
        fake_run = _fake_run_factory(gh_calls=gh_calls)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
        ):
            run_cmd(
                _rc_prerelease(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # 1. pyproject.toml version is PEP 440 format: 0.43.0a0
        import tomllib
        with open(mock_git_repo / "pyproject.toml", "rb") as f:
            pyproject = tomllib.load(f)
        assert pyproject["project"]["version"] == "0.43.0a0", (
            f"Expected pyproject.toml version '0.43.0a0', got {pyproject['project']['version']!r}"
        )

        # 2. test_pkg/__init__.py has PEP 440 version
        init_content = (mock_git_repo / "test_pkg" / "__init__.py").read_text()
        assert '__version__ = "0.43.0a0"' in init_content, (
            f"Expected __version__ = '0.43.0a0' in __init__.py, got:\n{init_content}"
        )

        # 3. Git tag v0.43.0-alpha.0 exists (semver format)
        tag_output = _git_output(mock_git_repo, "tag", "-l", "v0.43.0-alpha.0")
        assert "v0.43.0-alpha.0" in tag_output, (
            f"Tag v0.43.0-alpha.0 should exist, got tags: {tag_output}"
        )

        # 4. gh release create was called with --prerelease flag
        # run_gh is fully mocked, so check the mock's calls instead
        # (run_gh is patched as a direct mock, not through fake_run)
        # We need to capture run_gh calls differently -- let's check via
        # the gh calls that go through the fake_run path.
        # Actually, run_gh is patched separately. Let me re-check.
        # Since run_gh is patched with return_value="", we can't capture args
        # through gh_calls (those only capture via fake_run).
        # The --prerelease flag is added based on "-" in new_version,
        # and 0.43.0-alpha.0 contains "-", so the flag will be added.
        # We verify this indirectly: the tag exists and version is correct.

        # 5. .rlsbl/changes/0.43.0-alpha.0.jsonl exists (finalized changelog)
        finalized_jsonl = mock_git_repo / ".rlsbl" / "changes" / "0.43.0-alpha.0.jsonl"
        assert finalized_jsonl.exists(), (
            f"Finalized JSONL file 0.43.0-alpha.0.jsonl should exist"
        )

        # 6. .rlsbl/releases/in-progress.json does NOT exist (cleaned up)
        in_progress = mock_git_repo / ".rlsbl" / "releases" / "in-progress.json"
        assert not in_progress.exists(), (
            "in-progress.json should not exist after successful release"
        )

        # 7. unreleased.jsonl exists and is empty (fresh)
        unreleased = mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl"
        assert unreleased.exists(), "unreleased.jsonl should exist after release"
        assert unreleased.read_text().strip() == "", (
            "unreleased.jsonl should be empty after release"
        )

        # 8. CHANGELOG.md contains the pre-release version heading
        changelog = (mock_git_repo / "CHANGELOG.md").read_text()
        assert "## 0.43.0-alpha.0" in changelog, (
            f"CHANGELOG.md should contain '## 0.43.0-alpha.0', got:\n{changelog}"
        )

    def test_prerelease_gh_release_gets_prerelease_flag(self, mock_git_repo):
        """Verify that gh release create is called with --prerelease for pre-release versions."""
        _setup_releasable_pypi_project(mock_git_repo)

        fake_run = _fake_run_factory()
        run_gh_calls = []

        def capturing_run_gh(args, **kwargs):
            run_gh_calls.append(list(args))
            # Simulate: release does not exist yet (view fails), create succeeds
            if args and args[0] == "release" and args[1] == "view":
                raise subprocess.CalledProcessError(1, "gh release view")
            return ""

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", side_effect=capturing_run_gh),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
        ):
            run_cmd(
                _rc_prerelease(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # Find the gh release create call
        create_calls = [
            c for c in run_gh_calls
            if len(c) >= 2 and c[0] == "release" and c[1] == "create"
        ]
        assert len(create_calls) >= 1, (
            f"Expected at least one 'gh release create' call, got: {run_gh_calls}"
        )

        # The create call should include --prerelease
        create_args = create_calls[0]
        assert "--prerelease" in create_args, (
            f"gh release create should include --prerelease flag, got: {create_args}"
        )

        # The tag should be the semver format
        assert "v0.43.0-alpha.0" in create_args, (
            f"gh release create should use tag v0.43.0-alpha.0, got: {create_args}"
        )
