"""Tests for releasable release state relocation.

Releasable releases used to write in-progress.json under the representative
member's ``.rlsbl/releases/`` — polluting the member package with state that
belongs to the releasable. The state now lives at
``.rlsbl-monorepo/releasables/<name>/releases/in-progress.json`` and ALL
derivations (executor, run guard, resume CLI, scrub) go through one resolver.

Covers:
- A releasable release writes ZERO files under the representative's
  ``.rlsbl/releases/`` — the preserved state (on post-release failure)
  lands in the releasable's own releases dir, and resume completes from it.
- The run guard reads the releasable state path, and detects legacy state
  at the old representative location with a migration-hint error.
- resolve_resume_source: member-dir resolution, workspace-root resolution
  (single in-flight releasable), ambiguity error, legacy-location error.
- Scrub state (scrub-result.json) relocates the same way.
- The changelog exemption already covers the new state path.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from rlsbl.commands.release import resume_cmd, run_cmd
from rlsbl.commands.release.release_state import (
    StateResolutionError,
    get_state_path,
    load_release_state,
    resolve_releasable_dir,
    resolve_resume_source,
    save_release_state,
)
from rlsbl.context import create_context
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run
from rlsbl.workspace import (
    Releasable,
    get_releasable_dir,
    get_releasable_changes_dir,
    save_workspace,
    write_releasable_version,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_head(repo):
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _rc(description="test release"):
    return ReleaseConfig(
        bump="patch",
        include=["npm"],
        exclude=[],
        description=description,
    )


def _setup_releasable_workspace(root):
    """Workspace with releasable 'alpha' whose sole member is packages/core.

    Returns the member (representative) directory path.
    """
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "user.email", "test@test.local")
    _git(root, "config", "user.name", "Test")

    core = root / "packages" / "core"
    core.mkdir(parents=True)
    (core / "package.json").write_text(
        json.dumps({"name": "core", "version": "1.0.0"}, indent=2) + "\n"
    )
    (core / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    (core / ".rlsbl").mkdir()
    (core / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"], "pipelines": {}}) + "\n"
    )

    save_workspace(
        str(root),
        [{"path": "packages/core", "name": "core", "releasable": "alpha"}],
        releasables=[Releasable(name="alpha")],
    )
    write_releasable_version(str(root), "alpha", "1.0.0")
    changes_dir = get_releasable_changes_dir(str(root), "alpha")
    os.makedirs(changes_dir, exist_ok=True)
    with open(os.path.join(changes_dir, "unreleased.jsonl"), "w") as f:
        f.write("")
    rel_dir = get_releasable_dir(str(root), "alpha")
    with open(os.path.join(rel_dir, "config.json"), "w") as f:
        f.write("{}\n")

    _git(root, "add", ".rlsbl-monorepo", "packages")
    _git(root, "commit", "-q", "-m", "initial")
    _git(root, "tag", "alpha@v1.0.0")

    # Member-scoped feature commit
    (core / "feature.txt").write_text("new feature\n")
    _git(root, "add", "packages/core/feature.txt")
    _git(root, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(root)

    # Cover it in the releasable-level changelog
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    with open(os.path.join(changes_dir, "unreleased.jsonl"), "w") as f:
        f.write(json.dumps(entry) + "\n")
    _git(root, "add", os.path.relpath(changes_dir, str(root)))
    _git(root, "commit", "-q", "-m", "changelog: add feature entry",
         "--trailer", "Autogenerated: true")

    return core


def _make_ctx(member_dir, root):
    return create_context(Path(str(member_dir)), workspace_root=Path(str(root)))


def _fake_run_factory():
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


def _releasable_state_path(root, name="alpha"):
    return get_state_path(
        "", releasable_dir=get_releasable_dir(str(root), name),
    )


# ---------------------------------------------------------------------------
# Executor writes state to the releasable location
# ---------------------------------------------------------------------------


class TestReleasableStateRelocation:

    def test_failed_release_preserves_state_at_releasable_path(
        self, tmp_project, capsys,
    ):
        """A releasable release that fails post-release (GitHub Release
        creation) preserves its state under the releasable's dir and writes
        NOTHING under the representative member's .rlsbl/releases/."""
        core = _setup_releasable_workspace(tmp_project)

        def failing_run_gh(args, **kwargs):
            if args and args[0] == "release" and args[1] in ("create", "view"):
                raise subprocess.CalledProcessError(1, f"gh release {args[1]}")
            return ""

        fake_run = _fake_run_factory()
        with pytest.raises(SystemExit):
            with (
                patch("rlsbl.commands.release.check_gh_installed", return_value=True),
                patch("rlsbl.commands.release.check_gh_auth", return_value=True),
                patch("rlsbl.commands.release.push_if_needed"),
                patch("rlsbl.commands.release.run_gh", side_effect=failing_run_gh),
                patch("rlsbl.commands.release.run", side_effect=fake_run),
                patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            ):
                run_cmd(
                    _rc(),
                    {"yes": True, "quiet": True, "skip-lock": True},
                    ctx=_make_ctx(core, tmp_project),
                )

        # State preserved at the releasable location
        rel_state_path = _releasable_state_path(tmp_project)
        assert os.path.exists(rel_state_path), (
            "in-progress.json must live under the releasable's releases dir"
        )
        state = load_release_state(rel_state_path)
        assert state["releasable_name"] == "alpha"
        assert "PUSHED" in state["completed_steps"]

        # ZERO pollution of the representative member
        rep_releases = core / ".rlsbl" / "releases"
        assert not rep_releases.exists(), (
            "releasable release must not create files under the "
            "representative's .rlsbl/releases/"
        )

    def test_resume_from_releasable_state_completes(self, tmp_project):
        """Resume picks up the releasable-located state and clears it."""
        core = _setup_releasable_workspace(tmp_project)

        # First, produce a preserved state via a failed GH release
        def failing_run_gh(args, **kwargs):
            if args and args[0] == "release" and args[1] in ("create", "view"):
                raise subprocess.CalledProcessError(1, f"gh release {args[1]}")
            return ""

        fake_run = _fake_run_factory()
        with pytest.raises(SystemExit):
            with (
                patch("rlsbl.commands.release.check_gh_installed", return_value=True),
                patch("rlsbl.commands.release.check_gh_auth", return_value=True),
                patch("rlsbl.commands.release.push_if_needed"),
                patch("rlsbl.commands.release.run_gh", side_effect=failing_run_gh),
                patch("rlsbl.commands.release.run", side_effect=fake_run),
                patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            ):
                run_cmd(
                    _rc(),
                    {"yes": True, "quiet": True, "skip-lock": True},
                    ctx=_make_ctx(core, tmp_project),
                )

        rel_state_path = _releasable_state_path(tmp_project)
        saved = load_release_state(rel_state_path)
        assert saved is not None

        # Resume with a working gh: completes and clears the state
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=_fake_run_factory()),
        ):
            resume_cmd(
                saved,
                {"yes": True, "quiet": True, "skip-lock": True},
                ctx=_make_ctx(core, tmp_project),
            )

        assert not os.path.exists(rel_state_path)
        assert not (core / ".rlsbl" / "releases").exists()


# ---------------------------------------------------------------------------
# Run guard: releasable path + legacy migration hint
# ---------------------------------------------------------------------------


class TestGuardReleasableAwareness:

    def test_guard_blocks_on_releasable_state(self, tmp_project, capsys):
        core = _setup_releasable_workspace(tmp_project)

        rel_state_path = _releasable_state_path(tmp_project)
        save_release_state(rel_state_path, {
            "new_version": "1.0.1",
            "completed_steps": ["VERSION_BUMPED", "COMMITTED"],
        })

        with pytest.raises(SystemExit):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True, "skip-lock": True},
                ctx=_make_ctx(core, tmp_project),
            )

        captured = capsys.readouterr()
        assert "previous release is in progress" in captured.err

    def test_guard_detects_legacy_state_with_migration_hint(
        self, tmp_project, capsys,
    ):
        """In-flight state at the OLD representative location must not be
        silently ignored: the guard errors with a migration hint."""
        core = _setup_releasable_workspace(tmp_project)

        legacy_path = get_state_path(str(core))
        save_release_state(legacy_path, {
            "new_version": "1.0.1",
            "completed_steps": ["VERSION_BUMPED"],
        })

        with pytest.raises(SystemExit):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True, "skip-lock": True},
                ctx=_make_ctx(core, tmp_project),
            )

        captured = capsys.readouterr()
        assert "legacy location" in captured.err
        assert legacy_path in captured.err
        assert _releasable_state_path(tmp_project) in captured.err


# ---------------------------------------------------------------------------
# Resume source resolution (CLI logic)
# ---------------------------------------------------------------------------


class TestResolveResumeSource:

    def test_standalone(self, tmp_project):
        project_dir, state_path = resolve_resume_source(None, cwd=".")
        assert project_dir == "."
        assert state_path == get_state_path(".")

    def test_member_dir_resolves_releasable_path(self, tmp_project, monkeypatch):
        core = _setup_releasable_workspace(tmp_project)
        monkeypatch.chdir(core)

        project_dir, state_path = resolve_resume_source(
            str(tmp_project), cwd=".",
        )
        assert os.path.realpath(project_dir) == os.path.realpath(str(core))
        assert os.path.realpath(state_path) == os.path.realpath(
            _releasable_state_path(tmp_project)
        )

    def test_member_dir_legacy_state_errors_with_hint(
        self, tmp_project, monkeypatch,
    ):
        core = _setup_releasable_workspace(tmp_project)
        legacy_path = get_state_path(str(core))
        save_release_state(legacy_path, {"completed_steps": []})
        monkeypatch.chdir(core)

        with pytest.raises(StateResolutionError, match="legacy location"):
            resolve_resume_source(str(tmp_project), cwd=".")

    def test_workspace_root_single_inflight_releasable(self, tmp_project):
        core = _setup_releasable_workspace(tmp_project)
        rel_state_path = _releasable_state_path(tmp_project)
        save_release_state(rel_state_path, {
            "new_version": "1.0.1",
            "completed_steps": [],
            "monorepo_name": "core",
            "releasable_name": "alpha",
        })

        project_dir, state_path = resolve_resume_source(
            str(tmp_project), cwd=str(tmp_project),
        )
        assert os.path.realpath(project_dir) == os.path.realpath(str(core))
        assert os.path.realpath(state_path) == os.path.realpath(rel_state_path)

    def test_workspace_root_no_inflight_errors(self, tmp_project):
        _setup_releasable_workspace(tmp_project)
        with pytest.raises(StateResolutionError, match="cannot resume from monorepo root"):
            resolve_resume_source(str(tmp_project), cwd=str(tmp_project))

    def test_workspace_root_ambiguous_errors(self, tmp_project):
        """Two releasables mid-release: resume from root must error clearly."""
        _setup_releasable_workspace(tmp_project)
        # Add a second releasable with in-flight state
        beta_dir = get_releasable_dir(str(tmp_project), "beta")
        os.makedirs(beta_dir, exist_ok=True)
        save_release_state(
            get_state_path("", releasable_dir=beta_dir),
            {"completed_steps": []},
        )
        save_release_state(
            _releasable_state_path(tmp_project, "alpha"),
            {"completed_steps": [], "monorepo_name": "core"},
        )

        with pytest.raises(StateResolutionError) as exc_info:
            resolve_resume_source(str(tmp_project), cwd=str(tmp_project))
        assert "alpha" in str(exc_info.value)
        assert "beta" in str(exc_info.value)


# ---------------------------------------------------------------------------
# resolve_releasable_dir
# ---------------------------------------------------------------------------


class TestResolveReleasableDir:

    def test_member_resolves(self, tmp_project):
        core = _setup_releasable_workspace(tmp_project)
        result = resolve_releasable_dir(str(core), str(tmp_project))
        assert result is not None
        assert os.path.realpath(result) == os.path.realpath(
            get_releasable_dir(str(tmp_project), "alpha")
        )

    def test_none_without_workspace(self, tmp_project):
        assert resolve_releasable_dir(str(tmp_project), None) is None

    def test_none_for_non_member(self, tmp_project):
        _setup_releasable_workspace(tmp_project)
        other = tmp_project / "packages" / "other"
        other.mkdir(parents=True)
        assert resolve_releasable_dir(str(other), str(tmp_project)) is None


# ---------------------------------------------------------------------------
# Scrub state relocation
# ---------------------------------------------------------------------------


class TestScrubStateRelocation:

    def test_stale_scrub_result_read_from_releasable_path(
        self, tmp_project, capsys,
    ):
        """Scrub reads scrub-result.json from the releasable releases dir
        for releasable member projects."""
        from rlsbl.commands.release.release_state import get_scrub_result_path
        from rlsbl.commands.release_scrub import run_cmd as scrub_run_cmd

        core = _setup_releasable_workspace(tmp_project)
        rel_dir = get_releasable_dir(str(tmp_project), "alpha")
        scrub_path = get_scrub_result_path(str(core), releasable_dir=rel_dir)
        os.makedirs(os.path.dirname(scrub_path), exist_ok=True)
        with open(scrub_path, "w") as f:
            json.dump({"new_head": "stale_sha", "completed_steps": []}, f)

        flags = {
            "pattern": "secret", "replace": "XXX",
            "reason": "test", "entire-history": True,
        }
        mod = "rlsbl.commands.release_scrub"
        with pytest.raises(SystemExit) as exc_info:
            with (
                patch(f"{mod}.require_tool"),
                patch(f"{mod}.run", MagicMock(
                    side_effect=["safegit 0.22.0", "different_sha"],
                )),
            ):
                scrub_run_cmd(flags, ctx=_make_ctx(core, tmp_project))
        assert exc_info.value.code == 1

        captured = capsys.readouterr()
        assert "stale scrub-result.json" in captured.err
        assert scrub_path in captured.err


# ---------------------------------------------------------------------------
# Batch orchestrator alignment
# ---------------------------------------------------------------------------


class TestBatchOrchestratorAlignment:
    """The batch orchestrator delegates to run_cmd per releasable; the
    releasable-aware state resolver and step model must hold end-to-end:
    the release completes, state is cleared, and the representative
    member's .rlsbl/ stays clean."""

    def test_batch_releasable_release_leaves_no_state(
        self, tmp_project, bypass_upfront_validation,
    ):
        from rlsbl.commands.monorepo.batch_release import _cmd_batch_release

        core = _setup_releasable_workspace(tmp_project)

        # Batch release file for the releasable
        releases_dir = tmp_project / ".rlsbl-monorepo" / "releases"
        releases_dir.mkdir(parents=True)
        (releases_dir / "unreleased.toml").write_text(
            '[releasables.alpha]\n'
            'bump = "patch"\n'
            'include = ["npm"]\n'
            'exclude = []\n'
            'description = "test release"\n'
        )
        _git(tmp_project, "add", ".rlsbl-monorepo/releases/unreleased.toml")
        _git(tmp_project, "commit", "-q", "-m", "add batch release file",
             "--trailer", "Autogenerated: true")

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            # The mocked release pushes the tag; model the remote as having it
            # so the batch archive gate (item_is_released) sees it as released.
            patch("rlsbl.commands.monorepo.batch_plan.tag_exists_on_remote",
                  return_value=True),
        ):
            _cmd_batch_release(
                {"yes": True, "quiet": True, "dry-run": False},
                tmp_project,
            )

        # Release completed: state cleared from the releasable location
        assert not os.path.exists(_releasable_state_path(tmp_project))
        # Representative member stays clean
        assert not (core / ".rlsbl" / "releases").exists()
        # Version bump actually happened
        pkg = json.loads((core / "package.json").read_text())
        assert pkg["version"] == "1.0.1"
        # Batch file finalized
        assert not (releases_dir / "unreleased.toml").exists()


# ---------------------------------------------------------------------------
# Changelog exemption covers the new state path
# ---------------------------------------------------------------------------


class TestExemptionCoversReleasableStatePath:

    def test_new_state_path_is_exempt(self):
        from rlsbl.changelog.exemptions import is_changelog_path

        assert is_changelog_path(
            ".rlsbl-monorepo/releasables/alpha/releases/in-progress.json"
        )
        # Also with a monorepo prefix
        assert is_changelog_path(
            "sub/.rlsbl-monorepo/releasables/alpha/releases/in-progress.json"
        )
