"""Tests for rlsbl.utils git helpers: has_staged_or_modified, commit_files_if_changed."""

import subprocess

import pytest

from unittest.mock import patch

from rlsbl.utils import commit_files_if_changed, has_staged_or_modified, remote_branch_exists


class TestHasStagedOrModified:
    """Tests for has_staged_or_modified using a real git repo."""

    def test_modified_file_detected(self, mock_git_repo):
        """A tracked file with unstaged changes is detected."""
        readme = mock_git_repo / "README.md"
        readme.write_text("modified content\n")
        assert has_staged_or_modified(["README.md"]) is True

    def test_staged_file_detected(self, mock_git_repo):
        """A file staged for commit is detected."""
        tracked = mock_git_repo / "tracked.txt"
        tracked.write_text("new file\n")
        subprocess.run(
            ["git", "add", "tracked.txt"],
            cwd=str(mock_git_repo),
            check=True,
        )
        assert has_staged_or_modified(["tracked.txt"]) is True

    def test_untracked_file_not_in_list(self, mock_git_repo):
        """An untracked file that is NOT in the paths list is not detected."""
        untracked = mock_git_repo / "untracked.txt"
        untracked.write_text("I am untracked\n")
        # Only check README.md which is clean
        assert has_staged_or_modified(["README.md"]) is False

    def test_clean_state_returns_false(self, mock_git_repo):
        """When no files are modified or staged, returns False."""
        assert has_staged_or_modified(["README.md"]) is False

    def test_nonexistent_path_returns_false(self, mock_git_repo):
        """A path that doesn't exist on disk returns False (no diff, no status)."""
        assert has_staged_or_modified(["does_not_exist.txt"]) is False

    def test_multiple_paths_one_dirty(self, mock_git_repo):
        """Returns True when at least one of multiple paths is dirty."""
        readme = mock_git_repo / "README.md"
        readme.write_text("changed\n")
        assert has_staged_or_modified(["nonexistent.txt", "README.md"]) is True

    def test_empty_paths_returns_false(self, mock_git_repo):
        """An empty paths list returns False."""
        assert has_staged_or_modified([]) is False


class TestCommitFilesIfChanged:
    """Tests for commit_files_if_changed using a real git repo."""

    def test_commits_when_files_changed(self, mock_git_repo):
        """When files have changes, commits them and returns True."""
        readme = mock_git_repo / "README.md"
        readme.write_text("updated content\n")
        result = commit_files_if_changed(
            "test commit", ["README.md"], autogenerated=False
        )
        assert result is True
        # Verify the commit was made
        log = subprocess.run(
            ["git", "log", "--oneline", "-1"],
            cwd=str(mock_git_repo),
            capture_output=True,
            text=True,
            check=True,
        )
        assert "test commit" in log.stdout

    def test_skips_when_files_unchanged(self, mock_git_repo, capsys):
        """When files are clean, prints skip message and returns False."""
        result = commit_files_if_changed("no-op", ["README.md"])
        assert result is False
        captured = capsys.readouterr()
        assert "No changes to commit." in captured.out

    def test_custom_skip_message(self, mock_git_repo, capsys):
        """Custom skip_message is printed when nothing changed."""
        result = commit_files_if_changed(
            "no-op", ["README.md"], skip_message="Nothing to do here."
        )
        assert result is False
        captured = capsys.readouterr()
        assert "Nothing to do here." in captured.out


class TestRemoteBranchExists:
    """Tests for remote_branch_exists -- mocked, no real git repo needed."""

    @patch("rlsbl.utils.run")
    def test_remote_branch_exists_returns_true(self, mock_run):
        """When the ref resolves, returns True."""
        mock_run.return_value = "abc123def456"
        assert remote_branch_exists("main") is True
        mock_run.assert_called_once_with(
            "git", ["rev-parse", "--verify", "origin/main"], cwd=None
        )

    @patch("rlsbl.utils.run")
    def test_remote_branch_exists_returns_false(self, mock_run):
        """When rev-parse fails, returns False."""
        mock_run.side_effect = subprocess.CalledProcessError(128, "git")
        assert remote_branch_exists("main") is False
