"""`changelog-coverage --releasable <root releasable>` answers for that releasable.

The root member's directory is the workspace root, so a check run naming the
root member's releasable looked, to the changelog checks, like a run over the
whole workspace: coverage reported every releasable's uncovered commits, a
commit touching only a nested member's files among them, and the same commit
once per releasable, unlabelled. ``changelog add`` refused that commit for the
root releasable, as its files belong to the nested member. The check now
answers for the releasable named, by the same ownership rule ``changelog add``
applies, and lines from several changelogs name the changelog each is about.
"""

import json
import subprocess

import pytest

from conftest import capture_all_checks, make_workspace

from rlsbl.workspace import Releasable, get_releasable_changes_dir


def _git(root, *args):
    return subprocess.run(
        ["git", *args], cwd=root, check=True, capture_output=True, text=True,
        timeout=30,
    ).stdout.strip()


@pytest.fixture
def workspace(tmp_project):
    root = tmp_project
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "user.email", "t@t.local")
    _git(root, "config", "user.name", "T")
    make_workspace(
        root,
        [
            {"path": ".", "name": "root", "releasable": "app"},
            {"path": "web", "name": "web", "releasable": "web"},
        ],
        releasables=[
            Releasable(name="app", tag_format="v{version}"),
            Releasable(name="web", tag_format="{name}@v{version}"),
        ],
    )
    for name in ("app", "web"):
        changes = get_releasable_changes_dir(str(root), name)
        subprocess.run(["mkdir", "-p", changes], check=True, timeout=30)
        with open(f"{changes}/unreleased.jsonl", "w") as f:
            f.write("")
    (root / "web").mkdir()
    (root / "web" / "package.json").write_text(json.dumps({"name": "web"}) + "\n")
    (root / "README.md").write_text("# app\n")
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "both")
    both = _git(root, "rev-parse", "HEAD")
    (root / "web" / "package.json").write_text(json.dumps({"name": "web", "keywords": ["x"]}) + "\n")
    _git(root, "commit", "-q", "-am", "web only")
    web_only = _git(root, "rev-parse", "HEAD")
    return root, both, web_only


def _coverage(monkeypatch, releasable):
    import rlsbl

    monkeypatch.setattr(rlsbl, "_check_releasable", releasable)
    ctx = rlsbl._check_context_factory()
    return capture_all_checks()["changelog-coverage"](ctx)


def _uncovered_lines(result):
    return [p.text for p in result.problems if "not covered" in p.text]


def test_the_root_releasable_lists_only_its_own_commits_once(workspace, monkeypatch):
    root, both, web_only = workspace
    result = _coverage(monkeypatch, "app")
    assert result.kind == "found"
    lines = _uncovered_lines(result)
    assert [line for line in lines if both[:12] in line] and len(lines) == 1, lines
    assert not [line for line in lines if web_only[:12] in line], lines

    # changelog add accepts, for the root releasable, the commit coverage lists.
    import rlsbl

    added = rlsbl.app.test(
        ["changelog", "add", "--commits", both, "--no-user-facing", "--no-auto-commit"],
    )
    assert added.exit_code == 0, added.stderr
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "changelog", "--trailer", "Autogenerated: true")
    assert _coverage(monkeypatch, "app").kind == "passed"


def test_changelog_add_refuses_the_nested_members_commit_at_the_root(workspace):
    import rlsbl

    _root, _both, web_only = workspace
    refused = rlsbl.app.test(
        ["changelog", "add", "--commits", web_only, "--no-user-facing", "--no-auto-commit"],
    )
    assert refused.exit_code != 0


def test_several_changelogs_label_their_lines(workspace):
    from rlsbl.check_context import WorkspaceCheckContext
    from rlsbl.context import create_context
    from rlsbl.workspace import load_releasables, load_workspace
    from rlsbl.workspace_graph import WorkspaceGraph

    root, both, _web_only = workspace
    projects = load_workspace(str(root))
    base = create_context(root, workspace_root=root)
    ctx = WorkspaceCheckContext(
        project_root=root, workspace_root=root, config=base.config,
        project=base.project, projects=projects,
        graph=WorkspaceGraph(str(root), projects),
        releasables=load_releasables(str(root), projects=projects),
    )
    lines = _uncovered_lines(capture_all_checks()["changelog-coverage"](ctx))
    assert any(line.startswith("app: ") and both[:12] in line for line in lines), lines
    assert any(line.startswith("web: ") and both[:12] in line for line in lines), lines
