"""Tests for monorepo sync command: workflow copying, router generation, cleanup."""

import json
import os
import stat
import subprocess
from unittest.mock import patch

import pytest

from rlsbl.commands.monorepo import (
    _cmd_init,
    _cmd_add,
    _build_project_template_vars,
    _cmd_sync,
    _generate_router,
    _inject_packages_dir,
    _inject_working_directory,
    _rewrite_version_file_inputs,
    parse_ci_workflow,
    emit_ci_workflow,
)
from rlsbl.workspace import load_workspace, WORKSPACE_DIR, WORKSPACE_FILE


CI_WORKFLOW = """\
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo test
"""

PUBLISH_WORKFLOW = """\
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo publish
"""


def _make_project(base_path, subdir, name=None, ci=True, publish=False):
    """Create a minimal npm project with optional CI and publish workflows."""
    proj_dir = os.path.join(str(base_path), subdir)
    os.makedirs(proj_dir, exist_ok=True)
    pkg_name = name or os.path.basename(subdir)
    with open(os.path.join(proj_dir, "package.json"), "w") as f:
        json.dump({"name": pkg_name, "version": "0.1.0"}, f)

    if ci:
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

    if publish:
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PUBLISH_WORKFLOW)

    return subdir


def _init_workspace_with_projects(base_path, project_specs):
    """Initialize workspace and add projects.

    project_specs: list of (subdir, kwargs_dict) tuples.
    Returns list of project names.
    """
    _cmd_init({}, project_root=".")
    names = []
    for subdir, kwargs in project_specs:
        _make_project(base_path, subdir, **kwargs)
        name = kwargs.get("name") or os.path.basename(subdir)
        flags = {}
        if "name" in kwargs:
            flags["name"] = kwargs["name"]
        _cmd_add([subdir], flags, project_root=".")
        names.append(name)
    # Commit the setup so safegit/git can work
    subprocess.run(["git", "add", "."], cwd=str(base_path), check=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", "setup workspace"],
        cwd=str(base_path), check=True,
    )
    return names


class TestInlineCISync:
    """Sync inlines project CI jobs into ci-router.yml instead of writing
    root-level reusable-workflow copies (GitHub rejects routers with 20+
    reusable-workflow calls)."""

    def test_no_root_copy_written(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        assert not dest.exists()
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        assert router.exists()

    def test_jobs_inlined_into_router(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        doc = parse_ci_workflow(content)
        # The 'test' job from tooling/ci.yml is inlined with a prefixed key
        assert "tooling-ci-test" in doc["jobs"]
        job = doc["jobs"]["tooling-ci-test"]
        # Reusable-workflow-era check-run naming preserved
        assert job["name"] == "tooling-ci / test"
        # Gated on the detect job
        assert list(job["needs"]) == ["detect"]
        assert job["if"] == "needs.detect.outputs.tooling == 'true'"
        # working-directory injected
        assert job["defaults"]["run"]["working-directory"] == "tooling"
        # No reusable workflow calls anywhere in the router
        assert "uses: ./.github/workflows/" not in content

    def test_header_comment(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "# DO NOT EDIT -- generated by rlsbl monorepo sync" in content

    def test_read_only_permissions(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        mode = stat.S_IMODE(os.stat(str(router)).st_mode)
        assert mode == 0o444

    def test_warns_missing_workflow(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": False}),
        ])
        # Auto-scaffold creates CI workflows; remove them to test the missing case
        import shutil
        wf_dir = mock_git_repo / "tooling" / ".github" / "workflows"
        if wf_dir.exists():
            shutil.rmtree(str(wf_dir))
        _cmd_sync({}, project_root=".")
        captured = capsys.readouterr()
        assert "Warning" in captured.err
        assert "tooling" in captured.err


class TestRouterGeneration:
    def test_router_generated(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        assert router.exists()

    def test_router_has_path_filters(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "tooling: 'tooling/**'" in content
        assert "core: 'core/**'" in content

    def test_router_has_conditional_jobs(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "needs.detect.outputs.tooling == 'true'" in content
        assert "needs.detect.outputs.core == 'true'" in content
        # Jobs are inlined with prefixed keys, not reusable workflow calls
        doc = parse_ci_workflow(content)
        assert "tooling-ci-test" in doc["jobs"]
        assert "core-ci-test" in doc["jobs"]
        assert "uses: ./.github/workflows/" not in content

    def test_publish_router(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True, "publish": True}),
            ("core", {"ci": True, "publish": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "publish.yml"
        assert router.exists()
        content = router.read_text()
        # Inline router has inlined jobs with tag prefix conditions
        assert "startsWith(github.ref_name, 'tooling@v')" in content
        assert "startsWith(github.ref_name, 'core@v')" in content
        # Jobs are inlined (prefixed job keys), not reusable workflow calls
        assert "tooling-publish:" in content
        assert "core-publish:" in content
        # No per-project publish wrappers should exist
        assert not (mock_git_repo / ".github" / "workflows" / "tooling-publish.yml").exists()
        assert not (mock_git_repo / ".github" / "workflows" / "core-publish.yml").exists()


class TestStaleCleanup:
    def test_removes_legacy_root_ci_copies(self, mock_git_repo, capsys):
        """Root-level {name}-ci*.yml copies from the pre-inline era are removed.

        Sync used to write per-project reusable-workflow copies at the root;
        the router now inlines all jobs, so every such copy is stale.
        """
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        # Plant legacy root copies (as older rlsbl versions wrote them)
        root_wf = mock_git_repo / ".github" / "workflows"
        root_wf.mkdir(parents=True, exist_ok=True)
        legacy_files = [
            root_wf / "tooling-ci.yml",
            root_wf / "removed-project-ci-pypi.yml",
            root_wf / "legacy-publish.yml",
        ]
        for f in legacy_files:
            f.write_text("# legacy generated copy\non: workflow_call\njobs: {}\n")
            os.chmod(str(f), 0o444)
        subprocess.run(["git", "add", "-f"] + [str(f) for f in legacy_files],
                       cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "legacy synced copies"],
            cwd=str(mock_git_repo), check=True,
        )

        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({}, project_root=".")

        for f in legacy_files:
            assert not f.exists(), f"stale workflow {f.name} not removed"
        # Router still present
        assert (root_wf / "ci-router.yml").exists()

        # Deletion should be committed -- working tree must be clean
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(mock_git_repo),
            capture_output=True, text=True,
        )
        assert result.stdout.strip() == "", (
            f"Working tree dirty after sync with stale deletion: {result.stdout}"
        )

    def test_removes_stale_workflows_after_project_removal(self, mock_git_repo, capsys):
        """Removing a project drops its jobs from the router on next sync."""
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({}, project_root=".")
        capsys.readouterr()

        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        assert "core-ci-test" in router.read_text()

        # Remove "core" from workspace
        from rlsbl.commands.monorepo import _cmd_remove
        _cmd_remove(["core"], {}, project_root=".")
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "remove core"],
            cwd=str(mock_git_repo), check=True,
        )

        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({}, project_root=".")

        content = router.read_text()
        assert "core-ci-test" not in content
        assert "tooling-ci-test" in content


class TestParseCIWorkflow:
    """Unit tests for parse_ci_workflow edge cases."""

    def test_multi_line_on_no_jobs(self):
        """Multi-line on: without jobs: returns None from parse_ci_workflow."""
        doc = parse_ci_workflow("on:\n  push:\n    branches: [main]\n")
        # No jobs: key means parse returns None
        assert doc is None


class TestInjectWorkingDirectory:
    """Unit tests for _inject_working_directory per-job merging behavior."""

    def test_basic_injection(self):
        """Single job with no existing defaults gets working-directory added."""
        content = (
            "on: push\n"
            "\n"
            "jobs:\n"
            "  test:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - run: echo hello\n"
        )
        doc = parse_ci_workflow(content)
        _inject_working_directory(doc, "myproject")
        result = emit_ci_workflow(doc)
        assert "working-directory: myproject" in result

    def test_per_job_injection(self):
        """Multiple jobs each get their own defaults.run.working-directory."""
        content = (
            "on: push\n"
            "\n"
            "jobs:\n"
            "  build:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - run: echo build\n"
            "  test:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - run: echo test\n"
            "  lint:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - run: echo lint\n"
        )
        doc = parse_ci_workflow(content)
        _inject_working_directory(doc, "myproject")
        result = emit_ci_workflow(doc)
        # Each job should have working-directory
        for job_name in ("build", "test", "lint"):
            job = doc['jobs'][job_name]
            assert job['defaults']['run']['working-directory'] == "myproject"

    def test_preserves_existing_defaults(self):
        """Job with existing defaults.run.shell keeps shell and gains working-directory."""
        content = (
            "on: push\n"
            "\n"
            "jobs:\n"
            "  test:\n"
            "    runs-on: ubuntu-latest\n"
            "    defaults:\n"
            "      run:\n"
            "        shell: bash\n"
            "    steps:\n"
            "      - run: echo hello\n"
        )
        doc = parse_ci_workflow(content)
        _inject_working_directory(doc, "myproject")
        result = emit_ci_workflow(doc)
        assert "working-directory: myproject" in result
        assert "shell: bash" in result

    def test_existing_working_directory_not_overwritten(self):
        """Job with existing working-directory keeps its value, not overwritten."""
        content = (
            "on: push\n"
            "\n"
            "jobs:\n"
            "  test:\n"
            "    runs-on: ubuntu-latest\n"
            "    defaults:\n"
            "      run:\n"
            "        working-directory: custom/path\n"
            "    steps:\n"
            "      - run: echo hello\n"
        )
        doc = parse_ci_workflow(content)
        _inject_working_directory(doc, "myproject")
        result = emit_ci_workflow(doc)
        assert "working-directory: custom/path" in result
        assert "working-directory: myproject" not in result

    def test_trailing_slash_stripped(self):
        """Path with trailing slash is stripped before injection."""
        content = (
            "on: push\n"
            "\n"
            "jobs:\n"
            "  test:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - run: echo hello\n"
        )
        doc = parse_ci_workflow(content)
        _inject_working_directory(doc, "myproject/")
        result = emit_ci_workflow(doc)
        assert "working-directory: myproject\n" in result
        assert "working-directory: myproject/" not in result


class TestRouterWatchPaths:
    """Tests for watch path support in CI router generation."""

    def test_router_without_watch_paths(self):
        """Projects without watch key use single-line filter format."""
        projects = [
            {"name": "tooling", "path": "tooling"},
            {"name": "core", "path": "core"},
        ]
        content = _generate_router(projects)
        assert "tooling: 'tooling/**'" in content
        assert "core: 'core/**'" in content

    def test_router_with_watch_paths(self):
        """Projects with watch key use multi-line list filter format."""
        projects = [
            {"name": "tooling", "path": "tooling", "watch": ["Package.swift", "shared/**"]},
        ]
        content = _generate_router(projects)
        # The filters block is a literal string inside the YAML; check content
        # without assuming exact outer indentation
        assert "tooling:" in content
        assert "- 'tooling/**'" in content
        assert "- 'Package.swift'" in content
        assert "- 'shared/**'" in content
        # Must NOT have single-line format
        assert "tooling: 'tooling/**'" not in content

    def test_router_mixed_watch_and_no_watch(self):
        """Mixed projects: watch uses multi-line, no-watch uses single-line."""
        projects = [
            {"name": "tooling", "path": "tooling", "watch": ["Package.swift", "shared/**"]},
            {"name": "core", "path": "core"},
        ]
        content = _generate_router(projects)
        # tooling: multi-line (inside literal string filters block)
        assert "tooling:" in content
        assert "- 'tooling/**'" in content
        assert "- 'Package.swift'" in content
        assert "- 'shared/**'" in content
        # core: single-line
        assert "core: 'core/**'" in content


class TestSwiftSubtreeWarning:
    """Tests for the Swift subtree_remote warning in monorepo sync."""

    def test_warns_swift_without_subtree_remote(self, mock_git_repo, capsys):
        """Sync warns when a Swift project lacks subtree_remote."""
        _cmd_init({}, project_root=".")
        # Create a Swift project (Package.swift triggers swift target detection)
        proj_dir = os.path.join(str(mock_git_repo), "swiftpkg")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "Package.swift"), "w") as f:
            f.write("// swift-tools-version:5.9\n")
        # Also need a version file for detect_targets
        with open(os.path.join(proj_dir, "VERSION"), "w") as f:
            f.write("0.1.0\n")
        # Create a minimal CI workflow so sync has something to process
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)
        _cmd_add(["swiftpkg"], {}, project_root=".")
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup swift project"],
            cwd=str(mock_git_repo), check=True,
        )
        capsys.readouterr()
        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({}, project_root=".")
        captured = capsys.readouterr()
        assert "Warning" in captured.err
        assert "swiftpkg" in captured.err
        assert "subtree_remote" in captured.err
        assert "SPM" in captured.err


class TestAutoCommit:
    def test_sync_commits_changes(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({}, project_root=".")
        # Working tree should be clean after sync
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(mock_git_repo),
            capture_output=True, text=True,
        )
        assert result.stdout.strip() == ""


GO_CI_WORKFLOW = """\
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./...
"""

PYPI_PUBLISH_WORKFLOW = """\
name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
"""

PYPI_PUBLISH_WITH_EXISTING_WITH = """\
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
"""


class TestTrailingSlashStripped:
    """Bug fix: paths like 'python/' should not produce '//' in output."""

    def test_router_no_double_slash(self):
        """Trailing slash in path does not produce // in router glob."""
        projects = [
            {"name": "mypkg", "path": "python/"},
        ]
        content = _generate_router(projects)
        assert "//" not in content
        assert "'python/**'" in content

    def test_router_watch_no_double_slash(self):
        """Trailing slash with watch paths does not produce //."""
        projects = [
            {"name": "mypkg", "path": "python/", "watch": ["shared/**"]},
        ]
        content = _generate_router(projects)
        assert "//" not in content
        assert "'python/**'" in content

    def test_router_working_directory_no_double_slash(self, mock_git_repo, capsys):
        """Inlined router jobs do not contain // from trailing slash."""
        # Create project with trailing-slash path
        proj_dir = os.path.join(str(mock_git_repo), "python")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "package.json"), "w") as f:
            json.dump({"name": "mypkg", "version": "0.1.0"}, f)
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        _cmd_init({}, project_root=".")
        # Manually add with trailing-slash path in workspace
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "python/", "name": "mypkg"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "python//" not in content
        assert "working-directory: python\n" in content

    def test_working_directory_no_trailing_slash(self, mock_git_repo, capsys):
        """working-directory value should not have a trailing slash."""
        proj_dir = os.path.join(str(mock_git_repo), "lib")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "package.json"), "w") as f:
            json.dump({"name": "mylib", "version": "0.1.0"}, f)
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "lib/", "name": "mylib"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "working-directory: lib\n" in content
        assert "working-directory: lib/\n" not in content


class TestVersionFileRewrite:
    """Bug fix: action with: inputs for version files must be rewritten."""

    def test_go_version_file_rewritten(self):
        """go-version-file: go.mod becomes go-version-file: myproj/go.mod."""
        doc = parse_ci_workflow(GO_CI_WORKFLOW)
        _rewrite_version_file_inputs(doc, "myproj")
        result = emit_ci_workflow(doc)
        assert "go-version-file: myproj/go.mod" in result
        assert "go-version-file: go.mod" not in result

    def test_already_prefixed_not_doubled(self):
        """If go-version-file already has the project path, don't double it."""
        content = GO_CI_WORKFLOW.replace(
            "go-version-file: go.mod",
            "go-version-file: myproj/go.mod",
        )
        doc = parse_ci_workflow(content)
        _rewrite_version_file_inputs(doc, "myproj")
        result = emit_ci_workflow(doc)
        assert "go-version-file: myproj/go.mod" in result
        assert "myproj/myproj/" not in result

    def test_absolute_path_not_rewritten(self):
        """Absolute paths are left alone."""
        content = GO_CI_WORKFLOW.replace(
            "go-version-file: go.mod",
            "go-version-file: /etc/go.mod",
        )
        doc = parse_ci_workflow(content)
        _rewrite_version_file_inputs(doc, "myproj")
        result = emit_ci_workflow(doc)
        assert "go-version-file: /etc/go.mod" in result

    def test_integration_go_version_file(self, mock_git_repo, capsys):
        """Full sync rewrites go-version-file for a Go project."""
        proj_dir = os.path.join(str(mock_git_repo), "gomod")
        os.makedirs(proj_dir, exist_ok=True)
        # go.mod triggers Go target detection
        with open(os.path.join(proj_dir, "go.mod"), "w") as f:
            f.write("module example.com/gomod\n\ngo 1.21\n")
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(GO_CI_WORKFLOW)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "gomod", "name": "gomod"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "go-version-file: gomod/go.mod" in content
        assert "go-version-file: go.mod" not in content


class TestPackagesDirInjection:
    """Bug fix: pypa/gh-action-pypi-publish needs packages-dir in monorepo."""

    def test_packages_dir_injected_no_with(self):
        """When no with: block exists, one is created with packages-dir."""
        doc = parse_ci_workflow(PYPI_PUBLISH_WORKFLOW)
        _inject_packages_dir(doc, "python")
        result = emit_ci_workflow(doc)
        assert "packages-dir: python/dist/" in result

    def test_packages_dir_injected_existing_with(self):
        """When with: block exists, packages-dir is added to it."""
        doc = parse_ci_workflow(PYPI_PUBLISH_WITH_EXISTING_WITH)
        _inject_packages_dir(doc, "python")
        result = emit_ci_workflow(doc)
        assert "packages-dir: python/dist/" in result
        assert "verbose: true" in result

    def test_packages_dir_not_doubled(self):
        """If packages-dir already present, don't add another."""
        content = PYPI_PUBLISH_WITH_EXISTING_WITH.replace(
            "verbose: true",
            "verbose: true\n          packages-dir: python/dist/",
        )
        doc = parse_ci_workflow(content)
        _inject_packages_dir(doc, "python")
        result = emit_ci_workflow(doc)
        assert result.count("packages-dir") == 1

    def test_integration_pypi_publish(self, mock_git_repo, capsys):
        """Full sync inlines publish jobs with packages-dir for PyPI."""
        proj_dir = os.path.join(str(mock_git_repo), "mypylib")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "pyproject.toml"), "w") as f:
            f.write('[project]\nname = "mypylib"\nversion = "0.1.0"\n')
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PYPI_PUBLISH_WORKFLOW)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "mypylib", "name": "mypylib"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        # Per-project publish wrappers no longer exist
        assert not (mock_git_repo / ".github" / "workflows" / "mypylib-publish.yml").exists()
        # packages-dir is in the inline publish router
        router = mock_git_repo / ".github" / "workflows" / "publish.yml"
        content = router.read_text()
        assert "packages-dir: mypylib/dist/" in content


class TestDotPathSelfReference:
    """Bug fix: path='.' must not wrap the generated router as a source workflow."""

    def test_publish_router_not_used_as_source(self, mock_git_repo, capsys):
        """When path='.', the generated publish router must never be read back
        as its own source. The root publisher now regenerates from config
        templates, so its publish.yml (which IS the router output) is never
        parsed as a source workflow -- proven by byte-stability across syncs
        and by the hand-authored source content being gone after the first
        sync.
        """
        # Root pypi package with a hand-authored, ungated publish.yml.
        wf_dir = os.path.join(str(mock_git_repo), ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PUBLISH_WORKFLOW)  # contains `run: echo publish`
        with open(os.path.join(str(mock_git_repo), "pyproject.toml"), "w") as f:
            f.write('[project]\nname = "orxtra"\nversion = "1.2.3"\n')

        _cmd_init({}, project_root=".")
        mono = os.path.join(str(mock_git_repo), ".rlsbl-monorepo")
        rel_dir = os.path.join(mono, "releasables", "orxtra")
        os.makedirs(rel_dir, exist_ok=True)
        with open(os.path.join(rel_dir, "config.json"), "w") as f:
            json.dump(
                {
                    "publish_mode": "ci",
                    "targets": ["pypi"],
                    "publish_gate_check_regex": r"^(test)( \(.*\))?$",
                },
                f,
            )
        with open(os.path.join(mono, "workspace.toml"), "w") as f:
            f.write(
                '[[releasables]]\nname = "orxtra"\n\n'
                '[[projects]]\npath = "."\nreleasable = "orxtra"\n'
            )
        subprocess.run(["git", "add", "-A"], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        publish = mock_git_repo / ".github" / "workflows" / "publish.yml"

        # First sync: the hand-authored ungated publish.yml is replaced by the
        # config-generated gated router.
        _cmd_sync({}, project_root=".")
        first = publish.read_text()
        assert "# DO NOT EDIT" in first
        # The hand-authored source content is gone (regenerated from config).
        assert "echo publish" not in first
        # The router is gated.
        assert "\n  gate:\n" in first

        # Second sync: the router is regenerated from config, NEVER read back
        # as a source. Idempotent by construction -> byte-identical.
        _cmd_sync({}, project_root=".")
        second = publish.read_text()
        assert first == second

        # Per-project publish wrappers are never generated in the inline flow.
        assert not (mock_git_repo / ".github" / "workflows" / "orxtra-publish.yml").exists()

    def test_ci_router_not_used_as_source(self, mock_git_repo, capsys):
        """When path='.', the CI router at .github/workflows/ci-router.yml
        is never the source (it's ci-router.yml, not ci.yml), but test
        the path='.' scenario still works for CI."""
        wf_dir = os.path.join(str(mock_git_repo), ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        with open(os.path.join(str(mock_git_repo), "package.json"), "w") as f:
            json.dump({"name": "rootpkg", "version": "0.1.0"}, f)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": ".", "name": "rootpkg"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        # CI jobs should be inlined normally (ci.yml != ci-router.yml)
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        doc = parse_ci_workflow(content)
        assert "rootpkg-ci-test" in doc["jobs"]
        # No root-level reusable copy is written
        assert not (mock_git_repo / ".github" / "workflows" / "rootpkg-ci.yml").exists()


PYPI_CI_WITH_TEMPLATE_VARS = """\
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # requires-python: >= {{pypi.minRequiredPython}}
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - run: uv run pytest
"""

GO_CI_WITH_TEMPLATE_VARS = """\
name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # min go version: {{go.minRequiredGo}}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./...
"""


class TestTemplateVarResolution:
    """Tests for resolving {{...}} template variables during sync."""

    def test_pypi_template_var_resolved(self, mock_git_repo, capsys):
        """{{pypi.minRequiredPython}} in CI workflow comments is resolved during sync."""
        proj_dir = os.path.join(str(mock_git_repo), "mypylib")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "pyproject.toml"), "w") as f:
            f.write(
                '[project]\nname = "mypylib"\nversion = "0.1.0"\n'
                'requires-python = ">= 3.11"\n'
            )
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(PYPI_CI_WITH_TEMPLATE_VARS)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "mypylib", "name": "mypylib"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        # The template var should be resolved to the actual version
        assert "3.11" in content
        # The literal {{...}} pattern should NOT appear
        assert "{{pypi.minRequiredPython}}" not in content

    def test_go_template_var_resolved(self, mock_git_repo, capsys):
        """{{go.minRequiredGo}} in CI workflow comments is resolved during sync."""
        proj_dir = os.path.join(str(mock_git_repo), "mygomod")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "go.mod"), "w") as f:
            f.write("module example.com/mygomod\n\ngo 1.22\n")
        # Go target needs a VERSION file
        with open(os.path.join(proj_dir, "VERSION"), "w") as f:
            f.write("0.1.0\n")
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(GO_CI_WITH_TEMPLATE_VARS)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "mygomod", "name": "mygomod"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        # The template var should be resolved to the actual Go version
        assert "1.22" in content
        assert "{{go.minRequiredGo}}" not in content

    def test_no_template_vars_still_works(self, mock_git_repo, capsys):
        """CI workflow without any {{...}} patterns is synced normally."""
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        doc = parse_ci_workflow(content)
        assert "tooling-ci-test" in doc["jobs"]

    def test_github_actions_expressions_preserved(self, mock_git_repo, capsys):
        """${{ ... }} GitHub Actions expressions are not touched by template resolution."""
        proj_dir = os.path.join(str(mock_git_repo), "mypylib")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "pyproject.toml"), "w") as f:
            f.write(
                '[project]\nname = "mypylib"\nversion = "0.1.0"\n'
                'requires-python = ">= 3.11"\n'
            )
        ci_content = """\
name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # requires-python: >= {{pypi.minRequiredPython}}
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - run: uv python install ${{ matrix.python-version }}
"""
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(ci_content)

        _cmd_init({}, project_root=".")
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "mypylib", "name": "mypylib"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({}, project_root=".")
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        # rlsbl template var resolved
        assert "{{pypi.minRequiredPython}}" not in content
        # GitHub Actions expression preserved
        assert "matrix.python-version" in content


class TestBuildProjectTemplateVars:
    """Unit tests for _build_project_template_vars."""

    def test_pypi_project_vars(self, mock_git_repo):
        """PyPI project returns namespaced and un-namespaced vars."""
        proj_dir = os.path.join(str(mock_git_repo), "mypkg")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "pyproject.toml"), "w") as f:
            f.write(
                '[project]\nname = "mypkg"\nversion = "1.0.0"\n'
                'requires-python = ">= 3.12"\n'
            )
        tvars = _build_project_template_vars(proj_dir, str(mock_git_repo))
        # Namespaced key should exist
        assert tvars.get("pypi.minRequiredPython") == "3.12"
        # Un-namespaced key should also exist
        assert tvars.get("minRequiredPython") == "3.12"

    def test_go_project_vars(self, mock_git_repo):
        """Go project returns namespaced and un-namespaced vars."""
        proj_dir = os.path.join(str(mock_git_repo), "gomod")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "go.mod"), "w") as f:
            f.write("module example.com/gomod\n\ngo 1.23\n")
        with open(os.path.join(proj_dir, "VERSION"), "w") as f:
            f.write("0.1.0\n")
        tvars = _build_project_template_vars(proj_dir, str(mock_git_repo))
        assert tvars.get("go.minRequiredGo") == "1.23"
        assert tvars.get("minRequiredGo") == "1.23"

    def test_no_targets_returns_empty(self, mock_git_repo):
        """Directory with no detectable targets returns empty dict."""
        proj_dir = os.path.join(str(mock_git_repo), "empty")
        os.makedirs(proj_dir, exist_ok=True)
        tvars = _build_project_template_vars(proj_dir, str(mock_git_repo))
        assert tvars == {}


class TestRootPublisherSync:
    """End-to-end: `_cmd_sync` on a root (path='.') pypi publisher generates a
    gated publish.yml router from config instead of leaving the hand-authored
    ungated publish.yml in place."""

    def _setup_root_publisher_workspace(self, repo, *, gate_regex):
        root = str(repo)
        # Root package pyproject.toml
        with open(os.path.join(root, "pyproject.toml"), "w") as f:
            f.write('[project]\nname = "orxtra"\nversion = "1.2.3"\n')

        # Hand-authored (ungated) root publish.yml -- its presence is the
        # signal that the root publishes (it becomes the router output).
        wf_dir = os.path.join(root, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PUBLISH_WORKFLOW)

        mono = os.path.join(root, ".rlsbl-monorepo")
        rel_dir = os.path.join(mono, "releasables", "orxtra")
        os.makedirs(rel_dir, exist_ok=True)
        cfg = {"publish_mode": "ci", "targets": ["pypi"]}
        if gate_regex is not None:
            cfg["publish_gate_check_regex"] = gate_regex
        with open(os.path.join(rel_dir, "config.json"), "w") as f:
            json.dump(cfg, f)

        with open(os.path.join(mono, "workspace.toml"), "w") as f:
            f.write(
                '[[releasables]]\nname = "orxtra"\n\n'
                '[[projects]]\npath = "."\nreleasable = "orxtra"\n'
            )
        subprocess.run(["git", "add", "-A"], cwd=root, check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup root publisher"],
            cwd=root, check=True,
        )

    def test_root_publisher_generates_gated_router(self, mock_git_repo, capsys):
        regex = r"^(test)( \(.*\))?$"
        self._setup_root_publisher_workspace(mock_git_repo, gate_regex=regex)
        _cmd_sync({}, project_root=".")

        publish = mock_git_repo / ".github" / "workflows" / "publish.yml"
        assert publish.exists()
        content = publish.read_text()
        assert "# DO NOT EDIT" in content
        doc = parse_ci_workflow(content)
        jobs = doc["jobs"]
        assert "gate" in jobs
        assert any(k.startswith("orxtra-") for k in jobs)
        # The mandatory configured gate regex is baked into the router.
        assert regex in content
        # Generated router is read-only.
        mode = stat.S_IMODE(os.stat(str(publish)).st_mode)
        assert mode == 0o444

    def test_root_publisher_missing_gate_key_errors(self, mock_git_repo, capsys):
        self._setup_root_publisher_workspace(mock_git_repo, gate_regex=None)
        from rlsbl.errors import ConfigError

        with pytest.raises(ConfigError) as exc:
            _cmd_sync({}, project_root=".")
        assert "publish_gate_check_regex" in str(exc.value)
