"""Integration tests for the release flow against a real git repo.

Uses a real git repository with minimal mocking: only `gh` CLI calls and
`git push` / `git fetch` are intercepted. Everything else (git operations,
changelog validation, version bumping) runs for real.

Follows the pattern from test_release_finalize_md.py.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


def _rc(bump="patch", include=None, exclude=None):
    """Shorthand for creating a ReleaseConfig with sensible defaults."""
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_output(repo, *args):
    result = subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _git_head(repo):
    return _git_output(repo, "rev-parse", "HEAD")


def _setup_releasable_npm_project(repo):
    """Create an npm project at v1.0.0 with one unreleased commit, ready to release.

    Returns the SHA of the unreleased feature commit.
    """
    # package.json at v1.0.0
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )

    # CHANGELOG.md with 1.0.0 section
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ — do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )

    # .rlsbl scaffolding
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"private": False, "targets": ["npm"]}) + "\n"
    )

    _git(repo, "add",
         "package.json",
         "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl",
         ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    # Make an unreleased feature commit
    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    # Cover it with a JSONL entry (with Autogenerated trailer to self-exempt)
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(
        repo, "commit", "-q", "-m", "changelog: add feature entry",
        "--trailer", "Autogenerated: true",
    )

    # Create the release file
    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "unreleased.toml").write_text(
        'bump = "patch"\ninclude = ["npm"]\nexclude = []\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")

    return feature_sha


def _make_ctx(repo):
    """Build a ProjectContext pointing at repo."""
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config={"private": False, "pipelines": {}},
    )


def _fake_run_factory():
    """Create a fake_run that intercepts gh/push/fetch, passes everything else through."""
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


class TestReleaseDryRunFullFlow:
    """Test 1: dry-run release prints expected version without modifying files."""

    def test_release_dry_run_full_flow(self, mock_git_repo, capsys):
        _setup_releasable_npm_project(mock_git_repo)

        # Snapshot file state before dry-run
        pkg_before = (mock_git_repo / "package.json").read_text()
        changelog_before = (mock_git_repo / "CHANGELOG.md").read_text()
        jsonl_before = (mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl").read_text()

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
        ):
            run_cmd(
                _rc(),
                {"dry-run": True, "yes": True, "quiet": False},
                ctx=_make_ctx(mock_git_repo),
            )

        captured = capsys.readouterr()

        # Dry-run should print the target version
        assert "1.0.1" in captured.out, (
            f"Expected '1.0.1' in dry-run output, got:\n{captured.out}"
        )

        # Release-relevant files should not be modified
        assert (mock_git_repo / "package.json").read_text() == pkg_before
        assert (mock_git_repo / "CHANGELOG.md").read_text() == changelog_before
        assert (mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl").read_text() == jsonl_before

        # No new tags
        tags = _git_output(mock_git_repo, "tag", "-l", "v1.0.1")
        assert tags == "", "Dry-run should not create a tag"


class TestReleaseFullFlowRealGit:
    """Test 2: full release with real git, intercepting only gh/push/fetch."""

    def test_release_full_flow_real_git(self, mock_git_repo):
        _setup_releasable_npm_project(mock_git_repo)

        fake_run = _fake_run_factory()

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
        ):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # 1. package.json has version 1.0.1
        pkg = json.loads((mock_git_repo / "package.json").read_text())
        assert pkg["version"] == "1.0.1", f"Expected version 1.0.1, got {pkg['version']}"

        # 2. git tag v1.0.1 exists
        tag_output = _git_output(mock_git_repo, "tag", "-l", "v1.0.1")
        assert "v1.0.1" in tag_output, "Tag v1.0.1 should exist"

        # 3. CHANGELOG.md contains ## 1.0.1
        changelog = (mock_git_repo / "CHANGELOG.md").read_text()
        assert "## 1.0.1" in changelog, (
            f"CHANGELOG.md should contain '## 1.0.1', got:\n{changelog}"
        )

        # 4. .rlsbl/changes/1.0.1.jsonl exists
        assert (mock_git_repo / ".rlsbl" / "changes" / "1.0.1.jsonl").exists(), (
            "Finalized JSONL file 1.0.1.jsonl should exist"
        )

        # 5. unreleased.jsonl exists and is empty (fresh)
        unreleased = mock_git_repo / ".rlsbl" / "changes" / "unreleased.jsonl"
        assert unreleased.exists(), "unreleased.jsonl should exist after release"
        assert unreleased.read_text().strip() == "", (
            "unreleased.jsonl should be empty after release"
        )

        # 6. Working tree is clean
        status = _git_output(mock_git_repo, "status", "--porcelain")
        # The advisory lock file may be present; filter it out
        dirty = [
            line for line in status.splitlines()
            if line.strip() and "lock" not in line
        ]
        assert dirty == [], f"Working tree should be clean, got: {dirty}"


class TestReleaseVpathRelativePaths:
    """Test 3: verify that files_to_commit uses relative paths (not absolute)."""

    def test_release_vpath_produces_relative_paths(self, mock_git_repo):
        _setup_releasable_npm_project(mock_git_repo)

        fake_run = _fake_run_factory()

        # Track all commit_files calls to inspect the paths
        committed_file_lists = []
        original_commit_files = None

        # We need to import the real commit_files to capture and delegate
        from rlsbl.utils import commit_files as real_commit_files
        original_commit_files = real_commit_files

        def capturing_commit_files(message, files, allow_failure=False, autogenerated=True, cwd=None):
            committed_file_lists.append(list(files))
            return original_commit_files(message, files, allow_failure=allow_failure, autogenerated=autogenerated, cwd=cwd)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.commit_files", side_effect=capturing_commit_files),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
        ):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # Verify we captured some commit calls
        assert len(committed_file_lists) > 0, "Expected at least one commit_files call"

        # The first commit is the version-bump commit (files_to_commit built
        # via vpath()). All its paths must be relative to the git root --
        # absolute paths would have been the vpath bug.
        version_bump_files = committed_file_lists[0]
        assert len(version_bump_files) > 0, "Version bump commit should include files"
        for fpath in version_bump_files:
            assert not os.path.isabs(fpath), (
                f"Version-bump commit contains absolute path: {fpath}\n"
                f"Full list: {version_bump_files}\n"
                "vpath() should produce paths relative to the git root."
            )


class TestReleaseGhReleaseCreateFailure:
    """Verify that gh release create failure is non-fatal for post-push steps."""

    def test_gh_release_create_failure_continues_and_exits_1(self, mock_git_repo, capsys):
        _setup_releasable_npm_project(mock_git_repo)

        def failing_run_gh(args, **kwargs):
            if args and args[0] == "release" and args[1] in ("create", "view"):
                raise subprocess.CalledProcessError(1, f"gh release {args[1]}")
            return ""

        def intercepting_run(cmd, args=None, timeout=120, env=None, cwd=None):
            if cmd == "git" and args and args[0] == "push":
                return ""
            if cmd == "git" and args and args[0] == "fetch":
                return ""
            if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
                return "0"
            return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)

        with pytest.raises(SystemExit) as exc_info:
            with (
                patch("rlsbl.commands.release.check_gh_installed", return_value=True),
                patch("rlsbl.commands.release.check_gh_auth", return_value=True),
                patch("rlsbl.commands.release.push_if_needed"),
                patch("rlsbl.commands.release.run_gh", side_effect=failing_run_gh),
                patch("rlsbl.commands.release.run", side_effect=intercepting_run),
                patch("rlsbl.commands.release.upload_release_assets") as mock_upload,
                patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            ):
                run_cmd(
                    _rc(),
                    {"yes": True, "quiet": False},
                    ctx=_make_ctx(mock_git_repo),
                )

        # Should exit with code 1
        assert exc_info.value.code == 1

        # Error message should appear in stderr
        captured = capsys.readouterr()
        assert "GitHub Release creation failed" in captured.err
        assert "gh release create" in captured.err
        assert "rlsbl release undo" in captured.err

        # Asset upload should NOT have been called (depends on release existing)
        mock_upload.assert_not_called()

        # Verify the release still completed its other steps (tag was created, etc.)
        tag_output = _git_output(mock_git_repo, "tag", "-l", "v1.0.1")
        assert "v1.0.1" in tag_output, "Tag should still exist even though GH Release failed"

    def test_recovery_hint_uses_committed_md_file(self, mock_git_repo, capsys):
        """Recovery hint references the committed .rlsbl/changes/{version}.md, not
        a temp notes file, and does not suggest rlsbl release edit (which requires
        the release to already exist)."""
        _setup_releasable_npm_project(mock_git_repo)

        gh_calls = []

        def failing_run_gh(args, **kwargs):
            if args and args[0] == "release":
                gh_calls.append(args)
                if args[1] in ("create", "view"):
                    raise subprocess.CalledProcessError(1, f"gh release {args[1]}")
            return ""

        def intercepting_run(cmd, args=None, timeout=120, env=None, cwd=None):
            if cmd == "git" and args and args[0] == "push":
                return ""
            if cmd == "git" and args and args[0] == "fetch":
                return ""
            if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
                return "0"
            return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)

        with pytest.raises(SystemExit):
            with (
                patch("rlsbl.commands.release.check_gh_installed", return_value=True),
                patch("rlsbl.commands.release.check_gh_auth", return_value=True),
                patch("rlsbl.commands.release.push_if_needed"),
                patch("rlsbl.commands.release.run_gh", side_effect=failing_run_gh),
                patch("rlsbl.commands.release.run", side_effect=intercepting_run),
                patch("rlsbl.commands.release.upload_release_assets"),
                patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            ):
                run_cmd(
                    _rc(),
                    {"yes": True, "quiet": False},
                    ctx=_make_ctx(mock_git_repo),
                )

        captured = capsys.readouterr()

        # Recovery hint must contain the full gh release create command with
        # the committed per-version .md file path (not the temp notes file)
        assert ".rlsbl/changes/1.0.1.md" in captured.err, (
            f"Recovery hint should reference .rlsbl/changes/1.0.1.md, got:\n{captured.err}"
        )
        assert "gh release create v1.0.1 --title v1.0.1 --notes-file .rlsbl/changes/1.0.1.md" in captured.err, (
            f"Recovery hint should contain full gh release create command, got:\n{captured.err}"
        )

        # Must NOT suggest rlsbl release edit (it checks release exists first)
        assert "rlsbl release edit" not in captured.err, (
            f"Recovery hint must not suggest 'rlsbl release edit', got:\n{captured.err}"
        )

        # Must NOT suggest rlsbl release retry (it dispatches CI, not create releases)
        assert "rlsbl release retry" not in captured.err, (
            f"Recovery hint must not suggest 'rlsbl release retry', got:\n{captured.err}"
        )

        # Verify retry behavior: should have attempted create twice, view twice
        create_calls = [c for c in gh_calls if c[1] == "create"]
        view_calls = [c for c in gh_calls if c[1] == "view"]
        assert len(create_calls) == 2, (
            f"Expected 2 gh release create attempts, got {len(create_calls)}: {create_calls}"
        )
        # 3 view calls: 1 from the GITHUB_RELEASE guard (pre-check) +
        # 2 from the retry loop's race-condition detection
        assert len(view_calls) == 3, (
            f"Expected 3 gh release view checks, got {len(view_calls)}: {view_calls}"
        )


class TestBuildFailureAbortsRelease:
    """Build failures must abort the release pre-push and trigger rollback."""

    def test_primary_build_failure_aborts_release(self, mock_git_repo):
        """A RuntimeError from target.build() must prevent commit/tag/push."""
        _setup_releasable_npm_project(mock_git_repo)
        fake_run = _fake_run_factory()

        head_before = _git_output(mock_git_repo, "rev-parse", "HEAD")

        # Mock target.build to raise RuntimeError (simulating a build failure)
        from rlsbl.targets.npm import NpmTarget
        original_build = NpmTarget.build

        def failing_build(self, dir_path, version, *, config=None):
            raise RuntimeError("build failed: compile error")

        with (
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch.object(NpmTarget, "build", failing_build),
        ):
            with pytest.raises((RuntimeError, SystemExit)):
                run_cmd(
                    _rc(),
                    {"yes": True, "quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        # HEAD must not have moved (rollback should have run)
        head_after = _git_output(mock_git_repo, "rev-parse", "HEAD")
        assert head_after == head_before, (
            f"HEAD moved from {head_before[:10]} to {head_after[:10]}; "
            f"build failure should have triggered rollback"
        )

        # No tag should have been created
        tags = _git_output(mock_git_repo, "tag", "-l")
        assert "v1.0.1" not in tags, "v1.0.1 tag should not exist after build failure"
