"""Tests for post-release step tracking: markers, fatality classes, and
incremental resume of the post-release phase.

Covers:
- A fully successful release records a marker for EVERY canonical step
  before the state file is cleared (provable completeness).
- Pipeline publish failure is FATAL: state preserved, resumable (it used
  to be downgraded to a warning -- silent degradation for local pipelines).
- Resume re-attempts publish after a publish failure.
- Resume skips already-completed post-release steps (e.g. does not
  re-upload assets when ASSETS_UPLOADED is marked).
- Deploy and post-release hook failures are non-fatal but recorded as
  failure markers and loudly named in the completion summary.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from githarness import record_release

from rlsbl.commands.release import resume_cmd, run_cmd
from rlsbl.commands.release.release_state import (
    MUTATING_STEPS,
    RELEASE_STEPS,
    get_state_path,
    load_release_state,
    save_release_state,
)
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run

from conftest import with_root_member, make_workspace


# ---------------------------------------------------------------------------
# Helpers (conventions follow tests/test_release_resume.py)
# ---------------------------------------------------------------------------


def _rc(bump="patch", include=None, exclude=None, description="test release"):
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
        description=description,
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_head(repo):
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _setup_npm_project(repo):
    """Create an npm project at v1.0.0 with one unreleased commit."""
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"]}) + "\n"
    )
    _git(repo, "add",
         "package.json", "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    record_release(repo, "v1.0.0")

    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(repo, "commit", "-q", "-m", "changelog: add feature entry",
         "--trailer", "Autogenerated: true")


def _make_ctx(repo, config=None):
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config=config or {"publish_mode": "ci", "pipelines": {}},
    )


def _fake_run_factory():
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


_RUN_CMD_PATCHES = (
    ("rlsbl.commands.release.check_gh_installed", {"return_value": True}),
    ("rlsbl.commands.release.check_gh_auth", {"return_value": True}),
    ("rlsbl.commands.release.remote_branch_exists", {"return_value": True}),
)


def _make_in_progress_state(repo, *, completed_steps=None, failed_steps=None,
                            version="1.0.1", branch="main"):
    """Write an in-progress.json state file and return its path."""
    state_path = get_state_path(str(repo))
    pre_sha = _git_head(repo)
    state = {
        "new_version": version,
        "tag": f"v{version}",
        "branch": branch,
        "pre_release_sha": pre_sha,
        "bump_type": "patch",
        "registry": "npm",
        "completed_steps": completed_steps or [],
        "failed_steps": failed_steps or {},
        "companion_tags": [],
        "monorepo_name": None,
        "releasable_name": None,
        "commit_msg": f"v{version}",
        "description": "test release",
        "context": "",
        "include": ["npm"],
        "exclude": [],
        "preid": "",
        "blog": False,
    }
    save_release_state(state_path, state)
    return state_path


def _bump_and_tag(repo, version="1.0.1"):
    """Simulate the mutating phase already done: bump, commit, tag."""
    pkg = json.loads((repo / "package.json").read_text())
    pkg["version"] = version
    (repo / "package.json").write_text(json.dumps(pkg, indent=2) + "\n")
    _git(repo, "add", "package.json")
    _git(repo, "commit", "-q", "-m", f"v{version}")
    record_release(repo, f"v{version}")


def _setup_subtree_monorepo(repo, project_path="packages/mylib", name="mylib",
                            version="1.0.1", mirror_remote=None):
    """A monorepo whose only releasable declares a ``subtree_remote``, staged at
    the point a resume re-enters the post-GitHub-Release phase.

    Returns the project directory. The release is already tagged and its
    state file records every mutating step, so the resume goes straight to
    the mirror publishing block.

    *mirror_remote* is the mirror's git URL. Pass a local bare repository (see
    ``_bare_mirror``) for a test that lets the mirror steps really run; the
    default names a remote nothing can reach, for tests about what happens when
    they fail.
    """
    from rlsbl.workspace import save_workspace

    proj_dir = repo / project_path
    proj_dir.mkdir(parents=True)
    (proj_dir / "package.json").write_text(
        json.dumps({"name": name, "version": version}, indent=2) + "\n"
    )
    (proj_dir / ".rlsbl").mkdir()
    (proj_dir / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "none", "targets": ["npm"]}) + "\n"
    )
    make_workspace(
        str(repo),
        [{"path": project_path, "name": name, "releasable": name}],
        releasables=[{
            "name": name,
            "subtree_remote": mirror_remote or "/nonexistent/mirror.git",
        }],
    )
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", f"{name}@v{version}")
    tag = f"{name}@v{version}"
    _git(repo, "tag", tag)

    from rlsbl.commands.release.release_state import resolve_releasable_dir
    state_path = get_state_path(
        str(proj_dir),
        releasable_dir=resolve_releasable_dir(str(proj_dir), str(repo)),
    )
    save_release_state(state_path, {
        "new_version": version,
        "tag": tag,
        "branch": "main",
        "pre_release_sha": _git_head(repo),
        "candidate_sha": _git_head(repo),
        "pin_sha": _git_head(repo),
        "bump_type": "patch",
        "registry": "npm",
        "completed_steps": list(MUTATING_STEPS),
        "failed_steps": {},
        "companion_tags": [],
        "monorepo_name": name,
        # make_workspace derives one releasable per member, named after it.
        "releasable_name": name,
        "commit_msg": tag,
        "description": "test release",
        "context": "",
        "include": ["npm"],
        "exclude": [],
        "preid": "",
        "blog": False,
    })
    return str(proj_dir)


def _bare_mirror(path):
    """A local bare repository standing in for the mirror remote.

    Every mirror push in this file goes here: the suite never reaches a real
    remote, and the reconciler's force-with-lease, scaffold layer and tag push
    are all exercised for real against it.
    """
    path.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init", "-q", "--bare"], cwd=str(path), check=True)
    return str(path)


def _mirror_refs(remote, cwd):
    """``{refname: sha}`` on the mirror, tags peeled to their commits."""
    from rlsbl.mirror_publication import parse_ls_remote

    out = subprocess.run(
        ["git", "ls-remote", remote], cwd=str(cwd),
        capture_output=True, text=True, check=True,
    ).stdout
    return parse_ls_remote(out)


def _make_subtree_ctx(repo, project_dir):
    return ProjectContext(
        project_root=Path(project_dir),
        workspace_root=Path(str(repo)),
        config={"publish_mode": "none", "pipelines": {}},
    )


class _RecordingPipeline:
    """Fake pipeline that records publish calls; optionally fails."""

    # validate_pipeline_config checks .local for required-env validation
    local = False

    def __init__(self, fail=False):
        self.fail = fail
        self.publish_calls = []

    def publish(self, path, version, *, ctx):
        self.publish_calls.append((path, version))
        if self.fail:
            raise RuntimeError("registry rejected the upload")


# ---------------------------------------------------------------------------
# Provable completeness on success
# ---------------------------------------------------------------------------


class TestSuccessMarksAllSteps:
    """A fully successful release marks every canonical step before the
    state file is cleared."""

    def test_all_steps_marked_before_clear(self, mock_git_repo):
        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        from rlsbl.commands.release.release_state import (
            clear_release_state as real_clear,
        )

        snapshots = []

        def capturing_clear(path):
            state = load_release_state(path)
            if state is not None:
                snapshots.append(state)
            real_clear(path)

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.release.execute.clear_release_state",
                  side_effect=capturing_clear),
        ):
            run_cmd(
                _rc(),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        assert not os.path.exists(state_path)
        assert len(snapshots) == 1, "state should be cleared exactly once"
        final = snapshots[0]
        assert set(final["completed_steps"]) == set(RELEASE_STEPS), (
            "every canonical step must have a success marker on a fully "
            f"successful release; got {sorted(final['completed_steps'])}"
        )
        assert not final.get("failed_steps")


# ---------------------------------------------------------------------------
# Pipeline publish fatality
# ---------------------------------------------------------------------------


class TestPublishFailureIsFatal:
    """Pipeline publish failure aborts the release with preserved state
    (previously it was downgraded to a warning and the release completed)."""

    def test_publish_failure_preserves_state_and_aborts(
        self, mock_git_repo, capsys,
    ):
        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        failing = _RecordingPipeline(fail=True)
        fake_run = _fake_run_factory()
        with pytest.raises(SystemExit) as exc_info:
            with (
                patch("rlsbl.commands.release.check_gh_installed", return_value=True),
                patch("rlsbl.commands.release.check_gh_auth", return_value=True),
                patch("rlsbl.commands.release.push_if_needed"),
                patch("rlsbl.commands.release.run_gh", return_value=""),
                patch("rlsbl.commands.release.run", side_effect=fake_run),
                patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
                patch("rlsbl.commands.release.load_pipelines",
                      return_value={"npm": failing}),
            ):
                run_cmd(
                    _rc(),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code == 1
        assert failing.publish_calls, "publish must have been attempted"

        # State preserved and resumable
        assert os.path.exists(state_path), (
            "publish failure must preserve in-progress.json for resume"
        )
        state = load_release_state(state_path)
        assert "PUSHED" in state["completed_steps"]
        assert "PIPELINES_PUBLISHED" not in state["completed_steps"]
        assert "PIPELINES_PUBLISHED" in state.get("failed_steps", {})

        captured = capsys.readouterr()
        assert "publish failed" in captured.err
        assert "resume" in captured.err

    def test_resume_reattempts_publish(self, mock_git_repo):
        """After a publish failure, resume re-attempts the publish step."""
        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS) + ["ASSETS_UPLOADED"],
            failed_steps={"PIPELINES_PUBLISHED": "registry rejected the upload"},
        )

        recording = _RecordingPipeline()
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.load_pipelines",
                  return_value={"npm": recording}),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        assert recording.publish_calls, (
            "resume must re-attempt the failed publish step"
        )
        assert not os.path.exists(state_path)


# ---------------------------------------------------------------------------
# Incremental resume of post-release steps
# ---------------------------------------------------------------------------


class TestIncrementalPostReleaseResume:

    def test_resume_skips_uploaded_assets_and_proceeds_to_publish(
        self, mock_git_repo,
    ):
        """ASSETS_UPLOADED success marker gates resume-skip: assets are not
        re-uploaded, and the flow proceeds to publish."""
        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS) + ["ASSETS_UPLOADED"],
        )

        recording = _RecordingPipeline()
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.upload_release_assets") as mock_upload,
            patch("rlsbl.commands.release.load_pipelines",
                  return_value={"npm": recording}),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        mock_upload.assert_not_called()
        assert recording.publish_calls, "resume must proceed to publish"
        assert not os.path.exists(state_path)

    def test_resume_after_kill_during_assets(self, mock_git_repo):
        """State with only the mutating steps (killed during asset upload)
        is resumable: assets are uploaded and the release completes."""
        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS),
        )

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.upload_release_assets") as mock_upload,
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        mock_upload.assert_called_once()
        assert not os.path.exists(state_path)


# ---------------------------------------------------------------------------
# Non-fatal failures: deploy, post-release hooks
# ---------------------------------------------------------------------------


class TestNonFatalFailures:
    """"Non-fatal" means the release is NOT rolled back and stays resumable.

    It never meant "exit 0". A release that ends with a failed step reports
    that failure through its exit code and keeps its state file, so
    `rlsbl release resume` can re-attempt the step. The single decision
    point is the completion epilogue: any failure marker => nonzero, state
    preserved.
    """

    def test_deploy_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """A deploy failure does not roll the release back, but it must not
        be reported as success either: nonzero exit, state preserved."""
        from rlsbl.deploy import DeployResult

        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        deploy_cfg = [{"name": "prod", "type": "ssh"}]
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.release.read_deploy_config",
                  return_value=(deploy_cfg, [])),
            patch("rlsbl.commands.release.deploy_target",
                  return_value=DeployResult("prod", False, "ssh timed out")),
        ):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    _rc(),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path), (
            "a failed step must leave the state file behind so "
            "`rlsbl release resume` stays reachable"
        )
        state = load_release_state(state_path)
        assert "DEPLOYED" in state.get("failed_steps", {})

        captured = capsys.readouterr()
        assert "DEPLOYED" in captured.err
        assert "ssh timed out" in captured.err

    def test_post_hook_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """A post-release hook failure is not fatal to the published release,
        but it is still a failed step: nonzero exit, state preserved."""
        _setup_npm_project(mock_git_repo)
        state_path = get_state_path(str(mock_git_repo))

        from rlsbl.commands.release.hooks import (
            run_release_hook as real_run_release_hook,
        )

        def failing_post_hook(hook_name, *args, **kwargs):
            if hook_name == "post-release":
                raise RuntimeError("hook exploded")
            return real_run_release_hook(hook_name, *args, **kwargs)

        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.release.hooks.run_release_hook",
                  side_effect=failing_post_hook),
        ):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    _rc(),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path)
        state = load_release_state(state_path)
        assert "POST_HOOKS_RUN" in state.get("failed_steps", {})

        captured = capsys.readouterr()
        assert "POST_HOOKS_RUN" in captured.err
        assert "hook exploded" in captured.err

    def test_mirror_convergence_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys,
    ):
        """A mirror the reconciler cannot converge is a tracked step, not a
        bare warning: nonzero exit, marker recorded, state preserved, and the
        marker names the command that heals it."""
        project_dir = _setup_subtree_monorepo(mock_git_repo)
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        state_path = get_state_path(
            project_dir,
            releasable_dir=resolve_releasable_dir(project_dir, str(mock_git_repo)),
        )

        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=_fake_run_factory()),
            patch(
                "rlsbl.commands.monorepo.mirror_cmd.converge_branch",
                side_effect=RuntimeError("the mirror is unreachable"),
            ),
        ):
            with pytest.raises(SystemExit) as exc_info:
                resume_cmd(
                    load_release_state(state_path),
                    {"quiet": True, "skip-lock": True},
                    ctx=_make_subtree_ctx(mock_git_repo, project_dir),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path)
        state = load_release_state(state_path)
        marker = state["failed_steps"]["SUBTREE_PUBLISHED"]
        assert "the mirror is unreachable" in marker
        assert "rlsbl monorepo mirror mylib" in marker

        err = capsys.readouterr().err
        assert "SUBTREE_PUBLISHED" in err

    def test_mirror_release_failure_exits_nonzero_and_preserves_state(
        self, mock_git_repo, capsys, tmp_path,
    ):
        """Same for the mirror's tag and Release: a warning is not an outcome,
        and the marker names both healers."""
        mirror = _bare_mirror(tmp_path / "mirror.git")
        project_dir = _setup_subtree_monorepo(
            mock_git_repo, mirror_remote=mirror,
        )
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        state_path = get_state_path(
            project_dir,
            releasable_dir=resolve_releasable_dir(project_dir, str(mock_git_repo)),
        )

        def failing_mirror(*args, **kwargs):
            raise RuntimeError("mirror repo not found")

        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped",
                  side_effect=failing_mirror),
            patch("rlsbl.commands.release.run", side_effect=_fake_run_factory()),
        ):
            with pytest.raises(SystemExit) as exc_info:
                resume_cmd(
                    load_release_state(state_path),
                    {"quiet": True, "skip-lock": True},
                    ctx=_make_subtree_ctx(mock_git_repo, project_dir),
                )

        assert exc_info.value.code == 1
        assert os.path.exists(state_path)
        state = load_release_state(state_path)
        marker = state["failed_steps"]["MIRROR_RELEASED"]
        assert "rlsbl monorepo mirror mylib" in marker
        assert "rlsbl release reconcile" in marker
        # The branch step still succeeded on its own.
        assert "SUBTREE_PUBLISHED" in state["completed_steps"]

        err = capsys.readouterr().err
        assert "MIRROR_RELEASED" in err

    def test_a_converged_mirror_gets_one_tag_one_release_and_no_branch_write(
        self, mock_git_repo, tmp_path,
    ):
        """The whole mirror step against a real (local) mirror remote.

        The mirror is converged FIRST, at exactly the commit the release is
        staged on, so the branch has nothing left to do -- which is what makes
        the assertion meaningful: publishing the version must add exactly one
        tag and one GitHub Release, and must not move ``main``.
        """
        from rlsbl.commands.monorepo import mirror_cmd
        from rlsbl.commands.monorepo.mirror_cmd import converge_branch

        mirror = _bare_mirror(tmp_path / "mirror.git")
        project_dir = _setup_subtree_monorepo(
            mock_git_repo, mirror_remote=mirror,
        )
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        state_path = get_state_path(
            project_dir,
            releasable_dir=resolve_releasable_dir(project_dir, str(mock_git_repo)),
        )

        converge_branch(
            mirror, str(mock_git_repo), "packages/mylib",
            os.path.join(project_dir, ".rlsbl", "config.json"),
        )
        before = _mirror_refs(mirror, mock_git_repo)
        assert "refs/heads/main" in before
        assert not [r for r in before if r.startswith("refs/tags/")]

        gh_calls = []

        def fake_gh(args, **kwargs):
            gh_calls.append(list(args))
            if args[:2] == ["release", "view"]:
                raise RuntimeError("not found")
            return ""

        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped", side_effect=fake_gh),
            patch("rlsbl.commands.release.run", side_effect=_fake_run_factory()),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True, "skip-lock": True},
                ctx=_make_subtree_ctx(mock_git_repo, project_dir),
            )

        assert not os.path.exists(state_path), "a clean release clears its state"

        after = _mirror_refs(mirror, mock_git_repo)
        assert after["refs/heads/main"] == before["refs/heads/main"], (
            "publishing a version must not move the mirror's branch"
        )
        tags = {r: sha for r, sha in after.items() if r.startswith("refs/tags/")}
        assert list(tags) == ["refs/tags/v1.0.1"]
        # The tag names the subtree split of the release's ledger anchor,
        # which this fixture stages at HEAD.
        from rlsbl.mirror_publication import split_commit_for

        anchor = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=str(mock_git_repo),
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        assert tags["refs/tags/v1.0.1"] == split_commit_for(
            str(mock_git_repo), "packages/mylib", anchor,
        )

        creates = [c for c in gh_calls if c[:2] == ["release", "create"]]
        assert len(creates) == 1
        assert creates[0][2] == "v1.0.1"
        assert "--repo" in creates[0]

    def test_a_completed_mirror_step_is_not_re_converged_on_resume(
        self, mock_git_repo, tmp_path,
    ):
        """A resume skips the mirror steps their markers say are done.

        Every other step in the flow reads its success marker before acting;
        the mirror block did not, so a resume after a LATER step failed
        re-converged a mirror that was already converged and re-published a
        version already on it.
        """
        import rlsbl.commands.monorepo.mirror_cmd as mirror_cmd
        import rlsbl.mirror_publication as mirror_publication

        mirror = _bare_mirror(tmp_path / "mirror.git")
        project_dir = _setup_subtree_monorepo(
            mock_git_repo, mirror_remote=mirror,
        )
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        state_path = get_state_path(
            project_dir,
            releasable_dir=resolve_releasable_dir(project_dir, str(mock_git_repo)),
        )
        state = load_release_state(state_path)
        state["completed_steps"] = list(state["completed_steps"]) + [
            "SUBTREE_PUBLISHED", "MIRROR_RELEASED",
        ]
        save_release_state(state_path, state)

        converged = []
        published = []
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=_fake_run_factory()),
            patch.object(
                mirror_cmd, "converge_branch",
                side_effect=lambda *a, **k: converged.append(a),
            ),
            patch.object(
                mirror_publication, "publish_version",
                side_effect=lambda **k: published.append(k),
            ),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True, "skip-lock": True},
                ctx=_make_subtree_ctx(mock_git_repo, project_dir),
            )

        assert converged == [], "a completed mirror branch step was re-run"
        assert published == [], "a completed mirror release step was re-run"

    def test_the_mirror_release_notes_file_stays_out_of_the_release_cwd(
        self, mock_git_repo, tmp_path, monkeypatch,
    ):
        """The mirror's Release body is written where the release keeps state.

        It used to be written into whatever directory the release ran from,
        where a stray ``.rlsbl-notes-*.tmp`` is a file in somebody's working
        tree.
        """
        mirror = _bare_mirror(tmp_path / "mirror.git")
        project_dir = _setup_subtree_monorepo(
            mock_git_repo, mirror_remote=mirror,
        )
        from rlsbl.commands.release.release_state import resolve_releasable_dir
        releasable_dir = resolve_releasable_dir(project_dir, str(mock_git_repo))
        state_path = get_state_path(project_dir, releasable_dir=releasable_dir)

        notes_paths = []

        def fake_gh(args, **kwargs):
            if "--notes-file" in args:
                notes_paths.append(args[args.index("--notes-file") + 1])
            if args[:2] == ["release", "view"]:
                raise RuntimeError("not found")
            return ""

        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run_gh_unscoped", side_effect=fake_gh),
            patch("rlsbl.commands.release.run", side_effect=_fake_run_factory()),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True, "skip-lock": True},
                ctx=_make_subtree_ctx(mock_git_repo, project_dir),
            )

        assert notes_paths, "the mirror Release must be created from a notes file"
        for path in notes_paths:
            assert os.path.dirname(path), (
                f"the mirror notes file has no directory of its own: {path}"
            )
            assert os.path.realpath(os.path.dirname(path)) == os.path.realpath(
                os.path.join(str(mock_git_repo), releasable_dir, "releases")
            ), path

    def test_resume_after_nonfatal_failure_completes_and_clears_state(
        self, mock_git_repo,
    ):
        """The preserved state is genuinely resumable: a resume that
        re-attempts the failed step successfully clears the failure marker,
        completes the release, and removes the state file."""
        from rlsbl.deploy import DeployResult

        _setup_npm_project(mock_git_repo)
        _bump_and_tag(mock_git_repo)

        state_path = _make_in_progress_state(
            mock_git_repo,
            completed_steps=list(MUTATING_STEPS)
            + ["ASSETS_UPLOADED", "PIPELINES_PUBLISHED"],
            failed_steps={"DEPLOYED": "deploy to prod failed: ssh timed out"},
        )

        deploy_cfg = [{"name": "prod", "type": "ssh"}]
        fake_run = _fake_run_factory()
        with (
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.read_deploy_config",
                  return_value=(deploy_cfg, [])),
            patch("rlsbl.commands.release.deploy_target",
                  return_value=DeployResult("prod", True, "deployed")),
        ):
            resume_cmd(
                load_release_state(state_path),
                {"quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        assert not os.path.exists(state_path), (
            "a resume that clears every failure marker must complete the "
            "release and remove the state file"
        )
