"""Tests for root-level selfdoc detection in monorepo batch releases.

When selfdoc.json exists at the workspace root (but not at member level),
the batch release flow must run selfdoc gen + check once at the root
before per-member releases, and commit any generated files.
"""

import json
import os
from unittest.mock import patch, MagicMock, call

import pytest

from rlsbl.commands.monorepo.batch_release import _run_root_selfdoc


class TestRunRootSelfdoc:
    """Unit tests for _run_root_selfdoc."""

    def test_skips_when_no_selfdoc_json(self, tmp_path):
        """No selfdoc.json at workspace root -> no-op."""
        flags = {}
        calls = []

        def log(msg):
            calls.append(msg)

        _run_root_selfdoc(flags, str(tmp_path), log)
        # No log messages when selfdoc.json is absent
        assert calls == []

    def test_runs_gen_and_check_when_selfdoc_exists(self, tmp_path):
        """selfdoc.json at workspace root triggers gen + check."""
        (tmp_path / "selfdoc.json").write_text('{"version": "0.1.0"}')
        flags = {}
        log_msgs = []

        with patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_gen"
        ) as mock_gen, patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_check"
        ) as mock_check, patch(
            "rlsbl.commands.monorepo.batch_release.run",
            return_value="",
        ), patch(
            "rlsbl.commands.monorepo.batch_release.parse_porcelain_paths",
            return_value=set(),
        ):
            _run_root_selfdoc(flags, str(tmp_path), lambda m: log_msgs.append(m))

        mock_gen.assert_called_once_with(flags, project_dir=str(tmp_path))
        mock_check.assert_called_once_with(flags, project_dir=str(tmp_path))
        assert any("workspace root" in m for m in log_msgs)

    def test_commits_generated_files(self, tmp_path):
        """Files dirtied by selfdoc gen are committed."""
        (tmp_path / "selfdoc.json").write_text('{"version": "0.1.0"}')
        flags = {}

        call_count = [0]

        def fake_run(tool, args, **kwargs):
            if tool == "git" and args == ["status", "--porcelain"]:
                call_count[0] += 1
                if call_count[0] == 1:
                    return ""  # pre-selfdoc: clean
                else:
                    return " M README.md\n?? docs/api.md\n"  # post-selfdoc
            return ""

        commit_calls = []

        def fake_commit(msg, files, autogenerated=True, **kwargs):
            commit_calls.append({"msg": msg, "files": files, "auto": autogenerated})

        with patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_gen"
        ), patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_check"
        ), patch(
            "rlsbl.commands.monorepo.batch_release.run",
            side_effect=fake_run,
        ), patch(
            "rlsbl.commands.monorepo.batch_release.commit_files",
            side_effect=fake_commit,
        ):
            from rlsbl.commands.release.validate import parse_porcelain_paths as real_parse
            with patch(
                "rlsbl.commands.monorepo.batch_release.parse_porcelain_paths",
                side_effect=real_parse,
            ):
                _run_root_selfdoc(flags, str(tmp_path), lambda m: None)

        assert len(commit_calls) == 1
        assert commit_calls[0]["auto"] is True
        assert sorted(commit_calls[0]["files"]) == ["README.md", "docs/api.md"]

    def test_dry_run_skips_commit(self, tmp_path):
        """In dry-run mode, selfdoc gen/check run but no commit."""
        (tmp_path / "selfdoc.json").write_text('{"version": "0.1.0"}')
        flags = {"dry-run": True}

        commit_calls = []

        with patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_gen"
        ) as mock_gen, patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_check"
        ) as mock_check, patch(
            "rlsbl.commands.monorepo.batch_release.commit_files",
            side_effect=lambda *a, **k: commit_calls.append(1),
        ):
            _run_root_selfdoc(flags, str(tmp_path), lambda m: None)

        mock_gen.assert_called_once()
        mock_check.assert_called_once()
        assert commit_calls == []

    def test_no_commit_when_no_new_dirty_files(self, tmp_path):
        """If selfdoc gen produces no new dirty files, no commit is made."""
        (tmp_path / "selfdoc.json").write_text('{"version": "0.1.0"}')
        flags = {}

        with patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_gen"
        ), patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_check"
        ), patch(
            "rlsbl.commands.monorepo.batch_release.run",
            return_value="",
        ), patch(
            "rlsbl.commands.monorepo.batch_release.parse_porcelain_paths",
            return_value=set(),
        ) as mock_parse, patch(
            "rlsbl.commands.monorepo.batch_release.commit_files"
        ) as mock_commit:
            _run_root_selfdoc(flags, str(tmp_path), lambda m: None)

        mock_commit.assert_not_called()

    def test_hook_error_propagates(self, tmp_path):
        """HookError from selfdoc gen/check propagates to caller."""
        from rlsbl.commands.release.validate import HookError

        (tmp_path / "selfdoc.json").write_text('{"version": "0.1.0"}')
        flags = {}

        with patch(
            "rlsbl.commands.monorepo.batch_release._run_selfdoc_gen",
            side_effect=HookError("selfdoc gen failed"),
        ):
            with pytest.raises(HookError, match="selfdoc gen failed"):
                _run_root_selfdoc(flags, str(tmp_path), lambda m: None)


class TestBatchReleaseRootSelfdocIntegration:
    """Integration-level tests verifying _cmd_batch_release invokes root selfdoc."""

    def test_batch_release_calls_root_selfdoc(self, tmp_path, monkeypatch):
        """_cmd_batch_release calls _run_root_selfdoc before per-member releases."""
        monkeypatch.chdir(tmp_path)

        # Create minimal workspace
        ws_dir = tmp_path / ".rlsbl-monorepo"
        ws_dir.mkdir()
        (ws_dir / "workspace.toml").write_text(
            '[[projects]]\npath = "pkg"\nname = "pkg"\n'
        )

        # Create batch release file (needed so the path check passes)
        releases_dir = ws_dir / "releases"
        releases_dir.mkdir()
        (releases_dir / "unreleased.toml").write_text(
            '[packages.pkg]\nbump = "patch"\ndescription = "test"\n'
            'include = ["pypi"]\nexclude = []\n'
        )

        # Create the member project
        pkg_dir = tmp_path / "pkg"
        pkg_dir.mkdir()
        (pkg_dir / "pyproject.toml").write_text(
            '[project]\nname = "pkg"\nversion = "0.1.0"\n'
        )

        # Create selfdoc.json at root (but NOT in the member)
        (tmp_path / "selfdoc.json").write_text('{"version": "0.1.0"}')

        flags = {"dry-run": True, "allow-dirty": True, "quiet": False}

        with patch(
            "rlsbl.commands.monorepo.batch_release.validate_gh_cli"
        ), patch(
            "rlsbl.commands.monorepo.batch_release.validate_gh_push_access"
        ), patch(
            "rlsbl.commands.monorepo.batch_release.validate_clean_tree",
            return_value=set(),
        ), patch(
            "rlsbl.commands.monorepo.batch_release.validate_branch_and_remote",
            return_value="main",
        ), patch(
            "rlsbl.commands.monorepo.batch_release._run_root_selfdoc"
        ) as mock_root_selfdoc, patch(
            "rlsbl.commands.monorepo.batch_release._batch_release_packages"
        ):
            from pathlib import Path
            from rlsbl.commands.monorepo.batch_release import _cmd_batch_release
            _cmd_batch_release(flags, Path(tmp_path))

        mock_root_selfdoc.assert_called_once()
        call_args = mock_root_selfdoc.call_args
        assert call_args[0][0] == flags  # flags
        assert call_args[0][1] == str(tmp_path)  # workspace_root
