"""Tests for release.mode config rejection.

PR mode has been removed. These tests verify:
- validate_config_schema rejects release.mode entirely
- The release flow rejects configs with release.mode
- Imperative mode (default) works without the release.mode key
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import call, patch, MagicMock

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.config import validate_config_schema
from rlsbl.context import ProjectContext
from rlsbl.errors import ConfigError
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rc(bump="patch", include=None, exclude=None, description="test release"):
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
        description=description,
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_output(repo, *args):
    result = subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _git_head(repo):
    return _git_output(repo, "rev-parse", "HEAD")


def _setup_pr_mode_project(repo):
    """Create an npm project at v1.0.0 with PR release mode configured.

    Returns the SHA of the unreleased feature commit.
    """
    # package.json at v1.0.0
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )

    # CHANGELOG.md
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )

    # .rlsbl scaffolding with PR mode
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({
            "private": False,
            "targets": ["npm"],
            "release": {"mode": "pr"},
            "pipelines": {},
        }) + "\n"
    )

    _git(repo, "add",
         "package.json",
         "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl",
         ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    # Make an unreleased feature commit
    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    # Cover it with a JSONL entry
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(
        repo, "commit", "-q", "-m", "changelog: add feature entry",
        "--trailer", "Autogenerated: true",
    )

    # Create the release file
    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "unreleased.toml").write_text(
        'bump = "patch"\ninclude = ["npm"]\nexclude = []\ndescription = "test release"\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")

    return feature_sha


def _make_ctx(repo, *, config_override=None):
    """Build a ProjectContext for release tests.

    By default creates an imperative-mode config (no release.mode key,
    since PR mode is removed).  Use config_override to test specific
    config shapes.
    """
    config = config_override or {
        "private": False,
        "pipelines": {},
    }
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config=config,
    )


def _fake_run_factory():
    """Create a fake_run that intercepts gh/push/fetch, passes everything else through."""
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


# ---------------------------------------------------------------------------
# PR mode config rejection tests
# ---------------------------------------------------------------------------

class TestPrModeConfigRejected:
    """PR mode configs are rejected by validate_config_schema."""

    def test_pr_mode_config_rejected_by_schema_validation(self):
        config = {"release": {"mode": "pr"}}
        with pytest.raises(ConfigError, match="release.mode is no longer supported"):
            validate_config_schema(config)

    def test_imperative_mode_config_also_rejected(self):
        """Even imperative mode key is banned -- the key itself is dead config."""
        config = {"release": {"mode": "imperative"}}
        with pytest.raises(ConfigError, match="release.mode is no longer supported"):
            validate_config_schema(config)

    def test_release_flow_rejects_pr_mode_config(self, mock_git_repo):
        """The release flow exits with an error when release.mode is set."""
        _setup_pr_mode_project(mock_git_repo)

        with pytest.raises(SystemExit):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": False},
                ctx=_make_ctx(mock_git_repo, config_override={
                    "private": False,
                    "pipelines": {},
                    "release": {"mode": "pr"},
                }),
            )


class TestImperativeModeUnchanged:
    """Test 8: Imperative mode (default) behavior is unchanged."""

    def test_imperative_mode_creates_tag(self, mock_git_repo):
        """Imperative mode should create tags like before."""
        # Set up a normal project (no PR mode)
        (mock_git_repo / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
        )
        (mock_git_repo / "CHANGELOG.md").write_text(
            "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
            "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
        )
        changes_dir = mock_git_repo / ".rlsbl" / "changes"
        changes_dir.mkdir(parents=True)
        (changes_dir / "unreleased.jsonl").write_text("")
        (mock_git_repo / ".rlsbl" / "config.json").write_text(
            json.dumps({"private": False, "targets": ["npm"], "pipelines": {}}) + "\n"
        )
        _git(mock_git_repo, "add",
             "package.json", "CHANGELOG.md",
             ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
        _git(mock_git_repo, "commit", "-q", "-m", "initial")
        _git(mock_git_repo, "tag", "v1.0.0")

        (mock_git_repo / "feature.txt").write_text("new feature\n")
        _git(mock_git_repo, "add", "feature.txt")
        _git(mock_git_repo, "commit", "-q", "-m", "add feature")
        feature_sha = _git_head(mock_git_repo)

        entry = {
            "commits": [feature_sha],
            "user_facing": True,
            "description": "**New feature.** A shiny new thing.",
            "type": "feature",
        }
        (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
        _git(mock_git_repo, "add", ".rlsbl/changes/unreleased.jsonl")
        _git(mock_git_repo, "commit", "-q", "-m", "changelog: add entry",
             "--trailer", "Autogenerated: true")

        releases_dir = mock_git_repo / ".rlsbl" / "releases"
        releases_dir.mkdir(parents=True)
        (releases_dir / "unreleased.toml").write_text(
            'bump = "patch"\ninclude = ["npm"]\nexclude = []\ndescription = "test"\n'
        )
        _git(mock_git_repo, "add", ".rlsbl/releases/unreleased.toml")
        _git(mock_git_repo, "commit", "-q", "-m", "add release file",
             "--trailer", "Autogenerated: true")

        fake_run = _fake_run_factory()

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
        ):
            run_cmd(
                _rc(description="test"),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo),
            )

        # Imperative mode should create a tag
        tags = _git_output(mock_git_repo, "tag", "-l", "v1.0.1")
        assert "v1.0.1" in tags, f"Imperative mode should create v1.0.1 tag, got: {tags}"

        # Should NOT have created a release branch
        branches = _git_output(mock_git_repo, "branch", "--list", "release/v*")
        assert branches == "", f"Imperative mode should not create release branches, got: {branches}"


class TestAnyReleaseModeKeyErrors:
    """Any release.mode key (valid or invalid) errors during release."""

    def test_any_release_mode_key_rejects(self, mock_git_repo):
        _setup_pr_mode_project(mock_git_repo)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            pytest.raises(SystemExit),
        ):
            run_cmd(
                _rc(),
                {"yes": True, "quiet": True},
                ctx=_make_ctx(mock_git_repo, config_override={
                    "private": False,
                    "pipelines": {},
                    "release": {"mode": "invalid"},
                }),
            )
