"""The release runs in a detached checkout of the committed commit.

Covers :mod:`rlsbl.release_checkout` and the release commands' way into it:

- another session's uncommitted edits to files the release does not write
  neither block a release nor leak into it, and remain byte for byte through
  a successful release and through a failed one;
- uncommitted source never reaches a file the release generates and commits;
- the branch advances only by compare-and-swap from where the release left
  it, and a branch that moved mid-release is refused with nothing written;
- an uncommitted change to a path the release writes refuses it, naming the
  path, and ``--dry-run`` reports the same instead of refusing;
- every refusal that names a fix is followed by performing that fix, and the
  refusal clears.

The end-to-end tests drive ``rlsbl release run`` through the CLI dispatch
against a real repository and a bare local remote; only the GitHub side (gh)
is stubbed.
"""

import json
import os
import subprocess
from contextlib import contextmanager
from pathlib import Path
from unittest.mock import patch

import pytest

from githarness import add_remote, git, init_repo, record_release
from rlsbl import app, release_checkout


# ---------------------------------------------------------------------------
# Fixture: an npm project one covered commit ahead of v1.0.0, with a remote
# ---------------------------------------------------------------------------


def _write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _commit_all(repo, message, *, autogenerated=False):
    git(repo, "add", "-A")
    args = ["commit", "-q", "-m", message]
    if autogenerated:
        args += ["--trailer", "Autogenerated: true"]
    git(repo, *args)
    return git(repo, "rev-parse", "HEAD")


def _project(tmp_path, *, pre_checks=None):
    """A releasable npm project and its bare remote; returns the repo path."""
    repo = tmp_path / "repo"
    init_repo(repo)
    _write(repo / "package.json",
           json.dumps({"name": "pkg", "version": "1.0.0"}, indent=2) + "\n")
    _write(repo / "CHANGELOG.md",
           "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
           "# Changelog\n\n## 1.0.0\n\n- Initial release.\n")
    _write(repo / "README.md", "# pkg\n")
    _write(repo / "notes.txt", "notes\n")
    _write(repo / "src.txt", "committed source\n")
    _write(repo / ".gitignore", "node_modules/\n")
    _write(repo / ".rlsbl" / "config.json",
           json.dumps({"publish_mode": "ci", "targets": ["npm"], "tag": False,
                       "pipelines": {}}) + "\n")
    _write(repo / ".rlsbl" / "changes" / "unreleased.jsonl", "")
    if pre_checks is not None:
        _write(repo / ".rlsbl" / "hooks" / "pre-checks.sh", pre_checks)
    _commit_all(repo, "initial")
    record_release(repo, "v1.0.0")

    _write(repo / "feature.txt", "a feature\n")
    feature = _commit_all(repo, "add feature")
    entry = {
        "format_version": 1, "commits": [feature], "user_facing": True,
        "description": "**A feature.** It does a thing.", "type": "feature",
    }
    _write(repo / ".rlsbl" / "changes" / "unreleased.jsonl", json.dumps(entry) + "\n")
    _commit_all(repo, "changelog: add feature entry", autogenerated=True)
    _write(repo / ".rlsbl" / "releases" / "unreleased.toml",
           'format_version = 1\nbump = "patch"\ninclude = ["npm"]\n'
           'exclude = []\ndescription = "a patch release"\n')
    _commit_all(repo, "add release file", autogenerated=True)
    add_remote(repo, tmp_path / "remote")
    return repo


def _fake_gh(args, **_kwargs):
    if args[:2] == ["release", "view"]:
        raise subprocess.CalledProcessError(1, ["gh", *args])
    return ""


@contextmanager
def _github_stubbed():
    """The GitHub half of a release, stubbed; git and the remote are real."""
    with (
        patch("rlsbl.commands.release.validate_gh_cli"),
        patch("rlsbl.commands.release.validate_gh_push_access"),
        patch("rlsbl.commands.release.run_gh", side_effect=_fake_gh),
    ):
        yield


def _release(repo, monkeypatch, *extra):
    monkeypatch.chdir(repo)
    with _github_stubbed():
        return app.test(
            ["release", "run", "--no-watch", "--approve-consequential", *extra]
        )


def _bytes(path):
    return Path(path).read_bytes()


def _status(repo):
    # Not through the harness's git(): it strips the output, and with it the
    # leading space of the first record's status column.
    return subprocess.run(
        ["git", "status", "--porcelain", "--untracked-files=all"],
        cwd=str(repo), capture_output=True, text=True, check=True,
    ).stdout.rstrip("\n")


def _reject_pushes(remote):
    hook = remote / "hooks" / "pre-receive"
    hook.write_text("#!/bin/sh\necho 'push refused by the test remote' >&2\nexit 1\n")
    hook.chmod(0o755)
    return hook


# ---------------------------------------------------------------------------
# The checkout itself
# ---------------------------------------------------------------------------


class TestPrepareCheckout:
    def test_created_under_the_git_common_dir_and_detached(self, tmp_path):
        repo = _project(tmp_path)
        head = git(repo, "rev-parse", "HEAD")
        path = release_checkout.prepare_checkout(str(repo), head)
        assert path == os.path.realpath(repo / ".git" / "rlsbl" / "release-checkout")
        assert git(path, "rev-parse", "HEAD") == head
        assert git(path, "symbolic-ref", "-q", "HEAD", check=False) == ""
        assert _status(path) == ""

    def test_reused_reset_and_cleaned_but_ignored_files_kept(self, tmp_path):
        repo = _project(tmp_path)
        head = git(repo, "rev-parse", "HEAD")
        path = Path(release_checkout.prepare_checkout(str(repo), head))
        (path / "README.md").write_text("scribbled by a previous release\n")
        (path / "stray.txt").write_text("untracked leftover\n")
        (path / "node_modules").mkdir()
        (path / "node_modules" / "cache").write_text("warm\n")

        again = release_checkout.prepare_checkout(str(repo), head)

        assert again == str(path)
        assert (path / "README.md").read_text() == "# pkg\n"
        assert not (path / "stray.txt").exists()
        assert (path / "node_modules" / "cache").read_text() == "warm\n"

    def test_a_foreign_directory_is_refused_and_deleting_it_clears(self, tmp_path):
        repo = _project(tmp_path)
        head = git(repo, "rev-parse", "HEAD")
        squatter = repo / ".git" / "rlsbl" / "release-checkout"
        squatter.mkdir(parents=True)
        (squatter / "something").write_text("not ours\n")
        with pytest.raises(release_checkout.ReleaseCheckoutError) as exc:
            release_checkout.prepare_checkout(str(repo), head)
        assert str(squatter) in str(exc.value)
        assert "Delete" in str(exc.value)
        # The fix the refusal names.
        import shutil
        shutil.rmtree(squatter)
        path = release_checkout.prepare_checkout(str(repo), head)
        assert git(path, "rev-parse", "HEAD") == head


def _enter(repo):
    """Enter the release checkout of *repo*'s main as a release would."""
    head = git(repo, "rev-parse", "refs/heads/main")
    return release_checkout.entered(str(repo), branch="main", sha=head, cwd=str(repo))


class TestAdvance:
    def test_only_the_release_s_paths_are_written_back(self, tmp_path, monkeypatch):
        repo = _project(tmp_path)
        (repo / "README.md").write_text("another session's edit\n")
        (repo / "scratch.txt").write_text("another session's new file\n")
        before_readme = _bytes(repo / "README.md")
        with _enter(repo) as co:
            _write(Path(co.path) / "package.json", '{"version": "1.0.1"}\n')
            _write(Path(co.path) / "generated.txt", "generated\n")
            new = _commit_all(co.path, "release")
            release_checkout.advance_live_branch("HEAD", rerun="re-run it")
        assert git(repo, "rev-parse", "refs/heads/main") == new
        assert (repo / "package.json").read_text() == '{"version": "1.0.1"}\n'
        assert (repo / "generated.txt").read_text() == "generated\n"
        assert _bytes(repo / "README.md") == before_readme
        assert (repo / "scratch.txt").read_text() == "another session's new file\n"
        assert sorted(_status(repo).splitlines()) == [" M README.md", "?? scratch.txt"]

    def test_an_uncommitted_edit_to_a_written_path_refuses_naming_it(self, tmp_path):
        repo = _project(tmp_path)
        pin = git(repo, "rev-parse", "HEAD")
        (repo / "package.json").write_text("another session's edit\n")
        with _enter(repo) as co:
            _write(Path(co.path) / "package.json", '{"version": "1.0.1"}\n')
            _commit_all(co.path, "release")
            with pytest.raises(release_checkout.LiveTreeConflictError) as exc:
                release_checkout.advance_live_branch("HEAD", rerun="re-run it")
        assert "package.json" in str(exc.value)
        assert git(repo, "rev-parse", "refs/heads/main") == pin
        assert (repo / "package.json").read_text() == "another session's edit\n"

    def test_a_branch_that_moved_is_refused_and_nothing_is_written(self, tmp_path):
        repo = _project(tmp_path)
        with _enter(repo) as co:
            _write(Path(co.path) / "package.json", '{"version": "1.0.1"}\n')
            _commit_all(co.path, "release")
            # Another session commits on the live branch meanwhile.
            _write(repo / "notes.txt", "committed by someone else\n")
            moved = _commit_all(repo, "someone else's commit")
            with pytest.raises(release_checkout.BranchMovedError) as exc:
                release_checkout.advance_live_branch("HEAD", rerun="re-run it")
        assert moved[:12] in str(exc.value)
        assert git(repo, "rev-parse", "refs/heads/main") == moved
        assert json.loads((repo / "package.json").read_text())["version"] == "1.0.0"
        assert _status(repo) == ""

    def test_unwind_takes_the_advance_back(self, tmp_path):
        repo = _project(tmp_path)
        pin = git(repo, "rev-parse", "HEAD")
        (repo / "README.md").write_text("another session's edit\n")
        with _enter(repo) as co:
            _write(Path(co.path) / "package.json", '{"version": "1.0.1"}\n')
            _commit_all(co.path, "release")
            release_checkout.advance_live_branch("HEAD", rerun="re-run it")
            assert release_checkout.unwind_last_advance() == (True, None)
        assert git(repo, "rev-parse", "refs/heads/main") == pin
        assert json.loads((repo / "package.json").read_text())["version"] == "1.0.0"
        assert _status(repo) == " M README.md"

    def test_unwind_refuses_when_something_was_committed_on_top(self, tmp_path):
        repo = _project(tmp_path)
        with _enter(repo) as co:
            _write(Path(co.path) / "package.json", '{"version": "1.0.1"}\n')
            _commit_all(co.path, "release")
            release_checkout.advance_live_branch("HEAD", rerun="re-run it")
            _write(repo / "notes.txt", "on top\n")
            on_top = _commit_all(repo, "on top")
            ok, reason = release_checkout.unwind_last_advance()
        assert not ok and "committed on top" in reason
        assert git(repo, "rev-parse", "refs/heads/main") == on_top


class TestWriteScope:
    def test_standalone_scope_and_partition(self, tmp_path):
        repo = _project(tmp_path)
        scope = release_checkout.write_scope(
            live_root=str(repo), project_dirs=[(str(repo), None)],
            state_homes=[str(repo / ".rlsbl")],
        )
        assert {".rlsbl", "CHANGELOG.md", "package.json"} <= set(scope)
        blocking, ignored = release_checkout.partition_changes(
            [(" M", "package.json"), (" M", "README.md"),
             ("??", ".rlsbl/releases/unreleased.toml"), ("??", "x/y.txt")],
            scope,
        )
        assert [p for _s, p in blocking] == [
            "package.json", ".rlsbl/releases/unreleased.toml",
        ]
        assert [p for _s, p in ignored] == ["README.md", "x/y.txt"]

    def test_rlsbl_s_own_bookkeeping_is_never_counted(self, tmp_path):
        repo = _project(tmp_path)
        _write(repo / ".rlsbl" / "releases" / "in-progress.json", "{}\n")
        _write(repo / ".rlsbl" / "lock", "")
        assert release_checkout.live_changes(str(repo)) == []


# ---------------------------------------------------------------------------
# End to end: `rlsbl release run`
# ---------------------------------------------------------------------------


_PRODUCER_AND_CONCURRENT_EDIT = """#!/bin/sh
set -e
# A producer: the release commits what it generates.
cp src.txt generated.txt
# Another session edits a tracked file in the working tree mid-release.
printf 'edited by another session mid-release\\n' > "$RLSBL_TEST_LIVE/notes.txt"
"""


class TestReleaseRunsInTheCheckout:
    def test_a_successful_release_leaves_other_sessions_edits_byte_for_byte(
        self, tmp_path, monkeypatch,
    ):
        repo = _project(tmp_path, pre_checks=_PRODUCER_AND_CONCURRENT_EDIT)
        monkeypatch.setenv("RLSBL_TEST_LIVE", str(repo))
        # Another session's uncommitted work, before the release starts.
        (repo / "README.md").write_text("another session's README edit\n")
        (repo / "src.txt").write_text("UNCOMMITTED SOURCE\n")
        (repo / "wip.txt").write_text("another session's untracked file\n")
        readme, src, wip = (_bytes(repo / n) for n in ("README.md", "src.txt", "wip.txt"))

        result = _release(repo, monkeypatch)

        assert result.exit_code == 0, result.stderr + result.stdout
        assert "Releasing from the release checkout" in result.stdout
        assert "README.md" in result.stderr, "ignored changes are listed"
        # The release shipped and the branch is its last commit, on origin too.
        head = git(repo, "rev-parse", "refs/heads/main")
        assert git(repo, "ls-remote", "origin", "refs/heads/main").split()[0] == head
        assert git(repo, "rev-parse", "v1.0.1^{commit}")
        # Uncommitted source never reached the generated file the release committed.
        assert git(repo, "show", "v1.0.1:generated.txt") == "committed source"
        assert (repo / "generated.txt").read_text() == "committed source\n"
        # Every other session's edit is exactly as it was.
        assert _bytes(repo / "README.md") == readme
        assert _bytes(repo / "src.txt") == src
        assert _bytes(repo / "wip.txt") == wip
        assert (repo / "notes.txt").read_text() == "edited by another session mid-release\n"
        # ...and none of it is in the release.
        for name in ("README.md", "src.txt", "notes.txt"):
            assert git(repo, "show", f"{head}:{name}") != (repo / name).read_text().rstrip("\n")
        assert git(repo, "ls-tree", "--name-only", head, "wip.txt") == ""
        assert json.loads((repo / "package.json").read_text())["version"] == "1.0.1"
        assert sorted(_status(repo).splitlines()) == [
            " M README.md", " M notes.txt", " M src.txt", "?? wip.txt",
        ]
        assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

    def test_a_failed_release_leaves_other_sessions_edits_byte_for_byte(
        self, tmp_path, monkeypatch,
    ):
        repo = _project(tmp_path, pre_checks=_PRODUCER_AND_CONCURRENT_EDIT)
        monkeypatch.setenv("RLSBL_TEST_LIVE", str(repo))
        pin = git(repo, "rev-parse", "HEAD")
        hook = _reject_pushes(tmp_path / "remote")
        (repo / "README.md").write_text("another session's README edit\n")
        (repo / "src.txt").write_text("UNCOMMITTED SOURCE\n")
        readme, src = _bytes(repo / "README.md"), _bytes(repo / "src.txt")

        result = _release(repo, monkeypatch)

        assert result.exit_code != 0
        assert "before the release candidate was pushed" in result.stderr
        # The branch is back where the release found it, with nothing of it
        # in the working tree, and every other session's edit is intact.
        assert git(repo, "rev-parse", "refs/heads/main") == pin
        assert json.loads((repo / "package.json").read_text())["version"] == "1.0.0"
        assert not (repo / "generated.txt").exists()
        assert _bytes(repo / "README.md") == readme
        assert _bytes(repo / "src.txt") == src
        assert (repo / "notes.txt").read_text() == "edited by another session mid-release\n"
        assert sorted(_status(repo).splitlines()) == [
            " M README.md", " M notes.txt", " M src.txt",
        ]
        assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

        # The fix the message names: address the error, re-run the release.
        hook.unlink()
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout
        assert git(repo, "rev-parse", "v1.0.1^{commit}")

    def test_the_branch_moving_mid_release_is_refused(self, tmp_path, monkeypatch):
        """The compare-and-swap: a commit that lands on the branch between the
        release's last look and its advance is never overwritten."""
        repo = _project(tmp_path)
        pin = git(repo, "rev-parse", "HEAD")
        real_advance = release_checkout.advance_live_branch
        moved = {}

        def someone_commits_first(new_sha, **kwargs):
            if not moved:
                _write(repo / "notes.txt", "someone else's commit\n")
                git(repo, "add", "notes.txt")
                git(repo, "commit", "-q", "-m", "chore: someone else",
                    "--trailer", "Autogenerated: true")
                moved["sha"] = git(repo, "rev-parse", "HEAD")
            return real_advance(new_sha, **kwargs)

        monkeypatch.setattr(release_checkout, "advance_live_branch", someone_commits_first)
        result = _release(repo, monkeypatch)

        assert result.exit_code != 0
        assert "moved while the release was running" in result.stderr
        assert moved["sha"][:12] in result.stderr
        assert git(repo, "rev-parse", "refs/heads/main") == moved["sha"]
        assert git(repo, "rev-parse", f"{moved['sha']}~1") == pin
        assert json.loads((repo / "package.json").read_text())["version"] == "1.0.0"
        assert _status(repo) == ""
        assert git(repo, "ls-remote", "origin", "refs/heads/main").split()[0] == pin
        assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

        # The fix the refusal names: take the commits in (this one carries the
        # Autogenerated trailer, so the changelog already accounts for it) and
        # re-run the release.
        monkeypatch.setattr(release_checkout, "advance_live_branch", real_advance)
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout
        assert subprocess.run(
            ["git", "merge-base", "--is-ancestor", moved["sha"], "v1.0.1"],
            cwd=repo,
        ).returncode == 0

    def test_an_uncommitted_edit_to_a_file_the_release_writes_refuses_it(
        self, tmp_path, monkeypatch,
    ):
        repo = _project(tmp_path)
        pin = git(repo, "rev-parse", "HEAD")
        (repo / "package.json").write_text(
            json.dumps({"name": "pkg", "version": "1.0.0", "private": False}, indent=2) + "\n"
        )
        (repo / "README.md").write_text("unrelated edit\n")

        result = _release(repo, monkeypatch)

        assert result.exit_code != 0
        assert "package.json" in result.stderr
        assert "Commit those changes" in result.stderr
        assert git(repo, "rev-parse", "refs/heads/main") == pin
        assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

        # The fix it names: commit the change, then re-run.
        git(repo, "add", "package.json")
        git(repo, "commit", "-q", "-m", "chore: package metadata",
            "--trailer", "Autogenerated: true")
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout
        assert (repo / "README.md").read_text() == "unrelated edit\n"

    def test_dry_run_reports_a_dirty_tree_and_exits_zero(self, tmp_path, monkeypatch):
        repo = _project(tmp_path)
        pin = git(repo, "rev-parse", "HEAD")
        (repo / "package.json").write_text('{"name": "pkg", "version": "1.0.0"}\n')
        (repo / "README.md").write_text("unrelated edit\n")

        result = _release(repo, monkeypatch, "--dry-run")

        assert result.exit_code == 0, result.stderr + result.stdout
        assert "would refuse" in result.stderr and "package.json" in result.stderr
        assert "README.md" in result.stderr
        assert git(repo, "rev-parse", "refs/heads/main") == pin
        assert not (repo / ".git" / "rlsbl" / "release-checkout").exists()

    def test_a_detached_head_is_refused_and_checking_the_branch_out_clears(
        self, tmp_path, monkeypatch,
    ):
        repo = _project(tmp_path)
        git(repo, "checkout", "-q", "--detach")
        result = _release(repo, monkeypatch)
        assert result.exit_code != 0
        assert "detached" in result.stderr
        git(repo, "checkout", "-q", "main")
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout

    def test_an_ignored_release_file_is_refused_until_committed(self, tmp_path, monkeypatch):
        repo = _project(tmp_path)
        release_file = repo / ".rlsbl" / "releases" / "unreleased.toml"
        git(repo, "rm", "-q", "--cached", str(release_file))
        git(repo, "commit", "-q", "-m", "stop tracking the release file",
            "--trailer", "Autogenerated: true")
        exclude = repo / ".git" / "info" / "exclude"
        exclude.write_text(".rlsbl/releases/unreleased.toml\n")

        result = _release(repo, monkeypatch)
        assert result.exit_code != 0
        assert "is not committed" in result.stderr

        # The fix it names: commit it, then re-run.
        exclude.write_text("")
        git(repo, "add", str(release_file))
        git(repo, "commit", "-q", "-m", "add the release file",
            "--trailer", "Autogenerated: true")
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout

    def test_the_working_tree_leaving_the_branch_mid_release_is_refused(
        self, tmp_path, monkeypatch,
    ):
        repo = _project(tmp_path)
        pin = git(repo, "rev-parse", "HEAD")
        real_advance = release_checkout.advance_live_branch

        def switch_first(new_sha, **kwargs):
            git(repo, "checkout", "-q", "-b", "elsewhere")
            return real_advance(new_sha, **kwargs)

        monkeypatch.setattr(release_checkout, "advance_live_branch", switch_first)
        result = _release(repo, monkeypatch)
        assert result.exit_code != 0
        assert "no longer on main" in result.stderr
        assert git(repo, "rev-parse", "refs/heads/main") == pin

        # The fix it names: check the branch out again, then re-run.
        monkeypatch.setattr(release_checkout, "advance_live_branch", real_advance)
        git(repo, "checkout", "-q", "main")
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout

    def test_a_refused_unwind_keeps_the_release_resumable(self, tmp_path, monkeypatch):
        """The candidate push is refused AND something landed on top of the
        release commit meanwhile: the advance is not taken back (that would
        drop the other commit), the state is kept, and `rlsbl release resume`
        -- the fix the message names -- completes the release."""
        repo = _project(tmp_path)
        remote = tmp_path / "remote"
        hook = remote / "hooks" / "pre-receive"
        hook.write_text(
            "#!/bin/sh\n"
            f"cd '{repo}' && unset GIT_DIR GIT_QUARANTINE_PATH GIT_OBJECT_DIRECTORY "
            "GIT_ALTERNATE_OBJECT_DIRECTORIES && "
            "printf 'x\\n' >> notes.txt && git add notes.txt && "
            "git commit -q -m 'chore: on top' --trailer 'Autogenerated: true'\n"
            "exit 1\n"
        )
        hook.chmod(0o755)

        result = _release(repo, monkeypatch)
        assert result.exit_code != 0
        assert "could not be taken back" in result.stderr
        assert "rlsbl release resume" in result.stderr
        assert (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

        def resume():
            monkeypatch.chdir(repo)
            with _github_stubbed():
                return app.test(
                    ["release", "resume", "--no-watch", "--approve-consequential"]
                )

        # A resume refuses an uncommitted change to a file it writes, naming
        # the resume as what to run once it is committed.
        (repo / "package.json").write_text(
            (repo / "package.json").read_text().replace(
                '"name": "pkg"', '"name": "pkg", "private": false')
        )
        refused = resume()
        assert refused.exit_code != 0
        assert "package.json" in refused.stderr
        assert "then run `rlsbl release resume`" in refused.stderr
        git(repo, "add", "package.json")
        git(repo, "commit", "-q", "-m", "chore: package metadata",
            "--trailer", "Autogenerated: true")

        # A resume whose candidate push is refused puts the state back and
        # names the resume again.
        hook.write_text("#!/bin/sh\nexit 1\n")
        again = resume()
        assert again.exit_code != 0
        assert "re-run:\n  rlsbl release resume" in again.stderr
        assert (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

        hook.unlink()
        resumed = resume()
        assert resumed.exit_code == 0, resumed.stderr + resumed.stdout
        assert git(repo, "rev-parse", "v1.0.1^{commit}")
        assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

    def test_a_checkout_left_unclean_is_refused_until_deleted(self, tmp_path, monkeypatch):
        """The checkout is reset and cleaned before every release; should that
        ever leave it dirty, the release refuses, and deleting the checkout --
        the fix the refusal names -- clears it."""
        import shutil

        repo = _project(tmp_path)
        real = release_checkout._dirty_records
        checkout = os.path.realpath(repo / ".git" / "rlsbl" / "release-checkout")

        def left_dirty(cwd):
            if os.path.realpath(cwd) == checkout:
                return [(" M", "README.md")]
            return real(cwd)

        monkeypatch.setattr(release_checkout, "_dirty_records", left_dirty)
        result = _release(repo, monkeypatch)
        assert result.exit_code != 0
        assert "is not clean after being reset" in result.stderr
        assert checkout in result.stderr

        monkeypatch.setattr(release_checkout, "_dirty_records", real)
        shutil.rmtree(checkout)
        again = _release(repo, monkeypatch)
        assert again.exit_code == 0, again.stderr + again.stdout


# ---------------------------------------------------------------------------
# End to end: a workspace -- one releasable, and a batch of several
# ---------------------------------------------------------------------------


def _workspace(tmp_path, names):
    """A workspace with one npm releasable per name under packages/<name>,
    each one covered commit ahead of <name>@v1.0.0, and a bare remote."""
    from conftest import make_workspace
    from rlsbl.workspace import (
        get_releasable_changes_dir, get_releasable_dir, write_releasable_version,
    )

    root = tmp_path / "ws"
    init_repo(root)
    for name in names:
        member = root / "packages" / name
        _write(member / "package.json",
               json.dumps({"name": name, "version": "1.0.0"}, indent=2) + "\n")
        _write(member / ".rlsbl" / "config.json", json.dumps(
            {"publish_mode": "ci", "targets": ["npm"], "pipelines": {},
             "tag": False}) + "\n")
    make_workspace(
        str(root),
        [{"path": f"packages/{n}", "name": n, "releasable": n} for n in names],
        releasables=list(names),
    )
    _write(root / "README.md", "# ws\n")
    for name in names:
        write_releasable_version(str(root), name, "1.0.0")
        _write(Path(get_releasable_changes_dir(str(root), name)) / "unreleased.jsonl", "")
        _write(Path(get_releasable_dir(str(root), name)) / "config.json", "{}\n")
    _commit_all(root, "initial")
    for name in names:
        record_release(root, f"{name}@v1.0.0")
    for name in names:
        _write(root / "packages" / name / "feature.txt", f"{name} feature\n")
        feature = _commit_all(root, f"{name}: add feature")
        entry = {
            "format_version": 1, "commits": [feature], "user_facing": True,
            "description": f"**{name} feature.** It does a thing.", "type": "feature",
        }
        _write(Path(get_releasable_changes_dir(str(root), name)) / "unreleased.jsonl",
               json.dumps(entry) + "\n")
        _commit_all(root, f"changelog: {name} entry", autogenerated=True)
    add_remote(root, tmp_path / "remote")
    return root


def _tag_exists(repo, tag):
    return subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", f"refs/tags/{tag}"],
        cwd=str(repo), capture_output=True,
    ).returncode == 0


class TestWorkspaceReleasesRunInTheCheckout:
    def test_a_releasable_release(self, tmp_path, monkeypatch):
        from rlsbl.workspace import get_releasable_dir

        root = _workspace(tmp_path, ["alpha"])
        rel_dir = Path(get_releasable_dir(str(root), "alpha"))
        _write(rel_dir / "releases" / "unreleased.toml",
               'format_version = 1\nbump = "patch"\ninclude = ["npm"]\n'
               'exclude = []\ndescription = "an alpha patch"\n')
        _commit_all(root, "alpha release file", autogenerated=True)
        (root / "README.md").write_text("another session's edit\n")
        readme = _bytes(root / "README.md")

        result = _release(root / "packages" / "alpha", monkeypatch)

        assert result.exit_code == 0, result.stderr + result.stdout
        assert "Releasing from the release checkout" in result.stdout
        assert _tag_exists(root, "alpha@v1.0.1")
        assert (rel_dir / "releases" / "v1.0.1.toml").exists()
        assert not (rel_dir / "releases" / "unreleased.toml").exists()
        assert json.loads(
            (root / "packages" / "alpha" / "package.json").read_text()
        )["version"] == "1.0.1"
        assert _bytes(root / "README.md") == readme
        assert _status(root) == " M README.md"
        assert git(root, "ls-remote", "origin", "refs/heads/main").split()[0] == \
            git(root, "rev-parse", "refs/heads/main")

    def test_a_batch_of_several_releasables(self, tmp_path, monkeypatch):
        root = _workspace(tmp_path, ["alpha", "beta"])
        batch_release = lambda: app.test([  # noqa: E731
            "monorepo", "release", "run", "--no-watch", "--approve-consequential",
        ])
        _write(root / ".rlsbl-monorepo" / "releases" / "unreleased.toml",
               '[releasables.alpha]\nbump = "patch"\ndescription = "alpha patch"\n'
               'include = ["npm"]\nexclude = []\n\n'
               '[releasables.beta]\nbump = "minor"\ndescription = "beta minor"\n'
               'include = ["npm"]\nexclude = []\n')
        _commit_all(root, "batch release file", autogenerated=True)
        (root / "README.md").write_text("another session's edit\n")
        (root / "packages" / "beta" / "notes.txt").write_text("untracked wip\n")
        readme = _bytes(root / "README.md")

        # A member's version file with an uncommitted change refuses the
        # whole batch, naming it; committing it (the named fix) clears it.
        beta_pkg = root / "packages" / "beta" / "package.json"
        beta_pkg.write_text(beta_pkg.read_text().replace(
            '"name": "beta"', '"name": "beta", "private": false'))

        monkeypatch.chdir(root)
        with _github_stubbed(), patch(
            "rlsbl.commands.monorepo.batch_release.validate_gh_cli",
        ), patch(
            "rlsbl.commands.monorepo.batch_release.validate_gh_push_access",
        ):
            refused = batch_release()
            assert refused.exit_code != 0
            assert "packages/beta/package.json" in refused.stderr
            assert "then re-run `rlsbl monorepo release run`" in refused.stderr
            git(root, "add", str(beta_pkg))
            git(root, "commit", "-q", "-m", "chore: beta metadata",
                "--trailer", "Autogenerated: true")
            result = batch_release()

        assert result.exit_code == 0, result.stderr + result.stdout
        assert "Releasing from the release checkout" in result.stdout
        assert (root / ".git" / "rlsbl" / "release-checkout").is_dir()
        assert _tag_exists(root, "alpha@v1.0.1")
        assert _tag_exists(root, "beta@v1.1.0")
        assert _bytes(root / "README.md") == readme
        assert (root / "packages" / "beta" / "notes.txt").read_text() == "untracked wip\n"
        assert sorted(_status(root).splitlines()) == [
            " M README.md", "?? packages/beta/notes.txt",
        ]
        assert git(root, "ls-remote", "origin", "refs/heads/main").split()[0] == \
            git(root, "rev-parse", "refs/heads/main")
