"""Tests for monorepo status subcommand and monorepo-aware rlsbl status."""

import json
import os
import subprocess

import pytest

from conftest import make_ctx
from rlsbl.changelog.resolve import _unreleased_range
from rlsbl.commands.monorepo import _cmd_init, _cmd_add, _cmd_status
from rlsbl.workspace import load_workspace, save_workspace, WORKSPACE_DIR, WORKSPACE_FILE


def _make_npm_project(base_path, subdir, version="0.1.0"):
    """Create a minimal npm project (package.json) so detect_targets finds it."""
    proj_dir = os.path.join(str(base_path), subdir)
    os.makedirs(proj_dir, exist_ok=True)
    with open(os.path.join(proj_dir, "package.json"), "w") as f:
        json.dump({"name": "test-" + subdir.replace("/", "-"), "version": version}, f)
    return subdir


class TestMonorepoStatus:
    """Tests for the 'rlsbl monorepo status' subcommand."""

    def test_status_empty_workspace(self, mock_git_repo, capsys):
        _cmd_init({}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "No projects in workspace." in captured.out

    def test_status_with_projects(self, mock_git_repo, capsys):
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "pkg-a", version="1.0.0")
        _cmd_add(["pkg-a"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        # Header
        assert "Project" in captured.out
        assert "Path" in captured.out
        assert "Target" in captured.out
        assert "Version" in captured.out
        assert "Tag" in captured.out
        assert "Unreleased" in captured.out
        # Project row
        assert "pkg-a" in captured.out
        assert "npm" in captured.out
        assert "1.0.0" in captured.out

    def test_status_shows_unreleased(self, mock_git_repo, capsys):
        """Project with no tag shows (none) for tag and info in Unreleased column."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "mylib", version="0.2.0")
        _cmd_add(["mylib"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "(none)" in captured.out

    def test_status_shows_released(self, mock_git_repo, capsys):
        """Project with a tag matching its version shows 'released'."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "mylib", version="1.0.0")
        _cmd_add(["mylib"], {}, project_root=".")
        # Create a matching tag
        subprocess.run(
            ["git", "tag", "mylib@v1.0.0"],
            cwd=str(mock_git_repo),
            check=True,
        )
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "released" in captured.out
        assert "mylib@v1.0.0" in captured.out

    def test_status_no_workspace(self, mock_git_repo, capsys):
        """Without an initialized workspace, status should error."""
        with pytest.raises(SystemExit):
            _cmd_status({}, project_root=".")

    def test_status_multiple_projects(self, mock_git_repo, capsys):
        """Status displays all projects in the workspace."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "alpha", version="1.0.0")
        _make_npm_project(mock_git_repo, "beta", version="2.0.0")
        _cmd_add(["alpha"], {}, project_root=".")
        _cmd_add(["beta"], {}, project_root=".")
        # Tag only alpha
        subprocess.run(
            ["git", "tag", "alpha@v1.0.0"],
            cwd=str(mock_git_repo),
            check=True,
        )
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        # Header + 2 project rows
        assert len(lines) == 3
        assert "alpha" in captured.out
        assert "beta" in captured.out


class TestMonorepoStatusReleasableChangelog:
    """Releasable members keep their canonical CHANGELOG.md at the
    releasable level; the Unreleased column must reflect the releasable's
    changelog state instead of showing 'no changelog'."""

    def test_releasable_member_shows_releasable_changelog(self, mock_git_repo, capsys):
        from rlsbl.workspace import Releasable, get_releasable_dir, save_workspace

        _make_npm_project(mock_git_repo, "pkg-a", version="1.0.0")
        save_workspace(
            str(mock_git_repo),
            [{"path": "pkg-a", "name": "pkg-a", "releasable": "alpha"}],
            releasables=[Releasable(name="alpha")],
        )
        rel_dir = get_releasable_dir(str(mock_git_repo), "alpha")
        os.makedirs(rel_dir, exist_ok=True)
        with open(os.path.join(rel_dir, "CHANGELOG.md"), "w") as f:
            f.write(
                "<!-- Generated by rlsbl -->\n\n# Changelog\n\n"
                "## 1.1.0\n\n- New thing.\n- Another thing.\n\n"
                "## 1.0.0\n\n- Old thing.\n"
            )
        # No member-level CHANGELOG.md exists
        assert not os.path.exists(
            os.path.join(str(mock_git_repo), "pkg-a", "CHANGELOG.md")
        )

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "no changelog" not in captured.out, (
            "releasable members must show the releasable's changelog state"
        )
        # No tag -> all 3 bullets count as unreleased
        assert "3 entries" in captured.out

    def test_releasable_member_without_any_changelog(self, mock_git_repo, capsys):
        from rlsbl.workspace import Releasable, save_workspace

        _make_npm_project(mock_git_repo, "pkg-b", version="1.0.0")
        save_workspace(
            str(mock_git_repo),
            [{"path": "pkg-b", "name": "pkg-b", "releasable": "beta"}],
            releasables=[Releasable(name="beta")],
        )

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "no changelog" in captured.out


class TestMonorepoStatusChangelog:
    """Tests for the Unreleased changelog column in monorepo status."""

    def test_no_changelog_file(self, mock_git_repo, capsys):
        """Project with no CHANGELOG.md shows 'no changelog'."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "pkg-a", version="0.1.0")
        _cmd_add(["pkg-a"], {}, project_root=".")
        # Auto-scaffold creates CHANGELOG.md; remove it to test the missing case
        changelog = os.path.join(str(mock_git_repo), "pkg-a", "CHANGELOG.md")
        if os.path.exists(changelog):
            os.remove(changelog)
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "no changelog" in captured.out

    def test_changelog_with_entries_no_tag(self, mock_git_repo, capsys):
        """Changelog with bullets and no git tag shows entry count."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "pkg-b", version="0.1.0")
        _cmd_add(["pkg-b"], {}, project_root=".")
        changelog = mock_git_repo / "pkg-b" / "CHANGELOG.md"
        changelog.write_text("## 0.1.0\n- Added X\n- Added Y\n")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "2 entries" in captured.out

    def test_changelog_entries_above_tagged_version(self, mock_git_repo, capsys):
        """Only bullets above the tagged version heading are counted."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "proj", version="0.2.0")
        _cmd_add(["proj"], {}, project_root=".")
        changelog = mock_git_repo / "proj" / "CHANGELOG.md"
        changelog.write_text("## 0.2.0\n- New feature\n## 0.1.0\n- Initial\n")
        # Create tag matching version 0.1.0
        subprocess.run(
            ["git", "tag", "proj@v0.1.0"],
            cwd=str(mock_git_repo),
            check=True,
        )
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "1 entry" in captured.out

    def test_column_header_is_unreleased(self, mock_git_repo, capsys):
        """The column header should be 'Unreleased', not 'Status'."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "pkg-c", version="0.1.0")
        _cmd_add(["pkg-c"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]
        assert "Unreleased" in header_line


class TestStatusMonorepoAware:
    """Tests for monorepo awareness in 'rlsbl status'."""

    def test_status_shows_monorepo_hint(self, mock_git_repo, monkeypatch, capsys):
        """When inside a monorepo project, status output includes the hint."""
        # Set up monorepo workspace
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "core", version="1.0.0")
        _cmd_add(["core"], {}, project_root=".")
        capsys.readouterr()

        # Change into the project directory
        monkeypatch.chdir(str(mock_git_repo / "core"))

        from rlsbl.commands.status import run_cmd
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        captured = capsys.readouterr()

        assert "Part of monorepo" in captured.out
        assert "rlsbl monorepo status" in captured.out
        assert "core@v1.0.0" in captured.out

    def test_status_standalone_unchanged(self, mock_git_repo, capsys):
        """When NOT in a monorepo, no hint shown."""
        # Create a standalone npm project (no monorepo init)
        with open(str(mock_git_repo / "package.json"), "w") as f:
            json.dump({"name": "standalone", "version": "1.0.0"}, f)

        from rlsbl.commands.status import run_cmd
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        captured = capsys.readouterr()

        assert "Part of monorepo" not in captured.out
        assert "Mono tag" not in captured.out
        # Normal status output still works
        assert "Package:" in captured.out
        assert "standalone" in captured.out

    def test_status_monorepo_root_shows_hint_only(self, mock_git_repo, capsys):
        """At monorepo root (not inside a project), show hint without scoped tag."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "core", version="1.0.0")
        _cmd_add(["core"], {}, project_root=".")
        capsys.readouterr()

        # Create a package.json at root so status command works
        with open(str(mock_git_repo / "package.json"), "w") as f:
            json.dump({"name": "monorepo-root", "version": "0.0.1"}, f)

        from rlsbl.commands.status import run_cmd
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        captured = capsys.readouterr()

        assert "Part of monorepo" in captured.out
        # Root is not a registered project, so no mono tag
        assert "Mono tag" not in captured.out


class TestStatusTagScoping:
    """Tests that status coverage uses monorepo-scoped tags via tag_glob."""

    def test_monorepo_passes_tag_glob(self, mock_git_repo, monkeypatch, capsys):
        """In a monorepo project, _unreleased_range receives the computed tag_glob."""
        from unittest.mock import patch

        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "mylib", version="1.0.0")
        _cmd_add(["mylib"], {}, project_root=".")

        # Set up .rlsbl/changes so coverage code path is triggered
        changes_dir = mock_git_repo / "mylib" / ".rlsbl" / "changes"
        changes_dir.mkdir(parents=True, exist_ok=True)
        (changes_dir / "unreleased.jsonl").write_text("")

        capsys.readouterr()

        monkeypatch.chdir(str(mock_git_repo / "mylib"))

        captured_calls = []
        original_unreleased_range = _unreleased_range

        def spy_unreleased_range(tag_glob=None):
            captured_calls.append(tag_glob)
            return original_unreleased_range(tag_glob=tag_glob)

        with patch(
            "rlsbl.commands.status._unreleased_range",
            side_effect=spy_unreleased_range,
        ):
            from rlsbl.commands.status import run_cmd
            run_cmd("npm", [], {}, ctx=make_ctx("."))

        assert len(captured_calls) == 1
        assert captured_calls[0] == "mylib@v*"

    def test_standalone_no_tag_glob(self, mock_git_repo, monkeypatch, capsys):
        """In a standalone project, _unreleased_range receives no tag_glob."""
        from unittest.mock import patch

        # Create a standalone npm project (no monorepo init)
        with open(str(mock_git_repo / "package.json"), "w") as f:
            json.dump({"name": "standalone", "version": "1.0.0"}, f)

        # Set up .rlsbl/changes so coverage code path is triggered
        changes_dir = mock_git_repo / ".rlsbl" / "changes"
        changes_dir.mkdir(parents=True, exist_ok=True)
        (changes_dir / "unreleased.jsonl").write_text("")

        capsys.readouterr()

        captured_calls = []
        original_unreleased_range = _unreleased_range

        def spy_unreleased_range(tag_glob=None):
            captured_calls.append(tag_glob)
            return original_unreleased_range(tag_glob=tag_glob)

        with patch(
            "rlsbl.commands.status._unreleased_range",
            side_effect=spy_unreleased_range,
        ):
            from rlsbl.commands.status import run_cmd
            run_cmd("npm", [], {}, ctx=make_ctx("."))

        assert len(captured_calls) == 1
        assert captured_calls[0] is None

    def test_collect_status_forwards_tag_glob(self, mock_git_repo, capsys):
        """_collect_status passes tag_glob through to _unreleased_range."""
        from unittest.mock import patch

        with open(str(mock_git_repo / "package.json"), "w") as f:
            json.dump({"name": "test-pkg", "version": "1.0.0"}, f)

        # Set up .rlsbl/changes
        changes_dir = mock_git_repo / ".rlsbl" / "changes"
        changes_dir.mkdir(parents=True, exist_ok=True)
        (changes_dir / "unreleased.jsonl").write_text("")

        captured_calls = []
        original_unreleased_range = _unreleased_range

        def spy_unreleased_range(tag_glob=None):
            captured_calls.append(tag_glob)
            return original_unreleased_range(tag_glob=tag_glob)

        with patch(
            "rlsbl.commands.status._unreleased_range",
            side_effect=spy_unreleased_range,
        ):
            from rlsbl.commands.status import _collect_status
            _collect_status("npm", ".", tag_glob="my-project@v*", ctx=make_ctx("."))

        assert len(captured_calls) == 1
        assert captured_calls[0] == "my-project@v*"

    def test_monorepo_root_no_tag_glob(self, mock_git_repo, monkeypatch, capsys):
        """At monorepo root (not a registered project), tag_glob is None."""
        from unittest.mock import patch

        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "core", version="1.0.0")
        _cmd_add(["core"], {}, project_root=".")

        # Create a package.json at root so status works
        with open(str(mock_git_repo / "package.json"), "w") as f:
            json.dump({"name": "monorepo-root", "version": "0.0.1"}, f)

        # Set up .rlsbl/changes at root
        changes_dir = mock_git_repo / ".rlsbl" / "changes"
        changes_dir.mkdir(parents=True, exist_ok=True)
        (changes_dir / "unreleased.jsonl").write_text("")

        capsys.readouterr()

        captured_calls = []
        original_unreleased_range = _unreleased_range

        def spy_unreleased_range(tag_glob=None):
            captured_calls.append(tag_glob)
            return original_unreleased_range(tag_glob=tag_glob)

        with patch(
            "rlsbl.commands.status._unreleased_range",
            side_effect=spy_unreleased_range,
        ):
            from rlsbl.commands.status import run_cmd
            run_cmd("npm", [], {}, ctx=make_ctx("."))

        assert len(captured_calls) == 1
        # Root is not a project in the workspace, so no tag glob
        assert captured_calls[0] is None


class TestMonorepoStatusWatch:
    """Tests for watch path display in monorepo status."""

    def test_status_shows_watch_count(self, mock_git_repo, capsys):
        """Project with watch paths shows count in Watch column."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "tooling", version="1.0.0")
        _cmd_add(["tooling"], {}, project_root=".")

        # Add watch paths to workspace
        projects = load_workspace(".")
        for p in projects:
            if p["name"] == "tooling":
                p["watch"] = ["Package.swift", "shared/**"]
        save_workspace(".", projects)

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "Watch" in captured.out
        assert "2 paths" in captured.out

    def test_status_no_watch_shows_dash(self, mock_git_repo, capsys):
        """Project without watch paths shows '-' when Watch column is present."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "tooling", version="1.0.0")
        _make_npm_project(mock_git_repo, "core", version="1.0.0")
        _cmd_add(["tooling"], {}, project_root=".")
        _cmd_add(["core"], {}, project_root=".")

        # Add watch only to tooling
        projects = load_workspace(".")
        for p in projects:
            if p["name"] == "tooling":
                p["watch"] = ["Package.swift"]
        save_workspace(".", projects)

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "Watch" in captured.out
        assert "1 paths" in captured.out
        # core should show "-"
        lines = captured.out.strip().split("\n")
        core_line = [l for l in lines if "core" in l][0]
        assert "-" in core_line

    def test_status_no_watch_column_when_none(self, mock_git_repo, capsys):
        """Watch column is omitted when no project has watch paths."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "tooling", version="1.0.0")
        _cmd_add(["tooling"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "Watch" not in captured.out


class TestMonorepoStatusRemote:
    """Tests for subtree_remote display in monorepo status."""

    def test_status_shows_remote_column(self, mock_git_repo, capsys):
        """Project with subtree_remote shows Remote column with URL."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "tooling", version="1.0.0")
        _cmd_add(["tooling"], {}, project_root=".")

        # Add subtree_remote to workspace
        projects = load_workspace(".")
        for p in projects:
            if p["name"] == "tooling":
                p["subtree_remote"] = "git@github.com:user/tooling.git"
        save_workspace(".", projects)

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "Remote" in captured.out
        assert "git@github.com:user/tooling.git" in captured.out

    def test_status_no_remote_shows_dash(self, mock_git_repo, capsys):
        """Project without subtree_remote shows '-' when Remote column is present."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "tooling", version="1.0.0")
        _make_npm_project(mock_git_repo, "core", version="1.0.0")
        _cmd_add(["tooling"], {}, project_root=".")
        _cmd_add(["core"], {}, project_root=".")

        # Add subtree_remote only to tooling
        projects = load_workspace(".")
        for p in projects:
            if p["name"] == "tooling":
                p["subtree_remote"] = "git@github.com:user/tooling.git"
        save_workspace(".", projects)

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        assert "Remote" in captured.out
        # core should show "-" in the Remote column
        lines = captured.out.strip().split("\n")
        core_line = [l for l in lines if "core" in l and "tooling" not in l][0]
        # The last column should be "-" for core (since it has no remote)
        assert "-" in core_line


def _make_npm_project_with_deps(base_path, subdir, version="0.1.0", deps=None):
    """Create an npm project with optional dependencies in package.json."""
    proj_dir = os.path.join(str(base_path), subdir)
    os.makedirs(proj_dir, exist_ok=True)
    pkg = {"name": subdir, "version": version}
    if deps:
        pkg["dependencies"] = deps
    with open(os.path.join(proj_dir, "package.json"), "w") as f:
        json.dump(pkg, f)
    return subdir


def _setup_workspace_with_deps(base_path):
    """Create a workspace with three projects where lib-b depends on lib-a,
    and lib-c depends on both lib-a and lib-b.

    Returns the list of project dicts.
    """
    ws_dir = os.path.join(str(base_path), WORKSPACE_DIR)
    os.makedirs(ws_dir, exist_ok=True)

    _make_npm_project_with_deps(base_path, "lib-a", version="1.0.0")
    _make_npm_project_with_deps(base_path, "lib-b", version="1.0.0", deps={"lib-a": "^1.0.0"})
    _make_npm_project_with_deps(base_path, "lib-c", version="1.0.0", deps={"lib-a": "^1.0.0", "lib-b": "^1.0.0"})

    projects = [
        {"path": "lib-a", "name": "lib-a"},
        {"path": "lib-b", "name": "lib-b"},
        {"path": "lib-c", "name": "lib-c"},
    ]
    save_workspace(str(base_path), projects)
    return projects


class TestMonorepoStatusLibrary:
    """Tests for Library column in monorepo status."""

    def test_library_column_shown_when_project_is_library(self, mock_git_repo, capsys):
        """Library column appears with 'yes' when a project has library = true."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "mylib", version="1.0.0")
        _cmd_add(["mylib"], {"library": "true"}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]
        assert "Library" in header_line
        data_line = captured.out.strip().split("\n")[1]
        assert "yes" in data_line

    def test_library_column_hidden_when_no_library_projects(self, mock_git_repo, capsys):
        """Library column is omitted when no project has library = true."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "app-a", version="1.0.0")
        _make_npm_project(mock_git_repo, "app-b", version="2.0.0")
        _cmd_add(["app-a"], {}, project_root=".")
        _cmd_add(["app-b"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]
        assert "Library" not in header_line

    def test_library_column_mixed_workspace(self, mock_git_repo, capsys):
        """Mixed workspace: column shown, 'yes' for library projects, blank for others."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "mylib", version="1.0.0")
        _make_npm_project(mock_git_repo, "myapp", version="2.0.0")
        _cmd_add(["mylib"], {"library": "true"}, project_root=".")
        _cmd_add(["myapp"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]
        assert "Library" in header_line
        lines = captured.out.strip().split("\n")
        lib_line = [l for l in lines[1:] if "mylib" in l][0]
        app_line = [l for l in lines[1:] if "myapp" in l][0]
        # Find Library column position from header
        lib_col_start = header_line.index("Library")
        lib_col_end = lib_col_start + len("Library")
        # Check that mylib has "yes" in the Library column area
        assert lib_line[lib_col_start:lib_col_end].strip() == "yes"
        # Check that myapp has blank in the Library column area
        assert app_line[lib_col_start:lib_col_end].strip() == ""


class TestMonorepoStatusDeps:
    """Tests for Deps and Rdeps columns in monorepo status."""

    def test_deps_rdeps_columns_shown_when_deps_exist(self, mock_git_repo, capsys):
        """Deps and Rdeps columns appear when projects have intra-workspace deps."""
        _setup_workspace_with_deps(mock_git_repo)
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]
        assert "Deps" in header_line
        assert "Rdeps" in header_line

    def test_deps_rdeps_columns_hidden_when_no_deps(self, mock_git_repo, capsys):
        """Deps and Rdeps columns are hidden when no intra-workspace deps exist."""
        _cmd_init({}, project_root=".")
        _make_npm_project(mock_git_repo, "standalone-a", version="1.0.0")
        _make_npm_project(mock_git_repo, "standalone-b", version="1.0.0")
        _cmd_add(["standalone-a"], {}, project_root=".")
        _cmd_add(["standalone-b"], {}, project_root=".")
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]
        assert "Deps" not in header_line
        assert "Rdeps" not in header_line

    def test_correct_dep_counts(self, mock_git_repo, capsys):
        """Verify correct dep and rdep counts for a known dependency structure.

        lib-a: 0 deps, 2 rdeps (lib-b and lib-c depend on it)
        lib-b: 1 dep (lib-a), 1 rdep (lib-c depends on it)
        lib-c: 2 deps (lib-a, lib-b), 0 rdeps
        """
        _setup_workspace_with_deps(mock_git_repo)
        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        lines = captured.out.strip().split("\n")
        header = lines[0]

        # Find column start positions using header text positions
        deps_start = header.index("Deps")
        rdeps_start = header.index("Rdeps")

        # Find end positions: next column start or end of line
        # Columns are separated by 2+ spaces; find next column start after each
        def _col_end(start, col_name):
            """Find end of a column: start of next column header or end of line."""
            after = start + len(col_name)
            # Look for next non-space char after a gap of spaces
            rest = header[after:]
            stripped = rest.lstrip()
            if not stripped:
                return None  # last column
            return after + (len(rest) - len(stripped))

        deps_end = _col_end(deps_start, "Deps")
        rdeps_end = _col_end(rdeps_start, "Rdeps")

        # Parse each project row using fixed positions
        for line in lines[1:]:
            name = line.split()[0]
            deps_val = line[deps_start:deps_end].strip() if deps_end else line[deps_start:].strip()
            rdeps_val = line[rdeps_start:rdeps_end].strip() if rdeps_end else line[rdeps_start:].strip()

            if name == "lib-a":
                assert deps_val == "0", f"lib-a should have 0 deps, got {deps_val}"
                assert rdeps_val == "2", f"lib-a should have 2 rdeps, got {rdeps_val}"
            elif name == "lib-b":
                assert deps_val == "1", f"lib-b should have 1 dep, got {deps_val}"
                assert rdeps_val == "1", f"lib-b should have 1 rdep, got {rdeps_val}"
            elif name == "lib-c":
                assert deps_val == "2", f"lib-c should have 2 deps, got {deps_val}"
                assert rdeps_val == "0", f"lib-c should have 0 rdeps, got {rdeps_val}"

    def test_deps_columns_before_watch_and_remote(self, mock_git_repo, capsys):
        """Deps/Rdeps columns appear after Unreleased but before Watch and Remote."""
        _setup_workspace_with_deps(mock_git_repo)

        # Add watch paths and subtree remote to lib-a
        projects = load_workspace(".")
        for p in projects:
            if p["name"] == "lib-a":
                p["watch"] = ["shared/**"]
                p["subtree_remote"] = "git@github.com:user/lib-a.git"
        save_workspace(".", projects)

        capsys.readouterr()
        _cmd_status({}, project_root=".")
        captured = capsys.readouterr()
        header_line = captured.out.strip().split("\n")[0]

        # All dynamic columns should be present
        assert "Deps" in header_line
        assert "Rdeps" in header_line
        assert "Watch" in header_line
        assert "Remote" in header_line

        # Verify ordering: Deps before Watch, Rdeps before Watch
        deps_pos = header_line.index("Deps")
        rdeps_pos = header_line.index("Rdeps")
        watch_pos = header_line.index("Watch")
        remote_pos = header_line.index("Remote")
        assert deps_pos < rdeps_pos < watch_pos < remote_pos
