"""A release refuses a Go module that is not tidy, before anything mutates.

The release runs ``go mod tidy`` to refresh ``go.sum``. Nothing the release
itself writes changes a Go module's requirements, so on a tidy module that run
changes nothing; on an untidy one it rewrites ``go.mod``, and the release used
to stop late with an "unexpected modified files (possible concurrent change)"
abort that named the wrong cause. The refusal comes first now, names
``go mod tidy`` and a commit as the fix, and the test applies it.

Real git and a real Go toolchain; only gh, pushes, and fetches are faked. The
untidy requirement is a local ``replace``, so tidying needs no network.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from githarness import record_release

from rlsbl.commands.release import run_cmd
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run

pytestmark = pytest.mark.skipif(
    subprocess.run(["go", "version"], capture_output=True).returncode != 0,
    reason="needs a Go toolchain",
)

UNTIDY_GO_MOD = (
    "module example.com/lib\n\ngo 1.22\n\ntoolchain go1.22.0\n\n"
    "require example.com/dep v0.0.0\n\n"
    "replace example.com/dep => ./dep\n"
)


def _git(repo, *args):
    return subprocess.run(
        ["git", *args], cwd=str(repo), check=True, capture_output=True, text=True,
    ).stdout.strip()


def _commit(repo, message, *paths):
    _git(repo, "add", *paths)
    _git(repo, "commit", "-q", "-m", message, "--trailer", "Autogenerated: true")


def _go_project(repo):
    """A released Go library with one covered unreleased commit and an
    untidy go.mod: it requires a module no package imports."""
    (repo / "go.mod").write_text(UNTIDY_GO_MOD)
    (repo / "go.sum").write_text("")
    (repo / "VERSION").write_text("0.1.0\n")
    (repo / "lib.go").write_text("package lib\n\nfunc F() int { return 1 }\n")
    (repo / "dep").mkdir()
    (repo / "dep" / "go.mod").write_text("module example.com/dep\n\ngo 1.22\n")
    (repo / "dep" / "dep.go").write_text("package dep\n")
    changes = repo / ".rlsbl" / "changes"
    changes.mkdir(parents=True)
    (changes / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["go"]}) + "\n"
    )
    _commit(repo, "initial", ".")
    record_release(repo, "v0.1.0")

    (repo / "lib.go").write_text("package lib\n\nfunc F() int { return 2 }\n")
    _git(repo, "add", "lib.go")
    _git(repo, "commit", "-q", "-m", "change F")
    sha = _git(repo, "rev-parse", "HEAD")
    (changes / "unreleased.jsonl").write_text(json.dumps({
        "format_version": 1, "commits": [sha], "user_facing": True,
        "description": "**F.** Returns 2.", "type": "feature",
    }) + "\n")
    releases = repo / ".rlsbl" / "releases"
    releases.mkdir(parents=True, exist_ok=True)
    (releases / "unreleased.toml").write_text(
        'format_version = 1\nbump = "patch"\ninclude = ["go"]\nexclude = []\n'
        'description = "test release"\n'
    )
    _commit(repo, "changelog and release file", ".rlsbl")


def _fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
    if cmd == "gh":
        return ""
    if cmd == "git" and args and args[0] in ("push", "fetch"):
        return ""
    if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any(
        "origin/" in a for a in args
    ):
        return "0"
    return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)


def _release(repo):
    ctx = ProjectContext(
        project_root=Path(str(repo)), workspace_root=None,
        config={"publish_mode": "ci", "pipelines": {}},
    )
    with (
        patch("rlsbl.commands.release.check_gh_installed", return_value=True),
        patch("rlsbl.commands.release.check_gh_auth", return_value=True),
        patch("rlsbl.commands.release.push_if_needed"),
        patch("rlsbl.commands.release.run_gh", return_value=""),
        patch("rlsbl.commands.release.run", side_effect=_fake_run),
        patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
    ):
        run_cmd(
            ReleaseConfig(bump="patch", include=["go"], exclude=[]),
            {"quiet": True}, ctx=ctx,
        )


@pytest.fixture
def go_env(monkeypatch):
    monkeypatch.setenv("GOPROXY", "off")
    monkeypatch.setenv("GOFLAGS", "")
    monkeypatch.setenv("GOTOOLCHAIN", "local")


def test_an_untidy_go_module_is_refused_before_the_release_mutates(
    mock_git_repo, go_env, capsys,
):
    repo = mock_git_repo
    _go_project(repo)
    head = _git(repo, "rev-parse", "HEAD")

    with pytest.raises(SystemExit) as exc:
        _release(repo)
    assert exc.value.code == 1
    err = capsys.readouterr().err
    assert "is not tidy" in err
    assert "go mod tidy" in err
    assert "possible concurrent change" not in err
    assert _git(repo, "rev-parse", "HEAD") == head
    assert _git(repo, "tag", "-l", "v0.1.1") == ""

    # The fix the refusal names: tidy, commit go.mod and go.sum, re-run.
    subprocess.run(["go", "mod", "tidy"], cwd=str(repo), check=True)
    _git(repo, "add", "go.mod", "go.sum")
    _git(repo, "commit", "-q", "-m", "go mod tidy")
    sha = _git(repo, "rev-parse", "HEAD")
    changes = repo / ".rlsbl" / "changes" / "unreleased.jsonl"
    lines = changes.read_text().splitlines()
    lines.append(json.dumps({
        "format_version": 1, "commits": [sha], "user_facing": False,
    }))
    changes.write_text("\n".join(lines) + "\n")
    _commit(repo, "changelog: tidy", ".rlsbl/changes/unreleased.jsonl")

    _release(repo)
    assert "v0.1.1" in _git(repo, "tag", "-l", "v0.1.1")
    assert os.path.exists(repo / ".rlsbl" / "releases" / "v0.1.1.toml")
