"""The Phase-A / Phase-B seam of `rlsbl release run`, pinned.

`release run --dry-run` is the flagship preview: the deepest and most
consequential command in rlsbl, previewed by RECORDING the first half of a real
release rather than by describing it. Four properties make that honest, and
each is pinned here because each is one refactor away from being lost:

1. **The boundary exists, and it is in the right place.** The preview reports
   Phase A -- everything through the candidate push, whose effects really were
   recorded -- then the boundary line, then Phase B as a DECLARED table. A
   reader must never mistake the second for the first, and the ordering is what
   says which is which.
2. **The executor reads only through declared result captures.** The plan
   builder does the reading; the executor issues effects. If the executor
   starts asking questions of its own, the preview is back to truncating at the
   first observe after a recorded mutation -- the exact defect this design
   removed.
3. **The threading is what the design says it is.** Exactly one value crosses
   the seam (``candidate_sha``), produced by one step and consumed by two.
4. **A preview cannot push, by construction.** Not by a flag check that a
   future edit could invert: `git push` is a recorded effect like any other,
   and no observe allowlist prefix exists that could make it execute.
"""

import ast
import inspect
from pathlib import Path

import pytest

from rlsbl.commands.release import phase_a
from rlsbl.commands.release.validate import (
    BOUNDARY_LINE,
    print_release_preview,
    _phase_b_rows,
)


# ---------------------------------------------------------------------------
# Fixture plan: a hand-built Phase-A plan of the canonical shape.
#
# Built rather than derived from a repo so the seam assertions describe the
# SEAM and not whatever a fixture project happens to contain. The end-to-end
# rendering of a real preview is exercised by the release integration tests.
# ---------------------------------------------------------------------------


def _fixture_plan():
    return phase_a.PhaseAPlan(
        steps=[
            phase_a.PlanStep(
                kind=phase_a.WRITE_TARGET_VERSION,
                release_step="VERSION_BUMPED",
                summary="bump npm version in . -> 1.2.0",
                payload={"target": "npm", "path": ".", "version": "1.2.0",
                         "primary": True},
            ),
            phase_a.PlanStep(
                kind=phase_a.COMMIT,
                release_step="COMMITTED",
                summary="commit 2 file(s) as 'v1.2.0'",
                payload={"message": "v1.2.0", "files": ["package.json"],
                         "cwd": ".", "autogenerated": False},
                produces=phase_a.CANDIDATE_SHA,
                capture=(phase_a.CANDIDATE_SHA, ["git", "rev-parse", "HEAD"], "."),
                marks=("COMMITTED",),
            ),
            phase_a.PlanStep(
                kind=phase_a.RECORD_CANDIDATE,
                release_step="BRANCH_PUSHED",
                summary="record the candidate in in-progress.json",
                payload={"path": "in-progress.json",
                         "ref": phase_a.StepRef(phase_a.CANDIDATE_SHA)},
            ),
            phase_a.PlanStep(
                kind=phase_a.GUARD_CANDIDATE_WINDOW,
                release_step="BRANCH_PUSHED",
                summary=("refuse a candidate whose diff window cannot trigger "
                         "this project's CI"),
                payload={"remote_head": "a" * 40, "branch": "main",
                         "candidate": phase_a.StepRef(phase_a.CANDIDATE_SHA)},
                capture=("window",
                         ["git", "diff", "--name-only", "<base>..<candidate>"],
                         "."),
            ),
            phase_a.PlanStep(
                kind=phase_a.PUSH_CANDIDATE,
                release_step="BRANCH_PUSHED",
                summary="run git push --no-verify origin <candidate_sha>:refs/heads/main",
                payload={
                    "argv": ["git", "push", "--no-verify", "origin",
                             phase_a.StepRef(
                                 phase_a.CANDIDATE_SHA,
                                 template=phase_a.SLOT + ":refs/heads/main",
                             )],
                    "sha": phase_a.StepRef(phase_a.CANDIDATE_SHA),
                    "timeout": 300,
                },
                marks=("BRANCH_PUSHED",),
            ),
        ],
        files_to_commit=["package.json", "CHANGELOG.md"],
    )


class _FixtureState:
    """The slice of ReleaseState the preview renderer reads."""

    new_version = "1.2.0"
    tag = "v1.2.0"
    branch = "main"
    changes_dir = ".rlsbl/changes"
    monorepo_name = None
    monorepo_project_path = None


# ---------------------------------------------------------------------------
# 1. The boundary sits between the recorded log and the declared table
# ---------------------------------------------------------------------------


class TestPreviewBoundary:

    def _render(self):
        lines = []
        print_release_preview(
            lines.append, _fixture_plan(), _FixtureState(),
            registry="npm", files_to_commit=["package.json", "CHANGELOG.md"],
        )
        return "\n".join(lines)

    def test_the_boundary_line_is_rendered(self):
        assert BOUNDARY_LINE in self._render()

    def test_the_boundary_names_ci_as_what_everything_below_waits_on(self):
        assert "CI" in BOUNDARY_LINE
        assert "below" in BOUNDARY_LINE

    def test_the_recorded_phase_a_log_is_above_the_boundary(self):
        text = self._render()
        # Every Phase-A step the plan issued must appear before the line.
        for step in _fixture_plan().steps:
            assert step.summary in text, f"missing Phase-A step: {step.summary}"
            assert text.index(step.summary) < text.index(BOUNDARY_LINE), (
                f"Phase-A step rendered BELOW the boundary: {step.summary!r}. "
                "Everything above the line is recorded fact; everything below "
                "it waits on CI. A recorded effect under the line reads as a "
                "promise instead of a record."
            )

    def test_the_declared_phase_b_table_is_below_the_boundary(self):
        text = self._render()
        rows = _phase_b_rows(_FixtureState(), registry="npm")
        assert rows, "Phase B must declare its steps"
        for step, _what in rows:
            assert step in text, f"missing Phase-B row: {step}"
            assert text.index(BOUNDARY_LINE) < text.rindex(step), (
                f"Phase-B row rendered ABOVE the boundary: {step!r}. Nothing "
                "below the line was recorded, and the line is the only thing "
                "saying so."
            )

    def test_phase_b_is_labelled_as_not_recorded(self):
        assert "NOT recorded" in self._render()

    def test_phase_b_covers_the_whole_remaining_release(self):
        """Every canonical step after BRANCH_PUSHED is declared."""
        from rlsbl.commands.release.release_state import RELEASE_STEPS

        declared = {step for step, _ in _phase_b_rows(
            # Monorepo state: the subtree/mirror rows are only owed there.
            type("S", (_FixtureState,), {
                "monorepo_name": "pkg", "monorepo_project_path": "pkg",
            })(),
            registry="npm",
        )}
        after_push = RELEASE_STEPS[RELEASE_STEPS.index("BRANCH_PUSHED") + 1:]
        missing = [s for s in after_push if s not in declared]
        assert not missing, (
            f"Phase B does not declare {missing}. A step the preview omits is "
            "a step the operator does not know is coming."
        )


# ---------------------------------------------------------------------------
# 2. The executor's reads are only the whitelisted result captures
# ---------------------------------------------------------------------------


# The ONLY function in the executor that may read the WORLD. Everything the
# executor needs beyond the plan arrives through it.
_EXECUTOR_READ_WHITELIST = {"_capture"}

# Bare helper names that read the world. An executor method calling one of
# these is asking a question the builder was supposed to have answered.
_READ_CALLS = {"run", "run_gh", "head_sha", "_git_read", "_git_answer"}

# Reads of the release-state LEDGER. These are invisible to the world-read scan
# above (no subprocess, no git), so they are scanned separately -- an undeclared
# read that nothing can see is worse than one that is merely tolerated.
#
# The ledger is the executor's OWN writing surface: it records how far this walk
# has got, and reading it back is part of writing it. A builder-time snapshot
# cannot substitute, because ``save_step`` mutates the file between the build
# and every step that follows -- writing back a stale document would erase the
# markers the walk itself had just recorded. Each site below is tolerated for
# that reason and no other; anything new here has to earn its own line.
_LEDGER_CALLS = {"load_release_state", "save_step", "_track_release_commit"}

_TOLERATED_LEDGER_READS = {
    # Records each marker as the walk reaches it. The walk is the only thing
    # that knows how far it got.
    "run": {"save_step"},
    # The drift guard's trail: which commits this release created. A commit's
    # SHA does not exist until the commit step has run.
    "_settle": {"_track_release_commit"},
    # Reads back the document the walk has been writing, so the candidate SHA
    # joins the markers already recorded instead of replacing them.
    "_do_record_candidate": {"load_release_state"},
}

# Binaries whose reads the framework really executes under --dry-run (they are
# on the observe allowlist). An ``effects.run`` in the executor with one of
# these as a LITERAL first operand is an observe -- a read wearing the
# chokepoint's clothes. A run whose argv comes from the plan is fine: that is
# the step's own effect.
_OBSERVE_BINARIES = {"git", "gh"}


def _is_literal_observe(call):
    """True when *call* is ``effects.run(["git", ...])`` with a literal argv."""
    func = call.func
    if not (isinstance(func, ast.Attribute) and func.attr == "run"):
        return False
    if not (isinstance(func.value, ast.Name)
            and func.value.id in ("effects", "_effects")):
        return False
    if not call.args:
        return False
    argv = call.args[0]
    if not isinstance(argv, (ast.List, ast.Tuple)) or not argv.elts:
        return False
    first = argv.elts[0]
    return isinstance(first, ast.Constant) and first.value in _OBSERVE_BINARIES


def _executor_methods():
    """(name, ast.FunctionDef) for every method of the Phase-A executor."""
    tree = ast.parse(inspect.getsource(phase_a))
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "_Executor":
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    yield item.name, item


class TestExecutorReads:

    def test_the_executor_class_is_there_to_scan(self):
        names = [name for name, _ in _executor_methods()]
        assert names, "no _Executor methods found -- the scan below is vacuous"
        assert "_capture" in names

    def test_only_the_result_capture_issues_a_read(self):
        offenders = []
        for name, fn in _executor_methods():
            if name in _EXECUTOR_READ_WHITELIST:
                continue
            for node in ast.walk(fn):
                if not isinstance(node, ast.Call):
                    continue
                func = node.func
                if isinstance(func, ast.Name) and func.id in _READ_CALLS:
                    offenders.append(f"{name}() calls {func.id}()")
                elif _is_literal_observe(node):
                    offenders.append(f"{name}() issues a literal git/gh observe")
        assert not offenders, (
            "the Phase-A executor derives nothing and asks nothing: its only "
            "permitted read is the per-step declared result capture "
            f"(_capture). Found: {offenders}. Move the read into "
            "build_phase_a_plan, or declare it as the step's capture."
        )

    def test_every_ledger_read_is_named_and_justified(self):
        """The release-state reads are enumerated, not silently exempt.

        They do not touch git or the filesystem-as-world, so the scan above
        cannot see them at all. Scanning them separately is what keeps the
        "the executor asks nothing" claim honest: the reads that remain are
        listed, each at a named site, each for a recorded reason.
        """
        offenders = []
        for name, fn in _executor_methods():
            allowed = _TOLERATED_LEDGER_READS.get(name, frozenset())
            for node in ast.walk(fn):
                if not isinstance(node, ast.Call):
                    continue
                func = node.func
                called = (
                    func.id if isinstance(func, ast.Name)
                    else func.attr if isinstance(func, ast.Attribute)
                    else None
                )
                if called in _LEDGER_CALLS and called not in allowed:
                    offenders.append(f"{name}() calls {called}()")
        assert not offenders, (
            "the Phase-A executor read the release-state ledger somewhere it "
            f"is not accounted for: {offenders}. The ledger is the executor's "
            "own writing surface, and reading it back is only legitimate where "
            "the value being written did not exist at build time. Add the site "
            "to _TOLERATED_LEDGER_READS with the reason, or move the read into "
            "build_phase_a_plan."
        )

    def test_the_tolerated_ledger_reads_still_exist(self):
        """The whitelist is a record of real sites, not accumulated cruft."""
        methods = dict(_executor_methods())
        for name, calls in _TOLERATED_LEDGER_READS.items():
            assert name in methods, (
                f"_TOLERATED_LEDGER_READS names {name}(), which the executor no "
                "longer has -- drop the entry rather than leaving a standing "
                "exemption for a method that does not exist"
            )
            source = ast.dump(methods[name])
            for call in calls:
                assert f"'{call}'" in source, (
                    f"{name}() no longer calls {call}(): the exemption is dead "
                    "and must be removed, not left to cover a future read"
                )

    def test_the_capture_is_declared_per_step_not_improvised(self):
        """Every capture the executor runs was named by the builder."""
        for step in _fixture_plan().steps:
            if step.produces:
                assert step.capture is not None, (
                    f"step {step.kind!r} produces {step.produces!r} without a "
                    "declared capture: the executor would have to invent the "
                    "read."
                )
                name, argv, _cwd = step.capture
                assert name == step.produces
                assert argv and argv[0] == "git"


# ---------------------------------------------------------------------------
# 3. Value threading: one producer, three consumers, one value
# ---------------------------------------------------------------------------


class TestValueThreading:

    def test_exactly_one_value_crosses_the_seam(self):
        plan = _fixture_plan()
        assert plan.produced_names == [phase_a.CANDIDATE_SHA]

    def test_the_commit_step_produces_it(self):
        plan = _fixture_plan()
        producers = [s for s in plan.steps if s.produces == phase_a.CANDIDATE_SHA]
        assert len(producers) == 1
        assert producers[0].kind in (phase_a.COMMIT, phase_a.SNAPSHOT)

    def test_the_declared_consumers_are_the_only_consumers(self):
        """Four edges, not three.

        The design was first written down as "one producer and two consumers"
        -- the state-save and the push -- because those were the two steps
        holding a StepRef. The candidate-window guard read candidate_sha too,
        but it reached into the executor's value table instead of declaring it,
        so ``consumers_of`` could not see it and the count read as three. The
        guard now declares its consumption like the others, which makes four
        the true number: the count only ever undercounted because one consumer
        was threading the value off the plan's books.
        """
        plan = _fixture_plan()
        consumers = plan.consumers_of(phase_a.CANDIDATE_SHA)
        assert [s.kind for s in consumers] == [
            phase_a.RECORD_CANDIDATE,
            phase_a.GUARD_CANDIDATE_WINDOW,
            phase_a.PUSH_CANDIDATE,
        ], (
            "Phase A threads exactly four edges: the commit yields "
            "candidate_sha, and the state-save, the candidate-window guard and "
            "the push consume it -- each declaring the consumption in its own "
            "payload, so the plan is the whole truth about who reads the value."
        )

    def test_no_handler_threads_the_value_off_the_books(self):
        """A handler reaching into ``_values`` bypasses ``consumers_of``.

        ``_resolve`` is the declared path (it takes a StepRef out of the step's
        own payload). ``self._values`` is the raw table behind it, and a handler
        indexing it directly consumes the threaded value without the plan --
        and therefore the preview -- ever saying so.
        """
        offenders = []
        for name, fn in _executor_methods():
            if name in {"__init__", "_resolve", "_settle", "run"}:
                continue  # the threading machinery itself
            for node in ast.walk(fn):
                if not isinstance(node, ast.Attribute) or node.attr != "_values":
                    continue
                if isinstance(node.value, ast.Name) and node.value.id == "self":
                    offenders.append(name)
        assert not offenders, (
            f"{sorted(set(offenders))} read the executor's value table "
            "directly. Declare a StepRef in the step's payload and resolve it "
            "with self._resolve, so PhaseAPlan.consumers_of reports the edge."
        )

    def test_a_step_ref_renders_its_template_in_the_plan_table(self):
        ref = phase_a.StepRef(
            phase_a.CANDIDATE_SHA, template=phase_a.SLOT + ":refs/heads/main",
        )
        assert ref.render() == "<candidate_sha>:refs/heads/main"

    def test_the_plan_table_names_the_produced_value(self):
        table = phase_a.render_plan_table(_fixture_plan())
        assert "-> candidate_sha" in table


# ---------------------------------------------------------------------------
# 3b. The same threading, on a plan the REAL builder produced
#
# Everything above describes the seam through a hand-built plan, which pins the
# shape but cannot notice the builder drifting away from it. These drive
# build_phase_a_plan itself, over a stubbed-but-real project, so the
# one-producer / declared-consumers invariant is pinned on what the release
# actually issues.
# ---------------------------------------------------------------------------


class _BuiltState:
    """The slice of ReleaseState build_phase_a_plan reads."""

    current_version = "1.0.0"
    new_version = "1.1.0"
    tag = "v1.1.0"
    branch = "main"
    quiet = False
    releasable_name = None
    member_package_paths = None
    monorepo_project_path = None
    monorepo_name = None
    changes_dir = None
    hook_generated = ()
    pre_existing_dirty = None
    flags: dict = {}


def _built_plan(tmp_path):
    """A plan from the real builder, over a real (if minimal) npm project.

    ``tmp_path`` is not a git repo, so every builder read answers None -- which
    is the builder's declared "assume the work is owed" case, and therefore the
    arrangement that produces the FULL plan rather than an idempotency-skipped
    one.
    """
    import json

    (tmp_path / "package.json").write_text(
        json.dumps({"name": "p", "version": "1.0.0"}), encoding="utf-8",
    )
    (tmp_path / ".rlsbl").mkdir()
    project_dir = str(tmp_path)
    return phase_a.build_phase_a_plan(phase_a.BuildInputs(
        state=_BuiltState(),
        ctx=type("C", (), {"config": {}, "project_root": project_dir})(),
        log=lambda _m: None,
        project_dir=project_dir, git_root=project_dir,
        monorepo_root=None, releasable_cfg_dir=None, rep_is_private=False,
        registry="npm", primary_path=project_dir,
        target_paths={"npm": project_dir}, secondary_targets={},
        state_path=str(tmp_path / ".rlsbl" / "in-progress.json"),
        completed=set(), pin_sha=None, baseline_dirty=set(),
        commit_msg="v1.1.0", lock_dir=".rlsbl",
    ))


class TestTheBuilderProducesTheDeclaredSeam:

    def test_the_builder_emits_exactly_one_producer(self, tmp_path):
        plan = _built_plan(tmp_path)
        assert plan.produced_names == [phase_a.CANDIDATE_SHA], (
            "build_phase_a_plan produced "
            f"{plan.produced_names}. Exactly one value crosses the seam, from "
            "exactly one step -- _retarget_candidate exists to keep it that way "
            "when the snapshot commit lands after the release commit."
        )

    def test_the_producer_is_the_last_commit_the_plan_makes(self, tmp_path):
        plan = _built_plan(tmp_path)
        producer = next(s for s in plan.steps if s.produces)
        assert producer.kind in (phase_a.COMMIT, phase_a.SNAPSHOT)
        assert producer.capture is not None, (
            "the producing step must declare the observe that resolves it; "
            "otherwise the executor has to invent the read"
        )
        assert producer.capture[0] == phase_a.CANDIDATE_SHA
        assert producer.capture[1][:2] == ["git", "rev-parse"]

    def test_every_consumer_the_builder_emits_declared_itself(self, tmp_path):
        """The builder's consumers are the ones the design names, in order."""
        plan = _built_plan(tmp_path)
        consumers = [s.kind for s in plan.consumers_of(phase_a.CANDIDATE_SHA)]
        assert consumers == [
            phase_a.RECORD_CANDIDATE,
            phase_a.GUARD_CANDIDATE_WINDOW,
            phase_a.PUSH_CANDIDATE,
        ], (
            f"the real builder threads candidate_sha to {consumers}. Four edges "
            "total: one producer, three declared consumers. A consumer the "
            "builder emits without a StepRef is invisible to consumers_of -- "
            "and to the preview."
        )

    def test_the_builder_threads_no_second_value(self, tmp_path):
        """Only candidate_sha crosses the seam, on the real builder's output."""
        plan = _built_plan(tmp_path)
        names = set()
        for step in plan.steps:
            names |= phase_a._refs_in(step.payload)
        assert names == {phase_a.CANDIDATE_SHA}, (
            f"the plan references threaded values {sorted(names)}. A second "
            "value crossing the seam needs its own producer, its own declared "
            "capture, and its own line in the module docstring."
        )

    def test_the_built_plan_renders_its_thread_in_the_table(self, tmp_path):
        table = phase_a.render_plan_table(_built_plan(tmp_path))
        assert "-> candidate_sha" in table
        assert "<candidate_sha>:refs/heads/main" in table, (
            "the push row must show the refspec it would push, with the "
            "unresolved thread named -- that is what makes the preview honest "
            "about waiting on a commit that does not exist yet"
        )


# ---------------------------------------------------------------------------
# 4. A preview cannot push, by construction
# ---------------------------------------------------------------------------


class TestPreviewCannotPush:

    def test_no_observe_prefix_would_let_a_git_push_execute(self):
        """`git push` must never match the observe allowlist.

        An observe really runs under ``--dry-run``. A bare ``["git"]`` prefix
        -- or any prefix ``git push`` starts with -- would turn the release's
        candidate push into a real push during a preview. strictcli separately
        bans single-token prefixes; this pins the rlsbl-side consequence.
        """
        from rlsbl import app

        for prefix in app._proc_observe_allowlist:
            assert len(prefix) >= 2, (
                f"single-token observe prefix {list(prefix)!r}: it would make "
                "EVERY subcommand of that binary execute under --dry-run"
            )
            push = ("git", "push", "--no-verify", "origin", "HEAD:refs/heads/main")
            assert push[:len(prefix)] != tuple(prefix), (
                f"observe allowlist prefix {list(prefix)!r} matches `git push`: "
                "a preview would push for real"
            )

    def test_the_push_step_goes_through_the_effects_chokepoint(self):
        """The push is issued as an effect, so preview mode records it."""
        source = inspect.getsource(phase_a._Executor._do_push_candidate)
        assert "effects.run(" in source, (
            "the candidate push must be issued on the effects chokepoint; a "
            "direct subprocess would execute under --dry-run"
        )

    def test_the_chokepoint_exemption_list_does_not_cover_phase_a(self):
        """phase_a.py is not exempt from the chokepoint scan."""
        chokepoint = Path(__file__).with_name("test_effects_chokepoint.py")
        text = chokepoint.read_text()
        assert "phase_a" not in text, (
            "phase_a.py appears in the chokepoint test -- if it was added to "
            "the exemption list, the executor can bypass effects entirely"
        )


# ---------------------------------------------------------------------------
# 5. Rollback is an executor concern, never a plan step
# ---------------------------------------------------------------------------


class TestRollbackIsNotAPlanStep:

    def test_no_step_kind_undoes_anything(self):
        kinds = {
            v for k, v in vars(phase_a).items()
            if k.isupper() and isinstance(v, str) and not k.startswith("_")
        }
        forbidden = [
            k for k in kinds
            if any(word in k for word in ("rollback", "revert", "reset", "undo"))
        ]
        assert not forbidden, (
            f"Phase A declares undo steps {forbidden}. Rollback belongs to the "
            "executor's caller -- reset to the pre-release pin plus orphan "
            "cleanup -- so that a failure at any step unwinds the same way, "
            "and so a preview (which executes nothing) needs none."
        )

    def test_the_executor_never_resets(self):
        source = inspect.getsource(phase_a._Executor)
        assert "reset --hard" not in source
        assert '"reset"' not in source
        assert "tag -d" not in source


# ---------------------------------------------------------------------------
# 6. The preflight is OUTSIDE the plan
# ---------------------------------------------------------------------------


class TestPreflightIsOutsideThePlan:

    def test_the_builder_does_not_schedule_preflight_work(self):
        """Hooks, selfdoc and the schema dump are not Phase-A steps.

        The preflight keeps executing its observes and recording its mutations
        exactly as it always has, and its recorded effects render FIRST. Pulling
        it into the plan would put reads (its own checks) after the plan's
        writes, which is the arrangement the split exists to prevent.
        """
        source = inspect.getsource(phase_a.build_phase_a_plan)
        for helper in (
            "run_release_hook", "run_releasable_hooks",
            "_run_selfdoc_gen", "_run_selfdoc_check",
            "_run_strictcli_schema_dump", "_run_selfblog_post_generate",
            "run_checks",
        ):
            assert helper not in source, (
                f"the Phase-A plan builder calls {helper}(): the preflight "
                "stays outside the plan, executing its observes and recording "
                "its mutations as it always has, so that its effects render "
                "first and the plan's reads all happen before the plan's writes"
            )

    def test_no_hand_rolled_would_run_prints_remain_in_the_preflight(self):
        """The preflight's children are effects; recording is automatic.

        The resume preview's ``Would run: <remaining steps>`` line is a
        different thing and stays: it names STEPS, not an argv, and nothing
        records it. What must not come back is a hand-written restatement of a
        command the chokepoint already reports.
        """
        from rlsbl.commands.release import publish, validate

        for module in (validate, publish):
            source = inspect.getsource(module)
            for banned in (
                "Would run: selfdoc", "Would run: selfblog",
                "Would run: {' '.join(cmd)}",
            ):
                assert banned not in source, (
                    f"{module.__name__} hand-rolls {banned!r}. Its children go "
                    "through effects.run, so the framework's would-do log "
                    "already reports the real argv -- a second, hand-written "
                    "copy can only drift from it."
                )


# ---------------------------------------------------------------------------
# 7. The preview render is reachable on EVERY previewing path
# ---------------------------------------------------------------------------


def _mutating_fn():
    """The ``_run_release_mutating`` FunctionDef, parsed from source."""
    from rlsbl.commands.release import execute

    tree = ast.parse(inspect.getsource(execute))
    for node in ast.walk(tree):
        if (isinstance(node, ast.FunctionDef)
                and node.name == "_run_release_mutating"):
            return node
    raise AssertionError("_run_release_mutating not found")


# Statement kinds whose body only *sometimes* runs. An assignment under one of
# these is not a definition the preview render can count on.
_CONDITIONAL_STMTS = (ast.If, ast.For, ast.While, ast.ExceptHandler, ast.Try)


def _unconditionally_assigned(fn):
    """Names *fn* assigns on every path through its body.

    ``Try`` counts as conditional for its handlers and ``orelse``, but its
    ``body`` is entered unconditionally -- so the walk descends into
    ``Try.body`` and stops at everything else.
    """
    names = set()

    def walk(stmts):
        for stmt in stmts:
            if isinstance(stmt, ast.Try):
                walk(stmt.body)
                continue
            if isinstance(stmt, _CONDITIONAL_STMTS):
                continue
            for node in ast.walk(stmt):
                if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                    names.add(node.id)

    walk(fn.body)
    return names


class TestThePreviewRenderIsAlwaysReachable:

    def test_every_operand_of_the_preview_render_is_always_defined(self):
        """The seam's render must not depend on which Phase-A path was taken.

        ``_run_release_mutating`` has a branch that SKIPS Phase A entirely (a
        resume past the CI gate, or a batch member the orchestrator already
        gated). A preview still reaches the seam render on that path, so every
        local the render is handed must be defined before the branch -- or the
        preview dies with ``UnboundLocalError`` instead of printing.
        """
        fn = _mutating_fn()
        calls = [
            n for n in ast.walk(fn)
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
            and n.func.id == "print_release_preview"
        ]
        assert calls, "the seam no longer renders a preview -- pin is vacuous"
        always = _unconditionally_assigned(fn)
        always |= {a.arg for a in fn.args.args}
        for call in calls:
            operands = [
                a.id for a in list(call.args) + [k.value for k in call.keywords]
                if isinstance(a, ast.Name)
            ]
            assert operands, "the render takes no locals -- pin is vacuous"
            missing = [n for n in operands if n not in always]
            assert not missing, (
                f"print_release_preview is handed {missing}, which "
                "_run_release_mutating only assigns on SOME paths. The "
                "Phase-A-skipping branch (already CI-verified, or gated by the "
                "batch orchestrator) reaches this render too, and an operand "
                "assigned only in the other branch makes `release run "
                "--dry-run` raise UnboundLocalError there."
            )

    def test_the_render_states_plainly_when_phase_a_was_not_owed(self):
        """``plan is None`` is the declared shape for "Phase A issued nothing".

        An empty table would read as "Phase A does nothing"; the truth on that
        path is "Phase A was already done", and the preview has to say which.
        """
        lines = []
        print_release_preview(
            lines.append, None, _FixtureState(),
            registry="npm", files_to_commit=[],
        )
        text = "\n".join(lines)
        assert BOUNDARY_LINE in text, (
            "a preview with no Phase-A plan still owes the boundary and the "
            "declared Phase-B table"
        )
        assert "already" in text.lower(), (
            "the preview must say Phase A was already satisfied rather than "
            "rendering an empty plan table that reads as 'nothing to do'"
        )


# ---------------------------------------------------------------------------
# 8. Narration is live-only: a preview never speaks in the past tense
# ---------------------------------------------------------------------------


class _NarrationInputs:
    """The slice of BuildInputs the narrating step handlers read."""

    def __init__(self, project_dir, *, log):
        self.log = log
        self.project_dir = str(project_dir)
        self.git_root = str(project_dir)
        self.state_path = str(Path(project_dir) / "in-progress.json")
        self.completed = set()
        self.monorepo_root = None
        self.pin_sha = None
        self.state = type("S", (), {"quiet": False, "branch": "main"})()
        self.ctx = type("C", (), {
            "project_root": str(project_dir), "config": {},
        })()


# Words a preview must never emit: they claim work that was RECORDED, not done.
_PAST_TENSE_NARRATION = (
    "Tagged ", "Cleared ", "removed ", "Committed", "Pushed ", "Updated ",
    "Synced ", "Regenerated ",
)


def _narration_plan():
    """The two steps whose helpers narrate through a channel of their own.

    ``ensure_npm_keyword`` prints directly (its own ``quiet`` flag is the only
    lever), and ``clean_stale_artifacts`` logs through a callable the handler
    passes in. Both are past-tense, and both were reachable from a preview.
    """
    return phase_a.PhaseAPlan(
        steps=[
            phase_a.PlanStep(
                kind=phase_a.ENSURE_KEYWORD,
                release_step="VERSION_BUMPED",
                summary="add the 'rlsbl' keyword to package.json",
                payload={"kind": "npm", "path": ".",
                         "manifest_path": "package.json"},
            ),
            phase_a.PlanStep(
                kind=phase_a.CLEAN_ARTIFACTS,
                release_step="VERSION_BUMPED",
                summary="clear stale build artifacts from dist/",
                payload={"project_dir": ".", "target_paths": {}},
            ),
        ],
        files_to_commit=[],
    )


class TestPreviewNarrationIsLiveOnly:

    def _run_preview(self, tmp_path, capsys):
        """Issue the narrating steps in preview mode; return everything said."""
        import json

        (tmp_path / "package.json").write_text(
            json.dumps({"name": "p", "version": "1.0.0", "keywords": []}),
            encoding="utf-8",
        )
        dist = tmp_path / "dist"
        dist.mkdir()
        (dist / "p-0.9.0.tar.gz").write_bytes(b"stale")

        said = []
        plan = _narration_plan()
        for step in plan.steps:
            step.payload["path" if step.kind == phase_a.ENSURE_KEYWORD
                         else "project_dir"] = str(tmp_path)
        phase_a.execute_phase_a_plan(
            plan, _NarrationInputs(tmp_path, log=said.append), preview=True,
        )
        captured = capsys.readouterr()
        return said + captured.out.splitlines() + captured.err.splitlines()

    def test_a_preview_narrates_nothing_in_the_past_tense(self, tmp_path, capsys):
        lines = self._run_preview(tmp_path, capsys)
        offenders = [
            line for line in lines
            if any(word in line for word in _PAST_TENSE_NARRATION)
        ]
        assert not offenders, (
            "the Phase-A executor narrated completed work during a PREVIEW: "
            f"{offenders}. Per-step progress logging is live-only -- a preview "
            "recorded these effects rather than performing them, and the plan "
            "table it prints instead says the same things in the "
            "past-conditional they belong in."
        )

    def test_the_same_steps_do_narrate_when_live(self, tmp_path, capsys):
        """The silencing is preview-scoped, not a deletion of the narration."""
        import json

        (tmp_path / "package.json").write_text(
            json.dumps({"name": "p", "version": "1.0.0", "keywords": []}),
            encoding="utf-8",
        )
        dist = tmp_path / "dist"
        dist.mkdir()
        (dist / "p-0.9.0.tar.gz").write_bytes(b"stale")

        said = []
        plan = _narration_plan()
        for step in plan.steps:
            step.payload["path" if step.kind == phase_a.ENSURE_KEYWORD
                         else "project_dir"] = str(tmp_path)
        phase_a.execute_phase_a_plan(
            plan, _NarrationInputs(tmp_path, log=said.append), preview=False,
        )
        lines = said + capsys.readouterr().out.splitlines()
        assert any("Tagged " in line for line in lines), (
            "a LIVE run must still report the keyword it really added"
        )
        assert any("Cleared " in line for line in lines), (
            "a LIVE run must still report the stale artifacts it really removed"
        )


@pytest.mark.parametrize("kind", sorted({
    v for k, v in vars(phase_a).items()
    if k.isupper() and isinstance(v, str) and not k.startswith("_")
    and k not in ("CANDIDATE_SHA", "SLOT")
}))
def test_every_step_kind_has_an_executor_handler(kind):
    """A plan step nothing can issue is a step that silently does nothing."""
    assert kind in phase_a._HANDLERS, (
        f"step kind {kind!r} has no handler: build_phase_a_plan could emit it "
        "and the executor would raise KeyError mid-release"
    )
