"""Tests for the snapshot-based unexpected-files check in _run_release_mutating.

The check guards against concurrent modifications during the version bump.
Files that were already dirty when the mutating phase began (from
generate_changelog, hooks, lint, --allow-dirty) must NOT trigger the abort.
Only genuinely new modifications (appearing after the baseline snapshot)
should cause the release to fail.

Uses real git repos (not mocked git) to exercise the actual dirty-tree
detection logic end-to-end.
"""

import json
import os
import subprocess
from unittest.mock import patch

import pytest

from pathlib import Path
from rlsbl.context import ProjectContext

from rlsbl.release_file import ReleaseConfig


def _rc(bump="patch", include=None, exclude=None):
    """Shorthand for creating a ReleaseConfig with sensible defaults."""
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_head(repo):
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _setup_releasable_npm_project(repo):
    """Create a git repo with a tagged v1.0.0 release and an unreleased commit
    covered by an unreleased.jsonl entry. Ready for `rlsbl release patch`.

    The JSONL changelog commit uses the ``Autogenerated: true`` trailer
    so it is automatically exempted from coverage checks.
    """
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "test@test.local")
    _git(repo, "config", "user.name", "Test")

    # Initial release: package.json @ 1.0.0
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )
    (repo / "CHANGELOG.md").write_text(
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"private": False}) + "\n"
    )
    _git(repo, "add", "package.json", "CHANGELOG.md", ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    # Make an unreleased feature commit
    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    # Cover it with a JSONL entry (autogenerated trailer exempts the
    # changelog commit itself from coverage)
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**Add feature.** New feature is now available.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(
        repo, "commit", "-q", "-m", "changelog: add feature entry",
        "--trailer", "Autogenerated: true",
    )


class TestReleaseUnexpectedFiles:
    """Tests for the snapshot-based unexpected-files guard."""

    def test_intermediate_stage_files_not_flagged(self, tmp_project):
        """Files dirtied by generate_changelog (e.g. per-version .md) or a
        pre-release hook should not trigger the 'unexpected modified files'
        abort. The baseline snapshot at the start of _run_release_mutating
        captures them, so they are excluded from the unexpected set.

        Simulate the scenario by writing extra dirty files AFTER changelog
        generation but BEFORE the version bump, using a pre-release hook
        that creates an extra file.
        """
        _setup_releasable_npm_project(tmp_project)

        # Install a pre-release hook that creates an extra file. The hook
        # runs before _run_release_mutating, so the file will be dirty when
        # the baseline snapshot is taken.
        hooks_dir = tmp_project / ".rlsbl" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        hook = hooks_dir / "pre-release.sh"
        hook.write_text(
            "#!/bin/bash\n"
            "echo 'hook-output' > hook_artifact.txt\n"
        )
        hook.chmod(0o755)
        _git(tmp_project, "add", ".rlsbl/hooks/pre-release.sh")
        _git(tmp_project, "commit", "-q", "-m", "add pre-release hook")

        # Cover the hook commit
        hook_sha = _git_head(tmp_project)
        changes_dir = tmp_project / ".rlsbl" / "changes"
        with open(changes_dir / "unreleased.jsonl", "a") as f:
            f.write(json.dumps({"commits": [hook_sha], "user_facing": False}) + "\n")
        _git(tmp_project, "add", ".rlsbl/changes/unreleased.jsonl")
        _git(
            tmp_project, "commit", "-q", "-m", "changelog: cover hook commit",
            "--trailer", "Autogenerated: true",
        )

        from rlsbl.commands.release import run_cmd
        from rlsbl.utils import run as real_run

        def fake_run(cmd, args=None, timeout=120, env=None):
            """Intercept gh and git-push calls; let everything else through."""
            if cmd == "gh":
                return ""
            if cmd == "git" and args and args[0] == "push":
                return ""
            return real_run(cmd, args=args, timeout=timeout, env=env)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
        ):
            # Should complete without aborting on "unexpected modified files"
            run_cmd(
                _rc(),
                {
                    "yes": True,
                    "quiet": True,
                },
            
                ctx=ProjectContext(project_root=Path("."), workspace_root=None, config={"private": False}),
)

        # Verify the release actually completed: the version was bumped
        pkg = json.loads((tmp_project / "package.json").read_text())
        assert pkg["version"] == "1.0.1", (
            f"expected version 1.0.1 after release, got {pkg['version']}"
        )

        # The hook artifact file should still exist (it was not cleaned up)
        assert (tmp_project / "hook_artifact.txt").exists(), (
            "hook_artifact.txt should exist after release"
        )

    def test_concurrent_modification_still_flagged(self, tmp_project):
        """A file that appears AFTER the baseline snapshot (i.e. during the
        version bump) should still trigger the 'unexpected modified files'
        abort. This tests that the guard catches genuinely concurrent changes.

        Inject a rogue file by monkey-patching the npm target's write_version
        to also create an unexpected file as a side effect.
        """
        _setup_releasable_npm_project(tmp_project)

        from rlsbl.commands.release import run_cmd
        from rlsbl.targets.npm import NpmTarget
        from rlsbl.utils import run as real_run

        original_write_version = NpmTarget.write_version

        def rogue_write_version(self, dir_path, version):
            """Write version normally, then create an unexpected file."""
            result = original_write_version(self, dir_path, version)
            # Simulate a concurrent process writing a rogue file
            rogue_path = os.path.join(dir_path, "rogue_concurrent.txt")
            with open(rogue_path, "w") as f:
                f.write("I should not be here\n")
            return result

        def fake_run(cmd, args=None, timeout=120, env=None):
            """Intercept gh and git-push calls; let everything else through."""
            if cmd == "gh":
                return ""
            if cmd == "git" and args and args[0] == "push":
                return ""
            return real_run(cmd, args=args, timeout=timeout, env=env)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch.object(NpmTarget, "write_version", rogue_write_version),
        ):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    _rc(),
                    {
                        "yes": True,
                        "quiet": True,
                    },
                
                    ctx=ProjectContext(project_root=Path("."), workspace_root=None, config={"private": False}),
)

        assert exc_info.value.code == 1, (
            "release should exit 1 when unexpected files are detected"
        )
