"""Exit-code regression pins for the four release abort classes.

Every one of these aborts was, at some point in this project's history, a
path that printed a warning and let ``rlsbl release run`` return 0 -- a
release that reports success while nothing (or the wrong thing) shipped.
Each is fixed; this table exists so no future refactor can quietly re-open
one of them.

The pinned invariant per row is the same: ``run_cmd`` must raise
``SystemExit`` with a NONZERO code, and stderr must carry the abort's own
remediation text (so the row cannot pass by exiting nonzero for an
unrelated reason).

Covered classes:

- unclean working tree            -> ``ReleaseValidationError``
- a previous release in progress  -> ``ReleaseValidationError``
- CI never ran on the candidate   -> ``ReleaseCIError``
- selfdoc check failed            -> ``HookError``
"""

import json
import subprocess
from contextlib import ExitStack
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.commands.release.release_state import (
    MUTATING_STEPS,
    get_state_path,
    save_release_state,
)
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------


def _git(repo, *args):
    subprocess.run(["git", *args], cwd=str(repo), check=True,
                   capture_output=True, text=True)


def _git_head(repo):
    return subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=str(repo),
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def _setup_npm_project(repo):
    """An npm project at v1.0.0 with one unreleased, changelog-covered commit."""
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"]}) + "\n"
    )
    _git(repo, "add", "package.json", "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")

    entry = {
        "commits": [_git_head(repo)],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(repo, "commit", "-q", "-m", "changelog: add feature entry",
         "--trailer", "Autogenerated: true")


def _fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
    """Neutralize gh and the network-touching git verbs; run everything else."""
    if cmd == "gh":
        return ""
    if cmd == "git" and args and args[0] in ("push", "fetch"):
        return ""
    if (cmd == "git" and args and args[:2] == ["rev-list", "--count"]
            and any("origin/" in a for a in args)):
        return "0"
    return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)


def _make_ctx(repo):
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config={"publish_mode": "ci", "pipelines": {}},
    )


def _base_patches(stack):
    """Patches every row needs: no real gh, no real push, no real remote."""
    stack.enter_context(
        patch("rlsbl.commands.release.check_gh_installed", return_value=True))
    stack.enter_context(
        patch("rlsbl.commands.release.check_gh_auth", return_value=True))
    stack.enter_context(
        patch("rlsbl.commands.release.remote_branch_exists", return_value=True))
    stack.enter_context(patch("rlsbl.commands.release.push_if_needed"))
    stack.enter_context(patch("rlsbl.commands.release.run_gh", return_value=""))
    stack.enter_context(
        patch("rlsbl.commands.release.run", side_effect=_fake_run))


# ---------------------------------------------------------------------------
# Per-class setups. Each returns nothing; it stages the abort condition on
# the repo and installs whatever patches that class needs into ``stack``.
# ---------------------------------------------------------------------------


def _stage_unclean_tree(repo, stack):
    # A tracked file modified after the last commit: validate_clean_tree
    # refuses without --allow-dirty.
    (repo / "feature.txt").write_text("uncommitted edit\n")


def _stage_release_in_progress(repo, stack):
    # A partial (not provably complete) state file: the run must refuse and
    # point at `rlsbl release resume`, never start a second release.
    save_release_state(get_state_path(str(repo)), {
        "new_version": "1.0.1",
        "tag": "v1.0.1",
        "branch": "main",
        "pre_release_sha": _git_head(repo),
        "bump_type": "patch",
        "registry": "npm",
        "completed_steps": list(MUTATING_STEPS)[:1],
        "failed_steps": {},
        "companion_tags": [],
        "monorepo_name": None,
        "releasable_name": None,
        "commit_msg": "v1.0.1",
        "description": "test release",
        "context": "",
        "include": ["npm"],
        "exclude": [],
        "preid": "",
        "blog": False,
    })


def _stage_ci_never_ran(repo, stack):
    # The candidate pushed, CI concluded green -- but this project's own job
    # never ran, so nothing was proven. Tagging here would burn a version
    # that can never publish.
    from rlsbl.ci_checks import ProjectCINotRunError

    def _never_ran(*args, **kwargs):
        raise ProjectCINotRunError(
            "no check run matched this project's publish filter"
        )

    stack.enter_context(
        patch("rlsbl.commands.release.wait_for_ci_green",
              side_effect=_never_ran))


def _stage_selfdoc_check_failure(repo, stack):
    (repo / "selfdoc.json").write_text(json.dumps({"docs_dir": "docs"}) + "\n")
    _git(repo, "add", "selfdoc.json")
    _git(repo, "commit", "-q", "-m", "add selfdoc config",
         "--trailer", "Autogenerated: true")

    real_subprocess_run = subprocess.run

    def fake_effects_run(cmd, *args, **kwargs):
        if (isinstance(cmd, (list, tuple)) and len(cmd) >= 2
                and cmd[0] == "selfdoc"):
            if cmd[1] == "check":
                raise subprocess.CalledProcessError(returncode=1, cmd=list(cmd))
            return subprocess.CompletedProcess(cmd, 0)
        return real_subprocess_run(cmd, *args, **kwargs)

    stack.enter_context(
        patch("rlsbl.commands.release.require_tool", return_value=True))
    stack.enter_context(patch("rlsbl.effects.run", side_effect=fake_effects_run))


# id -> (stage fn, expected stderr fragment)
ABORT_CLASSES = {
    "unclean_tree": (_stage_unclean_tree, "working tree is not clean"),
    "release_in_progress": (
        _stage_release_in_progress, "a previous release is in progress"),
    "ci_never_ran": (
        _stage_ci_never_ran, "CI never ran for this project"),
    "selfdoc_check": (_stage_selfdoc_check_failure, "selfdoc check failed"),
}


class TestReleaseAbortExitCodes:
    """Every abort class exits NONZERO and says why."""

    @pytest.mark.parametrize("abort_class", sorted(ABORT_CLASSES))
    def test_abort_exits_nonzero(self, mock_git_repo, capsys, abort_class):
        stage, expected_fragment = ABORT_CLASSES[abort_class]
        _setup_npm_project(mock_git_repo)

        with ExitStack() as stack:
            _base_patches(stack)
            stage(mock_git_repo, stack)
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    ReleaseConfig(bump="patch", include=["npm"], exclude=[],
                                  description="test release"),
                    {"quiet": True},
                    ctx=_make_ctx(mock_git_repo),
                )

        assert exc_info.value.code not in (0, None), (
            f"{abort_class}: an aborted release must exit nonzero, "
            f"got {exc_info.value.code!r}"
        )
        err = capsys.readouterr().err
        assert expected_fragment in err, (
            f"{abort_class}: stderr must name the abort; expected "
            f"{expected_fragment!r} in:\n{err}"
        )

    def test_every_abort_class_is_covered(self):
        """The table is the spec: adding an abort class without a row here
        is how these regressions came back last time."""
        assert set(ABORT_CLASSES) == {
            "unclean_tree",
            "release_in_progress",
            "ci_never_ran",
            "selfdoc_check",
        }
