"""Tests for the first-release destroyed-tag guard.

``compute_release_version`` treats a missing current-version tag as a first
release. But a tag that once existed and was later destroyed (e.g. by an
interrupted or undone release) is indistinguishable from "never tagged" by
that check alone. When a finalized, immutable ``<version>.jsonl`` for the
current version exists, the version was demonstrably released before -- so the
release must abort PRE-MUTATION with a diagnosis and recovery options, rather
than run the whole pipeline and crash at finalization (triggering a rollback).

Covers standalone mode end-to-end with the real-git harness (asserting no
commit is created and the tree stays clean) and the releasable-mode changes-dir
resolution unit-wise. The negative case -- a genuinely new project with no
finalized version file -- must still take the first-release path.
"""

import json
import os

import pytest

from githarness import init_repo, commit_file, git
from unittest.mock import MagicMock, patch

from rlsbl.commands.release.validate import (
    ReleaseValidationError,
    compute_release_version,
    _abort_on_destroyed_tag,
)

TAG_EXISTS_FN = "rlsbl.commands.release.tag_exists_locally"


def _mock_target(version):
    target = MagicMock()
    target.read_version.return_value = version
    target.tag_format.side_effect = lambda v: f"v{v}"
    return target


def _write_finalized_jsonl(changes_dir, version):
    """Write a finalized (chmod 444) per-version JSONL file."""
    changes_dir.mkdir(parents=True, exist_ok=True)
    jsonl = changes_dir / f"{version}.jsonl"
    jsonl.write_text(
        json.dumps(
            {
                "commits": ["deadbeef"],
                "user_facing": True,
                "description": "**Initial.** First version.",
                "type": "feature",
            }
        )
        + "\n"
    )
    os.chmod(jsonl, 0o444)
    return jsonl


class TestDestroyedTagStandalone:
    def test_destroyed_tag_aborts_pre_mutation(self, tmp_path):
        """Version files at X.Y.Z + finalized JSONL + no tag => hard error
        BEFORE any commit, with the tag and both recovery options named."""
        repo = tmp_path / "repo"
        init_repo(repo)
        commit_file(
            repo,
            "package.json",
            json.dumps({"name": "pkg", "version": "1.2.3"}, indent=2) + "\n",
            "initial",
        )

        changes = repo / ".rlsbl" / "changes"
        _write_finalized_jsonl(changes, "1.2.3")
        (changes / "unreleased.jsonl").write_text("")
        (repo / "CHANGELOG.md").write_text(
            "<!-- Generated by rlsbl -->\n\n# Changelog\n\n## 1.2.3\n\nInitial.\n"
        )
        # Commit the released state so the working tree is clean afterwards.
        git(repo, "add", ".rlsbl/changes/1.2.3.jsonl",
            ".rlsbl/changes/unreleased.jsonl", "CHANGELOG.md")
        git(repo, "commit", "-q", "-m", "released state")

        head_before = git(repo, "rev-parse", "HEAD")
        assert git(repo, "status", "--porcelain") == ""

        target = _mock_target("1.2.3")
        with patch(TAG_EXISTS_FN, return_value=False):
            with pytest.raises(ReleaseValidationError) as exc:
                compute_release_version(
                    target, str(repo), None, None, None, lambda _m: None,
                    project_dir=str(repo),
                )

        msg = str(exc.value)
        assert "1.2.3" in msg
        assert "v1.2.3" in msg  # the tag is named
        # Recovery option 1: restore the tag.
        assert "restore" in msg.lower()
        assert f"git tag v1.2.3" in msg
        # Recovery option 2: move the version forward.
        assert "forward" in msg.lower()

        # Pre-mutation guarantee: nothing committed, tree still clean.
        assert git(repo, "rev-parse", "HEAD") == head_before
        assert git(repo, "status", "--porcelain") == ""

    def test_falls_back_to_primary_path_when_project_dir_omitted(self, tmp_path):
        """With project_dir omitted, the guard resolves the changes dir from
        primary_path (the standalone project root)."""
        repo = tmp_path / "repo"
        init_repo(repo)
        commit_file(
            repo,
            "package.json",
            json.dumps({"name": "pkg", "version": "2.0.0"}, indent=2) + "\n",
            "initial",
        )
        _write_finalized_jsonl(repo / ".rlsbl" / "changes", "2.0.0")

        target = _mock_target("2.0.0")
        with patch(TAG_EXISTS_FN, return_value=False):
            with pytest.raises(ReleaseValidationError) as exc:
                # No project_dir kwarg -> falls back to primary_path (str(repo)).
                compute_release_version(
                    target, str(repo), None, None, None, lambda _m: None,
                )
        assert "2.0.0" in str(exc.value)

    def test_new_project_still_takes_first_release_path(self, tmp_path):
        """A genuinely new project (changes dir exists, no finalized version
        file) still first-releases current_version as-is."""
        repo = tmp_path / "repo"
        init_repo(repo)
        commit_file(
            repo,
            "package.json",
            json.dumps({"name": "pkg", "version": "1.0.0"}, indent=2) + "\n",
            "initial",
        )
        changes = repo / ".rlsbl" / "changes"
        changes.mkdir(parents=True)
        (changes / "unreleased.jsonl").write_text("")

        target = _mock_target("1.0.0")
        with patch(TAG_EXISTS_FN, return_value=False):
            current, new, bump, tag = compute_release_version(
                target, str(repo), None, None, None, lambda _m: None,
                project_dir=str(repo),
            )
        assert current == "1.0.0"
        assert new == "1.0.0"
        assert bump is None
        assert tag == "v1.0.0"

    def test_no_changes_dir_is_noop(self, tmp_path):
        """No .rlsbl/changes/ at all -> guard is a no-op, first release proceeds."""
        repo = tmp_path / "repo"
        init_repo(repo)
        commit_file(
            repo,
            "package.json",
            json.dumps({"name": "pkg", "version": "0.1.0"}, indent=2) + "\n",
            "initial",
        )

        target = _mock_target("0.1.0")
        with patch(TAG_EXISTS_FN, return_value=False):
            current, new, bump, tag = compute_release_version(
                target, str(repo), None, None, None, lambda _m: None,
                project_dir=str(repo),
            )
        assert (current, new, bump, tag) == ("0.1.0", "0.1.0", None, "v0.1.0")


class TestDestroyedTagGuardUnit:
    def test_standalone_finalized_file_aborts(self, tmp_path):
        changes = tmp_path / ".rlsbl" / "changes"
        _write_finalized_jsonl(changes, "3.4.5")
        with pytest.raises(ReleaseValidationError) as exc:
            _abort_on_destroyed_tag(str(tmp_path), "3.4.5", "v3.4.5")
        msg = str(exc.value)
        assert "v3.4.5" in msg
        assert "restore" in msg.lower()
        assert "forward" in msg.lower()

    def test_standalone_no_finalized_file_passes(self, tmp_path):
        changes = tmp_path / ".rlsbl" / "changes"
        changes.mkdir(parents=True)
        (changes / "unreleased.jsonl").write_text("")
        # Must not raise.
        _abort_on_destroyed_tag(str(tmp_path), "3.4.5", "v3.4.5")

    def test_releasable_finalized_file_aborts(self, tmp_path):
        """Releasable mode resolves the changes dir under
        .rlsbl-monorepo/releasables/<name>/changes/."""
        ws = tmp_path / "monorepo"
        changes = ws / ".rlsbl-monorepo" / "releasables" / "www" / "changes"
        _write_finalized_jsonl(changes, "2.0.0")

        with pytest.raises(ReleaseValidationError) as exc:
            _abort_on_destroyed_tag(
                str(ws / "packages" / "www"), "2.0.0", "www@v2.0.0",
                releasable_name="www", workspace_root=str(ws),
            )
        msg = str(exc.value)
        assert "www@v2.0.0" in msg
        assert "2.0.0" in msg

    def test_releasable_no_finalized_file_passes(self, tmp_path):
        ws = tmp_path / "monorepo"
        changes = ws / ".rlsbl-monorepo" / "releasables" / "www" / "changes"
        changes.mkdir(parents=True)
        (changes / "unreleased.jsonl").write_text("")
        _abort_on_destroyed_tag(
            str(ws / "packages" / "www"), "2.0.0", "www@v2.0.0",
            releasable_name="www", workspace_root=str(ws),
        )
