"""Tests for releasable-aware `rlsbl release undo`.

In explicit releasable mode the finalized JSONL and the canonical
CHANGELOG.md live at the releasable level, so undo must unfinalize and
regenerate there (never at the representative member's .rlsbl/changes/).
Undo must also clear any preserved in-progress release state after a
successful rollback -- otherwise the stale state hard-blocks the next
`rlsbl release run`.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.commands.release.release_state import (
    get_state_path,
    save_release_state,
)
from rlsbl.commands.undo import run_cmd as undo_run_cmd
from rlsbl.context import ProjectContext, create_context
from rlsbl.utils import run as real_run
from rlsbl.workspace import (
    Releasable,
    get_releasable_changes_dir,
    get_releasable_dir,
    save_workspace,
    write_releasable_version,
)


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


_ENTRY = {
    "commits": [],
    "user_facing": True,
    "description": "**New feature.** A shiny new thing.",
    "type": "feature",
}


def _fake_run_factory():
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


def _undo_patches():
    def failing_run_gh(args, **kwargs):
        raise subprocess.CalledProcessError(1, "gh")

    return [
        patch("rlsbl.commands.undo.check_gh_installed", return_value=True),
        patch("rlsbl.commands.undo.check_gh_auth", return_value=True),
        patch("rlsbl.commands.undo.run_gh", side_effect=failing_run_gh),
        patch("rlsbl.commands.undo.run", side_effect=_fake_run_factory()),
        patch("rlsbl.commands.undo.push_if_needed"),
    ]


def _run_undo(ctx):
    patches = _undo_patches()
    for p in patches:
        p.start()
    try:
        undo_run_cmd(None, [], {"yes": True}, ctx=ctx)
    finally:
        for p in patches:
            p.stop()


def _setup_released_releasable_workspace(root):
    """Releasable workspace 'alpha' in the state a completed release leaves:
    a version-bump commit, a changelog-finalize commit, and the release tag.

    Returns the member (representative) directory.
    """
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "user.email", "test@test.local")
    _git(root, "config", "user.name", "Test")

    core = root / "packages" / "core"
    core.mkdir(parents=True)
    (core / "package.json").write_text(
        json.dumps({"name": "core", "version": "1.0.0"}, indent=2) + "\n"
    )
    (core / ".rlsbl").mkdir()
    (core / ".rlsbl" / "config.json").write_text(
        json.dumps({"private": False, "targets": ["npm"], "pipelines": {}}) + "\n"
    )

    # in-progress.json is gitignored in scaffolded projects
    (root / ".gitignore").write_text(
        ".rlsbl-monorepo/releasables/*/releases/in-progress.json\n"
    )

    save_workspace(
        str(root),
        [{"path": "packages/core", "name": "core", "releasable": "alpha"}],
        releasables=[Releasable(name="alpha")],
    )
    write_releasable_version(str(root), "alpha", "1.0.0")
    rel_dir = get_releasable_dir(str(root), "alpha")
    changes_dir = get_releasable_changes_dir(str(root), "alpha")
    os.makedirs(changes_dir, exist_ok=True)
    (Path(changes_dir) / "unreleased.jsonl").write_text(json.dumps(_ENTRY) + "\n")
    (Path(rel_dir) / "config.json").write_text("{}\n")
    (Path(rel_dir) / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ — do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- No user-facing changes.\n"
    )
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "initial")
    _git(root, "tag", "alpha@v1.0.0")

    # Version-bump commit (as the release flow would create it)
    pkg = json.loads((core / "package.json").read_text())
    pkg["version"] = "1.0.1"
    (core / "package.json").write_text(json.dumps(pkg, indent=2) + "\n")
    write_releasable_version(str(root), "alpha", "1.0.1")
    (Path(rel_dir) / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ — do not edit -->\n\n"
        "# Changelog\n\n## 1.0.1\n\n### Features\n\n"
        "- **New feature.** A shiny new thing.\n\n"
        "## 1.0.0\n\n- No user-facing changes.\n"
    )
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "alpha: release v1.0.1")

    # Changelog-finalize commit
    unreleased = Path(changes_dir) / "unreleased.jsonl"
    finalized = Path(changes_dir) / "1.0.1.jsonl"
    os.rename(unreleased, finalized)
    unreleased.write_text("")
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "chore: finalize changelog for 1.0.1")

    _git(root, "tag", "alpha@v1.0.1")
    return core


class TestUndoReleasablePaths:

    def test_undo_restores_releasable_changelog_state(self, tmp_project, monkeypatch):
        core = _setup_released_releasable_workspace(tmp_project)
        monkeypatch.chdir(core)
        ctx = create_context(Path(str(core)), workspace_root=Path(str(tmp_project)))

        _run_undo(ctx)

        changes_dir = Path(get_releasable_changes_dir(str(tmp_project), "alpha"))
        assert not (changes_dir / "1.0.1.jsonl").exists(), (
            "undo must remove the finalized JSONL at the RELEASABLE level"
        )
        unreleased = (changes_dir / "unreleased.jsonl").read_text()
        assert "A shiny new thing." in unreleased, (
            "undo must restore the unreleased entries at the RELEASABLE level"
        )

        # Canonical + combined root CHANGELOG.md regenerated with the
        # restored unreleased entries
        rel_dir = get_releasable_dir(str(tmp_project), "alpha")
        canonical = (Path(rel_dir) / "CHANGELOG.md").read_text()
        assert "## Unreleased" in canonical
        root_combined = (Path(str(tmp_project)) / "CHANGELOG.md").read_text()
        assert "# alpha" in root_combined
        assert "## Unreleased" in root_combined

        # The member's .rlsbl/changes/ must never be created by undo
        assert not (core / ".rlsbl" / "changes").exists()

    def test_undo_clears_releasable_in_progress_state(self, tmp_project, monkeypatch):
        """After undoing a release whose fatal failure preserved
        in-progress.json, the state file is cleared so the next
        `rlsbl release run` is not hard-blocked."""
        core = _setup_released_releasable_workspace(tmp_project)
        rel_dir = get_releasable_dir(str(tmp_project), "alpha")
        state_path = get_state_path(str(core), releasable_dir=rel_dir)
        save_release_state(state_path, {
            "new_version": "1.0.1",
            "tag": "alpha@v1.0.1",
            "branch": "main",
            "completed_steps": ["VERSION_BUMPED", "COMMITTED", "TAGGED", "PUSHED"],
            "failed_steps": {"GITHUB_RELEASE": "boom"},
            "releasable_name": "alpha",
        })

        monkeypatch.chdir(core)
        ctx = create_context(Path(str(core)), workspace_root=Path(str(tmp_project)))
        _run_undo(ctx)

        assert not os.path.exists(state_path), (
            "undo must clear the in-progress release state after a "
            "successful rollback"
        )


class TestUndoPrModeClearsState:
    """PR-mode undo (open PR: close + delete branch + restore files) must
    also clear any preserved in-progress release state after a successful
    rollback -- mirroring the imperative-mode clear."""

    def test_pr_undo_clears_releasable_in_progress_state(
        self, tmp_project, monkeypatch,
    ):
        core = _setup_released_releasable_workspace(tmp_project)
        rel_dir = get_releasable_dir(str(tmp_project), "alpha")
        state_path = get_state_path(str(core), releasable_dir=rel_dir)
        save_release_state(state_path, {
            "new_version": "1.0.1",
            "tag": "alpha@v1.0.1",
            "branch": "main",
            "completed_steps": ["VERSION_BUMPED", "COMMITTED"],
            "releasable_name": "alpha",
            "release_mode": "pr",
        })

        # PR-mode config for the member (committed: undo requires a clean tree)
        (core / ".rlsbl" / "config.json").write_text(
            json.dumps({
                "private": False, "targets": ["npm"], "pipelines": {},
                "release": {"mode": "pr"},
            }) + "\n"
        )
        _git(tmp_project, "add", "packages/core/.rlsbl/config.json")
        _git(tmp_project, "commit", "-q", "-m", "switch to pr release mode")

        monkeypatch.chdir(core)
        ctx = create_context(Path(str(core)), workspace_root=Path(str(tmp_project)))

        patches = _undo_patches() + [
            patch("rlsbl.commands.undo._detect_pr_state", return_value="open"),
        ]
        for p in patches:
            p.start()
        try:
            undo_run_cmd(None, [], {"yes": True}, ctx=ctx)
        finally:
            for p in patches:
                p.stop()

        assert not os.path.exists(state_path), (
            "PR-mode undo must clear the in-progress release state after a "
            "successful rollback"
        )


class TestUndoClearsStandaloneState:

    def test_undo_clears_standalone_in_progress_state(self, tmp_project, monkeypatch):
        repo = tmp_project
        _git(repo, "init", "-q", "-b", "main")
        _git(repo, "config", "user.email", "test@test.local")
        _git(repo, "config", "user.name", "Test")
        (repo / "package.json").write_text(
            json.dumps({"name": "pkg", "version": "1.0.0"}, indent=2) + "\n"
        )
        (repo / ".gitignore").write_text(".rlsbl/releases/in-progress.json\n")
        changes_dir = repo / ".rlsbl" / "changes"
        changes_dir.mkdir(parents=True)
        (changes_dir / "unreleased.jsonl").write_text(json.dumps(_ENTRY) + "\n")
        (repo / ".rlsbl" / "config.json").write_text(
            json.dumps({"private": False, "targets": ["npm"]}) + "\n"
        )
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "initial")
        _git(repo, "tag", "v1.0.0")

        # Simulated release commit + tag
        pkg = json.loads((repo / "package.json").read_text())
        pkg["version"] = "1.0.1"
        (repo / "package.json").write_text(json.dumps(pkg, indent=2) + "\n")
        _git(repo, "add", "-A")
        _git(repo, "commit", "-q", "-m", "v1.0.1")
        _git(repo, "tag", "v1.0.1")

        state_path = get_state_path(str(repo))
        save_release_state(state_path, {
            "new_version": "1.0.1",
            "tag": "v1.0.1",
            "branch": "main",
            "completed_steps": ["VERSION_BUMPED", "COMMITTED", "TAGGED", "PUSHED"],
            "failed_steps": {"GITHUB_RELEASE": "boom"},
        })

        ctx = ProjectContext(
            project_root=Path(str(repo)),
            workspace_root=None,
            config={"private": False},
        )
        _run_undo(ctx)

        assert not os.path.exists(state_path), (
            "undo must clear .rlsbl/releases/in-progress.json after a "
            "successful rollback"
        )
