"""Tests for rlsbl.utils.commit_files."""

import subprocess
from unittest.mock import patch, call

import pytest

from rlsbl.utils import commit_files


class TestCommitFilesSafegit:
    """Tests for the safegit path."""

    @patch("rlsbl.utils.run")
    @patch("shutil.which", return_value="/usr/bin/safegit")
    def test_calls_safegit_with_correct_args(self, mock_which, mock_run):
        result = commit_files("test message", ["file1.py", "file2.py"])
        assert result is True
        mock_run.assert_called_once_with(
            "safegit", ["commit", "--yes", "--trailer", "Autogenerated: true", "-m", "test message", "--", "file1.py", "file2.py"], cwd=None,
        )


class TestCommitFilesGitFallback:
    """Tests for the git fallback path."""

    @patch("rlsbl.utils.run")
    @patch("shutil.which", return_value=None)
    def test_calls_git_add_then_commit(self, mock_which, mock_run):
        result = commit_files("test message", ["a.txt", "b.txt"])
        assert result is True
        assert mock_run.call_count == 2
        mock_run.assert_any_call("git", ["add", "a.txt", "b.txt"], cwd=None)
        mock_run.assert_any_call("git", ["commit", "--trailer", "Autogenerated: true", "-m", "test message"], cwd=None)


class TestCommitFilesAllowFailure:
    """Tests for error handling with allow_failure."""

    @patch("rlsbl.utils.run", side_effect=subprocess.CalledProcessError(1, "git"))
    @patch("shutil.which", return_value=None)
    def test_returns_false_on_error(self, mock_which, mock_run, capsys):
        result = commit_files("msg", ["f.txt"], allow_failure=True)
        assert result is False
        captured = capsys.readouterr()
        assert "Warning: commit failed" in captured.err

    @patch("rlsbl.utils.run", side_effect=FileNotFoundError("git not found"))
    @patch("shutil.which", return_value=None)
    def test_returns_false_on_file_not_found(self, mock_which, mock_run, capsys):
        result = commit_files("msg", ["f.txt"], allow_failure=True)
        assert result is False
        captured = capsys.readouterr()
        assert "Warning: commit failed" in captured.err


class TestCommitFilesExceptionPropagation:
    """Tests for error propagation when allow_failure is False."""

    @patch("rlsbl.utils.run", side_effect=subprocess.CalledProcessError(1, "git"))
    @patch("shutil.which", return_value=None)
    def test_raises_on_error(self, mock_which, mock_run):
        with pytest.raises(subprocess.CalledProcessError):
            commit_files("msg", ["f.txt"], allow_failure=False)

    @patch("rlsbl.utils.run", side_effect=FileNotFoundError("git not found"))
    @patch("shutil.which", return_value=None)
    def test_raises_file_not_found(self, mock_which, mock_run):
        with pytest.raises(FileNotFoundError):
            commit_files("msg", ["f.txt"], allow_failure=False)


class TestGitToplevelGuard:
    """assert_git_toplevel / expected_root guard: refuse committing into the
    wrong repository when the commit cwd walks up into an enclosing repo.

    Regression: a fixture dir created inside the real repo (TMPDIR-inside-repo)
    is not its own git repo, so ``git`` walks UP to the real repo and commits
    junk there. The expected_root check makes that a hard error.
    """

    def _init_repo(self, path):
        subprocess.run(["git", "init", "-q", "-b", "main"], cwd=str(path), check=True)
        subprocess.run(["git", "config", "user.email", "t@t.local"], cwd=str(path), check=True)
        subprocess.run(["git", "config", "user.name", "T"], cwd=str(path), check=True)

    def test_mismatch_is_hard_error(self, tmp_path):
        from rlsbl.utils import assert_git_toplevel
        from rlsbl.errors import GitError

        self._init_repo(tmp_path)
        sub = tmp_path / "sub"  # NOT its own git repo -> git walks up to tmp_path
        sub.mkdir()

        with pytest.raises(GitError, match="not the expected project root"):
            assert_git_toplevel(str(sub), str(sub))

    def test_match_passes(self, tmp_path):
        from rlsbl.utils import assert_git_toplevel

        self._init_repo(tmp_path)
        # toplevel resolved from tmp_path IS tmp_path -> no error.
        assert_git_toplevel(str(tmp_path), str(tmp_path))

    def test_commit_scaffold_refuses_wrong_repo(self, tmp_path):
        """commit_scaffold_file with a mis-anchored expected_root refuses,
        rather than committing into the enclosing repo."""
        from rlsbl.utils import commit_scaffold_file
        from rlsbl.errors import GitError

        self._init_repo(tmp_path)
        sub = tmp_path / "member"
        sub.mkdir()
        f = sub / "file.txt"
        f.write_text("x\n")

        # cwd=sub walks up to tmp_path; expected_root=sub -> mismatch -> refuse.
        with pytest.raises(GitError, match="refusing to commit"):
            commit_scaffold_file("scaffold", [str(f)], cwd=str(sub), expected_root=str(sub))

    def test_commit_files_expected_root_match_commits(self, tmp_path):
        """When expected_root matches the toplevel, the commit proceeds."""
        from rlsbl.utils import commit_files

        self._init_repo(tmp_path)
        f = tmp_path / "file.txt"
        f.write_text("x\n")

        ok = commit_files(
            "msg", ["file.txt"], cwd=str(tmp_path), expected_root=str(tmp_path),
            autogenerated=False,
        )
        assert ok is True
        log = subprocess.run(
            ["git", "log", "--oneline"], cwd=str(tmp_path),
            capture_output=True, text=True,
        )
        assert "msg" in log.stdout
