"""Tests for releasable-aware JSONL coverage in ``rlsbl status``.

A releasable member's changelog entries live in the releasable's state
directory (``.rlsbl-monorepo/releasables/<name>/changes/``), not in the member
package. ``status`` resolved ``.rlsbl/changes/`` relative to the member, so it
reported ``JSONL: not set up`` for every releasable member. Scoping is
releasable-wide too: a commit touching ANY member is the releasable's commit.
"""

import json
import os
import subprocess

from conftest import archive_release, make_ctx, with_root_member

from rlsbl.commands.status import run_cmd
from rlsbl.workspace import (
    Releasable,
    get_releasable_changes_dir,
    save_workspace,
    write_releasable_version,
)


def _make_npm_project(base_path, subdir, version="1.0.0"):
    proj_dir = os.path.join(str(base_path), subdir)
    os.makedirs(proj_dir, exist_ok=True)
    with open(os.path.join(proj_dir, "package.json"), "w") as f:
        json.dump({"name": subdir, "version": version}, f)
    return proj_dir


def _commit_file(repo, name, content="x\n", message="change"):
    fp = os.path.join(str(repo), name)
    os.makedirs(os.path.dirname(fp), exist_ok=True)
    with open(fp, "w") as f:
        f.write(content)
    subprocess.run(["git", "add", name], cwd=str(repo), check=True)
    subprocess.run(["git", "commit", "-q", "-m", message], cwd=str(repo), check=True)
    return subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=str(repo),
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def _commit_autogenerated(repo, name, message="chore: regenerate"):
    """Commit a file carrying the ``Autogenerated: true`` trailer."""
    fp = os.path.join(str(repo), name)
    os.makedirs(os.path.dirname(fp), exist_ok=True)
    with open(fp, "a") as f:
        f.write("x\n")
    subprocess.run(["git", "add", name], cwd=str(repo), check=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", f"{message}\n\nAutogenerated: true"],
        cwd=str(repo), check=True,
    )


def _workspace_with_releasable(repo, members=("pkg-a", "pkg-b"), name="alpha",
                               version="1.0.0"):
    """Explicit-mode workspace: all *members* belong to releasable *name*."""
    for member in members:
        _make_npm_project(repo, member, version=version)
    save_workspace(
        str(repo),
        with_root_member([{"path": m, "name": m, "releasable": name} for m in members]),
        releasables=[Releasable(name=name)],
    )
    write_releasable_version(str(repo), name, version)
    changes_dir = get_releasable_changes_dir(str(repo), name)
    os.makedirs(changes_dir, exist_ok=True)
    with open(os.path.join(changes_dir, "unreleased.jsonl"), "w") as f:
        f.write("")
    subprocess.run(
        ["git", "add", ".rlsbl-monorepo", *members], cwd=str(repo), check=True,
    )
    subprocess.run(
        ["git", "commit", "-q", "-m", "workspace setup"], cwd=str(repo), check=True,
    )
    subprocess.run(["git", "tag", f"{name}@v{version}"], cwd=str(repo), check=True)
    # The releasable's RELEASE RECORD entry: coverage is measured from the archived
    # release, not from the tag.
    archive_release(
        os.path.join(os.path.dirname(changes_dir), "releases"), version,
        subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=str(repo),
            capture_output=True, text=True, check=True,
        ).stdout.strip(),
    )
    return changes_dir


def _write_entry(changes_dir, sha, description="Thing.", entry_type="feature"):
    with open(os.path.join(changes_dir, "unreleased.jsonl"), "a") as f:
        f.write(json.dumps({
            "commits": [sha], "user_facing": True,
            "description": description, "type": entry_type,
        }) + "\n")


def _jsonl_line(out):
    for line in out.splitlines():
        if line.startswith("JSONL:"):
            return line
    raise AssertionError(f"no JSONL line in status output:\n{out}")


class TestStatusReleasableCoverage:
    def test_member_reads_the_releasable_changes_dir(
        self, mock_git_repo, monkeypatch, capsys,
    ):
        changes_dir = _workspace_with_releasable(mock_git_repo)
        sha = _commit_file(mock_git_repo, "pkg-a/feature.js", message="feat: thing")
        _write_entry(changes_dir, sha)

        monkeypatch.chdir(str(mock_git_repo / "pkg-a"))
        capsys.readouterr()
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        line = _jsonl_line(capsys.readouterr().out)

        assert "not set up" not in line
        assert "1/1 commits covered" in line

    def test_uncovered_member_commit_is_reported(
        self, mock_git_repo, monkeypatch, capsys,
    ):
        _workspace_with_releasable(mock_git_repo)
        _commit_file(mock_git_repo, "pkg-a/feature.js", message="feat: thing")

        monkeypatch.chdir(str(mock_git_repo / "pkg-a"))
        capsys.readouterr()
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        line = _jsonl_line(capsys.readouterr().out)

        assert "0/1 commits covered" in line

    def test_scope_covers_every_member_of_the_releasable(
        self, mock_git_repo, monkeypatch, capsys,
    ):
        """A commit touching a sibling member is the releasable's commit too."""
        _workspace_with_releasable(mock_git_repo)
        _commit_file(mock_git_repo, "pkg-a/a.js", message="feat: a")
        _commit_file(mock_git_repo, "pkg-b/b.js", message="feat: b")

        monkeypatch.chdir(str(mock_git_repo / "pkg-a"))
        capsys.readouterr()
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        line = _jsonl_line(capsys.readouterr().out)

        assert "0/2 commits covered" in line

    def test_exemptions_are_scoped_to_the_releasable(
        self, mock_git_repo, monkeypatch, capsys,
    ):
        """Exemptions are applied AFTER scoping, so out-of-scope churn never
        inflates this releasable's exempted count."""
        _workspace_with_releasable(mock_git_repo)
        _commit_file(mock_git_repo, "pkg-a/a.js", message="feat: a")
        # In scope and exempt: an autogenerated commit inside a member.
        _commit_autogenerated(mock_git_repo, "pkg-a/generated.js")
        # Out of scope entirely: belongs to no member of the releasable.
        _commit_file(
            mock_git_repo, "other/.rlsbl/changes/unreleased.jsonl",
            content='{"commits":["deadbee"],"user_facing":false}\n',
            message="changelog: other entry",
        )

        monkeypatch.chdir(str(mock_git_repo / "pkg-a"))
        capsys.readouterr()
        run_cmd("npm", [], {}, ctx=make_ctx("."))
        line = _jsonl_line(capsys.readouterr().out)

        assert "0/1 commits covered (1 exempted)" in line
