"""A release whose lockfile tool is missing stops before anything is pushed.

After the version bump the release re-locks each lockfile with the tool that
owns it (``uv lock``, ``npm install --package-lock-only``). A tool missing
from PATH used to be a warning, and the release went on without the re-lock and
shipped the lockfile stale. It is a refusal now, raised before anything is
pushed: it names the tool to install and the command that continues the
release, and a resumed release keeps its state.

Each test applies the fix the refusal names by putting a stand-in tool on PATH
and shows the release then goes on.
"""

import os
import shutil

import pytest

from githarness import git

from rlsbl.commands.release import execute

import test_devnode_editable_lock_refresh as devnode
from test_release_lockfile_sync_refusal import (
    ECOSYSTEMS,
    World,
    _project,
    _release,
    _stand_in,
)


def _hide_tools_outside(bin_dir, monkeypatch):
    """Answer PATH lookups as if only *bin_dir* held the lockfile tools.

    The machine running the suite may have real npm/uv installed; the refusal
    is about a tool the release cannot find, so every lockfile tool resolves
    only when a stand-in sits in *bin_dir*.
    """
    real_which = shutil.which
    tools = {spec[1] for spec in execute._LOCKFILE_SPECS}

    def which(name, *args, **kwargs):
        found = real_which(name, *args, **kwargs)
        if name in tools and (
            found is None or os.path.dirname(found) != str(bin_dir)
        ):
            return None
        return found

    monkeypatch.setattr(shutil, "which", which)


@pytest.fixture(params=sorted(ECOSYSTEMS))
def project(request, tmp_path, monkeypatch):
    eco = request.param
    world = World(tmp_path / "world")
    world.publish("sib@0.3.0")
    bin_dir = tmp_path / "bin"
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    _hide_tools_outside(bin_dir, monkeypatch)
    return _project(tmp_path, eco), eco, world, bin_dir


def _install_hint(eco):
    tool = ECOSYSTEMS[eco]["tool"]
    return f"Install {tool} (or put it on PATH)"


def test_a_missing_tool_refuses_and_installing_it_ships(project, monkeypatch):
    repo, eco, world, bin_dir = project
    pin = git(repo, "rev-parse", "refs/heads/main")
    origin = git(repo, "ls-remote", "origin")

    result = _release(repo, monkeypatch)
    assert result.exit_code == 1, result.stderr + result.stdout
    err = result.stderr
    tool = ECOSYSTEMS[eco]["tool"]
    lockfile = ECOSYSTEMS[eco]["lockfile"]
    assert f"`{tool}` is not on PATH" in err
    assert f"re-lock {lockfile}" in err
    assert _install_hint(eco) in err
    assert "re-run `rlsbl release run`" in err
    assert "Warning" not in err
    # Nothing pushed, tagged, committed or recorded.
    assert git(repo, "ls-remote", "origin") == origin
    assert git(repo, "tag", "-l", "v1.0.1") == ""
    assert git(repo, "rev-parse", "refs/heads/main") == pin
    assert git(repo, "status", "--porcelain") == ""
    assert not (repo / ".rlsbl" / "releases" / "in-progress.json").exists()

    _stand_in(bin_dir, world, eco)
    shipped = _release(repo, monkeypatch)
    assert shipped.exit_code == 0, shipped.stderr + shipped.stdout
    assert git(repo, "rev-parse", "v1.0.1^{commit}")
    # The stand-in's re-lock ran: the released lockfile records the bump.
    assert "1.0.1" in git(repo, "show", f"v1.0.1:{lockfile}")


def test_a_resume_with_the_tool_missing_keeps_the_state_and_names_the_resume(
    project, tmp_path, monkeypatch,
):
    repo, eco, world, bin_dir = project
    _stand_in(bin_dir, world, eco)
    # A first attempt whose candidate push is refused while another commit
    # lands on top of the release commit: the attempt is kept for a resume.
    hook = tmp_path / "remote" / "hooks" / "pre-receive"
    hook.write_text(
        "#!/bin/sh\n"
        f"cd '{repo}' && unset GIT_DIR GIT_QUARANTINE_PATH GIT_OBJECT_DIRECTORY "
        "GIT_ALTERNATE_OBJECT_DIRECTORIES && "
        "printf 'x\\n' >> feature.txt && git add feature.txt && "
        "git commit -q -m 'chore: on top' --trailer 'Autogenerated: true'\n"
        "exit 1\n"
    )
    hook.chmod(0o755)
    assert _release(repo, monkeypatch).exit_code != 0
    state = repo / ".rlsbl" / "releases" / "in-progress.json"
    assert state.exists()
    hook.unlink()

    tool_path = bin_dir / ECOSYSTEMS[eco]["tool"]
    tool_path.unlink()
    refused = _release(repo, monkeypatch, "resume")
    assert refused.exit_code == 1, refused.stderr + refused.stdout
    assert _install_hint(eco) in refused.stderr
    assert "then run `rlsbl release resume`" in refused.stderr
    assert state.exists()

    fresh = bin_dir.parent / "fresh-bin"
    _stand_in(fresh, world, eco)
    shutil.copy2(fresh / ECOSYSTEMS[eco]["tool"], tool_path)
    resumed = _release(repo, monkeypatch, "resume")
    assert resumed.exit_code == 0, resumed.stderr + resumed.stdout
    assert git(repo, "rev-parse", "v1.0.1^{commit}")
    assert not state.exists()


def test_a_dev_node_lock_with_uv_missing_refuses_and_installing_it_plans_the_sync(
    tmp_path, monkeypatch,
):
    """The dev_node refresh is planned apart from the release's own targets."""
    root = tmp_path / "ws"
    root.mkdir()
    devnode._workspace(root)
    bin_dir = tmp_path / "bin"
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{os.environ['PATH']}")
    _hide_tools_outside(bin_dir, monkeypatch)

    with pytest.raises(execute.ReleaseAbortError) as refused:
        devnode._plan(root)
    message = str(refused.value)
    assert "`uv` is not on PATH" in message
    assert "Install uv (or put it on PATH)" in message
    assert "re-run `rlsbl release run`" in message

    bin_dir.mkdir()
    (bin_dir / "uv").write_text("#!/bin/sh\nexit 0\n")
    (bin_dir / "uv").chmod(0o755)
    plan = devnode._plan(root)
    dirs = [os.path.normpath(p["cwd"]) for p in devnode._uv_lock_syncs(plan)]
    assert os.path.normpath(str(root / "conformance")) in dirs
