"""Tests for the ``rlsbl changelog remap`` command (cmd_remap)."""

import os
import sys

import pytest

from rlsbl.changelog.files import get_changes_dir, remap_jsonl_hashes
from rlsbl.changelog.schema import ChangelogEntry, parse_jsonl, serialize_entry
from rlsbl.commands.changelog_cmd import _parse_sha_map_lines, cmd_remap


def _write_entries(path, entries):
    """Write a list of ChangelogEntry objects to a JSONL file."""
    with open(path, "w", encoding="utf-8") as f:
        for entry in entries:
            f.write(serialize_entry(entry) + "\n")


def _setup_standalone_project(tmp_path):
    """Create a minimal standalone rlsbl project with a changes dir."""
    project = tmp_path / "project"
    project.mkdir()
    changes = project / ".rlsbl" / "changes"
    changes.mkdir(parents=True)
    return project, changes


# ---------------------------------------------------------------------------
# _parse_sha_map_lines tests
# ---------------------------------------------------------------------------


class TestParseShaMapLines:
    """Tests for the ``old_sha new_sha`` line parser."""

    def test_parses_two_column_lines(self):
        lines = [
            "abc123 def456\n",
            "111aaa 222bbb\n",
        ]
        result = _parse_sha_map_lines(lines)
        assert result == {"abc123": "def456", "111aaa": "222bbb"}

    def test_skips_blank_lines_and_comments(self):
        lines = [
            "# comment\n",
            "\n",
            "   \n",
            "abc123 def456\n",
        ]
        result = _parse_sha_map_lines(lines)
        assert result == {"abc123": "def456"}

    def test_ignores_extra_columns(self):
        """git's post-rewrite hook may emit extra fields after the two SHAs."""
        lines = ["old_sha new_sha extra_field\n"]
        result = _parse_sha_map_lines(lines)
        assert result == {"old_sha": "new_sha"}

    def test_warns_on_single_column(self, capsys):
        lines = ["only_one_field\n"]
        result = _parse_sha_map_lines(lines)
        assert result == {}
        captured = capsys.readouterr()
        assert "malformed" in captured.err


# ---------------------------------------------------------------------------
# cmd_remap: --map-file source
# ---------------------------------------------------------------------------


class TestRemapViaMapFile:
    """Test remapping a single entry via --map-file."""

    def test_remap_single_entry_via_map_file(self, tmp_path, monkeypatch):
        project, changes = _setup_standalone_project(tmp_path)
        unreleased = changes / "unreleased.jsonl"
        _write_entries(str(unreleased), [
            ChangelogEntry(commits=["old_aaa"], user_facing=False),
            ChangelogEntry(
                commits=["old_bbb"],
                user_facing=True,
                description="A feature",
                type="feature",
            ),
        ])

        # Write a map file
        map_file = tmp_path / "map.txt"
        map_file.write_text("old_aaa new_aaa\nold_bbb new_bbb\n")

        # Stub out commit_files to avoid needing a real git repo
        import rlsbl.commands.changelog_cmd as mod
        committed = []
        monkeypatch.setattr(mod, "commit_files", lambda *a, **kw: committed.append((a, kw)))

        flags = {
            "map-file": str(map_file),
            "from-journal": False,
            "stdin": False,
            "dry-run": False,
        }
        cmd_remap(flags, project_root=project)

        # Verify the JSONL was rewritten
        updated = parse_jsonl(str(unreleased))
        assert updated[0].commits == ["new_aaa"]
        assert updated[1].commits == ["new_bbb"]
        assert updated[1].description == "A feature"

        # Verify auto-commit was called
        assert len(committed) == 1
        assert committed[0][1].get("autogenerated") is True


# ---------------------------------------------------------------------------
# cmd_remap: --stdin source
# ---------------------------------------------------------------------------


class TestRemapViaStdin:
    """Test remapping via stdin (piped map)."""

    def test_remap_via_stdin(self, tmp_path, monkeypatch):
        project, changes = _setup_standalone_project(tmp_path)
        unreleased = changes / "unreleased.jsonl"
        _write_entries(str(unreleased), [
            ChangelogEntry(commits=["stale_hash"], user_facing=False),
        ])

        # Mock stdin
        import io
        monkeypatch.setattr(sys, "stdin", io.StringIO("stale_hash fresh_hash\n"))

        # Stub out commit_files
        import rlsbl.commands.changelog_cmd as mod
        monkeypatch.setattr(mod, "commit_files", lambda *a, **kw: None)

        flags = {
            "map-file": None,
            "from-journal": False,
            "stdin": True,
            "dry-run": False,
        }
        cmd_remap(flags, project_root=project)

        updated = parse_jsonl(str(unreleased))
        assert updated[0].commits == ["fresh_hash"]


# ---------------------------------------------------------------------------
# cmd_remap: unmapped hash warning
# ---------------------------------------------------------------------------


class TestRemapUnmappedWarning:
    """Test that unmapped hashes are reported as warnings."""

    def test_unmapped_hash_reported(self, tmp_path, monkeypatch, capsys):
        project, changes = _setup_standalone_project(tmp_path)
        unreleased = changes / "unreleased.jsonl"
        _write_entries(str(unreleased), [
            ChangelogEntry(commits=["mapped_hash", "orphan_hash"], user_facing=False),
        ])

        map_file = tmp_path / "map.txt"
        map_file.write_text("mapped_hash new_mapped\n")

        import rlsbl.commands.changelog_cmd as mod
        monkeypatch.setattr(mod, "commit_files", lambda *a, **kw: None)

        flags = {
            "map-file": str(map_file),
            "from-journal": False,
            "stdin": False,
            "dry-run": False,
        }
        cmd_remap(flags, project_root=project)

        captured = capsys.readouterr()
        assert "unmapped hash" in captured.err
        assert "orphan_hash" in captured.err

        # The mapped hash should still have been remapped
        updated = parse_jsonl(str(unreleased))
        assert updated[0].commits == ["new_mapped", "orphan_hash"]


# ---------------------------------------------------------------------------
# cmd_remap: no-source error
# ---------------------------------------------------------------------------


class TestRemapNoSourceError:
    """Test that no source flags produce a hard error."""

    def test_no_source_exits(self, tmp_path):
        project, _ = _setup_standalone_project(tmp_path)
        flags = {
            "map-file": None,
            "from-journal": False,
            "stdin": False,
            "dry-run": False,
        }
        with pytest.raises(SystemExit) as exc_info:
            cmd_remap(flags, project_root=project)
        assert exc_info.value.code == 1
