"""Regression test: in-progress.json must be cleaned up before watch runs.

Bug: watch_run_cmd() calls sys.exit() directly (watch.py lines 319, 322,
426, 429), which terminates the process.  If clear_release_state() runs
AFTER the watch block, the in-progress.json state file is never cleaned
up, blocking future releases with "a previous release is in progress."

The fix moves clear_release_state() and the "Release complete!" message
to BEFORE the watch block, since the release is already done at that
point (tag pushed, GitHub Release created).

This test runs a successful release with watch=True and verifies that
the in-progress.json state file is already deleted by the time the
watch function is invoked.
"""

import json
import os
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.commands.release.release_state import get_state_path
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run


def _rc(bump="patch", include=None, exclude=None):
    return ReleaseConfig(
        bump=bump,
        include=include or ["npm"],
        exclude=exclude or [],
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _git_head(repo):
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _setup_releasable_npm_project(repo):
    """Create an npm project at v1.0.0 with one unreleased commit."""
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "test@test.local")
    _git(repo, "config", "user.name", "Test")

    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"]}) + "\n"
    )
    _git(repo, "add",
         "package.json", "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_head(repo)

    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(repo, "commit", "-q", "-m", "changelog: add feature entry",
         "--trailer", "Autogenerated: true")

    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "unreleased.toml").write_text(
        'bump = "patch"\ninclude = ["npm"]\nexclude = []\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")


def _make_ctx(repo):
    return ProjectContext(
        project_root=Path(str(repo)),
        workspace_root=None,
        config={"publish_mode": "ci", "pipelines": {}},
    )


def _fake_run_factory():
    def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
        if cmd == "gh":
            return ""
        if cmd == "git" and args and args[0] == "push":
            return ""
        if cmd == "git" and args and args[0] == "fetch":
            return ""
        if cmd == "git" and args and args[:2] == ["rev-list", "--count"] and any("origin/" in a for a in args):
            return "0"
        return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)
    return fake_run


class TestWatchCleanup:
    """Regression: in-progress.json must be deleted before watch_run_cmd runs."""

    def test_state_file_cleaned_before_watch(self, tmp_project):
        """Run a successful release with watch=True and verify that
        in-progress.json is already gone when watch_run_cmd is called."""
        _setup_releasable_npm_project(tmp_project)

        state_path = get_state_path(str(tmp_project))
        state_existed_during_watch = []

        def fake_watch(app_unused, args, flags):
            """Mock watch that checks whether the state file exists,
            then exits like the real watch does."""
            state_existed_during_watch.append(os.path.exists(state_path))
            raise SystemExit(0)

        fake_run = _fake_run_factory()

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.push_if_needed"),
            patch("rlsbl.commands.release.run_gh", return_value=""),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.remote_branch_exists", return_value=True),
            patch("rlsbl.commands.watch.run_cmd", side_effect=fake_watch),
        ):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(
                    _rc(),
                    {"yes": True, "quiet": True, "watch": True},
                    ctx=_make_ctx(tmp_project),
                )

            assert exc_info.value.code == 0, (
                "watch sys.exit should propagate with code 0"
            )

        # The mock was called (watch was invoked)
        assert len(state_existed_during_watch) == 1, (
            "watch_run_cmd should have been called exactly once"
        )

        # The state file must NOT have existed when watch was called
        assert state_existed_during_watch[0] is False, (
            "in-progress.json must be cleaned up BEFORE watch_run_cmd is "
            "called, because watch calls sys.exit() and would skip cleanup"
        )

        # Double-check: state file is gone after the test too
        assert not os.path.exists(state_path), (
            "in-progress.json should not exist after a successful release"
        )
