"""Phase 1.7 post-push failure-state tests.

Covers the gaps closed in the release push-failure flow:

- Fix 1: an expected push failure exits run_cmd cleanly (SystemExit(1), no
  traceback) with resume guidance, instead of propagating a raw exception.
- Fix 2: a transient tag-push failure that clears on the in-handler retry
  recovers -- the release falls through into GITHUB_RELEASE rather than
  aborting.
- Fix 3: a batch item is only "released" when its tag exists on the REMOTE
  (not merely tagged locally); the archive gate also refuses while any item
  has in-progress release state.
- Fix 4: the branch-push skip uses a LIVE `git ls-remote` comparison, not the
  (possibly stale) local origin/<branch> tracking ref.
"""

import json
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from rlsbl.commands.release import run_cmd
from rlsbl.commands.release.release_state import get_state_path, load_release_state
from rlsbl.context import ProjectContext
from rlsbl.release_file import ReleaseConfig
from rlsbl.utils import run as real_run

from githarness import init_repo, commit_file, add_remote


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _rc(bump="patch"):
    return ReleaseConfig(
        bump=bump, include=["npm"], exclude=[], description="test release",
    )


def _git(repo, *args):
    subprocess.run(
        ["git"] + list(args), cwd=str(repo), check=True,
        capture_output=True, text=True,
    )


def _git_out(repo, *args):
    return subprocess.run(
        ["git"] + list(args), cwd=str(repo), check=True,
        capture_output=True, text=True,
    ).stdout.strip()


def _setup_npm_project(repo):
    """An npm project at v1.0.0 with one covered unreleased commit + release file."""
    (repo / "package.json").write_text(
        json.dumps({"name": "test-pkg", "version": "1.0.0"}, indent=2) + "\n"
    )
    (repo / "CHANGELOG.md").write_text(
        "<!-- Generated by rlsbl from .rlsbl/changes/ -- do not edit -->\n\n"
        "# Changelog\n\n## 1.0.0\n\n- Initial release.\n"
    )
    changes_dir = repo / ".rlsbl" / "changes"
    changes_dir.mkdir(parents=True)
    (changes_dir / "unreleased.jsonl").write_text("")
    (repo / ".rlsbl" / "config.json").write_text(
        json.dumps({"publish_mode": "ci", "targets": ["npm"]}) + "\n"
    )
    _git(repo, "add", "package.json", "CHANGELOG.md",
         ".rlsbl/changes/unreleased.jsonl", ".rlsbl/config.json")
    _git(repo, "commit", "-q", "-m", "initial")
    _git(repo, "tag", "v1.0.0")

    (repo / "feature.txt").write_text("new feature\n")
    _git(repo, "add", "feature.txt")
    _git(repo, "commit", "-q", "-m", "add feature")
    feature_sha = _git_out(repo, "rev-parse", "HEAD")
    entry = {
        "commits": [feature_sha],
        "user_facing": True,
        "description": "**New feature.** A shiny new thing.",
        "type": "feature",
    }
    (changes_dir / "unreleased.jsonl").write_text(json.dumps(entry) + "\n")
    _git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
    _git(repo, "commit", "-q", "-m", "changelog: add feature entry",
         "--trailer", "Autogenerated: true")

    releases_dir = repo / ".rlsbl" / "releases"
    releases_dir.mkdir(parents=True)
    (releases_dir / "unreleased.toml").write_text(
        'bump = "patch"\ninclude = ["npm"]\nexclude = []\n'
        'description = "test release"\n'
    )
    _git(repo, "add", ".rlsbl/releases/unreleased.toml")
    _git(repo, "commit", "-q", "-m", "add release file",
         "--trailer", "Autogenerated: true")
    return feature_sha


def _ctx(repo):
    return ProjectContext(
        project_root=Path(str(repo)), workspace_root=None,
        config={"publish_mode": "ci", "pipelines": {}},
    )


# ---------------------------------------------------------------------------
# Fix 2: transient tag-push retry success reaches GITHUB_RELEASE
# ---------------------------------------------------------------------------


class TestTransientTagPushRetrySuccess:
    """A post-TAGGED tag-push failure that clears on the in-handler retry must
    recover and continue into GITHUB_RELEASE, not abort with resume guidance."""

    def test_transient_retry_reaches_github_release(self, mock_git_repo):
        _setup_npm_project(mock_git_repo)

        gh_calls = []
        tag_push_attempts = []

        def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
            if cmd == "git" and args and args[0] == "push" and len(args) > 2 \
                    and args[2].startswith("v"):
                tag_push_attempts.append(list(args))
                # Fail the first attempt only; the in-handler retry succeeds.
                if len(tag_push_attempts) == 1:
                    raise subprocess.CalledProcessError(
                        1, ["git", "push", "origin", args[2]],
                        stderr="fatal: transient network blip",
                    )
                return ""
            return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)

        def fake_run_gh(gh_args, **kwargs):
            gh_calls.append(list(gh_args))
            # gh release view fails -> creation proceeds -> GITHUB_RELEASE.
            if gh_args[:2] == ["release", "view"]:
                raise subprocess.CalledProcessError(1, "gh release view")
            return ""

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.validate_gh_push_access"),
            patch("rlsbl.commands.release.validate_branch_and_remote",
                  return_value="main"),
            patch("rlsbl.commands.release.push_if_needed"),  # branch push OK
            patch("rlsbl.commands.release.tag_exists_on_remote",
                  return_value=False),  # tag not yet on remote -> push attempted
            patch("rlsbl.commands.release.execute.time.sleep"),  # no retry delay
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.run_gh", side_effect=fake_run_gh),
        ):
            # No SystemExit: the recovered push falls through to completion.
            run_cmd(_rc(), {"yes": True, "quiet": True}, ctx=_ctx(mock_git_repo))

        assert len(tag_push_attempts) >= 2, \
            "the tag push must be retried after the transient failure"
        assert any(c[:2] == ["release", "create"] for c in gh_calls), \
            "recovery must fall through into GitHub Release creation"

        # A fully-completed release clears its state file.
        assert not load_release_state(get_state_path(str(mock_git_repo))), \
            "state must be cleared after the recovered release completes"


# ---------------------------------------------------------------------------
# Fix 4: branch-push skip uses a live ls-remote comparison
# ---------------------------------------------------------------------------


class TestLiveLsRemoteBranchSkip:
    """The branch push is skipped when a LIVE ls-remote shows the remote is
    already at the local HEAD -- even if the local origin/<branch> tracking
    ref is stale/absent (which is what the old rev-parse check relied on)."""

    def test_branch_push_skipped_via_live_ls_remote(self, mock_git_repo, capsys):
        _setup_npm_project(mock_git_repo)

        push_if_needed_called = []

        def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
            # Model the live remote as already at local HEAD: ls-remote of the
            # branch ref returns the current HEAD sha. (The old code queried the
            # local origin/<branch> tracking ref, which does not exist here, so
            # it would NOT skip -> this asserts the new live-query behavior.)
            if cmd == "git" and args and args[0] == "ls-remote" \
                    and len(args) >= 3 and args[2].startswith("refs/heads/"):
                head = real_run("git", ["rev-parse", "HEAD"]).strip()
                return f"{head}\t{args[2]}"
            return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)

        def fake_push_if_needed(branch, env=None, *, config):
            push_if_needed_called.append(branch)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.validate_gh_push_access"),
            patch("rlsbl.commands.release.validate_branch_and_remote",
                  return_value="main"),
            patch("rlsbl.commands.release.push_if_needed",
                  side_effect=fake_push_if_needed),
            patch("rlsbl.commands.release.tag_exists_on_remote",
                  return_value=True),  # tag already on remote -> tag push skipped
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.run_gh", return_value=""),
        ):
            run_cmd(_rc(), {"yes": True, "quiet": False}, ctx=_ctx(mock_git_repo))

        assert push_if_needed_called == [], \
            "branch push must be skipped when the live remote is at local HEAD"
        assert "Skipping branch push (remote already at local HEAD)" \
            in capsys.readouterr().out


# ---------------------------------------------------------------------------
# Fix 1 + Fix 5: permanent push failure exits cleanly with resume guidance
# ---------------------------------------------------------------------------


class TestPermanentPushFailureCleanExit:
    """A permanent post-TAGGED push failure exits run_cmd via SystemExit(1)
    with resume guidance and no traceback; the local tag is preserved but the
    remote never receives it, so the item is NOT observably released."""

    def test_exits_cleanly_and_remote_lacks_tag(self, tmp_path, monkeypatch, capsys):
        repo = tmp_path / "repo"
        init_repo(repo)
        # Seed an initial commit before wiring the remote so add_remote can push.
        commit_file(repo, ".gitkeep", "", "seed")
        _setup_npm_project(repo)
        add_remote(repo, tmp_path / "remote")  # pushes main + tags
        monkeypatch.chdir(repo)  # release validation (clean-tree) runs in cwd

        from rlsbl.commands.monorepo.batch_plan import PlanItem, item_is_released

        def fake_run(cmd, args=None, timeout=120, env=None, cwd=None):
            # Permanent tag-push failure (branch push goes through real
            # push_if_needed, which is NOT patched, so the branch reaches the
            # bare remote -- but the tag never does).
            if cmd == "git" and args and args[0] == "push" and len(args) > 2 \
                    and args[2].startswith("v"):
                raise subprocess.CalledProcessError(
                    1, ["git", "push", "origin", args[2]],
                    stderr="fatal: remote rejected tag",
                )
            return real_run(cmd, args=args, timeout=timeout, env=env, cwd=cwd)

        with (
            patch("rlsbl.commands.release.check_gh_installed", return_value=True),
            patch("rlsbl.commands.release.check_gh_auth", return_value=True),
            patch("rlsbl.commands.release.validate_gh_push_access"),
            patch("rlsbl.commands.release.validate_branch_and_remote",
                  return_value="main"),
            patch("rlsbl.commands.release.execute.time.sleep"),
            patch("rlsbl.commands.release.run", side_effect=fake_run),
            patch("rlsbl.commands.release.run_gh", return_value=""),
        ):
            with pytest.raises(SystemExit) as exc:
                run_cmd(_rc(), {"yes": True, "quiet": False},
                        ctx=_ctx(repo))
        assert exc.value.code == 1

        err = capsys.readouterr().err
        assert "Traceback" not in err, "must not dump a Python traceback"
        assert "rlsbl release resume" in err, "must print resume guidance"

        # The local tag exists but the remote never received it.
        assert _git_out(repo, "tag", "-l", "v1.0.1") == "v1.0.1"
        remote_tag = _git_out(repo, "ls-remote", "--tags", "origin", "v1.0.1")
        assert remote_tag == "", "remote must NOT have the tag after the failure"

        # Fix 3a interaction: an item whose live version matches the target but
        # whose tag is only local is NOT observably released.
        item = PlanItem(
            name="test-pkg", base_version="1.0.0", target_version="1.0.1",
            tag="v1.0.1", registry="npm", bump="patch",
        )
        with patch(
            "rlsbl.commands.monorepo.batch_plan.read_live_version",
            return_value="1.0.1",
        ):
            # cwd is repo (monkeypatch.chdir above): the real ls-remote runs
            # against the bare remote, which lacks the tag.
            assert not item_is_released(str(repo), item, [], "packages"), \
                "a locally-tagged-but-unpushed item is not released"


# ---------------------------------------------------------------------------
# Fix 3a: item_is_released requires the tag on the remote (real bare remote)
# ---------------------------------------------------------------------------


class TestItemReleasedRequiresRemoteTag:
    """item_is_released flips from False to True only once the tag is pushed."""

    def test_local_then_pushed_tag(self, tmp_path):
        import os

        repo = tmp_path / "repo"
        init_repo(repo)
        commit_file(repo, "README.md", "# hi\n", "initial")
        add_remote(repo, tmp_path / "remote")

        from rlsbl.commands.monorepo.batch_plan import PlanItem, item_is_released

        # Create a local tag that is NOT pushed.
        _git(repo, "tag", "pkg@v0.2.0")

        item = PlanItem(
            name="pkg", base_version="0.1.0", target_version="0.2.0",
            tag="pkg@v0.2.0", registry="pypi", bump="minor",
        )

        cwd0 = os.getcwd()
        os.chdir(str(repo))
        try:
            with patch(
                "rlsbl.commands.monorepo.batch_plan.read_live_version",
                return_value="0.2.0",
            ):
                assert not item_is_released(str(repo), item, [], "packages"), \
                    "local-only tag must not count as released"
                # Push the tag: now the remote has it.
                _git(repo, "push", "-q", "origin", "pkg@v0.2.0")
                assert item_is_released(str(repo), item, [], "packages"), \
                    "a pushed tag must count as released"
        finally:
            os.chdir(cwd0)


# ---------------------------------------------------------------------------
# Fix 3b: archive gate refuses while any item has in-progress state
# ---------------------------------------------------------------------------


class TestArchiveRefusedWithInProgressState:
    """_archive_batch_if_complete must not finalize the batch file while any
    plan item still has an in-progress.json on disk."""

    def test_in_progress_state_blocks_archive(self, tmp_path):
        import os

        from rlsbl.commands.monorepo.batch_plan import BatchPlan, PlanItem
        from rlsbl.commands.monorepo.batch_release import (
            _archive_batch_if_complete, _plan_items_in_progress,
        )

        ws = tmp_path / "ws"
        pkg_dir = ws / "packages" / "alpha"
        (pkg_dir / ".rlsbl" / "releases").mkdir(parents=True)
        # Write an in-progress.json for alpha.
        (pkg_dir / ".rlsbl" / "releases" / "in-progress.json").write_text(
            json.dumps({"new_version": "0.2.0", "completed_steps": ["TAGGED"]})
        )

        projects = [{"name": "alpha", "path": "packages/alpha"}]
        plan = BatchPlan(
            section_type="packages",
            items={
                "alpha": PlanItem(
                    "alpha", "0.1.0", "0.2.0", "alpha@v0.2.0", "pypi", "minor",
                ),
            },
        )

        stranded = _plan_items_in_progress(plan, str(ws), projects)
        assert stranded == ["alpha"]

        batch_path = ws / ".rlsbl-monorepo" / "releases" / "unreleased.toml"
        batch_path.parent.mkdir(parents=True)
        batch_path.write_text("[packages.alpha]\nbump = \"minor\"\n")

        logs = []
        # plan_all_released short-circuits on the (missing) remote tag, so patch
        # it True to isolate the in-progress guard as the reason for refusal.
        with patch(
            "rlsbl.commands.monorepo.batch_release.plan_all_released",
            return_value=True,
        ):
            _archive_batch_if_complete(
                str(batch_path), plan, str(ws), projects, logs.append,
            )

        assert batch_path.exists(), \
            "batch file must NOT be archived while an item is in-progress"
        assert any("in-progress release state exists" in m for m in logs)
