"""Tests for the full run_cmd flow of rlsbl.commands.pre_push_check."""

import json
from io import StringIO
from unittest.mock import patch

import pytest

from conftest import run_git as _run_git, git_head as _git_head
from rlsbl.commands.pre_push_check import (
    _check_gitignore_guard,
    _check_jsonl_changelog,
    _has_version_tag_push,
    run_cmd,
)


@pytest.fixture
def jsonl_git_repo(tmp_path, monkeypatch):
    """Create a git repo with .rlsbl/changes/ for JSONL changelog testing."""
    repo = tmp_path / "repo"
    repo.mkdir()
    monkeypatch.chdir(repo)

    _run_git(repo, "init", "-q")
    _run_git(repo, "config", "user.email", "test@test.local")
    _run_git(repo, "config", "user.name", "Test")

    # Initial commit
    (repo / "README.md").write_text("# test\n")
    _run_git(repo, "add", "README.md")
    _run_git(repo, "commit", "-q", "-m", "initial")

    # Create a baseline version tag
    _run_git(repo, "tag", "v0.0.0")

    # Set up .rlsbl/changes with empty unreleased.jsonl
    changes = repo / ".rlsbl" / "changes"
    changes.mkdir(parents=True)
    (changes / "unreleased.jsonl").write_text("")

    return repo


class TestRunCmdEntryExists:
    """run_cmd exits 0 when CHANGELOG.md has a matching version heading."""

    def test_exits_zero(self, tmp_project):
        (tmp_project / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"})
        )
        (tmp_project / "CHANGELOG.md").write_text("# Changelog\n\n## 1.0.0\n\n- Initial release\n")

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {}, project_root=".")

        assert exc_info.value.code == 0


class TestRunCmdWithoutJsonl:
    """run_cmd warns and exits 0 when JSONL changelog is not set up."""

    def test_warns_no_jsonl(self, tmp_project, capsys):
        (tmp_project / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"})
        )
        (tmp_project / "CHANGELOG.md").write_text("# Changelog\n\n## 0.9.0\n\n- Old stuff\n")

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {}, project_root=".")

        assert exc_info.value.code == 0
        captured = capsys.readouterr()
        assert "JSONL changelog not set up" in captured.err

    def test_no_changelog_exits_zero(self, tmp_project, capsys):
        (tmp_project / "package.json").write_text(
            json.dumps({"name": "test-pkg", "version": "1.0.0"})
        )

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {}, project_root=".")

        assert exc_info.value.code == 0


class TestRunCmdNoProjectFiles:
    """run_cmd exits 0 silently when no project files exist."""

    def test_exits_zero(self, tmp_project):
        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {}, project_root=".")

        assert exc_info.value.code == 0


class TestAutogeneratedCommitFiltering:
    """Autogenerated commits (with trailer) should be filtered from JSONL coverage checks."""

    def test_autogenerated_commit_skipped(self, jsonl_git_repo):
        """An autogenerated commit passes -- filtered from coverage set."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)
        _run_git(repo, "commit", "--allow-empty", "-m", "auto\n\nAutogenerated: true")
        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_multiple_autogenerated_commits_skipped(self, jsonl_git_repo):
        """Multiple autogenerated commits all pass."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)
        _run_git(repo, "commit", "--allow-empty", "-m", "auto1\n\nAutogenerated: true")
        _run_git(repo, "commit", "--allow-empty", "-m", "auto2\n\nAutogenerated: true")
        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_non_autogenerated_commit_needs_coverage(self, jsonl_git_repo):
        """A regular commit without the trailer fails with empty JSONL."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is not None
        assert "no jsonl changelog entries found" in error.lower()

    def test_autogenerated_mixed_with_code_commit(self, jsonl_git_repo):
        """Autogenerated commits are filtered; code commits still need coverage."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # Code commit needing coverage
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        code_sha = _git_head(repo)

        # Autogenerated commit (should be filtered out)
        _run_git(repo, "commit", "--allow-empty", "-m", "auto\n\nAutogenerated: true")
        sha = _git_head(repo)

        # Add JSONL entry covering the code commit
        changes_dir = repo / ".rlsbl" / "changes"
        entry = json.dumps({"commits": [code_sha], "user_facing": True,
                            "description": "add feature", "type": "feature"})
        (changes_dir / "unreleased.jsonl").write_text(entry + "\n")

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_code_commits_with_jsonl_coverage_pass(self, jsonl_git_repo):
        """Code commits with proper JSONL coverage pass alongside autogenerated commits."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # Regular code commit
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        code_sha = _git_head(repo)

        # Add JSONL entry covering the code commit
        changes_dir = repo / ".rlsbl" / "changes"
        entry = json.dumps({"commits": [code_sha], "user_facing": True,
                            "description": "add feature", "type": "feature"})
        (changes_dir / "unreleased.jsonl").write_text(entry + "\n")
        _run_git(repo, "add", ".rlsbl/changes/unreleased.jsonl")
        _run_git(repo, "commit", "-q", "-m", "changelog entry\n\nAutogenerated: true")

        sha = _git_head(repo)

        refs = [(sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None


class TestHasVersionTagPush:
    """Unit tests for _has_version_tag_push."""

    def test_simple_version_tag(self):
        lines = ["refs/tags/v1.2.3 abc123 refs/tags/v1.2.3 def456"]
        assert _has_version_tag_push(lines) is True

    def test_monorepo_scoped_tag(self):
        lines = ["refs/tags/mylib@v1.2.3 abc123 refs/tags/mylib@v1.2.3 def456"]
        assert _has_version_tag_push(lines) is True

    def test_branch_push_no_tag(self):
        lines = ["refs/heads/main abc123 refs/heads/main def456"]
        assert _has_version_tag_push(lines) is False

    def test_non_version_tag(self):
        """A tag that does not match the version pattern is not a release."""
        lines = ["refs/tags/some-label abc123 refs/tags/some-label def456"]
        assert _has_version_tag_push(lines) is False

    def test_mixed_branch_and_version_tag(self):
        """If any line is a version tag, the result is True."""
        lines = [
            "refs/heads/main abc123 refs/heads/main def456",
            "refs/tags/v2.0.0 aaa111 refs/tags/v2.0.0 bbb222",
        ]
        assert _has_version_tag_push(lines) is True

    def test_mixed_branch_and_non_version_tag(self):
        lines = [
            "refs/heads/main abc123 refs/heads/main def456",
            "refs/tags/nightly abc123 refs/tags/nightly def456",
        ]
        assert _has_version_tag_push(lines) is False

    def test_v_prefix_required(self):
        """Tag must start with 'v' followed by a digit."""
        lines = ["refs/tags/version-1.0 abc123 refs/tags/version-1.0 def456"]
        assert _has_version_tag_push(lines) is False

    def test_empty_lines(self):
        assert _has_version_tag_push([]) is False


class TestVersionTagPushSkipsCheck:
    """run_cmd exits 0 immediately when the push includes a version tag."""

    def test_version_tag_skips_jsonl_check(self, jsonl_git_repo):
        """Pushing a version tag skips the JSONL check entirely."""
        repo = jsonl_git_repo

        # Make a commit without JSONL coverage -- would normally fail
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: uncovered")
        sha = _git_head(repo)

        stdin_data = f"refs/tags/v1.0.0 {sha} refs/tags/v1.0.0 {'0' * 40}\n"

        with patch("sys.stdin", StringIO(stdin_data)), \
             patch("sys.stdin.isatty", return_value=False):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(None, [], {}, project_root=".")
            assert exc_info.value.code == 0

    def test_monorepo_tag_skips_jsonl_check(self, jsonl_git_repo):
        """Pushing a monorepo scoped version tag skips the JSONL check."""
        repo = jsonl_git_repo

        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: uncovered")
        sha = _git_head(repo)

        stdin_data = f"refs/tags/mylib@v2.0.0 {sha} refs/tags/mylib@v2.0.0 {'0' * 40}\n"

        with patch("sys.stdin", StringIO(stdin_data)), \
             patch("sys.stdin.isatty", return_value=False):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(None, [], {}, project_root=".")
            assert exc_info.value.code == 0

    def test_branch_push_still_checks(self, jsonl_git_repo):
        """Pushing a branch (no tags) still runs the JSONL check."""
        repo = jsonl_git_repo

        # Make a commit without JSONL coverage
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: uncovered")
        sha = _git_head(repo)
        base_sha = "0" * 40

        stdin_data = f"refs/heads/main {sha} refs/heads/main {base_sha}\n"

        with patch("sys.stdin", StringIO(stdin_data)), \
             patch("sys.stdin.isatty", return_value=False):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(None, [], {}, project_root=".")
            # Should fail because the commit has no JSONL coverage
            assert exc_info.value.code == 1

    def test_non_version_tag_still_checks(self, jsonl_git_repo):
        """Pushing a non-version tag does NOT skip the JSONL check."""
        repo = jsonl_git_repo

        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: uncovered")
        sha = _git_head(repo)

        stdin_data = f"refs/tags/some-label {sha} refs/tags/some-label {'0' * 40}\n"

        with patch("sys.stdin", StringIO(stdin_data)), \
             patch("sys.stdin.isatty", return_value=False):
            with pytest.raises(SystemExit) as exc_info:
                run_cmd(None, [], {}, project_root=".")
            # Should fail -- non-version tag doesn't skip the check
            assert exc_info.value.code == 1


class TestGitignoreGuard:
    """Unit tests for _check_gitignore_guard."""

    def test_unreleased_jsonl_gitignored(self, mock_git_repo):
        """Gitignored unreleased.jsonl triggers an error."""
        (mock_git_repo / ".gitignore").write_text(".rlsbl/changes/unreleased.jsonl\n")
        _run_git(mock_git_repo, "add", ".gitignore")
        _run_git(mock_git_repo, "commit", "-q", "-m", "add gitignore")

        result = _check_gitignore_guard(str(mock_git_repo))
        assert result is not None
        assert "unreleased.jsonl" in result

    def test_validated_gitignored(self, mock_git_repo):
        """Gitignored .validated triggers an error."""
        (mock_git_repo / ".gitignore").write_text(".rlsbl/changes/.validated\n")
        _run_git(mock_git_repo, "add", ".gitignore")
        _run_git(mock_git_repo, "commit", "-q", "-m", "add gitignore")

        result = _check_gitignore_guard(str(mock_git_repo))
        assert result is not None
        assert ".validated" in result

    def test_changelog_md_gitignored(self, mock_git_repo):
        """Gitignored CHANGELOG.md triggers an error."""
        (mock_git_repo / ".gitignore").write_text("CHANGELOG.md\n")
        _run_git(mock_git_repo, "add", ".gitignore")
        _run_git(mock_git_repo, "commit", "-q", "-m", "add gitignore")

        result = _check_gitignore_guard(str(mock_git_repo))
        assert result is not None
        assert "CHANGELOG.md" in result

    def test_nothing_gitignored(self, mock_git_repo):
        """No gitignored rlsbl files returns None."""
        result = _check_gitignore_guard(str(mock_git_repo))
        assert result is None

    def test_multiple_files_gitignored(self, mock_git_repo):
        """Multiple gitignored files are all listed in the error."""
        (mock_git_repo / ".gitignore").write_text(
            ".rlsbl/changes/unreleased.jsonl\n"
            "CHANGELOG.md\n"
        )
        _run_git(mock_git_repo, "add", ".gitignore")
        _run_git(mock_git_repo, "commit", "-q", "-m", "add gitignore")

        result = _check_gitignore_guard(str(mock_git_repo))
        assert result is not None
        assert "unreleased.jsonl" in result
        assert "CHANGELOG.md" in result


class TestVersionedJsonlCoverage:
    """Entries in versioned JSONL files (e.g. 0.30.1.jsonl) provide coverage."""

    def test_versioned_file_covers_pushed_commits(self, jsonl_git_repo):
        """Empty unreleased.jsonl + versioned file with entries -> passes."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # Make a code commit
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        code_sha = _git_head(repo)

        # Put the entry in a versioned JSONL file (simulating post-release state)
        changes_dir = repo / ".rlsbl" / "changes"
        entry = json.dumps({"commits": [code_sha], "user_facing": True,
                            "description": "add feature", "type": "feature"})
        (changes_dir / "0.1.0.jsonl").write_text(entry + "\n")

        # unreleased.jsonl is empty (already set up by fixture)
        refs = [(code_sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None

    def test_neither_unreleased_nor_versioned_covers_commit(self, jsonl_git_repo):
        """Empty unreleased.jsonl + versioned file without matching entry -> fails."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # Make a code commit
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: add feature")
        code_sha = _git_head(repo)

        # Versioned file exists but covers a different commit
        changes_dir = repo / ".rlsbl" / "changes"
        other_entry = json.dumps({"commits": ["deadbeef"], "user_facing": False})
        (changes_dir / "0.1.0.jsonl").write_text(other_entry + "\n")

        refs = [(code_sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is not None
        assert "missing coverage" in error.lower()

    def test_combined_unreleased_and_versioned_coverage(self, jsonl_git_repo):
        """Entries split across unreleased and versioned files both contribute."""
        repo = jsonl_git_repo
        base_sha = _git_head(repo)

        # First code commit
        (repo / "src.py").write_text("x = 1\n")
        _run_git(repo, "add", "src.py")
        _run_git(repo, "commit", "-q", "-m", "feat: first feature")
        first_sha = _git_head(repo)

        # Second code commit
        (repo / "src2.py").write_text("y = 2\n")
        _run_git(repo, "add", "src2.py")
        _run_git(repo, "commit", "-q", "-m", "feat: second feature")
        second_sha = _git_head(repo)

        # First commit covered by versioned file, second by unreleased
        changes_dir = repo / ".rlsbl" / "changes"
        versioned_entry = json.dumps({"commits": [first_sha], "user_facing": True,
                                      "description": "first feature", "type": "feature"})
        (changes_dir / "0.1.0.jsonl").write_text(versioned_entry + "\n")

        unreleased_entry = json.dumps({"commits": [second_sha], "user_facing": True,
                                       "description": "second feature", "type": "feature"})
        (changes_dir / "unreleased.jsonl").write_text(unreleased_entry + "\n")

        refs = [(second_sha, base_sha)]
        error = _check_jsonl_changelog(str(repo), refs)
        assert error is None


class TestGitignoreGuardIntegration:
    """Integration test: run_cmd exits 1 when an rlsbl file is gitignored."""

    def test_run_cmd_exits_1_when_gitignored(self, mock_git_repo):
        """run_cmd exits 1 when CHANGELOG.md is gitignored."""
        (mock_git_repo / ".gitignore").write_text("CHANGELOG.md\n")
        _run_git(mock_git_repo, "add", ".gitignore")
        _run_git(mock_git_repo, "commit", "-q", "-m", "add gitignore")

        with pytest.raises(SystemExit) as exc_info:
            run_cmd(None, [], {}, project_root=".")
        assert exc_info.value.code == 1
