"""Tests for monorepo sync command: workflow copying, router generation, cleanup."""

import json
import os
import stat
import subprocess
from unittest.mock import patch

import pytest

from rlsbl.commands.monorepo import (
    _cmd_init,
    _cmd_add,
    _cmd_sync,
    _generate_router,
    _inject_packages_dir,
    _rewrite_trigger,
    _rewrite_version_file_inputs,
    parse_ci_workflow,
    emit_ci_workflow,
)
from rlsbl.workspace import load_workspace, WORKSPACE_DIR, WORKSPACE_FILE


CI_WORKFLOW = """\
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo test
"""

PUBLISH_WORKFLOW = """\
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo publish
"""


def _make_project(base_path, subdir, name=None, ci=True, publish=False):
    """Create a minimal npm project with optional CI and publish workflows."""
    proj_dir = os.path.join(str(base_path), subdir)
    os.makedirs(proj_dir, exist_ok=True)
    pkg_name = name or os.path.basename(subdir)
    with open(os.path.join(proj_dir, "package.json"), "w") as f:
        json.dump({"name": pkg_name, "version": "0.1.0"}, f)

    if ci:
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

    if publish:
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PUBLISH_WORKFLOW)

    return subdir


def _init_workspace_with_projects(base_path, project_specs):
    """Initialize workspace and add projects.

    project_specs: list of (subdir, kwargs_dict) tuples.
    Returns list of project names.
    """
    _cmd_init({})
    names = []
    for subdir, kwargs in project_specs:
        _make_project(base_path, subdir, **kwargs)
        name = kwargs.get("name") or os.path.basename(subdir)
        flags = {}
        if "name" in kwargs:
            flags["name"] = kwargs["name"]
        _cmd_add([subdir], flags)
        names.append(name)
    # Commit the setup so safegit/git can work
    subprocess.run(["git", "add", "."], cwd=str(base_path), check=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", "setup workspace"],
        cwd=str(base_path), check=True,
    )
    return names


class TestWorkflowCopy:
    def test_copies_ci_workflow_to_root(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        assert dest.exists()

    def test_trigger_rewrite(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        content = dest.read_text()
        assert "workflow_call" in content
        assert "push:" not in content
        assert "pull_request:" not in content

    def test_header_comment(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        content = dest.read_text()
        assert "# DO NOT EDIT -- generated by rlsbl monorepo sync" in content
        assert "# Source: tooling/.github/workflows/ci.yml" in content

    def test_read_only_permissions(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "tooling-ci.yml"
        mode = stat.S_IMODE(os.stat(str(dest)).st_mode)
        assert mode == 0o444

    def test_warns_missing_workflow(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": False}),
        ])
        # Auto-scaffold creates CI workflows; remove them to test the missing case
        import shutil
        wf_dir = mock_git_repo / "tooling" / ".github" / "workflows"
        if wf_dir.exists():
            shutil.rmtree(str(wf_dir))
        # Also remove the synced copies at root
        root_wf = mock_git_repo / ".github" / "workflows"
        for f in root_wf.glob("tooling-*"):
            f.chmod(0o644)
            f.unlink()
        _cmd_sync({})
        captured = capsys.readouterr()
        assert "Warning" in captured.err
        assert "tooling" in captured.err


class TestRouterGeneration:
    def test_router_generated(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        assert router.exists()

    def test_router_has_path_filters(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "tooling: 'tooling/**'" in content
        assert "core: 'core/**'" in content

    def test_router_has_conditional_jobs(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "ci-router.yml"
        content = router.read_text()
        assert "needs.detect.outputs.tooling == 'true'" in content
        assert "needs.detect.outputs.core == 'true'" in content
        assert "uses: ./.github/workflows/tooling-ci.yml" in content
        assert "uses: ./.github/workflows/core-ci.yml" in content

    def test_publish_router(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True, "publish": True}),
            ("core", {"ci": True, "publish": True}),
        ])
        _cmd_sync({})
        router = mock_git_repo / ".github" / "workflows" / "publish.yml"
        assert router.exists()
        content = router.read_text()
        # Inline router has inlined jobs with tag prefix conditions
        assert "startsWith(github.event.release.tag_name, 'tooling@v')" in content
        assert "startsWith(github.event.release.tag_name, 'core@v')" in content
        # Jobs are inlined (prefixed job keys), not reusable workflow calls
        assert "tooling-publish:" in content
        assert "core-publish:" in content
        # No per-project publish wrappers should exist
        assert not (mock_git_repo / ".github" / "workflows" / "tooling-publish.yml").exists()
        assert not (mock_git_repo / ".github" / "workflows" / "core-publish.yml").exists()


class TestStaleCleanup:
    def test_removes_stale_workflows(self, mock_git_repo, capsys):
        # Add two projects, sync, then remove one and sync again
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
            ("core", {"ci": True}),
        ])
        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({})
        capsys.readouterr()

        # Verify both exist
        assert (mock_git_repo / ".github" / "workflows" / "tooling-ci.yml").exists()
        assert (mock_git_repo / ".github" / "workflows" / "core-ci.yml").exists()

        # Remove "core" from workspace
        from rlsbl.commands.monorepo import _cmd_remove
        _cmd_remove(["core"], {})
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "remove core"],
            cwd=str(mock_git_repo), check=True,
        )

        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({})

        # "core-ci.yml" should be removed
        assert not (mock_git_repo / ".github" / "workflows" / "core-ci.yml").exists()
        # "tooling-ci.yml" should still exist
        assert (mock_git_repo / ".github" / "workflows" / "tooling-ci.yml").exists()

        # Deletion should be committed -- working tree must be clean
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(mock_git_repo),
            capture_output=True, text=True,
        )
        assert result.stdout.strip() == "", (
            f"Working tree dirty after sync with stale deletion: {result.stdout}"
        )


class TestRewriteTrigger:
    """Unit tests for _rewrite_trigger function (structured YAML)."""

    def test_single_line_trigger(self):
        """Single-line 'on: push' is replaced with workflow_call."""
        doc = parse_ci_workflow("on: push\n\njobs:\n  test:\n")
        _rewrite_trigger(doc)
        result = emit_ci_workflow(doc)
        assert "workflow_call" in result
        assert "push" not in result.split("workflow_call")[0]  # no push before workflow_call

    def test_single_line_array_trigger(self):
        """Single-line 'on: [push, pull_request]' is replaced with workflow_call."""
        doc = parse_ci_workflow("on: [push, pull_request]\n\njobs:\n  test:\n")
        _rewrite_trigger(doc)
        result = emit_ci_workflow(doc)
        assert "workflow_call" in result

    def test_no_on_block(self, capsys):
        """Document without 'on:' is returned unchanged with a warning."""
        doc = parse_ci_workflow("name: CI\njobs:\n  test:\n")
        _rewrite_trigger(doc)
        captured = capsys.readouterr()
        assert "Warning" in captured.err

    def test_multi_line_on_no_jobs(self):
        """Multi-line on: without jobs: returns None from parse_ci_workflow."""
        doc = parse_ci_workflow("on:\n  push:\n    branches: [main]\n")
        # No jobs: key means parse returns None
        assert doc is None

    def test_preserves_intermediate_top_level_keys(self):
        """Rewrite only replaces the on: block, preserving keys between on: and jobs:."""
        content = (
            "name: Publish\n"
            "\n"
            "on:\n"
            "  release:\n"
            "    types: [published]\n"
            "\n"
            "permissions:\n"
            "  contents: read\n"
            "  id-token: write\n"
            "\n"
            "env:\n"
            "  REGISTRY: ghcr.io\n"
            "\n"
            "jobs:\n"
            "  publish:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
        )
        doc = parse_ci_workflow(content)
        _rewrite_trigger(doc)
        result = emit_ci_workflow(doc)
        # on: block replaced with workflow_call
        assert "workflow_call" in result
        assert "release:" not in result
        assert "types:" not in result
        # Intermediate top-level keys preserved
        assert "permissions:" in result
        assert "contents: read" in result
        assert "id-token: write" in result
        assert "REGISTRY: ghcr.io" in result
        # jobs preserved
        assert "publish:" in result
        assert "runs-on: ubuntu-latest" in result


class TestRouterWatchPaths:
    """Tests for watch path support in CI router generation."""

    def test_router_without_watch_paths(self):
        """Projects without watch key use single-line filter format."""
        projects = [
            {"name": "tooling", "path": "tooling"},
            {"name": "core", "path": "core"},
        ]
        content = _generate_router(projects)
        assert "tooling: 'tooling/**'" in content
        assert "core: 'core/**'" in content

    def test_router_with_watch_paths(self):
        """Projects with watch key use multi-line list filter format."""
        projects = [
            {"name": "tooling", "path": "tooling", "watch": ["Package.swift", "shared/**"]},
        ]
        content = _generate_router(projects)
        # The filters block is a literal string inside the YAML; check content
        # without assuming exact outer indentation
        assert "tooling:" in content
        assert "- 'tooling/**'" in content
        assert "- 'Package.swift'" in content
        assert "- 'shared/**'" in content
        # Must NOT have single-line format
        assert "tooling: 'tooling/**'" not in content

    def test_router_mixed_watch_and_no_watch(self):
        """Mixed projects: watch uses multi-line, no-watch uses single-line."""
        projects = [
            {"name": "tooling", "path": "tooling", "watch": ["Package.swift", "shared/**"]},
            {"name": "core", "path": "core"},
        ]
        content = _generate_router(projects)
        # tooling: multi-line (inside literal string filters block)
        assert "tooling:" in content
        assert "- 'tooling/**'" in content
        assert "- 'Package.swift'" in content
        assert "- 'shared/**'" in content
        # core: single-line
        assert "core: 'core/**'" in content


class TestSwiftSubtreeWarning:
    """Tests for the Swift subtree_remote warning in monorepo sync."""

    def test_warns_swift_without_subtree_remote(self, mock_git_repo, capsys):
        """Sync warns when a Swift project lacks subtree_remote."""
        _cmd_init({})
        # Create a Swift project (Package.swift triggers swift target detection)
        proj_dir = os.path.join(str(mock_git_repo), "swiftpkg")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "Package.swift"), "w") as f:
            f.write("// swift-tools-version:5.9\n")
        # Also need a version file for detect_targets
        with open(os.path.join(proj_dir, "VERSION"), "w") as f:
            f.write("0.1.0\n")
        # Create a minimal CI workflow so sync has something to process
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)
        _cmd_add(["swiftpkg"], {})
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup swift project"],
            cwd=str(mock_git_repo), check=True,
        )
        capsys.readouterr()
        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({})
        captured = capsys.readouterr()
        assert "Warning" in captured.err
        assert "swiftpkg" in captured.err
        assert "subtree_remote" in captured.err
        assert "SPM" in captured.err


class TestAutoCommit:
    def test_sync_commits_changes(self, mock_git_repo, capsys):
        _init_workspace_with_projects(mock_git_repo, [
            ("tooling", {"ci": True}),
        ])
        with patch("rlsbl.utils.find_commit_tool", return_value="git"):
            _cmd_sync({})
        # Working tree should be clean after sync
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(mock_git_repo),
            capture_output=True, text=True,
        )
        assert result.stdout.strip() == ""


GO_CI_WORKFLOW = """\
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./...
"""

PYPI_PUBLISH_WORKFLOW = """\
name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
"""

PYPI_PUBLISH_WITH_EXISTING_WITH = """\
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
"""


class TestTrailingSlashStripped:
    """Bug fix: paths like 'python/' should not produce '//' in output."""

    def test_router_no_double_slash(self):
        """Trailing slash in path does not produce // in router glob."""
        projects = [
            {"name": "mypkg", "path": "python/"},
        ]
        content = _generate_router(projects)
        assert "//" not in content
        assert "'python/**'" in content

    def test_router_watch_no_double_slash(self):
        """Trailing slash with watch paths does not produce //."""
        projects = [
            {"name": "mypkg", "path": "python/", "watch": ["shared/**"]},
        ]
        content = _generate_router(projects)
        assert "//" not in content
        assert "'python/**'" in content

    def test_source_comment_no_double_slash(self, mock_git_repo, capsys):
        """Source comment does not contain // from trailing slash."""
        # Create project with trailing-slash path
        proj_dir = os.path.join(str(mock_git_repo), "python")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "package.json"), "w") as f:
            json.dump({"name": "mypkg", "version": "0.1.0"}, f)
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        _cmd_init({})
        # Manually add with trailing-slash path in workspace
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "python/", "name": "mypkg"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "mypkg-ci.yml"
        content = dest.read_text()
        assert "# Source: python/.github/workflows/ci.yml" in content
        assert "python//" not in content
        assert "working-directory: python\n" in content

    def test_working_directory_no_trailing_slash(self, mock_git_repo, capsys):
        """working-directory value should not have a trailing slash."""
        proj_dir = os.path.join(str(mock_git_repo), "lib")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "package.json"), "w") as f:
            json.dump({"name": "mylib", "version": "0.1.0"}, f)
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        _cmd_init({})
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "lib/", "name": "mylib"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "mylib-ci.yml"
        content = dest.read_text()
        assert "working-directory: lib\n" in content
        assert "working-directory: lib/\n" not in content


class TestVersionFileRewrite:
    """Bug fix: action with: inputs for version files must be rewritten."""

    def test_go_version_file_rewritten(self):
        """go-version-file: go.mod becomes go-version-file: myproj/go.mod."""
        doc = parse_ci_workflow(GO_CI_WORKFLOW)
        _rewrite_version_file_inputs(doc, "myproj")
        result = emit_ci_workflow(doc)
        assert "go-version-file: myproj/go.mod" in result
        assert "go-version-file: go.mod" not in result

    def test_already_prefixed_not_doubled(self):
        """If go-version-file already has the project path, don't double it."""
        content = GO_CI_WORKFLOW.replace(
            "go-version-file: go.mod",
            "go-version-file: myproj/go.mod",
        )
        doc = parse_ci_workflow(content)
        _rewrite_version_file_inputs(doc, "myproj")
        result = emit_ci_workflow(doc)
        assert "go-version-file: myproj/go.mod" in result
        assert "myproj/myproj/" not in result

    def test_absolute_path_not_rewritten(self):
        """Absolute paths are left alone."""
        content = GO_CI_WORKFLOW.replace(
            "go-version-file: go.mod",
            "go-version-file: /etc/go.mod",
        )
        doc = parse_ci_workflow(content)
        _rewrite_version_file_inputs(doc, "myproj")
        result = emit_ci_workflow(doc)
        assert "go-version-file: /etc/go.mod" in result

    def test_integration_go_version_file(self, mock_git_repo, capsys):
        """Full sync rewrites go-version-file for a Go project."""
        proj_dir = os.path.join(str(mock_git_repo), "gomod")
        os.makedirs(proj_dir, exist_ok=True)
        # go.mod triggers Go target detection
        with open(os.path.join(proj_dir, "go.mod"), "w") as f:
            f.write("module example.com/gomod\n\ngo 1.21\n")
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(GO_CI_WORKFLOW)

        _cmd_init({})
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "gomod", "name": "gomod"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({})
        dest = mock_git_repo / ".github" / "workflows" / "gomod-ci.yml"
        content = dest.read_text()
        assert "go-version-file: gomod/go.mod" in content
        assert "go-version-file: go.mod" not in content


class TestPackagesDirInjection:
    """Bug fix: pypa/gh-action-pypi-publish needs packages-dir in monorepo."""

    def test_packages_dir_injected_no_with(self):
        """When no with: block exists, one is created with packages-dir."""
        doc = parse_ci_workflow(PYPI_PUBLISH_WORKFLOW)
        _inject_packages_dir(doc, "python")
        result = emit_ci_workflow(doc)
        assert "packages-dir: python/dist/" in result

    def test_packages_dir_injected_existing_with(self):
        """When with: block exists, packages-dir is added to it."""
        doc = parse_ci_workflow(PYPI_PUBLISH_WITH_EXISTING_WITH)
        _inject_packages_dir(doc, "python")
        result = emit_ci_workflow(doc)
        assert "packages-dir: python/dist/" in result
        assert "verbose: true" in result

    def test_packages_dir_not_doubled(self):
        """If packages-dir already present, don't add another."""
        content = PYPI_PUBLISH_WITH_EXISTING_WITH.replace(
            "verbose: true",
            "verbose: true\n          packages-dir: python/dist/",
        )
        doc = parse_ci_workflow(content)
        _inject_packages_dir(doc, "python")
        result = emit_ci_workflow(doc)
        assert result.count("packages-dir") == 1

    def test_integration_pypi_publish(self, mock_git_repo, capsys):
        """Full sync inlines publish jobs with packages-dir for PyPI."""
        proj_dir = os.path.join(str(mock_git_repo), "mypylib")
        os.makedirs(proj_dir, exist_ok=True)
        with open(os.path.join(proj_dir, "pyproject.toml"), "w") as f:
            f.write('[project]\nname = "mypylib"\nversion = "0.1.0"\n')
        wf_dir = os.path.join(proj_dir, ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PYPI_PUBLISH_WORKFLOW)

        _cmd_init({})
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": "mypylib", "name": "mypylib"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({})
        # Per-project publish wrappers no longer exist
        assert not (mock_git_repo / ".github" / "workflows" / "mypylib-publish.yml").exists()
        # packages-dir is in the inline publish router
        router = mock_git_repo / ".github" / "workflows" / "publish.yml"
        content = router.read_text()
        assert "packages-dir: mypylib/dist/" in content


class TestDotPathSelfReference:
    """Bug fix: path='.' must not wrap the generated router as a source workflow."""

    def test_publish_router_not_used_as_source(self, mock_git_repo, capsys):
        """When path='.', the publish router at .github/workflows/publish.yml
        must not be picked up as the project's publish workflow source."""
        # Create a root-level project with CI workflow
        wf_dir = os.path.join(str(mock_git_repo), ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        # Create a real publish workflow that is NOT the router
        with open(os.path.join(wf_dir, "publish.yml"), "w") as f:
            f.write(PUBLISH_WORKFLOW)

        # Also need a package.json at root for target detection
        with open(os.path.join(str(mock_git_repo), "package.json"), "w") as f:
            json.dump({"name": "rootpkg", "version": "0.1.0"}, f)

        _cmd_init({})
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": ".", "name": "rootpkg"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        # First sync: the real publish.yml is used as source for the inline
        # router, which overwrites publish.yml at the same path.
        _cmd_sync({})
        capsys.readouterr()  # discard first sync output

        # Second sync: now publish.yml IS the router. It must be skipped.
        _cmd_sync({})
        captured = capsys.readouterr()

        # The warning should fire for the publish workflow
        assert "router itself" in captured.err
        assert "rootpkg" in captured.err

        # Per-project publish wrappers are never generated in the inline flow
        assert not (mock_git_repo / ".github" / "workflows" / "rootpkg-publish.yml").exists()

    def test_ci_router_not_used_as_source(self, mock_git_repo, capsys):
        """When path='.', the CI router at .github/workflows/ci-router.yml
        is never the source (it's ci-router.yml, not ci.yml), but test
        the path='.' scenario still works for CI."""
        wf_dir = os.path.join(str(mock_git_repo), ".github", "workflows")
        os.makedirs(wf_dir, exist_ok=True)
        with open(os.path.join(wf_dir, "ci.yml"), "w") as f:
            f.write(CI_WORKFLOW)

        with open(os.path.join(str(mock_git_repo), "package.json"), "w") as f:
            json.dump({"name": "rootpkg", "version": "0.1.0"}, f)

        _cmd_init({})
        from rlsbl.workspace import save_workspace
        save_workspace(".", [{"path": ".", "name": "rootpkg"}])
        subprocess.run(["git", "add", "."], cwd=str(mock_git_repo), check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "setup"],
            cwd=str(mock_git_repo), check=True,
        )

        _cmd_sync({})
        # CI workflow should be synced normally (ci.yml != ci-router.yml)
        dest = mock_git_repo / ".github" / "workflows" / "rootpkg-ci.yml"
        assert dest.exists()
        content = dest.read_text()
        assert "workflow_call" in content
