package workflows

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/previewapply"
	"github.com/stricttools/rlsbl/internal/testsupport"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// syncRepository is a committed workspace: core and web with CI, core
// publishing, tools publishing nothing yet keeping a publish workflow, a
// root workflow copy an earlier sync wrote, and web's Python package named
// webapp.
func syncRepository(t *testing.T) *testsupport.Repo {
	t.Helper()
	r := testsupport.NewRepo(t)
	files := publishFixture(map[string]string{
		declarations.ReleasablesFile:          withTools,
		"apps/web/pyproject.toml":             "[project]\nname = \"webapp\"\nversion = \"1.0.0\"\n",
		"apps/web/src/webapp/__init__.py":     "",
		".github/workflows/core-ci.yml":       "jobs: {}\n",
		".github/workflows/core-publish.yml":  "jobs: {}\n",
		".github/workflows/release-notes.yml": "jobs: {}\n",
	})
	var paths []string
	for rel, content := range files {
		r.Write(rel, content)
		paths = append(paths, rel)
	}
	r.Commit("the fixture", paths...)
	return r
}

func syncInputs(autoCommit bool) SyncInputs {
	return SyncInputs{Actions: ActionVersions{"actions/checkout": "v6", "dorny/paths-filter": "v4"}, AutoCommit: autoCommit}
}

func TestSyncWritesTheRoutersRemovesWhatTheyReplacedAndCommits(t *testing.T) {
	hygiene.Isolate(t)
	r := syncRepository(t)
	testsupport.FakeSafegit(t)
	rm := testsupport.FakeSaferm(t)
	w, err := workspace.Load(r.Dir)
	if err != nil {
		t.Fatal(err)
	}
	var result SyncResult
	testsupport.RunEffects(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating, Allowlist: previewapply.Prefixes()}, func(e *strictcli.Effects) error {
		result, err = Sync(e, w, syncInputs(true))
		return err
	})
	if !reflect.DeepEqual(result.ImportNames, []ImportName{{Member: "web", ImportName: "webapp"}}) {
		t.Fatalf("import names: %v", result.ImportNames)
	}
	if !reflect.DeepEqual(result.Written, []string{declarations.ReleasablesFile, declarations.ReleasablesDir + "/manifest.toml", RouterPath, PublishPath}) {
		t.Fatalf("written: %v", result.Written)
	}
	wantRemoved := []string{"tools/.github/workflows/publish.yml", ".github/workflows/core-ci.yml", ".github/workflows/core-publish.yml"}
	if !reflect.DeepEqual(result.Removed, wantRemoved) {
		t.Fatalf("removed: %v", result.Removed)
	}
	calls := strings.Join(rm.Calls(), "\n")
	for _, p := range wantRemoved {
		if !strings.Contains(calls, "-- "+p) {
			t.Fatalf("saferm did not delete %s:\n%s", p, calls)
		}
	}
	if strings.Contains(calls, "release-notes.yml") {
		t.Fatalf("sync removed a workflow it did not write:\n%s", calls)
	}
	if !result.Committed || r.Git("log", "-1", "--format=%s") != SyncCommitMessage {
		t.Fatalf("committed %v, HEAD: %s", result.Committed, r.Git("log", "-1", "--format=%s"))
	}
	if !strings.Contains(r.Git("log", "-1", "--format=%B"), "Autogenerated: true") {
		t.Fatal("sync's commit carries no Autogenerated trailer")
	}
	info, err := os.Stat(filepath.Join(r.Dir, filepath.FromSlash(RouterPath)))
	if err != nil || info.Mode().Perm() != 0o444 {
		t.Fatalf("the router: %v %v", info, err)
	}
	decls, err := os.ReadFile(filepath.Join(r.Dir, filepath.FromSlash(declarations.ReleasablesFile)))
	if err != nil || !strings.Contains(string(decls), `import_name = "webapp"`) {
		t.Fatalf("the declarations:\n%s", decls)
	}

	// Run again: the routers are current, so nothing is written.
	w, err = workspace.Load(r.Dir)
	if err != nil {
		t.Fatal(err)
	}
	testsupport.RunEffects(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating, Allowlist: previewapply.Prefixes()}, func(e *strictcli.Effects) error {
		result, err = Sync(e, w, syncInputs(false))
		return err
	})
	if len(result.Written) != 0 || len(result.ImportNames) != 0 {
		t.Fatalf("a second sync wrote %v, declared %v", result.Written, result.ImportNames)
	}
}

func TestSyncUnderDryRunWritesNothing(t *testing.T) {
	hygiene.Isolate(t)
	r := syncRepository(t)
	testsupport.FakeSafegit(t)
	rm := testsupport.FakeSaferm(t)
	w, err := workspace.Load(r.Dir)
	if err != nil {
		t.Fatal(err)
	}
	res := testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating, DryRun: true, Allowlist: previewapply.Prefixes()}, func(ctx *strictcli.Context) error {
		_, err := Sync(ctx.Effects(), w, syncInputs(true))
		return err
	})
	if res.ExitCode != 0 {
		t.Fatalf("exit %d:\n%s%s", res.ExitCode, res.Stdout, res.Stderr)
	}
	if _, err := os.Stat(filepath.Join(r.Dir, filepath.FromSlash(RouterPath))); !os.IsNotExist(err) {
		t.Fatalf("a dry run wrote the router: %v", err)
	}
	if len(rm.Calls()) != 0 || r.Git("status", "--porcelain") != "" {
		t.Fatalf("a dry run changed something: %v\n%s", rm.Calls(), r.Git("status", "--porcelain"))
	}
}

func TestSyncRefusesAStandaloneRepository(t *testing.T) {
	hygiene.Isolate(t)
	w := fixtureWorkspace(t, `format_version = 1
repository_layout = "standalone"
release_branches = ["main"]

[[releasables]]
name = "gadget"
tag_format = "v{version}"
publish_mode = "none"

[[members]]
path = "."
name = "root"
releasable = "gadget"
`, nil)
	testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating}, func(ctx *strictcli.Context) error {
		if _, err := Sync(ctx.Effects(), w, syncInputs(false)); err == nil || !strings.Contains(err.Error(), "rlsbl scaffold") {
			t.Fatalf("got %v", err)
		}
		return nil
	})
}
