package workflows

import (
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/saferm"
	"github.com/stricttools/rlsbl/internal/targets"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// ImportName is an import_name sync declares for a member: the directory
// name of the Python package its pyproject.toml builds, when that differs
// from the member's name with '-' as '_'.
type ImportName struct {
	Member     string `json:"member"`
	ImportName string `json:"import_name"`
}

// ImportNames are the import_name declarations the workspace lacks: for
// each member declaring none whose directory holds a Python project whose
// package directory is named other than the member's name with '-' as '_'.
func ImportNames(w *workspace.Workspace) ([]ImportName, error) {
	var out []ImportName
	for _, m := range w.Members() {
		if m.ImportName != "" {
			continue
		}
		root, found, err := targets.PythonPackageRoot(w.MemberDir(m))
		if err != nil {
			return nil, fmt.Errorf("the member %q: %w", m.Name, err)
		}
		if !found {
			continue
		}
		detected := path.Base(root)
		if detected != strings.ReplaceAll(m.Name, "-", "_") {
			out = append(out, ImportName{Member: m.Name, ImportName: detected})
		}
	}
	return out, nil
}

// SyncInputs are what sync is run with besides the workspace.
type SyncInputs struct {
	// Actions pins the actions of the generated workflows.
	Actions ActionVersions
	// RootPublishWorkflow renders the root member's publish workflow from
	// scaffold's templates (PublishInputs).
	RootPublishWorkflow func(root declarations.Member) (string, error)
	// AutoCommit commits what sync wrote and removed, with the
	// Autogenerated trailer.
	AutoCommit bool
}

// SyncResult is what sync did. Paths are repository-relative.
type SyncResult struct {
	ImportNames []ImportName `json:"import_names"`
	Written     []string     `json:"written"`
	Removed     []string     `json:"removed"`
	Committed   bool         `json:"committed"`
}

// SyncCommitMessage is the message of sync's commit.
const SyncCommitMessage = "Sync the workspace's CI router and publish router"

// generatedMode is the mode of a generated workflow: read-only, so an edit
// meant for a member's own workflow is not made to the generated one.
const generatedMode = 0o444

// staleCopies are the root workflows earlier versions of sync wrote, one
// per member CI file and publish workflow, which the routers replaced:
// <member>-publish.yml, <member>-ci.yml, and <member>-ci-<x>.yml, for
// declared members only, and never a root member's own CI workflow.
func staleCopies(w *workspace.Workspace) ([]string, error) {
	dir := filepath.Join(w.Root, filepath.FromSlash(Dir))
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	rootSources := map[string]bool{}
	sources, err := CISources(w.Root)
	if err != nil {
		return nil, err
	}
	for _, s := range sources {
		rootSources[filepath.Base(s)] = true
	}
	var stale []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || name == RouterFile || name == PublishFile || rootSources[name] {
			continue
		}
		for _, m := range w.Members() {
			if name == m.Name+"-publish.yml" || name == m.Name+"-ci.yml" || (strings.HasPrefix(name, m.Name+"-ci-") && strings.HasSuffix(name, ".yml")) {
				stale = append(stale, Dir+"/"+name)
				break
			}
		}
	}
	sort.Strings(stale)
	return stale, nil
}

// writeGenerated writes a generated workflow, read-only, unless it already
// holds text with that mode.
func writeGenerated(e *strictcli.Effects, root, rel, text string) (bool, error) {
	abs := filepath.Join(root, filepath.FromSlash(rel))
	info, err := os.Stat(abs)
	switch {
	case err == nil:
		data, err := os.ReadFile(abs)
		if err != nil {
			return false, err
		}
		if string(data) == text && info.Mode().Perm() == generatedMode {
			return false, nil
		}
		// A read-only file cannot be opened for writing.
		if _, err := e.Chmod(abs, 0o644); err != nil {
			return false, fmt.Errorf("making %s writable: %w", rel, err)
		}
	case !errors.Is(err, os.ErrNotExist):
		return false, err
	}
	if _, err := e.Mkdir(filepath.Dir(abs)); err != nil {
		return false, err
	}
	if _, err := e.Write(abs, text, strictcli.Mode(generatedMode)); err != nil {
		return false, fmt.Errorf("writing %s: %w", rel, err)
	}
	return true, nil
}

// generatedOnDisk reports whether rel exists and carries Header.
func generatedOnDisk(root, rel string) (bool, error) {
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return IsGenerated(string(data)), nil
}

// Sync regenerates a workspace's routers: it declares the import_name of
// each member whose Python package directory is named otherwise
// (ImportNames), writes the CI router (CIRouter) and the publish router
// (PublishRouter), removes through saferm a generated router with nothing
// left to route, the publish workflows of members publishing nothing, and
// the root workflow copies earlier versions of sync wrote, and commits all
// of it when asked. Everything is derived before anything is written, so a
// refusal changes nothing.
func Sync(e *strictcli.Effects, w *workspace.Workspace, in SyncInputs) (SyncResult, error) {
	if !w.IsWorkspace() {
		return SyncResult{}, fmt.Errorf("`monorepo sync` generates a workspace's routers, and %s declares a standalone layout; a standalone repository's workflows are rendered by `rlsbl scaffold`", declarations.ReleasablesFile)
	}
	result := SyncResult{}
	names, err := ImportNames(w)
	if err != nil {
		return SyncResult{}, err
	}
	var declared []byte
	if len(names) > 0 {
		data, err := os.ReadFile(filepath.Join(w.Root, filepath.FromSlash(declarations.ReleasablesFile)))
		if err != nil {
			return SyncResult{}, err
		}
		ed, err := declarations.NewEditor(data)
		if err != nil {
			return SyncResult{}, err
		}
		for _, n := range names {
			m, _ := w.Declarations.Member(n.Member)
			if err := ed.SetMemberImportName(m.Path, n.ImportName); err != nil {
				return SyncResult{}, err
			}
		}
		edited, d, err := ed.Result()
		if err != nil {
			return SyncResult{}, err
		}
		if w, err = workspace.New(w.Root, d); err != nil {
			return SyncResult{}, err
		}
		declared = edited
		result.ImportNames = names
	}

	router, routes, err := CIRouter(w, RouterInputs{Actions: in.Actions})
	if err != nil {
		return SyncResult{}, err
	}
	plan, err := PublishRouter(w, PublishInputs{RootPublishWorkflow: in.RootPublishWorkflow})
	if err != nil {
		return SyncResult{}, err
	}
	stale, err := staleCopies(w)
	if err != nil {
		return SyncResult{}, err
	}
	var remove []saferm.Request
	for _, rel := range plan.Suppressed {
		remove = append(remove, saferm.Request{Path: rel, Description: fmt.Sprintf("monorepo sync: %s belongs to a member that publishes nothing, so it must not feed the publish router", rel)})
	}
	for _, generated := range []struct {
		rel   string
		keeps bool
		why   string
	}{
		{RouterPath, routes, "no member has CI of its own left to route"},
		{PublishPath, plan.Text != "", "no member publishes from CI any more"},
	} {
		if generated.keeps {
			continue
		}
		isGenerated, err := generatedOnDisk(w.Root, generated.rel)
		if err != nil {
			return SyncResult{}, err
		}
		if isGenerated {
			remove = append(remove, saferm.Request{Path: generated.rel, Description: "monorepo sync: the generated " + generated.rel + " is left with nothing to do: " + generated.why})
		}
	}
	for _, rel := range stale {
		remove = append(remove, saferm.Request{Path: rel, Description: "monorepo sync: " + rel + " is a per-member workflow copy an earlier sync wrote; the routers inline its jobs"})
	}

	if declared != nil {
		// Writing the declarations creates their directory's manifest when
		// it is missing, and the commit carries it too.
		manifest := declarations.ReleasablesDir + "/manifest.toml"
		_, statErr := os.Stat(filepath.Join(w.Root, filepath.FromSlash(manifest)))
		if statErr != nil && !errors.Is(statErr, os.ErrNotExist) {
			return SyncResult{}, statErr
		}
		if _, err := declarations.Write(e, w.Root, declared); err != nil {
			return SyncResult{}, err
		}
		result.Written = append(result.Written, declarations.ReleasablesFile)
		if statErr != nil {
			result.Written = append(result.Written, manifest)
		}
	}
	for _, out := range []struct {
		rel, text string
	}{{RouterPath, router}, {PublishPath, plan.Text}} {
		if out.text == "" {
			continue
		}
		wrote, err := writeGenerated(e, w.Root, out.rel, out.text)
		if err != nil {
			return SyncResult{}, err
		}
		if wrote {
			result.Written = append(result.Written, out.rel)
		}
	}
	for _, r := range remove {
		if err := saferm.Delete(e, w.Root, r); err != nil {
			return SyncResult{}, err
		}
		result.Removed = append(result.Removed, r.Path)
	}
	changed := append(append([]string(nil), result.Written...), result.Removed...)
	if in.AutoCommit && len(changed) > 0 {
		repo, err := git.Open(e, w.Root)
		if err != nil {
			return SyncResult{}, err
		}
		committed, err := repo.Commit(git.CommitRequest{Message: SyncCommitMessage, Paths: changed, Autogenerated: true})
		if err != nil {
			return result, err
		}
		result.Committed = committed
	}
	return result, nil
}

// Expected are the routers a workspace's committed ones must equal: the CI
// router (empty when nothing routes) and the publish router (empty when no
// member publishes), as sync would write them now. A check comparing the
// committed routers asks this.
func Expected(w *workspace.Workspace, in SyncInputs) (ciRouter, publishRouter string, err error) {
	router, _, err := CIRouter(w, RouterInputs{Actions: in.Actions})
	if err != nil {
		return "", "", err
	}
	plan, err := PublishRouter(w, PublishInputs{RootPublishWorkflow: in.RootPublishWorkflow})
	if err != nil {
		return "", "", err
	}
	return router, plan.Text, nil
}
