// Package workflows generates the GitHub Actions workflows rlsbl owns: a
// workspace's CI router (every member's CI jobs inlined into one
// ci-router.yml, each run only when the push touched what the member's path
// filter covers), a workspace's publish router (every publishing member's
// publish jobs inlined into one publish.yml, each run only for its own
// releasable's tags), the wait-for-ci job that holds every publish until the
// releasing project's CI passed on the release commit, and the jobs that
// package a go binary pipeline's binaries for npm (one platform package per
// platform and the main package selecting them) and for PyPI (one binary
// wheel per platform).
//
// The frame of each generated workflow is rendered from text. Only the jobs
// inlined from a member's own workflow files are re-encoded from the parsed
// YAML, because they are the member's YAML, transformed.
//
// Scaffold renders a standalone repository's publish workflow from its
// templates and takes the wait-for-ci job (WaitForCIJob) and the go binary
// packaging jobs (NPMPackagingJobs, WheelJob) from here.
package workflows

import (
	"fmt"
	"strings"

	"github.com/stricttools/rlsbl/internal/workspace"
)

// The paths GitHub reads workflows from and the files generated there.
const (
	// Dir is where GitHub reads a repository's workflows, relative to the
	// repository root, and where a member keeps its own workflow sources,
	// relative to the member.
	Dir = ".github/workflows"
	// RouterFile is the generated CI router's file name.
	RouterFile = "ci-router.yml"
	// PublishFile is a publish workflow's file name: a member's own, and the
	// generated publish router at a workspace's root.
	PublishFile = "publish.yml"
	// RouterPath is the CI router, repository-relative.
	RouterPath = Dir + "/" + RouterFile
	// PublishPath is the publish router, repository-relative.
	PublishPath = Dir + "/" + PublishFile
)

// Header is the first line of every workflow `rlsbl monorepo sync` writes.
// Its presence separates a generated workflow (regenerated by every sync,
// compared against a fresh rendering) from a hand-written one, which sync
// never reads as a source, never overwrites, and never removes.
const Header = "# DO NOT EDIT -- generated by rlsbl monorepo sync"

// IsGenerated reports whether a workflow's text carries Header on its first
// line.
func IsGenerated(text string) bool {
	first, _, _ := strings.Cut(text, "\n")
	return strings.TrimRight(first, "\r") == Header
}

// WaitForCIJobKey is the key of the job every publish workflow starts with,
// which waits until the releasing project's CI passed on the release commit.
// Every other publish job needs it.
const WaitForCIJobKey = "wait-for-ci"

// RetiredWaitJobKey is the key the publish workflows' waiting job had before
// it was renamed WaitForCIJobKey. A member publish workflow still carrying it
// is refused, naming `rlsbl scaffold`, which renders the current one.
const RetiredWaitJobKey = "gate"

// TagExpression is the release tag a publish run publishes: the tag a retry
// dispatch names, else the ref the release event or the dispatch ran at.
const TagExpression = "${{ inputs.tag || github.ref_name }}"

// TagParts are a tag scheme's text around its version: a tag of the scheme is
// Prefix, the version, then Suffix.
type TagParts struct {
	Prefix string
	Suffix string
}

// Pattern is the scheme's pattern, the version written {version}.
func (t TagParts) Pattern() string { return t.Prefix + "{version}" + t.Suffix }

// Regexp is the extended regular expression matching the scheme's tags and
// no others: the tag matcher's (workspace.TagScheme.Regexp), for a shell
// step to judge a tag with.
func (t TagParts) Regexp() (string, error) {
	s, err := workspace.NewTagScheme(t.Pattern())
	if err != nil {
		return "", err
	}
	return s.Regexp(), nil
}

// TagPartsOf splits a tag scheme's pattern at its {version}.
func TagPartsOf(s workspace.TagScheme) TagParts {
	prefix, suffix, _ := strings.Cut(s.Pattern(), "{version}")
	return TagParts{Prefix: prefix, Suffix: suffix}
}

// shellQuote is s as one single-quoted POSIX shell word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// yamlSingleQuoted is s as a single-quoted YAML scalar.
func yamlSingleQuoted(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// expressionQuoted is s as a string literal inside a GitHub expression.
func expressionQuoted(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// indentBlock prefixes every non-empty line of text with prefix.
func indentBlock(text, prefix string) string {
	lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}

// literalBlock renders text as a YAML literal block scalar's lines, each
// indented by indent; text's own trailing newline ends the block.
func literalBlock(text, indent string) string {
	return indentBlock(text, indent) + "\n"
}

// validJobKey reports whether key is a job id GitHub accepts.
func validJobKey(key string) error {
	if key == "" {
		return fmt.Errorf("a job key is empty")
	}
	for i, r := range key {
		letter := r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
		if i == 0 && !letter {
			return fmt.Errorf("the job key %q must start with a letter or '_'", key)
		}
		if !letter && r != '-' && (r < '0' || r > '9') {
			return fmt.Errorf("the job key %q holds %q; a job key holds letters, digits, '-', and '_'", key, r)
		}
	}
	return nil
}
