// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.5.0
// schema:              rlsbl-releasables (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package releasablesspec

import "github.com/stricttools/strictspec/go/strictspec"

// GENERATED_BY is the strictspec release that produced this file. It is
// INFORMATIONAL: pairing is on GENERATED_CODE_FORMAT below, so a later release
// of the runtime reads this file unchanged, and no tool may derive a dependency
// floor from this string.
const GENERATED_BY = "0.5.0"

// GENERATED_CODE_FORMAT is the shape of generated code this file was written
// to. The runtime pairing guard hard-errors unless this format is one the
// linked runtime reads; the remedy is regeneration.
const GENERATED_CODE_FORMAT = 2

// SCHEMA_FORMAT_VERSION is the document format_version this validator accepts.
const SCHEMA_FORMAT_VERSION = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"releasables.schema.toml": `# strictspec schema for a repository's release declarations,
# .strictmetadata/releasables/releasables.toml.
#
# The generated Go validator (internal/declarations/releasablesspec) is what
# declarations.Parse runs first, so a document that reaches the typed decode
# and the declaration rules has already been through here.
#
# SCOPE: this schema owns the document's shape -- every key at every level,
# each value's type, the closed value sets, and the uniqueness of names inside
# one list. The rules that relate one part of the document to another (the
# root member, a member naming a declared releasable, a pipeline naming a
# target its member declares, the layout's member count) are checked by
# internal/declarations after this schema passes.

name = "rlsbl-releasables"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "Releasables"
description = "A repository's release declarations: its layout, release branches, timeouts, releasables, and members with their targets, pipelines, hooks, and checks."

[types.Releasables]
type = "record"

[types.Releasables.fields.format_version]
type = "literal"
value = 1
required = true
description = "The document's format version."

[types.Releasables.fields.repository_layout]
type = "enum"
required = true
values = ["standalone", "workspace"]
description = "Whether the repository is one standalone project or a workspace of members; never derived from the member count."

[types.Releasables.fields.release_branches]
type = "array"
required = true
min_len = 1
description = "The branches a release may run from."
[types.Releasables.fields.release_branches.item]
type = "string"
non_empty = true

[types.Releasables.fields.github_repository]
type = "string"
required = false
regex = "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"
description = "The GitHub repository as owner/name; absent means the origin remote names it."

[types.Releasables.fields.environment_file]
type = "string"
required = false
non_empty = true
description = "A KEY=VALUE file loaded into the release's environment."

[types.Releasables.fields.timeouts]
type = "Timeouts"
required = false
description = "The release's timeouts, in seconds."

[types.Releasables.fields.releasables]
type = "array"
required = true
description = "The units of versioning: each has one version, one changelog, and one tag scheme."
[types.Releasables.fields.releasables.item]
type = "Releasable"

[types.Releasables.fields.members]
type = "array"
required = true
min_len = 1
description = "The directories of the repository rlsbl knows, each owning the files under its path that no deeper member claims."
[types.Releasables.fields.members.item]
type = "Member"

[[types.Releasables.constraints]]
form = "unique-by"
collection = "releasables"
field = "name"
normalization = "none"

[[types.Releasables.constraints]]
form = "unique-by"
collection = "members"
field = "path"
normalization = "none"

[[types.Releasables.constraints]]
form = "unique-by"
collection = "members"
field = "name"
normalization = "none"

[types.Timeouts]
type = "record"

[types.Timeouts.fields.push_seconds]
type = "integer"
required = false
min = 1
description = "How long a push may take; absent means the shipped push timeout."

[types.Timeouts.fields.ci_seconds]
type = "integer"
required = false
min = 1
description = "How long CI may take; absent means the shipped CI timeout."

[types.Timeouts.fields.check_seconds]
type = "integer"
required = false
min = 1
description = "How long a check may take; absent means the shipped check timeout."

[types.Timeouts.fields.hook_seconds]
type = "integer"
required = false
min = 1
description = "How long a hook may take; absent means hooks run with no timeout."

[types.Releasable]
type = "record"

[types.Releasable.fields.name]
type = "string"
required = true
non_empty = true
description = "The releasable's name, recorded and never derived."

[types.Releasable.fields.tag_format]
type = "string"
required = true
non_empty = true
description = "The releasable's tag format: one {version} placeholder, and optionally {name}."

[types.Releasable.fields.publish_mode]
type = "enum"
required = true
values = ["ci", "none"]
description = "ci publishes from CI; none publishes nothing."

[types.Releasable.fields.publish_ci_check_pattern]
type = "string"
required = false
non_empty = true
description = "The pattern of the check-run names the root's own CI reports, which publishing waits for; declared only by the releasable owning the root member of a workspace that publishes from CI."

[types.Releasable.fields.deploy_command]
type = "array"
required = false
min_len = 1
description = "The command a release runs to deploy the releasable after tagging, {version} replaced by the released version."
[types.Releasable.fields.deploy_command.item]
type = "string"
non_empty = true

[types.Releasable.fields.hooks]
type = "Hooks"
required = false
description = "Commands the release runs at its hook points for the releasable as a whole."

[types.Hooks]
type = "record"

[types.Hooks.fields.pre_checks]
type = "array"
required = false
description = "Run before the checks."
[types.Hooks.fields.pre_checks.item]
type = "HookEntry"

[types.Hooks.fields.pre_release]
type = "array"
required = false
description = "Run before the release commit; declaring one replaces the built-in tests."
[types.Hooks.fields.pre_release.item]
type = "HookEntry"

[types.Hooks.fields.post_release]
type = "array"
required = false
description = "Run after the release."
[types.Hooks.fields.post_release.item]
type = "HookEntry"

[types.HookEntry]
type = "node-kind-union"
description = "A shell command line, or a table naming the command, the directory it runs in, and extra environment."
[types.HookEntry.arms.string]
type = "string"
non_empty = true
[types.HookEntry.arms.record]
type = "HookCommand"

[types.HookCommand]
type = "record"

[types.HookCommand.fields.cmd]
type = "string"
required = true
non_empty = true
description = "The shell command line."

[types.HookCommand.fields.dir]
type = "string"
required = false
non_empty = true
description = "The directory it runs in, relative to the declaring member."

[types.HookCommand.fields.env]
type = "map"
required = false
key_pattern = "^[A-Za-z_][A-Za-z0-9_]*$"
description = "Environment variables added for the command."
[types.HookCommand.fields.env.value]
type = "string"

[types.Member]
type = "record"

[types.Member.fields.path]
type = "string"
required = true
non_empty = true
description = "The member's directory, repository-relative; the root member's is \".\"."

[types.Member.fields.name]
type = "string"
required = true
non_empty = true
description = "The member's name; the root member's is \"root\"."

[types.Member.fields.releasable]
type = "MemberReleasable"
required = true
description = "The releasable the member is versioned under, or false."

[types.Member.fields.dev_only]
type = "boolean"
required = false
description = "The member is development tooling."

[types.Member.fields.library]
type = "boolean"
required = false
description = "The member is a library."

[types.Member.fields.test_only]
type = "boolean"
required = false
description = "The member is test infrastructure."

[types.Member.fields.depends_on]
type = "array"
required = false
description = "Members this member depends on beyond what its manifests say."
[types.Member.fields.depends_on.item]
type = "string"
non_empty = true

[types.Member.fields.import_name]
type = "string"
required = false
non_empty = true
description = "The name the member's code is imported by."

[types.Member.fields.registry_name]
type = "string"
required = false
non_empty = true
description = "The name the member is published under."

[types.Member.fields.description]
type = "string"
required = false
non_empty = true
description = "What the member is."

[types.Member.fields.lint_allow]
type = "array"
required = false
description = "Imports strictcode allows this member."
[types.Member.fields.lint_allow.item]
type = "string"
non_empty = true

[types.Member.fields.internal_dep_floors]
type = "array"
required = false
description = "Dependencies whose version floors rlsbl:dep-floors keeps current."
[types.Member.fields.internal_dep_floors.item]
type = "string"
non_empty = true

[types.Member.fields.targets]
type = "array"
required = false
min_len = 1
description = "The member's release targets; absent means they are detected from its manifests."
[types.Member.fields.targets.item]
type = "Target"

[types.Member.fields.hooks]
type = "Hooks"
required = false
description = "Commands the release runs at its hook points for this member."

[types.Member.fields.external_checks]
type = "array"
required = false
description = "Checks the member declares, each a shell command."
[types.Member.fields.external_checks.item]
type = "ExternalCheck"

[types.Member.fields.test]
type = "TestSettings"
required = false
description = "How the built-in tests run for this member."

[types.Member.fields.pipelines]
type = "array"
required = false
description = "The member's publish pipelines."
[types.Member.fields.pipelines.item]
type = "Pipeline"

[[types.Member.constraints]]
form = "unique-by"
collection = "pipelines"
field = "name"
normalization = "none"

[[types.Member.constraints]]
form = "unique-by"
collection = "targets"
field = "name"
normalization = "none"

[types.MemberReleasable]
type = "node-kind-union"
description = "A releasable's name, or false for a member versioned under none."
[types.MemberReleasable.arms.string]
type = "string"
non_empty = true
[types.MemberReleasable.arms.boolean]
type = "literal"
value = false

[types.Target]
type = "record"

[types.Target.fields.name]
type = "enum"
required = true
values = ["go", "npm", "pypi"]
description = "The target."

[types.Target.fields.path]
type = "string"
required = false
non_empty = true
description = "The target's directory relative to the member; absent means the member's own."

[types.ExternalCheck]
type = "record"

[types.ExternalCheck.fields.name]
type = "string"
required = true
regex = "^[a-z][a-z0-9-]*$"
description = "The check's name."

[types.ExternalCheck.fields.tag]
type = "string"
required = true
non_empty = true
description = "The tag the check runs under."

[types.ExternalCheck.fields.command]
type = "string"
required = true
non_empty = true
description = "The shell command line the check runs."

[types.ExternalCheck.fields.depends_on]
type = "array"
required = false
description = "Checks that must pass first."
[types.ExternalCheck.fields.depends_on.item]
type = "string"
non_empty = true

[types.ExternalCheck.fields.cwd]
type = "string"
required = false
non_empty = true
description = "The directory the command runs in, relative to the member."

[types.TestSettings]
type = "record"

[types.TestSettings.fields.pypi_markers]
type = "string"
required = false
non_empty = true
description = "The pytest marker expression the pypi target's tests run with."

[types.TestSettings.fields.go_command]
type = "string"
required = false
non_empty = true
description = "The command the go target's tests run instead of go test."

[types.Pipeline]
type = "record"

[types.Pipeline.fields.name]
type = "string"
required = true
regex = "^[A-Za-z0-9_-]+$"
description = "The pipeline's name."

[types.Pipeline.fields.type]
type = "enum"
required = true
values = ["go", "npm", "pypi"]
description = "The pipeline type."

[types.Pipeline.fields.target]
type = "enum"
required = true
values = ["go", "npm", "pypi"]
description = "The target the pipeline publishes, one the member declares."

[types.Pipeline.fields.local]
type = "boolean"
required = true
description = "Whether the pipeline publishes from this machine instead of CI."

[types.Pipeline.fields.artifact]
type = "enum"
required = true
values = ["binary", "library", "package", "go-binary"]
description = "What the pipeline publishes: go binary or library; npm and pypi package or go-binary."

[types.Pipeline.fields.install_paths]
type = "array"
required = false
min_len = 1
description = "A go pipeline's main packages; required when local is true."
[types.Pipeline.fields.install_paths.item]
type = "string"
non_empty = true

[types.Pipeline.fields.homebrew_tap]
type = "string"
required = false
non_empty = true
description = "The Homebrew tap a go binary pipeline publishes to."

[types.Pipeline.fields.binary_pipeline]
type = "string"
required = false
non_empty = true
description = "The go binary pipeline an npm or pypi go-binary pipeline wraps."
`,
}

const embeddedMainFile = "releasables.schema.toml"

var program *strictspec.Program

func init() {
	// Pairing: this file's generated-code format must be one the runtime reads.
	strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Releasables, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindReleasables(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Releasables, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindReleasables(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Releasables, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindReleasables(v), nil
}

// Releasables is the frozen typed binding of the "Releasables" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Releasables struct {
	FormatVersion    int64
	RepositoryLayout string
	ReleaseBranches  []string
	GithubRepository string
	EnvironmentFile  string
	Timeouts         *Timeouts
	Releasables      []*Releasable
	Members          []*Member
}

func bindReleasables(v strictspec.Value) *Releasables {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Releasables{}
	if fv, ok := v.Field("format_version"); ok {
		out.FormatVersion = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("repository_layout"); ok {
		out.RepositoryLayout = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("release_branches"); ok {
		out.ReleaseBranches = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("github_repository"); ok {
		out.GithubRepository = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("environment_file"); ok {
		out.EnvironmentFile = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("timeouts"); ok {
		out.Timeouts = bindTimeouts(fv)
	}
	if fv, ok := v.Field("releasables"); ok {
		out.Releasables = bindSlice(fv, func(e strictspec.Value) *Releasable { return bindReleasable(e) })
	}
	if fv, ok := v.Field("members"); ok {
		out.Members = bindSlice(fv, func(e strictspec.Value) *Member { return bindMember(e) })
	}
	return out
}

// WithFormatVersion returns a copy of Releasables with FormatVersion set to the given value.
func (x *Releasables) WithFormatVersion(v int64) *Releasables {
	c := *x
	c.FormatVersion = v
	return &c
}

// WithRepositoryLayout returns a copy of Releasables with RepositoryLayout set to the given value.
func (x *Releasables) WithRepositoryLayout(v string) *Releasables {
	c := *x
	c.RepositoryLayout = v
	return &c
}

// WithReleaseBranches returns a copy of Releasables with ReleaseBranches set to the given value.
func (x *Releasables) WithReleaseBranches(v []string) *Releasables {
	c := *x
	c.ReleaseBranches = v
	return &c
}

// WithGithubRepository returns a copy of Releasables with GithubRepository set to the given value.
func (x *Releasables) WithGithubRepository(v string) *Releasables {
	c := *x
	c.GithubRepository = v
	return &c
}

// WithEnvironmentFile returns a copy of Releasables with EnvironmentFile set to the given value.
func (x *Releasables) WithEnvironmentFile(v string) *Releasables {
	c := *x
	c.EnvironmentFile = v
	return &c
}

// WithTimeouts returns a copy of Releasables with Timeouts set to the given value.
func (x *Releasables) WithTimeouts(v *Timeouts) *Releasables {
	c := *x
	c.Timeouts = v
	return &c
}

// WithReleasables returns a copy of Releasables with Releasables set to the given value.
func (x *Releasables) WithReleasables(v []*Releasable) *Releasables {
	c := *x
	c.Releasables = v
	return &c
}

// WithMembers returns a copy of Releasables with Members set to the given value.
func (x *Releasables) WithMembers(v []*Member) *Releasables {
	c := *x
	c.Members = v
	return &c
}

// Timeouts is the frozen typed binding of the "Timeouts" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Timeouts struct {
	PushSeconds  int64
	CiSeconds    int64
	CheckSeconds int64
	HookSeconds  int64
}

func bindTimeouts(v strictspec.Value) *Timeouts {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Timeouts{}
	if fv, ok := v.Field("push_seconds"); ok {
		out.PushSeconds = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("ci_seconds"); ok {
		out.CiSeconds = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("check_seconds"); ok {
		out.CheckSeconds = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("hook_seconds"); ok {
		out.HookSeconds = func() int64 { r, _ := fv.Int(); return r }()
	}
	return out
}

// WithPushSeconds returns a copy of Timeouts with PushSeconds set to the given value.
func (x *Timeouts) WithPushSeconds(v int64) *Timeouts {
	c := *x
	c.PushSeconds = v
	return &c
}

// WithCiSeconds returns a copy of Timeouts with CiSeconds set to the given value.
func (x *Timeouts) WithCiSeconds(v int64) *Timeouts {
	c := *x
	c.CiSeconds = v
	return &c
}

// WithCheckSeconds returns a copy of Timeouts with CheckSeconds set to the given value.
func (x *Timeouts) WithCheckSeconds(v int64) *Timeouts {
	c := *x
	c.CheckSeconds = v
	return &c
}

// WithHookSeconds returns a copy of Timeouts with HookSeconds set to the given value.
func (x *Timeouts) WithHookSeconds(v int64) *Timeouts {
	c := *x
	c.HookSeconds = v
	return &c
}

// Releasable is the frozen typed binding of the "Releasable" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Releasable struct {
	Name                  string
	TagFormat             string
	PublishMode           string
	PublishCiCheckPattern string
	DeployCommand         []string
	Hooks                 *Hooks
}

func bindReleasable(v strictspec.Value) *Releasable {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Releasable{}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("tag_format"); ok {
		out.TagFormat = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("publish_mode"); ok {
		out.PublishMode = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("publish_ci_check_pattern"); ok {
		out.PublishCiCheckPattern = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("deploy_command"); ok {
		out.DeployCommand = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("hooks"); ok {
		out.Hooks = bindHooks(fv)
	}
	return out
}

// WithName returns a copy of Releasable with Name set to the given value.
func (x *Releasable) WithName(v string) *Releasable {
	c := *x
	c.Name = v
	return &c
}

// WithTagFormat returns a copy of Releasable with TagFormat set to the given value.
func (x *Releasable) WithTagFormat(v string) *Releasable {
	c := *x
	c.TagFormat = v
	return &c
}

// WithPublishMode returns a copy of Releasable with PublishMode set to the given value.
func (x *Releasable) WithPublishMode(v string) *Releasable {
	c := *x
	c.PublishMode = v
	return &c
}

// WithPublishCiCheckPattern returns a copy of Releasable with PublishCiCheckPattern set to the given value.
func (x *Releasable) WithPublishCiCheckPattern(v string) *Releasable {
	c := *x
	c.PublishCiCheckPattern = v
	return &c
}

// WithDeployCommand returns a copy of Releasable with DeployCommand set to the given value.
func (x *Releasable) WithDeployCommand(v []string) *Releasable {
	c := *x
	c.DeployCommand = v
	return &c
}

// WithHooks returns a copy of Releasable with Hooks set to the given value.
func (x *Releasable) WithHooks(v *Hooks) *Releasable {
	c := *x
	c.Hooks = v
	return &c
}

// Hooks is the frozen typed binding of the "Hooks" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Hooks struct {
	PreChecks   []strictspec.Value
	PreRelease  []strictspec.Value
	PostRelease []strictspec.Value
}

func bindHooks(v strictspec.Value) *Hooks {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Hooks{}
	if fv, ok := v.Field("pre_checks"); ok {
		out.PreChecks = bindSlice(fv, func(e strictspec.Value) strictspec.Value { return e })
	}
	if fv, ok := v.Field("pre_release"); ok {
		out.PreRelease = bindSlice(fv, func(e strictspec.Value) strictspec.Value { return e })
	}
	if fv, ok := v.Field("post_release"); ok {
		out.PostRelease = bindSlice(fv, func(e strictspec.Value) strictspec.Value { return e })
	}
	return out
}

// WithPreChecks returns a copy of Hooks with PreChecks set to the given value.
func (x *Hooks) WithPreChecks(v []strictspec.Value) *Hooks {
	c := *x
	c.PreChecks = v
	return &c
}

// WithPreRelease returns a copy of Hooks with PreRelease set to the given value.
func (x *Hooks) WithPreRelease(v []strictspec.Value) *Hooks {
	c := *x
	c.PreRelease = v
	return &c
}

// WithPostRelease returns a copy of Hooks with PostRelease set to the given value.
func (x *Hooks) WithPostRelease(v []strictspec.Value) *Hooks {
	c := *x
	c.PostRelease = v
	return &c
}

// HookCommand is the frozen typed binding of the "HookCommand" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type HookCommand struct {
	Cmd string
	Dir string
	Env strictspec.Value
}

func bindHookCommand(v strictspec.Value) *HookCommand {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &HookCommand{}
	if fv, ok := v.Field("cmd"); ok {
		out.Cmd = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("dir"); ok {
		out.Dir = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("env"); ok {
		out.Env = fv
	}
	return out
}

// WithCmd returns a copy of HookCommand with Cmd set to the given value.
func (x *HookCommand) WithCmd(v string) *HookCommand {
	c := *x
	c.Cmd = v
	return &c
}

// WithDir returns a copy of HookCommand with Dir set to the given value.
func (x *HookCommand) WithDir(v string) *HookCommand {
	c := *x
	c.Dir = v
	return &c
}

// WithEnv returns a copy of HookCommand with Env set to the given value.
func (x *HookCommand) WithEnv(v strictspec.Value) *HookCommand {
	c := *x
	c.Env = v
	return &c
}

// Member is the frozen typed binding of the "Member" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Member struct {
	Path              string
	Name              string
	Releasable        strictspec.Value
	DevOnly           bool
	Library           bool
	TestOnly          bool
	DependsOn         []string
	ImportName        string
	RegistryName      string
	Description       string
	LintAllow         []string
	InternalDepFloors []string
	Targets           []*Target
	Hooks             *Hooks
	ExternalChecks    []*ExternalCheck
	Test              *TestSettings
	Pipelines         []*Pipeline
}

func bindMember(v strictspec.Value) *Member {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Member{}
	if fv, ok := v.Field("path"); ok {
		out.Path = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("releasable"); ok {
		out.Releasable = fv
	}
	if fv, ok := v.Field("dev_only"); ok {
		out.DevOnly = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("library"); ok {
		out.Library = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("test_only"); ok {
		out.TestOnly = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("depends_on"); ok {
		out.DependsOn = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("import_name"); ok {
		out.ImportName = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("registry_name"); ok {
		out.RegistryName = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("lint_allow"); ok {
		out.LintAllow = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("internal_dep_floors"); ok {
		out.InternalDepFloors = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("targets"); ok {
		out.Targets = bindSlice(fv, func(e strictspec.Value) *Target { return bindTarget(e) })
	}
	if fv, ok := v.Field("hooks"); ok {
		out.Hooks = bindHooks(fv)
	}
	if fv, ok := v.Field("external_checks"); ok {
		out.ExternalChecks = bindSlice(fv, func(e strictspec.Value) *ExternalCheck { return bindExternalCheck(e) })
	}
	if fv, ok := v.Field("test"); ok {
		out.Test = bindTestSettings(fv)
	}
	if fv, ok := v.Field("pipelines"); ok {
		out.Pipelines = bindSlice(fv, func(e strictspec.Value) *Pipeline { return bindPipeline(e) })
	}
	return out
}

// WithPath returns a copy of Member with Path set to the given value.
func (x *Member) WithPath(v string) *Member {
	c := *x
	c.Path = v
	return &c
}

// WithName returns a copy of Member with Name set to the given value.
func (x *Member) WithName(v string) *Member {
	c := *x
	c.Name = v
	return &c
}

// WithReleasable returns a copy of Member with Releasable set to the given value.
func (x *Member) WithReleasable(v strictspec.Value) *Member {
	c := *x
	c.Releasable = v
	return &c
}

// WithDevOnly returns a copy of Member with DevOnly set to the given value.
func (x *Member) WithDevOnly(v bool) *Member {
	c := *x
	c.DevOnly = v
	return &c
}

// WithLibrary returns a copy of Member with Library set to the given value.
func (x *Member) WithLibrary(v bool) *Member {
	c := *x
	c.Library = v
	return &c
}

// WithTestOnly returns a copy of Member with TestOnly set to the given value.
func (x *Member) WithTestOnly(v bool) *Member {
	c := *x
	c.TestOnly = v
	return &c
}

// WithDependsOn returns a copy of Member with DependsOn set to the given value.
func (x *Member) WithDependsOn(v []string) *Member {
	c := *x
	c.DependsOn = v
	return &c
}

// WithImportName returns a copy of Member with ImportName set to the given value.
func (x *Member) WithImportName(v string) *Member {
	c := *x
	c.ImportName = v
	return &c
}

// WithRegistryName returns a copy of Member with RegistryName set to the given value.
func (x *Member) WithRegistryName(v string) *Member {
	c := *x
	c.RegistryName = v
	return &c
}

// WithDescription returns a copy of Member with Description set to the given value.
func (x *Member) WithDescription(v string) *Member {
	c := *x
	c.Description = v
	return &c
}

// WithLintAllow returns a copy of Member with LintAllow set to the given value.
func (x *Member) WithLintAllow(v []string) *Member {
	c := *x
	c.LintAllow = v
	return &c
}

// WithInternalDepFloors returns a copy of Member with InternalDepFloors set to the given value.
func (x *Member) WithInternalDepFloors(v []string) *Member {
	c := *x
	c.InternalDepFloors = v
	return &c
}

// WithTargets returns a copy of Member with Targets set to the given value.
func (x *Member) WithTargets(v []*Target) *Member {
	c := *x
	c.Targets = v
	return &c
}

// WithHooks returns a copy of Member with Hooks set to the given value.
func (x *Member) WithHooks(v *Hooks) *Member {
	c := *x
	c.Hooks = v
	return &c
}

// WithExternalChecks returns a copy of Member with ExternalChecks set to the given value.
func (x *Member) WithExternalChecks(v []*ExternalCheck) *Member {
	c := *x
	c.ExternalChecks = v
	return &c
}

// WithTest returns a copy of Member with Test set to the given value.
func (x *Member) WithTest(v *TestSettings) *Member {
	c := *x
	c.Test = v
	return &c
}

// WithPipelines returns a copy of Member with Pipelines set to the given value.
func (x *Member) WithPipelines(v []*Pipeline) *Member {
	c := *x
	c.Pipelines = v
	return &c
}

// Target is the frozen typed binding of the "Target" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Target struct {
	Name string
	Path string
}

func bindTarget(v strictspec.Value) *Target {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Target{}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("path"); ok {
		out.Path = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithName returns a copy of Target with Name set to the given value.
func (x *Target) WithName(v string) *Target {
	c := *x
	c.Name = v
	return &c
}

// WithPath returns a copy of Target with Path set to the given value.
func (x *Target) WithPath(v string) *Target {
	c := *x
	c.Path = v
	return &c
}

// ExternalCheck is the frozen typed binding of the "ExternalCheck" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type ExternalCheck struct {
	Name      string
	Tag       string
	Command   string
	DependsOn []string
	Cwd       string
}

func bindExternalCheck(v strictspec.Value) *ExternalCheck {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &ExternalCheck{}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("tag"); ok {
		out.Tag = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("command"); ok {
		out.Command = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("depends_on"); ok {
		out.DependsOn = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("cwd"); ok {
		out.Cwd = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithName returns a copy of ExternalCheck with Name set to the given value.
func (x *ExternalCheck) WithName(v string) *ExternalCheck {
	c := *x
	c.Name = v
	return &c
}

// WithTag returns a copy of ExternalCheck with Tag set to the given value.
func (x *ExternalCheck) WithTag(v string) *ExternalCheck {
	c := *x
	c.Tag = v
	return &c
}

// WithCommand returns a copy of ExternalCheck with Command set to the given value.
func (x *ExternalCheck) WithCommand(v string) *ExternalCheck {
	c := *x
	c.Command = v
	return &c
}

// WithDependsOn returns a copy of ExternalCheck with DependsOn set to the given value.
func (x *ExternalCheck) WithDependsOn(v []string) *ExternalCheck {
	c := *x
	c.DependsOn = v
	return &c
}

// WithCwd returns a copy of ExternalCheck with Cwd set to the given value.
func (x *ExternalCheck) WithCwd(v string) *ExternalCheck {
	c := *x
	c.Cwd = v
	return &c
}

// TestSettings is the frozen typed binding of the "TestSettings" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type TestSettings struct {
	PypiMarkers string
	GoCommand   string
}

func bindTestSettings(v strictspec.Value) *TestSettings {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &TestSettings{}
	if fv, ok := v.Field("pypi_markers"); ok {
		out.PypiMarkers = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("go_command"); ok {
		out.GoCommand = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithPypiMarkers returns a copy of TestSettings with PypiMarkers set to the given value.
func (x *TestSettings) WithPypiMarkers(v string) *TestSettings {
	c := *x
	c.PypiMarkers = v
	return &c
}

// WithGoCommand returns a copy of TestSettings with GoCommand set to the given value.
func (x *TestSettings) WithGoCommand(v string) *TestSettings {
	c := *x
	c.GoCommand = v
	return &c
}

// Pipeline is the frozen typed binding of the "Pipeline" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Pipeline struct {
	Name           string
	Type           string
	Target         string
	Local          bool
	Artifact       string
	InstallPaths   []string
	HomebrewTap    string
	BinaryPipeline string
}

func bindPipeline(v strictspec.Value) *Pipeline {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Pipeline{}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("type"); ok {
		out.Type = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("target"); ok {
		out.Target = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("local"); ok {
		out.Local = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("artifact"); ok {
		out.Artifact = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("install_paths"); ok {
		out.InstallPaths = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("homebrew_tap"); ok {
		out.HomebrewTap = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("binary_pipeline"); ok {
		out.BinaryPipeline = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithName returns a copy of Pipeline with Name set to the given value.
func (x *Pipeline) WithName(v string) *Pipeline {
	c := *x
	c.Name = v
	return &c
}

// WithType returns a copy of Pipeline with Type set to the given value.
func (x *Pipeline) WithType(v string) *Pipeline {
	c := *x
	c.Type = v
	return &c
}

// WithTarget returns a copy of Pipeline with Target set to the given value.
func (x *Pipeline) WithTarget(v string) *Pipeline {
	c := *x
	c.Target = v
	return &c
}

// WithLocal returns a copy of Pipeline with Local set to the given value.
func (x *Pipeline) WithLocal(v bool) *Pipeline {
	c := *x
	c.Local = v
	return &c
}

// WithArtifact returns a copy of Pipeline with Artifact set to the given value.
func (x *Pipeline) WithArtifact(v string) *Pipeline {
	c := *x
	c.Artifact = v
	return &c
}

// WithInstallPaths returns a copy of Pipeline with InstallPaths set to the given value.
func (x *Pipeline) WithInstallPaths(v []string) *Pipeline {
	c := *x
	c.InstallPaths = v
	return &c
}

// WithHomebrewTap returns a copy of Pipeline with HomebrewTap set to the given value.
func (x *Pipeline) WithHomebrewTap(v string) *Pipeline {
	c := *x
	c.HomebrewTap = v
	return &c
}

// WithBinaryPipeline returns a copy of Pipeline with BinaryPipeline set to the given value.
func (x *Pipeline) WithBinaryPipeline(v string) *Pipeline {
	c := *x
	c.BinaryPipeline = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
