package checks

import (
	"strings"
	"testing"

	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

// unreleased is the portal changelog's unreleased file.
const unreleased = ".strictmetadata/changelog/portal/unreleased.jsonl"

// releasedPortal is portal released as 1.0.0 at its first commit (tagged,
// with its archive), plus one more commit, which is unreleased.
func releasedPortal(t *testing.T) (r *testsupport.Repo, released, next string) {
	t.Helper()
	r = portalRepo(t, "none", nil)
	released = r.Head()
	r.Git("tag", "v1.0.0", released)
	writeArchive(t, r, "portal", "1.0.0", released, map[string]string{".": strings.Repeat("e", 40)})
	next = r.CommitFile("main.go", "package main\n\nfunc main() {}\n", "Add the entry point")
	return r, released, next
}

func TestChangelogChecksSkipAMemberVersionedUnderNoReleasable(t *testing.T) {
	hygiene.Isolate(t)
	r := workspaceRepo(t)
	r.Write("docs/README.md", "docs\n")
	for _, name := range []string{"changelog-hashes", "changelog-coverage", "changelog-schema", "changelog-user-facing"} {
		got := runCheck(t, inputs(t, r.Path("docs")), name)
		mustStatus(t, got, "skip")
		mustMention(t, got, "versioned under no releasable")
	}
}

func TestALineOfAnotherFormatVersionIsNamedUntilMigrated(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	r.Write(unreleased, `{"commits":["`+next+`"],"user_facing":false}`+"\n")
	got := runCheck(t, inputs(t, r.Dir), "changelog-format-version")
	mustStatus(t, got, "fail")
	mustMention(t, got, "rlsbl migrate records")
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-schema"), "pass")
	unanswered := runCheck(t, inputs(t, r.Dir), "changelog-coverage")
	if !strings.Contains(unanswered.Unanswered, "changelog-format-version") {
		t.Errorf("coverage over an unreadable changelog did not refuse: %s", unanswered)
	}
	// What the migration writes: the line at format version 2.
	r.Write(unreleased, entryLine("1", next))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-format-version"), "pass")
}

func TestASchemaProblemIsNamedBySchemaAlone(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	r.Write(unreleased, `{"format_version":2,"id":"`+entryID("1")+`","commits":["`+next+`"],"user_facing":true}`+"\n")
	got := runCheck(t, inputs(t, r.Dir), "changelog-schema")
	mustStatus(t, got, "fail")
	mustMention(t, got, "line 1 of "+unreleased)
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-format-version"), "pass")
}

func TestChangelogEntryLooksForTheCurrentVersionsSection(t *testing.T) {
	hygiene.Isolate(t)
	r, _, _ := releasedPortal(t)
	got := runCheck(t, inputs(t, r.Dir), "changelog-entry")
	mustStatus(t, got, "fail")
	mustMention(t, got, "rlsbl changelog generate")
	r.Write("CHANGELOG.md", "# Changelog\n\n## 0.9.0\n\n- Earlier\n")
	got = runCheck(t, inputs(t, r.Dir), "changelog-entry")
	mustStatus(t, got, "warn")
	mustMention(t, got, "no section for 1.0.0")
	r.Write("CHANGELOG.md", "# Changelog\n\n## 1.0.0\n\n- First release\n")
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-entry"), "pass")
}

func TestAnUnresolvableHashFails(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	r.Write(unreleased, entryLine("1", next, strings.Repeat("d", 40)))
	got := runCheck(t, inputs(t, r.Dir), "changelog-hashes")
	mustStatus(t, got, "fail")
	mustMention(t, got, strings.Repeat("d", 40))
	r.Write(unreleased, entryLine("1", next))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-hashes"), "pass")
}

func TestACommitOfAnEarlierReleaseIsOutOfRange(t *testing.T) {
	hygiene.Isolate(t)
	r, released, next := releasedPortal(t)
	r.Write(unreleased, entryLine("1", next)+entryLine("2", released))
	got := runCheck(t, inputs(t, r.Dir), "changelog-range")
	mustStatus(t, got, "fail")
	mustMention(t, got, released, "not in the unreleased range")
	r.Write(unreleased, entryLine("1", next))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-range"), "pass")
}

func TestAnUncoveredCommitFailsUntilAnEntryDescribesIt(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	got := runCheck(t, inputs(t, r.Dir), "changelog-coverage")
	mustStatus(t, got, "fail")
	mustMention(t, got, next[:12], "rlsbl changelog add --commits")
	// What `rlsbl changelog add --commits <next>` writes.
	r.Write(unreleased, entryLine("1", next))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-coverage"), "pass")
}

func TestAnAutogeneratedCommitNeedsNoEntry(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	r.Write("generated.txt", "made by a tool\n")
	r.Git("add", "generated.txt")
	r.Git("commit", "-q", "-m", "Regenerate", "--trailer", "Autogenerated: true")
	r.Write(unreleased, entryLine("1", next))
	got := runCheck(t, inputs(t, r.Dir), "changelog-coverage")
	mustStatus(t, got, "pass")
	mustMention(t, got, "skipped 1 autogenerated commit(s)")
}

func TestAnEntryWhoseEveryCommitIsStaleIsAnOrphan(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	stale := entryLine("2", strings.Repeat("a", 40))
	r.Write(unreleased, entryLine("1", next)+stale)
	got := runCheck(t, inputs(t, r.Dir), "changelog-orphans")
	mustStatus(t, got, "fail")
	mustMention(t, got, "rlsbl changelog remap", "rlsbl changelog remove --id "+entryID("2"))
	// The removal the finding names.
	r.Write(unreleased, entryLine("1", next))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-orphans"), "pass")
}

func TestUserFacingWarnsWhenNoEntryIs(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	internal := changelog.Serialize(changelog.Entry{ID: entryID("1"), Commits: []string{next}}) + "\n"
	r.Write(unreleased, internal)
	got := runCheck(t, inputs(t, r.Dir), "changelog-user-facing")
	mustStatus(t, got, "warn")
	mustMention(t, got, `bump = "infra"`)
	r.Write(unreleased, internal+entryLine("2", next))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-user-facing"), "pass")
}

func TestAnEntryOverTheCommitLimitNeedsABatchReason(t *testing.T) {
	hygiene.Isolate(t)
	r, _, _ := releasedPortal(t)
	var commits []string
	for _, c := range "abcdef" {
		commits = append(commits, strings.Repeat(string(c), 40))
	}
	r.Write(unreleased, entryLine("1", commits...))
	got := runCheck(t, inputs(t, r.Dir), "changelog-batch-commits")
	mustStatus(t, got, "fail")
	mustMention(t, got, "--batch-reason")
	// What `rlsbl changelog add --batch-reason` writes.
	e := changelog.Entry{ID: entryID("1"), Commits: commits, UserFacing: true, Description: "one change", Type: changelog.TypeFeature, BatchReason: "one rename across six commits"}
	r.Write(unreleased, changelog.Serialize(e)+"\n")
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-batch-commits"), "pass")
}

func TestACommitInTooManyEntriesFails(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	var lines string
	for _, n := range []string{"1", "2", "3", "4", "5", "6"} {
		lines += entryLine(n, next)
	}
	r.Write(unreleased, lines)
	got := runCheck(t, inputs(t, r.Dir), "changelog-batch-entries")
	mustStatus(t, got, "fail")
	mustMention(t, got, next[:12], "merge the entries")
}

// After a declassification every changelog entry of a squashed proprietary
// period names the one squash commit, so the batch checks leave out a
// commit a committed history-rewrite archive records as a declassification's
// squash commit; a scrub's archive exempts nothing.
func TestTheBatchChecksLeaveOutADeclassificationsSquashCommit(t *testing.T) {
	hygiene.Isolate(t)
	r, _, next := releasedPortal(t)
	var lines string
	for _, n := range []string{"1", "2", "3", "4", "5", "6"} {
		lines += entryLine(n, next)
	}
	r.Write(unreleased, lines)
	archive := func(operation, squash string) string {
		return "format_version = 1\noperation = \"" + operation + "\"\nmode = \"squash\"\nreason = \"public\"\nold_head = \"" + strings.Repeat("a", 40) + "\"\nnew_head = \"" + next + "\"\ncommits_rewritten = 6\n" + squash + "\n[rewrites]\n\"" + strings.Repeat("a", 40) + "\" = \"" + next + "\"\n"
	}
	r.Write(".strictmetadata/history-rewrites/20260101T000000Z.toml", archive("scrub", ""))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-batch-entries"), "fail")
	r.Write(".strictmetadata/history-rewrites/20260101T000000Z.toml", archive("declassify", "squash_commits = [\""+next+"\"]\n"))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-batch-entries"), "pass")

	var commits []string
	for _, c := range "bcdef" {
		commits = append(commits, strings.Repeat(string(c), 40))
	}
	r.Write(unreleased, entryLine("1", append(commits, next)...))
	mustStatus(t, runCheck(t, inputs(t, r.Dir), "changelog-batch-commits"), "pass")
}
