package releaseops

import (
	"fmt"
	"sort"
	"strings"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/releaserecord"
	"github.com/stricttools/rlsbl/internal/runstate"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/targets"
)

// AbandonInvocation is the command line every refusal naming the abandon
// prints, stated once so the refusals cannot drift from it.
const AbandonInvocation = "rlsbl release abandon --approve-consequential"

// abandonHeader is the comment block of an archive `release abandon`
// writes.
var abandonHeader = []string{
	"Written by `rlsbl release abandon`: a release attempt claimed this version",
	"number and was abandoned before the step that records a release, so no",
	"release was ever published under it. The release bumps from it when the",
	"version files name it, and never releases under it again. bump is derived",
	"by version arithmetic against the latest release.",
}

// AbandonInstruction is the sentence every refusal over an unrecorded attempt
// prints to name the abandon.
func AbandonInstruction(v semver.Version) string {
	return fmt.Sprintf("To abandon %s instead, run `%s`: it records %s as never released and deletes the in-progress state file. The attempt's commits stay where they are, and the next release bumps from %s when the version files name it.", v, AbandonInvocation, v, v)
}

// LeftoverStateInstruction is the way out of an in-progress state file whose
// version the record already holds as never released.
func LeftoverStateInstruction(v semver.Version, archive, state string) string {
	return fmt.Sprintf("%s is recorded as never released (%s), so this in-progress state file is left over from an attempt that was already abandoned. Run `%s`, which finishes that abandon and deletes the file: %s", v, archive, AbandonInvocation, state)
}

// AbandonRequest is a `release abandon`.
type AbandonRequest struct {
	// Dir is the working directory, absolute.
	Dir string
}

// Abandon records an abandoned release attempt's version as never
// released: it writes the version's archive with never_released = true,
// commits it with the Autogenerated trailer, and deletes the in-progress
// state file. The version comes from the in-progress state, or from the
// version files when there is none. The attempt's commits are not reverted:
// the next release bumps from the abandoned version when the version files
// name it, and never releases under it.
//
// A state file naming a version already recorded never released is an
// earlier abandon that stopped part-way, and this one finishes it. Every
// other state that is not an unrecorded attempt is refused before anything
// is written: nothing to abandon, a version already archived as a release,
// a version below the latest release, the attempt's tag here or on origin
// (a tag is evidence of a release, which the backfill adopts), and a GitHub
// Release under the attempt's tag (a published release, which undo
// reverts). A question that cannot be answered is refused, never read as
// absence.
func Abandon(ctx *strictcli.Context, req AbandonRequest) (err error) {
	e := ctx.Effects()
	s, err := Select(e, req.Dir)
	if err != nil {
		return err
	}
	l, err := lock(ctx, s.Root())
	if err != nil {
		return err
	}
	defer unlock(l, &err)
	statePath := runstate.InProgressPath(s.Releasable.Name)
	state, inProgress, err := runstate.LoadInProgress(s.Root(), s.Releasable.Name)
	if err != nil {
		return fmt.Errorf("the in-progress release state could not be read: %w\n  Nothing was changed: which version the attempt claimed is unknown", err)
	}
	var v semver.Version
	if inProgress {
		if v, err = semver.Parse(state.Version); err != nil {
			return fmt.Errorf("the in-progress release state %s names the version %q: %w. Nothing was changed: which version the attempt claimed is unknown", statePath, state.Version, err)
		}
	} else if v, err = versionFilesVersion(s); err != nil {
		return err
	}
	archive := releaserecord.ArchivePath(s.Record.Dir(), v)
	fate, err := s.Record.Fate(v)
	if err != nil {
		return err
	}
	if inProgress && fate == releaserecord.FateNeverReleased {
		return finishAbandon(ctx, s, v, archive, statePath)
	}
	if !inProgress && fate != releaserecord.FateAbsent {
		held := "released"
		if fate == releaserecord.FateNeverReleased {
			held = "never released"
		}
		return fmt.Errorf("there is nothing to abandon: no release is in progress (%s does not exist), and the version files name %s, which the release record already holds as %s: %s. Nothing was changed", statePath, v, held, archive)
	}
	if fate != releaserecord.FateAbsent {
		return fmt.Errorf("%s is already archived, as a release: %s. Abandoning writes that archive, so there is nothing left for it to record. Nothing was changed", v, archive)
	}
	latest, released, err := s.latestReleased()
	if err != nil {
		return err
	}
	if released && semver.Compare(v, latest) < 0 {
		if inProgress {
			return fmt.Errorf("%s\n  The state file: %s", releaserecord.BehindLatestText(v, latest, "the in-progress release state names"), statePath)
		}
		return fmt.Errorf("%s\n  Set the version files to %s: they then name the latest release, and there is no abandoned version for them to name", releaserecord.BehindLatestText(v, latest, "the version files say"), latest)
	}
	tag := s.Scheme.Render(v)
	if inProgress && state.Tag != "" {
		tag = state.Tag
	}
	if err := refuseTagEvidence(ctx, s, v, tag, archive); err != nil {
		return err
	}
	bump := derivedBump(v, latest, released)
	spec := releaserecord.ArchiveSpec{
		ReleaseFile: releaserecord.ReleaseFile{
			Bump:        bump,
			Include:     []string{},
			Exclude:     []string{},
			Description: fmt.Sprintf("Abandoned release attempt: %s was never released.", v),
		},
		Fate:   releaserecord.FateNeverReleased,
		Header: abandonHeader,
	}
	if _, err := releaserecord.WriteArchive(e, s.Root(), s.Record.Dir(), v, spec); err != nil {
		return err
	}
	if err := commit(ctx, s, fmt.Sprintf("Record %s as never released (abandoned release attempt)", v), []string{archive}, true); err != nil {
		return fmt.Errorf("%s was written and committing it failed: %w. Commit it, then run `%s` again to delete the in-progress state", archive, err, AbandonInvocation)
	}
	if inProgress {
		if err := runstate.ClearInProgress(e, s.Root(), s.Releasable.Name); err != nil {
			return err
		}
	}
	verb, deleted := "Recorded", "Deleted"
	if ctx.DryRun() {
		verb, deleted = "Would record", "Would delete"
	}
	lines := []string{fmt.Sprintf("%s %s as never released: %s", verb, v, archive)}
	if inProgress {
		lines = append(lines, fmt.Sprintf("%s the in-progress release state: %s", deleted, statePath))
	}
	lines = append(lines, fmt.Sprintf("The next release bumps from %s when the version files name it, and never releases under %s.", v, v))
	ctx.Out(strings.Join(lines, "\n"))
	return nil
}

// finishAbandon completes an earlier abandon of v that wrote its archive
// and stopped before committing it or before deleting the state file.
func finishAbandon(ctx *strictcli.Context, s Selection, v semver.Version, archive, statePath string) error {
	changed, err := s.Repo.ChangedPaths([]string{archive}, git.UntrackedAll)
	if err != nil {
		return err
	}
	if len(changed) > 0 {
		if err := commit(ctx, s, fmt.Sprintf("Record %s as never released (abandoned release attempt)", v), []string{archive}, true); err != nil {
			return err
		}
	}
	if err := runstate.ClearInProgress(ctx.Effects(), s.Root(), s.Releasable.Name); err != nil {
		return err
	}
	verb, committed, deleted := "completed", "Committed", "Deleted"
	if ctx.DryRun() {
		verb, committed, deleted = "would complete", "Would commit", "Would delete"
	}
	lines := []string{fmt.Sprintf("This run %s the earlier abandon of %s: the release record already holds %s as never released (%s).", verb, v, v, archive)}
	if len(changed) > 0 {
		lines = append(lines, committed+" that archive, which the earlier run had not committed.")
	}
	lines = append(lines, fmt.Sprintf("%s the in-progress release state: %s", deleted, statePath))
	ctx.Out(strings.Join(lines, "\n"))
	return nil
}

// refuseTagEvidence refuses to abandon v while its tag exists here or on
// origin (evidence of a release, which the backfill adopts) or a GitHub
// Release stands under it (a published release, which undo reverts).
func refuseTagEvidence(ctx *strictcli.Context, s Selection, v semver.Version, tag, archive string) error {
	backfill := []string{
		"    rlsbl release backfill --dry-run",
		"    rlsbl release backfill --approve-consequential",
	}
	if _, found, err := s.Repo.TagCommit(tag); err != nil {
		return err
	} else if found {
		return fmt.Errorf("the attempt's tag %s exists in this repository.\n  The release record holds no archive for %s (%s), and a tag is evidence of a release, so %s is not recorded as never released. Nothing was changed.\n  Record the release the tag is evidence of: `rlsbl release backfill` adopts a version tag no archive records as released, from the commit it names. Preview first, then write:\n%s", tag, v, archive, v, strings.Join(backfill, "\n"))
	}
	remote, err := s.Repo.RemoteConfigured(origin)
	if err != nil {
		return err
	}
	if remote {
		at, found, err := s.Repo.RemoteTagCommit(origin, tag)
		if err != nil {
			return fmt.Errorf("whether the attempt's tag %s exists on origin cannot be told: %w\n  Nothing was changed. Resolve the remote access problem, then run the abandon again", tag, err)
		}
		if found {
			return fmt.Errorf("the attempt's tag %s exists on origin at %s.\n  The release record holds no archive for %s (%s), and a tag is evidence of a release, so %s is not recorded as never released. Nothing was changed.\n  Fetch the tag, then record the release it is evidence of: `rlsbl release backfill` adopts a version tag no archive records as released, from the commit it names. Preview first, then write:\n    git fetch origin tag %s\n%s", tag, at, v, archive, v, tag, strings.Join(backfill, "\n"))
		}
	}
	gh, slug, err := openGitHub(ctx.Effects(), s)
	if err != nil {
		return fmt.Errorf("whether a GitHub Release exists for %s cannot be told: %w\n  Nothing was changed", tag, err)
	}
	exists, err := gh.ReleaseExists(slug, tag)
	if err != nil {
		return fmt.Errorf("whether a GitHub Release exists for %s cannot be told: %w\n  Nothing was changed. Resolve the GitHub access problem, then run the abandon again", tag, err)
	}
	if exists {
		return fmt.Errorf("a GitHub Release exists for the attempt's tag %s.\n  That is a published release, and `rlsbl release undo` reverts it. Nothing was changed", tag)
	}
	return nil
}

// versionFilesVersion is the version the releasable's version files name:
// a workspace releasable's version file, or a standalone project's target
// manifests, which must agree.
func versionFilesVersion(s Selection) (semver.Version, error) {
	if s.Workspace.IsWorkspace() {
		return s.Workspace.ReadReleasableVersion(s.Releasable.Name)
	}
	versions := map[string]string{}
	for _, m := range s.Workspace.MembersOf(s.Releasable.Name) {
		ts, err := targets.MemberTargets(s.Root(), m)
		if err != nil {
			return semver.Version{}, err
		}
		for _, t := range ts {
			target, err := targets.Get(t.Name)
			if err != nil {
				return semver.Version{}, err
			}
			v, err := target.ReadVersion(s.abs(m.TargetDir(t)))
			if err != nil {
				return semver.Version{}, err
			}
			versions[t.Name+" ("+m.TargetDir(t)+")"] = v.String()
		}
	}
	distinct := map[string]bool{}
	for _, v := range versions {
		distinct[v] = true
	}
	switch len(distinct) {
	case 0:
		return semver.Version{}, fmt.Errorf("%s declares no release target, so no version file names a version to abandon", s.Releasable.Name)
	case 1:
		for v := range distinct {
			return semver.Parse(v)
		}
	}
	var lines []string
	for name, v := range versions {
		lines = append(lines, "  "+name+": "+v)
	}
	sort.Strings(lines)
	return semver.Version{}, fmt.Errorf("the version files disagree, so which version to abandon is not decided:\n%s\n  Nothing was changed. Make them agree, then run the abandon again", strings.Join(lines, "\n"))
}

// derivedBump is the bump from the latest release to v by version
// arithmetic: the highest-order component that differs names it, its size
// never read. Without a latest release v is measured against 0.0.0.
func derivedBump(v, latest semver.Version, released bool) semver.Bump {
	if !released {
		latest = semver.Version{}
	}
	switch {
	case v.Major != latest.Major:
		return semver.Major
	case v.Minor != latest.Minor:
		return semver.Minor
	}
	return semver.Patch
}
