package releaseops_test

import (
	"os"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle/index"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/releaseops"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestTheNoticeWording(t *testing.T) {
	hygiene.Isolate(t)
	use, err := semver.Parse("0.5.0")
	if err != nil {
		t.Fatal(err)
	}
	cases := []struct {
		reason string
		use    *semver.Version
		want   string
	}{
		{"", nil, "> **Deprecated.**"},
		{"Broken parser", nil, "> **Deprecated:** Broken parser."},
		{"Broken parser.", nil, "> **Deprecated:** Broken parser."},
		{"", &use, "> **Deprecated:** Use v0.5.0 instead."},
		{"Broken parser", &use, "> **Deprecated:** Broken parser. Use v0.5.0 instead."},
	}
	for _, c := range cases {
		if got := releaseops.Notice("Deprecated", c.reason, c.use); got != c.want {
			t.Errorf("Notice(%q, %v) = %q, want %q", c.reason, c.use, got, c.want)
		}
	}
}

// portalWithTwoReleases is portal with 0.3.0 and 0.4.0 released.
func portalWithTwoReleases(t *testing.T) *project {
	t.Helper()
	p := newPortal(t, "package.json")
	p.release("portal", "0.3.0")
	p.release("portal", "0.4.0")
	return p
}

func deprecate(t *testing.T, p *project, dryRun bool, req releaseops.NoticeRequest) strictcli.Result {
	t.Helper()
	req.Dir, req.IndexPath = p.Dir, p.indexPath
	return run(t, nil, dryRun, func(ctx *strictcli.Context) error { return releaseops.Deprecate(ctx, req) })
}

func TestDeprecateRecordsTheNoticeBeforeRewritingTheRelease(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	safegit := testsupport.FakeSafegit(t)
	gh := testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	r := deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0", Reason: "Broken parser", Use: "0.4.0"})
	requireExit(t, r, 0)
	notice := "> **Deprecated:** Broken parser. Use v0.4.0 instead."
	requireContains(t, p.read(".strictmetadata/releases/portal/v0.3.0.toml"), "release_notices", "Broken parser. Use v0.4.0 instead.")
	if got := p.subjects(1)[0]; got != "release: deprecate v0.3.0" {
		t.Fatalf("the last commit is %q", got)
	}
	requireContains(t, p.Git("log", "-1", "--format=%B"), "Autogenerated: true")
	if len(safegit.Calls()) != 1 {
		t.Fatalf("safegit calls %q", safegit.Calls())
	}
	edit, ok := called(gh.Calls(), rewriteArgs("v0.3.0", true))
	if !ok {
		t.Fatalf("the Release was not rewritten: %+v", gh.Calls())
	}
	if !strings.HasPrefix(edit.Stdin, notice+"\n\n") || !strings.Contains(edit.Stdin, "shipped in 0.3.0") || !strings.Contains(edit.Stdin, "rlsbl-ci-sha") {
		t.Fatalf("the Release body is %q", edit.Stdin)
	}
}

func TestARunAfterAnInterruptedDeprecateRecordsTheNoticeOnce(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	testsupport.FakeSafegit(t)
	testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	req := releaseops.NoticeRequest{Version: "0.3.0", Reason: "Broken parser"}
	requireExit(t, deprecate(t, p, false, req), 0)
	head := p.Head()
	requireExit(t, deprecate(t, p, false, req), 0)
	if p.Head() != head {
		t.Fatal("the second run recorded the notice again")
	}
	if n := strings.Count(p.read(".strictmetadata/releases/portal/v0.3.0.toml"), "Broken parser"); n != 1 {
		t.Fatalf("the archive holds the notice %d times", n)
	}
}

func TestDeprecateAndYankMarkTheLatestRelease(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	testsupport.FakeSafegit(t)
	gh := testsupport.FakeGH(t, authStatus, releaseExists("v0.4.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.4.0", true)})
	requireExit(t, deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.4.0", Reason: "Abandoned", Use: "0.3.0"}), 0)
	if _, ok := called(gh.Calls(), rewriteArgs("v0.4.0", true)); !ok {
		t.Fatalf("the latest Release was not rewritten: %+v", gh.Calls())
	}
	npm := fakeNpm(t)
	fake := testsupport.NewFakeHTTP(t, npmDocument("0.3.0", "0.4.0"))
	requireExit(t, yank(t, p, fake, false, releaseops.NoticeRequest{Version: "0.4.0", Reason: "Abandoned"}), 0)
	if calls := npm(); len(calls) != 1 || calls[0] != "deprecate portal@0.4.0 Abandoned" {
		t.Fatalf("npm calls %q", calls)
	}
	requireContains(t, p.read(".strictmetadata/releases/portal/v0.4.0.toml"), "**Deprecated:** Abandoned. Use v0.3.0 instead.", "**Yanked:** Abandoned.")
}

func TestDeprecateRefusesAVersionWithoutAReleaseUntilItExists(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	testsupport.FakeSafegit(t)
	testsupport.FakeGH(t, authStatus, releaseMissing("v0.3.0"))
	r := deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0"})
	requireExit(t, r, 1)
	requireContains(t, r.Stderr, "has no GitHub Release for v0.3.0", "rlsbl release reconcile")
	// What reconcile does: create the Release the record holds.
	testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	requireExit(t, deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0"}), 0)
}

func TestDeprecateRefusesAVersionWithoutAnArchiveUntilItIsBackfilled(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	testsupport.FakeSafegit(t)
	testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	archive := ".strictmetadata/releases/portal/v0.3.0.toml"
	content := p.read(archive)
	p.Git("rm", "-q", archive)
	p.Git("commit", "-q", "-m", "lose the archive")
	r := deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0"})
	requireExit(t, r, 1)
	requireContains(t, r.Stderr, "has no release archive", "rlsbl release backfill")
	// What the backfill writes: the archive recording the release.
	p.Write(archive, content)
	p.Commit("backfill", archive)
	requireExit(t, deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0"}), 0)
}

func TestAVersionWithALeadingVIsRefusedNamingTheBareOne(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	testsupport.FakeSafegit(t)
	testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	r := deprecate(t, p, false, releaseops.NoticeRequest{Version: "v0.3.0"})
	requireExit(t, r, 1)
	requireContains(t, r.Stderr, `carries a leading "v"`, "0.3.0")
	requireExit(t, deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0"}), 0)
}

func TestUseMustNameAReleasedVersion(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	testsupport.FakeSafegit(t)
	testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	r := deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0", Use: "0.9.0"})
	requireExit(t, r, 1)
	requireContains(t, r.Stderr, "--use names 0.9.0", "name a released version")
	requireExit(t, deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0", Use: "0.4.0"}), 0)
}

func TestADryRunDeprecateWritesNothing(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	safegit := testsupport.FakeSafegit(t)
	gh := testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"))
	archive := ".strictmetadata/releases/portal/v0.3.0.toml"
	before, head := p.read(archive), p.Head()
	r := deprecate(t, p, true, releaseops.NoticeRequest{Version: "0.3.0", Reason: "Broken"})
	requireExit(t, r, 0)
	requireContains(t, r.Stdout, "Would mark v0.3.0 pre-release")
	if p.read(archive) != before || p.Head() != head || len(safegit.Calls()) != 0 {
		t.Fatal("a dry run wrote or committed")
	}
	if _, ok := called(gh.Calls(), rewriteArgs("v0.3.0", true)); ok {
		t.Fatal("a dry run rewrote the Release")
	}
}

// diskWriter performs the index's writes, for a fixture.
type diskWriter struct{}

func (diskWriter) WriteFile(path string, data []byte) error { return os.WriteFile(path, data, 0o644) }
func (diskWriter) MkdirAll(path string) error               { return os.MkdirAll(path, 0o755) }

func TestANoticeNamingAConfidentialNameIsRefusedBeforeAnythingIsWritten(t *testing.T) {
	hygiene.Isolate(t)
	p := portalWithTwoReleases(t)
	idx, err := index.Load(p.indexPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := idx.Upsert(diskWriter{}, []string{"gadget"}, []string{"moonbeam"}); err != nil {
		t.Fatal(err)
	}
	testsupport.FakeSafegit(t)
	gh := testsupport.FakeGH(t, authStatus, releaseExists("v0.3.0"), testsupport.GHAnswer{Args: rewriteArgs("v0.3.0", true)})
	head := p.Head()
	r := deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0", Reason: "Moonbeam replaces it"})
	requireExit(t, r, 1)
	requireContains(t, r.Stderr, "confidential", "the GitHub Release body of v0.3.0", `"moonbeam"`)
	if p.Head() != head || strings.Contains(p.read(".strictmetadata/releases/portal/v0.3.0.toml"), "Moonbeam") {
		t.Fatal("a refused notice was recorded")
	}
	if _, ok := called(gh.Calls(), rewriteArgs("v0.3.0", true)); ok {
		t.Fatal("a refused notice rewrote the Release")
	}
	// The fix the refusal names: the name removed from the text.
	requireExit(t, deprecate(t, p, false, releaseops.NoticeRequest{Version: "0.3.0", Reason: "A successor replaces it"}), 0)
}
