"""Known pre-push hook content hashes used to safely regenerate `.git/hooks/pre-push` only when its current content matches a previously-shipped rlsbl version, never overwriting user customizations.

rlsbl installs a `.git/hooks/pre-push` hook in scaffolded projects. The hook
content has changed over time (older versions were 44-line standalone bash
scripts; the current version captures push stdin and delegates to
`rlsbl check --tag prepush`).

To safely upgrade an old hook without clobbering a user-customized one, we
compare its content hash against the set of every hook version rlsbl has
shipped. If it matches one of ours, we overwrite. If not, we leave it alone
and show the user a diff so they can decide what to do.
"""

import hashlib


CURRENT_PRE_PUSH_HOOK = '#!/usr/bin/env bash\nexport RLSBL_PUSH_STDIN="$(cat)"\nexec rlsbl check --tag prepush\n'


# Historical pre-push hook contents. These are the literal bytes rlsbl
# has shipped at one point or another, preserved here so we can recognise
# them on disk in old projects and upgrade safely. Whitespace at the very
# end of the file is stripped before hashing (see compute_hook_hash) so
# minor editor reformatting (e.g. adding a trailing newline) is tolerated.
#
# Version 1: original 44-line script, no VERSION file support.
# Recovered from git commit 291b066 (templates/shared/pre-push-hook.sh.tpl).
_PRE_PUSH_HOOK_V1 = """#!/usr/bin/env bash
# Pre-push hook: verify CHANGELOG.md has an entry for the current version.
# Install: cp scripts/pre-push-hook.sh .git/hooks/pre-push && chmod +x .git/hooks/pre-push

set -euo pipefail

# Detect project type and extract version
if [ -f package.json ]; then
  VERSION=$(node -e "console.log(require('./package.json').version)" 2>/dev/null) || exit 0
elif [ -f pyproject.toml ]; then
  VERSION=$(grep -m1 '^version' pyproject.toml | sed 's/.*"\\(.*\\)".*/\\1/') || exit 0
else
  exit 0
fi

if [ -z "$VERSION" ]; then
  exit 0
fi

# Check CHANGELOG.md has an entry for this version
if [ ! -f CHANGELOG.md ]; then
  echo "Warning: CHANGELOG.md not found."
  exit 0
fi

if ! grep -q "^## $VERSION" CHANGELOG.md; then
  echo "Error: CHANGELOG.md has no entry for version $VERSION."
  echo "Add a '## $VERSION' section before pushing."
  exit 1
fi

# Check scaffolding freshness
if [ -f .rlsbl/version ]; then
  SCAFFOLD_VER=$(cat .rlsbl/version | tr -d '[:space:]')
  if command -v rlsbl &>/dev/null; then
    CURRENT_VER=$(rlsbl --version 2>/dev/null | tr -d '[:space:]')
    if [ -n "$CURRENT_VER" ] && [ "$SCAFFOLD_VER" != "$CURRENT_VER" ]; then
      echo "Warning: scaffolding was generated by rlsbl $SCAFFOLD_VER but you have $CURRENT_VER installed."
      echo "Run 'rlsbl scaffold' to update scaffolding."
    fi
  fi
fi
"""

# Version 2: added VERSION file detection for Go-style projects.
# Recovered from git commit 86f720f.
_PRE_PUSH_HOOK_V2 = """#!/usr/bin/env bash
# Pre-push hook: verify CHANGELOG.md has an entry for the current version.
# Install: cp scripts/pre-push-hook.sh .git/hooks/pre-push && chmod +x .git/hooks/pre-push

set -euo pipefail

# Detect project type and extract version
if [ -f package.json ]; then
  VERSION=$(node -e "console.log(require('./package.json').version)" 2>/dev/null) || exit 0
elif [ -f pyproject.toml ]; then
  VERSION=$(grep -m1 '^version' pyproject.toml | sed 's/.*"\\(.*\\)".*/\\1/') || exit 0
elif [ -f VERSION ]; then
  VERSION=$(tr -d '[:space:]' < VERSION) || exit 0
else
  exit 0
fi

if [ -z "$VERSION" ]; then
  exit 0
fi

# Check CHANGELOG.md has an entry for this version
if [ ! -f CHANGELOG.md ]; then
  echo "Warning: CHANGELOG.md not found."
  exit 0
fi

if ! grep -q "^## $VERSION" CHANGELOG.md; then
  echo "Error: CHANGELOG.md has no entry for version $VERSION."
  echo "Add a '## $VERSION' section before pushing."
  exit 1
fi

# Check scaffolding freshness
if [ -f .rlsbl/version ]; then
  SCAFFOLD_VER=$(cat .rlsbl/version | tr -d '[:space:]')
  if command -v rlsbl &>/dev/null; then
    CURRENT_VER=$(rlsbl --version 2>/dev/null | tr -d '[:space:]')
    if [ -n "$CURRENT_VER" ] && [ "$SCAFFOLD_VER" != "$CURRENT_VER" ]; then
      echo "Warning: scaffolding was generated by rlsbl $SCAFFOLD_VER but you have $CURRENT_VER installed."
      echo "Run 'rlsbl scaffold' to update scaffolding."
    fi
  fi
fi
"""

# Version 3: two-line dispatcher that incorrectly forwards "$@" to rlsbl
# (strictcli rejects extra positional args). Inlined in init_cmd.py only --
# never lived as a standalone template file. Reconstructed from
# todo/fix-pre-push-hook-args.md.
_PRE_PUSH_HOOK_V3 = '#!/usr/bin/env bash\nexec rlsbl pre-push-check "$@"\n'

# Version 4: two-line dispatcher without "$@".
_PRE_PUSH_HOOK_V4 = '#!/usr/bin/env bash\nexec rlsbl pre-push-check\n'

# Version 5 (current): captures git's push stdin and delegates to the check system.
_PRE_PUSH_HOOK_V5 = CURRENT_PRE_PUSH_HOOK


def compute_hook_hash(content):
    """Return the SHA-256 hex digest of `content`, with trailing whitespace stripped.

    Trailing whitespace (including newlines) is stripped before hashing so that
    a hook re-saved by an editor with a tweaked trailing newline still matches.
    """
    if isinstance(content, bytes):
        content = content.decode("utf-8", errors="replace")
    normalized = content.rstrip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


# Every pre-push hook content rlsbl has ever shipped. If we find one of these
# on disk we know it's an unmodified rlsbl-installed hook and we can replace
# it. Anything not in this set is treated as user-customized.
PRE_PUSH_HOOK_HASHES = frozenset({
    compute_hook_hash(_PRE_PUSH_HOOK_V1),
    compute_hook_hash(_PRE_PUSH_HOOK_V2),
    compute_hook_hash(_PRE_PUSH_HOOK_V3),
    compute_hook_hash(_PRE_PUSH_HOOK_V4),
    compute_hook_hash(_PRE_PUSH_HOOK_V5),
})


CURRENT_PRE_PUSH_HOOK_HASH = compute_hook_hash(CURRENT_PRE_PUSH_HOOK)
