"""The declared strictspec floor must reach every generated validator.

A strictspec-generated validator carries the release that produced it as
``GENERATED_BY`` and calls ``strictspec.require_runtime_version(GENERATED_BY)``
AT IMPORT. That pairing is exact: the runtime the validator imports must be the
release it was generated by, or the import raises before any document is
validated.

So the manifest's ``strictspec`` floor is not advisory. A floor BELOW any
committed ``GENERATED_BY`` ships an artifact whose validators cannot import on
a floor-resolved install: the repo's own lock resolves the newer strictspec and
every local test passes, while a consumer installing the published artifact
resolves the floor and hits the pairing error on first use.

Why ``dep-floors`` cannot see this
----------------------------------

``dep-floors`` compares at major.minor, deliberately: a patch bump in a lock is
not a behavior boundary for an ordinary dependency. For this pairing it is --
``0.2.3`` and ``0.2.4`` are different releases and the guard refuses the
mismatch -- so the comparison here is at FULL PATCH precision, against the
generated files rather than against the lock.

What is compared
----------------

``strictspec.toml`` is the manifest that declares which validators exist and
where they are written, so it is the enumeration this check reads: no directory
is guessed at. For every declared output that exists, the ``GENERATED_BY``
constant is read; the highest one across all of them is the floor the manifest
must declare at least.
"""

import os
import re
import tomllib

#: ``GENERATED_BY = "0.2.3"`` as the python generator writes it.
_GENERATED_BY = re.compile(r"""^GENERATED_BY\s*=\s*["']([^"']+)["']""", re.M)

_VERSION = re.compile(r"^(\d+)(?:\.(\d+))?(?:\.(\d+))?")

#: The dependency whose floor this check polices.
PACKAGE = "strictspec"

MANIFEST = "strictspec.toml"


class StrictspecFloorVerdict:
    """Result of comparing the declared floor against the generated code."""

    def __init__(self, *, problems=None, notes=None, skip_reason=None):
        self.problems = list(problems or [])
        self.notes = list(notes or [])
        self.skip_reason = skip_reason

    @property
    def ok(self):
        return not self.problems


def parse_version(text):
    """``(major, minor, patch)`` of a version string, or None.

    Full patch precision, unlike :func:`rlsbl.dep_floors.version_tuple`: the
    runtime pairing this check polices is exact, so a patch difference is the
    whole point rather than noise.
    """
    if not isinstance(text, str):
        return None
    m = _VERSION.match(text.strip().lstrip("vV="))
    if m is None:
        return None
    return tuple(int(part) if part else 0 for part in m.groups())


def declared_floor(constraint):
    """The highest lower bound a PEP 440 specifier set states, or None."""
    best = None
    for clause in (constraint or "").split(","):
        clause = clause.strip()
        if not clause or clause.startswith(("!=", "<")):
            continue
        for op in ("===", ">=", "==", "~=", ">"):
            if clause.startswith(op):
                parsed = parse_version(clause[len(op):])
                if parsed is not None and (best is None or parsed > best):
                    best = parsed
                break
    return best


def read_generated_by(path):
    """The ``GENERATED_BY`` constant of a generated file, or None."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
    except (OSError, UnicodeDecodeError):
        return None
    m = _GENERATED_BY.search(text)
    return m.group(1) if m else None


def declared_targets(project_root):
    """``[(output_path, lang)]`` every schema target the manifest declares.

    Returns None when there is no readable ``strictspec.toml`` -- a project
    that generates no validators, which is not this check's business.
    """
    path = os.path.join(str(project_root), MANIFEST)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "rb") as f:
            data = tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError):
        return None
    targets = []
    for schema in data.get("schemas") or []:
        if not isinstance(schema, dict):
            continue
        for target in schema.get("targets") or []:
            if not isinstance(target, dict):
                continue
            output = target.get("output")
            if isinstance(output, str) and output:
                targets.append((output, target.get("lang")))
    return targets


def _render(version):
    return ".".join(str(part) for part in version)


def evaluate_strictspec_floor(project_root):
    """Compare the declared ``strictspec`` floor against every generated file."""
    from .dep_floors import normalize_pypi_name, pypi_declared

    root = str(project_root)
    targets = declared_targets(root)
    if targets is None:
        return StrictspecFloorVerdict(
            skip_reason=f"no {MANIFEST} -- this project generates no validators",
        )
    if not targets:
        return StrictspecFloorVerdict(
            skip_reason=f"{MANIFEST} declares no generation target",
        )

    problems = []
    notes = []
    generated = {}
    for output, lang in targets:
        path = os.path.join(root, output)
        if not os.path.isfile(path):
            notes.append(f"{output}: declared but not generated yet")
            continue
        stamp = read_generated_by(path)
        if stamp is None:
            if lang == "python":
                problems.append(
                    f"{output}: no GENERATED_BY constant, so the strictspec "
                    f"release that produced it -- the one its "
                    f"require_runtime_version pairing demands -- cannot be "
                    f"read. Regenerate it with `strictspec gen --manifest "
                    f"{MANIFEST}`."
                )
            else:
                notes.append(
                    f"{output}: no GENERATED_BY marker to read (lang {lang})"
                )
            continue
        parsed = parse_version(stamp)
        if parsed is None:
            problems.append(
                f"{output}: GENERATED_BY is {stamp!r}, which is not a version."
            )
            continue
        generated[output] = (stamp, parsed)

    if not generated:
        return StrictspecFloorVerdict(
            problems=problems,
            notes=notes or ["no generated validator carries a GENERATED_BY"],
        )

    highest_output, (highest_text, highest) = max(
        generated.items(), key=lambda item: item[1][1],
    )

    declared = pypi_declared(root)
    if declared is None:
        problems.append(
            f"the generated validators call "
            f"strictspec.require_runtime_version({highest_text!r}) at import, "
            f"but there is no readable pyproject.toml declaring a strictspec "
            f"floor."
        )
        return StrictspecFloorVerdict(problems=problems, notes=notes)

    entry = declared.get(normalize_pypi_name(PACKAGE))
    if entry is None:
        problems.append(
            f"{highest_output} is generated by strictspec {highest_text} and "
            f"pairs with exactly that runtime at import, but no manifest "
            f"section declares {PACKAGE} at all -- an installed artifact would "
            f"have no strictspec to import. Declare "
            f'"{PACKAGE}>={highest_text}".'
        )
        return StrictspecFloorVerdict(problems=problems, notes=notes)

    label, kind, constraint = entry
    if kind == "url":
        notes.append(
            f"{PACKAGE} is declared as a direct reference in {label}, which "
            f"states no floor to compare"
        )
        return StrictspecFloorVerdict(problems=problems, notes=notes)

    floor = declared_floor(constraint)
    if floor is None:
        problems.append(
            f"pyproject.toml {label} declares {PACKAGE} with no version floor, "
            f"but {highest_output} was generated by strictspec "
            f"{highest_text} and its validators refuse to import against any "
            f'other release. Declare "{PACKAGE}>={highest_text}".'
        )
    elif floor < highest:
        problems.append(
            f"pyproject.toml {label} declares {PACKAGE} '{constraint}' "
            f"(floor {_render(floor)}), but {highest_output} was generated by "
            f"strictspec {highest_text}: an install resolved at the declared "
            f"floor imports a strictspec the generated validators refuse to "
            f'pair with. Declare "{PACKAGE}>={highest_text}".'
        )
    else:
        notes.append(
            f"{PACKAGE} floor {_render(floor)} covers every generated "
            f"validator (highest GENERATED_BY {highest_text})"
        )
    return StrictspecFloorVerdict(problems=problems, notes=notes)
