package batchrelease_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/batchrelease"
	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/previewapply"
	"github.com/stricttools/rlsbl/internal/release"
	"github.com/stricttools/rlsbl/internal/runstate"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestMain(m *testing.M) {
	if testsupport.IsFakeGH() {
		os.Exit(testsupport.FakeGHMain())
	}
	os.Exit(m.Run())
}

const declarationsPath = ".strictmetadata/releasables/releasables.toml"

const batchFilePath = ".strictmetadata/batch-releases/unreleased.toml"

// batchDeclarations declare a workspace on GitHub as acme/portal: a
// dev-node root, and the releasables widget and gadget, one member each,
// publishing nothing, the member gadget depending on the member widget, so
// a batch releases widget first although gadget comes first by name.
const batchDeclarations = `format_version = 1
repository_layout = "workspace"
release_branches = ["main"]
github_repository = "acme/portal"

[[releasables]]
name = "widget"
tag_format = "{name}@v{version}"
publish_mode = "none"

[[releasables]]
name = "gadget"
tag_format = "{name}@v{version}"
publish_mode = "none"

[[members]]
path = "."
name = "root"
dev_only = true
releasable = false

[[members]]
path = "widget"
name = "widget"
releasable = "widget"

[[members]]
path = "gadget"
name = "gadget"
releasable = "gadget"
depends_on = ["widget"]
`

// batchFile releases widget with a minor bump and gadget with a patch.
const batchFile = `format_version = 2

[releasables.widget]
bump = "minor"
include = ["npm"]
exclude = []
description = "The widget's next release."

[releasables.gadget]
bump = "patch"
include = ["npm"]
exclude = []
description = "The gadget's next release."
`

// ciWorkflow is a workflow triggering on push.
const ciWorkflow = "name: CI\non: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ok\n"

var validationDay = time.Date(2026, 10, 7, 12, 0, 0, 0, time.UTC)

func packageJSON(name, version string) string {
	return fmt.Sprintf("{\n  \"name\": %q,\n  \"version\": %q\n}\n", name, version)
}

// entryNumber makes each fixture entry's id distinct.
var entryNumber int

func entry(userFacing bool, commits ...string) string {
	entryNumber++
	e := changelog.Entry{ID: fmt.Sprintf("%048x", entryNumber), Commits: commits}
	if userFacing {
		e.UserFacing, e.Type, e.Description = true, "feature", "A feature."
	}
	return changelog.Serialize(e) + "\n"
}

// recordRelease records HEAD as the release of version v of releasable,
// tagged tag: its archive, recording the tree of the member at path, and
// its released changelog file, committed with the Autogenerated trailer.
func recordRelease(t *testing.T, repo *testsupport.Repo, releasable, v, path string) {
	t.Helper()
	head := repo.Head()
	archive := ".strictmetadata/releases/" + releasable + "/v" + v + ".toml"
	repo.Write(archive, fmt.Sprintf("format_version = 2\nbump = \"minor\"\ninclude = []\nexclude = []\ndescription = \"release %s\"\nrelease_commit = %q\n\n[released_trees]\n%q = %q\n", v, head, path, strings.Repeat("e", 40)))
	released := changelog.Dir(releasable) + "/" + v + ".jsonl"
	repo.Write(released, entry(false, head))
	repo.Git("tag", releasable+"@v"+v, head)
	repo.Commit("release "+releasable+" "+v+"\n\nAutogenerated: true", archive, released)
}

// addEntry appends an entry naming commits to the releasable's unreleased
// changelog and commits it.
func addEntry(t *testing.T, repo *testsupport.Repo, releasable string, userFacing bool, commits ...string) string {
	t.Helper()
	rel := changelog.Dir(releasable) + "/" + changelog.UnreleasedName
	existing, err := os.ReadFile(repo.Path(rel))
	if err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	return repo.CommitFile(rel, string(existing)+entry(userFacing, commits...), "changelog: entry")
}

// workspaceRepo is the workspace of batchDeclarations with widget released
// at 0.1.0 and gadget at 0.2.0, extra files committed with it, and origin
// holding main and the tags.
func workspaceRepo(t *testing.T, extra map[string]string) *testsupport.Repo {
	t.Helper()
	repo := testsupport.NewRepo(t)
	files := map[string]string{
		declarationsPath:                          batchDeclarations,
		"widget/package.json":                     packageJSON("widget", "0.1.0"),
		"gadget/package.json":                     packageJSON("gadget", "0.2.0"),
		".strictmetadata/releases/widget/version": "0.1.0\n",
		".strictmetadata/releases/gadget/version": "0.2.0\n",
	}
	for p, content := range extra {
		files[p] = content
	}
	var paths []string
	for p, content := range files {
		repo.Write(p, content)
		paths = append(paths, p)
	}
	repo.Commit("the workspace", paths...)
	recordRelease(t, repo, "widget", "0.1.0", "widget")
	recordRelease(t, repo, "gadget", "0.2.0", "gadget")
	return repo
}

// batchRepo is workspaceRepo with a feature in each member, each described
// by a user-facing entry, the batch release file batchFile, and origin
// holding main and the tags.
func batchRepo(t *testing.T, extra map[string]string) *testsupport.Repo {
	t.Helper()
	repo := workspaceRepo(t, extra)
	widgetFeature := repo.CommitFile("widget/feature.txt", "a feature\n", "add a widget feature")
	gadgetFeature := repo.CommitFile("gadget/feature.txt", "a feature\n", "add a gadget feature")
	widgetLog := changelog.Dir("widget") + "/" + changelog.UnreleasedName
	gadgetLog := changelog.Dir("gadget") + "/" + changelog.UnreleasedName
	repo.Write(widgetLog, entry(true, widgetFeature))
	repo.Write(gadgetLog, entry(true, gadgetFeature))
	repo.Write(batchFilePath, batchFile)
	repo.Commit("prepare the batch", widgetLog, gadgetLog, batchFilePath)
	repo.AddBareRemote("origin")
	repo.Git("push", "-q", "origin", "main")
	repo.Git("push", "-q", "origin", "--tags")
	return repo
}

// passingChecks passes every check it is asked to run.
type passingChecks struct{}

func (passingChecks) RunChecks(_ strictcli.CheckContext, opts strictcli.RunChecksOptions) ([]strictcli.CheckRunResult, []string, int, error) {
	return []strictcli.CheckRunResult{{Name: opts.NameGlob, Outcome: (&strictcli.ErrorReporter{}).Passed("ok")}}, nil, 0, nil
}

// runRequest is the request a command started in dir of repo makes.
func runRequest(t *testing.T, repo *testsupport.Repo, dir string, dryRun bool, say func(string)) release.RunRequest {
	t.Helper()
	return release.RunRequest{
		Dir: dir, LiveRoot: repo.Dir, DryRun: dryRun, RlsblVersion: "0.0.0-test",
		Checks: passingChecks{}, IndexPath: filepath.Join(t.TempDir(), "confidential-names.toml"),
		Now:   func() time.Time { return validationDay },
		Sleep: func(time.Duration) {},
		Log:   say, Warn: say,
	}
}

// batchCommand runs `monorepo release run` (--no-watch) in repo's root and
// returns what it printed and its error.
func batchCommand(t *testing.T, repo *testsupport.Repo, dryRun bool) (string, error) {
	t.Helper()
	var ferr error
	var out strings.Builder
	say := func(s string) { out.WriteString(s + "\n") }
	testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating, DryRun: dryRun, Allowlist: previewapply.Prefixes(), HTTPClient: testsupport.NewFakeHTTP(t).Client()}, func(ctx *strictcli.Context) error {
		ferr = batchrelease.Run(ctx.Effects(), runRequest(t, repo, repo.Dir, dryRun, say))
		return ferr
	})
	return out.String(), ferr
}

// resumeCommand runs `release resume` (--no-watch) from dir.
func resumeCommand(t *testing.T, repo *testsupport.Repo, dir string) (string, error) {
	t.Helper()
	var ferr error
	var out strings.Builder
	say := func(s string) { out.WriteString(s + "\n") }
	testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating, Allowlist: previewapply.Prefixes(), HTTPClient: testsupport.NewFakeHTTP(t).Client()}, func(ctx *strictcli.Context) error {
		ferr = release.Resume(ctx.Effects(), runRequest(t, repo, dir, false, say))
		return ferr
	})
	return out.String(), ferr
}

// validationAnswers are gh's answers to the questions validation asks about
// acme/portal.
func validationAnswers() []testsupport.GHAnswer {
	return []testsupport.GHAnswer{
		{Args: []string{"--version"}, Stdout: "gh version 2.0.0\n"},
		{Args: []string{"auth", "status", "--hostname", "github.com"}},
		{Args: []string{"api", "--method", "GET", "repos/acme/portal"}, Stdout: `{"full_name":"acme/portal","visibility":"public","private":false,"archived":false,"permissions":{"push":true}}`},
	}
}

// releaseCreation are gh's answers to the GitHub Release of tag: none
// exists, and the creation succeeds.
func releaseCreation(tag string) []testsupport.GHAnswer {
	return []testsupport.GHAnswer{
		{Args: []string{"release", "view", tag, "--repo", "acme/portal", "--json", "tagName", "--jq", ".tagName"}, Stderr: "release not found\n", Exit: 1},
		{Args: []string{"release", "create", tag, "--repo", "acme/portal", "--title", tag, "--notes-file", "-", "--verify-tag"}},
	}
}

// failingReleaseCreation are gh's answers to the GitHub Release of tag:
// none exists, and the creation fails.
func failingReleaseCreation(tag string) []testsupport.GHAnswer {
	return []testsupport.GHAnswer{
		{Args: []string{"release", "view", tag, "--repo", "acme/portal", "--json", "tagName", "--jq", ".tagName"}, Stderr: "release not found\n", Exit: 1},
		{Args: []string{"release", "create", tag, "--repo", "acme/portal", "--title", tag, "--notes-file", "-", "--verify-tag"}, Stderr: "HTTP 502: Bad Gateway\n", Exit: 1},
	}
}

// ciRun are gh's answers about the CI run id on any commit: it concluded
// with conclusion, and a passing run's job test passed.
func ciRun(id int, conclusion string) []testsupport.GHAnswer {
	exit := 0
	if conclusion != "success" {
		exit = 1
	}
	run := fmt.Sprintf("repos/acme/portal/actions/runs/%d", id)
	jobs := `{"jobs":[]}`
	if conclusion == "success" {
		jobs = fmt.Sprintf(`{"jobs":[{"id":7,"name":"test","status":"completed","conclusion":"success","started_at":"2026-10-07T12:00:00Z","html_url":"https://github.com/acme/portal/actions/runs/%d/job/7"}]}`, id)
	}
	return []testsupport.GHAnswer{
		{Args: []string{"run", "list", "--repo", "acme/portal", "--commit", testsupport.GHAnyArg, "--limit", "100", "--json", "databaseId,name,workflowName,status,conclusion,headBranch,headSha,event"},
			Stdout: fmt.Sprintf(`[{"databaseId":%d,"name":"CI","workflowName":"CI","status":"completed","conclusion":%q,"headBranch":"main","headSha":"","event":"push"}]`, id, conclusion)},
		{Args: []string{"run", "watch", fmt.Sprint(id), "--repo", "acme/portal", "--exit-status"}, Exit: exit},
		{Args: []string{"run", "rerun", fmt.Sprint(id), "--repo", "acme/portal", "--failed"}},
		{Args: []string{"api", "--method", "GET", run}, Stdout: fmt.Sprintf(`{"status":"completed","conclusion":%q,"run_attempt":1}`, conclusion)},
		{Args: []string{"api", "--method", "GET", "--paginate", run + "/attempts/1/jobs?per_page=100"}, Stdout: jobs},
	}
}

func answers(groups ...[]testsupport.GHAnswer) []testsupport.GHAnswer {
	var out []testsupport.GHAnswer
	for _, g := range groups {
		out = append(out, g...)
	}
	return out
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func exists(t *testing.T, path string) bool {
	t.Helper()
	_, err := os.Stat(path)
	if err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	return err == nil
}

// changes are the working tree's changes, the run state's own directory
// left out.
func changes(t *testing.T, repo *testsupport.Repo) string {
	t.Helper()
	out, _, _ := testsupport.RunGit(t, repo.Dir, "status", "--porcelain", "--untracked-files=all")
	var kept []string
	for _, line := range strings.Split(strings.TrimRight(out, "\n"), "\n") {
		if line != "" && !strings.Contains(line, ".strictmetadata/.release-state/") {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

func remoteRef(t *testing.T, repo *testsupport.Repo, ref string) string {
	t.Helper()
	out, _, code := testsupport.RunGit(t, repo.Dir, "ls-remote", "origin", ref)
	if code != 0 {
		t.Fatalf("ls-remote origin %s failed", ref)
	}
	sha, _, _ := strings.Cut(strings.TrimSpace(out), "\t")
	return sha
}

func tagCommit(t *testing.T, repo *testsupport.Repo, tag string) string {
	t.Helper()
	out, _, code := testsupport.RunGit(t, repo.Dir, "rev-parse", "--verify", "--quiet", tag+"^{commit}")
	if code != 0 {
		return ""
	}
	return strings.TrimSpace(out)
}

func loadState(t *testing.T, repo *testsupport.Repo, releasable string) (runstate.InProgress, bool) {
	t.Helper()
	s, found, err := runstate.LoadInProgress(repo.Dir, releasable)
	if err != nil {
		t.Fatal(err)
	}
	return s, found
}

// batchArchives are the archives of batch release files in repo.
func batchArchives(t *testing.T, repo *testsupport.Repo) []string {
	t.Helper()
	matches, err := filepath.Glob(repo.Path(".strictmetadata/batch-releases/batch-*.toml"))
	if err != nil {
		t.Fatal(err)
	}
	return matches
}

func mustNotFail(t *testing.T, err error, out string) {
	t.Helper()
	if err != nil {
		t.Fatalf("%v\n%s", err, out)
	}
}

func requireContains(t *testing.T, text string, wants ...string) {
	t.Helper()
	for _, want := range wants {
		if !strings.Contains(text, want) {
			t.Fatalf("%q is not in:\n%s", want, text)
		}
	}
}
