package batchrelease_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/batchrelease"
	"github.com/stricttools/rlsbl/internal/release"
	"github.com/stricttools/rlsbl/internal/runstate"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestABatchReleasesItsReleasablesInDependencyOrderOnOneCandidate(t *testing.T) {
	hygiene.Isolate(t)
	gh := testsupport.FakeGH(t, answers(validationAnswers(), releaseCreation("widget@v0.2.0"), releaseCreation("gadget@v0.2.1"))...)
	repo := batchRepo(t, nil)
	start := repo.Head()
	out, err := batchCommand(t, repo, false)
	mustNotFail(t, err, out)
	widget, gadget := tagCommit(t, repo, "widget@v0.2.0"), tagCommit(t, repo, "gadget@v0.2.1")
	if widget == "" || widget != gadget {
		t.Fatalf("the two releasables are not tagged on one candidate: widget %q, gadget %q\n%s", widget, gadget, out)
	}
	if remoteRef(t, repo, "refs/tags/widget@v0.2.0") != widget || remoteRef(t, repo, "refs/tags/gadget@v0.2.1") != gadget {
		t.Errorf("origin does not hold both tags at the candidate")
	}
	// widget, which gadget depends on, is released first although gadget
	// comes first by name: its release commit is the older of the two.
	subjects := repo.Git("log", "--format=%s", start+".."+widget)
	if w, g := strings.Index(subjects, "widget: release v0.2.0"), strings.Index(subjects, "gadget: release v0.2.1"); w < 0 || g < 0 || g > w {
		t.Errorf("the release commits are not in dependency order (newest first):\n%s", subjects)
	}
	var created []string
	for _, c := range gh.Calls() {
		if len(c.Args) > 2 && c.Args[0] == "release" && c.Args[1] == "create" {
			created = append(created, c.Args[2])
		}
	}
	if strings.Join(created, ",") != "widget@v0.2.0,gadget@v0.2.1" {
		t.Errorf("the GitHub Releases were created as %v", created)
	}
	for _, archive := range []string{".strictmetadata/releases/widget/v0.2.0.toml", ".strictmetadata/releases/gadget/v0.2.1.toml"} {
		requireContains(t, read(t, repo.Path(archive)), `release_commit = "`+widget+`"`, "next release")
	}
	if read(t, repo.Path(".strictmetadata/releases/widget/version")) != "0.2.0\n" || read(t, repo.Path(".strictmetadata/releases/gadget/version")) != "0.2.1\n" {
		t.Errorf("the version files were not bumped")
	}
	// The batch release file is archived, committed, and pushed; the plan
	// and the release states are gone.
	if exists(t, repo.Path(batchFilePath)) {
		t.Errorf("the batch release file was not archived")
	}
	archives := batchArchives(t, repo)
	if len(archives) != 1 || !strings.Contains(read(t, archives[0]), "[releasables.gadget]") {
		t.Fatalf("the batch release file's archive: %v", archives)
	}
	requireContains(t, repo.Git("log", "-1", "--format=%B"), "chore: archive the batch release file as batch-", "Autogenerated: true")
	if remoteRef(t, repo, "refs/heads/main") != repo.Head() {
		t.Errorf("origin's main is not the working tree's after the archive")
	}
	if exists(t, repo.Path(runstate.BatchPlanPath)) {
		t.Errorf("the batch plan was left behind")
	}
	for _, name := range []string{"widget", "gadget"} {
		if _, found := loadState(t, repo, name); found {
			t.Errorf("the release state of %s was left behind", name)
		}
	}
	if c := changes(t, repo); c != "" {
		t.Errorf("the batch left the working tree changed:\n%s", c)
	}
	requireContains(t, out, "Batch release complete: widget, gadget")
}

func TestABatchStoppedByARedVerdictContinuesAtTheSameVersionsAfterTheFix(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, answers(validationAnswers(), ciRun(42, "failure"))...)
	repo := batchRepo(t, map[string]string{".github/workflows/ci.yml": ciWorkflow})
	out, err := batchCommand(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "CI did not pass on the batch release candidate") || !strings.Contains(err.Error(), "rlsbl monorepo release run --watch") {
		t.Fatalf("a red verdict did not stop the batch naming how it continues: %v\n%s", err, out)
	}
	var candidate string
	for _, name := range []string{"widget", "gadget"} {
		state, found := loadState(t, repo, name)
		if !found || !state.Completed(release.StepCandidatePushed) || state.Completed(release.StepCIVerified) || state.FailedSteps[release.StepCIVerified] == "" {
			t.Fatalf("the stopped state of %s: %+v", name, state)
		}
		candidate = state.ReleaseCommit
	}
	if remoteRef(t, repo, "refs/heads/main") != candidate || tagCommit(t, repo, "widget@v0.2.0") != "" || tagCommit(t, repo, "gadget@v0.2.1") != "" {
		t.Fatalf("the candidate is not on origin untagged")
	}
	if !exists(t, repo.Path(runstate.BatchPlanPath)) || !exists(t, repo.Path(batchFilePath)) {
		t.Fatalf("the plan or the batch release file is gone")
	}
	// The fix forward the refusal names, recorded in widget's changelog.
	fix := repo.CommitFile("widget/fix.txt", "the fix\n", "fix the failure")
	addEntry(t, repo, "widget", false, fix)
	tip := repo.Head()
	testsupport.FakeGH(t, answers(validationAnswers(), ciRun(43, "success"), releaseCreation("widget@v0.2.0"), releaseCreation("gadget@v0.2.1"))...)
	out, err = batchCommand(t, repo, false)
	mustNotFail(t, err, out)
	if tagCommit(t, repo, "widget@v0.2.0") != tip || tagCommit(t, repo, "gadget@v0.2.1") != tip {
		t.Errorf("the releasables are not tagged on the fixed tip CI verified (%s)", tip)
	}
	requireContains(t, read(t, repo.Path(".strictmetadata/changelog/widget/0.2.0.jsonl")), fix)
	if exists(t, repo.Path(runstate.BatchPlanPath)) || exists(t, repo.Path(batchFilePath)) || len(batchArchives(t, repo)) != 1 {
		t.Errorf("the finished batch was not archived")
	}
}

func TestABatchStoppedPastTheVerdictIsRefusedUntilThatReleaseIsResumed(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, answers(validationAnswers(), failingReleaseCreation("widget@v0.2.0"))...)
	repo := batchRepo(t, nil)
	out, err := batchCommand(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "Finish widget with `rlsbl release resume --watch`") {
		t.Fatalf("a failed GitHub Release did not stop the batch naming the resume: %v\n%s", err, out)
	}
	if state, found := loadState(t, repo, "widget"); !found || !state.Completed(release.StepCIVerified) || state.FailedSteps[release.StepGitHubReleaseCreated] == "" {
		t.Fatalf("widget's stopped state: %+v", state)
	}
	if state, found := loadState(t, repo, "gadget"); !found || state.Completed(release.StepCIVerified) {
		t.Fatalf("gadget's stopped state: %+v", state)
	}
	// Running the batch again would move the commit widget's verdict is
	// about: refused, naming the resume and where to run it.
	head := repo.Head()
	widgetDir, err := filepath.EvalSymlinks(repo.Path("widget"))
	if err != nil {
		t.Fatal(err)
	}
	testsupport.FakeGH(t, validationAnswers()...)
	_, err = batchCommand(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "`rlsbl release resume --watch`") || !strings.Contains(err.Error(), widgetDir) {
		t.Fatalf("a batch with a release past its verdict was not refused: %v", err)
	}
	if repo.Head() != head {
		t.Fatalf("the refused batch committed")
	}
	// The fix the refusal names: widget's release resumed from its member.
	testsupport.FakeGH(t, answers(validationAnswers(), releaseCreation("widget@v0.2.0"))...)
	out, err = resumeCommand(t, repo, repo.Path("widget"))
	mustNotFail(t, err, out)
	if _, found := loadState(t, repo, "widget"); found || tagCommit(t, repo, "widget@v0.2.0") == "" {
		t.Fatalf("the resume did not finish widget's release")
	}
	// The batch then finishes gadget and archives itself.
	testsupport.FakeGH(t, answers(validationAnswers(), releaseCreation("gadget@v0.2.1"))...)
	out, err = batchCommand(t, repo, false)
	mustNotFail(t, err, out)
	requireContains(t, out, "Skipping widget", "Batch release complete: gadget")
	if tagCommit(t, repo, "gadget@v0.2.1") == "" || remoteRef(t, repo, "refs/tags/gadget@v0.2.1") == "" {
		t.Errorf("gadget was not released")
	}
	if exists(t, repo.Path(batchFilePath)) || exists(t, repo.Path(runstate.BatchPlanPath)) {
		t.Errorf("the finished batch was not archived")
	}
}

func TestADryRunBatchValidatesAndWritesNothing(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, validationAnswers()...)
	repo := batchRepo(t, nil)
	head := repo.Head()
	out, err := batchCommand(t, repo, true)
	mustNotFail(t, err, out)
	requireContains(t, out, "in this order: widget, gadget", "widget: 0.1.0 -> 0.2.0 (widget@v0.2.0, minor)", "gadget: 0.2.0 -> 0.2.1 (gadget@v0.2.1, patch)")
	if repo.Head() != head || changes(t, repo) != "" || remoteRef(t, repo, "refs/heads/main") != head {
		t.Errorf("the preview wrote something:\n%s", changes(t, repo))
	}
	if exists(t, repo.Path(runstate.BatchPlanPath)) {
		t.Errorf("the preview planned the batch")
	}
}

func TestABatchReleasableWithAReleaseFileOfItsOwnIsRefusedUntilItIsDeleted(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, validationAnswers()...)
	repo := batchRepo(t, nil)
	own := ".strictmetadata/releases/widget/unreleased.toml"
	repo.CommitFile(own, "format_version = 2\nbump = \"major\"\ninclude = [\"npm\"]\nexclude = []\ndescription = \"its own\"\n", "widget's own release file")
	_, err := batchCommand(t, repo, true)
	if err == nil || !strings.Contains(err.Error(), "a release file of its own") || !strings.Contains(err.Error(), "saferm delete") || !strings.Contains(err.Error(), "safegit commit") {
		t.Fatalf("a releasable with two release files was not refused: %v", err)
	}
	// The fix the refusal names: the release file deleted, the deletion
	// committed.
	repo.Git("rm", "-q", own)
	repo.Git("commit", "-q", "-m", "release widget through the batch release file")
	out, err := batchCommand(t, repo, true)
	mustNotFail(t, err, out)
}

func TestABatchReleaseFileThatNoLongerMatchesItsPlanIsRefusedUntilThePlanIsGone(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, validationAnswers()...)
	repo := batchRepo(t, nil)
	plan := runstate.BatchPlan{Items: []runstate.BatchPlanItem{
		{Name: "widget", BaseVersion: "0.1.0", TargetVersion: "1.0.0", Tag: "widget@v1.0.0", Registry: "npm", Bump: "major"},
	}}
	testsupport.WriteFile(t, repo.Path(runstate.BatchPlanPath), string(runstate.RenderBatchPlan(plan)))
	_, err := batchCommand(t, repo, true)
	if err == nil || !strings.Contains(err.Error(), "does not match the plan") || !strings.Contains(err.Error(), "the plan bumps widget major, and the batch release file minor") || !strings.Contains(err.Error(), "saferm delete") {
		t.Fatalf("a batch release file not matching its plan was not refused: %v", err)
	}
	// The fix the refusal names: the plan deleted.
	if err := os.Remove(repo.Path(runstate.BatchPlanPath)); err != nil {
		t.Fatal(err)
	}
	out, err := batchCommand(t, repo, true)
	mustNotFail(t, err, out)
}

func TestABatchNamingAnUndeclaredReleasableIsRefusedUntilTheTableIsGone(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, validationAnswers()...)
	repo := batchRepo(t, nil)
	repo.CommitFile(batchFilePath, batchFile+"\n[releasables.portal]\nbump = \"patch\"\ninclude = [\"npm\"]\nexclude = []\ndescription = \"x\"\n", "name portal too")
	_, err := batchCommand(t, repo, true)
	if err == nil || !strings.Contains(err.Error(), "does not declare the releasable portal") || !strings.Contains(err.Error(), "the declared releasables are widget, gadget") {
		t.Fatalf("an undeclared releasable was not refused: %v", err)
	}
	// The fix: the table taken out of the batch release file.
	repo.CommitFile(batchFilePath, batchFile, "leave portal out")
	out, err := batchCommand(t, repo, true)
	mustNotFail(t, err, out)
}

func TestABatchWithoutABatchReleaseFileNamesTheInitThatWritesOne(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeSafegit(t)
	testsupport.FakeGH(t, validationAnswers()...)
	repo := workspaceRepo(t, nil)
	repo.AddBareRemote("origin")
	repo.Git("push", "-q", "origin", "main")
	_, err := batchCommand(t, repo, true)
	if err == nil || !strings.Contains(err.Error(), "rlsbl monorepo release init") {
		t.Fatalf("a batch with no batch release file did not name the init: %v", err)
	}
	// The fix: the init, then each table filled in.
	widgetFeature := repo.CommitFile("widget/feature.txt", "a feature\n", "add a widget feature")
	addEntry(t, repo, "widget", true, widgetFeature)
	res, ierr := initBatch(t, repo, nil)
	if ierr != nil || !res.Written {
		t.Fatalf("init: %+v %v", res, ierr)
	}
	text := strings.Replace(read(t, repo.Path(batchFilePath)), `bump = ""`, `bump = "minor"`, 1)
	text = strings.Replace(text, `description = ""`, `description = "The next widget."`, 1)
	repo.CommitFile(batchFilePath, text, "fill in the batch")
	out, err := batchCommand(t, repo, true)
	mustNotFail(t, err, out)
	requireContains(t, out, "widget: 0.1.0 -> 0.2.0")
}

func TestABatchReleaseOfAStandaloneProjectIsRefused(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	repo.CommitFile(declarationsPath, "format_version = 1\nrepository_layout = \"standalone\"\nrelease_branches = [\"main\"]\n\n[[releasables]]\nname = \"portal\"\ntag_format = \"v{version}\"\npublish_mode = \"none\"\n\n[[members]]\npath = \".\"\nname = \"root\"\nreleasable = \"portal\"\n", "the project")
	_, err := batchCommand(t, repo, true)
	if err == nil || !strings.Contains(err.Error(), "`rlsbl release run --watch`") {
		t.Fatalf("a standalone project's batch release was not refused: %v", err)
	}
}

// A dev-node root declaring selfdoc.json gets selfdoc gen and then selfdoc
// check before the batch, and the commit of what they wrote carries the
// hashes store gen records: check is selfdoc's read-only verdict, writing
// nothing and declaring no --auto-commit flag, so the batch passes it none.
func TestABatchCommitsWhatSelfdocGenWroteAtTheRootAndPassesCheckNoCommitFlag(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeGH(t, answers(validationAnswers(), releaseCreation("widget@v0.2.0"), releaseCreation("gadget@v0.2.1"))...)
	logPath := filepath.Join(t.TempDir(), "selfdoc-log")
	fakeDir := t.TempDir()
	script := "#!/bin/sh\necho \"selfdoc $*\" >> " + logPath + "\n" + `case "$1" in
gen) mkdir -p docs && echo generated > docs/index.md && echo recorded > docs/hashes.toml ;;
check) case " $* " in *" --no-auto-commit "*|*" --auto-commit "*) echo "error: unknown flag" >&2; exit 1 ;; esac ;;
esac
`
	if err := os.WriteFile(filepath.Join(fakeDir, "selfdoc"), []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", fakeDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	repo := batchRepo(t, map[string]string{"selfdoc.json": "{}\n"})
	start := repo.Head()
	out, err := batchCommand(t, repo, false)
	mustNotFail(t, err, out)
	if got := strings.TrimSpace(read(t, logPath)); got != "selfdoc gen --no-auto-commit\nselfdoc check" {
		t.Errorf("selfdoc ran as:\n%s", got)
	}
	var selfdocCommit string
	for _, line := range strings.Split(repo.Git("log", "--format=%H %s", start+"..HEAD"), "\n") {
		if hash, subject, _ := strings.Cut(line, " "); subject == batchrelease.RootSelfdocCommitMessage {
			selfdocCommit = hash
		}
	}
	if selfdocCommit == "" {
		t.Fatalf("no commit carries what selfdoc wrote:\n%s", repo.Git("log", "--format=%s", start+"..HEAD"))
	}
	if files := repo.Git("show", "--name-only", "--format=", selfdocCommit); files != "docs/hashes.toml\ndocs/index.md" {
		t.Errorf("the selfdoc commit carries:\n%s", files)
	}
}
