package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle/index"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/historyrewrite"
	"github.com/stricttools/rlsbl/internal/releaseops"
)

const changelogGroupHelp = "The structured changelog: one JSONL file of entries per release of each releasable, under " +
	".strictmetadata/changelog/<releasable>/ (unreleased.jsonl, and a read-only <version>.jsonl per release), each entry typed feature, fix, " +
	"or breaking and naming the commits it describes, with CHANGELOG.md generated from them. Every command acts on the releasable of the " +
	"member whose directory holds the working directory, except remap, which rewrites every changelog of the repository."

var changelogAddHelp = fmt.Sprintf("Append an entry to the releasable's unreleased.jsonl and commit it. Each commit must resolve and change a file "+
	"the releasable's changelog covers (its members' files and its own state directories). A user-facing entry (the default) needs "+
	"--description and --type; --no-user-facing marks an internal change that CHANGELOG.md and the release notes leave out. A commit an "+
	"entry of the same type and user-facing value already names is refused. An entry naming more than %d commits needs --batch-reason "+
	"saying why they are one change, which the entry carries and which exempts it from the per-entry limit; an entry within the limit "+
	"refuses one. A commit appears in at most %d entries. In a workspace the entry records the releasable's members the commits change. "+
	"Committed unless --no-auto-commit.", changelog.MaxCommitsPerEntry, changelog.MaxEntriesPerCommit)

const changelogGenerateHelp = "Write the releasable's CHANGELOG.md from its changelog files and release archives (the root CHANGELOG.md " +
	"standalone; .strictmetadata/changelog/<releasable>/CHANGELOG.md and the root roll-up in a workspace), and commit what changed with the " +
	"Autogenerated trailer unless --no-auto-commit. --dry-run prints the releasable's document and writes nothing."

const changelogAmendHelp = "Append an entry to a released version's read-only <version>.jsonl, which stays read-only, regenerate " +
	"CHANGELOG.md, commit both, and rewrite that version's GitHub Release from the record (as `rlsbl release edit <version>` does). The " +
	"entry's checks are changelog add's; --no-validate-hashes takes the commits as given, unresolved and unchecked against the scope, for an " +
	"old commit a rewrite took away. A version without a release archive, or with one stating no fate, is refused before anything is written; " +
	"a version recorded never released has no GitHub Release to rewrite."

const changelogEditHelp = "Change one existing entry, in unreleased.jsonl or a released version's file, as a sparse update: " +
	"--description, --type, and --user-facing write those fields, --unset-description and --unset-type clear them, and every field not named " +
	"is left as it is. The entry is named by --id or by --commits (an entry naming any of them); several entries matching --commits are " +
	"narrowed to those of the type the edit writes, and otherwise refused with every match named. Making an entry user-facing needs a " +
	"description and a type, held already or written by the same edit; making it internal keeps its description and type for a later flip " +
	"back unless the edit clears them. An edit of a released version's file keeps it read-only, regenerates CHANGELOG.md, and rewrites that " +
	"version's GitHub Release from the record. Committed unless --no-auto-commit."

const changelogRemoveHelp = "Delete one entry from unreleased.jsonl or a released version's file, named by --id or by --commits (a " +
	"commit that no longer resolves is matched as written, since the entry of a commit a rewrite took away is the usual one to remove). A " +
	"selector matching several entries is refused with every match named, and one matching none is refused. Removing from a released " +
	"version's file keeps it read-only, regenerates CHANGELOG.md, and rewrites that version's GitHub Release from the record. Committed " +
	"unless --no-auto-commit."

const changelogRemapHelp = "Rewrite stale commit ids in every changelog file of the repository (every releasable's, and every retired " +
	"release history's) through a map of old commits to new ones, read from --map-file (lines of \"<old> <new>\", as git's post-rewrite " +
	"hook prints them), from safegit's rewrite journal (--from-journal: its last rewrite), or from standard input (--stdin, which the " +
	"post-rewrite hook uses); sources may be combined, and an old commit two sources map differently is refused. Every other line keeps " +
	"its bytes and a released file stays read-only; an entry whose commits map to one commit names it once. An abbreviated id the map " +
	"cannot decide is refused before anything is written. What was rewritten is committed with the Autogenerated trailer."

// The entry types, as --type offers them.
var entryTypeChoices = strictcli.Choices(
	strictcli.Ch(changelog.TypeFeature, "a new capability users can reach"),
	strictcli.Ch(changelog.TypeFix, "a user-visible defect that no longer happens"),
	strictcli.Ch(changelog.TypeBreaking, "a change that requires action from users"),
)

// entrySelector builds the choices that name one existing entry. Each
// command gets its own declarations, since a choice belongs to one flag.
func entrySelector(verb string) (byID, byCommits *strictcli.ChoiceDecl, flag strictcli.Flag) {
	byID = strictcli.MemberChoice(
		strictcli.StringFlag("id", "The entry's id, as its line's own id field holds it", strictcli.Required()),
		"Name the entry by its id, which no edit of another line changes")
	byCommits = strictcli.MemberChoice(
		strictcli.StringFlag("commits", "Comma-separated commit ids; the entry naming any of them is "+verb, strictcli.Required()),
		"Name the entry by the commits it names")
	return byID, byCommits, strictcli.MemberChoiceFlag("entry", "Which entry is "+verb, strictcli.Required(), byID, byCommits)
}

var (
	editByID, editByCommits, editEntryFlag       = entrySelector("edited")
	removeByID, removeByCommits, removeEntryFlag = entrySelector("removed")
)

func registerChangelog(r *commandSet) {
	r.group([]string{"changelog"}, changelogGroupHelp)
	r.add(command{
		path:   []string{"changelog", "add"},
		help:   changelogAddHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.StringFlag("commits", "Comma-separated commit ids the entry describes", strictcli.Required()),
			strictcli.StringFlag("description", "The change in one line of markdown, as CHANGELOG.md shows it (required for a user-facing entry)", strictcli.Optional()),
			strictcli.StringFlag("type", "What the change is (required for a user-facing entry)", strictcli.Optional(), entryTypeChoices),
			strictcli.BoolFlag("user-facing", "Whether CHANGELOG.md and the release notes show the entry (user-facing when neither --user-facing nor --no-user-facing is passed)", strictcli.Optional()),
			strictcli.BoolFlag("auto-commit", "Commit the unreleased file (committed when neither --auto-commit nor --no-auto-commit is passed)", strictcli.Optional()),
			strictcli.StringFlag("batch-reason", fmt.Sprintf("Why the entry's more than %d commits are one change; the entry carries it, and it exempts the entry from the per-entry commit limit", changelog.MaxCommitsPerEntry), strictcli.Optional()),
		},
		run: runChangelogAdd,
	})
	r.add(command{
		path:   []string{"changelog", "generate"},
		help:   changelogGenerateHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.BoolFlag("auto-commit", "Commit what changed (committed when neither --auto-commit nor --no-auto-commit is passed)", strictcli.Optional()),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			s, inv, err := openChangelog(ctx)
			if err != nil {
				return nil, err
			}
			return nil, inv.Generate(s, optionalBool(kw, "auto_commit", true))
		},
	})
	r.add(command{
		path:   []string{"changelog", "amend"},
		help:   changelogAmendHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.StringFlag("version", "The released version whose file is amended, bare (0.39.0)", strictcli.Required()),
			strictcli.StringFlag("commits", "Comma-separated commit ids the entry describes", strictcli.Required()),
			strictcli.StringFlag("description", "The change in one line of markdown (required for a user-facing entry)", strictcli.Optional()),
			strictcli.StringFlag("type", "What the change is (required for a user-facing entry)", strictcli.Optional(), entryTypeChoices),
			strictcli.BoolFlag("user-facing", "Whether CHANGELOG.md and the release notes show the entry (user-facing when neither form is passed)", strictcli.Optional()),
			strictcli.BoolFlag("validate-hashes", "Resolve every commit and check it against the releasable's scope (validated when neither form is passed)", strictcli.Optional()),
		},
		run: runChangelogAmend,
	})
	r.add(command{
		path:   []string{"changelog", "edit"},
		help:   changelogEditHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			editEntryFlag,
			strictcli.StringFlag("description", "The entry's new description", strictcli.Optional(), strictcli.Nullable()),
			strictcli.StringFlag("type", "The entry's new type; it also narrows several entries --commits matches to those of this type", strictcli.Optional(), strictcli.Nullable(), entryTypeChoices),
			strictcli.BoolFlag("user-facing", "Make the entry user-facing (--user-facing) or internal (--no-user-facing)", strictcli.Optional()),
			strictcli.BoolFlag("auto-commit", "Commit the rewritten file (committed when neither --auto-commit nor --no-auto-commit is passed)", strictcli.Optional()),
		},
		options: []strictcli.CmdOption{
			strictcli.WithUpdateOf("changelog-entry", strictcli.WriteSparse,
				strictcli.Identity("entry"),
				strictcli.Properties("description", "type", "user-facing")),
		},
		run: runChangelogEdit,
	})
	r.add(command{
		path:   []string{"changelog", "remove"},
		help:   changelogRemoveHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			removeEntryFlag,
			strictcli.BoolFlag("auto-commit", "Commit the rewritten file (committed when neither --auto-commit nor --no-auto-commit is passed)", strictcli.Optional()),
		},
		run: runChangelogRemove,
	})
	r.add(command{
		path:   []string{"changelog", "remap"},
		help:   changelogRemapHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.StringFlag("map-file", "A file of \"<old commit> <new commit>\" lines, relative to this directory or absolute", strictcli.Optional()),
			strictcli.BoolFlag("from-journal", "Read the map of the last rewrite safegit's rewrite journal records", strictcli.Optional()),
			strictcli.BoolFlag("stdin", "Read \"<old commit> <new commit>\" lines from standard input, as git's post-rewrite hook passes them", strictcli.Optional()),
		},
		options: []strictcli.CmdOption{
			strictcli.WithConstraints(strictcli.AtLeastOne("map-source",
				strictcli.Member("map-file", strictcli.WhenPresent()),
				strictcli.Member("from-journal", strictcli.WhenTrue()),
				strictcli.Member("stdin", strictcli.WhenTrue()))),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			return nil, runChangelogRemap(ctx, kw, os.Stdin)
		},
	})
}

// openChangelog is the changelog the working directory selects, and the
// invocation the command runs as.
func openChangelog(ctx *strictcli.Context) (changelog.Subject, changelog.Invocation, error) {
	dir, err := os.Getwd()
	if err != nil {
		return changelog.Subject{}, changelog.Invocation{}, err
	}
	s, err := changelog.OpenAt(ctx.Effects(), dir)
	if err != nil {
		return changelog.Subject{}, changelog.Invocation{}, err
	}
	return s, invocation(ctx), nil
}

func invocation(ctx *strictcli.Context) changelog.Invocation {
	return changelog.Invocation{E: ctx.Effects(), DryRun: ctx.DryRun(), Say: ctx.Out}
}

// entryRequest reads the flags a new entry is built from.
func entryRequest(kw map[string]any) (changelog.EntryRequest, error) {
	if err := requireNonEmpty(kw, "commits"); err != nil {
		return changelog.EntryRequest{}, err
	}
	commits, err := changelog.SplitCommits(strictcli.Get[string](kw, "commits"), "--commits")
	if err != nil {
		return changelog.EntryRequest{}, err
	}
	description, given := strictcli.GetOpt[string](kw, "description")
	if given && description == "" {
		return changelog.EntryRequest{}, emptyArgument("--description")
	}
	return changelog.EntryRequest{
		Commits:     commits,
		UserFacing:  optionalBool(kw, "user_facing", true),
		Description: description,
		Type:        optionalString(kw, "type"),
	}, nil
}

func runChangelogAdd(ctx *strictcli.Context, kw map[string]any) (any, error) {
	req, err := entryRequest(kw)
	if err != nil {
		return nil, err
	}
	reason, given := strictcli.GetOpt[string](kw, "batch_reason")
	if given && reason == "" {
		return nil, emptyArgument("--batch-reason")
	}
	req.BatchReason = reason
	s, inv, err := openChangelog(ctx)
	if err != nil {
		return nil, err
	}
	return nil, inv.Add(s, changelog.AddRequest{Entry: req, AutoCommit: optionalBool(kw, "auto_commit", true)})
}

func runChangelogAmend(ctx *strictcli.Context, kw map[string]any) (any, error) {
	if err := requireNonEmpty(kw, "version"); err != nil {
		return nil, err
	}
	v, err := changelog.ParseVersionArgument(strictcli.Get[string](kw, "version"), "--version")
	if err != nil {
		return nil, err
	}
	req, err := entryRequest(kw)
	if err != nil {
		return nil, err
	}
	req.Unresolved = !optionalBool(kw, "validate_hashes", true)
	s, inv, err := openChangelog(ctx)
	if err != nil {
		return nil, err
	}
	outcome, err := inv.Amend(s, changelog.AmendRequest{Version: v, Entry: req})
	if err != nil {
		return nil, err
	}
	return nil, resyncRelease(ctx, outcome)
}

// selector reads the elected entry selector.
func selector(kw map[string]any, byID *strictcli.ChoiceDecl) (changelog.Selector, error) {
	elected := strictcli.GetElected(kw, "entry")
	value := strictcli.Get[string](elected.Fields, "value")
	if elected.Is(byID) {
		if value == "" {
			return changelog.Selector{}, emptyArgument("--id")
		}
		return changelog.Selector{ID: value}, nil
	}
	commits, err := changelog.SplitCommits(value, "--commits")
	if err != nil {
		return changelog.Selector{}, err
	}
	return changelog.Selector{Commits: commits}, nil
}

func runChangelogEdit(ctx *strictcli.Context, kw map[string]any) (any, error) {
	sel, err := selector(kw, editByID)
	if err != nil {
		return nil, err
	}
	var edit changelog.EditRequest
	if description, given := strictcli.GetOpt[string](kw, "description"); given {
		if description == "" {
			return nil, fmt.Errorf("--description must not be empty; to clear the entry's description, pass --unset-description")
		}
		edit.Description = &description
	}
	if typ, given := strictcli.GetOpt[string](kw, "type"); given {
		edit.Type = &typ
	}
	if userFacing, given := strictcli.GetOpt[bool](kw, "user_facing"); given {
		edit.UserFacing = &userFacing
	}
	edit.UnsetDescription = ctx.Unset("description")
	edit.UnsetType = ctx.Unset("type")
	s, inv, err := openChangelog(ctx)
	if err != nil {
		return nil, err
	}
	outcome, err := inv.Edit(s, changelog.EditCommand{Selector: sel, Edit: edit, AutoCommit: optionalBool(kw, "auto_commit", true)})
	if err != nil {
		return nil, err
	}
	return nil, resyncRelease(ctx, outcome)
}

func runChangelogRemove(ctx *strictcli.Context, kw map[string]any) (any, error) {
	sel, err := selector(kw, removeByID)
	if err != nil {
		return nil, err
	}
	s, inv, err := openChangelog(ctx)
	if err != nil {
		return nil, err
	}
	outcome, err := inv.Remove(s, changelog.RemoveCommand{Selector: sel, AutoCommit: optionalBool(kw, "auto_commit", true)})
	if err != nil {
		return nil, err
	}
	return nil, resyncRelease(ctx, outcome)
}

// resyncRelease rewrites the GitHub Release of the released version a
// changelog write left stale, from the record, as `release edit` does.
// Under --dry-run it says what it would do.
func resyncRelease(ctx *strictcli.Context, o changelog.Outcome) error {
	if o.Resync == nil {
		return nil
	}
	v := o.Resync.String()
	if ctx.DryRun() {
		ctx.Out("Would rewrite the GitHub Release of " + v + " from the record, as `rlsbl release edit " + v + "` does")
		return nil
	}
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	indexPath, err := index.DefaultPath()
	if err != nil {
		return err
	}
	if err := releaseops.Edit(ctx, releaseops.EditRequest{Dir: dir, Version: v, IndexPath: indexPath}); err != nil {
		return fmt.Errorf("the changelog of %s is written, but its GitHub Release was not rewritten from it: %w\nOnce the cause is fixed, `rlsbl release edit %s` rewrites it", v, err, v)
	}
	return nil
}

func runChangelogRemap(ctx *strictcli.Context, kw map[string]any, stdin io.Reader) error {
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	root, err := declarations.FindRepositoryRoot(dir)
	if err != nil {
		return err
	}
	repo, err := git.Open(ctx.Effects(), root)
	if err != nil {
		return err
	}
	var sources []changelog.MapSource
	if path, given := strictcli.GetOpt[string](kw, "map_file"); given {
		if path == "" {
			return emptyArgument("--map-file")
		}
		if !filepath.IsAbs(path) {
			path = filepath.Join(dir, path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading the map file: %w", err)
		}
		m, err := git.ParseRewriteMap(string(data))
		if err != nil {
			return fmt.Errorf("the map file %s: %w", path, err)
		}
		sources = append(sources, changelog.MapSource{Label: "the map file " + path, Map: m})
	}
	if optionalBool(kw, "from_journal", false) {
		journal, found, err := historyrewrite.ReadJournal(repo)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("safegit's rewrite journal records no rewrite in %s (its rewrites append to <git common dir>/safegit/rewrite-maps.jsonl), so --from-journal has no map to read", root)
		}
		sources = append(sources, changelog.MapSource{Label: journal.Label(), Map: journal.CommitMap})
	}
	if optionalBool(kw, "stdin", false) {
		data, err := io.ReadAll(stdin)
		if err != nil {
			return fmt.Errorf("reading standard input: %w", err)
		}
		m, err := git.ParseRewriteMap(string(data))
		if err != nil {
			return fmt.Errorf("standard input: %w", err)
		}
		sources = append(sources, changelog.MapSource{Label: "standard input", Map: m})
	}
	return invocation(ctx).RemapAll(repo, sources)
}
