package cli

import (
	"strings"
	"testing"

	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestCommitThroughTheApplication(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeSafegit(t)
	repo := releaseCommandsProject(t)
	repo.Write("generated.txt", "g\n")
	app := appWith(t, testsupport.NewFakeHTTP(t))

	if r := app.Test([]string{"commit", "--message", "regenerate", "--dry-run", "generated.txt"}); r.ExitCode == 0 || !strings.Contains(r.Stdout+r.Stderr, "safegit") {
		t.Fatalf("--dry-run was not refused: exit %d: %s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
	if r := app.Test([]string{"commit", "generated.txt"}); r.ExitCode == 0 || !strings.Contains(r.Stderr, "message") {
		t.Fatalf("a commit without --message: exit %d: %s", r.ExitCode, r.Stderr)
	}
	r := app.Test([]string{"commit", "--message", "regenerate", "generated.txt"})
	if r.ExitCode != 0 || !strings.Contains(r.Stdout, "Committed generated.txt with the Autogenerated trailer.") {
		t.Fatalf("exit %d: %s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
	if got := repo.Git("log", "-1", "--format=%s %(trailers:key=Autogenerated,valueonly)"); got != "regenerate true" {
		t.Fatalf("the commit is %q", got)
	}
}
