package cli

import (
	"path/filepath"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle/index"

	"github.com/stricttools/rlsbl/internal/migration"
)

const migrateGroupHelp = "The one-time conversion of a repository's rlsbl records from the layout the Python rlsbl wrote (.rlsbl/, " +
	".rlsbl-monorepo/, and each member's .rlsbl/) to the .strictmetadata/ layout this rlsbl reads."

const migrateRecordsHelp = "Convert the rlsbl records of the repository holding the working directory to the .strictmetadata/ layout, " +
	"once: the release declarations (releasables.toml, from every config.json, workspace.toml, and releasable.toml), the test " +
	"runner's settings, each releasable's changelog (every line restamped to format_version 2, an id minted where a line has none, " +
	"a batch exclusion moved onto the entry it exempts as batch_reason), its release file, archives, version file, and undo " +
	"audits, the batch release files, the transition record's surgery events, the scaffold state and merge bases, customized " +
	"hook scripts (each moved to .strictmetadata/release-hooks/ and run by a hooks declaration), .strictmetadata/go.mod, the " +
	"options entries of renamed options and of those that moved to strictcode, and strictcode.toml (the tool declarations, " +
	"the library lint lists, the dead-modules suppressions, and ruff-lint's coverage as strictcode's lint rule). It writes the " +
	"lifecycle-and-license record: one active lifecycle period and one license period per releasable from today, a retired " +
	"period per closed release history (whose release state moves to .strictmetadata/retired-release-histories/), the " +
	"releasable-name identities with their renames, the identity transitions (pending until their version is released), the " +
	"registry names of every releasable that publishes from CI and has released, and the unversioned tags; and it records the " +
	"repository's confidential names in the machine-local index. A license comes from the package manifests or from --licenses, " +
	"never from a LICENSE file. GitHub's visibility of the repository is read with gh. Every refusal is reported before anything " +
	"is written, each naming its fix: a value the new layout has no place for, a target other than go, npm, and pypi, a retired " +
	"key, a missing license, a private repository with no releasable declared proprietary, configs disagreeing on a " +
	"repository-wide value, a release or history rewrite in progress, a file of the old layout it does not recognize, and an " +
	"uncommitted change to any path it writes or removes. Otherwise it writes the new records, regenerates the changelogs, " +
	"removes the old layout through saferm, and commits exactly the paths it wrote or removed with the Autogenerated trailer; " +
	"uncommitted changes to other paths are listed and left alone. A repository already converted has nothing to do. Use " +
	"--dry-run to print, per file, the source, the destination, and the change, and every refusal, writing nothing."

func registerMigrate(r *commandSet, version string) {
	r.group([]string{"migrate"}, migrateGroupHelp)
	r.add(command{
		path:   []string{"migrate", "records"},
		help:   migrateRecordsHelp,
		effect: mutating,
		// Converting every record of a repository and committing the result
		// is the owner's call, repository by repository.
		consequential: true,
		flags: []strictcli.Flag{
			strictcli.StringFlag("licenses", "A TOML file mapping releasable names to an SPDX identifier or \"proprietary\" "+
				"(portal = \"MIT\"), for every releasable whose license the manifests do not state and every releasable that is "+
				"proprietary; without it, every license is read from the manifests", strictcli.Optional()),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			return nil, runMigrateRecords(ctx, kw, version)
		},
	})
}

func runMigrateRecords(ctx *strictcli.Context, kw map[string]any, version string) error {
	dir, root, err := workingRepository()
	if err != nil {
		return err
	}
	indexPath, err := index.DefaultPath()
	if err != nil {
		return err
	}
	req := migration.Request{Root: root, Now: time.Now(), RlsblVersion: version, IndexPath: indexPath}
	if file, ok := strictcli.GetOpt[string](kw, "licenses"); ok {
		if !filepath.IsAbs(file) {
			file = filepath.Join(dir, file)
		}
		licenses, err := migration.ReadLicenses(file)
		if err != nil {
			return err
		}
		req.Licenses, req.LicensesFile = licenses, file
	}
	return migration.Run(ctx, req)
}
