package cli

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/github"
	"github.com/stricttools/rlsbl/internal/scaffold"
	"github.com/stricttools/rlsbl/internal/workflows"
	"github.com/stricttools/rlsbl/internal/workspace"
)

const monorepoSyncHelp = "Regenerate the workspace's two routers in .github/workflows at the repository root. ci-router.yml inlines every member's own CI jobs " +
	"(the member's .github/workflows/ci.yml and ci-*.yml) under keys and names prefixed with the member and file, and runs each member's jobs " +
	"when its path filter matched the push or when the router is dispatched with run_all=true; each member's filter is derived from the " +
	"workspace (its directory, its dependencies' directories, the root manifests and lockfiles, the router, and its releasable's changelog " +
	"file), never declared. publish.yml inlines the publish jobs of every member whose releasable publishes from CI (the member's " +
	".github/workflows/publish.yml), each run only for its releasable's tags, behind " +
	"one wait-for-ci job that holds every publish until the releasing project's CI passed on the release commit. A root member publishing " +
	"from CI has its jobs rendered from scaffold's templates, as scaffold would render its publish.yml, since that file is the router itself. Jobs are inlined because " +
	"GitHub refuses a workflow calling 20 or more reusable workflows. Both routers are written read-only and start with a generated-file " +
	"header. A member whose Python package directory is named other than the member gets that name declared as its import_name. Removed " +
	"through saferm: a generated router left with nothing to route, the publish workflows of members publishing nothing, and the per-member " +
	"workflow copies earlier versions of this command wrote at the root. Everything is derived before anything is written, so a refusal " +
	"changes nothing. --auto-commit commits what was written and removed, with the Autogenerated trailer."

// syncPayload is monorepo sync's payload.
type syncPayload = workflows.SyncResult

func registerMonorepoSync(r *commandSet) {
	r.add(command{
		path:   []string{"monorepo", "sync"},
		help:   monorepoSyncHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.BoolFlag("auto-commit", "Commit what sync wrote and removed, with the Autogenerated trailer (--no-auto-commit leaves it uncommitted)", strictcli.Required()),
		},
		payload: syncPayloadSchema(),
		render:  renderSync,
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			cwd, err := os.Getwd()
			if err != nil {
				return nil, err
			}
			root, err := declarations.FindRepositoryRoot(cwd)
			if err != nil {
				return nil, err
			}
			w, err := workspace.Load(root)
			if err != nil {
				return nil, err
			}
			actions, err := scaffold.ActionVersions()
			if err != nil {
				return nil, err
			}
			gh, err := github.New(ctx.Effects())
			if err != nil {
				return nil, err
			}
			now := time.Now()
			result, err := workflows.Sync(ctx.Effects(), w, workflows.SyncInputs{
				Actions: actions,
				RootPublishWorkflow: func(root declarations.Member) (string, error) {
					return scaffold.MemberPublishWorkflow(ctx.Effects(), w, root, gh, now)
				},
				AutoCommit: strictcli.Get[bool](kw, "auto_commit"),
				DryRun:     ctx.DryRun(),
			})
			if err != nil {
				return nil, err
			}
			if result.ImportNames == nil {
				result.ImportNames = []workflows.ImportName{}
			}
			if result.Written == nil {
				result.Written = []string{}
			}
			if result.Removed == nil {
				result.Removed = []string{}
			}
			return result, nil
		},
	})
}

func syncPayloadSchema() map[string]any {
	strs := map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"import_names": map[string]any{"type": "array", "items": map[string]any{
				"type":                 "object",
				"properties":           map[string]any{"member": map[string]any{"type": "string"}, "import_name": map[string]any{"type": "string"}},
				"required":             []any{"member", "import_name"},
				"additionalProperties": false,
			}},
			"written":   strs,
			"removed":   strs,
			"committed": map[string]any{"type": "boolean"},
			"dry_run":   map[string]any{"type": "boolean"},
		},
		"required":             []any{"import_names", "written", "removed", "committed", "dry_run"},
		"additionalProperties": false,
	}
}

func renderSync(payload any) string {
	p, err := decodePayload[syncPayload](payload)
	if err != nil {
		return renderJSON(payload)
	}
	declared, wrote, removed := "Declared", "Wrote", "Removed"
	if p.DryRun {
		declared, wrote, removed = "Would declare", "Would write", "Would remove"
	}
	var lines []string
	for _, n := range p.ImportNames {
		lines = append(lines, fmt.Sprintf("%s import_name %q for %s", declared, n.ImportName, n.Member))
	}
	for _, f := range p.Written {
		lines = append(lines, wrote+" "+f)
	}
	for _, f := range p.Removed {
		lines = append(lines, removed+" "+f)
	}
	switch {
	case len(lines) == 0:
		lines = append(lines, "The routers are current; nothing was written.")
	case p.DryRun:
		lines = append(lines, "Nothing would be committed: a preview makes no commit.")
	case p.Committed:
		lines = append(lines, "Committed: "+workflows.SyncCommitMessage)
	default:
		lines = append(lines, "Nothing was committed.")
	}
	return strings.Join(lines, "\n")
}
