package cli

import (
	"os"
	"strings"
	"testing"

	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/options"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestOptionsRegistryPrintsTheShippedDocument(t *testing.T) {
	hygiene.Isolate(t)
	reg, err := options.Shipped()
	if err != nil {
		t.Fatal(err)
	}
	r := appWith(t, testsupport.NewFakeHTTP(t)).Test([]string{"options", "registry"})
	if r.ExitCode != 0 || strings.TrimSuffix(r.Stdout, "\n") != strings.TrimSuffix(string(reg.Document()), "\n") {
		t.Fatalf("exit %d:\n%s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
}

func TestOptionsRegistryJSONCarriesTheDeclarations(t *testing.T) {
	hygiene.Isolate(t)
	reg, err := options.Shipped()
	if err != nil {
		t.Fatal(err)
	}
	r := appWith(t, testsupport.NewFakeHTTP(t)).Test([]string{"options", "registry", "--json"})
	if r.ExitCode != 0 {
		t.Fatalf("exit %d:\n%s", r.ExitCode, r.Stderr)
	}
	p := jsonPayload(t, r)
	if p["format_version"].(float64) != 2 {
		t.Fatalf("format_version %v", p["format_version"])
	}
	declared := p["option"].([]any)
	if len(declared) != len(reg.Names()) {
		t.Fatalf("%d options in the payload, %d in the registry", len(declared), len(reg.Names()))
	}
	found := false
	for _, o := range declared {
		d := o.(map[string]any)
		if d["name"] == options.EcosystemTagging {
			found = d["values"] == "on > off" && d["default"] == "on" && d["subject"] == "project"
		}
	}
	if !found {
		t.Fatalf("ecosystem-tagging is not declared as registered: %v", declared)
	}
}

// optionsRepository is a repository with no release declarations, the
// working directory for the rest of the test, with safegit faked.
func optionsRepository(t *testing.T) *testsupport.Repo {
	t.Helper()
	testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	repo.CommitFile("README.md", "portal\n", "first")
	hygiene.Chdir(t, repo.Dir)
	return repo
}

func readText(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestOptionsSetCreatesTheDocumentAndManifestAndCommits(t *testing.T) {
	hygiene.Isolate(t)
	repo := optionsRepository(t)
	r := appWith(t, testsupport.NewFakeHTTP(t)).Test([]string{"options", "set", "rlsbl:ecosystem-tagging", "--current", "off", "--ideal", "on", "--reason", "the topic is added once the repository is public"})
	if r.ExitCode != 0 || !strings.Contains(r.Stdout, "Created rlsbl:ecosystem-tagging in .strictmetadata/options/project.toml: current off, ideal on") || !strings.Contains(r.Stdout, "Committed.") {
		t.Fatalf("exit %d:\n%s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
	doc := readText(t, repo.Path(".strictmetadata/options/project.toml"))
	if !strings.Contains(doc, "id = \"rlsbl:ecosystem-tagging\"\ncurrent = \"off\"\nideal = \"on\"") {
		t.Fatalf("project.toml:\n%s", doc)
	}
	if got := readText(t, repo.Path(".strictmetadata/options/manifest.toml")); got != "owner = \"strictspec\"\n" {
		t.Fatalf("manifest.toml: %q", got)
	}
	message := repo.Git("log", "-1", "--format=%B")
	if !strings.Contains(message, "rlsbl options set rlsbl:ecosystem-tagging") || !strings.Contains(message, "Autogenerated: true") {
		t.Fatalf("the commit: %q", message)
	}
	if status := repo.Git("status", "--porcelain"); status != "" {
		t.Fatalf("left uncommitted: %s", status)
	}
}

func TestOptionsSetDryRunWritesNothing(t *testing.T) {
	hygiene.Isolate(t)
	repo := optionsRepository(t)
	r := appWith(t, testsupport.NewFakeHTTP(t)).Test([]string{"options", "set", "rlsbl:ecosystem-tagging", "--current", "off", "--ideal", "on", "--reason", "not yet public", "--dry-run"})
	if r.ExitCode != 0 || !strings.Contains(r.Stdout, "Dry run: would write rlsbl:ecosystem-tagging") {
		t.Fatalf("exit %d:\n%s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
	if _, err := os.Stat(repo.Path(".strictmetadata/options")); !os.IsNotExist(err) {
		t.Fatalf("the dry run wrote: %v", err)
	}
}

func TestOptionsSetUpdatesAnEntryKeepingEveryOtherLine(t *testing.T) {
	hygiene.Isolate(t)
	repo := optionsRepository(t)
	repo.Write(".strictmetadata/options/manifest.toml", "owner = \"strictspec\"\n")
	repo.Write(".strictmetadata/options/project.toml", "format_version = 1\n\n# Kept by hand.\n[[entry]]\nid = \"rlsbl:ecosystem-tagging\"\ncurrent = \"off\"\nideal = \"on\"\nreason = \"first\"\n")
	repo.Commit("options", ".strictmetadata/options/manifest.toml", ".strictmetadata/options/project.toml")
	r := appWith(t, testsupport.NewFakeHTTP(t)).Test([]string{"options", "set", "rlsbl:ecosystem-tagging", "--current", "off", "--ideal", "on", "--reason", "second", "--no-auto-commit"})
	if r.ExitCode != 0 || !strings.Contains(r.Stdout, "Updated rlsbl:ecosystem-tagging") || strings.Contains(r.Stdout, "Committed.") {
		t.Fatalf("exit %d:\n%s%s", r.ExitCode, r.Stdout, r.Stderr)
	}
	doc := readText(t, repo.Path(".strictmetadata/options/project.toml"))
	if !strings.Contains(doc, "# Kept by hand.") || !strings.Contains(doc, "reason = \"second\"") || strings.Contains(doc, "first") {
		t.Fatalf("project.toml:\n%s", doc)
	}
	if status := repo.Git("status", "--porcelain"); !strings.Contains(status, "project.toml") {
		t.Fatalf("--no-auto-commit committed: %q", status)
	}
}

func TestOptionsSetRefusesWhatStrictspecRefuses(t *testing.T) {
	hygiene.Isolate(t)
	repo := optionsRepository(t)
	app := appWith(t, testsupport.NewFakeHTTP(t))
	cases := []struct {
		name string
		argv []string
		want string
	}{
		{"another tool's id", []string{"strictcode:lint", "--current", "off", "--ideal", "error", "--reason", "x"}, "not of rlsbl"},
		{"a value the option does not declare", []string{"rlsbl:ecosystem-tagging", "--current", "maybe", "--ideal", "on", "--reason", "x"}, "refused, so nothing was written"},
		{"a scope where no member is declared", []string{"rlsbl:test-sandbox", "--current", "on", "--ideal", "on", "--reason", "x", "--scope", "packages/widget"}, "declares no members"},
		{"an empty scope", []string{"rlsbl:test-sandbox", "--current", "on", "--ideal", "on", "--reason", "x", "--scope", ""}, "--scope must not be empty"},
		{"an empty reason", []string{"rlsbl:ecosystem-tagging", "--current", "off", "--ideal", "on", "--reason", ""}, "--reason must not be empty"},
	}
	for _, c := range cases {
		r := app.Test(append([]string{"options", "set"}, c.argv...))
		if r.ExitCode != 1 || !strings.Contains(r.Stderr, c.want) {
			t.Errorf("%s: exit %d:\n%s", c.name, r.ExitCode, r.Stderr)
		}
	}
	if _, err := os.Stat(repo.Path(".strictmetadata/options/project.toml")); !os.IsNotExist(err) {
		t.Fatal("a refused entry was written")
	}
}

func TestOptionsSetRefusesAManifestNamingAnotherOwnerAndTheNamedLineFixesIt(t *testing.T) {
	hygiene.Isolate(t)
	repo := optionsRepository(t)
	repo.Write(".strictmetadata/options/manifest.toml", "owner = \"strictcode\"\n")
	app := appWith(t, testsupport.NewFakeHTTP(t))
	argv := []string{"options", "set", "rlsbl:ecosystem-tagging", "--current", "off", "--ideal", "on", "--reason", "not yet public"}
	r := app.Test(argv)
	if r.ExitCode != 1 || !strings.Contains(r.Stderr, "Write this line instead:\nowner = \"strictspec\"") {
		t.Fatalf("exit %d:\n%s", r.ExitCode, r.Stderr)
	}
	repo.Write(".strictmetadata/options/manifest.toml", "owner = \"strictspec\"\n")
	if r := app.Test(argv); r.ExitCode != 0 {
		t.Fatalf("the named line did not clear the refusal: exit %d:\n%s", r.ExitCode, r.Stderr)
	}
}
