package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	tomledit "github.com/stricttools/go-toml-edit"
	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/options"
)

const optionsGroupHelp = "Print rlsbl's options registry, and write this repository's entries for rlsbl's options in .strictmetadata/options/ " +
	"at its git root. Every rlsbl check is an option, rlsbl:<check name>, ranked error > warn > off for an error check and warn > off for a " +
	"warning check, and a few options are not checks; `rlsbl options registry` lists every one. `rlsbl check` and every release apply each " +
	"entry's current value (off: the check does not run; warn: it runs and reports, never blocking; error: as registered). The options " +
	"representing an adoption default to off and accept a path scope naming one workspace member. Invalid entries stop every check run and " +
	"every release."

const optionsRegistryHelp = "Print rlsbl's options registry: one option per check, rlsbl:<check name>, plus the options that are not checks, " +
	"each with the subject file its entries are filed under, the values it ranks strongest first, its default, its scope type, the options it " +
	"requires, and what it governs. The TOML printed is the registry document rlsbl ships, in the shape of strictspec's built-in " +
	"options-registry schema; with --json the same declarations are the payload. Needs no rlsbl project."

const optionsSetHelp = "Write one rlsbl entry into .strictmetadata/options/<subject>.toml at the repository's git root, or update the entry " +
	"already there for the same option and scope, keeping every other line of the document. The subject file is the one the option's registry " +
	"declaration names. Creates .strictmetadata/options/ and its manifest.toml, naming strictspec as the owner, when absent. strictspec " +
	"validates the result before anything is written (every document's shape, and every rlsbl entry with this one in place), and each refusal " +
	"is its catalogued diagnostic: an unknown option, a value the option does not declare, a current ranked above the ideal, an entry equal to " +
	"the default, an empty reason, an option switched off while an option requiring it is not. A --scope must name a workspace member's path " +
	"as .strictmetadata/releasables/releasables.toml declares it, and only the options declaring the path scope type accept one. Refuses an id " +
	"outside the rlsbl namespace and a manifest naming another owner. The written files are committed with the Autogenerated trailer unless " +
	"--no-auto-commit is passed."

func registerOptions(r *commandSet) {
	r.group([]string{"options"}, optionsGroupHelp)
	r.add(command{
		path:    []string{"options", "registry"},
		help:    optionsRegistryHelp,
		effect:  readOnly,
		payload: optionsRegistryPayloadSchema(),
		render:  renderOptionsRegistry,
		run:     runOptionsRegistry,
	})
	r.add(command{
		path:   []string{"options", "set"},
		help:   optionsSetHelp,
		effect: mutating,
		args: []strictcli.Arg{
			strictcli.NewArg("id", "The option, as rlsbl:<name> (rlsbl:dep-floors, say); `rlsbl options registry` names every option", strictcli.ArgRequired()),
		},
		flags: []strictcli.Flag{
			strictcli.StringFlag("current", "The value the repository runs the option at now: error, warn, or off for an error check; warn or off for a "+
				"warning check; the values `rlsbl options registry` lists for any other option", strictcli.Required()),
			strictcli.StringFlag("ideal", "The value the repository should run the option at: one the option declares, never ranked below current, or "+
				"non-existent when the right value is one rlsbl does not offer yet", strictcli.Required()),
			strictcli.StringFlag("reason", "Why the repository deviates from the option's default, in one sentence, recorded in the entry as written", strictcli.Required()),
			strictcli.StringFlag("scope", "Narrow the entry to one workspace member, named by its path (packages/widget, say); accepted only by the "+
				"options declaring the path scope type. Without it the entry covers the whole repository", strictcli.Optional()),
			strictcli.BoolFlag("auto-commit", "Commit the written files with the Autogenerated trailer (committed when neither --auto-commit nor "+
				"--no-auto-commit is passed)", strictcli.Optional()),
		},
		payload: optionsSetPayloadSchema(),
		render:  renderOptionsSet,
		run:     runOptionsSet,
	})
}

// optionDeclaration is one option in options registry's payload.
type optionDeclaration struct {
	Name        string   `json:"name"`
	Subject     string   `json:"subject"`
	Values      string   `json:"values"`
	Default     string   `json:"default"`
	Scope       string   `json:"scope"`
	Requires    []string `json:"requires"`
	Description string   `json:"description"`
}

// optionsRegistryPayload is options registry's payload: the registry
// document's declarations.
type optionsRegistryPayload struct {
	FormatVersion int64               `json:"format_version"`
	Option        []optionDeclaration `json:"option"`
}

func optionsRegistryPayloadSchema() map[string]any {
	str := map[string]any{"type": "string"}
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"format_version": map[string]any{"type": "integer"},
			"option": map[string]any{"type": "array", "items": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": str, "subject": str, "values": str, "default": str, "scope": str,
					"requires":    map[string]any{"type": "array", "items": str},
					"description": str,
				},
				"required":             []any{"name", "subject", "values", "default", "scope", "requires", "description"},
				"additionalProperties": false,
			}},
		},
		"required":             []any{"format_version", "option"},
		"additionalProperties": false,
	}
}

// registryFormatVersion is the format_version the registry document
// declares.
func registryFormatVersion(document []byte) (int64, error) {
	doc, err := tomledit.Unmarshal[map[string]any](document)
	if err != nil {
		return 0, fmt.Errorf("the options registry does not parse: %w", err)
	}
	v, ok := (*doc)["format_version"].(int64)
	if !ok {
		return 0, errors.New("the options registry declares no integer format_version")
	}
	return v, nil
}

func runOptionsRegistry(*strictcli.Context, map[string]any) (any, error) {
	reg, err := options.Shipped()
	if err != nil {
		return nil, err
	}
	version, err := registryFormatVersion(reg.Document())
	if err != nil {
		return nil, err
	}
	p := optionsRegistryPayload{FormatVersion: version, Option: []optionDeclaration{}}
	for _, name := range reg.Names() {
		d, _ := reg.Declaration(name)
		p.Option = append(p.Option, optionDeclaration{
			Name: d.Name, Subject: d.Subject, Values: d.Values, Default: d.Default, Scope: d.Scope,
			Requires: append([]string{}, d.Requires...), Description: d.Description,
		})
	}
	return p, nil
}

// renderOptionsRegistry is the registry document rlsbl ships, byte for
// byte but its final newline; the payload carries the same declarations.
func renderOptionsRegistry(payload any) string {
	reg, err := options.Shipped()
	if err != nil {
		return renderJSON(payload)
	}
	return strings.TrimSuffix(string(reg.Document()), "\n")
}

// optionsSetPayload is options set's payload.
type optionsSetPayload struct {
	ID string `json:"id"`
	// File is the subject document, repository-relative.
	File string `json:"file"`
	// Scope is null for an entry without one.
	Scope   *string `json:"scope"`
	Action  string  `json:"action"`
	Current string  `json:"current"`
	Ideal   string  `json:"ideal"`
	Reason  string  `json:"reason"`
	// Class is the entry's classification: settled, debt, or
	// waiting-on-tool.
	Class     string   `json:"class"`
	Written   []string `json:"written"`
	Committed bool     `json:"committed"`
	// DryRun says the files were not written: Action and Written are what
	// the run would have done.
	DryRun bool `json:"dry_run"`
}

func optionsSetPayloadSchema() map[string]any {
	str := map[string]any{"type": "string"}
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"id": str, "file": str,
			"scope":   map[string]any{"type": []any{"string", "null"}},
			"action":  map[string]any{"type": "string", "enum": []any{options.ActionCreated, options.ActionUpdated, options.ActionUnchanged}},
			"current": str, "ideal": str, "reason": str, "class": str,
			"written":   map[string]any{"type": "array", "items": str},
			"committed": map[string]any{"type": "boolean"},
			"dry_run":   map[string]any{"type": "boolean"},
		},
		"required":             []any{"id", "file", "scope", "action", "current", "ideal", "reason", "class", "written", "committed", "dry_run"},
		"additionalProperties": false,
	}
}

// optionalDeclarations are the repository's release declarations, nil when
// it has none: an options entry may be written in any repository, and only
// a path scope needs members to name.
func optionalDeclarations(root string) (*declarations.Releasables, error) {
	_, err := os.Stat(filepath.Join(root, filepath.FromSlash(declarations.ReleasablesFile)))
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return declarations.Load(root)
}

func runOptionsSet(ctx *strictcli.Context, kw map[string]any) (any, error) {
	req := options.SetRequest{
		ID:      strictcli.Get[string](kw, "id"),
		Current: strictcli.Get[string](kw, "current"),
		Ideal:   strictcli.Get[string](kw, "ideal"),
		Reason:  strictcli.Get[string](kw, "reason"),
	}
	if req.ID == "" {
		return nil, errors.New("the option id must not be empty; `rlsbl options registry` names every option")
	}
	if err := requireNonEmpty(kw, "current", "ideal", "reason"); err != nil {
		return nil, err
	}
	scope, scoped := strictcli.GetOpt[string](kw, "scope")
	if scoped && scope == "" {
		return nil, errors.New("--scope must not be empty; leave it out for an entry covering the whole repository")
	}
	req.Scope = scope
	autoCommit, stated := strictcli.GetOpt[bool](kw, "auto_commit")
	if !stated {
		autoCommit = true
	}
	_, root, err := workingRepository()
	if err != nil {
		return nil, err
	}
	reg, err := options.Shipped()
	if err != nil {
		return nil, err
	}
	d, err := optionalDeclarations(root)
	if err != nil {
		return nil, err
	}
	result, err := options.Set(ctx.Effects(), reg, root, d, req)
	if err != nil {
		return nil, err
	}
	p := optionsSetPayload{
		ID: result.ID, File: result.File, Action: result.Action, Current: result.Current, Ideal: result.Ideal, Reason: result.Reason,
		Class: result.Class, Written: append([]string{}, result.Written...), DryRun: ctx.DryRun(),
	}
	if result.Scope != "" {
		scope := result.Scope
		p.Scope = &scope
	}
	if !ctx.DryRun() && autoCommit && len(result.Written) > 0 {
		repo, err := git.Open(ctx.Effects(), root)
		if err != nil {
			return p, err
		}
		if p.Committed, err = repo.Commit(git.CommitRequest{Message: "rlsbl options set " + result.ID, Paths: result.Written, Autogenerated: true}); err != nil {
			return p, err
		}
	}
	return p, nil
}

func renderOptionsSet(payload any) string {
	p, err := decodePayload[optionsSetPayload](payload)
	if err != nil {
		return renderJSON(payload)
	}
	scoped := ""
	if p.Scope != nil {
		scoped = fmt.Sprintf(" (scope %q)", *p.Scope)
	}
	summary := fmt.Sprintf("current %s, ideal %s (%s)", p.Current, p.Ideal, p.Class)
	switch {
	case p.DryRun && p.Action != options.ActionUnchanged:
		return fmt.Sprintf("Dry run: would write %s%s in %s: %s.", p.ID, scoped, p.File, summary)
	case p.Action == options.ActionUnchanged:
		return fmt.Sprintf("%s already holds %s%s: %s.", p.File, p.ID, scoped, summary)
	}
	line := fmt.Sprintf("%s%s %s%s in %s: %s.", strings.ToUpper(p.Action[:1]), p.Action[1:], p.ID, scoped, p.File, summary)
	if p.Committed {
		line += " Committed."
	}
	return line
}
