package cli

import (
	"errors"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle/index"

	"github.com/stricttools/rlsbl/internal/releaseops"
)

const releaseEditHelp = "Rewrite one released version's GitHub Release in place from the record: the notes its changelog holds, the deprecate and " +
	"yank notices its release archive records on top, the rlsbl-ci-sha marker naming the commit it shipped from, and the pre-release flag, set " +
	"when a notice is recorded and cleared otherwise. The version defaults to the latest release the archives record. A version the record holds no release " +
	"of, and one without a GitHub Release, are refused before anything is written. Run from the directory of a member versioned under the " +
	"releasable."

const releaseRetryHelp = "Dispatch the workflows of the releasable's latest release again at its tag, for a release whose GitHub Release exists " +
	"while its publish runs never started or failed for reasons outside it. A retry publishes again, so before anything is written or " +
	"dispatched it is refused what release validation refuses: a releasable or member on hold or retired, a repository whose visibility " +
	"disagrees with the lifecycle-and-license record, and an output the publishing rules forbid in the declarations or the tagged tree's " +
	"workflows. What is dispatched is the retry file, " +
	".strictmetadata/.release-state/<releasable>/retry.toml: ref, which must be the release tag (any other ref is refused, since a run there " +
	"cannot be tied to the release), and the workflow files. A missing retry file is written first, naming every workflow of the tagged tree " +
	"with a workflow_dispatch trigger. A workflow declaring a tag input is passed the tag. Workflows are dispatched one at a time; a dispatch " +
	"that fails stops the run with the retry file rewritten to hold the workflows not yet dispatched, so running retry again never dispatches " +
	"one twice, and the file is removed once every workflow was dispatched. --watch then watches the dispatched runs until they conclude and " +
	"exits 1 unless every one passed; --no-watch prints the command that watches them."

const releaseUndoHelp = "Revert a release. Without --version, the releasable's latest release (the highest version its release archives " +
	"record as released): delete its GitHub Release and its tags here and on origin, revert its version-bump commit, restore its changelog " +
	"entries to the unreleased file and its archive as the release file, regenerate the changelog, commit that as one commit, and push the " +
	"release branch. With --version, an earlier release: its GitHub Release and tags are deleted and its changelog and release file restored, " +
	"and its commits are not reverted, since history moved on. Either way the version must be provably unpublished: among the registries' " +
	"package listings (no request names one version), origin's Go module tags, and the runs of the publish workflows its tag started, a " +
	"source must have observed the version's absence and none may have seen it published or be publishing it; otherwise the undo is refused, " +
	"naming release yank and release deprecate. A release in progress that the archives do not record refuses the undo, naming release resume " +
	"and release abandon. Every refusal comes before anything is written, a conflict of the revert with later work included; an audit line " +
	"recording the plan and its evidence is appended to .strictmetadata/releases/<releasable>/undo-audits.jsonl and committed before the first " +
	"deletion. --dry-run prints the plan and writes nothing."

const releaseAbandonHelp = "Record an abandoned release attempt's version as never released: write its release archive with never_released = " +
	"true, commit it with the Autogenerated trailer, and delete the in-progress state file, as one operation. The version comes from the " +
	"in-progress state, or from the version files when there is none. The attempt's commits are not reverted: the next release bumps from the " +
	"abandoned version when the version files name it, and never releases under it again. When the in-progress state names a version already " +
	"recorded never released, an earlier abandon stopped part-way, and this one finishes it. Refused before anything is written: nothing to " +
	"abandon (no in-progress state, and the version files name a version the record already holds), a version already archived as a release, " +
	"a version below the latest release, the attempt's tag here or on origin (a tag is evidence of a release, which release backfill adopts), " +
	"and a GitHub Release under the attempt's tag (a published release, which release undo reverts). A question that cannot be answered is " +
	"refused, never read as absence."

const releaseDeprecateHelp = "Mark a release deprecated, the latest one included. The notice (\"> **Deprecated:** <reason>. Use v<use> instead.\") is recorded first " +
	"in the version's release archive (release_notices) and committed, so every later rewrite of the Release keeps it; the GitHub Release is " +
	"then rewritten from the record with the notice on top and the pre-release flag set. A version the record holds no release of and one " +
	"without a GitHub Release are refused before anything is written. --use must name a " +
	"version the record holds as released."

const releaseYankHelp = "Remove a published version, the latest one included, from its registries the way each allows, and mark its GitHub Release. Each package of " +
	"the releasable's members is looked up in its registry's listing (npm's package document, PyPI's project document, origin's Go module tag " +
	"and the module proxy's version list; no request names one version), and a package whose publication cannot be read refuses the yank " +
	"before anything is written. For each published package: npm deprecates the version (npm deprecate, run in the package's directory); a Go " +
	"module gains a retract directive in its go.mod, committed, which the next release publishes; PyPI, which offers no yank to a tool, is " +
	"yanked by hand, and the command exits 1 naming the steps until PyPI's project document shows the release's files yanked. Nothing is " +
	"ever unpublished. The yank notice is recorded in the version's release archive and committed, and the Release rewritten from the record " +
	"with the notice on top, marked pre-release. A releasable whose current license is proprietary is refused before anything is read, since " +
	"no registry write is made for it; release deprecate marks its Release without one. A version the record holds no release of and one " +
	"without a GitHub Release are refused before anything is written."

// noticeFlags are deprecate's and yank's flags.
func noticeFlags(verb string) []strictcli.Flag {
	return []strictcli.Flag{
		strictcli.StringFlag("reason", "Why the version is "+verb+"; it opens the notice", strictcli.Optional()),
		strictcli.StringFlag("use", "The released version to use instead, bare (0.5.0); the notice names it", strictcli.Optional()),
	}
}

func registerReleaseOps(r *commandSet) {
	r.add(command{
		path:   []string{"release", "edit"},
		help:   releaseEditHelp,
		effect: mutating,
		args: []strictcli.Arg{
			strictcli.NewArg("version", "The released version whose Release is rewritten, bare (0.4.0); the latest release when omitted", strictcli.ArgOptional()),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			version, given := strictcli.GetOpt[string](kw, "version")
			if given && version == "" {
				return nil, emptyArgument("version")
			}
			dir, _, err := workingRepository()
			if err != nil {
				return nil, err
			}
			indexPath, err := index.DefaultPath()
			if err != nil {
				return nil, err
			}
			return nil, releaseops.Edit(ctx, releaseops.EditRequest{Dir: dir, Version: version, IndexPath: indexPath})
		},
	})
	r.add(command{
		path:   []string{"release", "retry"},
		help:   releaseRetryHelp,
		effect: mutating,
		// Only a person decides that a release's publish runs start again:
		// a second publish run of a version that did publish fails, or
		// publishes twice where a registry allows it.
		consequential: true,
		flags: []strictcli.Flag{
			strictcli.BoolFlag("watch", "Watch the dispatched runs until they conclude (--no-watch prints the command that watches them)", strictcli.Required()),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			dir, _, err := workingRepository()
			if err != nil {
				return nil, err
			}
			return nil, releaseops.Retry(ctx, releaseops.RetryRequest{Dir: dir, Watch: strictcli.Get[bool](kw, "watch"), Sleep: time.Sleep})
		},
	})
	r.add(command{
		path:   []string{"release", "undo"},
		help:   releaseUndoHelp,
		effect: mutating,
		// Undo deletes a GitHub Release and tags on origin, and reverts
		// commits on the release branch: only a person decides that.
		consequential: true,
		flags: []strictcli.Flag{
			strictcli.StringFlag("version", "An earlier release to undo, bare (0.3.0), without reverting its commits; the latest release when omitted", strictcli.Optional()),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			req := releaseops.UndoRequest{Now: time.Now}
			var given bool
			if req.Version, given = strictcli.GetOpt[string](kw, "version"); given && req.Version == "" {
				return nil, emptyArgument("--version")
			}
			var err error
			if req.Dir, _, err = workingRepository(); err != nil {
				return nil, err
			}
			return nil, releaseops.Undo(ctx, req)
		},
	})
	r.add(command{
		path:   []string{"release", "abandon"},
		help:   releaseAbandonHelp,
		effect: mutating,
		// Recording a version as never released is permanent: the number is
		// never released under again.
		consequential: true,
		run: func(ctx *strictcli.Context, _ map[string]any) (any, error) {
			dir, _, err := workingRepository()
			if err != nil {
				return nil, err
			}
			return nil, releaseops.Abandon(ctx, releaseops.AbandonRequest{Dir: dir})
		},
	})
	for _, op := range []struct {
		name, help, verb string
		run              func(*strictcli.Context, releaseops.NoticeRequest) error
	}{
		{"deprecate", releaseDeprecateHelp, "deprecated", releaseops.Deprecate},
		{"yank", releaseYankHelp, "yanked", releaseops.Yank},
	} {
		r.add(command{
			path:   []string{"release", op.name},
			help:   op.help,
			effect: mutating,
			// A notice on a published Release, and a yank's registry writes,
			// are what consumers of the version see: only a person decides
			// them.
			consequential: true,
			args: []strictcli.Arg{
				strictcli.NewArg("version", "The released version, bare (0.3.0)", strictcli.ArgRequired()),
			},
			flags: noticeFlags(op.verb),
			run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
				req := releaseops.NoticeRequest{Version: strictcli.Get[string](kw, "version")}
				if req.Version == "" {
					return nil, emptyArgument("version")
				}
				var given bool
				if req.Reason, given = strictcli.GetOpt[string](kw, "reason"); given && req.Reason == "" {
					return nil, emptyArgument("--reason")
				}
				if req.Use, given = strictcli.GetOpt[string](kw, "use"); given && req.Use == "" {
					return nil, emptyArgument("--use")
				}
				var err error
				if req.Dir, _, err = workingRepository(); err != nil {
					return nil, err
				}
				if req.IndexPath, err = index.DefaultPath(); err != nil {
					return nil, err
				}
				return nil, op.run(ctx, req)
			},
		})
	}
}

// emptyArgument refuses an argument given as the empty string.
func emptyArgument(name string) error {
	return errors.New(name + " must not be empty")
}
