package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/options"
	"github.com/stricttools/rlsbl/internal/rewrite"
)

// rewriteGroupHelp is the rewrite group's help.
const rewriteGroupHelp = "Sweeping rewrites of the current working tree, each previewed before it is performed. Every command in this group observes the tree, " +
	"reports a per-file plan with occurrence counts, and refuses to apply when a count moved between the preview and the write, naming what it already wrote."

const goModulePathHelp = "Rename one Go module path across the repository containing the working directory. Rewrites the module-path tokens in every go.mod " +
	"(the module directive plus any require, replace, exclude, or retract reference from another module) and every Go import site under the old path, located " +
	"with go/parser and rewritten at the bytes of the import's string literal, keeping its quote form. A module nested under the old path with a go.mod of " +
	"its own is another module: its path and its packages' imports are left alone, since the longest declared module path owns every token and import, and " +
	"it is renamed by an invocation of its own. The committed strictcli schema dump moves with it: the top-level project_id of every " +
	".strictmetadata/.cli-schema/schema.json under the old module path is rewritten too. Containment is boundary-aware, so a neighboring module whose path " +
	"merely begins with the same letters is left alone. The files considered are what `git ls-files --cached --others --exclude-standard` lists, minus " +
	"vendor/ trees and the experiments/ and screenshots/ directories at the root, so an ignored third-party clone is never touched, and neither are comments " +
	"or any file but a go.mod, a Go source, or a schema dump. A rename that finds nothing to rewrite is refused, naming the module paths declared here, " +
	"since the likely cause is a mistyped --from-module; a Go file that does not parse is refused, naming it. Use --dry-run to print the per-file plan with " +
	"occurrence counts."

const projectNameHelp = "Rename a standalone project's published identity. Rewrites the package name in every target manifest whose name is a manifest " +
	"field (npm package.json \"name\", PyPI pyproject.toml [project].name), and for a Go target moves the module path to one whose last element is --to, " +
	"through the same rewrite as `rlsbl rewrite go-module-path`. Records each changed identity as a pending identity in the lifecycle-and-license record " +
	"(.strictmetadata/lifecycle-and-license/lifecycle-and-license.toml): package-name, and go-module-path when the latest release published another module " +
	"path (read from go.mod at its release commit). Each pending identity takes effect from the version the next release ships, decided as `rlsbl release " +
	"run` decides it (the release file's bump from the version files, or the version as it is for a project that never released; from version files naming " +
	"an unrecoverable version, the declared bump from it), keeps the registry and tag namespace of the identity it replaces, and becomes a dated period " +
	"when that version is released. The rename and the record are committed separately, so a crash between them is completed by running again; the record " +
	"commit carries the Autogenerated trailer, and the rename commit does not, so changelog coverage asks for the breaking entry the closing message prints. " +
	"Nothing else is touched: no source directory is moved, no command name (npm bin, PyPI [project.scripts]) is renamed, no registry is contacted, and no " +
	"repository is renamed; the closing message lists those remaining steps in order. Refuses, before writing anything, in a workspace (naming `rlsbl " +
	"monorepo rename-releasable`), when --from is not the name the manifests declare, when --from equals --to or --to is not a valid package name for every " +
	"target, when the release file is missing, when the next version cannot be decided the way the release decides it, when a Go target's latest release is " +
	"unrecoverable (the module path it published cannot be established), when another pending identity of the same facet is recorded, and on a dirty " +
	"working tree. Use --dry-run to print the per-file plan with occurrence counts and the pending identities it would record."

const uvPathSourcesHelp = "Convert the path- and workspace-sourced Python dependencies of the member whose directory holds the working directory into " +
	"registry constraints floored at the version uv.lock resolves. Covers [project].dependencies, every [project.optional-dependencies] extra, and every " +
	"PEP 735 [dependency-groups] group, keeping each entry's extras and environment marker, and deletes the matching [tool.uv.sources] entry so it stops " +
	"overriding the new constraint (a list of marker-gated sources loses only its path and workspace elements). The lock is the one beside pyproject.toml, " +
	"or the lock of the uv workspace root that claims the directory. Each converted name is added to the member's internal_dep_floors in " +
	".strictmetadata/releasables/releasables.toml, and the rlsbl:dep-floors option is switched on with an options entry (current and ideal error, scoped " +
	"to the member in a workspace) when it is off. Each locked version is checked against PyPI's project document, which lists every published version: a " +
	"version it does not list is refused, naming the fix (release that dependency first), and so is a document PyPI fails to answer. Use --dry-run to print " +
	"the per-dependency plan with entry counts."

func registerRewrite(r *commandSet) {
	r.group([]string{"rewrite"}, rewriteGroupHelp)
	r.add(command{
		path:   []string{"rewrite", "go-module-path"},
		help:   goModulePathHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.StringFlag("from-module", "The module path to rename", strictcli.Required()),
			strictcli.StringFlag("to-module", "The module path it becomes", strictcli.Required()),
		},
		run: runRewriteGoModulePath,
	})
	r.add(command{
		path:          []string{"rewrite", "project-name"},
		help:          projectNameHelp,
		effect:        mutating,
		consequential: true,
		flags: []strictcli.Flag{
			strictcli.StringFlag("from", "The package name the manifests declare now", strictcli.Required()),
			strictcli.StringFlag("to", "The package name they declare after the rename", strictcli.Required()),
		},
		run: runRewriteProjectName,
	})
	r.add(command{
		path:   []string{"rewrite", "uv-path-sources"},
		help:   uvPathSourcesHelp,
		effect: mutating,
		run:    runRewriteUvPathSources,
	})
}

// requireNonEmpty refuses a flag given an empty value.
func requireNonEmpty(kw map[string]any, names ...string) error {
	for _, n := range names {
		if strictcli.Get[string](kw, n) == "" {
			return fmt.Errorf("--%s must not be empty", strings.ReplaceAll(n, "_", "-"))
		}
	}
	return nil
}

// workingRepository is the working directory and the root of the git
// repository containing it.
func workingRepository() (dir, root string, err error) {
	dir, err = os.Getwd()
	if err != nil {
		return "", "", err
	}
	root, err = declarations.FindRepositoryRoot(dir)
	return dir, root, err
}

func runRewriteGoModulePath(ctx *strictcli.Context, kw map[string]any) (any, error) {
	if err := requireNonEmpty(kw, "from_module", "to_module"); err != nil {
		return nil, err
	}
	_, root, err := workingRepository()
	if err != nil {
		return nil, err
	}
	return nil, rewrite.RunGoModulePath(ctx, root, strictcli.Get[string](kw, "from_module"), strictcli.Get[string](kw, "to_module"))
}

func runRewriteProjectName(ctx *strictcli.Context, kw map[string]any) (any, error) {
	if err := requireNonEmpty(kw, "from", "to"); err != nil {
		return nil, err
	}
	_, root, err := workingRepository()
	if err != nil {
		return nil, err
	}
	return nil, rewrite.RunProjectName(ctx, root, strictcli.Get[string](kw, "from"), strictcli.Get[string](kw, "to"))
}

func runRewriteUvPathSources(ctx *strictcli.Context, kw map[string]any) (any, error) {
	dir, root, err := workingRepository()
	if err != nil {
		return nil, err
	}
	reg, err := options.Shipped()
	if err != nil {
		return nil, err
	}
	return nil, rewrite.RunUvPathSources(ctx, root, dir, reg)
}
