package cli

import (
	"fmt"
	"os"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/github"
	"github.com/stricttools/rlsbl/internal/scaffold"
)

const scaffoldHelp = "Render the release infrastructure of the member whose directory is the working directory, from rlsbl's templates and " +
	".strictmetadata/releasables/releasables.toml, and keep it current. Each target the member has (declared, or detected from its manifests) gets " +
	"its CI workflow (ci.yml, or ci-<target>.yml beside another target's), a Go module its VERSION and, for a go binary pipeline, .goreleaser.yml " +
	"and version.go, an npm package its .npmignore (written once, then the project's), and an npm go-binary package its bin/index.js launcher. A " +
	"releasable publishing from CI gets .github/workflows/publish.yml: the wait-for-ci job, then one job per pipeline publishing from CI, rendered " +
	"without build attestations, Go proxy requests, or repository URLs where the lifecycle-and-license record or GitHub's visibility forbids them. " +
	"Every member gets the .gitignore lines it lacks, the experiments/ and screenshots/ scratch directories, stub go.mod files keeping private " +
	"directories out of a Go module (.strictmetadata/go.mod at the root), a LICENSE written once from the record's license in effect when rlsbl " +
	"carries its text, and, while rlsbl:test-sandbox is on, the sandboxed test runner. pyproject.toml gains pytest's norecursedirs, its ignores of " +
	"nested members, and hatchling's sdist exclusions. The pre-push and post-rewrite git hooks are installed where git runs them. An existing file is " +
	"merged three ways against its merge base under .strictmetadata/.scaffold-bases/ (a missing base is rebuilt from the file's last `rlsbl scaffold` " +
	"commit); a conflict is written with git's markers, left uncommitted, and fails the command. A file scaffold managed and no longer renders is " +
	"removed through saferm while unmodified. Everything is planned and every refusal made before anything is written; the managed files and their " +
	"hashes are recorded in .strictmetadata/.scaffold-state/scaffold-state.toml. While rlsbl:ecosystem-tagging is on, the npm and PyPI manifests " +
	"gain the rlsbl keyword and the repository the rlsbl topic. A workspace's root member is not scaffolded: `rlsbl monorepo sync --auto-commit` generates its " +
	"workflows. Scaffolding any other member of a workspace ends by regenerating the workspace's CI router and publish router from the members' " +
	"workflows, as monorepo sync does, committed with the same choice as the scaffold; under --dry-run that step is named, not previewed."

// registerScaffold registers scaffold; version is this rlsbl's, which the
// scaffold state records.
func registerScaffold(r *commandSet, version string) {
	r.add(command{
		path:   []string{"scaffold"},
		help:   scaffoldHelp,
		effect: mutating,
		flags: []strictcli.Flag{
			strictcli.StringFlag("target", "A target the member must have: one it neither declares nor has detected is added to its declared targets (with the targets it has) in .strictmetadata/releasables/releasables.toml",
				strictcli.Optional(),
				strictcli.Choices(
					strictcli.Ch("go", "a Go module"),
					strictcli.Ch("npm", "an npm package"),
					strictcli.Ch("pypi", "a Python package"),
				)),
			strictcli.StringFlag("publish-mode", "The publish mode to declare for the member's releasable in .strictmetadata/releasables/releasables.toml",
				strictcli.Optional(),
				strictcli.Choices(
					strictcli.Ch("ci", "publish through the scaffolded CI publish workflow"),
					strictcli.Ch("none", "publish nothing to any registry"),
				)),
			strictcli.BoolFlag("auto-commit", "Commit what the run wrote, with the Autogenerated trailer (committed when neither --auto-commit nor --no-auto-commit is passed)", strictcli.Optional()),
			strictcli.BoolFlag("skip-shared", "Leave the files every member gets (.gitignore, scratch directories, stub go.mod files, LICENSE, the test runner) as they are (rendered when neither --skip-shared nor --no-skip-shared is passed)", strictcli.Optional()),
		},
		run: func(ctx *strictcli.Context, kw map[string]any) (any, error) {
			return nil, runScaffold(ctx, kw, version)
		},
	})
}

func runScaffold(ctx *strictcli.Context, kw map[string]any, version string) error {
	dir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("reading the working directory: %w", err)
	}
	target, _ := strictcli.GetOpt[string](kw, "target")
	mode, _ := strictcli.GetOpt[string](kw, "publish_mode")
	autoCommit, set := strictcli.GetOpt[bool](kw, "auto_commit")
	if !set {
		autoCommit = true
	}
	skipShared, _ := strictcli.GetOpt[bool](kw, "skip_shared")
	gh, err := github.New(ctx.Effects())
	if err != nil {
		return err
	}
	return scaffold.Run(ctx.Effects(), scaffold.Inputs{
		Dir:         dir,
		Version:     version,
		Target:      target,
		PublishMode: mode,
		AutoCommit:  autoCommit,
		SkipShared:  skipShared,
		DryRun:      ctx.DryRun(),
		Now:         time.Now(),
		Say:         ctx.Out,
		GitHub:      gh,
	})
}
