package lifecycleops_test

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/lifecycleops"
	"github.com/stricttools/rlsbl/internal/previewapply"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestMain(m *testing.M) {
	os.Exit(testsupport.RunTests(m))
}

// portalDeclarations declares the standalone project portal, which
// publishes nothing, on the GitHub repository acme/portal.
const portalDeclarations = `format_version = 1
repository_layout = "standalone"
release_branches = ["main"]
github_repository = "acme/portal"

[[releasables]]
name = "portal"
tag_format = "v{version}"
publish_mode = "none"

[[members]]
path = "."
name = "root"
releasable = "portal"
`

// today is the date every command in these tests runs on.
var today = time.Date(2026, 6, 1, 12, 0, 0, 0, time.UTC)

// fixture is a repository and the confidential-name index its commands
// use.
type fixture struct {
	repo  *testsupport.Repo
	index string
}

// newFixture is a repository with portal's declarations and the record
// given (none when empty), committed.
func newFixture(t *testing.T, record string) *fixture {
	t.Helper()
	repo := testsupport.NewRepo(t)
	repo.Write(declarations.ReleasablesFile, portalDeclarations)
	paths := []string{declarations.ReleasablesFile}
	if record != "" {
		repo.Write(lifecycle.RecordFile, record)
		repo.Write(lifecycle.ManifestFile, "owner = \"strictspec\"\n")
		paths = append(paths, lifecycle.RecordFile, lifecycle.ManifestFile)
	}
	repo.Commit("the project", paths...)
	return &fixture{repo: repo, index: filepath.Join(t.TempDir(), "confidential-names.toml")}
}

// run runs fn with an invocation dated today in a mutating command
// carrying rlsbl's observe allowlist.
func (f *fixture) run(t *testing.T, dryRun bool, fn func(inv lifecycleops.Invocation, dir string) error) strictcli.Result {
	t.Helper()
	return testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectMutating, DryRun: dryRun, Allowlist: previewapply.Prefixes()}, func(ctx *strictcli.Context) error {
		inv := lifecycleops.Invocation{E: ctx.Effects(), DryRun: ctx.DryRun(), Say: ctx.Out, Now: func() time.Time { return today }, IndexPath: f.index}
		return fn(inv, f.repo.Dir)
	})
}

func requireExit(t *testing.T, r strictcli.Result, code int) {
	t.Helper()
	if r.ExitCode != code {
		t.Fatalf("exit %d, want %d\nstdout:\n%s\nstderr:\n%s", r.ExitCode, code, r.Stdout, r.Stderr)
	}
}

func requireContains(t *testing.T, text string, wants ...string) {
	t.Helper()
	for _, want := range wants {
		if !strings.Contains(text, want) {
			t.Fatalf("missing %q in:\n%s", want, text)
		}
	}
}

func (f *fixture) record(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile(f.repo.Path(lifecycle.RecordFile))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func (f *fixture) indexText(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile(f.index)
	if os.IsNotExist(err) {
		return ""
	}
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// lastCommit is HEAD's subject and its Autogenerated trailer's value.
func (f *fixture) lastCommit(t *testing.T) (subject, autogenerated string) {
	t.Helper()
	out := f.repo.Git("log", "-1", "--format=%s%x00%(trailers:key=Autogenerated,valueonly)")
	subject, autogenerated, _ = strings.Cut(out, "\x00")
	return subject, strings.TrimSpace(autogenerated)
}

func (f *fixture) clean(t *testing.T) {
	t.Helper()
	if s := f.repo.Git("status", "--porcelain", "--", ".strictmetadata/lifecycle-and-license"); s != "" {
		t.Fatalf("the record is left uncommitted:\n%s", s)
	}
}

// gitAt runs git in dir with the author and committer dates (and, when
// identity is given, the author and committer) set, returning its trimmed
// stdout.
func gitAt(t *testing.T, dir string, env []string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), env...)
	var out, errOut bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errOut
	if err := cmd.Run(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, errOut.String())
	}
	return strings.TrimSpace(out.String())
}

// commitOn writes files and commits every change with both dates on date.
func commitOn(t *testing.T, repo *testsupport.Repo, date string, files map[string]string, message string) string {
	t.Helper()
	for rel, content := range files {
		repo.Write(rel, content)
	}
	repo.Git("add", "-A")
	when := date + "T10:00:00+00:00"
	gitAt(t, repo.Dir, []string{"GIT_AUTHOR_DATE=" + when, "GIT_COMMITTER_DATE=" + when}, "commit", "-q", "-m", message)
	return repo.Head()
}

// commitTree writes a commit carrying tree, parents, and the author and
// committer (dates included) of like, with message, as safegit's squash
// writes one.
func commitTree(t *testing.T, repo *testsupport.Repo, tree string, parents []string, like, message string) string {
	t.Helper()
	fields := strings.Split(repo.Git("log", "-1", "--format=%an%x00%ae%x00%aI%x00%cn%x00%ce%x00%cI", like), "\x00")
	env := []string{
		"GIT_AUTHOR_NAME=" + fields[0], "GIT_AUTHOR_EMAIL=" + fields[1], "GIT_AUTHOR_DATE=" + fields[2],
		"GIT_COMMITTER_NAME=" + fields[3], "GIT_COMMITTER_EMAIL=" + fields[4], "GIT_COMMITTER_DATE=" + fields[5],
	}
	args := []string{"commit-tree", tree, "-m", message}
	for _, p := range parents {
		args = append(args, "-p", p)
	}
	return gitAt(t, repo.Dir, env, args...)
}

func treeOf(repo *testsupport.Repo, commit string) string {
	return repo.Git("rev-parse", commit+"^{tree}")
}

// fakeSafegit is a safegit for one test: `--version` prints the version,
// `commit` commits with git as safegit would, and each squash runs the next
// answer's script and prints its stdout with its exit status, in order.
// Every invocation is recorded.
type fakeSafegit struct {
	t   *testing.T
	dir string
	n   int
}

const fakeSafegitScript = `#!/bin/sh
here="${0%/*}"
printf '%s\n' "$*" >> "$here/calls.txt"
if [ "$1" = --version ]; then
	echo "safegit 0.31.0"
	exit 0
fi
if [ "$1" = --approve-consequential ] && [ "$2" = scrub ]; then
	n=$(($(cat "$here/count.txt") + 1))
	echo "$n" > "$here/count.txt"
	if [ ! -f "$here/out-$n.txt" ]; then
		echo "fake safegit: no answer for squash $n" >&2
		exit 97
	fi
	sh "$here/script-$n.sh" >&2 || exit 1
	cat "$here/out-$n.txt"
	exit "$(cat "$here/exit-$n.txt")"
fi
if [ "$1" != commit ]; then
	echo "fake safegit: unexpected $*" >&2
	exit 97
fi
shift
trailer=""
message=""
while [ $# -gt 0 ]; do
	case "$1" in
	--trailer) trailer="$2"; shift 2 ;;
	-m) message="$2"; shift 2 ;;
	--) shift; break ;;
	*) echo "fake safegit: unexpected argument $1" >&2; exit 97 ;;
	esac
done
git add -A -- "$@" || exit 1
if [ -n "$trailer" ]; then
	exec git commit -q --trailer "$trailer" -m "$message"
fi
exec git commit -q -m "$message"
`

func newFakeSafegit(t *testing.T) *fakeSafegit {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "safegit"), []byte(fakeSafegitScript), 0o755); err != nil {
		t.Fatal(err)
	}
	s := &fakeSafegit{t: t, dir: dir}
	s.write("count.txt", "0\n")
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	return s
}

func (s *fakeSafegit) write(name, content string) {
	s.t.Helper()
	if err := os.WriteFile(filepath.Join(s.dir, name), []byte(content), 0o644); err != nil {
		s.t.Fatal(err)
	}
}

// Squash queues the next squash's answer.
func (s *fakeSafegit) Squash(script, stdout string, exit int) {
	s.t.Helper()
	s.n++
	s.write(fmt.Sprintf("script-%d.sh", s.n), script)
	s.write(fmt.Sprintf("out-%d.txt", s.n), stdout)
	s.write(fmt.Sprintf("exit-%d.txt", s.n), fmt.Sprintf("%d\n", exit))
}

// Squashes are the squash invocations, in order.
func (s *fakeSafegit) Squashes() []string {
	s.t.Helper()
	data, err := os.ReadFile(filepath.Join(s.dir, "calls.txt"))
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		s.t.Fatal(err)
	}
	var out []string
	for _, c := range strings.Split(strings.TrimRight(string(data), "\n"), "\n") {
		if strings.HasPrefix(c, "--approve-consequential scrub squash") {
			out = append(out, c)
		}
	}
	return out
}

// Gh answers for acme/portal.
var (
	ghAuth = testsupport.GHAnswer{Args: []string{"auth", "status", "--hostname", "github.com"}}
	ghRepo = []string{"api", "--method", "GET", "repos/acme/portal"}
)

func ghVisibility(visibility string) testsupport.GHAnswer {
	return testsupport.GHAnswer{Args: ghRepo, Stdout: fmt.Sprintf(`{"full_name":"acme/portal","visibility":%q,"private":%t,"archived":false}`, visibility, visibility != "public")}
}
