package changelog

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"sort"
	"strings"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/releaserecord"
	"github.com/stricttools/rlsbl/internal/runstate"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/upstream"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// Invocation is one run of a `changelog` command: the effects handle every
// read and write goes through, whether it runs under --dry-run, and where it
// prints its report. Every command holds the repository's release lock
// around its reads and its writes, since a changelog file is replaced whole.
// Under --dry-run the writes are recorded and the commit is not attempted.
type Invocation struct {
	E      *strictcli.Effects
	DryRun bool
	Say    func(string)
}

// Outcome is what a command that may write a released version's file
// leaves to do afterwards.
type Outcome struct {
	// Resync is the released version whose GitHub Release the write leaves
	// stale, and nil when there is none (an unreleased write, or a version
	// recorded never released, which has no Release).
	Resync *semver.Version
}

// OpenAt is the changelog of the releasable the absolute directory dir
// selects (the releasable of the member whose territory holds dir), in the
// repository holding dir. The commands ask nothing of the unreleased range,
// so a fork's upstream history is not read.
func OpenAt(e *strictcli.Effects, dir string) (Subject, error) {
	ws, err := workspace.Discover(dir)
	if err != nil {
		return Subject{}, err
	}
	repo, err := git.Open(e, ws.Root)
	if err != nil {
		return Subject{}, err
	}
	releasable, err := SubjectAt(ws, dir)
	if err != nil {
		return Subject{}, err
	}
	upstreamURL, err := upstream.URLOf(ws.Root)
	if err != nil {
		return Subject{}, err
	}
	return NewSubject(repo, ws, releasable, upstreamURL, nil)
}

// locked runs fn holding the release lock of the repository rooted at root.
func (inv Invocation) locked(root string, fn func() error) (err error) {
	lock, err := runstate.Acquire(inv.E, root, runstate.AcquireOptions{DryRun: inv.DryRun, Wait: runstate.WaitForHolder, OnWait: func(path string) {
		inv.Say(fmt.Sprintf("Another rlsbl process holds %s; waiting for it before writing the changelog.", path))
	}})
	if err != nil {
		return err
	}
	defer func() {
		if rerr := lock.Release(); rerr != nil && err == nil {
			err = rerr
		}
	}()
	return fn()
}

// changelogManifest is the ownership manifest of the changelog directories,
// which the first write into them creates; a commit carries it when it is
// new.
const changelogManifest = declarations.ChangelogRoot + "/manifest.toml"

// commit commits paths with message, skipped under --dry-run. A commit that
// fails leaves the written files on disk, and the error names the commit
// that records them.
func (inv Invocation) commit(repo git.Repo, message string, paths []string, autogenerated bool) error {
	paths = append(append([]string(nil), paths...), changelogManifest)
	if inv.DryRun {
		inv.Say("Would commit " + strings.Join(paths[:len(paths)-1], ", ") + ": " + firstLine(message))
		return nil
	}
	if _, err := repo.Commit(git.CommitRequest{Message: message, Paths: paths, Autogenerated: autogenerated, RequireChange: true}); err != nil {
		trailer := ""
		if autogenerated {
			trailer = "--trailer '" + git.AutogeneratedTrailer + ": true' "
		}
		return fmt.Errorf("the changelog is written but not committed: %w\nOnce the cause is fixed, commit what was written: safegit commit %s-m %s -- %s", err, trailer, shellQuote(message), strings.Join(presentPaths(repo.Dir(), paths), " "))
	}
	return nil
}

// presentPaths keeps the paths that exist under root, the ones a commit
// can name.
func presentPaths(root string, paths []string) []string {
	var out []string
	for _, p := range paths {
		if _, err := os.Lstat(absolute(root, p)); err == nil {
			out = append(out, p)
		}
	}
	return out
}

func firstLine(s string) string {
	line, _, _ := strings.Cut(s, "\n")
	return line
}

// shellQuote is s as one single-quoted shell word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// releasedFate decides, before anything is written, what a write to
// released version v's file of releasable leaves to do: a version whose
// archive records a release (recorded or unrecoverable) has a GitHub
// Release to rewrite; one recorded never released has none. A version
// without an archive, or with one stating no fate, is refused: whether its
// Release exists cannot be told, so the write would leave it unknowably
// stale.
func releasedFate(root, releasable string, v semver.Version) (Outcome, error) {
	dir := releaserecord.ArchiveDir(releasable)
	rel := releaserecord.ArchivePath(dir, v)
	if _, err := os.Lstat(absolute(root, rel)); errors.Is(err, fs.ErrNotExist) {
		return Outcome{}, fmt.Errorf("%s of %s has a released changelog file but no release archive at %s, so whether a GitHub Release carries its notes cannot be told; nothing was written. Backfill the archive first, previewing it: `rlsbl release backfill --dry-run`, then `rlsbl release backfill --approve-consequential`", v, releasable, rel)
	} else if err != nil {
		return Outcome{}, fmt.Errorf("reading %s: %w", rel, err)
	}
	a, err := releaserecord.ReadArchive(root, dir, v)
	if err != nil {
		return Outcome{}, err
	}
	switch a.Fate {
	case releaserecord.FateNeverReleased:
		return Outcome{}, nil
	case releaserecord.FateRecorded, releaserecord.FateUnrecoverable:
		version := v
		return Outcome{Resync: &version}, nil
	}
	return Outcome{}, fmt.Errorf("%s states no fate (recorded, unrecoverable, or never released), so whether a GitHub Release carries the notes of %s cannot be told; nothing was written. Backfill it first, previewing it: `rlsbl release backfill --dry-run`, then `rlsbl release backfill --approve-consequential`", rel, v)
}

// ParseVersionArgument reads a version a command names. A spelling with a
// leading "v" is refused naming the bare one: the caller's spelling is
// never tidied into another.
func ParseVersionArgument(text, what string) (semver.Version, error) {
	if rest, ok := strings.CutPrefix(text, "v"); ok && semver.Valid(rest) {
		return semver.Version{}, fmt.Errorf("%s %q carries a leading \"v\"; name the version bare: %s", what, text, rest)
	}
	v, err := semver.Parse(text)
	if err != nil {
		return semver.Version{}, fmt.Errorf("%s: %w", what, err)
	}
	return v, nil
}

// SplitCommits reads a comma-separated list of commit ids, refusing a list
// that names none.
func SplitCommits(text, flag string) ([]string, error) {
	var out []string
	for _, c := range strings.Split(text, ",") {
		if c = strings.TrimSpace(c); c != "" {
			out = append(out, c)
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s names no commit: pass one or more commit ids, separated by commas", flag)
	}
	return out, nil
}

// AddRequest is one `changelog add`.
type AddRequest struct {
	Entry      EntryRequest
	AutoCommit bool
}

// Add appends a new entry to the unreleased file of the releasable s
// names, after Prepare's checks, and commits the file.
func (inv Invocation) Add(s Subject, req AddRequest) error {
	return inv.locked(s.Root(), func() error {
		f, err := ReadUnreleased(s.Root(), s.Dir())
		if err != nil {
			return err
		}
		prepared, err := s.Prepare(req.Entry, f.Entries())
		if err != nil {
			return err
		}
		for _, note := range prepared.Notes {
			inv.Say("Note: " + note)
		}
		if err := s.Add(inv.E, prepared.Entry); err != nil {
			return err
		}
		if inv.DryRun {
			inv.Say("Would add to " + f.Path + ":\n  " + Serialize(prepared.Entry))
		} else {
			inv.Say(fmt.Sprintf("Added entry %s with %d commit(s) to %s", prepared.Entry.ID, len(prepared.Entry.Commits), f.Path))
		}
		if !req.AutoCommit {
			return nil
		}
		return inv.commit(s.Repo, entryCommitMessage("changelog", prepared.Entry), []string{f.Path}, false)
	})
}

// entryCommitMessage is the subject of a commit writing entry: the prefix
// and the entry's description, or a note that it is not user-facing.
func entryCommitMessage(prefix string, e Entry) string {
	if e.UserFacing && e.Description != "" {
		return prefix + ": " + e.Description
	}
	return prefix + ": non-user-facing entry"
}

// Generate writes the releasable's CHANGELOG.md (and, in a workspace, the
// roll-up) from its changelog files, and commits what changed with the
// Autogenerated trailer. Under --dry-run the releasable's document is
// printed. A releasable without a changelog directory is refused.
func (inv Invocation) Generate(s Subject, autoCommit bool) error {
	if info, err := os.Stat(absolute(s.Root(), s.Dir())); err != nil || !info.IsDir() {
		return fmt.Errorf("the releasable %q has no changelog directory %s, so there is nothing to generate CHANGELOG.md from: add its first entry with `rlsbl changelog add`", s.Releasable, s.Dir())
	}
	return inv.locked(s.Root(), func() error {
		if inv.DryRun {
			document, err := Document(s.Root(), s.Releasable, nil)
			if err != nil {
				return err
			}
			inv.Say(document)
		}
		written, err := Regenerate(inv.E, s.Root(), s.Workspace.Declarations, s.Releasable, nil)
		if err != nil {
			return err
		}
		if len(written) == 0 {
			inv.Say("The generated changelog is already what the changelog files give; nothing was written.")
			return nil
		}
		inv.Say("Generated " + strings.Join(written, ", "))
		if !autoCommit {
			return nil
		}
		return inv.commit(s.Repo, "changelog: regenerate from JSONL", written, true)
	})
}

// AmendRequest is one `changelog amend`.
type AmendRequest struct {
	Version semver.Version
	Entry   EntryRequest
}

// Amend appends a new entry to released version v's file, which stays
// read-only, regenerates CHANGELOG.md, and commits both. The outcome names
// the version whose GitHub Release is now stale.
func (inv Invocation) Amend(s Subject, req AmendRequest) (Outcome, error) {
	outcome, err := releasedFate(s.Root(), s.Releasable, req.Version)
	if err != nil {
		return Outcome{}, err
	}
	err = inv.locked(s.Root(), func() error {
		f, err := ReadVersion(s.Root(), s.Dir(), req.Version)
		if err != nil {
			return err
		}
		prepared, err := s.Prepare(req.Entry, f.Entries())
		if err != nil {
			return err
		}
		for _, note := range prepared.Notes {
			inv.Say("Note: " + note)
		}
		if err := s.Amend(inv.E, req.Version, prepared.Entry); err != nil {
			return err
		}
		inv.Say(fmt.Sprintf("Amended %s with entry %s (%d commit(s))", f.Path, prepared.Entry.ID, len(prepared.Entry.Commits)))
		regenerated, err := Regenerate(inv.E, s.Root(), s.Workspace.Declarations, s.Releasable, nil)
		if err != nil {
			return err
		}
		message := "changelog: amend " + req.Version.String()
		if prepared.Entry.UserFacing && prepared.Entry.Description != "" {
			message += ": " + prepared.Entry.Description
		}
		return inv.commit(s.Repo, message, append([]string{f.Path}, regenerated...), false)
	})
	if err != nil {
		return Outcome{}, err
	}
	return outcome, nil
}

// EditCommand is one `changelog edit`: the entry, and the sparse update.
type EditCommand struct {
	Selector   Selector
	Edit       EditRequest
	AutoCommit bool
}

// one narrows the matches of a selector to one entry. edit narrows several
// matches by the type the edit writes; a removal never narrows.
func one(matches []Match, typ *string, retry string) (Match, error) {
	if len(matches) == 1 {
		return matches[0], nil
	}
	if typ != nil {
		var kept []Match
		for _, m := range matches {
			if m.Entry().Type == *typ {
				kept = append(kept, m)
			}
		}
		if len(kept) == 1 {
			return kept[0], nil
		}
		if len(kept) > 1 {
			matches = kept
		}
	}
	lines := make([]string, len(matches))
	for i, m := range matches {
		lines[i] = "  " + m.Describe()
	}
	return Match{}, fmt.Errorf("the selector matches %d entries, and the command changes one; nothing was written. The matches are:\n%s\n%s", len(matches), strings.Join(lines, "\n"), retry)
}

// Edit applies a sparse update to one entry, wherever it is: the
// unreleased file, or a released version's file (which stays read-only,
// and whose version's CHANGELOG.md is regenerated). A commit selector
// matching several entries is narrowed by the type the edit writes, and
// otherwise refused with every match named.
func (inv Invocation) Edit(s Subject, req EditCommand) (Outcome, error) {
	var outcome Outcome
	err := inv.locked(s.Root(), func() error {
		matches, err := s.Find(req.Selector, true)
		if err != nil {
			return err
		}
		m, err := one(matches, req.Edit.Type, "Name one of them: `rlsbl changelog edit --id <id>` with the same changes.")
		if err != nil {
			return err
		}
		if m.File.Released {
			if outcome, err = releasedFate(s.Root(), s.Releasable, m.File.Version); err != nil {
				return err
			}
		}
		edited, err := ApplyEdit(m.Entry(), req.Edit)
		if err != nil {
			return err
		}
		if err := Replace(inv.E, s.Root(), m, edited); err != nil {
			return err
		}
		if inv.DryRun {
			inv.Say("Would rewrite the entry in " + m.File.Path + " as:\n  " + Serialize(edited))
		} else {
			inv.Say("Edited entry " + edited.ID + " in " + m.File.Path)
		}
		paths := []string{m.File.Path}
		if m.File.Released {
			regenerated, err := Regenerate(inv.E, s.Root(), s.Workspace.Declarations, s.Releasable, nil)
			if err != nil {
				return err
			}
			paths = append(paths, regenerated...)
		}
		if !req.AutoCommit {
			return nil
		}
		return inv.commit(s.Repo, describedMessage("changelog: edit "+m.File.Label(), edited), paths, false)
	})
	if err != nil {
		return Outcome{}, err
	}
	return outcome, nil
}

// describedMessage is prefix and the entry's description, or "entry".
func describedMessage(prefix string, e Entry) string {
	described := e.Description
	if described == "" {
		described = "entry"
	}
	return prefix + ": " + described
}

// RemoveCommand is one `changelog remove`.
type RemoveCommand struct {
	Selector   Selector
	AutoCommit bool
}

// Remove deletes one entry, wherever it is. A commit that no longer
// resolves is matched as written, since the entry of a commit a rewrite
// took away is the one a removal is usually for. A selector matching
// several entries is refused with every match named: a removal of the
// wrong line cannot be put right by running it again.
func (inv Invocation) Remove(s Subject, req RemoveCommand) (Outcome, error) {
	var outcome Outcome
	err := inv.locked(s.Root(), func() error {
		matches, err := s.Find(req.Selector, false)
		if err != nil {
			return err
		}
		m, err := one(matches, nil, "Name one of them: `rlsbl changelog remove --id <id>`.")
		if err != nil {
			return err
		}
		if m.File.Released {
			if outcome, err = releasedFate(s.Root(), s.Releasable, m.File.Version); err != nil {
				return err
			}
		}
		removed := m.Entry()
		if err := Remove(inv.E, s.Root(), m); err != nil {
			return err
		}
		if inv.DryRun {
			inv.Say("Would remove from " + m.File.Path + ":\n  " + Serialize(removed))
		} else {
			inv.Say("Removed entry " + removed.ID + " from " + m.File.Path)
		}
		paths := []string{m.File.Path}
		if m.File.Released {
			regenerated, err := Regenerate(inv.E, s.Root(), s.Workspace.Declarations, s.Releasable, nil)
			if err != nil {
				return err
			}
			paths = append(paths, regenerated...)
		}
		if !req.AutoCommit {
			return nil
		}
		return inv.commit(s.Repo, describedMessage("changelog: remove from "+m.File.Label(), removed), paths, false)
	})
	if err != nil {
		return Outcome{}, err
	}
	return outcome, nil
}

// MapSource is one source of a remap's commit map: a map file, safegit's
// rewrite journal, or standard input.
type MapSource struct {
	// Label names the source in a message.
	Label string
	Map   map[string]string
}

// mergeSources is the union of the sources' maps. A source holding no
// mapping is refused, and so is an old commit two sources map to
// different commits: which one is meant would be a guess.
func mergeSources(sources []MapSource) (map[string]string, error) {
	if len(sources) == 0 {
		return nil, errors.New("a remap needs a commit map: name one or more of --map-file, --from-journal, and --stdin")
	}
	merged := map[string]string{}
	from := map[string]string{}
	for _, src := range sources {
		if len(src.Map) == 0 {
			return nil, fmt.Errorf("%s holds no mapping of an old commit to a new one, so it names nothing to remap", src.Label)
		}
		for old, next := range src.Map {
			if had, ok := merged[old]; ok && had != next {
				return nil, fmt.Errorf("%s maps %s to %s, and %s maps it to %s; which rewrite renamed it cannot be decided, so nothing was written. Remap from one source", from[old], short(old), short(had), src.Label, short(next))
			}
			merged[old] = next
			from[old] = src.Label
		}
	}
	return merged, nil
}

// ambiguousIDs lists, per changelog file of the repository at root, the
// abbreviated commit ids that are a prefix of more than one commit the map
// renames: no rewrite of them can be decided.
func ambiguousIDs(root string, rewrites map[string]string) (map[string][]string, error) {
	dirs, err := Dirs(root)
	if err != nil {
		return nil, err
	}
	out := map[string][]string{}
	for _, dir := range dirs {
		files, err := ReadAll(root, dir)
		if err != nil {
			return nil, err
		}
		for _, f := range files {
			for _, l := range f.Lines {
				for _, h := range l.Entry.Commits {
					if _, ambiguous := mapCommit(h, rewrites); ambiguous {
						out[f.Path] = appendOnce(out[f.Path], h)
					}
				}
			}
		}
	}
	return out, nil
}

// RemapAll rewrites the commit ids of every changelog file of the
// repository rooted at root through the sources' map, and commits what it
// rewrote with the Autogenerated trailer. An abbreviated id the map cannot
// decide is refused before anything is written, naming the file.
func (inv Invocation) RemapAll(repo git.Repo, sources []MapSource) error {
	rewrites, err := mergeSources(sources)
	if err != nil {
		return err
	}
	root := repo.Dir()
	return inv.locked(root, func() error {
		ambiguous, err := ambiguousIDs(root, rewrites)
		if err != nil {
			return err
		}
		if len(ambiguous) > 0 {
			var lines []string
			for _, file := range sortedKeys(ambiguous) {
				lines = append(lines, fmt.Sprintf("  %s: %s", file, strings.Join(ambiguous[file], ", ")))
			}
			return fmt.Errorf("abbreviated commit ids are the prefix of more than one commit the map renames, so where each moved cannot be decided; nothing was written:\n%s\nWrite the full commit id each entry means into its line by hand (no command changes an entry's commits), then remap again", strings.Join(lines, "\n"))
		}
		report, err := Remap(inv.E, root, rewrites)
		if err != nil {
			return err
		}
		if len(report.Files) == 0 {
			inv.Say("No changelog commit id is one the map renames; nothing was written.")
			return nil
		}
		var paths []string
		commits, entries := 0, 0
		for _, f := range report.Files {
			paths = append(paths, f.Path)
			commits += f.CommitsRemapped
			entries += f.EntriesModified
		}
		sort.Strings(paths)
		verb := "Remapped"
		if inv.DryRun {
			verb = "Would remap"
		}
		inv.Say(fmt.Sprintf("%s %d commit id(s) in %d entr(ies) across %d file(s): %s", verb, commits, entries, len(paths), strings.Join(paths, ", ")))
		return inv.commit(repo, "changelog: remap stale commit hashes", paths, true)
	})
}
