package changelog_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

func TestASectionGroupsUserFacingEntriesByType(t *testing.T) {
	hygiene.Isolate(t)
	fix := changelog.Entry{ID: id("2"), Commits: []string{sha1}, UserFacing: true, Description: "Fix the gadget", Type: changelog.TypeFix}
	breaking := changelog.Entry{ID: id("3"), Commits: []string{sha1}, UserFacing: true, Description: "Drop the old flag", Type: changelog.TypeBreaking, Packages: []string{"widget", "gadget"}}
	got := changelog.Section("1.2.0", []changelog.Entry{feature("1", "Add the widget", sha1), fix, internalEntry("4", sha1), breaking}, changelog.SectionMeta{Description: "A release.", Context: "Why."}, 2)
	want := "## 1.2.0\n\nA release.\n\n<details>\n<summary>Context</summary>\n\nWhy.\n\n</details>\n\n### Breaking\n\n- [gadget, widget] Drop the old flag\n\n### Features\n\n- Add the widget\n\n### Fixes\n\n- Fix the gadget\n"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestASectionWithoutUserFacingEntriesSaysSo(t *testing.T) {
	hygiene.Isolate(t)
	if got := changelog.Section("1.0.1", []changelog.Entry{internalEntry("1", sha1)}, changelog.SectionMeta{}, 2); got != "## 1.0.1\n\n- No user-facing changes.\n" {
		t.Errorf("got %q", got)
	}
	infra := changelog.Section("1.0.2", nil, changelog.SectionMeta{Description: "Rebuild the CI.", Bump: semver.Infra}, 2)
	if infra != "## 1.0.2\n\nRebuild the CI.\n\n### Infrastructure\n\n- Rebuild the CI.\n" {
		t.Errorf("infra: %q", infra)
	}
	never := changelog.Section("1.0.3", nil, changelog.SectionMeta{NeverReleased: true}, 3)
	if never != "### 1.0.3\n\n"+changelog.NeverReleasedNote+"\n\n- No user-facing changes.\n" {
		t.Errorf("never released: %q", never)
	}
}

func TestADocumentListsTheUnreleasedEntriesThenEachReleaseWithItsArchive(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	dir := changelog.Dir("portal")
	writeLines(t, root, dir+"/unreleased.jsonl", feature("3", "Next thing", sha1))
	writeReleased(t, root, "portal", "1.1.0", feature("2", "Second thing", sha1))
	writeReleased(t, root, "portal", "1.0.0", feature("1", "First thing", sha1))
	writeArchive(t, root, "portal", "1.1.0", "recorded", strings.Repeat("a", 40), "The second release")
	got, err := changelog.Document(root, "portal", nil)
	mustNotFail(t, err)
	want := "<!-- Generated by rlsbl from .strictmetadata/changelog/portal/ — do not edit -->\n\n# Changelog\n\n" +
		"## Unreleased\n\n### Features\n\n- Next thing\n\n" +
		"## 1.1.0\n\nThe second release\n\n### Features\n\n- Second thing\n\n" +
		"## 1.0.0\n\n### Features\n\n- First thing\n"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
	pending := &changelog.Pending{Version: version(t, "1.2.0"), Description: "The third release"}
	got, err = changelog.Document(root, "portal", pending)
	mustNotFail(t, err)
	requireContains(t, got, "## 1.2.0\n\nThe third release\n\n### Features\n\n- Next thing\n")
	if strings.Contains(got, "Unreleased") {
		t.Errorf("a pending release kept the Unreleased heading:\n%s", got)
	}
}

func TestAPendingReleaseWithNoEntriesStillHasASection(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	writeLines(t, root, changelog.Dir("portal")+"/unreleased.jsonl")
	got, err := changelog.Document(root, "portal", nil)
	mustNotFail(t, err)
	if strings.Contains(got, "##") {
		t.Errorf("an empty unreleased file got a section:\n%s", got)
	}
	got, err = changelog.Document(root, "portal", &changelog.Pending{Version: version(t, "0.2.0"), Description: "Rebuild the CI.", Bump: semver.Infra})
	mustNotFail(t, err)
	requireContains(t, got, "## 0.2.0\n\nRebuild the CI.\n\n### Infrastructure\n\n- Rebuild the CI.\n")
}

func TestAnArchiveThatCannotBeReadStopsGeneration(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	writeReleased(t, root, "portal", "1.0.0", feature("1", "First thing", sha1))
	writeArchive(t, root, "portal", "1.0.0", "recorded", strings.Repeat("a", 40), "The first release")
	archive := filepath.Join(root, ".strictmetadata", "releases", "portal", "v1.0.0.toml")
	testsupport.WriteFile(t, archive, "format_version = 2\nbump = \"hotfix\"\n")
	if _, err := changelog.Document(root, "portal", nil); err == nil {
		t.Fatal("an unreadable archive was rendered as a release without a description")
	}
}

func TestANeverReleasedVersionIsAnnotated(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	writeReleased(t, root, "portal", "1.0.0", feature("1", "First thing", sha1))
	writeArchive(t, root, "portal", "1.0.0", "never-released", "", "Abandoned")
	got, err := changelog.Document(root, "portal", nil)
	mustNotFail(t, err)
	requireContains(t, got, "## 1.0.0\n\n"+changelog.NeverReleasedNote+"\n\nAbandoned\n")
}

// The roll-up used to stack each releasable's CHANGELOG.md, one "#" heading
// per releasable and versions at "##", so the document had as many titles
// as releasables (todo/workspace-changelog-rollup-emits-one-h1-per-releasable.md).
// It has one title, a "##" heading per releasable, and versions below.
func TestTheRollUpHasOneTitleAndEachReleasableOneLevelBelowIt(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	d := parseDeclarations(t, twoReleasables)
	writeReleased(t, root, "widget", "0.1.0", feature("1", "Widget thing", sha1))
	writeReleased(t, root, "gadget", "0.2.0", feature("2", "Gadget thing", sha1))
	got, err := changelog.RollUp(root, d, "", nil)
	mustNotFail(t, err)
	var titles []string
	for _, l := range strings.Split(got, "\n") {
		if strings.HasPrefix(l, "# ") {
			titles = append(titles, l)
		}
	}
	if strings.Join(titles, "|") != "# Changelog" {
		t.Fatalf("titles %v in:\n%s", titles, got)
	}
	want := "<!-- Generated by rlsbl from .strictmetadata/changelog/ — do not edit -->\n\n# Changelog\n\n" +
		"## widget\n\n### 0.1.0\n\n#### Features\n\n- Widget thing\n\n" +
		"## gadget\n\n### 0.2.0\n\n#### Features\n\n- Gadget thing\n"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestRegenerateWritesTheHomeAndTheRollUpOnlyWhenTheyChange(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	d := parseDeclarations(t, twoReleasables)
	writeReleased(t, root, "widget", "0.1.0", feature("1", "Widget thing", sha1))
	var written []string
	regenerate := func() {
		_, err := appending(t, root, false, func(e *strictcli.Effects) error {
			var err error
			written, err = changelog.Regenerate(e, root, d, "widget", nil)
			return err
		})
		mustNotFail(t, err)
	}
	regenerate()
	if strings.Join(written, ",") != ".strictmetadata/changelog/widget/CHANGELOG.md,CHANGELOG.md" {
		t.Fatalf("wrote %v", written)
	}
	requireContains(t, readText(t, filepath.Join(root, "CHANGELOG.md")), "## widget\n\n### 0.1.0")
	regenerate()
	if len(written) != 0 {
		t.Errorf("an unchanged regeneration wrote %v", written)
	}
}

func TestAStandaloneRepositoryWritesTheRootChangelog(t *testing.T) {
	hygiene.Isolate(t)
	root := t.TempDir()
	d := parseDeclarations(t, standalone)
	if changelog.Home(d, "portal") != "CHANGELOG.md" {
		t.Fatalf("home %q", changelog.Home(d, "portal"))
	}
	writeLines(t, root, changelog.Dir("portal")+"/unreleased.jsonl", feature("1", "First thing", sha1))
	var written []string
	_, err := appending(t, root, false, func(e *strictcli.Effects) error {
		var err error
		written, err = changelog.Regenerate(e, root, d, "portal", nil)
		return err
	})
	mustNotFail(t, err)
	if strings.Join(written, ",") != "CHANGELOG.md" {
		t.Fatalf("wrote %v", written)
	}
	if _, err := os.Stat(filepath.Join(root, ".strictmetadata", "changelog", "portal", "CHANGELOG.md")); !os.IsNotExist(err) {
		t.Errorf("a standalone repository got a releasable CHANGELOG.md (%v)", err)
	}
}

func TestExtractSectionReadsOneVersionsBody(t *testing.T) {
	hygiene.Isolate(t)
	content := "# Changelog\n\n## 1.1.0\n\n### Features\n\n- Second\n\n## 1.0.0\n\n- First\n"
	body, found := changelog.ExtractSection(content, "1.1.0")
	if !found || body != "### Features\n\n- Second" {
		t.Errorf("1.1.0: %q, %v", body, found)
	}
	body, found = changelog.ExtractSection(content, "1.0.0")
	if !found || body != "- First" {
		t.Errorf("1.0.0: %q, %v", body, found)
	}
	if _, found := changelog.ExtractSection(content, "1.0"); found {
		t.Error("a version prefix matched")
	}
}
