package changelog_test

import (
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/previewapply"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

const nullID = "0000000000000000000000000000000000000000"

func TestPushedCommitsAreWhatTheRemoteDoesNotHave(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	repo.AddBareRemote("origin")
	base := repo.CommitFile("a.txt", "a\n", "base")
	repo.Git("push", "-q", "origin", "main")
	repo.Git("fetch", "-q", "origin")
	next := repo.CommitFile("b.txt", "b\n", "next")
	last := repo.CommitFile("c.txt", "c\n", "last")
	rewrittenAway := strings.Repeat("9", 40)
	refs := []git.PushedRef{
		{LocalRef: "refs/heads/main", LocalID: last, RemoteRef: "refs/heads/main", RemoteID: base},
		{LocalRef: "refs/heads/topic", LocalID: last, RemoteRef: "refs/heads/topic", RemoteID: nullID},
		{LocalRef: "(delete)", LocalID: nullID, RemoteRef: "refs/heads/old", RemoteID: base},
		{LocalRef: "refs/heads/main", LocalID: last, RemoteRef: "refs/heads/rewritten", RemoteID: rewrittenAway},
	}
	mustNotFail(t, reading(t, repo.Dir, func(gr git.Repo) error {
		pushed, err := changelog.PushedCommits(gr, refs, nil)
		if err != nil {
			return err
		}
		if strings.Join(pushed.Commits, ",") != last+","+next {
			t.Errorf("commits %v", pushed.Commits)
		}
		if len(pushed.Rewritten) != 1 || pushed.Rewritten[0].RemoteID != rewrittenAway {
			t.Errorf("rewritten %+v", pushed.Rewritten)
		}
		return nil
	}))
}

func TestPushCoverageCountsEveryChangelogFileAndSkipsExemptCommits(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	shipped := repo.CommitFile("a.txt", "a\n", "shipped")
	fresh := repo.CommitFile("b.txt", "b\n", "fresh")
	generated := repo.CommitFile("c.txt", "c\n", "generated\n\nAutogenerated: true")
	missing := repo.CommitFile("d.txt", "d\n", "missing")
	files := []*changelog.File{
		{Path: "unreleased.jsonl", Lines: []changelog.Line{{Number: 1, Entry: feature("1", "fresh", fresh[:9])}}},
		{Path: "0.1.0.jsonl", Released: true, Lines: []changelog.Line{{Number: 1, Entry: feature("2", "shipped", shipped)}}},
	}
	mustNotFail(t, reading(t, repo.Dir, func(gr git.Repo) error {
		got, err := changelog.PushCoverage(gr, files, []string{missing, generated, fresh, shipped})
		if err != nil {
			return err
		}
		if strings.Join(got, ",") != missing[:12] {
			t.Errorf("missing %v", got)
		}
		return nil
	}))
}

func TestIgnoredChangelogRecordsAreNamed(t *testing.T) {
	hygiene.Isolate(t)
	repo := testsupport.NewRepo(t)
	repo.CommitFile(".gitignore", "CHANGELOG.md\n", "ignore the changelog")
	d := parseDeclarations(t, twoReleasables)
	paths := changelog.TrackedRecords(d, "widget")
	if strings.Join(paths, ",") != ".strictmetadata/changelog/widget/unreleased.jsonl,.strictmetadata/changelog/widget/CHANGELOG.md,CHANGELOG.md" {
		t.Fatalf("records %v", paths)
	}
	var ignored []string
	testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectReadOnly, Allowlist: previewapply.Prefixes()}, func(ctx *strictcli.Context) error {
		var err error
		ignored, err = changelog.IgnoredPaths(ctx.Effects(), repo.Dir, paths)
		mustNotFail(t, err)
		return nil
	})
	if strings.Join(ignored, ",") != ".strictmetadata/changelog/widget/CHANGELOG.md,CHANGELOG.md" {
		t.Fatalf("ignored %v", ignored)
	}
	requireContains(t, changelog.IgnoredRecordsFinding(repo.Dir, ignored), "CHANGELOG.md", "git check-ignore -v")
	if changelog.IgnoredRecordsFinding(repo.Dir, nil) != "" {
		t.Error("no ignored record was worded as a finding")
	}
}
