package changelog

import (
	"fmt"
	"sort"
	"strings"

	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// The batch limits, fixed: no repository overrides them. An entry over the
// first carries batch_reason; nothing exempts a commit from the second.
const (
	MaxCommitsPerEntry  = 5
	MaxEntriesPerCommit = 5
)

// HashFindings name every commit of f's entries that does not resolve.
func (s Subject) HashFindings(f *File) ([]string, error) {
	res := newResolver(s.Repo)
	var findings []string
	for _, l := range f.Lines {
		var bad []string
		for _, h := range l.Entry.Commits {
			full, err := res.resolve(h)
			if err != nil {
				return nil, err
			}
			if full == "" {
				bad = append(bad, h)
			}
		}
		for _, h := range bad {
			findings = append(findings, fmt.Sprintf("line %d of %s: commit %s does not resolve (%d of %d commits of the entry still resolve)", l.Number, f.Path, h, len(l.Entry.Commits)-len(bad), len(l.Entry.Commits)))
		}
	}
	return findings, nil
}

// inScopeOf is the set of rng's commits the subject's scope claims.
func (s Subject) inScopeOf(rng Range) (map[string]bool, error) {
	kept, err := workspace.FilterCommits(s.Repo, rng.Commits, s.Scope())
	if err != nil {
		return nil, err
	}
	set := make(map[string]bool, len(kept))
	for _, c := range kept {
		set[c] = true
	}
	return set, nil
}

// RangeFindings name every resolving commit of f's entries that is not an
// unreleased commit of the subject. Two different things are wrong with
// such a commit, and each finding says which: out of range, the commit is
// not between the nearest release and HEAD (a stale id, or work that
// already shipped); out of scope, it is in the range but its files belong
// to another releasable, so the entry is filed in the wrong changelog.
func (s Subject) RangeFindings(f *File, rng Range) ([]string, error) {
	inScope, err := s.inScopeOf(rng)
	if err != nil {
		return nil, err
	}
	res := newResolver(s.Repo)
	reported := map[string]bool{}
	var findings []string
	for _, l := range f.Lines {
		for _, raw := range l.Entry.Commits {
			full, err := res.resolve(raw)
			if err != nil {
				return nil, err
			}
			if full == "" || inScope[full] || reported[full] {
				continue
			}
			reported[full] = true
			if !rng.Contains(full) {
				findings = append(findings, fmt.Sprintf("line %d of %s: commit %s (%s) is not in the unreleased range of %q: it is not between the nearest release and HEAD", l.Number, f.Path, raw, full, s.Releasable))
				continue
			}
			finding, err := s.outOfScopeFinding(f, l, raw, full)
			if err != nil {
				return nil, err
			}
			findings = append(findings, finding)
		}
	}
	return findings, nil
}

// outOfScopeFinding is the finding for an entry naming a commit in the
// unreleased range that the subject's changelog does not cover. When
// another member owns the commit's files the entry belongs in that
// member's changelog; when nothing owns them (every file is tool-owned) no
// changelog covers the commit and the entry is removed outright.
func (s Subject) outOfScopeFinding(f *File, l Line, raw, full string) (string, error) {
	scope := s.Scope()
	owner, err := ForeignOwner(s.Repo, s.Workspace, scope, full)
	if err != nil {
		return "", err
	}
	finding := fmt.Sprintf("line %d of %s: commit %s (%s) is in the unreleased range but outside this changelog's scope: its files belong to %s, while this changelog covers %s. ", l.Number, f.Path, raw, full, owner, scope.Describe())
	if owner == NoDeclaredOwner {
		return finding + fmt.Sprintf("Every file it touches is tool-owned, so no changelog covers it and the entry has nowhere to move to: remove it with `%s`.", RemovalCommand(l.Entry)), nil
	}
	return finding + fmt.Sprintf("The entry is filed under the wrong releasable: remove it here with `%s`, then add it from a directory of the owning member with `rlsbl changelog add --commits %s --description \"...\" --type %s`.", RemovalCommand(l.Entry), full, typeOrFeature(l.Entry)), nil
}

func typeOrFeature(e Entry) string {
	if e.Type != "" {
		return e.Type
	}
	return TypeFeature
}

// Coverage is what CoverageFindings found.
type Coverage struct {
	// Uncovered are the unreleased commits needing an entry that no entry
	// names, sorted.
	Uncovered []string
	Stats     ExemptionStats
	// OutsideScope counts the range's commits outside the subject's scope.
	OutsideScope int
}

// Findings words the uncovered commits, one finding each.
func (c Coverage) Findings() []string {
	out := make([]string, len(c.Uncovered))
	for i, sha := range c.Uncovered {
		out[i] = "unreleased commit not covered by any changelog entry: " + short(sha)
	}
	return out
}

// Notes word what was left out of coverage and why.
func (c Coverage) Notes() []string {
	var notes []string
	if c.Stats.Autogenerated > 0 {
		notes = append(notes, fmt.Sprintf("skipped %d autogenerated commit(s)", c.Stats.Autogenerated))
	}
	if c.Stats.ChangelogOnly > 0 {
		notes = append(notes, fmt.Sprintf("skipped %d changelog-only commit(s)", c.Stats.ChangelogOnly))
	}
	if c.OutsideScope > 0 {
		notes = append(notes, fmt.Sprintf("skipped %d commit(s) outside this releasable's scope", c.OutsideScope))
	}
	return notes
}

// CoveredCommits are the full ids of the commits f's entries name; an id
// that resolves to no commit of the repository covers nothing.
func (s Subject) CoveredCommits(f *File) (map[string]bool, error) {
	res := newResolver(s.Repo)
	covered := map[string]bool{}
	for _, l := range f.Lines {
		for _, h := range l.Entry.Commits {
			full, err := res.resolve(h)
			if err != nil {
				return nil, err
			}
			if full != "" {
				covered[full] = true
			}
		}
	}
	return covered, nil
}

// CoverageOf checks that every unreleased commit in the subject's scope
// that is not exempt appears in at least one of f's entries.
func (s Subject) CoverageOf(f *File, rng Range) (Coverage, error) {
	covered, err := s.CoveredCommits(f)
	if err != nil {
		return Coverage{}, err
	}
	n, err := CommitsNeedingEntries(s.Repo, rng.Commits, s.Scope(), covered)
	if err != nil {
		return Coverage{}, err
	}
	return Coverage{Uncovered: n.Commits, Stats: n.Stats, OutsideScope: n.OutsideScope}, nil
}

// OrphanFindings name every entry of f none of whose commits is both
// resolvable and an unreleased commit of the subject: all its commits do
// not resolve, lie outside the range, or belong to another releasable.
// Each finding counts the three apart and names both ways out: remapping
// ids a history rewrite changed, or removing the entry.
func (s Subject) OrphanFindings(f *File, rng Range) ([]string, error) {
	inScope, err := s.inScopeOf(rng)
	if err != nil {
		return nil, err
	}
	res := newResolver(s.Repo)
	var findings []string
	for _, l := range f.Lines {
		var unresolvable, outOfRange, outOfScope []string
		live := 0
		for _, h := range l.Entry.Commits {
			full, err := res.resolve(h)
			if err != nil {
				return nil, err
			}
			switch {
			case full == "":
				unresolvable = append(unresolvable, h)
			case inScope[full]:
				live++
			case rng.Contains(full):
				outOfScope = append(outOfScope, h)
			default:
				outOfRange = append(outOfRange, h)
			}
		}
		if live > 0 {
			continue
		}
		var parts []string
		if len(unresolvable) > 0 {
			parts = append(parts, fmt.Sprintf("%d unresolvable", len(unresolvable)))
		}
		if len(outOfRange) > 0 {
			parts = append(parts, fmt.Sprintf("%d out of range", len(outOfRange)))
		}
		if len(outOfScope) > 0 {
			parts = append(parts, fmt.Sprintf("%d in range but owned by another releasable", len(outOfScope)))
		}
		stale := append(append(append([]string(nil), unresolvable...), outOfRange...), outOfScope...)
		findings = append(findings, fmt.Sprintf("line %d of %s: every commit of the entry is stale (%s: %s); run `rlsbl changelog remap` when a history rewrite changed their ids, or `%s` when the entry no longer describes anything", l.Number, f.Path, strings.Join(parts, ", "), strings.Join(stale, ", "), RemovalCommand(l.Entry)))
	}
	return findings, nil
}

// HasUserFacing reports whether any of entries is user-facing.
func HasUserFacing(entries []Entry) bool {
	for _, e := range entries {
		if e.UserFacing {
			return true
		}
	}
	return false
}

// UserFacingProblem is the release's rule on user-facing entries for a
// release of bump, and empty when entries keep it: an infra release has
// none, every other release at least one.
func UserFacingProblem(entries []Entry, bump semver.Bump) string {
	has := HasUserFacing(entries)
	if bump == semver.Infra {
		if has {
			return "an infra release must not have user-facing changelog entries: set bump = \"patch\", \"minor\", or \"major\" in the release file, unreleased.toml, or mark each of them not user-facing with `rlsbl changelog edit`"
		}
		return ""
	}
	if !has {
		if bump == "" {
			return "a release needs at least one user-facing changelog entry; a release with only infrastructure changes sets bump = \"infra\" in its release file, unreleased.toml"
		}
		return fmt.Sprintf("a %s release needs at least one user-facing changelog entry; a release with only infrastructure changes sets bump = \"infra\" in its release file, unreleased.toml", bump)
	}
	return ""
}

// BatchCommitFindings name every entry of f with more commits than
// MaxCommitsPerEntry that carries no batch_reason, with the commands that
// replace it by an entry that does. A commit in squashes (a
// declassification's squash commit, which every entry of its squashed
// period names) is not counted.
func BatchCommitFindings(f *File, squashes map[string]bool) []string {
	var findings []string
	for _, l := range f.Lines {
		e := l.Entry
		counted := 0
		for _, c := range e.Commits {
			if !squashes[c] {
				counted++
			}
		}
		if counted <= MaxCommitsPerEntry || e.BatchReason != "" {
			continue
		}
		shorts := make([]string, len(e.Commits))
		for i, c := range e.Commits {
			shorts[i] = short(c)
		}
		findings = append(findings, fmt.Sprintf("line %d of %s: the entry names %d commits, over the limit of %d per entry [%s]. Split it into entries of at most %d commits, or, when the commits are one change, replace it with an entry that says why: `%s`, then `rlsbl changelog add --commits %s --batch-reason \"<why one entry describes them>\"` with its description and type",
			l.Number, f.Path, len(e.Commits), MaxCommitsPerEntry, strings.Join(shorts, ", "), MaxCommitsPerEntry, RemovalCommand(e), strings.Join(e.Commits, ",")))
	}
	return findings
}

// BatchEntryFindings name every commit that appears in more than
// MaxEntriesPerCommit entries across files (the unreleased file and every
// released version's), with each place it appears. A commit in squashes (a
// declassification's squash commit, which every entry of its squashed
// period names) is left out.
func BatchEntryFindings(files []*File, squashes map[string]bool) []string {
	places := map[string][]string{}
	for _, f := range files {
		for _, l := range f.Lines {
			for _, c := range dedupe(l.Entry.Commits) {
				if squashes[c] {
					continue
				}
				places[c] = append(places[c], fmt.Sprintf("%s:%d", f.Path, l.Number))
			}
		}
	}
	commits := make([]string, 0, len(places))
	for c, where := range places {
		if len(where) > MaxEntriesPerCommit {
			commits = append(commits, c)
		}
	}
	sort.Strings(commits)
	findings := make([]string, len(commits))
	for i, c := range commits {
		findings[i] = fmt.Sprintf("commit %s appears in %d changelog entries, over the limit of %d per commit [%s]; merge the entries that describe the same change", short(c), len(places[c]), MaxEntriesPerCommit, strings.Join(places[c], ", "))
	}
	return findings
}
