package monorepo

import (
	"os"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

// residueFixture is twoMembers holding old-layout residue, all tracked: the
// root's .rlsbl/, widget's own .rlsbl/ and CHANGELOG.md, .rlsbl-monorepo/,
// and the changelog directory of a name no releasable is declared as,
// which cleanup keeps.
func residueFixture(t *testing.T) *testsupport.Repo {
	t.Helper()
	files := map[string]string{
		".rlsbl/config.json":                                       "{}\n",
		"packages/widget/.rlsbl/version":                           "0.130.0\n",
		"packages/widget/CHANGELOG.md":                             "# Changelog\n",
		".rlsbl-monorepo/workspace.toml":                           "[[projects]]\n",
		declarations.ChangelogDir("retired") + "/unreleased.jsonl": "",
	}
	for k, v := range twoMemberFiles {
		files[k] = v
	}
	return newWorkspace(t, twoMembers, files)
}

func cleaning(repo *testsupport.Repo, autoCommit, dryRun bool, out *Cleanup) func(e *strictcli.Effects, say func(string)) error {
	return func(e *strictcli.Effects, _ func(string)) error {
		ws, err := Load(repo.Dir, "cleanup")
		if err != nil {
			return err
		}
		r, err := git.Open(e, repo.Dir)
		if err != nil {
			return err
		}
		*out, err = RunCleanup(e, r, ws, autoCommit, dryRun)
		return err
	}
}

func TestCleanupRemovesTheResidueThroughSafermAndCommits(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeSafegit(t)
	calls := deletingSaferm(t)
	repo := residueFixture(t)
	var out Cleanup
	mustRun(t, strictcli.EffectMutating, false, cleaning(repo, true, false, &out))
	var removed []string
	for _, r := range out.Removed {
		removed = append(removed, r.Path)
	}
	want := []string{".rlsbl", ".rlsbl-monorepo", "packages/widget/.rlsbl", "packages/widget/CHANGELOG.md"}
	if strings.Join(removed, " ") != strings.Join(want, " ") {
		t.Fatalf("removed %v, want %v", removed, want)
	}
	if len(out.Kept) != 1 || out.Kept[0].Path != declarations.ChangelogDir("retired") {
		t.Errorf("kept %+v", out.Kept)
	}
	for _, p := range want {
		if exists(repo, p) {
			t.Errorf("%s is still there", p)
		}
	}
	if !exists(repo, declarations.ChangelogDir("retired")+"/unreleased.jsonl") {
		t.Error("the record of an undeclared name was removed")
	}
	data, err := os.ReadFile(calls)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "delete -r -f --description") || !strings.Contains(string(data), "--on-error abort -- .rlsbl-monorepo") {
		t.Errorf("saferm was called as:\n%s", data)
	}
	if !out.Committed || repo.Git("log", "-1", "--format=%s") != CleanupCommitMessage {
		t.Fatalf("committed %v, last commit %q", out.Committed, repo.Git("log", "-1", "--format=%s"))
	}
	if trailer := repo.Git("log", "-1", "--format=%(trailers:key=Autogenerated,valueonly)"); trailer != "true" {
		t.Errorf("the commit's Autogenerated trailer is %q", trailer)
	}
	if status := repo.Git("status", "--porcelain"); status != "" {
		t.Errorf("the cleanup left changes:\n%s", status)
	}
}

func TestCleanupWithoutAutoCommitCommitsNothing(t *testing.T) {
	hygiene.Isolate(t)
	testsupport.FakeSafegit(t)
	deletingSaferm(t)
	repo := residueFixture(t)
	before := repo.Head()
	var out Cleanup
	mustRun(t, strictcli.EffectMutating, false, cleaning(repo, false, false, &out))
	if out.Committed || repo.Head() != before || exists(repo, ".rlsbl") {
		t.Fatalf("committed %v, head moved %v", out.Committed, repo.Head() != before)
	}
}

func TestADryRunCleanupRemovesNothing(t *testing.T) {
	hygiene.Isolate(t)
	calls := deletingSaferm(t)
	repo := residueFixture(t)
	var out Cleanup
	mustRun(t, strictcli.EffectMutating, true, cleaning(repo, true, true, &out))
	if len(out.Removed) != 4 || out.Committed || !exists(repo, ".rlsbl/config.json") {
		t.Fatalf("out %+v", out)
	}
	if _, err := os.Stat(calls); err == nil {
		t.Error("saferm ran under --dry-run")
	}
}

func TestCleanupOfAWorkspaceWithoutResidueDoesNothing(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	var out Cleanup
	mustRun(t, strictcli.EffectMutating, false, cleaning(repo, true, false, &out))
	if len(out.Removed) != 0 || len(out.Kept) != 0 || out.Committed {
		t.Fatalf("out %+v", out)
	}
}
