package monorepo

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/release"
	"github.com/stricttools/rlsbl/internal/releaserecord"
	"github.com/stricttools/rlsbl/internal/runstate"
	"github.com/stricttools/rlsbl/internal/saferm"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/workflows"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// Remote is the remote the rename pushes its boundary alias tag to.
const Remote = "origin"

// RenameCommitMessage is the message of the rename's commit, which a run
// completing an interrupted one finds it by.
func RenameCommitMessage(old, new string) string {
	return "monorepo: rename releasable " + old + " -> " + new
}

func shippedAsCommitMessage(old, new string) string {
	return "monorepo: record the " + old + " tags " + new + "'s past releases shipped under"
}

func aliasCommitMessage(new string) string {
	return "monorepo: record the " + new + " rename boundary alias"
}

// RenameRequest is one `monorepo rename-releasable`.
type RenameRequest struct {
	Old, New string
	DryRun   bool
	// Now is the date the identities and periods change on.
	Now time.Time
	// Sync regenerates the workspace's routers from the renamed
	// declarations without committing.
	Sync func(ws *workspace.Workspace) (workflows.SyncResult, error)
	Say  func(string)
}

// Renamed is what the rename did.
type Renamed struct {
	// Resumed is whether the run completed an interrupted rename.
	Resumed bool
	// RenameCommit is the rename's commit; empty under --dry-run.
	RenameCommit string
	// NeedsEntry is whether changelog coverage asks an entry for it.
	NeedsEntry bool
	// NameInFormat is whether the tag format holds {name}, so the tags
	// change spelling.
	NameInFormat bool
	// ShippedAs are the versions whose archive now records the tag they
	// shipped under; Unstamped the released versions left without one,
	// each with the reason.
	ShippedAs []string
	Unstamped []string
	// AliasTag is the boundary alias tag at the current version, and empty
	// when there is none; AliasStatus says what happened to it.
	AliasTag    string
	AliasStatus string
}

// The alias tag's outcomes.
const (
	AliasCreated       = "created and pushed"
	AliasAlreadyDone   = "already created and pushed"
	AliasNoSourceTag   = "no tag of the current version under the old name, so nothing to alias"
	AliasNeverReleased = "the releasable has no version file yet, so nothing to alias"
)

// renamer carries one rename.
type renamer struct {
	e        *strictcli.Effects
	repo     git.Repo
	ws       *workspace.Workspace
	req      RenameRequest
	format   string
	resuming bool
}

// RenameReleasable renames a releasable of the workspace: its declaration
// and every member's reference to it, its changelog, release, and run-state
// directories, and its subjects in the lifecycle-and-license record (each
// open period and identity of the old name is closed on the rename's date
// and opened again under the new name, the releasable-name identity taking
// the new name and every identity the tag namespace the new name renders).
// The routers are regenerated, and all of it is committed as one commit
// without the Autogenerated trailer. When the tag format holds {name}, each
// past release's archive records the tag it shipped under (shipped_as), and
// the current version gets a boundary alias tag under the new name at the
// commit its old tag names, recorded in the transition record and pushed.
//
// A run whose declarations already name the new releasable and not the old
// completes an interrupted rename: every step does only what is left.
func RenameReleasable(e *strictcli.Effects, repo git.Repo, ws *workspace.Workspace, req RenameRequest) (Renamed, error) {
	if req.Say == nil || req.Sync == nil {
		return Renamed{}, errors.New("monorepo rename-releasable needs somewhere to report to and a router regeneration")
	}
	r := &renamer{e: e, repo: repo, ws: ws, req: req}
	target, err := r.preflight()
	if err != nil {
		return Renamed{}, err
	}
	r.format = target.TagFormat
	out := Renamed{Resumed: r.resuming, NameInFormat: strings.Contains(r.format, "{name}")}
	if req.DryRun {
		r.sayPlan(out.NameInFormat)
		return out, nil
	}
	lock, err := runstate.Acquire(e, ws.Root, runstate.AcquireOptions{
		Wait: runstate.WaitForHolder,
		OnWait: func(path string) {
			req.Say(fmt.Sprintf("Waiting for %s: another rlsbl process is changing this repository's release state", path))
		},
	})
	if err != nil {
		return Renamed{}, err
	}
	defer lock.Release()

	renamedWS, err := r.renameLocally()
	if err != nil {
		return Renamed{}, err
	}
	if out.RenameCommit, err = r.findRenameCommit(); err != nil {
		return Renamed{}, err
	}
	if out.RenameCommit != "" {
		needing, err := changelog.CommitsNeedingEntries(repo, []string{out.RenameCommit}, renamedWS.ScopeOfReleasable(req.New), nil)
		if err != nil {
			return Renamed{}, err
		}
		out.NeedsEntry = len(needing.Commits) > 0
	}
	if !out.NameInFormat {
		return out, nil
	}
	if out.ShippedAs, out.Unstamped, err = r.recordShippedAs(); err != nil {
		return Renamed{}, err
	}
	if out.AliasTag, out.AliasStatus, err = r.aliasCurrentVersion(renamedWS); err != nil {
		return Renamed{}, err
	}
	return out, nil
}

// preflight refuses what the rename cannot do, before anything is written,
// and returns the releasable being renamed as the declarations hold it.
func (r *renamer) preflight() (declarations.Releasable, error) {
	old, new := r.req.Old, r.req.New
	d := r.ws.Declarations
	oldRel, oldDeclared := d.Releasable(old)
	newRel, newDeclared := d.Releasable(new)
	if old == new {
		return declarations.Releasable{}, fmt.Errorf("the old and the new name are both %q", old)
	}
	if !oldDeclared && newDeclared {
		resumable, err := r.interrupted()
		if err != nil {
			return declarations.Releasable{}, err
		}
		if resumable {
			r.resuming = true
			return newRel, nil
		}
	}
	if !oldDeclared {
		var names []string
		for _, rel := range r.ws.Releasables() {
			names = append(names, rel.Name)
		}
		return declarations.Releasable{}, fmt.Errorf("no releasable is named %q; the declared releasables are %s", old, strings.Join(names, ", "))
	}
	if newDeclared {
		return declarations.Releasable{}, fmt.Errorf("a releasable named %q is declared already", new)
	}
	if problem := declarations.NameProblem(new); problem != "" {
		return declarations.Releasable{}, fmt.Errorf("a releasable cannot be named %q: %s", new, problem)
	}
	if m, ok := d.Member(new); ok {
		return declarations.Releasable{}, fmt.Errorf("%q is the name of the member at %s; a releasable and a member share the directories under %s that their names name, so pick another name", new, m.Path, declarations.MetadataDir)
	}
	for _, dir := range []string{declarations.ChangelogDir(new), declarations.ReleasesDir(new), declarations.RetiredHistoryDir(new)} {
		if exists, err := pathExists(r.ws.Root, dir); err != nil {
			return declarations.Releasable{}, err
		} else if exists {
			return declarations.Releasable{}, fmt.Errorf("%s exists already, so the releasable's state cannot move there; it is the record of another subject named %q", dir, new)
		}
	}
	dirty, err := r.repo.ChangedPaths(nil, git.UntrackedNormal)
	if err != nil {
		return declarations.Releasable{}, err
	}
	if len(dirty) > 0 {
		return declarations.Releasable{}, fmt.Errorf("the working tree has uncommitted changes, and the rename commits the files it changes as one commit: commit or remove these first:\n  %s", strings.Join(dirty, "\n  "))
	}
	inProgress, err := runstate.InProgressReleasables(r.ws.Root)
	if err != nil {
		return declarations.Releasable{}, err
	}
	if len(inProgress) > 0 {
		return declarations.Releasable{}, fmt.Errorf("a release is in progress for %s (%s); resume it with `"+runstate.ResumeInvocation+"` or abandon it with `rlsbl release abandon` before renaming", strings.Join(inProgress, ", "), runstate.InProgressPath(inProgress[0]))
	}
	if _, found, err := runstate.LoadBatchPlan(r.ws.Root); err != nil {
		return declarations.Releasable{}, err
	} else if found {
		return declarations.Releasable{}, fmt.Errorf("a batch release is in progress (%s); finish it with `"+runstate.BatchRunInvocation+"` before renaming", runstate.BatchPlanPath)
	}
	if exists, err := pathExists(r.ws.Root, releaserecord.BatchReleaseFilePath); err != nil {
		return declarations.Releasable{}, err
	} else if exists {
		batch, err := releaserecord.ReadBatchReleaseFile(r.ws.Root)
		if err != nil {
			return declarations.Releasable{}, err
		}
		for _, name := range batch.Names() {
			if name == old {
				return declarations.Releasable{}, fmt.Errorf("the batch release file %s names %q in [releasables.%s]; delete that table, or release the batch, before renaming", releaserecord.BatchReleaseFilePath, old, old)
			}
		}
	}
	rec, err := lifecycle.Load(r.ws.Root)
	if err != nil {
		return declarations.Releasable{}, err
	}
	if err := requireRenamableRecord(rec, old, oldRel); err != nil {
		return declarations.Releasable{}, err
	}
	return oldRel, nil
}

// interrupted reports whether a releasable named New with no Old declared
// is the end of an interrupted rename of Old: the old name's state is still
// on disk, or the record still holds its open releasable-name identity or
// the closed one this rename recorded.
func (r *renamer) interrupted() (bool, error) {
	for _, dir := range []string{declarations.ChangelogDir(r.req.Old), declarations.ReleasesDir(r.req.Old)} {
		if exists, err := pathExists(r.ws.Root, dir); err != nil || exists {
			return exists, err
		}
	}
	rec, err := lifecycle.Load(r.ws.Root)
	if err != nil {
		return false, err
	}
	for _, id := range rec.Identities() {
		if id.Subject == r.req.Old && id.Facet == lifecycle.FacetReleasableName && !id.Pending() {
			return true, nil
		}
	}
	return false, nil
}

// requireRenamableRecord refuses a record without the releasable's open
// releasable-name identity, which the rename closes, and a record holding a
// pending identity of it, which only its release converts.
func requireRenamableRecord(rec *lifecycle.Record, old string, rel declarations.Releasable) error {
	open := false
	for _, id := range rec.Identities() {
		if id.Subject != old {
			continue
		}
		if id.Pending() {
			return fmt.Errorf("%s holds a pending %s identity of %q, %q effective %s, which the release of that version converts; a renamed releasable would leave it naming a subject that no longer exists. Release that version first, or delete the pending entry", lifecycle.RecordFile, id.Facet, old, id.Value, id.EffectiveVersion)
		}
		if id.Facet == lifecycle.FacetReleasableName && id.Open() {
			open = true
		}
	}
	if open {
		return nil
	}
	scheme, err := workspace.SchemeOf(rel)
	if err != nil {
		return err
	}
	return fmt.Errorf("%s holds no open releasable-name identity of %q, and the rename closes it and opens one for the new name, so the record keeps which name owned which tags when. Record the identity the releasable has held, from the day it took the name:\n\n  [[identities]]\n  subject = %q\n  facet = %q\n  value = %q\n  registry = \"\"\n  tag_patterns = [%q]\n  from = <the day it took the name, YYYY-MM-DD>\n  reason = \"...\"\n",
		lifecycle.RecordFile, old, old, lifecycle.FacetReleasableName, old, scheme.ListGlob())
}

// sayPlan prints what the rename would do.
func (r *renamer) sayPlan(nameInFormat bool) {
	old, new := r.req.Old, r.req.New
	say := r.req.Say
	if r.resuming {
		say(fmt.Sprintf("Would complete the interrupted rename of %q to %q, doing only what is left of:", old, new))
	}
	say(fmt.Sprintf("Would rename the releasable %q to %q in %s, with every member versioned under it.", old, new, declarations.ReleasablesFile))
	say(fmt.Sprintf("Would move %s, %s, and %s to the new name, and remove the changelog validation cache of %q through saferm.", declarations.ChangelogDir(old), declarations.ReleasesDir(old), declarations.RunStateDir(old), old))
	say(fmt.Sprintf("Would close every open period and identity of %q in %s and open each again under %q, the releasable-name identity taking the new name.", old, lifecycle.RecordFile, new))
	say("Would regenerate the workspace's routers and commit all of it: " + RenameCommitMessage(old, new))
	if !nameInFormat {
		say("The tag format holds no {name}, so the tags keep their spelling: no shipped_as, no alias tag, no push.")
		return
	}
	say(fmt.Sprintf("Would record on each past release's archive the %s tag it shipped under (shipped_as), and commit it.", strings.ReplaceAll(r.format, "{name}", old)))
	say(fmt.Sprintf("Would create the alias tag of the current version under %q at the commit of its tag under %q, record it in %s, and push it to %s.", new, old, declarations.TransitionsFile, Remote))
}

// renameLocally performs every step up to and including the rename commit,
// each only when it is left to do, and returns the renamed workspace.
func (r *renamer) renameLocally() (*workspace.Workspace, error) {
	e, root, old, new := r.e, r.ws.Root, r.req.Old, r.req.New
	ws := r.ws
	if !r.resuming {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(declarations.ReleasablesFile)))
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", declarations.ReleasablesFile, err)
		}
		ed, err := declarations.NewEditor(data)
		if err != nil {
			return nil, err
		}
		if err := ed.RenameReleasable(old, new); err != nil {
			return nil, err
		}
		edited, _, err := ed.Result()
		if err != nil {
			return nil, err
		}
		d, err := declarations.Write(e, root, edited)
		if err != nil {
			return nil, err
		}
		if ws, err = workspace.New(root, d); err != nil {
			return nil, err
		}
	}
	// The lock writes the run-state directory's .gitignore when it is
	// missing, which belongs with the rename's other changes.
	commitPaths := []string{declarations.ReleasablesFile, declarations.ReleasablesDir + "/manifest.toml", declarations.ReleaseStateDir + "/.gitignore"}
	for _, pair := range [][2]string{
		{declarations.ChangelogDir(old), declarations.ChangelogDir(new)},
		{declarations.ReleasesDir(old), declarations.ReleasesDir(new)},
		{declarations.RunStateDir(old), declarations.RunStateDir(new)},
	} {
		from, err := pathExists(root, pair[0])
		if err != nil {
			return nil, err
		}
		to, err := pathExists(root, pair[1])
		if err != nil {
			return nil, err
		}
		if from && to {
			return nil, fmt.Errorf("both %s and %s exist, so the rename cannot tell which one is the releasable's state; merge them by hand and run this again", pair[0], pair[1])
		}
		if from {
			if _, err := e.Rename(filepath.Join(root, filepath.FromSlash(pair[0])), filepath.Join(root, filepath.FromSlash(pair[1]))); err != nil {
				return nil, fmt.Errorf("moving %s to %s: %w", pair[0], pair[1], err)
			}
		}
		if pair[0] != declarations.RunStateDir(old) {
			commitPaths = append(commitPaths, pair[0], pair[1])
		}
	}
	cache := declarations.ChangelogValidationFile(old)
	if exists, err := pathExists(root, cache); err != nil {
		return nil, err
	} else if exists {
		if err := saferm.Delete(e, root, saferm.Request{Path: cache, Description: "the changelog validation cache of a renamed releasable", SkipMissing: true}); err != nil {
			return nil, err
		}
		commitPaths = append(commitPaths, cache)
	}
	if err := r.renameSubjects(ws); err != nil {
		return nil, err
	}
	commitPaths = append(commitPaths, lifecycle.RecordFile, lifecycle.ManifestFile)
	sync, err := r.req.Sync(ws)
	if err != nil {
		return nil, fmt.Errorf("regenerating the routers: %w", err)
	}
	commitPaths = append(commitPaths, sync.Written...)
	commitPaths = append(commitPaths, sync.Removed...)
	// Not autogenerated: whether the rename needs a changelog entry is
	// coverage's decision.
	committed, err := r.repo.Commit(git.CommitRequest{Message: RenameCommitMessage(old, new), Paths: commitPaths})
	if err != nil {
		return nil, err
	}
	if committed {
		r.req.Say("Committed: " + RenameCommitMessage(old, new))
	} else {
		r.req.Say("The rename is committed already; nothing left to commit.")
	}
	return ws, nil
}

// renameSubjects closes every open period and identity of the old name in
// the lifecycle-and-license record and opens each again under the new one,
// unless the new name's releasable-name identity is open already (a run
// completing an interrupted rename).
func (r *renamer) renameSubjects(ws *workspace.Workspace) error {
	old, new := r.req.Old, r.req.New
	rec, err := lifecycle.Load(ws.Root)
	if err != nil {
		return err
	}
	for _, id := range rec.Identities() {
		if id.Subject == new && id.Facet == lifecycle.FacetReleasableName && id.Open() && !id.Pending() {
			return nil
		}
	}
	renamed, _ := ws.Declarations.Releasable(new)
	oldScheme, err := workspace.SchemeOf(declarations.Releasable{Name: old, TagFormat: renamed.TagFormat})
	if err != nil {
		return err
	}
	newScheme, err := workspace.SchemeOf(renamed)
	if err != nil {
		return err
	}
	on := r.req.Now
	reason := fmt.Sprintf("renamed from %s with `rlsbl monorepo rename-releasable %s %s`", old, old, new)
	for _, l := range rec.Lifecycle() {
		if l.Subject != old || !l.Open() {
			continue
		}
		if err := rec.ClosePeriod(lifecycle.TableLifecycle, old, on); err != nil {
			return err
		}
		if err := rec.OpenPeriod(lifecycle.TableLifecycle, new, string(l.Status), on, reason); err != nil {
			return err
		}
	}
	for _, l := range rec.Licenses() {
		if l.Subject != old || !l.Open() {
			continue
		}
		if err := rec.ClosePeriod(lifecycle.TableLicenses, old, on); err != nil {
			return err
		}
		if err := rec.OpenPeriod(lifecycle.TableLicenses, new, l.License, on, reason); err != nil {
			return err
		}
	}
	for _, id := range rec.Identities() {
		if id.Subject != old || id.Pending() || !id.Open() {
			continue
		}
		if err := rec.CloseIdentity(old, id.Facet, on); err != nil {
			return err
		}
		next := lifecycle.Identity{
			Subject:  new,
			Facet:    id.Facet,
			Value:    id.Value,
			Registry: id.Registry,
			Period:   lifecycle.Period{From: on},
			Reason:   reason,
		}
		if id.Facet == lifecycle.FacetReleasableName {
			next.Value = new
		}
		for _, p := range id.TagPatterns {
			if p == oldScheme.ListGlob() {
				p = newScheme.ListGlob()
			}
			next.TagPatterns = append(next.TagPatterns, p)
		}
		if err := rec.AddIdentity(next); err != nil {
			return err
		}
	}
	if err := rec.Validate(on, declaredSubjects(ws)); err != nil {
		return fmt.Errorf("the renamed record is refused: %w", err)
	}
	return rec.Write(recordWriter{r.e}, ws.Root)
}

// declaredSubjects are every releasable and member name the declarations
// hold.
func declaredSubjects(ws *workspace.Workspace) []string {
	var names []string
	for _, rel := range ws.Releasables() {
		names = append(names, rel.Name)
	}
	for _, m := range ws.Members() {
		names = append(names, m.Name)
	}
	return names
}

// findRenameCommit is the newest commit carrying the rename's message; ""
// when there is none.
func (r *renamer) findRenameCommit() (string, error) {
	c, err := r.e.Run([]interface{}{"git", "log", "-1", "--format=%H", "--fixed-strings", "--grep=" + RenameCommitMessage(r.req.Old, r.req.New)},
		strictcli.Cwd(r.ws.Root), strictcli.Check(false), strictcli.Timeout(2*time.Minute))
	if err != nil {
		return "", err
	}
	if c.ExitCode() != 0 {
		return "", fmt.Errorf("git log in %s exited %d: %s", r.ws.Root, c.ExitCode(), strings.TrimSpace(c.Stderr()))
	}
	return strings.TrimSpace(c.Stdout()), nil
}

// tagUnder is the tag of version under the releasable named name.
func (r *renamer) tagUnder(name string, v semver.Version) (string, error) {
	scheme, err := workspace.SchemeOf(declarations.Releasable{Name: name, TagFormat: r.format})
	if err != nil {
		return "", err
	}
	return scheme.Render(v), nil
}

// recordShippedAs records on each past release's archive the tag spelled
// with the old name that it shipped under, and commits them. A version
// counts as shipped under the old spelling when that tag stands at the
// archive's release commit (or exists, for an unrecoverable archive, which
// names none), so a run long after the rename leaves every version released
// since alone.
func (r *renamer) recordShippedAs() (stamped, unstamped []string, err error) {
	root, dir := r.ws.Root, releaserecord.ArchiveDir(r.req.New)
	versions, err := releaserecord.ArchivedVersions(root, dir)
	if err != nil {
		return nil, nil, err
	}
	var paths []string
	for _, v := range versions {
		a, err := releaserecord.ReadArchive(root, dir, v)
		if err != nil {
			return nil, nil, err
		}
		if a.Fate == releaserecord.FateNeverReleased || a.ShippedAs != "" {
			continue
		}
		oldTag, err := r.tagUnder(r.req.Old, v)
		if err != nil {
			return nil, nil, err
		}
		commit, found, err := r.repo.TagCommit(oldTag)
		if err != nil {
			return nil, nil, err
		}
		if !found {
			newTag, err := r.tagUnder(r.req.New, v)
			if err != nil {
				return nil, nil, err
			}
			if _, released, err := r.repo.TagCommit(newTag); err != nil {
				return nil, nil, err
			} else if !released {
				unstamped = append(unstamped, fmt.Sprintf("%s (no tag %s exists here)", v, oldTag))
			}
			continue
		}
		if a.ReleaseCommit.Commit != "" && !strings.HasPrefix(commit, a.ReleaseCommit.Commit) {
			unstamped = append(unstamped, fmt.Sprintf("%s (%s names %s, not the release commit %s)", v, oldTag, commit, a.ReleaseCommit.Commit))
			continue
		}
		changed, err := releaserecord.RecordShippedAs(r.e, root, dir, v, oldTag)
		if err != nil {
			return nil, nil, err
		}
		if changed {
			stamped = append(stamped, v.String())
			paths = append(paths, a.Path)
		}
	}
	if len(paths) > 0 {
		// The archive writer creates the release directories' ownership
		// manifest when it is missing.
		paths = append(paths, declarations.ReleasesRoot+"/manifest.toml")
		if _, err := r.repo.Commit(git.CommitRequest{Message: shippedAsCommitMessage(r.req.Old, r.req.New), Paths: paths, Autogenerated: true, RequireChange: true}); err != nil {
			return nil, nil, err
		}
	}
	return stamped, unstamped, nil
}

// aliasCurrentVersion creates the tag of the current version under the new
// name at the commit its tag under the old name names, records it in the
// transition record (before the push, so a pushed tag never lacks its
// record), commits the record, and pushes the tag, each only when it is
// left to do.
func (r *renamer) aliasCurrentVersion(ws *workspace.Workspace) (tag, status string, err error) {
	text, found, err := releasableVersion(ws, r.req.New)
	if err != nil {
		return "", "", err
	}
	if !found {
		return "", AliasNeverReleased, nil
	}
	v, err := semver.Parse(text)
	if err != nil {
		return "", "", err
	}
	oldTag, err := r.tagUnder(r.req.Old, v)
	if err != nil {
		return "", "", err
	}
	newTag, err := r.tagUnder(r.req.New, v)
	if err != nil {
		return "", "", err
	}
	local, haveLocal, err := r.repo.TagCommit(newTag)
	if err != nil {
		return "", "", err
	}
	remote, haveRemote, err := r.repo.RemoteTagCommit(Remote, newTag)
	if err != nil {
		return "", "", err
	}
	if haveLocal && haveRemote && local == remote {
		return newTag, AliasAlreadyDone, nil
	}
	source, haveSource, err := r.repo.TagCommit(oldTag)
	if err != nil {
		return "", "", err
	}
	if !haveLocal {
		if !haveSource {
			return newTag, AliasNoSourceTag, nil
		}
		if err := r.repo.CreateRef("refs/tags/"+newTag, source); err != nil {
			return "", "", err
		}
		local = source
	}
	if haveRemote && remote != local {
		return "", "", fmt.Errorf("the tag %s on %s names %s, and here it names %s; a tag is never moved, so find out which one is right before running this again", newTag, Remote, remote, local)
	}
	if err := r.recordAlias(newTag, oldTag, local); err != nil {
		return "", "", err
	}
	if !haveRemote {
		timeout, err := release.PushTimeout(ws.Declarations, 0, false)
		if err != nil {
			return "", "", err
		}
		if err := r.repo.Push(Remote, git.RefUpdate{Ref: "refs/tags/" + newTag, New: local}, timeout); err != nil {
			return "", "", err
		}
	}
	return newTag, AliasCreated, nil
}

// recordAlias appends the boundary alias to the transition record and
// commits it, unless the record holds it already.
func (r *renamer) recordAlias(aliasTag, aliasedTag, commit string) error {
	events, err := releaserecord.ReadEvents(r.ws.Root)
	if err != nil {
		return err
	}
	for _, ev := range events {
		b, ok := ev.(*releaserecord.BoundaryAliasEvent)
		if !ok {
			continue
		}
		for _, a := range b.Aliases {
			if a.AliasTag == aliasTag {
				return nil
			}
		}
	}
	event := &releaserecord.BoundaryAliasEvent{
		Releasable: r.req.New,
		Aliases:    []releaserecord.BoundaryAlias{{AliasTag: aliasTag, AliasedTag: aliasedTag, Commit: commit}},
	}
	if err := releaserecord.AppendEvents(r.e, r.ws.Root, []releaserecord.Event{event}, r.req.Now); err != nil {
		return err
	}
	_, err = r.repo.Commit(git.CommitRequest{Message: aliasCommitMessage(r.req.New), Paths: []string{path.Dir(declarations.TransitionsFile)}, Autogenerated: true, RequireChange: true})
	return err
}

// pathExists reports whether the repository-relative path exists.
func pathExists(root, rel string) (bool, error) {
	_, err := os.Lstat(filepath.Join(root, filepath.FromSlash(rel)))
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// RenameClosing is what the rename prints when it is done: what happened to
// the past releases' tags and the alias tag, and the changelog entry the
// rename commit needs, when coverage asks one.
func RenameClosing(ws *workspace.Workspace, old, new string, out Renamed) []string {
	var lines []string
	if out.Resumed {
		lines = append(lines, fmt.Sprintf("Completed the interrupted rename of %q to %q.", old, new))
	}
	if out.NameInFormat {
		if len(out.ShippedAs) > 0 {
			lines = append(lines, "Recorded shipped_as on the archives of "+strings.Join(out.ShippedAs, ", ")+".")
		}
		for _, u := range out.Unstamped {
			lines = append(lines, "Left without shipped_as, so its tag is spelled with the new name: "+u+".")
		}
		if out.AliasTag != "" {
			lines = append(lines, fmt.Sprintf("Alias tag %s: %s.", out.AliasTag, out.AliasStatus))
		} else {
			lines = append(lines, "No alias tag: "+out.AliasStatus+".")
		}
		lines = append(lines, fmt.Sprintf("Past releases keep the tags they shipped under, spelled with %q; releases from now on are tagged with %q.", old, new))
	}
	if out.RenameCommit != "" && !out.NeedsEntry {
		return lines
	}
	description := fmt.Sprintf("Renamed the releasable %s to %s.", old, new)
	if out.NameInFormat {
		description = fmt.Sprintf("Renamed the releasable %s to %s: releases from now on are tagged under the name %s.", old, new, new)
	}
	commits := "<the rename commit>"
	if out.RenameCommit != "" {
		commits = out.RenameCommit[:12]
	}
	command := fmt.Sprintf("rlsbl changelog add --commits %s --type breaking --description %s", commits, shellQuote(description))
	if members := ws.MembersOf(new); len(members) > 0 && !members[0].IsRoot() {
		command = fmt.Sprintf("(cd %s && %s)", shellQuote(members[0].Path), command)
	}
	return append(lines, "The rename commit needs a changelog entry: "+command)
}

// shellQuote quotes s for a POSIX shell, as a printed command line spells
// an argument.
func shellQuote(s string) string {
	if s != "" && strings.Trim(s, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@%+=:,./-_") == "" {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
