package monorepo

import (
	"errors"
	"slices"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/registry"
	"github.com/stricttools/rlsbl/internal/release"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

// statusFixture is twoMembers with gadget's version file at 0.2.0, then a
// commit changing widget and an autogenerated commit changing widget.
func statusFixture(t *testing.T) *testsupport.Repo {
	t.Helper()
	files := map[string]string{declarations.VersionFile("gadget"): "0.2.0\n"}
	for k, v := range twoMemberFiles {
		files[k] = v
	}
	repo := newWorkspace(t, twoMembers, files)
	repo.CommitFile("packages/widget/index.js", "module.exports = {};\n", "widget's entry point")
	repo.Write("packages/widget/README.md", "widget\n")
	repo.Git("add", "packages/widget/README.md")
	repo.Git("commit", "-q", "--trailer", "Autogenerated: true", "-m", "a generated readme")
	return repo
}

func TestStatusReportsEachReleasableAndMember(t *testing.T) {
	hygiene.Isolate(t)
	repo := statusFixture(t)
	var st Status
	mustRun(t, strictcli.EffectReadOnly, false, func(e *strictcli.Effects, _ func(string)) error {
		var err error
		st, err = ReadStatus(openRepo(t, e, repo.Dir), load(t, repo), release.Fork{})
		return err
	})
	if len(st.Releasables) != 2 || len(st.Members) != 3 {
		t.Fatalf("status %+v", st)
	}
	widget, gadget := st.Releasables[0], st.Releasables[1]
	if widget.Name != "widget" || widget.Version != nil || widget.Coverage != (release.Coverage{Covered: 0, Total: 2, Exempted: 1}) || !slices.Equal(widget.Members, []string{"widget"}) {
		t.Errorf("widget %+v", widget)
	}
	if gadget.Version == nil || *gadget.Version != "0.2.0" || gadget.Coverage.Total != 1 || gadget.Latest == "" {
		t.Errorf("gadget %+v", gadget)
	}
	root, wm, gm := st.Members[0], st.Members[1], st.Members[2]
	if root.Version != nil || root.VersionSource != VersionFromNoTarget || len(root.Targets) != 0 || root.Releasable != nil || !root.DevOnly {
		t.Errorf("root %+v", root)
	}
	if wm.Version == nil || *wm.Version != "0.1.0" || wm.VersionSource != "npm" || wm.Dependents != 1 || wm.Dependencies != 0 {
		t.Errorf("widget member %+v", wm)
	}
	// gadget's releasable publishes nothing, so nothing bumps its manifest
	// (0.2.0 here by chance), and its version file answers.
	if gm.VersionSource != VersionFromVersionFile || gm.Version == nil || *gm.Version != "0.2.0" || gm.Dependencies != 1 {
		t.Errorf("gadget member %+v", gm)
	}
}

func TestOutdatedJudgesEachConstraintAgainstTheCurrentVersion(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	deps, err := Outdated(load(t, repo))
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 1 || deps[0].Member != "gadget" || deps[0].Dependency != "widget" || deps[0].Constraint != "^0.1.0" || deps[0].Current == nil || *deps[0].Current != "0.1.0" || deps[0].Status != "ok" {
		t.Fatalf("dependencies %+v", deps)
	}
	repo.Write("packages/widget/package.json", "{\n  \"name\": \"widget\",\n  \"version\": \"1.0.0\"\n}\n")
	deps, err = Outdated(load(t, repo))
	if err != nil {
		t.Fatal(err)
	}
	if deps[0].Status != "outdated" {
		t.Fatalf("dependencies %+v", deps)
	}
}

func TestOutdatedReportsAnExplicitDependencyByItsForm(t *testing.T) {
	hygiene.Isolate(t)
	decls := strings.Replace(twoMembers, "releasable = \"gadget\"\n", "releasable = \"gadget\"\ndepends_on = [\"root\"]\n", 1)
	repo := newWorkspace(t, decls, twoMemberFiles)
	deps, err := Outdated(load(t, repo))
	if err != nil {
		t.Fatal(err)
	}
	var explicit *Dependency
	for i := range deps {
		if deps[i].Dependency == "root" {
			explicit = &deps[i]
		}
	}
	if explicit == nil || explicit.Status != "explicit" || explicit.Current != nil || explicit.Constraint != "" {
		t.Fatalf("dependencies %+v", deps)
	}
}

func TestTheGraphIsInTopologicalOrder(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	g, err := ReadGraph(load(t, repo), GraphRequest{Depth: -1})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(g.Order, []string{"root", "widget", "gadget"}) {
		t.Fatalf("order %v", g.Order)
	}
	if len(g.Edges) != 1 || g.Edges[0] != (Edge{From: "gadget", To: "widget", Form: "versioned", Constraint: "^0.1.0", Scope: "runtime"}) {
		t.Fatalf("edges %+v", g.Edges)
	}
	widget, _ := g.member("widget")
	gadget, _ := g.member("gadget")
	if widget.Leaf || !widget.RuntimeDependents || !slices.Equal(widget.Dependents, []string{"gadget"}) || widget.Version == nil || *widget.Version != "0.1.0" || !slices.Equal(widget.Targets, []string{"npm"}) {
		t.Errorf("widget %+v", widget)
	}
	if !gadget.Leaf || !slices.Equal(gadget.Dependencies, []string{"widget"}) || gadget.Releasable == nil || *gadget.Releasable != "gadget" {
		t.Errorf("gadget %+v", gadget)
	}
}

func TestTheGraphRenderings(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	g, err := ReadGraph(load(t, repo), GraphRequest{Depth: -1})
	if err != nil {
		t.Fatal(err)
	}
	tree, err := g.Render(FormatTree)
	if err != nil {
		t.Fatal(err)
	}
	if want := "gadget [leaf]\n  widget\nroot [dev] [leaf]\nwidget"; tree != want {
		t.Errorf("tree:\n%s\nwant:\n%s", tree, want)
	}
	dot, err := g.Render(FormatDot)
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range []string{"digraph dependencies {", `    "gadget" [style=filled, fillcolor=lightgreen];`, `    "root" [style=filled, fillcolor=lightgray];`, `    "gadget" -> "widget";`} {
		if !strings.Contains(dot, line+"\n") {
			t.Errorf("the DOT rendering lacks %q:\n%s", line, dot)
		}
	}
	if strings.Contains(dot, `"widget" [`) {
		t.Errorf("a member something depends on is styled:\n%s", dot)
	}
	if _, err := g.Render("text"); err == nil {
		t.Error("an unknown rendering was accepted")
	}
}

func TestTheGraphNarrowedToAMember(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	ws := load(t, repo)
	g, err := ReadGraph(ws, GraphRequest{Root: "gadget", Depth: -1})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(g.Order, []string{"widget", "gadget"}) {
		t.Errorf("--root gadget: %v", g.Order)
	}
	g, err = ReadGraph(ws, GraphRequest{Reverse: "widget", Depth: 0})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(g.Order, []string{"widget"}) || len(g.Edges) != 0 {
		t.Errorf("--reverse widget --depth 0: %+v", g)
	}
	if _, err := ReadGraph(ws, GraphRequest{Root: "portal", Depth: -1}); err == nil || !strings.Contains(err.Error(), `no member is named "portal"`) {
		t.Errorf("an unknown member: %v", err)
	}
	if _, err := ReadGraph(ws, GraphRequest{Root: "gadget", Reverse: "widget", Depth: -1}); err == nil || !strings.Contains(err.Error(), "name one of them") {
		t.Errorf("both narrowings: %v", err)
	}
}

func TestTheGraphRefusesACycle(t *testing.T) {
	hygiene.Isolate(t)
	files := map[string]string{}
	for k, v := range twoMemberFiles {
		files[k] = v
	}
	files["packages/widget/package.json"] = "{\n  \"name\": \"widget\",\n  \"version\": \"0.1.0\",\n  \"dependencies\": {\"gadget\": \"^0.2.0\"}\n}\n"
	repo := newWorkspace(t, twoMembers, files)
	if _, err := ReadGraph(load(t, repo), GraphRequest{Depth: -1}); err == nil || !strings.Contains(err.Error(), "cycle") {
		t.Fatalf("err %v", err)
	}
}

func impactOf(t *testing.T, repo *testsupport.Repo, req ImpactRequest) (Impact, error) {
	t.Helper()
	var out Impact
	var err error
	run(t, strictcli.EffectReadOnly, false, func(e *strictcli.Effects, _ func(string)) error {
		out, err = ReadImpact(openRepo(t, e, repo.Dir), load(t, repo), req)
		return nil
	})
	return out, err
}

func TestImpactOfAMemberAndOfAPath(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	for _, subject := range []string{"widget", "packages/widget/package.json", "packages/widget"} {
		got, err := impactOf(t, repo, ImpactRequest{Subjects: []string{subject}, Depth: -1})
		if err != nil {
			t.Fatalf("%s: %v", subject, err)
		}
		if !slices.Equal(got.Changed, []string{"widget"}) || !slices.Equal(got.DirectDependents, []string{"gadget"}) || !slices.Equal(got.TransitiveDependents, []string{"gadget"}) {
			t.Errorf("%s: %+v", subject, got)
		}
	}
	got, err := impactOf(t, repo, ImpactRequest{Subjects: []string{"gadget"}, Depth: -1})
	if err != nil || len(got.DirectDependents) != 0 || len(got.TransitiveDependents) != 0 {
		t.Errorf("a leaf: %+v %v", got, err)
	}
}

func TestImpactSince(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	base := repo.Head()
	repo.CommitFile("apps/gadget/index.js", "module.exports = {};\n", "gadget's entry point")
	got, err := impactOf(t, repo, ImpactRequest{Since: base, Depth: -1})
	if err != nil || !slices.Equal(got.Changed, []string{"gadget"}) || len(got.DirectDependents) != 0 {
		t.Fatalf("%+v %v", got, err)
	}
	if _, err := impactOf(t, repo, ImpactRequest{Since: "no-such-revision", Depth: -1}); err == nil || !strings.Contains(err.Error(), "names no commit") {
		t.Errorf("an unknown revision: %v", err)
	}
}

func TestImpactRefusals(t *testing.T) {
	hygiene.Isolate(t)
	repo := newWorkspace(t, twoMembers, twoMemberFiles)
	repo.Write("CHANGELOG.md", "# Changelog\n")
	repo.Write("gadget/notes.md", "a directory at the root named like a member\n")
	for _, c := range []struct {
		req  ImpactRequest
		want string
	}{
		{ImpactRequest{Depth: -1}, "name what changed"},
		{ImpactRequest{Subjects: []string{"widget"}, Since: "HEAD", Depth: -1}, "not both"},
		{ImpactRequest{Subjects: []string{"portal"}, Depth: -1}, `"portal" is neither a member's name nor a path`},
		{ImpactRequest{Subjects: []string{"CHANGELOG.md"}, Depth: -1}, "belongs to no member"},
		{ImpactRequest{Subjects: []string{"gadget"}, Depth: -1}, `"./gadget"`},
	} {
		if _, err := impactOf(t, repo, c.req); err == nil || !strings.Contains(err.Error(), c.want) {
			t.Errorf("%+v: %v", c.req, err)
		}
	}
	got, err := impactOf(t, repo, ImpactRequest{Subjects: []string{"./gadget"}, Depth: -1})
	if err != nil || !slices.Equal(got.Changed, []string{"root"}) {
		t.Errorf("the path spelled apart from the member: %+v %v", got, err)
	}
}

// offlineOnly is a registry getter for checks that ask no registry.
type offlineOnly struct{ t *testing.T }

func (o offlineOnly) Get(url string, _ ...strictcli.EffectOption) (strictcli.Response, error) {
	o.t.Errorf("a registry was asked: %s", url)
	return strictcli.Response{}, errors.New("no registry here")
}

func TestCheckNamesChecksEveryMemberThatPublishes(t *testing.T) {
	hygiene.Isolate(t)
	decls := strings.Replace(twoMembers, "name = \"widget\"\nreleasable = \"widget\"\n", "name = \"widget\"\nreleasable = \"widget\"\nregistry_name = \"acme_widget\"\n", 1)
	repo := newWorkspace(t, decls, twoMemberFiles)
	client, err := registry.New(offlineOnly{t})
	if err != nil {
		t.Fatal(err)
	}
	checks, err := CheckNames(client, load(t, repo), registry.Ecosystem("go"), "x", "", 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(checks) != 2 {
		t.Fatalf("checks %+v", checks)
	}
	if checks[0].Member != "widget" || checks[0].Name != "acme_widget" || checks[0].Result.Status != registry.StatusDiscouraged {
		t.Errorf("widget, by its registry_name: %+v", checks[0])
	}
	if checks[1].Member != "gadget" || checks[1].Name != "xgadget" || checks[1].Result.Status != registry.StatusAvailable {
		t.Errorf("gadget, with the prefix: %+v", checks[1])
	}
}
