package registry

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"slices"
	"sort"
	"strings"
	"sync"
	"unicode"
)

// goStdlibTable is the committed table of the Go standard library's
// importable packages, generated by internal/registry/gen from `go list std`
// over every platform. rlsbl never asks a Go toolchain at run time, so the
// same candidate gets the same answer on every machine.
//
//go:embed go-stdlib-packages.json
var goStdlibTable []byte

// GoStdlibTable is the decoded table.
type GoStdlibTable struct {
	Generator string   `json:"generator"`
	Source    string   `json:"source"`
	GoVersion string   `json:"go_version"`
	Packages  []string `json:"packages"`
}

var loadGoStdlib = sync.OnceValues(func() (GoStdlibTable, error) {
	var t GoStdlibTable
	if err := json.Unmarshal(goStdlibTable, &t); err != nil {
		return GoStdlibTable{}, fmt.Errorf("the embedded Go standard-library table does not decode: %w", err)
	}
	return t, nil
})

// GoStdlib is the embedded Go standard-library table.
func GoStdlib() GoStdlibTable {
	t, err := loadGoStdlib()
	if err != nil {
		// The table is compiled in; a test decodes it, so this cannot happen
		// in a binary that passed its suite.
		panic(err)
	}
	return t
}

// goKeywords are Go's keywords (https://go.dev/ref/spec#Keywords).
var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true, "default": true, "defer": true, "else": true,
	"fallthrough": true, "for": true, "func": true, "go": true, "goto": true, "if": true, "import": true, "interface": true,
	"map": true, "package": true, "range": true, "return": true, "select": true, "struct": true, "switch": true, "type": true,
	"var": true,
}

// goPredeclared are Go's predeclared identifiers
// (https://go.dev/ref/spec#Predeclared_identifiers).
var goPredeclared = map[string]bool{
	"any": true, "bool": true, "byte": true, "comparable": true, "complex64": true, "complex128": true, "error": true,
	"float32": true, "float64": true, "int": true, "int8": true, "int16": true, "int32": true, "int64": true, "rune": true,
	"string": true, "uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "uintptr": true,
	"true": true, "false": true, "iota": true, "nil": true,
	"append": true, "cap": true, "clear": true, "close": true, "complex": true, "copy": true, "delete": true, "imag": true,
	"len": true, "make": true, "max": true, "min": true, "new": true, "panic": true, "print": true, "println": true, "real": true,
	"recover": true,
}

// The Go package-name verdicts.
const (
	StatusAvailable   = "available"
	StatusTaken       = "taken"
	StatusInvalid     = "invalid"
	StatusDiscouraged = "discouraged"
	StatusError       = "error"
)

var majorVersionElement = regexp.MustCompile(`^(v[2-9][0-9]*|v1[0-9]+)$`)

// PackageNameOf is the package name an import path conventionally declares:
// its last element, or the element before a major-version suffix
// (math/rand/v2 declares rand).
func PackageNameOf(importPath string) string {
	parts := strings.Split(importPath, "/")
	if len(parts) > 1 && majorVersionElement.MatchString(parts[len(parts)-1]) {
		return parts[len(parts)-2]
	}
	return parts[len(parts)-1]
}

// StdlibPackagesNamed is every standard-library import path whose package
// name is name, sorted.
func StdlibPackagesNamed(name string) []string {
	var out []string
	for _, p := range GoStdlib().Packages {
		if PackageNameOf(p) == name {
			out = append(out, p)
		}
	}
	sort.Strings(out)
	return out
}

func isIdentLetter(r rune) bool { return r == '_' || unicode.IsLetter(r) }
func isIdentDigit(r rune) bool  { return unicode.IsDigit(r) }

// IsGoIdentifier reports whether name is a Go identifier: a letter or "_"
// followed by letters, digits, and "_".
func IsGoIdentifier(name string) bool {
	for i, r := range name {
		if i == 0 && !isIdentLetter(r) {
			return false
		}
		if !isIdentLetter(r) && !isIdentDigit(r) {
			return false
		}
	}
	return name != ""
}

// GoVerdict is the offline judgment of a Go package name.
type GoVerdict struct {
	// Status is available, taken, invalid, or discouraged.
	Status string
	// Reason is a stable token: not-identifier, keyword, blank, stdlib,
	// uppercase, underscore, or predeclared; empty when available.
	Reason string
	// Conflicts are the colliding standard-library import paths (taken).
	Conflicts []string
	// Note explains the verdict; empty when available.
	Note string
}

func invalidGoName(name, reason, why string) GoVerdict {
	return GoVerdict{
		Status: StatusInvalid,
		Reason: reason,
		Note: fmt.Sprintf("%s, so it cannot be a Go package name. A module or directory named '%s' needs a package clause "+
			"that differs from that path element, and importers see that other name; rlsbl does not choose it.", why, name),
	}
}

// JudgeGoPackageName judges name as a Go package name, offline: invalid when
// the Go spec refuses it as a package clause, taken when a standard-library
// package has that name (every file importing both needs an alias),
// discouraged when it has uppercase letters or underscores or is a
// predeclared identifier, and available otherwise. Invalid is checked
// before taken, and taken before discouraged.
func JudgeGoPackageName(name string) GoVerdict {
	if !IsGoIdentifier(name) {
		var bad []rune
		for _, r := range name {
			if !isIdentLetter(r) && !isIdentDigit(r) && !slices.Contains(bad, r) {
				bad = append(bad, r)
			}
		}
		slices.Sort(bad)
		var why string
		switch {
		case name == "":
			why = "The empty string is not a Go identifier"
		case len(bad) > 0:
			quoted := make([]string, len(bad))
			for i, r := range bad {
				quoted[i] = "'" + string(r) + "'"
			}
			why = fmt.Sprintf("'%s' is not a Go identifier (%s not allowed)", name, strings.Join(quoted, ", "))
		default:
			why = fmt.Sprintf("'%s' is not a Go identifier (it must start with a letter or '_')", name)
		}
		return invalidGoName(name, "not-identifier", why)
	}
	if goKeywords[name] {
		return invalidGoName(name, "keyword", fmt.Sprintf("'%s' is a Go keyword", name))
	}
	if name == "_" {
		return invalidGoName(name, "blank", "'_' is the blank identifier")
	}
	if conflicts := StdlibPackagesNamed(name); len(conflicts) > 0 {
		quoted := make([]string, len(conflicts))
		for i, p := range conflicts {
			quoted[i] = "'" + p + "'"
		}
		return GoVerdict{
			Status:    StatusTaken,
			Reason:    "stdlib",
			Conflicts: conflicts,
			Note:      fmt.Sprintf("conflicts with Go standard library package %s: every file importing both must rename one with an import alias", strings.Join(quoted, ", ")),
		}
	}
	type problem struct{ reason, text string }
	var problems []problem
	if strings.IndexFunc(name, unicode.IsUpper) >= 0 {
		problems = append(problems, problem{"uppercase", "it contains uppercase letters (Go package names are lowercase)"})
	}
	if strings.Contains(name, "_") {
		problems = append(problems, problem{"underscore", "it contains an underscore (Effective Go: no underscores or mixedCaps)"})
	}
	if goPredeclared[name] {
		problems = append(problems, problem{"predeclared", fmt.Sprintf("it is the predeclared identifier '%s', which the package name shadows in every importing file", name)})
	}
	if len(problems) > 0 {
		texts := make([]string, len(problems))
		for i, p := range problems {
			texts[i] = p.text
		}
		return GoVerdict{Status: StatusDiscouraged, Reason: problems[0].reason, Note: "legal but discouraged: " + strings.Join(texts, "; ")}
	}
	return GoVerdict{Status: StatusAvailable}
}
