# strictspec document version gate (do not remove)
format_version = 1
bump = "patch"
include = ["npm", "pypi", "docs"]
exclude = []
candidate_sha = "cf892f16476dea1ce57ce13d7b0db8a31935c4b8"

[tree_hashes]
"." = "48e99d3506a06f71031b494a8c4517e2a8319396"
