"""Batch release command for monorepo workspaces that validates listed items, determines topological order, and releases each sequentially.

Reads .rlsbl-monorepo/releases/unreleased.toml, validates all listed items,
determines topological release order, and releases each sequentially
by delegating to the existing single-package release flow.

In explicit mode (``[releasables.*]`` sections), iterates releasables in
dependency order (a releasable's position = max topological position of
its member packages). For each releasable, picks one representative member
package and releases through it.

In implicit mode (``[packages.*]`` sections), iterates packages directly
in topological order (original behavior).
"""

import os
import stat
import sys
import time

from ...release_file import (
    get_batch_release_file_path,
    read_batch_release_file,
)
from ...errors import ReleaseFileError
from ...lock import rlsbl_lock
from ...utils import commit_files, run
from ...workspace import find_workspace_root, load_workspace, is_explicit_mode
from ...workspace_graph import CycleError, WorkspaceGraph
from ..watch import wait_for_ci_green
from .batch_plan import (
    PLAN_FILENAME,
    BatchPlanError,
    archive_plan_file,
    compute_batch_plan,
    get_batch_plan_path,
    item_is_released,
    plan_all_released,
    read_batch_plan,
    validate_plan_against_config,
    write_batch_plan,
)
from ..release.execute import ForeignCommitError, head_sha
from ..release.validate import (
    ReleaseValidationError,
    HookError,
    _run_selfdoc_gen,
    _run_selfdoc_check,
    parse_porcelain_paths,
    validate_branch_and_remote,
    validate_clean_tree,
    validate_gh_cli,
    validate_gh_push_access,
)
from ... import effects


def _run_root_selfdoc(flags, workspace_root, log):
    """Detect and run selfdoc at the workspace root if selfdoc.json exists there.

    Member-level selfdoc is handled by the per-member release flow.  This
    function covers the case where selfdoc.json lives at the repo root only
    (e.g. a monorepo-wide docs site).

    Runs ``selfdoc gen --no-auto-commit`` and ``selfdoc check``, then commits
    any generated files so the tree is clean for per-member validation.
    """
    selfdoc_config = os.path.join(workspace_root, "selfdoc.json")
    if not os.path.exists(selfdoc_config):
        return

    log("Detected selfdoc.json at workspace root")

    # Snapshot dirty files before selfdoc runs. All git operations here are
    # anchored to workspace_root -- never the process cwd. An unanchored
    # ``git status``/commit here once walked up from a TMPDIR-inside-repo
    # fixture into the real repo and committed junk (the Jul junk-commit
    # incidents); the explicit cwd makes the target repo unambiguous.
    pre_output = run("git", ["status", "--porcelain"], cwd=workspace_root)
    pre_dirty = parse_porcelain_paths(pre_output) if pre_output else set()

    _run_selfdoc_gen(flags, project_dir=workspace_root)
    _run_selfdoc_check(flags, project_dir=workspace_root)

    if flags.get("dry-run", False):
        return

    # Commit any files selfdoc generated (diff against pre-selfdoc snapshot)
    post_output = run("git", ["status", "--porcelain"], cwd=workspace_root)
    post_dirty = parse_porcelain_paths(post_output) if post_output else set()
    selfdoc_generated = post_dirty - pre_dirty
    if selfdoc_generated:
        commit_files(
            "selfdoc: regenerate (workspace root)",
            sorted(selfdoc_generated),
            autogenerated=True,
            cwd=workspace_root,
            expected_root=workspace_root,
        )
        log("Committed root-level selfdoc-generated files")


def _batch_release_flags(flags, **extra):
    """Per-item release flags for the batch loop."""
    release_flags = {
        "dry-run": flags.get("dry-run", False),
        "yes": flags.get("yes", False),
        "quiet": flags.get("quiet", False),
        "allow-dirty": flags.get("allow-dirty", False),
        "skip-lock": True,
        "batch-mode": True,
    }
    for key in ("push-timeout", "ci-timeout", "check-timeout", "hook-timeout"):
        if flags.get(key) is not None:
            release_flags[key] = flags[key]
    release_flags.update(extra)
    return release_flags


def _commits_between(start, end, workspace_root):
    """The commits in ``start..end``, newest first; empty when unresolvable.

    Bookkeeping for the batch drift guard, so it goes through
    ``effects.run`` directly rather than the release flow's mock-patched
    ``run`` -- the same rationale as
    :func:`~rlsbl.commands.release.execute.head_sha`. An unresolvable range
    yields no trail entries, and an unresolvable pin disables the guard
    outright, so neither can fabricate a foreign commit.
    """
    if not start or not end:
        return []
    try:
        out = effects.run(
            ["git", "rev-list", f"{start}..{end}"],
            capture_output=True, text=True, check=True, cwd=workspace_root,
        ).stdout
    except Exception:
        return []
    return [c.strip() for c in out.splitlines() if c.strip()]


def _batch_release_trail(pending, inline_commits):
    """The union of every batch member's own release-commit trail.

    Members still mid-flight keep their trail in their in-progress state file.
    A member whose release ran to completion inside its own call cleared that
    file, so the orchestrator records the commits that appeared across its call
    in *inline_commits* instead.
    """
    trail = set(inline_commits)
    for entry in pending:
        state = read_state_for_resume(entry[2])
        trail.update((state or {}).get("release_commits", []))
    return trail


def _batch_ci_gate(workspace_root, flags, log, *, pin_sha=None, trail=()):
    """Run ONE CI gate for the whole batch and return the verified SHA.

    Every member's candidate has been pushed by this point (the first pass runs
    with ``ci-defer``), so the branch tip contains all of them and a single CI
    verdict covers the batch. Each member is then tagged on exactly this
    commit, so every tag in the batch points at a CI-verified tree.

    Refuse-on-drift: the tip is guarded against foreign commits before it is
    gated. The per-member guards only cover each member's own call, so a commit
    that landed between the last candidate push and this gate -- a concurrent
    session sharing the worktree, say -- would otherwise ride into every tag in
    the batch. It is a hard error naming the SHAs; nothing is rolled back
    (the candidates are already on the remote).

    Returns the verified SHA. Raises :class:`ReleaseValidationError` when CI is
    red, unresolved or unreachable -- the candidates stay on the branch
    untagged, nothing is finalized, and no version number is burnt.
    """
    from ...utils import get_ci_timeout
    from ..release.execute import guard_foreign_commits
    from ..watch import CI_GREEN, CI_NOT_CONFIGURED, CI_TIMEOUT, CIWaitError

    guard_foreign_commits(
        pin_sha, trail, cwd=workspace_root, phase="batch CI gate",
    )

    sha = run("git", ["rev-parse", "HEAD"], cwd=workspace_root).strip()
    # Config is per-project in a workspace; the batch gate is a workspace-level
    # wait, so only the CLI override applies here (no single config owns it).
    timeout = get_ci_timeout(None, override=flags.get("ci-timeout"))
    try:
        verdict, results = wait_for_ci_green(
            sha, timeout=timeout, log=log, repo_root=workspace_root,
            label=f"batch candidate {sha[:12]}",
        )
    except CIWaitError as exc:
        raise ReleaseValidationError(str(exc)) from exc

    if verdict == CI_NOT_CONFIGURED:
        # Unconditional and on stderr: this notice is the operator's only
        # signal that the batch shipped with NO CI gate, and --quiet must not
        # be able to swallow it.
        print(
            "rlsbl: no push-triggered CI workflow is configured in "
            ".github/workflows; proceeding without a CI gate.",
            file=sys.stderr,
        )
        return sha
    if verdict == CI_TIMEOUT:
        unresolved = ", ".join(
            r["name"] for r in results if r.get("timed_out")
        ) or "unknown"
        raise ReleaseValidationError(
            f"The CI wait for the batch release candidate {sha} ran out of "
            f"time before every run concluded.\n"
            f"  Unresolved workflow(s) after {timeout}s: {unresolved}\n"
            f"\n"
            f"This is NOT a CI failure: those runs may still be in progress, "
            f"and nothing was proven about the candidate either way.\n"
            f"Nothing in this batch was tagged, released or finalized -- no "
            f"version number was burnt.\n"
            f"\n"
            f"Check the runs with `rlsbl watch {sha[:12]}`. When they are "
            f"green, re-run `rlsbl monorepo release run`: each member resumes "
            f"at its own unchanged version. If CI is merely slow, raise the "
            f"budget with `--ci-timeout`."
        )
    if verdict != CI_GREEN:
        red = ", ".join(
            r["name"] for r in results
            if not r["passed"] and not r.get("timed_out")
        ) or "unknown"
        raise ReleaseValidationError(
            f"CI did not pass on the batch release candidate {sha}.\n"
            f"  Failing workflow(s): {red}\n"
            f"\n"
            f"Nothing in this batch was tagged, released or finalized -- no "
            f"version number was burnt. Every member's version-bump commit is "
            f"on the release branch, which is the design: the branch carries "
            f"the candidate until CI proves it green.\n"
            f"Fix forward on the release branch, then re-run "
            f"`rlsbl monorepo release run`: each member resumes at its own "
            f"unchanged version."
        )
    log(f"CI is green on the batch candidate {sha[:12]}")
    return sha


def _resume_batch_item(name, project_dir, workspace_root, state_path, flags,
                       verified_sha, log):
    """Second batch pass: finish one member on the verified candidate."""
    from pathlib import Path

    from ...context import create_context
    from ..release import resume_cmd

    saved = read_state_for_resume(state_path)
    if saved is None:
        raise ReleaseValidationError(
            f"release state for {name!r} vanished between the candidate push "
            f"and the CI gate ({state_path}). Investigate before retrying."
        )
    pkg_ctx = create_context(Path(project_dir), workspace_root=Path(workspace_root))
    resume_cmd(
        saved,
        _batch_release_flags(flags, **{"ci-verified-sha": verified_sha}),
        ctx=pkg_ctx,
    )


def read_state_for_resume(state_path):
    from ..release.release_state import load_release_state

    return load_release_state(state_path)


def _releasable_release_order(batch_names, releasables, projects, graph):
    """Compute release order for releasables based on member topological positions.

    A releasable's position is the maximum topological position of its member
    packages. This ensures that a releasable whose members depend on members
    of another releasable is released after the dependency.

    Returns an ordered list of releasable names from the batch.
    """
    from ...workspace import members_of

    full_order = graph.topological_order()
    position = {name: i for i, name in enumerate(full_order)}

    releasable_positions = {}
    for rel in releasables:
        if rel.name not in batch_names:
            continue
        members = members_of(rel.name, projects)
        if members:
            max_pos = max(position.get(m["name"], 0) for m in members)
        else:
            max_pos = 0
        releasable_positions[rel.name] = max_pos

    return sorted(batch_names, key=lambda n: releasable_positions.get(n, 0))


def _cmd_batch_release(flags, project_root):
    """Execute a batch release of multiple monorepo packages or releasables."""
    start = str(project_root)
    workspace_root = find_workspace_root(start)
    if workspace_root is None:
        print(
            "Error: No workspace found. Run 'rlsbl monorepo init' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    batch_path = get_batch_release_file_path(workspace_root)
    if not os.path.exists(batch_path):
        print(
            "Error: No batch release file found at "
            f"{os.path.relpath(batch_path)}.\n"
            "Create .rlsbl-monorepo/releases/unreleased.toml with "
            "[packages.<name>] or [releasables.<name>] sections.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        batch_config = read_batch_release_file(batch_path)
    except ReleaseFileError as e:
        print(f"Error in batch release file: {e}", file=sys.stderr)
        sys.exit(1)

    quiet = flags.get("quiet", False)
    dry_run = flags.get("dry-run", False)

    def log(msg):
        if not quiet:
            print(msg)

    projects = load_workspace(workspace_root)
    explicit = is_explicit_mode(workspace_root)

    if batch_config.section_type == "releasables" and not explicit:
        print(
            "Error: batch release file uses [releasables] sections but the "
            "workspace is in implicit mode (no [[releasables]] in workspace.toml).",
            file=sys.stderr,
        )
        sys.exit(1)

    # --- Repair pass / resolved-plan handling ---
    # If a plan sidecar already exists, this is not a fresh batch: validate it
    # against the current batch file (never regenerate) and, if every item is
    # provably released, archive both files and stop -- the batch is complete
    # and the on-disk unreleased.toml is a stale leftover from a mid-loop crash.
    plan_path = get_batch_plan_path(workspace_root)
    plan = None
    try:
        plan = read_batch_plan(plan_path)
    except FileNotFoundError:
        plan = None
    if plan is not None:
        try:
            validate_plan_against_config(plan, batch_config)
        except BatchPlanError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)

        if not dry_run and plan_all_released(workspace_root, plan, projects):
            with rlsbl_lock(".rlsbl-monorepo", project_root=workspace_root):
                archived = _archive_batch_if_complete(
                    batch_path, plan, workspace_root, projects, log,
                )
            if archived:
                log(
                    "Batch release already complete (all items released per "
                    "plan); archived the stale batch file and plan."
                )
                return
            # All released per plan, but a stranded in-progress.json blocks
            # archival: fall through so the unfinished release can be resumed
            # (or the operator can roll it back) -- never silently archive it.

    # Upfront validation: fail before releasing anything
    try:
        validate_gh_cli()
        validate_gh_push_access()
        validate_clean_tree(flags)
        validate_branch_and_remote(flags, cwd=workspace_root)
    except ReleaseValidationError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Root-level selfdoc: run once before per-member releases so generated
    # files are committed and the tree is clean for per-member validation.
    try:
        _run_root_selfdoc(flags, workspace_root, log)
    except HookError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # The plan (possibly None here) is passed to the mode functions. When it is
    # None and this is not a dry-run, the mode function resolves and persists a
    # fresh plan AFTER validating item membership (so version/tag computation
    # only runs for items that actually exist in the workspace).
    if batch_config.section_type == "releasables":
        _batch_release_releasables(
            flags, workspace_root, batch_path, batch_config, projects,
            plan, plan_path,
        )
    else:
        _batch_release_packages(
            flags, workspace_root, batch_path, batch_config, projects,
            plan, plan_path,
        )


def _resolve_fresh_plan(workspace_root, batch_config, projects, plan_path, log):
    """Compute, persist, and commit a fresh resolved plan.

    Called by the mode functions after item membership has been validated.
    A plan-less batch whose target tags already exist predates resolved-plan
    tracking -- that is a hard error (no guessing about partial legacy runs).
    Returns the BatchPlan.
    """
    try:
        plan = compute_batch_plan(workspace_root, batch_config, projects)
    except ReleaseValidationError as e:
        if "already exists" in str(e):
            _abort_legacy_plan_less_batch(
                get_batch_release_file_path(workspace_root), plan_path, str(e)
            )
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    write_batch_plan(plan_path, plan)
    commit_files(
        "chore: resolve batch release plan",
        [os.path.normpath(plan_path)],
        autogenerated=True,
        allow_failure=True,
    )
    log("Resolved batch release plan (base/target versions, tags).")
    return plan


def _abort_legacy_plan_less_batch(batch_path, plan_path, detail):
    """Hard error for a plan-less batch file that was already (partly) released.

    A batch ``unreleased.toml`` with no plan sidecar whose target tags already
    exist predates resolved-plan tracking: it was partially executed by an
    older rlsbl that never persisted base versions, so there is no safe way to
    decide which items still need releasing. Refuse to guess.
    """
    print(
        "Error: found a batch release file that predates resolved-plan "
        "tracking and appears to have been partially released.\n"
        f"  Batch file: {os.path.relpath(batch_path)}\n"
        f"  Missing plan sidecar: {os.path.relpath(plan_path)}\n"
        f"  Detail: {detail}\n"
        "Without a resolved plan, rlsbl cannot tell which items are already "
        "released. Resolve manually:\n"
        "  1. For each item in the batch file, verify whether its release "
        "already completed (check `git tag` and the published version).\n"
        "  2. If the batch is fully released, archive the batch file manually "
        "(move it out of .rlsbl-monorepo/releases/).\n"
        "  3. Otherwise, delete the batch file and re-run "
        "`rlsbl monorepo release init` to start a fresh, plan-tracked batch.",
        file=sys.stderr,
    )
    sys.exit(1)


def _batch_release_releasables(flags, workspace_root, batch_path, batch_config,
                               projects, plan=None, plan_path=None):
    """Execute batch release in releasable mode."""
    from ...workspace import load_releasables, members_of

    releasables = load_releasables(workspace_root, projects)
    releasable_by_name = {r.name: r for r in releasables}

    # Validate all releasable names exist
    missing = set(batch_config.packages.keys()) - set(releasable_by_name.keys())
    if missing:
        print(
            f"Error: releasables not found in workspace: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Build graph and compute release order
    graph = WorkspaceGraph(workspace_root, projects)
    try:
        graph.topological_order()
    except CycleError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    batch_names = set(batch_config.packages.keys())
    release_order = _releasable_release_order(
        batch_names, releasables, projects, graph,
    )

    dry_run = flags.get("dry-run", False)
    quiet = flags.get("quiet", False)

    def log(msg):
        if not quiet:
            print(msg)

    # Resolve a fresh plan now that membership is validated (skip in dry-run).
    if plan is None and not dry_run and plan_path is not None:
        plan = _resolve_fresh_plan(
            workspace_root, batch_config, projects, plan_path, log,
        )

    log(f"Batch release: {len(release_order)} releasable(s)")
    log(f"Release order: {', '.join(release_order)}")

    if dry_run:
        for i, name in enumerate(release_order, 1):
            rc = batch_config.packages[name]
            log(f"  {i}. {name} ({rc.bump}) — {rc.description}")

    log("")

    released = []
    last_sha = None
    with rlsbl_lock(".rlsbl-monorepo", project_root=workspace_root):
        # Workspace-level pin, taken before the first candidate is built. Every
        # commit that appears in pin..HEAD must be one a member's own release
        # call created; anything else is a ride-in and aborts the gate.
        batch_pin = None if dry_run else head_sha(cwd=workspace_root)
        inline_commits = []
        # Pass 1: push every member's candidate untagged (the CI gate is
        # deferred so ONE wait covers the whole batch).
        pending = []
        for rel_name in release_order:
            release_config = batch_config.packages[rel_name]
            member_projs = members_of(rel_name, projects)
            if not member_projs:
                print(f"Error: releasable '{rel_name}' has no member projects.", file=sys.stderr)
                sys.exit(1)

            # Per-item idempotency: skip a releasable that is already released
            # per the resolved plan (live version == target and tag exists).
            if plan is not None and not dry_run:
                plan_item = plan.items[rel_name]
                if item_is_released(workspace_root, plan_item, projects, "releasables"):
                    log(
                        f"--- Skipping releasable {rel_name}: already released "
                        f"at {plan_item.target_version} (tag {plan_item.tag}) ---"
                    )
                    log("")
                    continue

            # Pick the first member as the representative for the release flow
            representative = member_projs[0]
            project_dir = os.path.join(workspace_root, representative["path"])

            log(f"--- Releasing releasable {rel_name} ({release_config.bump}) ---")

            try:
                from pathlib import Path

                from ...context import create_context
                from ..release import run_cmd

                release_flags = _batch_release_flags(
                    flags, **({} if dry_run else {"ci-defer": True}),
                )
                pkg_ctx = create_context(Path(project_dir), workspace_root=Path(workspace_root))
                _before = None if dry_run else head_sha(cwd=workspace_root)
                run_cmd(release_config, release_flags, ctx=pkg_ctx)
                if dry_run:
                    released.append(rel_name)
                else:
                    from ...workspace_types import get_releasable_dir as _grd
                    from ..release.release_state import get_state_path as _gsp
                    _sp = _gsp(
                        workspace_root,
                        releasable_dir=_grd(workspace_root, rel_name),
                    )
                    if os.path.exists(_sp):
                        pending.append((rel_name, project_dir, _sp))
                    else:
                        # No in-progress state means nothing is in progress:
                        # the member's release ran to completion inside its own
                        # call (every step already satisfied), so there is
                        # nothing for the batch gate to finish. The archive
                        # gate below is the correctness backstop.
                        released.append(rel_name)
                        last_sha = run("git", ["rev-parse", "HEAD"])
                        # Its trail died with its state file; the commits that
                        # appeared across its call are the batch's own.
                        inline_commits.extend(
                            _commits_between(_before, last_sha.strip(),
                                             workspace_root)
                        )
            except SystemExit as e:
                if e.code != 0:
                    print(
                        f"\nError: release of releasable {rel_name} failed. "
                        f"Successfully released: {', '.join(released) if released else '(none)'}",
                        file=sys.stderr,
                    )
                    raise

            log("")

        # One CI gate for the whole batch, then pass 2: finalize, tag and
        # release each member on the verified candidate.
        if pending:
            try:
                verified_sha = _batch_ci_gate(
                    workspace_root, flags, log,
                    pin_sha=batch_pin,
                    trail=_batch_release_trail(pending, inline_commits),
                )
            except ForeignCommitError as e:
                # A ride-in on the batch tip. Never rolled back: those commits
                # are exactly what must be preserved. Every member's candidate
                # is on the branch untagged and no version is burnt.
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            except ReleaseValidationError as e:
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            for rel_name, project_dir, state_path in pending:
                log(f"--- Completing releasable {rel_name} ---")
                try:
                    _resume_batch_item(
                        rel_name, project_dir, workspace_root, state_path,
                        flags, verified_sha, log,
                    )
                except ReleaseValidationError as e:
                    print(f"Error: {e}", file=sys.stderr)
                    sys.exit(1)
                except SystemExit as e:
                    if e.code != 0:
                        print(
                            f"\nError: release of releasable {rel_name} failed. "
                            f"Successfully released: {', '.join(released) if released else '(none)'}",
                            file=sys.stderr,
                        )
                        raise
                released.append(rel_name)
                log("")
            last_sha = verified_sha

        # Archive is state-driven: only fires when every plan item is released.
        if not dry_run:
            _archive_batch_if_complete(batch_path, plan, workspace_root, projects, log)

    # Log completion BEFORE watch, because watch_run_cmd() calls sys.exit().
    log(f"Batch release complete: {', '.join(released)}")

    if not dry_run and last_sha:
        # Watch CI or print hint for the last release's commit
        if flags.get("watch"):
            log(f"Watching CI for {last_sha}...")
            from ..watch import run_cmd as watch_run_cmd
            watch_run_cmd(None, [last_sha], {})
        else:
            log(f"Watch CI: rlsbl watch {last_sha}")


def _batch_release_packages(flags, workspace_root, batch_path, batch_config,
                            projects, plan=None, plan_path=None):
    """Execute batch release in package mode (implicit, original behavior)."""
    project_names = {p["name"] for p in projects}
    project_by_name = {p["name"]: p for p in projects}

    # Validate all packages exist in workspace
    missing = set(batch_config.packages.keys()) - project_names
    if missing:
        print(
            f"Error: packages not found in workspace: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Reject non-releasable projects
    non_releasable_in_batch = sorted(
        name
        for name in batch_config.packages
        if not project_by_name[name].is_releasable
    )
    if non_releasable_in_batch:
        print(
            "Error: non-releasable projects cannot be in batch release: "
            f"{', '.join(non_releasable_in_batch)}. "
            "Set releasable = \"<name>\" in workspace.toml if these projects "
            "should be releasable.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Determine topological order for the listed packages
    graph = WorkspaceGraph(workspace_root, projects)
    try:
        full_order = graph.topological_order()
    except CycleError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    # Filter to only the packages in the batch, preserving topological order
    batch_names = set(batch_config.packages.keys())
    release_order = [name for name in full_order if name in batch_names]

    dry_run = flags.get("dry-run", False)
    quiet = flags.get("quiet", False)

    def log(msg):
        if not quiet:
            print(msg)

    # Resolve a fresh plan now that membership is validated (skip in dry-run).
    if plan is None and not dry_run and plan_path is not None:
        plan = _resolve_fresh_plan(
            workspace_root, batch_config, projects, plan_path, log,
        )

    log(f"Batch release: {len(release_order)} package(s)")
    log(f"Release order: {', '.join(release_order)}")

    if dry_run:
        for i, name in enumerate(release_order, 1):
            rc = batch_config.packages[name]
            log(f"  {i}. {name} ({rc.bump}) — {rc.description}")

    log("")

    # Release each package in order
    released = []
    last_sha = None
    with rlsbl_lock(".rlsbl-monorepo", project_root=workspace_root):
        # Workspace-level pin, taken before the first candidate is built. Every
        # commit that appears in pin..HEAD must be one a member's own release
        # call created; anything else is a ride-in and aborts the gate.
        batch_pin = None if dry_run else head_sha(cwd=workspace_root)
        inline_commits = []
        # Pass 1: push every package's candidate untagged (the CI gate is
        # deferred so ONE wait covers the whole batch).
        pending = []
        for pkg_name in release_order:
            release_config = batch_config.packages[pkg_name]
            project = project_by_name[pkg_name]
            project_dir = os.path.join(workspace_root, project["path"])

            # Per-item idempotency: skip a package already released per the
            # resolved plan (live version == target and tag exists).
            if plan is not None and not dry_run:
                plan_item = plan.items[pkg_name]
                if item_is_released(workspace_root, plan_item, projects, "packages"):
                    log(
                        f"--- Skipping {pkg_name}: already released at "
                        f"{plan_item.target_version} (tag {plan_item.tag}) ---"
                    )
                    log("")
                    continue

            log(f"--- Releasing {pkg_name} ({release_config.bump}) ---")

            try:
                from pathlib import Path

                from ...context import create_context
                from ..release import run_cmd

                release_flags = _batch_release_flags(
                    flags, **({} if dry_run else {"ci-defer": True}),
                )
                pkg_ctx = create_context(Path(project_dir), workspace_root=Path(workspace_root))
                _before = None if dry_run else head_sha(cwd=workspace_root)
                run_cmd(release_config, release_flags, ctx=pkg_ctx)
                if dry_run:
                    released.append(pkg_name)
                else:
                    from ..release.release_state import get_state_path as _gsp
                    _sp = _gsp(project_dir)
                    if os.path.exists(_sp):
                        pending.append((pkg_name, project_dir, _sp))
                    else:
                        # No in-progress state means nothing is in progress:
                        # the package's release ran to completion inside its
                        # own call. The archive gate below is the backstop.
                        released.append(pkg_name)
                        last_sha = run("git", ["rev-parse", "HEAD"])
                        # Its trail died with its state file; the commits that
                        # appeared across its call are the batch's own.
                        inline_commits.extend(
                            _commits_between(_before, last_sha.strip(),
                                             workspace_root)
                        )
            except SystemExit as e:
                if e.code != 0:
                    print(
                        f"\nError: release of {pkg_name} failed. "
                        f"Successfully released: {', '.join(released) if released else '(none)'}",
                        file=sys.stderr,
                    )
                    raise

            log("")

        # One CI gate for the whole batch, then pass 2: finalize, tag and
        # release each package on the verified candidate.
        if pending:
            try:
                verified_sha = _batch_ci_gate(
                    workspace_root, flags, log,
                    pin_sha=batch_pin,
                    trail=_batch_release_trail(pending, inline_commits),
                )
            except ForeignCommitError as e:
                # A ride-in on the batch tip. Never rolled back: those commits
                # are exactly what must be preserved. Every member's candidate
                # is on the branch untagged and no version is burnt.
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            except ReleaseValidationError as e:
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            for pkg_name, project_dir, state_path in pending:
                log(f"--- Completing {pkg_name} ---")
                try:
                    _resume_batch_item(
                        pkg_name, project_dir, workspace_root, state_path,
                        flags, verified_sha, log,
                    )
                except ReleaseValidationError as e:
                    print(f"Error: {e}", file=sys.stderr)
                    sys.exit(1)
                except SystemExit as e:
                    if e.code != 0:
                        print(
                            f"\nError: release of {pkg_name} failed. "
                            f"Successfully released: {', '.join(released) if released else '(none)'}",
                            file=sys.stderr,
                        )
                        raise
                released.append(pkg_name)
                log("")
            last_sha = verified_sha

        # Archive is state-driven: only fires when every plan item is released.
        if not dry_run:
            _archive_batch_if_complete(batch_path, plan, workspace_root, projects, log)

    # Log completion BEFORE watch, because watch_run_cmd() calls sys.exit().
    log(f"Batch release complete: {', '.join(released)}")

    if not dry_run and last_sha:
        # Watch CI or print hint for the last release's commit
        if flags.get("watch"):
            log(f"Watching CI for {last_sha}...")
            from ..watch import run_cmd as watch_run_cmd
            watch_run_cmd(None, [last_sha], {})
        else:
            log(f"Watch CI: rlsbl watch {last_sha}")


def _plan_items_in_progress(plan, workspace_root, projects):
    """Return the names of plan items with an on-disk in-progress.json.

    A per-item release state file means that item's release did not run to
    completion (it crashed mid-flight or is mid-resume). A successful release
    clears its state file, so a lingering one is evidence of an unfinished
    release that the batch archive must not strand.
    """
    from ..release.release_state import get_state_path
    from ...workspace_types import get_releasable_dir

    project_by_name = {p["name"]: p for p in projects}
    stranded = []
    for name in plan.items:
        if plan.section_type == "releasables":
            rel_dir = get_releasable_dir(workspace_root, name)
            state_path = get_state_path(workspace_root, releasable_dir=rel_dir)
        else:
            project = project_by_name.get(name)
            if project is None:
                continue
            project_dir = os.path.join(workspace_root, project["path"])
            state_path = get_state_path(project_dir)
        if os.path.exists(state_path):
            stranded.append(name)
    return stranded


def _archive_batch_if_complete(batch_path, plan, workspace_root, projects, log):
    """State-driven archive gate: finalize iff every plan item is released.

    This is the idempotent guard around :func:`_finalize_batch_file`. It is
    called both at the batch-loop tail and (via the repair pass) at the start
    of the command. When no plan exists (dry-run never reaches here), it is a
    no-op.

    Beyond the released-per-plan check, it refuses to archive when ANY plan
    item still has an in-progress.json on disk -- an unfinished/resumable
    release must never be silently archived away.
    """
    if plan is None:
        return False
    if not plan_all_released(workspace_root, plan, projects):
        log(
            "Not archiving batch file: some plan items are not yet released."
        )
        return False
    stranded = _plan_items_in_progress(plan, workspace_root, projects)
    if stranded:
        log(
            "Not archiving batch file: in-progress release state exists for "
            f"{', '.join(stranded)}. Resume or roll back those releases first."
        )
        return False
    _finalize_batch_file(batch_path, log)
    return True


def _finalize_batch_file(batch_path, log):
    """Rename the batch release file (and its plan sidecar) and lock them.

    Idempotent: a no-op when the batch file has already been archived. The plan
    sidecar, when present, is archived alongside under the same timestamped
    stem so the two always travel together.
    """
    if not os.path.exists(batch_path):
        log("Batch release file already archived; nothing to finalize.")
        return

    releases_dir = os.path.dirname(batch_path)
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    versioned_stem = f"batch-{timestamp}"
    versioned_name = f"{versioned_stem}.toml"
    versioned_path = os.path.join(releases_dir, versioned_name)

    effects.rename(batch_path, versioned_path)
    effects.chmod(versioned_path, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)  # 444

    # Commit finalized files
    finalize_files = [
        os.path.normpath(versioned_path),
        os.path.normpath(batch_path),
    ]

    # Archive the resolved-plan sidecar alongside, under the same stem.
    plan_path = os.path.join(releases_dir, PLAN_FILENAME)
    finalize_files.extend(archive_plan_file(plan_path, versioned_stem))

    commit_files(
        f"chore: finalize batch release file ({versioned_name})",
        finalize_files,
        allow_failure=True,
    )
    log(f"Finalized batch release file: {versioned_name}")
