"""Batch release command for monorepo workspaces that validates listed items, determines topological order, and releases each sequentially.

Reads .rlsbl-monorepo/releases/unreleased.toml, validates all listed items,
determines topological release order, and releases each sequentially
by delegating to the existing single-package release flow.

In explicit mode (``[releasables.*]`` sections), iterates releasables in
dependency order (a releasable's position = max topological position of
its member packages). For each releasable, picks one representative member
package and releases through it.

In implicit mode (``[packages.*]`` sections), iterates packages directly
in topological order (original behavior).
"""

import os
import stat
import subprocess
import sys
import time

from ...release_file import (
    get_batch_release_file_path,
    read_batch_release_file,
)
from ...errors import ConfigError, GitError, ReleaseFileError
from ...lock import rlsbl_lock
from ...utils import commit_files, run
from ...workspace import find_workspace_root, load_workspace, is_explicit_mode
from ...workspace_graph import CycleError, WorkspaceGraph
from ..watch import wait_for_ci_green
from .batch_plan import (
    PLAN_FILENAME,
    BatchPlanError,
    archive_plan_file,
    compute_batch_plan,
    get_batch_plan_path,
    item_is_released,
    plan_all_released,
    read_batch_plan,
    validate_plan_against_config,
    write_batch_plan,
)
from ..release.execute import (
    ForeignCommitError,
    ReleaseCIError,
    _announce_unverified_publication,
    _verify_publication_members,
    head_sha,
)
from ..release.validate import (
    ReleaseValidationError,
    HookError,
    _run_selfdoc_gen,
    _run_selfdoc_check,
    parse_porcelain_paths,
    validate_branch_and_remote,
    validate_clean_tree,
    validate_gh_cli,
    validate_gh_push_access,
)
from ... import effects


def _run_root_selfdoc(flags, workspace_root, log):
    """Detect and run selfdoc at the workspace root if selfdoc.json exists there.

    Member-level selfdoc is handled by the per-member release flow.  This
    function covers the case where selfdoc.json lives at the repo root only
    (e.g. a monorepo-wide docs site).

    Runs ``selfdoc gen --no-auto-commit`` and ``selfdoc check``, then commits
    any generated files so the tree is clean for per-member validation.
    """
    selfdoc_config = os.path.join(workspace_root, "selfdoc.json")
    if not os.path.exists(selfdoc_config):
        return

    log("Detected selfdoc.json at workspace root")

    # Snapshot dirty files before selfdoc runs. All git operations here are
    # anchored to workspace_root -- never the process cwd. An unanchored
    # ``git status``/commit here once walked up from a TMPDIR-inside-repo
    # fixture into the real repo and committed junk (the Jul junk-commit
    # incidents); the explicit cwd makes the target repo unambiguous.
    pre_output = run("git", ["--no-optional-locks", "status", "--porcelain"], cwd=workspace_root)
    pre_dirty = parse_porcelain_paths(pre_output) if pre_output else set()

    _run_selfdoc_gen(flags, project_dir=workspace_root)
    _run_selfdoc_check(flags, project_dir=workspace_root)

    if flags.get("dry-run", False):
        return

    # Commit any files selfdoc generated (diff against pre-selfdoc snapshot)
    post_output = run("git", ["--no-optional-locks", "status", "--porcelain"], cwd=workspace_root)
    post_dirty = parse_porcelain_paths(post_output) if post_output else set()
    selfdoc_generated = post_dirty - pre_dirty
    if selfdoc_generated:
        commit_files(
            "selfdoc: regenerate (workspace root)",
            sorted(selfdoc_generated),
            autogenerated=True,
            cwd=workspace_root,
            expected_root=workspace_root,
        )
        log("Committed root-level selfdoc-generated files")


def _batch_release_flags(flags, **extra):
    """Per-item release flags for the batch loop."""
    release_flags = {
        "dry-run": flags.get("dry-run", False),
        "quiet": flags.get("quiet", False),
        "allow-dirty": flags.get("allow-dirty", False),
        "skip-lock": True,
        "batch-mode": True,
        # The branch the orchestrator already resolved and validated.
        "release-branch": flags.get("release-branch"),
    }
    for key in ("push-timeout", "ci-timeout", "check-timeout", "hook-timeout"):
        if flags.get(key) is not None:
            release_flags[key] = flags[key]
    release_flags.update(extra)
    return release_flags


def _commits_between(start, end, workspace_root):
    """The commits in ``start..end``, newest first; empty when unresolvable.

    Bookkeeping for the batch drift guard, so it goes through
    ``effects.run`` directly rather than the release flow's mock-patched
    ``run`` -- the same rationale as
    :func:`~rlsbl.commands.release.execute.head_sha`. An unresolvable range
    yields no trail entries, and an unresolvable pin disables the guard
    outright, so neither can fabricate a foreign commit.
    """
    if not start or not end:
        return []
    try:
        out = effects.run(
            ["git", "rev-list", f"{start}..{end}"],
            capture_output=True, text=True, check=True, cwd=workspace_root,
        ).stdout
    except Exception:
        return []
    return [c.strip() for c in out.splitlines() if c.strip()]


def _batch_release_trail(pending, inline_commits):
    """The union of every batch member's own release-commit trail.

    Members still mid-flight keep their trail in their in-progress state file.
    A member whose release ran to completion inside its own call cleared that
    file, so the orchestrator records the commits that appeared across its call
    in *inline_commits* instead.
    """
    trail = set(inline_commits)
    for entry in pending:
        state = read_state_for_resume(entry[2])
        trail.update((state or {}).get("release_commits", []))
    return trail


def _watch_and_verify_batch(flags, last_sha, probe_specs, log):
    """The batch's watch tail: CI verdict, then the registry outcome check.

    Both batch loops (releasable and package mode) end here so the two paths
    cannot drift. Under ``--watch`` the CI wait runs first -- a green run is
    what makes the registry question meaningful, since CI is what runs the
    publish jobs -- and every member is then probed for its own new version.
    A red CI exits with CI's own code: reporting missing artifacts on top of a
    failed publish adds nothing.

    Under ``--no-watch`` NOTHING is probed, deliberately: the publish workflow
    is still in flight, so a probe would report every member as missing and
    fail every ``--no-watch`` batch. The run says so out loud instead (see
    :func:`_announce_unverified_publication`).
    """
    if not flags.get("watch"):
        _announce_unverified_publication(last_sha, log)
        return
    log(f"Watching CI for {last_sha}...")
    from ..watch import run_cmd as watch_run_cmd
    # watch_run_cmd exits with CI's verdict; catch it so the outcome check
    # below can run on a green one.
    watch_code = 0
    try:
        watch_run_cmd(None, [last_sha], {})
    except SystemExit as e:
        watch_code = e.code or 0
    if watch_code:
        sys.exit(watch_code)
    _verify_publication_members(probe_specs, log=log)


def _member_probe_spec(name, project_dir, workspace_root, state_path, log):
    """One member's ``(label, resolved_targets, version, tag, ctx)`` probe spec.

    Built from the member's release state BEFORE pass 2 runs, because a member
    that finishes clears its state file -- by the time the batch reaches its
    watch tail there is nothing left to read the version and targets out of.

    Targets are resolved through :func:`resolve_member_context`, the same
    single source of truth the release flow itself uses, so releasable-level
    ``publish_mode`` / ``targets`` inheritance applies exactly as it did during
    the release.

    Returns ``None`` when no spec can be built: the state carries no version
    (an item that never entered the mutating phase), or the member's config
    cannot be resolved into targets. The second case is SAID OUT LOUD rather
    than swallowed, and never converted into a verdict -- the same stance
    :func:`~rlsbl.commands.release.execute._probe_publication` takes on an
    inconclusive probe. Raising instead would turn a finished, tagged, released
    batch into a crash over the bookkeeping for a check that has not run yet.
    """
    from pathlib import Path

    from ...context import create_context
    from ...errors import RlsblError
    from ...member_context import resolve_member_context
    from ...workspace import get_releasable_dir

    saved = read_state_for_resume(state_path) or {}
    version = saved.get("new_version")
    if not version:
        return None
    rel_name = saved.get("releasable_name")
    try:
        rel_dir = (
            get_releasable_dir(str(workspace_root), rel_name)
            if rel_name else None
        )
        member = resolve_member_context(
            project_dir, releasable_config_dir=rel_dir,
            primary_name=saved.get("registry"),
        )
        resolved_targets = member.resolved_targets
    except RlsblError as exc:
        log(
            f"  {name}: publication cannot be verified -- its release targets "
            f"could not be resolved ({exc})"
        )
        return None
    ctx = create_context(
        Path(project_dir), workspace_root=Path(workspace_root),
    )
    return (name, resolved_targets, version, saved.get("tag"), ctx)


def _publish_batch_candidate(workspace_root, pending, flags, log, *,
                             pin_sha=None, trail=()):
    """Guard the tip, then publish the whole batch as ONE candidate push.

    Pass 1 runs every member with ``ci-defer``, which COMMITS but never pushes,
    so by the time this runs the branch tip carries every member's release
    commits and a single push publishes all of them together.

    That single push is what makes the batch verifiable at all. The generated
    CI router filters paths against the push's own before-SHA, so a push per
    member carries a one-project diff: on the commit every tag would point at,
    all the other members' CI jobs conclude ``skipped``, and their publish
    gates refuse a skipped check (correctly -- it proves nothing about that
    commit). One push whose diff spans every participating project triggers
    every project's CI job on exactly the commit all the tags land on.

    Refuse-on-drift runs FIRST, so a ride-in is never published: the per-member
    guards only cover each member's own call, and a commit that landed between
    the last member and this push -- a concurrent session sharing the worktree,
    say -- would otherwise ship under every tag in the batch. It is a hard
    error naming the SHAs; nothing is rolled back and nothing has been pushed.

    The empty-candidate-window guard then runs ONCE PER MEMBER, not against the
    union of the members' router filter patterns. The union would pass the
    moment ONE member's paths were touched, which is precisely the
    half-skipped batch this whole two-pass design exists to prevent: the batch
    CI gate applies each member's OWN publish-gate filter, so a member the
    window misses concludes ``skipped`` and blocks the entire batch after the
    full CI wait. Per-member reuses :func:`_guard_empty_candidate_window`
    verbatim -- the same call the single-release path makes, with that member's
    own state file, monorepo name, releasable and version -- and refuses from
    the diff, before the wait.

    Returns the published SHA: the commit the CI gate verifies and every
    member's tag lands on.
    """
    from ...utils import get_current_branch
    # Late-bound through the release package namespace, exactly like the
    # per-member push site, so one mock.patch covers every push in a batch.
    from ..release import push_if_needed
    from ..release.execute import (
        _guard_empty_candidate_window, guard_foreign_commits,
    )
    from ..release.release_state import (
        load_release_state, save_release_state, save_step,
    )

    guard_foreign_commits(
        pin_sha, trail, cwd=workspace_root, phase="batch candidate push",
    )

    sha = run("git", ["rev-parse", "HEAD"], cwd=workspace_root).strip()
    branch = get_current_branch(cwd=workspace_root)
    # No single project's config owns a workspace-level push, so only the CLI
    # override applies (the same stance :func:`_batch_ci_gate` takes on the
    # CI-wait timeout).
    push_config = (
        {"push_timeout": flags["push-timeout"]}
        if flags.get("push-timeout") else None
    )

    remote_head = None
    try:
        ls_out = run(
            "git", ["ls-remote", "origin", f"refs/heads/{branch}"],
            cwd=workspace_root,
        ).strip()
        remote_head = ls_out.split()[0] if ls_out else None
    except Exception:
        pass  # Remote branch might not exist yet.
    needs_push = not (remote_head and remote_head == sha)
    for _name, _project_dir, _state_path in pending:
        _st = load_release_state(_state_path) or {}
        _guard_empty_candidate_window(
            candidate_sha=sha,
            remote_head=remote_head,
            needs_push=needs_push,
            state_path=_state_path,
            monorepo_root=workspace_root,
            monorepo_name=_st.get("monorepo_name"),
            releasable_name=_st.get("releasable_name"),
            version=_st.get("new_version"),
            tag=_st.get("tag"),
            branch=branch,
            cwd=workspace_root,
            log=log,
        )

    push_if_needed(branch, config=push_config, cwd=workspace_root, sha=sha)
    log(
        f"Pushed the batch release candidate {sha[:12]} to origin/{branch} "
        f"(untagged, {len(pending)} member(s))"
    )

    # Record the publication in every member's state: the candidate is on the
    # remote now, so a later resume must neither re-push it nor roll back past
    # it, and each member's pass-2 resume finds its own BRANCH_PUSHED marker.
    for _name, _project_dir, state_path in pending:
        state = load_release_state(state_path) or {}
        state["candidate_sha"] = sha
        save_release_state(state_path, state)
        save_step(state_path, "BRANCH_PUSHED")

    return sha


def _batch_ci_gate(workspace_root, flags, log, sha, pending):
    """Run ONE CI gate for the whole batch on the published candidate *sha*.

    The batch's commits were published by a single push
    (:func:`_publish_batch_candidate`), so one CI verdict covers every member
    and each is then tagged on exactly this commit -- a commit whose CI
    genuinely ran for every participating project.

    "Genuinely ran" is enforced, not assumed: the gate applies every
    participating project's OWN publish-gate check filter
    (:func:`rlsbl.ci_checks.workspace_check_filters`) to the candidate, so a
    member whose router job concluded ``skipped`` blocks the whole batch
    instead of being tagged for a version its publish gate will refuse.

    Returns the verified SHA. Raises :class:`ReleaseValidationError` when CI is
    red, unresolved or unreachable -- the candidate stays on the branch
    untagged, nothing is finalized, and no version number is burnt.
    """
    from ...ci_checks import ProjectCINotRunError, workspace_check_filters
    from ...utils import get_ci_timeout
    from ..watch import CI_GREEN, CI_NOT_CONFIGURED, CI_TIMEOUT, CIWaitError

    # Config is per-project in a workspace; the batch gate is a workspace-level
    # wait, so only the CLI override applies here (no single config owns it).
    timeout = get_ci_timeout(None, override=flags.get("ci-timeout"))
    try:
        check_filters = workspace_check_filters(
            workspace_root, [entry[1] for entry in pending],
        )
        verdict, results = wait_for_ci_green(
            sha, timeout=timeout, check_filters=check_filters, log=log,
            repo_root=workspace_root,
            label=f"batch candidate {sha[:12]}",
        )
    except ProjectCINotRunError as exc:
        raise ReleaseValidationError(
            f"CI never ran for at least one member of this batch on the "
            f"release candidate {sha}.\n"
            f"  {exc}\n"
            f"\n"
            f"This is NOT a CI failure: the workflow run went green, but that "
            f"member's own job inside it never ran, so nothing was proven "
            f"about the candidate for it.\n"
            f"Nothing in this batch was tagged, released or finalized -- no "
            f"version number was burnt. The publish gate applies the SAME "
            f"filter, so tagging here would create tags for versions that can "
            f"never publish.\n"
            f"\n"
            f"Make the candidate contain a commit each listed project's CI "
            f"actually runs on -- commit a change under its paths on the "
            f"release branch (its `watch` patterns feed the `filters:` block "
            f"of .github/workflows/ci-router.yml) -- then re-run `rlsbl "
            f"monorepo release run`: each member resumes at its own unchanged "
            f"version."
        ) from exc
    except CIWaitError as exc:
        raise ReleaseValidationError(str(exc)) from exc

    if verdict == CI_NOT_CONFIGURED:
        # Unconditional and on stderr: this notice is the operator's only
        # signal that the batch shipped with NO CI gate, and --quiet must not
        # be able to swallow it.
        print(
            "rlsbl: no push-triggered CI workflow is configured in "
            ".github/workflows; proceeding without a CI gate.",
            file=sys.stderr,
        )
        return sha
    if verdict == CI_TIMEOUT:
        unresolved = ", ".join(
            r["name"] for r in results if r.get("timed_out")
        ) or "unknown"
        raise ReleaseValidationError(
            f"The CI wait for the batch release candidate {sha} ran out of "
            f"time before every run concluded.\n"
            f"  Unresolved workflow(s) after {timeout}s: {unresolved}\n"
            f"\n"
            f"This is NOT a CI failure: those runs may still be in progress, "
            f"and nothing was proven about the candidate either way.\n"
            f"Nothing in this batch was tagged, released or finalized -- no "
            f"version number was burnt.\n"
            f"\n"
            f"Check the runs with `rlsbl watch {sha[:12]}`. When they are "
            f"green, re-run `rlsbl monorepo release run`: each member resumes "
            f"at its own unchanged version. If CI is merely slow, raise the "
            f"budget with `--ci-timeout`."
        )
    if verdict != CI_GREEN:
        red = ", ".join(
            r["name"] for r in results
            if not r["passed"] and not r.get("timed_out")
        ) or "unknown"
        raise ReleaseValidationError(
            f"CI did not pass on the batch release candidate {sha}.\n"
            f"  Failing workflow(s): {red}\n"
            f"\n"
            f"Nothing in this batch was tagged, released or finalized -- no "
            f"version number was burnt. Every member's version-bump commit is "
            f"on the release branch, which is the design: the branch carries "
            f"the candidate until CI proves it green.\n"
            f"Fix forward on the release branch, then re-run "
            f"`rlsbl monorepo release run`: each member resumes at its own "
            f"unchanged version."
        )
    log(f"CI is green on the batch candidate {sha[:12]}")
    return sha


def _resume_batch_item(name, project_dir, workspace_root, state_path, flags,
                       verified_sha, log):
    """Second batch pass: finish one member on the verified candidate."""
    from pathlib import Path

    from ...context import create_context
    from ..release import resume_cmd

    saved = read_state_for_resume(state_path)
    if saved is None:
        raise ReleaseValidationError(
            f"release state for {name!r} vanished between the candidate push "
            f"and the CI gate ({state_path}). Investigate before retrying."
        )
    pkg_ctx = create_context(Path(project_dir), workspace_root=Path(workspace_root))
    resume_cmd(
        saved,
        _batch_release_flags(flags, **{"ci-verified-sha": verified_sha}),
        ctx=pkg_ctx,
    )


def read_state_for_resume(state_path):
    from ..release.release_state import load_release_state

    return load_release_state(state_path)


def _releasable_release_order(batch_names, releasables, projects, graph):
    """Compute release order for releasables based on member topological positions.

    A releasable's position is the maximum topological position of its member
    packages. This ensures that a releasable whose members depend on members
    of another releasable is released after the dependency.

    Returns an ordered list of releasable names from the batch.
    """
    from ...workspace import members_of

    full_order = graph.topological_order()
    position = {name: i for i, name in enumerate(full_order)}

    releasable_positions = {}
    for rel in releasables:
        if rel.name not in batch_names:
            continue
        members = members_of(rel.name, projects)
        if members:
            max_pos = max(position.get(m["name"], 0) for m in members)
        else:
            max_pos = 0
        releasable_positions[rel.name] = max_pos

    return sorted(batch_names, key=lambda n: releasable_positions.get(n, 0))


def _cmd_batch_release(flags, project_root):
    """Execute a batch release of multiple monorepo packages or releasables."""
    start = str(project_root)
    workspace_root = find_workspace_root(start)
    if workspace_root is None:
        print(
            "Error: No workspace found. Run 'rlsbl monorepo init' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    batch_path = get_batch_release_file_path(workspace_root)
    if not os.path.exists(batch_path):
        print(
            "Error: No batch release file found at "
            f"{os.path.relpath(batch_path)}.\n"
            "Create .rlsbl-monorepo/releases/unreleased.toml with "
            "[packages.<name>] or [releasables.<name>] sections.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        batch_config = read_batch_release_file(batch_path)
    except ReleaseFileError as e:
        print(f"Error in batch release file: {e}", file=sys.stderr)
        sys.exit(1)

    quiet = flags.get("quiet", False)
    dry_run = flags.get("dry-run", False)

    def log(msg):
        if not quiet:
            print(msg)

    # The workspace root's own env file, loaded before anything runs. The
    # orchestrator does root-level work of its own (root selfdoc, the batch
    # candidate push, the CI gate) that no member's release_env covers, and a
    # configured-but-missing file must stop the batch here rather than
    # halfway through a member's release.
    from ..release.shared import load_release_env
    from ...config import read_project_config
    try:
        load_release_env(read_project_config(workspace_root))
    except ConfigError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    projects = load_workspace(workspace_root)
    explicit = is_explicit_mode(workspace_root)

    if batch_config.section_type == "releasables" and not explicit:
        print(
            "Error: batch release file uses [releasables] sections but the "
            "workspace is in implicit mode (no [[releasables]] in workspace.toml).",
            file=sys.stderr,
        )
        sys.exit(1)

    # --- Repair pass / resolved-plan handling ---
    # If a plan sidecar already exists, this is not a fresh batch: validate it
    # against the current batch file (never regenerate) and, if every item is
    # provably released, stop -- there is nothing left for this run to do.
    plan_path = get_batch_plan_path(workspace_root)
    plan = None
    try:
        plan = read_batch_plan(plan_path)
    except FileNotFoundError:
        plan = None
    if plan is not None:
        try:
            validate_plan_against_config(plan, batch_config)
        except BatchPlanError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)

        if not dry_run and plan_all_released(workspace_root, plan, projects):
            with rlsbl_lock(".rlsbl-monorepo", project_root=workspace_root):
                _abort_on_completed_plan(
                    plan, plan_path, batch_path, workspace_root, projects,
                )

    # Upfront validation: fail before releasing anything
    try:
        validate_gh_cli()
        validate_gh_push_access()
        validate_clean_tree(flags)
        # Resolved ONCE, here, before anything the batch does is recorded or
        # performed. The branch is fixed for the whole run, and each member's
        # release would otherwise re-read it -- which under a preview happens
        # after the previous member's effects were recorded, where the
        # framework answers observes with a stale carrier.
        flags = dict(flags)
        flags["release-branch"] = str(
            validate_branch_and_remote(flags, cwd=workspace_root)
        )
    except ReleaseValidationError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Root-level selfdoc: run once before per-member releases so generated
    # files are committed and the tree is clean for per-member validation.
    try:
        _run_root_selfdoc(flags, workspace_root, log)
    except HookError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # The plan (possibly None here) is passed to the mode functions. When it is
    # None and this is not a dry-run, the mode function resolves and persists a
    # fresh plan AFTER validating item membership (so version/tag computation
    # only runs for items that actually exist in the workspace).
    if batch_config.section_type == "releasables":
        _batch_release_releasables(
            flags, workspace_root, batch_path, batch_config, projects,
            plan, plan_path,
        )
    else:
        _batch_release_packages(
            flags, workspace_root, batch_path, batch_config, projects,
            plan, plan_path,
        )


def _resolve_fresh_plan(workspace_root, batch_config, projects, plan_path, log):
    """Compute, persist, and commit a fresh resolved plan.

    Called by the mode functions after item membership has been validated.
    A plan-less batch whose target tags already exist predates resolved-plan
    tracking -- that is a hard error (no guessing about partial legacy runs).
    Returns the BatchPlan.
    """
    try:
        plan = compute_batch_plan(workspace_root, batch_config, projects)
    except ReleaseValidationError as e:
        if "already exists" in str(e):
            _abort_legacy_plan_less_batch(
                get_batch_release_file_path(workspace_root), plan_path, str(e)
            )
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    write_batch_plan(plan_path, plan)
    commit_files(
        "chore: resolve batch release plan",
        [os.path.normpath(plan_path)],
        autogenerated=True,
        allow_failure=True,
    )
    log("Resolved batch release plan (base/target versions, tags).")
    return plan


def _abort_legacy_plan_less_batch(batch_path, plan_path, detail):
    """Hard error for a plan-less batch file that was already (partly) released.

    A batch ``unreleased.toml`` with no plan sidecar whose target tags already
    exist predates resolved-plan tracking: it was partially executed by an
    older rlsbl that never persisted base versions, so there is no safe way to
    decide which items still need releasing. Refuse to guess.
    """
    print(
        "Error: found a batch release file that predates resolved-plan "
        "tracking and appears to have been partially released.\n"
        f"  Batch file: {os.path.relpath(batch_path)}\n"
        f"  Missing plan sidecar: {os.path.relpath(plan_path)}\n"
        f"  Detail: {detail}\n"
        "Without a resolved plan, rlsbl cannot tell which items are already "
        "released. Resolve manually:\n"
        "  1. For each item in the batch file, verify whether its release "
        "already completed (check `git tag` and the published version).\n"
        "  2. If the batch is fully released, archive the batch file manually "
        "(move it out of .rlsbl-monorepo/releases/).\n"
        "  3. Otherwise, delete the batch file and re-run "
        "`rlsbl monorepo release init` to start a fresh, plan-tracked batch.",
        file=sys.stderr,
    )
    sys.exit(1)


def _batch_release_releasables(flags, workspace_root, batch_path, batch_config,
                               projects, plan=None, plan_path=None):
    """Execute batch release in releasable mode."""
    from ...workspace import load_releasables, members_of

    releasables = load_releasables(workspace_root, projects)
    releasable_by_name = {r.name: r for r in releasables}

    # Validate all releasable names exist
    missing = set(batch_config.packages.keys()) - set(releasable_by_name.keys())
    if missing:
        print(
            f"Error: releasables not found in workspace: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Build graph and compute release order
    graph = WorkspaceGraph(workspace_root, projects)
    try:
        graph.topological_order()
    except CycleError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    batch_names = set(batch_config.packages.keys())
    release_order = _releasable_release_order(
        batch_names, releasables, projects, graph,
    )

    dry_run = flags.get("dry-run", False)
    quiet = flags.get("quiet", False)

    def log(msg):
        if not quiet:
            print(msg)

    # Resolve a fresh plan now that membership is validated (skip in dry-run).
    if plan is None and not dry_run and plan_path is not None:
        plan = _resolve_fresh_plan(
            workspace_root, batch_config, projects, plan_path, log,
        )

    log(f"Batch release: {len(release_order)} releasable(s)")
    log(f"Release order: {', '.join(release_order)}")

    if dry_run:
        for i, name in enumerate(release_order, 1):
            rc = batch_config.packages[name]
            log(f"  {i}. {name} ({rc.bump}) — {rc.description}")

    log("")

    released = []
    last_sha = None
    # Per-member probe specs for the watch tail's registry check, captured
    # before each member's state file is cleared by its pass-2 completion.
    probe_specs = []
    with rlsbl_lock(".rlsbl-monorepo", project_root=workspace_root):
        # Workspace-level pin, taken before the first candidate is built. Every
        # commit that appears in pin..HEAD must be one a member's own release
        # call created; anything else is a ride-in and aborts the gate.
        batch_pin = None if dry_run else head_sha(cwd=workspace_root)
        inline_commits = []
        # Pass 1: COMMIT every member's release locally (``ci-defer``). The
        # push and the CI gate are deferred so ONE push publishes the whole
        # batch and ONE wait covers it. Members an earlier invocation left
        # mid-flight are seeded straight into pass 2: their commits are
        # already on the branch, and this run's single push + gate covers
        # them exactly as it covers the members it commits itself.
        stranded = _seed_stranded_pending(
            plan, workspace_root, projects, dry_run, "releasable",
        )
        pending = []
        for rel_name in release_order:
            release_config = batch_config.packages[rel_name]
            member_projs = members_of(rel_name, projects)
            if not member_projs:
                print(f"Error: releasable '{rel_name}' has no member projects.", file=sys.stderr)
                sys.exit(1)

            # Per-item idempotency: skip a releasable that is already released
            # per the resolved plan (live version == target and tag exists).
            if plan is not None and not dry_run:
                plan_item = plan.items[rel_name]
                if item_is_released(workspace_root, plan_item, projects, "releasables"):
                    log(
                        f"--- Skipping releasable {rel_name}: already released "
                        f"at {plan_item.target_version} (tag {plan_item.tag}) ---"
                    )
                    log("")
                    continue

            # Pick the first member as the representative for the release flow
            representative = member_projs[0]
            project_dir = os.path.join(workspace_root, representative["path"])

            if rel_name in stranded:
                log(
                    f"--- Resuming releasable {rel_name}: an earlier run left "
                    f"it mid-flight; it joins this batch's candidate ---"
                )
                pending.append((rel_name, project_dir, stranded[rel_name]))
                log("")
                continue

            log(f"--- Releasing releasable {rel_name} ({release_config.bump}) ---")

            try:
                from pathlib import Path

                from ...context import create_context
                from ..release import run_cmd

                release_flags = _batch_release_flags(
                    # ``ci-defer`` in EVERY mode: pass 1 is commit-only,
                    # and a preview of pass 1 must be a preview of the
                    # same thing. Without it a previewed member ran its
                    # own candidate push, which the real pass 1 never
                    # does -- the batch publishes one candidate for the
                    # whole group. The batch preview is therefore the
                    # members' Phase-A plans, concatenated, and nothing
                    # else.
                    flags, **{"ci-defer": True},
                )
                pkg_ctx = create_context(Path(project_dir), workspace_root=Path(workspace_root))
                _before = None if dry_run else head_sha(cwd=workspace_root)
                run_cmd(release_config, release_flags, ctx=pkg_ctx)
                if dry_run:
                    released.append(rel_name)
                else:
                    from ...workspace_types import get_releasable_dir as _grd
                    from ..release.release_state import get_state_path as _gsp
                    _sp = _gsp(
                        workspace_root,
                        releasable_dir=_grd(workspace_root, rel_name),
                    )
                    if os.path.exists(_sp):
                        pending.append((rel_name, project_dir, _sp))
                    else:
                        # No in-progress state means nothing is in progress:
                        # the member's release ran to completion inside its own
                        # call (every step already satisfied), so there is
                        # nothing for the batch gate to finish. The archive
                        # gate below is the correctness backstop.
                        released.append(rel_name)
                        last_sha = run("git", ["rev-parse", "HEAD"])
                        # Its trail died with its state file; the commits that
                        # appeared across its call are the batch's own.
                        inline_commits.extend(
                            _commits_between(_before, last_sha.strip(),
                                             workspace_root)
                        )
            except SystemExit as e:
                if e.code not in (0, None):
                    print(
                        f"\nError: release of releasable {rel_name} failed. "
                        f"Successfully released: {', '.join(released) if released else '(none)'}",
                        file=sys.stderr,
                    )
                    raise
                from ...workspace_types import get_releasable_dir as _grd0
                from ..release.release_state import get_state_path as _gsp0
                _absorb_member_exit_zero(
                    rel_name, project_dir,
                    _gsp0(workspace_root,
                          releasable_dir=_grd0(workspace_root, rel_name)),
                    pending, dry_run=dry_run, kind="releasable",
                )

            log("")

        # ONE push for the whole batch, ONE CI gate on it, then pass 2:
        # finalize, tag and release each member on the verified candidate.
        if pending:
            try:
                candidate_sha = _publish_batch_candidate(
                    workspace_root, pending, flags, log,
                    pin_sha=batch_pin,
                    trail=_batch_release_trail(pending, inline_commits),
                )
                verified_sha = _batch_ci_gate(
                    workspace_root, flags, log, candidate_sha, pending,
                )
            except ForeignCommitError as e:
                # A ride-in on the batch tip. Never rolled back: those commits
                # are exactly what must be preserved. The batch's own commits
                # are local and unpushed, and no version is burnt.
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            except GitError as e:
                # The candidate push failed. Every member's release commits sit
                # on the local branch, nothing is tagged, and re-running the
                # batch republishes and re-gates the same commits.
                print(
                    f"Error: the batch release candidate could not be pushed: "
                    f"{e}\nNothing was tagged, released or finalized. Re-run "
                    f"`rlsbl monorepo release run` once pushing works again.",
                    file=sys.stderr,
                )
                sys.exit(1)
            except ReleaseCIError as e:
                # The candidate's diff window cannot trigger some member's CI
                # job (or CI did not go green on it). Nothing was tagged,
                # released or finalized and no version is burnt: each member's
                # state carries a CI_VERIFIED failure marker and the batch
                # resumes once the window is widened.
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            except ReleaseValidationError as e:
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            for rel_name, project_dir, state_path in pending:
                log(f"--- Completing releasable {rel_name} ---")
                # Read before the resume: a member that completes clears its
                # state file, and the watch tail's registry probe needs that
                # member's version and resolved targets.
                _spec = _member_probe_spec(
                    rel_name, project_dir, workspace_root, state_path, log,
                )
                try:
                    _resume_batch_item(
                        rel_name, project_dir, workspace_root, state_path,
                        flags, verified_sha, log,
                    )
                except ReleaseValidationError as e:
                    print(f"Error: {e}", file=sys.stderr)
                    sys.exit(1)
                except SystemExit as e:
                    if e.code != 0:
                        print(
                            f"\nError: release of releasable {rel_name} failed. "
                            f"Successfully released: {', '.join(released) if released else '(none)'}",
                            file=sys.stderr,
                        )
                        raise
                released.append(rel_name)
                if _spec is not None:
                    probe_specs.append(_spec)
                log("")
            last_sha = verified_sha

        # Archive is state-driven: only fires when every plan item is released.
        if not dry_run:
            _archive_batch_if_complete(
                batch_path, plan, workspace_root, projects, log,
                flags=flags,
            )

    # Log completion BEFORE the watch tail: the tail exits the process on a
    # red CI or a missing artifact, and would skip the announcement.
    _announce_batch_completion(released, log, kind="releasable")

    if not dry_run and last_sha:
        _watch_and_verify_batch(flags, last_sha, probe_specs, log)


def _batch_release_packages(flags, workspace_root, batch_path, batch_config,
                            projects, plan=None, plan_path=None):
    """Execute batch release in package mode (implicit, original behavior)."""
    project_names = {p["name"] for p in projects}
    project_by_name = {p["name"]: p for p in projects}

    # Validate all packages exist in workspace
    missing = set(batch_config.packages.keys()) - project_names
    if missing:
        print(
            f"Error: packages not found in workspace: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Reject non-releasable projects
    non_releasable_in_batch = sorted(
        name
        for name in batch_config.packages
        if not project_by_name[name].is_releasable
    )
    if non_releasable_in_batch:
        print(
            "Error: non-releasable projects cannot be in batch release: "
            f"{', '.join(non_releasable_in_batch)}. "
            "Set releasable = \"<name>\" in workspace.toml if these projects "
            "should be releasable.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Determine topological order for the listed packages
    graph = WorkspaceGraph(workspace_root, projects)
    try:
        full_order = graph.topological_order()
    except CycleError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    # Filter to only the packages in the batch, preserving topological order
    batch_names = set(batch_config.packages.keys())
    release_order = [name for name in full_order if name in batch_names]

    dry_run = flags.get("dry-run", False)
    quiet = flags.get("quiet", False)

    def log(msg):
        if not quiet:
            print(msg)

    # Resolve a fresh plan now that membership is validated (skip in dry-run).
    if plan is None and not dry_run and plan_path is not None:
        plan = _resolve_fresh_plan(
            workspace_root, batch_config, projects, plan_path, log,
        )

    log(f"Batch release: {len(release_order)} package(s)")
    log(f"Release order: {', '.join(release_order)}")

    if dry_run:
        for i, name in enumerate(release_order, 1):
            rc = batch_config.packages[name]
            log(f"  {i}. {name} ({rc.bump}) — {rc.description}")

    log("")

    # Release each package in order
    released = []
    last_sha = None
    # Per-member probe specs for the watch tail's registry check, captured
    # before each package's state file is cleared by its pass-2 completion.
    probe_specs = []
    with rlsbl_lock(".rlsbl-monorepo", project_root=workspace_root):
        # Workspace-level pin, taken before the first candidate is built. Every
        # commit that appears in pin..HEAD must be one a member's own release
        # call created; anything else is a ride-in and aborts the gate.
        batch_pin = None if dry_run else head_sha(cwd=workspace_root)
        inline_commits = []
        # Pass 1: COMMIT every package's release locally (``ci-defer``). The
        # push and the CI gate are deferred so ONE push publishes the whole
        # batch and ONE wait covers it. Members an earlier invocation left
        # mid-flight are seeded straight into pass 2: their commits are
        # already on the branch, and this run's single push + gate covers
        # them exactly as it covers the members it commits itself.
        stranded = _seed_stranded_pending(
            plan, workspace_root, projects, dry_run, "package",
        )
        pending = []
        for pkg_name in release_order:
            release_config = batch_config.packages[pkg_name]
            project = project_by_name[pkg_name]
            project_dir = os.path.join(workspace_root, project["path"])

            # Per-item idempotency: skip a package already released per the
            # resolved plan (live version == target and tag exists).
            if plan is not None and not dry_run:
                plan_item = plan.items[pkg_name]
                if item_is_released(workspace_root, plan_item, projects, "packages"):
                    log(
                        f"--- Skipping {pkg_name}: already released at "
                        f"{plan_item.target_version} (tag {plan_item.tag}) ---"
                    )
                    log("")
                    continue

            if pkg_name in stranded:
                log(
                    f"--- Resuming {pkg_name}: an earlier run left it "
                    f"mid-flight; it joins this batch's candidate ---"
                )
                pending.append((pkg_name, project_dir, stranded[pkg_name]))
                log("")
                continue

            log(f"--- Releasing {pkg_name} ({release_config.bump}) ---")

            try:
                from pathlib import Path

                from ...context import create_context
                from ..release import run_cmd

                release_flags = _batch_release_flags(
                    # ``ci-defer`` in EVERY mode: pass 1 is commit-only,
                    # and a preview of pass 1 must be a preview of the
                    # same thing. Without it a previewed member ran its
                    # own candidate push, which the real pass 1 never
                    # does -- the batch publishes one candidate for the
                    # whole group. The batch preview is therefore the
                    # members' Phase-A plans, concatenated, and nothing
                    # else.
                    flags, **{"ci-defer": True},
                )
                pkg_ctx = create_context(Path(project_dir), workspace_root=Path(workspace_root))
                _before = None if dry_run else head_sha(cwd=workspace_root)
                run_cmd(release_config, release_flags, ctx=pkg_ctx)
                if dry_run:
                    released.append(pkg_name)
                else:
                    from ..release.release_state import get_state_path as _gsp
                    _sp = _gsp(project_dir)
                    if os.path.exists(_sp):
                        pending.append((pkg_name, project_dir, _sp))
                    else:
                        # No in-progress state means nothing is in progress:
                        # the package's release ran to completion inside its
                        # own call. The archive gate below is the backstop.
                        released.append(pkg_name)
                        last_sha = run("git", ["rev-parse", "HEAD"])
                        # Its trail died with its state file; the commits that
                        # appeared across its call are the batch's own.
                        inline_commits.extend(
                            _commits_between(_before, last_sha.strip(),
                                             workspace_root)
                        )
            except SystemExit as e:
                if e.code not in (0, None):
                    print(
                        f"\nError: release of {pkg_name} failed. "
                        f"Successfully released: {', '.join(released) if released else '(none)'}",
                        file=sys.stderr,
                    )
                    raise
                from ..release.release_state import get_state_path as _gsp0
                _absorb_member_exit_zero(
                    pkg_name, project_dir, _gsp0(project_dir), pending,
                    dry_run=dry_run, kind="package",
                )

            log("")

        # ONE push for the whole batch, ONE CI gate on it, then pass 2:
        # finalize, tag and release each package on the verified candidate.
        if pending:
            try:
                candidate_sha = _publish_batch_candidate(
                    workspace_root, pending, flags, log,
                    pin_sha=batch_pin,
                    trail=_batch_release_trail(pending, inline_commits),
                )
                verified_sha = _batch_ci_gate(
                    workspace_root, flags, log, candidate_sha, pending,
                )
            except ForeignCommitError as e:
                # A ride-in on the batch tip. Never rolled back: those commits
                # are exactly what must be preserved. The batch's own commits
                # are local and unpushed, and no version is burnt.
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            except GitError as e:
                # The candidate push failed. Every member's release commits sit
                # on the local branch, nothing is tagged, and re-running the
                # batch republishes and re-gates the same commits.
                print(
                    f"Error: the batch release candidate could not be pushed: "
                    f"{e}\nNothing was tagged, released or finalized. Re-run "
                    f"`rlsbl monorepo release run` once pushing works again.",
                    file=sys.stderr,
                )
                sys.exit(1)
            except ReleaseCIError as e:
                # The candidate's diff window cannot trigger some member's CI
                # job (or CI did not go green on it). Nothing was tagged,
                # released or finalized and no version is burnt: each member's
                # state carries a CI_VERIFIED failure marker and the batch
                # resumes once the window is widened.
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            except ReleaseValidationError as e:
                print(f"Error: {e}", file=sys.stderr)
                sys.exit(1)
            for pkg_name, project_dir, state_path in pending:
                log(f"--- Completing {pkg_name} ---")
                # Read before the resume: a member that completes clears its
                # state file, and the watch tail's registry probe needs that
                # member's version and resolved targets.
                _spec = _member_probe_spec(
                    pkg_name, project_dir, workspace_root, state_path, log,
                )
                try:
                    _resume_batch_item(
                        pkg_name, project_dir, workspace_root, state_path,
                        flags, verified_sha, log,
                    )
                except ReleaseValidationError as e:
                    print(f"Error: {e}", file=sys.stderr)
                    sys.exit(1)
                except SystemExit as e:
                    if e.code != 0:
                        print(
                            f"\nError: release of {pkg_name} failed. "
                            f"Successfully released: {', '.join(released) if released else '(none)'}",
                            file=sys.stderr,
                        )
                        raise
                released.append(pkg_name)
                if _spec is not None:
                    probe_specs.append(_spec)
                log("")
            last_sha = verified_sha

        # Archive is state-driven: only fires when every plan item is released.
        if not dry_run:
            _archive_batch_if_complete(
                batch_path, plan, workspace_root, projects, log,
                flags=flags,
            )

    # Log completion BEFORE the watch tail: the tail exits the process on a
    # red CI or a missing artifact, and would skip the announcement.
    _announce_batch_completion(released, log, kind="package")

    if not dry_run and last_sha:
        _watch_and_verify_batch(flags, last_sha, probe_specs, log)


def _abort_on_completed_plan(plan, plan_path, batch_path, workspace_root,
                             projects):
    """Every item in the resolved plan is already released: stop, nonzero.

    This path used to archive the batch file AND the plan and return 0. Two
    things were wrong with that. It reported success for a run that released
    nothing. And because a plan is matched against a batch file by item set
    and bump intent only (base versions legitimately drift mid-resume, so
    they are deliberately not compared), a FRESH ``unreleased.toml`` written
    for the next batch validates against the stale plan -- and got renamed
    into the archive without a single release happening.

    So the batch file is never touched here; it belongs to the operator. Only
    the plan sidecar is archived, which is exactly what unblocks the next
    run: with the stale plan gone, a re-run resolves a fresh plan against the
    surviving batch file.

    Never returns.
    """
    plan_rel = os.path.relpath(plan_path)
    batch_rel = os.path.relpath(batch_path)

    stranded = _plan_items_in_progress(plan, workspace_root, projects)
    if stranded:
        # The plan is not stale -- those items still need it. Archiving it
        # here would strand a resumable release with no way to finish it.
        print(
            f"\nError: every item in {plan_rel} is already released, but "
            f"in-progress release state remains for: {', '.join(stranded)}.\n"
            f"Finish each one with `rlsbl release resume` (or roll it back "
            f"with `rlsbl release undo`), then re-run "
            f"`rlsbl monorepo release run`.",
            file=sys.stderr,
        )
        sys.exit(1)

    versioned_stem = f"batch-{time.strftime('%Y%m%d-%H%M%S')}"
    archived = archive_plan_file(plan_path, versioned_stem)
    if archived:
        commit_files(
            f"chore: archive completed batch plan ({versioned_stem}.plan.json)",
            archived,
            autogenerated=True,
            allow_failure=True,
            cwd=workspace_root,
            expected_root=workspace_root,
        )
    print(
        f"\nError: {plan_rel} is a completed plan -- every item it names is "
        f"already released, so this run had nothing to do.\n"
        f"The stale plan has been archived as {versioned_stem}.plan.json; "
        f"{batch_rel} was left untouched.\n"
        f"If {batch_rel} describes the next batch, re-run "
        f"`rlsbl monorepo release run` and a fresh plan will be resolved "
        f"against it. If it is leftover from the finished batch, delete it.",
        file=sys.stderr,
    )
    sys.exit(1)


def _absorb_member_exit_zero(name, project_dir, state_path, pending, *,
                             dry_run, kind):
    """Interpret a ``SystemExit(0)`` escaping a member's release call.

    A zero exit unwinds past the batch's own bookkeeping, so neither
    ``released`` nor ``pending`` learns about the member. The only reading
    under which that is safe is an in-progress state file: the member's
    release really is mid-flight and pass 2 finishes it on the verified
    candidate. With no state file the batch has NO evidence about what the
    member did -- it may have released, may have done nothing -- and
    continuing would either strand it or announce a completion nobody can
    substantiate. That is a hard error.
    """
    if not dry_run and os.path.exists(state_path):
        pending.append((name, project_dir, state_path))
        return
    print(
        f"\nError: the release of {kind} {name} exited 0 without leaving "
        f"in-progress release state, so the batch has no evidence of what it "
        f"did.\nInspect {name} (`rlsbl status` in {project_dir}) and re-run "
        f"`rlsbl monorepo release run` once its state is clear.",
        file=sys.stderr,
    )
    sys.exit(1)


def _announce_batch_completion(released, log, *, kind):
    """Print the completion line, or refuse when nothing was released.

    An empty ``released`` list means the run produced no release at all --
    every item was skipped as already-released, or a member vanished without
    accounting for itself. Announcing "Batch release complete" there is the
    same silent-success lie the exit-code family exists to kill.
    """
    if not released:
        print(
            f"\nError: the batch released nothing -- every {kind} was skipped "
            f"or unaccounted for.\nIf they are all already released, the batch "
            f"file and its plan are stale: archive them (or delete the plan "
            f"sidecar and re-run) instead of re-running an empty batch.",
            file=sys.stderr,
        )
        sys.exit(1)
    log(f"Batch release complete: {', '.join(released)}")


def _plan_item_state_paths(plan, workspace_root, projects):
    """Yield ``(name, state_path)`` for every resolvable plan item.

    One place decides where a plan item's release state lives, so the archive
    gate, the completed-plan abort and the pass-1 resume seeding all address
    the same file.
    """
    from ..release.release_state import get_state_path
    from ...workspace_types import get_releasable_dir

    project_by_name = {p["name"]: p for p in projects}
    for name in plan.items:
        if plan.section_type == "releasables":
            rel_dir = get_releasable_dir(workspace_root, name)
            yield name, get_state_path(workspace_root, releasable_dir=rel_dir)
        else:
            project = project_by_name.get(name)
            if project is None:
                continue
            project_dir = os.path.join(workspace_root, project["path"])
            yield name, get_state_path(project_dir)


def _plan_items_in_progress(plan, workspace_root, projects):
    """Return the names of plan items with an on-disk in-progress.json.

    A per-item release state file means that item's release did not run to
    completion (it crashed mid-flight or is mid-resume). A successful release
    clears its state file, so a lingering one is evidence of an unfinished
    release that the batch archive must not strand.
    """
    return [
        name
        for name, state_path in _plan_item_state_paths(
            plan, workspace_root, projects,
        )
        if os.path.exists(state_path)
    ]


def _partition_stranded_items(plan, workspace_root, projects):
    """Split the plan's in-progress items into batch-resumable and CI-sealed.

    Returns ``(resumable, sealed)``: a name -> state_path mapping of items this
    batch can finish itself, and a list of names it must refuse.

    The split is the CI gate, for the same reason a single release's resume
    splits there. Before ``CI_VERIFIED`` a member is just committed work on the
    branch: folding it into the batch candidate is exactly right -- one push
    publishes it with everyone else and one CI verdict covers them all. After
    ``CI_VERIFIED`` the release is SEALED to the commit CI judged; the tag and
    the CI-SHA marker address that commit, so re-gating it on a new batch
    candidate would move the ground under a verdict that already exists.
    """
    from ..release.release_state import load_release_state

    resumable = {}
    sealed = []
    for name, state_path in _plan_item_state_paths(plan, workspace_root, projects):
        if not os.path.exists(state_path):
            continue
        state = load_release_state(state_path) or {}
        if "CI_VERIFIED" in set(state.get("completed_steps") or []):
            sealed.append(name)
        else:
            resumable[name] = state_path
    return resumable, sealed


def _abort_on_sealed_items(sealed, kind):
    """Refuse a batch that would have to re-gate a CI-verified member."""
    print(
        f"\nError: {', '.join(sealed)} {'is' if len(sealed) == 1 else 'are'} "
        f"mid-release past the CI gate: the candidate {kind} "
        f"{'was' if len(sealed) == 1 else 'were'} already verified and "
        f"{'is' if len(sealed) == 1 else 'are'} sealed to that commit.\n"
        f"This batch would publish a NEW candidate and gate that instead, "
        f"moving the commit the tag and the publish gate address.\n"
        f"Finish each one where it stands with `rlsbl release resume` (or roll "
        f"it back with `rlsbl release undo`), then re-run "
        f"`rlsbl monorepo release run`.",
        file=sys.stderr,
    )
    sys.exit(1)


def _seed_stranded_pending(plan, workspace_root, projects, dry_run, kind):
    """Resolve which plan items pass 1 must SKIP and hand straight to pass 2.

    A batch that died between its pass-1 commits and its pass-2 completion
    leaves every member holding an in-progress.json. Handing such a member
    back to ``release run`` is a guaranteed refusal -- that command's whole
    contract is that an in-progress release must be resumed, not restarted --
    so the batch used to die on the state it had created itself, with no way
    to finish the group as a group.

    Returns a name -> state_path mapping. Never returns for a sealed member.
    """
    if plan is None or dry_run:
        return {}
    resumable, sealed = _partition_stranded_items(plan, workspace_root, projects)
    if sealed:
        _abort_on_sealed_items(sealed, kind)
    return resumable


def _archive_batch_if_complete(batch_path, plan, workspace_root, projects, log,
                               *, flags=None):
    """State-driven archive gate: finalize iff every plan item is released.

    This is the idempotent guard around :func:`_finalize_batch_file`, and it
    runs at the batch-loop tail only: the batch file is consumed by the run
    that actually completes the batch, never by a later run that finds an
    already-complete plan (see :func:`_abort_on_completed_plan` -- that path
    must not consume an operator's fresh batch file). When no plan exists
    (dry-run never reaches here), it is a no-op.

    Beyond the released-per-plan check, it refuses to archive when ANY plan
    item still has an in-progress.json on disk -- an unfinished/resumable
    release must never be silently archived away.

    The finalize commit is then PUBLISHED (:func:`_push_finalized_batch_file`).
    Owning the push here rather than inside the file helper keeps the helper a
    pure rename-and-commit, and makes the push a visible step of the flow that
    owns batch completion -- so a failure is reported as an unresolved step
    with a remedy instead of as a failure of a release that already shipped.
    """
    if plan is None:
        return False
    if not plan_all_released(workspace_root, plan, projects):
        log(
            "Not archiving batch file: some plan items are not yet released."
        )
        return False
    stranded = _plan_items_in_progress(plan, workspace_root, projects)
    if stranded:
        log(
            "Not archiving batch file: in-progress release state exists for "
            f"{', '.join(stranded)}. Resume or roll back those releases first."
        )
        return False
    pin_sha = head_sha(cwd=workspace_root)
    _finalize_batch_file(batch_path, log)
    try:
        _push_finalized_batch_file(
            workspace_root, flags or {}, log, pin_sha=pin_sha,
        )
    except (ForeignCommitError, GitError, subprocess.CalledProcessError) as e:
        _announce_unpushed_finalize(e, workspace_root)
    return True


def _announce_unpushed_finalize(exc, workspace_root):
    """Report the finalize push as an unresolved step, with its remedy.

    Everything the batch releases is already tagged, published and on the
    remote by the time the archive gate runs, so a failure here is not a
    failed release and must not be reported as one -- re-running or resuming
    would find nothing to do. What it IS is the branch left one commit ahead
    of its remote, which the next release's preflight will meet. So it is
    stated out loud, on stderr (``--quiet`` cannot swallow it), naming the one
    command that resolves it.
    """
    from ...utils import get_current_branch

    try:
        branch = get_current_branch(cwd=workspace_root)
    except Exception:
        branch = "<branch>"
    print(
        f"\nUNRESOLVED: the batch finalize commit was not pushed.\n"
        f"{exc}\n"
        f"Every member of the batch is tagged, released and on the remote --\n"
        f"this is not a failed release and there is nothing to resume. What\n"
        f"remains is the archive commit for the batch release file, which is\n"
        f"committed locally but not published, leaving the branch one commit\n"
        f"ahead of its remote.\n"
        f"  Resolve with: git push origin {branch}\n"
        f"  (if the message above names commits this release did not create,\n"
        f"  move them off the branch or record them first)",
        file=sys.stderr,
    )


def _push_finalized_batch_file(workspace_root, flags, log, *, pin_sha):
    """Publish the batch's own finalize commit -- the batch's last push.

    Every other commit a batch creates reaches the remote: pass 1's members
    ride the single candidate push, and pass 2's per-member finalization is
    pushed by each member's own release. The archive commit is created after
    all of it, so without this step every repository that completed a batch
    stayed one commit ahead of its remote forever, and the remote's history
    was missing the document describing the release that just shipped.

    Range-pinned like every other release push: the window ``pin_sha..HEAD``
    must contain exactly the commit the finalize step created. A commit that
    is not the batch's own (a concurrent session sharing the worktree) is
    named and refused -- a release push never carries unreviewed work -- and
    an empty window (the batch file was already archived, or the commit
    failed) means there is nothing to publish.

    ``push_if_needed`` is late-bound through the release package namespace,
    exactly like the candidate push, so one mock covers every push in a batch.
    """
    from ...utils import get_current_branch
    from ..release import push_if_needed
    from ..release.execute import guard_foreign_commits

    created = _commits_between(pin_sha, head_sha(cwd=workspace_root),
                               workspace_root)
    if not created:
        return
    # rev-list is newest-first, so the window's OLDEST commit is the one the
    # finalize step created; anything above it rode in.
    guard_foreign_commits(
        pin_sha, [created[-1]], cwd=workspace_root,
        phase="batch finalize push",
    )
    finalize_sha = created[0]
    branch = get_current_branch(cwd=workspace_root)
    # No single project's config owns a workspace-level push, so only the CLI
    # override applies (the same stance the candidate push takes).
    push_config = (
        {"push_timeout": flags["push-timeout"]}
        if flags.get("push-timeout") else None
    )
    push_if_needed(
        branch, config=push_config, cwd=workspace_root, sha=finalize_sha,
    )
    log(
        f"Pushed the batch finalize commit {finalize_sha[:12]} to "
        f"origin/{branch}"
    )


def _finalize_batch_file(batch_path, log):
    """Rename the batch release file (and its plan sidecar) and lock them.

    Idempotent: a no-op when the batch file has already been archived. The plan
    sidecar, when present, is archived alongside under the same timestamped
    stem so the two always travel together.
    """
    if not os.path.exists(batch_path):
        log("Batch release file already archived; nothing to finalize.")
        return

    releases_dir = os.path.dirname(batch_path)
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    versioned_stem = f"batch-{timestamp}"
    versioned_name = f"{versioned_stem}.toml"
    versioned_path = os.path.join(releases_dir, versioned_name)

    effects.rename(batch_path, versioned_path)
    effects.chmod(versioned_path, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)  # 444

    # Commit finalized files
    finalize_files = [
        os.path.normpath(versioned_path),
        os.path.normpath(batch_path),
    ]

    # Archive the resolved-plan sidecar alongside, under the same stem.
    plan_path = os.path.join(releases_dir, PLAN_FILENAME)
    finalize_files.extend(archive_plan_file(plan_path, versioned_stem))

    commit_files(
        f"chore: finalize batch release file ({versioned_name})",
        finalize_files,
        allow_failure=True,
    )
    log(f"Finalized batch release file: {versioned_name}")
