"""Batch release init command: scaffold a batch release file for all workspace projects."""

import os
import re
import subprocess
import sys

import tomlkit

from ...release_file import get_batch_release_file_path
from ...targets import detect_targets, TARGETS
from ...workspace import find_workspace_root, load_workspace


def _get_unreleased_commit_count(proj, workspace_root):
    """Return the number of unreleased commits touching a project's files.

    Uses the project's monorepo tag glob to find the last version tag,
    then counts commits since that tag that touch files within the
    project's path or watch globs.  Returns (count, last_tag) where
    last_tag is the tag string or None if no tags exist.
    """
    from ...changelog.validate import _is_autogenerated, _is_changelog_only_commit
    from ...git_util import filter_commits_for_project

    name = proj["name"]
    path = proj["path"]

    # Determine tag glob for this project
    project_dir = os.path.join(workspace_root, path)
    target_entries = detect_targets(project_dir)
    if target_entries and target_entries[0].name in TARGETS:
        tag_glob = TARGETS[target_entries[0].name].monorepo_tag_glob(name, path=path)
    else:
        tag_glob = f"{name}@v*"

    # Find last version tag
    last_tag = None
    try:
        result = subprocess.run(
            ["git", "tag", "-l", tag_glob, "--sort=-v:refname"],
            capture_output=True, text=True, timeout=10,
            cwd=workspace_root,
        )
        if result.returncode == 0:
            first_line = result.stdout.strip().split("\n")[0].strip() if result.stdout.strip() else ""
            if first_line:
                last_tag = first_line
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass

    # Get commits in range
    range_spec = f"{last_tag}..HEAD" if last_tag else "HEAD"
    try:
        result = subprocess.run(
            ["git", "log", "--format=%H", range_spec],
            capture_output=True, text=True, timeout=30,
            cwd=workspace_root,
        )
        if result.returncode != 0:
            return (0, last_tag)
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return (0, last_tag)

    all_commits = [
        line.strip()
        for line in result.stdout.strip().splitlines()
        if line.strip()
    ]

    # Filter out autogenerated and changelog-only commits
    relevant = [
        c for c in all_commits
        if not _is_autogenerated(c) and not _is_changelog_only_commit(c)
    ]

    # Filter to commits touching this project's files
    if relevant:
        filtered = filter_commits_for_project(set(relevant), proj)
        relevant = [c for c in relevant if c in filtered]

    return (len(relevant), last_tag)


def _build_pkg_section(proj, workspace_root, target_names):
    """Build a tomlkit table for a single package section."""
    pkg_table = tomlkit.table()
    pkg_table.add(tomlkit.comment("Version bump type: patch, minor, or major"))
    pkg_table.add("bump", "")
    pkg_table.add(tomlkit.comment("Short description of this release (required)"))
    pkg_table.add("description", "")
    pkg_table.add(tomlkit.comment("Optional context explaining why these changes were made"))
    pkg_table.add("context", "")
    pkg_table.add("include", target_names)
    pkg_table.add("exclude", [])

    # Add per-target config sections for Flutter targets
    flutter_targets = [n for n in target_names if "flutter" in n]
    if flutter_targets:
        targets_table = tomlkit.table(is_super_table=True)
        for ft in flutter_targets:
            t = tomlkit.table()
            t.add("mode", "build")
            targets_table.add(ft, t)
        pkg_table.add("targets", targets_table)

    return pkg_table


def _render_commented_section(name, target_names, reason):
    """Render a package section as TOML comments.

    Returns a string of comment lines (each prefixed with '# ') that
    represent the section the user would uncomment if they want to include it.
    """
    lines = [
        f"# {name}: {reason}",
        f"# [packages.{name}]",
        "# bump = \"\"",
        "# description = \"\"",
        "# context = \"\"",
        f"# include = {tomlkit.dumps(tomlkit.item(target_names)).strip()}",
        "# exclude = []",
    ]
    return "\n".join(lines)


def _cmd_batch_release_init(project_root, packages=None):
    """Create .rlsbl-monorepo/releases/unreleased.toml with per-package sections.

    Iterates over all workspace projects (skipping dev_node projects),
    detects targets for each, and scaffolds a [packages.<name>] section
    with empty bump/description and the detected include list.

    Packages with zero unreleased commits are included as commented-out
    sections with a note explaining why.

    Args:
        project_root: Path to the project root directory.
        packages: Optional comma-separated string of package names to include.
            If provided, only these packages are scaffolded.
    """
    start = str(project_root)
    workspace_root = find_workspace_root(start)
    if workspace_root is None:
        print(
            "Error: No workspace found. Run 'rlsbl monorepo init' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    batch_path = get_batch_release_file_path(workspace_root)
    if os.path.exists(batch_path):
        content = open(batch_path).read().strip()
        if content:
            print(f"Error: {batch_path} already exists.", file=sys.stderr)
            sys.exit(1)

    projects = load_workspace(workspace_root)
    if not projects:
        print("Error: no projects in workspace.", file=sys.stderr)
        sys.exit(1)

    # Parse --packages filter
    requested_names = None
    if packages:
        requested_names = [n.strip() for n in packages.split(",") if n.strip()]
        all_names = {p["name"] for p in projects}
        unknown = [n for n in requested_names if n not in all_names]
        if unknown:
            print(
                f"Error: unknown package(s): {', '.join(unknown)}. "
                f"Available: {', '.join(sorted(all_names))}",
                file=sys.stderr,
            )
            sys.exit(1)

    doc = tomlkit.document()
    packages_table = tomlkit.table(is_super_table=True)

    any_added = False
    commented_sections = []

    for proj in projects:
        if proj.get("dev_node", False):
            print(f"Skipping dev_node project: {proj['name']}", file=sys.stderr)
            continue

        # Apply --packages filter
        if requested_names is not None and proj["name"] not in requested_names:
            continue

        project_dir = os.path.join(workspace_root, proj["path"])
        entries = detect_targets(project_dir)
        if not entries:
            print(
                f"Warning: no targets detected for {proj['name']}, skipping.",
                file=sys.stderr,
            )
            continue

        target_names = [e.name for e in entries]

        # Check for unreleased commits
        commit_count, last_tag = _get_unreleased_commit_count(proj, workspace_root)

        if commit_count == 0 and last_tag is not None:
            # Package has a tag but no unreleased commits -- comment it out
            reason = f"no unreleased commits since {last_tag}"
            commented_sections.append((proj["name"], target_names, reason))
            any_added = True
            continue

        pkg_table = _build_pkg_section(proj, workspace_root, target_names)
        packages_table.add(proj["name"], pkg_table)
        any_added = True

    if not any_added:
        print("Error: no eligible projects with detected targets.", file=sys.stderr)
        sys.exit(1)

    doc.add("packages", packages_table)

    releases_dir = os.path.dirname(batch_path)
    os.makedirs(releases_dir, exist_ok=True)

    # Write the TOML, then append commented-out sections
    toml_text = tomlkit.dumps(doc)

    if commented_sections:
        comment_blocks = []
        for name, target_names, reason in commented_sections:
            comment_blocks.append(
                _render_commented_section(name, target_names, reason)
            )
        toml_text = toml_text.rstrip("\n") + "\n\n" + "\n\n".join(comment_blocks) + "\n"

    with open(batch_path, "w", encoding="utf-8") as f:
        f.write(toml_text)

    print(batch_path)
