"""Scaffold a batch release file for all workspace projects, auto-detecting targets and commenting out packages with no unreleased commits."""

import os
import re
import subprocess
import sys

import tomlkit

from ...release_file import get_batch_release_file_path
from ...targets import detect_targets, TARGETS
from ...workspace import find_workspace_root, load_workspace


def _get_unreleased_commit_count(proj, workspace_root):
    """Return the number of unreleased commits touching a project's files.

    Uses the project's monorepo tag glob to find the last version tag,
    then counts commits since that tag that touch files within the
    project's path or watch globs.  Returns (count, last_tag) where
    last_tag is the tag string or None if no tags exist.
    """
    from ...changelog.validate import filter_exempt_commits
    from ...git_util import filter_commits_for_project

    name = proj["name"]
    path = proj["path"]

    # Determine tag glob for this project
    project_dir = os.path.join(workspace_root, path)
    target_entries = detect_targets(project_dir)
    if target_entries and target_entries[0].name in TARGETS:
        tag_glob = TARGETS[target_entries[0].name].monorepo_tag_glob(name, path=path)
    else:
        tag_glob = f"{name}@v*"

    # Find last version tag
    last_tag = None
    try:
        result = subprocess.run(
            ["git", "tag", "-l", tag_glob, "--sort=-v:refname"],
            capture_output=True, text=True, timeout=10,
            cwd=workspace_root,
        )
        if result.returncode == 0:
            first_line = result.stdout.strip().split("\n")[0].strip() if result.stdout.strip() else ""
            if first_line:
                last_tag = first_line
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass

    # Get commits in range
    range_spec = f"{last_tag}..HEAD" if last_tag else "HEAD"
    try:
        result = subprocess.run(
            ["git", "log", "--format=%H", range_spec],
            capture_output=True, text=True, timeout=30,
            cwd=workspace_root,
        )
        if result.returncode != 0:
            return (0, last_tag)
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return (0, last_tag)

    all_commits = [
        line.strip()
        for line in result.stdout.strip().splitlines()
        if line.strip()
    ]

    # Filter out autogenerated and changelog-only commits
    relevant, _stats = filter_exempt_commits(all_commits)

    # Filter to commits touching this project's files
    if relevant:
        filtered = filter_commits_for_project(set(relevant), proj)
        relevant = [c for c in relevant if c in filtered]

    return (len(relevant), last_tag)


def _build_pkg_section(proj, workspace_root, target_names):
    """Build a tomlkit table for a single package section."""
    pkg_table = tomlkit.table()
    pkg_table.add(tomlkit.comment("Version bump type: patch, minor, or major"))
    pkg_table.add("bump", "")
    pkg_table.add(tomlkit.comment("Short description of this release (required)"))
    pkg_table.add("description", "")
    pkg_table.add(tomlkit.comment("Optional context explaining why these changes were made"))
    pkg_table.add("context", "")
    pkg_table.add("include", target_names)
    pkg_table.add("exclude", [])

    # Add per-target config sections for Flutter target
    flutter_targets = [n for n in target_names if n == "flutter"]
    if flutter_targets:
        targets_table = tomlkit.table(is_super_table=True)
        for ft in flutter_targets:
            t = tomlkit.table()
            t.add("mode", "build")
            targets_table.add(ft, t)
        pkg_table.add("targets", targets_table)

    return pkg_table


def _render_commented_section(name, target_names, reason, section_key="packages"):
    """Render a package/releasable section as TOML comments.

    Returns a string of comment lines (each prefixed with '# ') that
    represent the section the user would uncomment if they want to include it.
    """
    lines = [
        f"# {name}: {reason}",
        f"# [{section_key}.{name}]",
        "# bump = \"\"",
        "# description = \"\"",
        "# context = \"\"",
        f"# include = {tomlkit.item(target_names).as_string()}",
        "# exclude = []",
    ]
    return "\n".join(lines)


def _collect_releasable_targets(releasable_name, member_projects, workspace_root):
    """Collect the union of targets across all member projects of a releasable.

    Returns a deduplicated list of target names.
    """
    seen = set()
    result = []
    for proj in member_projects:
        project_dir = os.path.join(workspace_root, proj["path"])
        entries = detect_targets(project_dir)
        for e in entries:
            if e.name not in seen:
                seen.add(e.name)
                result.append(e.name)
    return result


def _cmd_batch_release_init(project_root, packages=None):
    """Create .rlsbl-monorepo/releases/unreleased.toml with per-package or
    per-releasable sections.

    In explicit mode (workspace has ``[[releasables]]``), scaffolds
    ``[releasables.<name>]`` sections grouped by releasable. In implicit
    mode, scaffolds ``[packages.<name>]`` sections per package.

    Iterates over all releasable units (skipping non-releasable projects),
    detects targets for each, and scaffolds sections with empty bump/description
    and the detected include list.

    Items with zero unreleased commits are included as commented-out sections.

    Args:
        project_root: Path to the project root directory.
        packages: Optional comma-separated string of names to include.
            In explicit mode these are releasable names; in implicit mode,
            package names.
    """
    from ...workspace import is_explicit_mode, load_releasables, members_of

    start = str(project_root)
    workspace_root = find_workspace_root(start)
    if workspace_root is None:
        print(
            "Error: No workspace found. Run 'rlsbl monorepo init' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    batch_path = get_batch_release_file_path(workspace_root)
    if os.path.exists(batch_path):
        content = open(batch_path).read().strip()
        if content:
            print(f"Error: {batch_path} already exists.", file=sys.stderr)
            sys.exit(1)

    projects = load_workspace(workspace_root)
    if not projects:
        print("Error: no projects in workspace.", file=sys.stderr)
        sys.exit(1)

    explicit = is_explicit_mode(workspace_root)

    if explicit:
        _scaffold_releasable_sections(
            workspace_root, projects, batch_path, packages,
        )
    else:
        _scaffold_package_sections(
            workspace_root, projects, batch_path, packages,
        )


def _scaffold_releasable_sections(workspace_root, projects, batch_path, filter_names):
    """Scaffold [releasables.<name>] sections for explicit mode."""
    from ...workspace import load_releasables, members_of

    releasables = load_releasables(workspace_root, projects)

    # Parse filter
    requested_names = None
    if filter_names:
        requested_names = [n.strip() for n in filter_names.split(",") if n.strip()]
        all_names = {r.name for r in releasables}
        unknown = [n for n in requested_names if n not in all_names]
        if unknown:
            print(
                f"Error: unknown releasable(s): {', '.join(unknown)}. "
                f"Available: {', '.join(sorted(all_names))}",
                file=sys.stderr,
            )
            sys.exit(1)

    doc = tomlkit.document()
    section_table = tomlkit.table(is_super_table=True)

    any_added = False
    commented_sections = []

    for rel in releasables:
        if requested_names is not None and rel.name not in requested_names:
            continue

        member_projs = members_of(rel.name, projects)
        if not member_projs:
            print(f"Warning: releasable '{rel.name}' has no member projects, skipping.", file=sys.stderr)
            continue

        target_names = _collect_releasable_targets(rel.name, member_projs, workspace_root)
        if not target_names:
            print(f"Warning: no targets detected for releasable '{rel.name}', skipping.", file=sys.stderr)
            continue

        # Check unreleased commits across all member projects
        total_commits = 0
        last_tag = None
        for proj in member_projs:
            count, tag = _get_unreleased_commit_count(proj, workspace_root)
            total_commits += count
            if tag is not None:
                last_tag = tag

        if total_commits == 0 and last_tag is not None:
            reason = f"no unreleased commits since {last_tag}"
            commented_sections.append((rel.name, target_names, reason))
            any_added = True
            continue

        pkg_table = _build_pkg_section(None, workspace_root, target_names)
        section_table.add(rel.name, pkg_table)
        any_added = True

    if not any_added:
        print("Error: no eligible releasables with detected targets.", file=sys.stderr)
        sys.exit(1)

    doc.add("releasables", section_table)

    releases_dir = os.path.dirname(batch_path)
    os.makedirs(releases_dir, exist_ok=True)

    toml_text = tomlkit.dumps(doc)

    if commented_sections:
        comment_blocks = []
        for name, target_names, reason in commented_sections:
            comment_blocks.append(
                _render_commented_section(
                    name, target_names, reason, section_key="releasables",
                )
            )
        toml_text = toml_text.rstrip("\n") + "\n\n" + "\n\n".join(comment_blocks) + "\n"

    with open(batch_path, "w", encoding="utf-8") as f:
        f.write(toml_text)

    print(batch_path)


def _scaffold_package_sections(workspace_root, projects, batch_path, filter_names):
    """Scaffold [packages.<name>] sections for implicit mode (original behavior)."""
    # Parse filter
    requested_names = None
    if filter_names:
        requested_names = [n.strip() for n in filter_names.split(",") if n.strip()]
        all_names = {p["name"] for p in projects}
        unknown = [n for n in requested_names if n not in all_names]
        if unknown:
            print(
                f"Error: unknown package(s): {', '.join(unknown)}. "
                f"Available: {', '.join(sorted(all_names))}",
                file=sys.stderr,
            )
            sys.exit(1)

    doc = tomlkit.document()
    packages_table = tomlkit.table(is_super_table=True)

    any_added = False
    commented_sections = []

    for proj in projects:
        if not proj.is_releasable:
            print(f"Skipping non-releasable project: {proj['name']}", file=sys.stderr)
            continue

        if requested_names is not None and proj["name"] not in requested_names:
            continue

        project_dir = os.path.join(workspace_root, proj["path"])
        entries = detect_targets(project_dir)
        if not entries:
            print(
                f"Warning: no targets detected for {proj['name']}, skipping.",
                file=sys.stderr,
            )
            continue

        target_names = [e.name for e in entries]

        commit_count, last_tag = _get_unreleased_commit_count(proj, workspace_root)

        if commit_count == 0 and last_tag is not None:
            reason = f"no unreleased commits since {last_tag}"
            commented_sections.append((proj["name"], target_names, reason))
            any_added = True
            continue

        pkg_table = _build_pkg_section(proj, workspace_root, target_names)
        packages_table.add(proj["name"], pkg_table)
        any_added = True

    if not any_added:
        print("Error: no eligible projects with detected targets.", file=sys.stderr)
        sys.exit(1)

    doc.add("packages", packages_table)

    releases_dir = os.path.dirname(batch_path)
    os.makedirs(releases_dir, exist_ok=True)

    toml_text = tomlkit.dumps(doc)

    if commented_sections:
        comment_blocks = []
        for name, target_names, reason in commented_sections:
            comment_blocks.append(
                _render_commented_section(name, target_names, reason)
            )
        toml_text = toml_text.rstrip("\n") + "\n\n" + "\n\n".join(comment_blocks) + "\n"

    with open(batch_path, "w", encoding="utf-8") as f:
        f.write(toml_text)

    print(batch_path)
