"""Monorepo snapshot commands: write .rlsbl-monorepo/snapshot.json, or check it.

The two jobs used to be one command with a ``--check`` flag, which made the
command's classification unanswerable: verifying is a pure read, regenerating
writes and commits.  They are two commands now -- ``monorepo snapshot`` is
``mutating`` and previews completely under ``--dry-run``, ``monorepo
snapshot-check`` is ``read_only`` and never writes anything.
"""

import sys

from ...snapshot import (
    SNAPSHOT_FILE,
    check_snapshot,
    generate_snapshot,
    write_snapshot,
)
from ... import effects
from ...utils import commit_files
from ...workspace import WORKSPACE_DIR, find_workspace_root, load_workspace
from ...workspace_graph import WorkspaceGraph


def _load(project_root):
    """Resolve the workspace and build its graph, or exit with guidance."""
    root = find_workspace_root(str(project_root))
    if root is None:
        print("Error: No workspace found. Run 'rlsbl monorepo init' first.", file=sys.stderr)
        sys.exit(1)
    projects = load_workspace(root)
    if not projects:
        return root, None, None
    return root, projects, WorkspaceGraph(root, projects)


def _cmd_snapshot(flags, project_root):
    """Regenerate the workspace snapshot artifact and commit it."""
    root, projects, graph = _load(project_root)
    if projects is None:
        print("No projects in workspace.")
        return

    rel_path = f"{WORKSPACE_DIR}/{SNAPSHOT_FILE}"
    # Read BEFORE writing.  Under --dry-run the write is recorded rather than
    # performed, so asking the filesystem afterwards whether the artifact
    # changed would be asking about a write that never happened -- the effects
    # regime answers such a question with an unsettled value and truncates the
    # preview.  Deciding here, from a pure read, keeps the preview complete.
    stale = not check_snapshot(root, projects, graph)

    snapshot = generate_snapshot(root, projects, graph)
    write_snapshot(root, snapshot)
    # A preview wrote nothing; the would-do log reports what it would have
    # written, and a "Wrote ..." line above it would contradict the header.
    print(f"{'Would write' if effects.previewing() else 'Wrote'} {rel_path}")

    if not stale:
        print("Snapshot unchanged.")
        return
    commit_files("snapshot", [rel_path], autogenerated=True)


def _cmd_snapshot_check(flags, project_root):
    """Verify the workspace snapshot artifact is current. Writes nothing."""
    root, projects, graph = _load(project_root)
    if projects is None:
        print("No projects in workspace.")
        return

    if check_snapshot(root, projects, graph):
        print("Snapshot is up-to-date.")
        return
    print("Snapshot is stale or missing.", file=sys.stderr)
    sys.exit(1)
