"""Monorepo snapshot command: generate or verify .rlsbl-monorepo/snapshot.json."""

import sys

from ...snapshot import (
    SNAPSHOT_FILE,
    check_snapshot,
    generate_snapshot,
    write_snapshot,
)
from ...utils import commit_files_if_changed
from ...workspace import WORKSPACE_DIR, find_workspace_root, load_workspace
from ...workspace_graph import WorkspaceGraph


def _cmd_snapshot(flags, project_root):
    """Generate or check the monorepo snapshot."""
    start = str(project_root)
    root = find_workspace_root(start)
    if root is None:
        print("Error: No workspace found. Run 'rlsbl monorepo init' first.", file=sys.stderr)
        sys.exit(1)

    projects = load_workspace(root)
    if not projects:
        print("No projects in workspace.")
        return

    graph = WorkspaceGraph(root, projects)

    check = flags.get("check", False)

    if check:
        if check_snapshot(root, projects, graph):
            print("Snapshot is up-to-date.")
        else:
            print("Snapshot is stale or missing.", file=sys.stderr)
            sys.exit(1)
        return

    # --dry-run reached this command and was dropped on the floor: the
    # snapshot was regenerated and committed regardless. It is a real preview
    # now -- the snapshot is computed (that is pure) and the write and the
    # commit are only described. check_snapshot answers the same question the
    # write would have: whether the on-disk artifact already matches.
    if flags.get("dry-run", False):
        rel_path = f"{WORKSPACE_DIR}/{SNAPSHOT_FILE}"
        if check_snapshot(root, projects, graph):
            print(f"Would write {rel_path}: unchanged, nothing to commit.")
        else:
            print(f"Would write {rel_path} ({len(projects)} package(s)) and "
                  f"commit it.")
        return

    snapshot = generate_snapshot(root, projects, graph)
    rel_path = write_snapshot(root, snapshot)
    print(f"Wrote {rel_path}")

    commit_files_if_changed("snapshot", [rel_path], skip_message="Snapshot unchanged.", autogenerated=True)
