package release

import (
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle"
	"github.com/stricttools/strictspec/go/lifecycle/index"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/ci"
	"github.com/stricttools/rlsbl/internal/declarations"
	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/github"
	"github.com/stricttools/rlsbl/internal/pipelines"
	"github.com/stricttools/rlsbl/internal/publishrules"
	"github.com/stricttools/rlsbl/internal/registry"
	"github.com/stricttools/rlsbl/internal/releasenotes"
	"github.com/stricttools/rlsbl/internal/releaserecord"
	"github.com/stricttools/rlsbl/internal/runstate"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/tagging"
	"github.com/stricttools/rlsbl/internal/targets"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// origin is the remote a release pushes to.
const origin = "origin"

// A release walks its step table in order, recording each step in the
// in-progress state as it completes or fails. Until the candidate reaches
// origin, a failure discards the attempt: it ran in the release checkout,
// so only the advance of the branch it made is taken back, and a fresh
// release's state is removed (a resume's is put back as the attempt found
// it). Once the candidate is on origin nothing is taken back: the failure is
// recorded and `rlsbl release resume` continues from the step that failed.
// The release tags the commit CI verified (main-as-candidate ordering): the
// candidate is pushed untagged, CI judges it, and only a passing verdict
// lets the release finalize, tag, and publish.

// execution is one walk of a release's steps.
type execution struct {
	e       *strictcli.Effects
	session *Session
	// co is the release checkout; nil under --dry-run.
	co   *Checkout
	live git.Repo
	// repo and ws are rooted at the release checkout.
	repo             git.Repo
	ws               *workspace.Workspace
	releasable       declarations.Releasable
	representative   declarations.Member
	scheme           workspace.TagScheme
	version          semver.Version
	current          semver.Version
	primary          string
	syncs            []LockfileSync
	env              map[string]string
	gh               github.Client
	ghRepo           github.Repository
	reg              registry.Client
	record           *lifecycle.Record
	index            *index.Index
	scanner          *publishrules.Scanner
	timeouts         Timeouts
	ecosystemTagging bool
	publishesFromCI  bool
	branch           string
	now              time.Time
	resuming         bool
	req              RunRequest
	// generated are the files the pre-release pipeline and the hooks wrote
	// outside the selfdoc commit, which the release commit carries.
	generated []string
	state     runstate.InProgress
	// entry is a resume's state as the attempt found it, put back when the
	// attempt is discarded.
	entry runstate.InProgress
	// pushed is set once the candidate is on origin; pushAttempted once its
	// push started, since a push that timed out may have reached origin.
	pushed, pushAttempted bool
	candidate             string
	// batch is the release's role in a batch release; the zero value is a
	// release of its own.
	batch batchRole
}

func (x *execution) name() string { return x.releasable.Name }

func (x *execution) statePath() string {
	return filepath.Join(x.session.LiveRoot, filepath.FromSlash(runstate.InProgressPath(x.name())))
}

func (x *execution) save() error { return runstate.SaveInProgress(x.e, x.session.LiveRoot, x.state) }

func (x *execution) complete(step string) error {
	x.state.Complete(step)
	return x.save()
}

func (x *execution) rerun() string {
	if x.batch.rerun != "" {
		return x.batch.rerun
	}
	if x.resuming {
		return RerunResume
	}
	return RerunFresh
}

func (x *execution) branchRef() string { return "refs/heads/" + x.branch }

// recordCreated adds the commit HEAD names in the checkout to the release's
// own commits.
func (x *execution) recordCreated() error {
	head, err := x.repo.Head()
	if err != nil {
		return err
	}
	if !slices.Contains(x.state.CreatedCommits, head) {
		x.state.CreatedCommits = append(x.state.CreatedCommits, head)
	}
	return x.save()
}

// commit commits paths in the checkout with the Autogenerated trailer,
// records the commit among the release's own, and advances the release
// branch to the checkout's HEAD, which carries every commit the release
// made there (the selfdoc commit too). A commit that finds nothing changed
// makes no commit; the advance is then a no-op unless an earlier commit of
// the checkout is not on the branch yet.
func (x *execution) commit(message string, paths []string, requireChange bool) error {
	committed, err := x.repo.CommitDetached(git.CommitRequest{Message: message, Paths: paths, Autogenerated: true, RequireChange: requireChange})
	if err != nil {
		return err
	}
	if committed {
		if err := x.recordCreated(); err != nil {
			return err
		}
		x.req.Log("Committed: " + message)
	}
	return x.co.Advance("HEAD", "The release", x.rerun())
}

func (x *execution) guard(checkpoint string) error {
	return GuardForeignCommits(x.live, x.branchRef(), x.state.PinCommit, x.state.CreatedCommits, checkpoint, x.rerun())
}

// walk takes every step the state does not record as completed, then the
// epilogue.
func (x *execution) walk() error {
	if err := x.guard(CheckpointEntry); err != nil {
		return x.stop(StepVersionBumped, err)
	}
	if err := x.bumpAndCommit(); err != nil {
		return x.stop(StepCommitted, err)
	}
	if x.batch.deferCandidate {
		x.req.Log(fmt.Sprintf("Committed the release of %s %s; the batch pushes one candidate for every releasable it commits and waits for CI once", x.name(), x.version))
		return nil
	}
	if err := x.pushCandidate(); err != nil {
		return x.stop(StepCandidatePushed, err)
	}
	if err := x.verifyCI(); err != nil {
		return x.stop(StepCIVerified, err)
	}
	if err := x.guard(CheckpointCIGate); err != nil {
		return x.stop(StepChangelogFinalized, err)
	}
	steps := []struct {
		name string
		run  func() error
	}{
		{StepChangelogFinalized, x.finalizeChangelog},
		{StepReleaseArchived, x.archive},
		{StepTagged, x.tag},
		{StepPushed, x.push},
		{StepGitHubReleaseCreated, x.githubRelease},
		{StepPipelinesPublished, x.publishPipelines},
		{StepDeployed, x.deploy},
	}
	for _, s := range steps {
		if x.state.Completed(s.name) {
			x.req.Log(fmt.Sprintf("Skipping %s (done earlier)", s.name))
			continue
		}
		if err := s.run(); err != nil {
			return x.stop(s.name, err)
		}
	}
	if err := x.postReleaseHooks(); err != nil {
		return err
	}
	return x.epilogue()
}

// stop ends a walk that failed at step. Before the candidate reached origin
// the attempt is discarded; a refusal of the candidate's CI window and a
// stop after the candidate reached origin keep the state, recording the
// failure against step for `rlsbl release resume`.
func (x *execution) stop(step string, err error) error {
	var ciErr *CIError
	isCI := errors.As(err, &ciErr)
	timedOut := x.pushAttempted && strings.Contains(err.Error(), " timed out: ")
	if !x.pushed && !timedOut && !isCI {
		return x.discard(err)
	}
	x.state.Fail(step, err.Error())
	if serr := x.save(); serr != nil {
		return errors.Join(err, serr)
	}
	var foreign *ForeignCommitError
	var unverified *UnverifiedCandidateError
	if isCI || errors.As(err, &foreign) || errors.As(err, &unverified) {
		return err
	}
	if timedOut && !x.pushed {
		return fmt.Errorf("%w\nThe push of the candidate to origin/%s timed out, so whether it reached origin is unknown, and nothing was taken back. Nothing was tagged, released, or finalized, and %s is not burnt. Give the push more time and resume: `rlsbl release resume --push-timeout 900` (or declare push_seconds in %s)", err, x.branch, x.version, declarations.ReleasablesFile)
	}
	return fmt.Errorf("%w\nThe release candidate is on origin, so nothing was taken back. The release state is kept in %s: fix the cause and run `rlsbl release resume`, which continues from %s", err, x.statePath(), step)
}

// discard throws away an attempt that stopped before its candidate reached
// origin: the branch advance it made is taken back, and the state is
// removed (a fresh release) or put back as the attempt found it (a resume).
// An advance that cannot be taken back without touching somebody else's work
// is left in place with the state kept.
func (x *execution) discard(err error) error {
	ok, reason, uerr := x.co.UnwindLastAdvance()
	if uerr != nil {
		return errors.Join(err, uerr)
	}
	if !ok {
		x.state.Fail(StepCandidatePushed, err.Error())
		if serr := x.save(); serr != nil {
			return errors.Join(err, serr)
		}
		return fmt.Errorf("%w\nThe release candidate was not pushed, and %s could not be taken back to where the release started: %s. The release commit stays on %s and the release state is kept: fix the cause and run `rlsbl release resume`, or run `rlsbl release abandon --approve-consequential` to record %s as never released", err, x.branch, reason, x.branch, x.version)
	}
	if x.resuming {
		if serr := runstate.SaveInProgress(x.e, x.session.LiveRoot, x.entry); serr != nil {
			return errors.Join(err, serr)
		}
	} else if serr := runstate.ClearInProgress(x.e, x.session.LiveRoot, x.name()); serr != nil {
		return errors.Join(err, serr)
	}
	return fmt.Errorf("%w\nThe release stopped before its candidate was pushed. It ran in the release checkout, so nothing of this attempt is on %s or in the working tree, and nothing reached origin. Deal with the error above and %s", err, x.branch, x.rerun())
}

// bumpPlan derives the version-bumped step's plan.
func (x *execution) bumpPlan() (BumpPlan, error) {
	return BuildBumpPlan(BumpPlanInputs{
		Workspace: x.ws, Releasable: x.name(), Representative: x.representative.Name,
		Current: x.current, Next: x.version, Primary: x.primary, Syncs: x.syncs,
		EcosystemTagging: x.ecosystemTagging, RlsblVersion: x.req.RlsblVersion, Generated: x.generated,
	})
}

func (x *execution) bumpExecution(preview bool) BumpExecution {
	return BumpExecution{
		Workspace: x.ws, Releasable: x.name(), Repo: x.repo, LiveRoot: x.session.LiveRoot,
		Environment: x.env, Rerun: x.rerun(), Preview: preview, Record: x.record, Index: x.index,
		Now: x.now, Log: x.req.Log,
	}
}

// bumpAndCommit takes the version-bumped and the committed steps: the
// version writes, the re-locks, the build and its scans, then the release
// commit (the version-bump commit, with the Autogenerated trailer), which
// the release branch advances to. They are taken together: the version
// writes exist only in the checkout until the commit reaches the branch, so
// a resume whose commit never reached it writes them again.
func (x *execution) bumpAndCommit() error {
	if x.state.Completed(StepCommitted) {
		x.req.Log("Skipping the version bump and the release commit (done earlier)")
		return nil
	}
	plan, err := x.bumpPlan()
	if err != nil {
		return err
	}
	result, err := ExecuteBumpPlan(x.e, plan, x.bumpExecution(false))
	if err != nil {
		return err
	}
	if err := x.complete(StepVersionBumped); err != nil {
		return err
	}
	files := newPathSet()
	for _, f := range append(append([]string(nil), plan.FilesToCommit...), result.Written...) {
		files.add(f)
	}
	requireChange := semver.Compare(x.current, x.version) != 0 && !plan.AlreadyBumped
	if err := x.commit(x.state.CommitMessage, files.list(), requireChange); err != nil {
		return err
	}
	return x.complete(StepCommitted)
}

// pushCandidate takes the candidate-pushed step: the branch tip, holding
// the release commit, is recorded as the candidate and pushed to origin,
// untagged, guarded by the value origin's branch held. A resume past the CI
// verdict tags the candidate the state records instead, pushing nothing.
func (x *execution) pushCandidate() error {
	if x.state.Completed(StepCIVerified) {
		fate, err := releaserecord.New(x.repo, x.name(), x.scheme, "").Fate(x.version)
		if err != nil {
			return err
		}
		x.candidate, err = requireRecordedCandidate(x.live, x.branchRef(), x.state.ReleaseCommit, x.version, fate, x.statePath())
		if err != nil {
			return err
		}
		x.pushed = true
		x.req.Log(fmt.Sprintf("Skipping the candidate push and the CI wait: CI verified %s earlier", short(x.candidate)))
		return nil
	}
	if x.batch.verified != "" {
		return x.adoptBatchCandidate()
	}
	x.candidate = x.co.Tip
	x.state.ReleaseCommit = x.candidate
	if err := x.save(); err != nil {
		return err
	}
	if err := x.guard(CheckpointCandidatePush); err != nil {
		return err
	}
	remote, found, err := x.live.RemoteRef(origin, x.branchRef())
	if err != nil {
		return fmt.Errorf("origin's %s could not be read, so the candidate push has no lease to go by: %w", x.branch, err)
	}
	if !found {
		remote = ""
	}
	needsPush := remote != x.candidate
	window, err := judgeCandidateWindow(x.repo, x.ws, x.name(), x.candidate, remote, needsPush, x.state.Completed(StepCandidatePushed), x.state.CreatedCommits, x.version, x.state.Tag, x.branch, RerunResume)
	if err != nil {
		return err
	}
	if window == windowOwesDispatch {
		x.state.RunAllDispatchFor = x.candidate
		if err := x.save(); err != nil {
			return err
		}
		x.req.Log(fmt.Sprintf("The push of %s cannot trigger the CI of %s, and its candidate was published once before: it is pushed and the CI router dispatched with %s=true, so every member's jobs run on it", short(x.candidate), x.name(), "run_all"))
	}
	if needsPush {
		x.pushAttempted = true
		if err := x.live.Push(origin, git.RefUpdate{Ref: x.branchRef(), New: x.candidate, Expected: remote}, x.timeouts.Push); err != nil {
			return err
		}
		x.req.Log(fmt.Sprintf("Pushed the release candidate %s to origin/%s (untagged)", short(x.candidate), x.branch))
	} else {
		x.req.Log(fmt.Sprintf("origin/%s is at the candidate %s already", x.branch, short(x.candidate)))
	}
	x.pushed = true
	return x.complete(StepCandidatePushed)
}

// watcher watches CI runs of the release's repository.
func (x *execution) watcher() ci.Watcher {
	return ci.Watcher{GH: x.gh, Repo: x.ghRepo, Log: x.req.Log, Sleep: x.req.Sleep, Now: x.req.Now}
}

// verifyCI takes the ci-verified step: it waits for CI's verdict on the
// candidate, refusing anything but a pass (or a repository that declares no
// push-triggered CI, which is said out loud).
func (x *execution) verifyCI() error {
	if x.state.Completed(StepCIVerified) {
		return nil
	}
	w := x.watcher()
	if x.state.RunAllDispatchFor == x.candidate {
		if _, err := w.DispatchRunAll(x.branch, x.candidate); err != nil {
			return err
		}
		x.state.RunAllDispatchFor = ""
		if err := x.save(); err != nil {
			return err
		}
	}
	filters, err := ci.ReleasableFilters(x.ws, x.name())
	if err != nil {
		return err
	}
	verdict, results, err := w.WaitForCIGreen(ci.WaitInputs{Commit: x.candidate, Root: x.ws.Root, Timeout: x.timeouts.CI, DiscoveryGrace: ci.DiscoveryGrace, Filters: filters})
	var notRun *ci.NotRunError
	var noRun *ci.WaitError
	switch {
	case errors.As(err, &notRun):
		return &CIError{Message: ciNotRunMessage(x.version, x.state.Tag, x.branch, x.candidate, notRun.Message)}
	case errors.As(err, &noRun):
		return &CIError{Message: ciRedMessage(x.version, x.state.Tag, x.branch, x.candidate, noRun.Message)}
	case err != nil:
		return err
	}
	switch verdict {
	case ci.NotConfigured:
		x.req.Warn("rlsbl: no workflow in .github/workflows triggers on push, so the release proceeds with no CI verdict on its candidate")
	case ci.Green:
		x.req.Log(fmt.Sprintf("CI passed on %s", short(x.candidate)))
	case ci.Timeout:
		var open []string
		for _, r := range results {
			if !r.Passed {
				open = append(open, r.Name)
			}
		}
		return &CIError{Message: ciTimeoutMessage(x.version, x.state.Tag, x.branch, x.candidate, fmt.Sprintf("Runs unresolved after %s: %s", x.timeouts.CI, strings.Join(orNone(open), ", ")))}
	default:
		var failed []string
		for _, r := range results {
			if !r.Passed && !r.Unresolved {
				failed = append(failed, r.Name)
			}
		}
		return &CIError{Message: ciRedMessage(x.version, x.state.Tag, x.branch, x.candidate, "Failing runs: "+strings.Join(orNone(failed), ", "))}
	}
	x.state.ReleaseCommit = x.candidate
	return x.complete(StepCIVerified)
}

// finalizeChangelog takes the changelog-finalized step: the unreleased
// entries become the released version's read-only file, committed with the
// generated changelogs a resume regenerated.
func (x *execution) finalizeChangelog() error {
	dir := changelog.Dir(x.name())
	root := x.ws.Root
	released := path.Join(dir, changelog.VersionName(x.version))
	unreleased := path.Join(dir, changelog.UnreleasedName)
	releasedExists, err := fileExists(filepath.Join(root, filepath.FromSlash(released)))
	if err != nil {
		return err
	}
	f, err := changelog.ReadUnreleased(root, dir)
	if err != nil {
		return err
	}
	if releasedExists && len(f.Entries()) == 0 {
		x.req.Log("The changelog is finalized already")
		return x.complete(StepChangelogFinalized)
	}
	if exists, err := fileExists(filepath.Join(root, filepath.FromSlash(unreleased))); err != nil {
		return err
	} else if !exists {
		// A releasable that never had an entry (an infra release) still
		// gets its released file, which the GitHub Release is composed from.
		if _, err := x.e.Mkdir(filepath.Join(root, filepath.FromSlash(dir))); err != nil {
			return err
		}
		if _, err := x.e.Write(filepath.Join(root, filepath.FromSlash(unreleased)), []byte{}, strictcli.Mode(0o644)); err != nil {
			return err
		}
	}
	if err := changelog.Finalize(x.e, root, dir, x.version); err != nil {
		return err
	}
	paths := []string{released, unreleased, changelog.Home(x.ws.Declarations, x.name())}
	if x.ws.IsWorkspace() {
		paths = append(paths, changelog.RollUpPath)
	}
	if err := x.commit(fmt.Sprintf("chore: finalize changelog for %s", x.version), paths, false); err != nil {
		return err
	}
	return x.complete(StepChangelogFinalized)
}

// releasedPaths are the paths whose trees a release records: "." for a
// standalone project, each member's directory for a workspace releasable.
func (x *execution) releasedPaths() []string {
	if !x.ws.IsWorkspace() {
		return []string{"."}
	}
	var out []string
	for _, m := range sortedMembers(x.ws.MembersOf(x.name())) {
		out = append(out, m.Path)
	}
	return out
}

// archive takes the release-archived step: the release file becomes the
// version's archive recording the commit CI verified and the trees of every
// path the release ships (a release with no release file of its own, a
// batch member, gets an archive written from its state), the record's
// pending identities of this version become dated periods, starting on the
// committer date of the release commit, and the changelogs are generated
// again from the archive.
func (x *execution) archive() error {
	root := x.ws.Root
	trees := map[string]string{}
	for _, p := range x.releasedPaths() {
		tree, found, err := x.repo.TreeAt(x.candidate, p)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("the release commit %s holds no %s, so its released tree cannot be recorded", short(x.candidate), p)
		}
		trees[p] = tree
	}
	rc := releaserecord.ReleaseCommit{Commit: x.candidate, Trees: trees}
	dir := releaserecord.ArchiveDir(x.name())
	archivePath := releaserecord.ArchivePath(dir, x.version)
	releaseFile := releaserecord.ReleaseFilePath(x.name())
	hasFile, err := fileExists(filepath.Join(root, filepath.FromSlash(releaseFile)))
	if err != nil {
		return err
	}
	hasArchive, err := fileExists(filepath.Join(root, filepath.FromSlash(archivePath)))
	if err != nil {
		return err
	}
	if hasFile || hasArchive {
		if err := releaserecord.ArchiveReleaseFile(x.e, root, x.name(), x.version, rc); err != nil {
			return err
		}
	} else {
		bump, err := semver.ParseBump(x.state.Bump)
		if err != nil || strings.TrimSpace(x.state.Description) == "" {
			return fmt.Errorf("the releasable %q has no release file %s to archive, and the release state holds no bump and description to write the archive of %s from", x.name(), releaseFile, x.version)
		}
		if _, err := releaserecord.WriteArchive(x.e, root, dir, x.version, releaserecord.ArchiveSpec{
			ReleaseFile:   releaserecord.ReleaseFile{Bump: bump, Include: x.state.Include, Exclude: x.state.Exclude, Description: x.state.Description, Context: x.state.Context},
			Fate:          releaserecord.FateRecorded,
			ReleaseCommit: rc,
		}); err != nil {
			return err
		}
	}
	paths := []string{archivePath, releaseFile}
	date, err := x.repo.CommitterDate(x.candidate)
	if err != nil {
		return err
	}
	record, err := lifecycle.Load(root)
	if err != nil {
		return err
	}
	converted, err := record.ActivatePendingIdentities(x.version.String(), date)
	if err != nil {
		return err
	}
	if len(converted) > 0 {
		if err := record.Write(effectsWriter{x.e}, root); err != nil {
			return err
		}
		x.record = record
		paths = append(paths, lifecycle.RecordFile)
		for _, id := range converted {
			x.req.Log(fmt.Sprintf("The %s of %s is %s from %s on, as recorded for %s", id.Facet, id.Subject, id.Value, date.Format(time.DateOnly), x.version))
		}
	}
	regenerated, err := changelog.Regenerate(x.e, root, x.ws.Declarations, x.name(), nil)
	if err != nil {
		return err
	}
	paths = append(paths, regenerated...)
	if err := x.commit(fmt.Sprintf("chore: finalize release file for %s", x.version), paths, false); err != nil {
		return err
	}
	return x.complete(StepReleaseArchived)
}

// expectedRefs are the tags the release creates: the tag format's spelling,
// the members' companion tags, and the aliases the transition record holds
// for the tag.
func (x *execution) expectedRefs() (targets.ExpectedRefs, error) {
	var members []targets.RefMember
	for _, m := range x.ws.MembersOf(x.name()) {
		ts, err := targets.MemberTargets(x.ws.Root, m)
		if err != nil {
			return targets.ExpectedRefs{}, err
		}
		members = append(members, targets.RefMember{Path: m.Path, Targets: ts, Publishes: x.releasable.PublishMode != declarations.PublishNone})
	}
	events, err := releaserecord.ReadEvents(x.ws.Root)
	if err != nil {
		return targets.ExpectedRefs{}, err
	}
	tag := x.scheme.Render(x.version)
	var aliases []string
	for _, ev := range events {
		alias, ok := ev.(*releaserecord.BoundaryAliasEvent)
		if !ok || (alias.Releasable != "" && alias.Releasable != x.name()) {
			continue
		}
		for _, b := range alias.Aliases {
			if b.AliasedTag == tag {
				aliases = append(aliases, b.AliasTag)
			}
		}
	}
	return targets.ExpectedRefsOf(x.version, targets.RefInputs{SchemeTag: tag, Members: members, Aliases: aliases})
}

// tag takes the tagged step: every tag the version owns is created on the
// commit CI verified. A tag already there at that commit is a resumed tag
// step; one at another commit is refused, since a release never moves a
// tag.
func (x *execution) tag() error {
	refs, err := x.expectedRefs()
	if err != nil {
		return err
	}
	if refs.Primary != x.state.Tag {
		return fmt.Errorf("the release resolved its tag as %s, and the releasable's refs name %s for %s; both read the same declarations, so one of them was given other ones. Nothing was tagged", x.state.Tag, refs.Primary, x.version)
	}
	tags := refs.Tags()
	for _, tag := range tags {
		sha, found, err := x.live.TagCommit(tag)
		if err != nil {
			return err
		}
		if found {
			if sha == x.candidate {
				continue
			}
			return fmt.Errorf("the tag %s exists already, at %s, and the release tags %s; a release never moves a tag, so find out where %s came from before resuming", tag, short(sha), short(x.candidate), tag)
		}
		if err := x.live.CreateRef("refs/tags/"+tag, x.candidate); err != nil {
			return err
		}
		x.req.Log(fmt.Sprintf("Tagged %s -> %s (the commit CI verified)", tag, short(x.candidate)))
	}
	x.state.CompanionTags = append([]string(nil), tags[1:]...)
	return x.complete(StepTagged)
}

// push takes the pushed step: the release branch, now carrying the
// finalization commits, and then each tag on its own (GitHub starts nothing
// for a push carrying more than three tags), each guarded by what origin
// held. A tag origin holds at the release commit is pushed already; one at
// another commit is refused.
func (x *execution) push() error {
	if err := x.guard(CheckpointFinalPush); err != nil {
		return err
	}
	tip, found, err := x.live.ResolveCommit(x.branchRef())
	if err != nil {
		return err
	}
	if !found {
		return fmt.Errorf("the release branch %s has disappeared", x.branch)
	}
	remote, onOrigin, err := x.live.RemoteRef(origin, x.branchRef())
	if err != nil {
		return err
	}
	if !onOrigin {
		remote = ""
	}
	if remote != tip {
		x.pushAttempted = true
		if err := x.live.Push(origin, git.RefUpdate{Ref: x.branchRef(), New: tip, Expected: remote}, x.timeouts.Push); err != nil {
			return err
		}
	}
	for _, tag := range append([]string{x.state.Tag}, x.state.CompanionTags...) {
		there, present, err := x.live.RemoteTagCommit(origin, tag)
		if err != nil {
			return fmt.Errorf("whether origin has the tag %s could not be read, and a tag is never pushed blind: %w", tag, err)
		}
		if present {
			if there == x.candidate {
				continue
			}
			return fmt.Errorf("origin has the tag %s at %s, and the release tagged %s; a release never moves a tag, so find out where origin's came from before resuming", tag, short(there), short(x.candidate))
		}
		if err := x.live.Push(origin, git.RefUpdate{Ref: "refs/tags/" + tag, New: x.candidate}, x.timeouts.Push); err != nil {
			return err
		}
	}
	x.req.Log(fmt.Sprintf("Pushed %s and the tags of %s to origin", x.branch, x.version))
	return x.complete(StepPushed)
}

// githubRelease takes the github-release-created step: the Release is
// composed from the record (the released changelog file, the archive, and
// the rlsbl-ci-sha marker naming the commit CI verified) and created; a
// Release that exists already gets the marker. With rlsbl:ecosystem-tagging
// on, a releasable that publishes puts the rlsbl topic on the repository.
func (x *execution) githubRelease() error {
	doc, err := releasenotes.Read(x.ws.Root, x.name(), x.scheme, x.version)
	if err != nil {
		return err
	}
	body, err := doc.Body()
	if err != nil {
		return err
	}
	if err := x.scanner.ScanTexts([]publishrules.Text{{Name: "the GitHub Release body of " + doc.Tag, Content: body}}); err != nil {
		return err
	}
	exists, err := x.gh.ReleaseExists(x.ghRepo, doc.Tag)
	if err != nil {
		return err
	}
	if !exists {
		if cerr := releasenotes.Create(x.gh, x.ghRepo, doc, true); cerr != nil {
			// GitHub can answer an error for a Release it created.
			created, err := x.gh.ReleaseExists(x.ghRepo, doc.Tag)
			if err != nil || !created {
				return fmt.Errorf("the GitHub Release of %s could not be created: %w", doc.Tag, cerr)
			}
			exists = true
		} else {
			x.req.Log("Created the GitHub Release " + doc.Tag)
		}
	}
	if exists {
		wrote, err := releasenotes.EnsureMarker(x.gh, x.ghRepo, doc)
		if err != nil {
			return fmt.Errorf("the GitHub Release of %s exists, and its rlsbl-ci-sha marker, which tells the publish workflow which commit CI verified, could not be written: %w", doc.Tag, err)
		}
		if wrote {
			x.req.Log("Wrote the rlsbl-ci-sha marker onto the existing GitHub Release " + doc.Tag)
		}
	}
	if x.ecosystemTagging && x.releasable.PublishMode != declarations.PublishNone {
		if _, err := x.gh.EnsureTopic(x.ghRepo, tagging.Keyword); err != nil {
			return fmt.Errorf("adding the %s topic to %s (rlsbl:ecosystem-tagging is on): %w", tagging.Keyword, x.ghRepo, err)
		}
	}
	return x.complete(StepGitHubReleaseCreated)
}

// lookupEnv reads a variable from the release's environment, then the
// process's.
func (x *execution) lookupEnv(name string) (string, bool) {
	if v, ok := x.env[name]; ok {
		return v, true
	}
	return os.LookupEnv(name)
}

// publishPipelines takes the pipelines-published step: every local pipeline
// of the releasable's members publishes from this machine, each recorded
// once published (as member/pipeline) so a resume publishes only the rest.
// CI pipelines publish from the workflow the Release started.
func (x *execution) publishPipelines() error {
	if x.releasable.PublishMode == declarations.PublishNone {
		return x.complete(StepPipelinesPublished)
	}
	for _, m := range sortedMembers(x.ws.MembersOf(x.name())) {
		ts, err := targets.MemberTargets(x.ws.Root, m)
		if err != nil {
			return err
		}
		for _, p := range m.Pipelines {
			if !p.Local {
				continue
			}
			key := m.Name + "/" + p.Name
			if slices.Contains(x.state.PublishedTargets, key) {
				x.req.Log(fmt.Sprintf("Skipping the pipeline %s (published earlier)", key))
				continue
			}
			dir := ""
			for _, t := range ts {
				if t.Name == p.Target {
					dir = filepath.Join(x.ws.Root, filepath.FromSlash(m.TargetDir(t)))
				}
			}
			if dir == "" {
				return fmt.Errorf("the pipeline %q of the member %q publishes the target %q, which the member does not have", p.Name, m.Name, p.Target)
			}
			published, err := pipelines.PublishLocal(x.e, x.reg, x.lookupEnv, pipelines.LocalPublish{Pipeline: p, Dir: dir, Version: x.version})
			if err != nil {
				return fmt.Errorf("the pipeline %s: %w", key, err)
			}
			x.req.Log(fmt.Sprintf("The pipeline %s: %s", key, published.Message))
			x.state.PublishedTargets = append(x.state.PublishedTargets, key)
			if err := x.save(); err != nil {
				return err
			}
		}
	}
	return x.complete(StepPipelinesPublished)
}

// deploy takes the deployed step: a server releasable's deploy_command,
// {version} replaced by the released version, run from the release
// checkout's root with the check timeout. A failure stops the release with
// its state kept, and `rlsbl release resume` runs it again.
func (x *execution) deploy() error {
	if x.releasable.DeployCommand == nil {
		return x.complete(StepDeployed)
	}
	argv := make([]interface{}, len(x.releasable.DeployCommand))
	shown := make([]string, len(x.releasable.DeployCommand))
	for i, a := range x.releasable.DeployCommand {
		shown[i] = strings.ReplaceAll(a, "{version}", x.version.String())
		argv[i] = shown[i]
	}
	x.req.Log("Deploying: " + strings.Join(shown, " "))
	if _, err := x.e.Run(argv, strictcli.Cwd(x.ws.Root), strictcli.EffectEnv(x.env), strictcli.Stream(true), strictcli.Timeout(x.timeouts.Check), strictcli.Resource("deploy:"+x.name())); err != nil {
		return fmt.Errorf("the deploy command `%s` of %s failed: %w", strings.Join(shown, " "), x.name(), err)
	}
	return x.complete(StepDeployed)
}

// postReleaseHooks takes the post-release-hooks-run step, the one step
// whose failure does not stop the release: every hook runs, and a failure is
// recorded for the epilogue.
func (x *execution) postReleaseHooks() error {
	if x.state.Completed(StepPostReleaseHooksRun) {
		return nil
	}
	runs, err := HookRuns(x.ws, x.name(), x.representative.Name, PostRelease, x.hookContext(x.state.Bump, x.state.Description))
	if err != nil {
		return err
	}
	if err := RunHooks(x.e, runs, x.env, x.timeouts.Hook); err != nil {
		x.req.Warn(err.Error())
		x.state.Fail(StepPostReleaseHooksRun, err.Error())
		return x.save()
	}
	return x.complete(StepPostReleaseHooksRun)
}

// epilogue ends a walk: a failed step keeps the state for a resume; a
// complete one removes it, confirms the publish workflows started, and
// under --watch watches CI on the release commit and asks the registries
// whether they list the version.
func (x *execution) epilogue() error {
	if failed := sortedKeys(x.state.FailedSteps); len(failed) > 0 {
		lines := []string{fmt.Sprintf("the release of %s %s finished with failed steps:", x.name(), x.version)}
		for _, step := range failed {
			lines = append(lines, fmt.Sprintf("  %s: %s", step, x.state.FailedSteps[step]))
		}
		lines = append(lines, fmt.Sprintf("The release state is kept in %s: fix the cause and run `rlsbl release resume` to take them again", x.statePath()))
		return errors.New(strings.Join(lines, "\n"))
	}
	if missing := x.state.MissingSteps(StepNames()); len(missing) > 0 {
		return fmt.Errorf("internal error: the release reached its end with steps it never recorded: %s", strings.Join(missing, ", "))
	}
	if err := runstate.ClearInProgress(x.e, x.session.LiveRoot, x.name()); err != nil {
		return err
	}
	x.req.Log(fmt.Sprintf("Released %s %s (%s)", x.name(), x.version, x.state.Tag))
	if x.publishesFromCI {
		runs := ci.PublishRuns{GH: x.gh, Repo: x.ghRepo, Git: x.live, Log: x.req.Log, Sleep: x.req.Sleep, Now: x.req.Now}
		if err := runs.ConfirmRunsStarted(x.state.Tag, x.candidate, ci.ConfirmDiscovery, ci.ConfirmInterval); err != nil {
			return err
		}
	}
	if !x.req.Watch {
		x.req.Warn(fmt.Sprintf("NOTICE: the publish outcome was not verified (--no-watch): the publish workflow runs in CI, and this run did not wait for it. Watch it with `rlsbl watch %s`, and confirm the version is listed by its registries before treating the release as shipped", x.candidate))
		return nil
	}
	results, err := x.watcher().WatchCommit(x.candidate, "release "+x.state.Tag)
	if err != nil {
		return err
	}
	var failing []string
	for _, r := range results {
		if !r.Passed {
			failing = append(failing, r.Name)
		}
	}
	if len(failing) > 0 {
		return fmt.Errorf("%s is tagged and released, and CI on it did not pass: %s. The tag and the Release exist, so nothing is released again: fix what failed and start the publish workflows at the tag again with `rlsbl release retry`", x.state.Tag, strings.Join(failing, ", "))
	}
	return x.verifyPublication()
}

// The registry listings' grace after CI concluded: a registry can take a
// while to list a version its publish accepted.
var publicationDelays = []time.Duration{0, 5 * time.Second, 15 * time.Second, 30 * time.Second}

// verifyPublication asks the package listing of every npm and PyPI package
// the releasable's CI pipelines publish whether it lists the version. A Go
// module is not asked: the proxy lists a version lazily, so its silence
// proves nothing.
func (x *execution) verifyPublication() error {
	if x.releasable.PublishMode == declarations.PublishNone {
		return nil
	}
	type pkg struct{ registry, name string }
	var packages []pkg
	for _, m := range sortedMembers(x.ws.MembersOf(x.name())) {
		ts, err := targets.MemberTargets(x.ws.Root, m)
		if err != nil {
			return err
		}
		for _, p := range m.Pipelines {
			if p.Local || (p.Type != declarations.TargetNPM && p.Type != declarations.TargetPyPI) {
				continue
			}
			for _, t := range ts {
				if t.Name != p.Target {
					continue
				}
				target, err := targets.Get(p.Type)
				if err != nil {
					return err
				}
				name, found, err := target.ReadName(filepath.Join(x.ws.Root, filepath.FromSlash(m.TargetDir(t))))
				if err != nil {
					return err
				}
				if found {
					packages = append(packages, pkg{p.Type, name})
				}
			}
		}
	}
	version := x.version.String()
	var missing []string
	for _, delay := range publicationDelays {
		if delay > 0 {
			x.req.Sleep(delay)
		}
		missing = nil
		for _, p := range packages {
			listed := false
			if p.registry == declarations.TargetNPM {
				doc, found, err := x.reg.NpmPackage(p.name)
				if err != nil {
					return err
				}
				listed = found && doc.Has(version)
			} else {
				doc, found, err := x.reg.PypiProject(p.name)
				if err != nil {
					return err
				}
				listed = found && doc.Has(version)
			}
			if !listed {
				missing = append(missing, fmt.Sprintf("%s on %s", p.name, p.registry))
			}
		}
		if len(missing) == 0 {
			if len(packages) > 0 {
				x.req.Log(fmt.Sprintf("The registries list %s: %d package(s)", version, len(packages)))
			}
			return nil
		}
	}
	return fmt.Errorf("%s is tagged and released, CI passed, and the registries do not list %s for %s: the publish never reached them. The tag and the Release exist, so nothing is released again: inspect the publish workflow's run for %s, fix the cause, and start it again with `rlsbl release retry`; if %s must not ship at all, `rlsbl release yank %s`", x.state.Tag, version, strings.Join(missing, ", "), x.state.Tag, version, version)
}

// preview is the rest of a release under --dry-run: the version-bumped plan,
// recorded, and the steps after it, named.
func (x *execution) preview() error {
	plan, err := x.bumpPlan()
	if err != nil {
		return err
	}
	x.req.Log("The version-bumped step's plan:\n" + RenderPlan(plan.Entries))
	if _, err := ExecuteBumpPlan(x.e, plan, x.bumpExecution(true)); err != nil {
		return err
	}
	x.req.Log(fmt.Sprintf("Would commit %d file(s) as %q: %s", len(plan.FilesToCommit), x.state.CommitMessage, strings.Join(plan.FilesToCommit, ", ")))
	x.req.Log(fmt.Sprintf("Would then push the candidate to origin/%s untagged, wait for CI's verdict on it, finalize the changelog, archive the release, tag %s on the commit CI verified, push, create the GitHub Release, publish the local pipelines, deploy, and run the post-release hooks", x.branch, x.state.Tag))
	return nil
}

// effectsWriter is the lifecycle library's file writer backed by the effects
// handle, so a preview records the record's writes.
type effectsWriter struct{ e *strictcli.Effects }

func (w effectsWriter) WriteFile(path string, data []byte) error {
	_, err := w.e.Write(path, data)
	return err
}

func (w effectsWriter) MkdirAll(path string) error {
	_, err := w.e.Mkdir(path)
	return err
}
