package release_test

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/changelog"
	"github.com/stricttools/rlsbl/internal/previewapply"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

const declarationsPath = ".strictmetadata/releasables/releasables.toml"

// standaloneDeclarations declares the standalone project portal; %s is its
// publish mode.
const standaloneDeclarations = `format_version = 1
repository_layout = "standalone"
release_branches = ["main"]

[[releasables]]
name = "portal"
tag_format = "v{version}"
publish_mode = "%s"

[[members]]
path = "."
name = "root"
releasable = "portal"
`

// workspaceDeclarations declares a workspace of the releasables widget and
// gadget, one member each, under a dev-node root.
const workspaceDeclarations = `format_version = 1
repository_layout = "workspace"
release_branches = ["main"]

[[releasables]]
name = "widget"
tag_format = "{name}@v{version}"
publish_mode = "none"

[[releasables]]
name = "gadget"
tag_format = "{name}@v{version}"
publish_mode = "none"

[[members]]
path = "."
name = "root"
dev_only = true
releasable = false

[[members]]
path = "widget"
name = "widget"
releasable = "widget"

[[members]]
path = "gadget"
name = "gadget"
releasable = "gadget"
`

func packageJSON(name, version string) string {
	return fmt.Sprintf("{\n  \"name\": %q,\n  \"version\": %q\n}\n", name, version)
}

// entryNumber makes each fixture entry's id distinct.
var entryNumber int

// entryLine is a serialized non-user-facing changelog entry naming commits.
func entryLine(commits ...string) string {
	entryNumber++
	id := fmt.Sprintf("%048x", entryNumber)
	return changelog.Serialize(changelog.Entry{ID: id, Commits: commits}) + "\n"
}

// standalone is the standalone project portal at version 0.4.0, nothing
// released yet.
func standalone(t *testing.T, publishMode string) *testsupport.Repo {
	t.Helper()
	repo := testsupport.NewRepo(t)
	repo.Write(declarationsPath, fmt.Sprintf(standaloneDeclarations, publishMode))
	repo.Write("package.json", packageJSON("portal", "0.4.0"))
	repo.Commit("the project", declarationsPath, "package.json")
	return repo
}

// workspaceRepo is the workspace of widget 0.1.0 and gadget 0.2.0, nothing
// released yet.
func workspaceRepo(t *testing.T) *testsupport.Repo {
	t.Helper()
	repo := testsupport.NewRepo(t)
	repo.Write(declarationsPath, workspaceDeclarations)
	repo.Write("widget/package.json", packageJSON("widget", "0.1.0"))
	repo.Write("gadget/package.json", packageJSON("gadget", "0.2.0"))
	repo.Write(".strictmetadata/releases/widget/version", "0.1.0\n")
	repo.Write(".strictmetadata/releases/gadget/version", "0.2.0\n")
	repo.Commit("the workspace", declarationsPath, "widget/package.json", "gadget/package.json", ".strictmetadata/releases/widget/version", ".strictmetadata/releases/gadget/version")
	return repo
}

// recordRelease records HEAD as the release of version v of releasable,
// tagged tag: its archive and its released changelog file, committed with
// the Autogenerated trailer as the release flow commits them. fate is
// "recorded", "unrecoverable", or "never-released".
func recordRelease(t *testing.T, repo *testsupport.Repo, releasable, v, tag, fate string) string {
	t.Helper()
	head := repo.Head()
	archive := ".strictmetadata/releases/" + releasable + "/v" + v + ".toml"
	body := "format_version = 2\nbump = \"minor\"\ninclude = []\nexclude = []\ndescription = \"release " + v + "\"\n"
	switch fate {
	case "recorded":
		body += "release_commit = \"" + head + "\"\n\n[released_trees]\n\".\" = \"" + strings.Repeat("e", 40) + "\"\n"
	case "unrecoverable":
		body += "unrecoverable = true\n"
	case "never-released":
		body += "never_released = true\n"
	default:
		t.Fatalf("unknown fate %q", fate)
	}
	repo.Write(archive, body)
	paths := []string{archive}
	if fate != "never-released" {
		released := changelog.Dir(releasable) + "/" + v + ".jsonl"
		repo.Write(released, entryLine(head))
		paths = append(paths, released)
	}
	if fate == "recorded" && tag != "" {
		repo.Git("tag", tag, head)
	}
	repo.Commit("release "+v+"\n\nAutogenerated: true", paths...)
	return head
}

// addEntry appends a non-user-facing entry naming commits to releasable's
// unreleased changelog and commits it.
func addEntry(t *testing.T, repo *testsupport.Repo, releasable string, commits ...string) string {
	t.Helper()
	rel := changelog.Dir(releasable) + "/" + changelog.UnreleasedName
	existing, err := os.ReadFile(repo.Path(rel))
	if err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	return repo.CommitFile(rel, string(existing)+entryLine(commits...), "changelog: entry")
}

// run runs fn with the effects handle of a read_only command carrying
// rlsbl's observe allowlist, its HTTP requests going to fake (nil: a fake
// that answers nothing, so any request fails the test), and returns fn's
// error.
func run(t *testing.T, fake *testsupport.FakeHTTP, fn func(e *strictcli.Effects) error) error {
	t.Helper()
	if fake == nil {
		fake = testsupport.NewFakeHTTP(t)
	}
	var ferr error
	testsupport.RunCommand(t, testsupport.CommandOptions{Effect: strictcli.EffectReadOnly, Allowlist: previewapply.Prefixes(), HTTPClient: fake.Client()}, func(ctx *strictcli.Context) error {
		ferr = fn(ctx.Effects())
		return ferr
	})
	return ferr
}

func mustNotFail(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatal(err)
	}
}

func requireContains(t *testing.T, text string, wants ...string) {
	t.Helper()
	for _, want := range wants {
		if !strings.Contains(text, want) {
			t.Fatalf("%q is not in:\n%s", want, text)
		}
	}
}
