package release_test

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/git"
	"github.com/stricttools/rlsbl/internal/release"
	"github.com/stricttools/rlsbl/internal/semver"
	"github.com/stricttools/rlsbl/internal/testsupport"
	"github.com/stricttools/rlsbl/internal/workspace"
)

// pipelineDeclarations declare the standalone project portal publishing
// nothing, whose pre-checks hook appends to the log at %s and writes a file.
const pipelineDeclarations = `format_version = 1
repository_layout = "standalone"
release_branches = ["main"]
github_repository = "acme/portal"

[[releasables]]
name = "portal"
tag_format = "v{version}"
publish_mode = "none"
hooks = { pre_checks = ["echo pre-checks >> %s; echo out > hook-output.txt"] }

[[members]]
path = "."
name = "root"
releasable = "portal"
`

// strictcliPackage is portal as a TypeScript strictcli program.
const strictcliPackage = `{
  "name": "portal",
  "version": "0.4.0",
  "bin": "cli.js",
  "dependencies": {
    "strictcli": "^0.50.0"
  }
}
`

// helpDocument is a help document in strictcli's canonical encoding, with a
// character a decode and re-encode would escape.
const helpDocument = "{\n  \"schema_version\": 2,\n  \"name\": \"portal\",\n  \"version\": \"0.0.0\",\n  \"help\": \"café\"\n}\n"

// pipelineRepo is portal declaring selfdoc and being a strictcli program,
// with the log every pipeline program appends to.
func pipelineRepo(t *testing.T) (*testsupport.Repo, string) {
	t.Helper()
	logPath := filepath.Join(t.TempDir(), "log")
	repo := testsupport.NewRepo(t)
	repo.Write(declarationsPath, fmt.Sprintf(pipelineDeclarations, logPath))
	repo.Write("package.json", strictcliPackage)
	repo.Write("cli.js", "// the program\n")
	repo.Write("selfdoc.json", "{}\n")
	repo.Commit("the project", declarationsPath, "package.json", "cli.js", "selfdoc.json")
	return repo, logPath
}

// fakeNode prints the help document, recording that it ran.
func fakeNode(t *testing.T, logPath, document string) {
	t.Helper()
	fakeProgram(t, "node", fmt.Sprintf("echo \"node $*\" >> %s\nprintf '%%s' '%s'\n", logPath, document))
}

// fakeSelfdoc writes a page and its hashes store on gen, and writes nothing
// on check, which is selfdoc's read-only verdict and declares no
// --auto-commit flag: given one, it refuses as selfdoc refuses an unknown
// flag.
func fakeSelfdoc(t *testing.T, logPath string) {
	t.Helper()
	fakeProgram(t, "selfdoc", fmt.Sprintf(`echo "selfdoc $*" >> %s
case "$1" in
gen) mkdir -p docs && echo generated > docs/index.md && echo recorded > docs/hashes.toml ;;
check) case " $* " in *" --no-auto-commit "*|*" --auto-commit "*) echo "error: unknown flag" >&2; exit 1 ;; esac ;;
esac
`, logPath))
}

func runPipeline(t *testing.T, repo *testsupport.Repo, dryRun bool) (release.PipelineResult, error) {
	t.Helper()
	var result release.PipelineResult
	_, err := mutating(t, dryRun, func(e *strictcli.Effects) error {
		ws, err := workspace.Load(repo.Dir)
		if err != nil {
			return err
		}
		r, err := git.Open(e, repo.Dir)
		if err != nil {
			return err
		}
		v, err := semver.Parse("0.5.0")
		if err != nil {
			return err
		}
		result, err = release.RunPipeline(e, release.PipelineInputs{
			Workspace: ws, Repo: r, Releasable: "portal", Representative: "root", Version: v,
			Hooks: release.HookContext{Version: "0.5.0"}, ProgramTimeout: time.Minute, DryRun: dryRun,
		})
		return err
	})
	return result, err
}

func TestThePrePipelineRunsInOrderAndCommitsWhatSelfdocWrote(t *testing.T) {
	hygiene.Isolate(t)
	repo, logPath := pipelineRepo(t)
	fakeNode(t, logPath, strings.ReplaceAll(helpDocument, "'", ""))
	fakeSelfdoc(t, logPath)
	before := repo.Head()
	result, err := runPipeline(t, repo, false)
	mustNotFail(t, err)
	want := []string{
		"pre-checks",
		"node cli.js help --json",
		"selfdoc gen --no-auto-commit --version-override 0.5.0",
		"selfdoc check --version-override 0.5.0",
	}
	if got := strings.Split(strings.TrimSpace(read(t, logPath)), "\n"); strings.Join(got, "|") != strings.Join(want, "|") {
		t.Fatalf("the pipeline ran:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
	// The selfdoc commit carries what selfdoc wrote, the hashes store gen
	// records included, with the trailer, and nothing the hook or the dump
	// wrote.
	head := repo.Head()
	if result.SelfdocCommit != head || repo.Git("rev-parse", "HEAD^") != before {
		t.Fatalf("the selfdoc commit is %q, HEAD is %s", result.SelfdocCommit, head)
	}
	if subject := repo.Git("log", "-1", "--format=%s"); subject != release.SelfdocCommitMessage {
		t.Errorf("the selfdoc commit's subject: %q", subject)
	}
	if body := repo.Git("log", "-1", "--format=%B"); !strings.Contains(body, "Autogenerated: true") {
		t.Errorf("the selfdoc commit carries no Autogenerated trailer:\n%s", body)
	}
	if files := repo.Git("show", "--name-only", "--format=", "HEAD"); files != "docs/hashes.toml\ndocs/index.md" {
		t.Errorf("the selfdoc commit carries:\n%s", files)
	}
	// The dump is the program's document with the release's version, every
	// other byte kept, left for the release commit to carry.
	dumped := read(t, repo.Path(".strictmetadata/.cli-schema/schema.json"))
	if dumped != strings.Replace(helpDocument, `"version": "0.0.0"`, `"version": "0.5.0"`, 1) {
		t.Errorf("the schema dump:\n%s", dumped)
	}
	if status := status(t, repo.Dir); !strings.Contains(status, "hook-output.txt") || !strings.Contains(status, ".strictmetadata/") {
		t.Errorf("the hook's and the dump's files are not left for the release commit:\n%s", status)
	}
}

func TestAPreviewOfThePipelineRecordsItsProgramsAndWritesNothing(t *testing.T) {
	hygiene.Isolate(t)
	repo, logPath := pipelineRepo(t)
	fakeNode(t, logPath, helpDocument)
	fakeSelfdoc(t, logPath)
	head := repo.Head()
	result, err := runPipeline(t, repo, true)
	mustNotFail(t, err)
	if _, err := os.Stat(logPath); !os.IsNotExist(err) {
		t.Errorf("a preview ran a program: %s", read(t, logPath))
	}
	if result.SelfdocCommit != "" || repo.Head() != head || status(t, repo.Dir) != "" {
		t.Errorf("a preview committed or wrote: %+v\n%s", result, status(t, repo.Dir))
	}
	if len(result.Dumps) != 1 || len(result.Selfdoc) != 1 {
		t.Errorf("the preview's pipeline: %+v", result)
	}
}

func TestSelfdocMissingIsRefusedUntilInstalled(t *testing.T) {
	hygiene.Isolate(t)
	repo, logPath := pipelineRepo(t)
	fakeNode(t, logPath, helpDocument)
	testsupport.PathOnly(t, "git", "bash", "node", "mkdir")
	_, err := runPipeline(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "selfdoc is not on PATH") || !strings.Contains(err.Error(), "install selfdoc") {
		t.Fatalf("a missing selfdoc was not refused: %v", err)
	}
	// The fix: selfdoc installed.
	fakeSelfdoc(t, logPath)
	_, err = runPipeline(t, repo, false)
	mustNotFail(t, err)
}

func TestAStrictcliWithoutHelpIsRefusedNamingTheUpgradeUntilUpgraded(t *testing.T) {
	hygiene.Isolate(t)
	repo, logPath := pipelineRepo(t)
	fakeSelfdoc(t, logPath)
	fakeProgram(t, "node", "echo \"error: unknown command 'help'\" >&2\nexit 1\n")
	_, err := runPipeline(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "predates `help --json`") || !strings.Contains(err.Error(), "npm install strictcli@latest") {
		t.Fatalf("a strictcli without help was not refused naming the upgrade: %v", err)
	}
	// The fix: a strictcli printing the help document.
	fakeNode(t, logPath, helpDocument)
	_, err = runPipeline(t, repo, false)
	mustNotFail(t, err)
}

func TestADumpThatIsNotAHelpDocumentIsRefused(t *testing.T) {
	hygiene.Isolate(t)
	repo, logPath := pipelineRepo(t)
	fakeSelfdoc(t, logPath)
	fakeNode(t, logPath, "not a document")
	_, err := runPipeline(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "is not a strictcli help document") {
		t.Fatalf("stdout that is not a help document was written: %v", err)
	}
	fakeNode(t, logPath, "{\n  \"schema_version\": 2\n}\n")
	_, err = runPipeline(t, repo, false)
	if err == nil || !strings.Contains(err.Error(), "no top-level \"version\" key") {
		t.Fatalf("a document without a version was written: %v", err)
	}
}

// goPortalDeclarations declare portal as a standalone Go project publishing
// nothing.
const goPortalDeclarations = `format_version = 1
repository_layout = "standalone"
release_branches = ["main"]
github_repository = "acme/portal"

[[releasables]]
name = "portal"
tag_format = "v{version}"
publish_mode = "none"

[[members]]
path = "."
name = "root"
releasable = "portal"
`

// TestTheSchemaDumpInTheCheckoutIgnoresTheWorkingTreesGoWork covers a Go
// strictcli program whose working tree holds an uncommitted go.work naming
// the working tree's own module. The release checkout lies below the working
// tree, so a Go command run there without the release's environment finds
// that go.work, whose module is not the checkout's, and lists no package:
// the schema dump's strictcli detection then cannot tell the entry point.
func TestTheSchemaDumpInTheCheckoutIgnoresTheWorkingTreesGoWork(t *testing.T) {
	hygiene.Isolate(t, hygiene.Preserve(hygiene.GoCache))
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no Go toolchain on PATH")
	}
	// The strictcli module is required but absent, and nothing is fetched.
	t.Setenv("GOPROXY", "off")
	// The session sets GOWORK; t.Setenv puts it back after the test.
	t.Setenv("GOWORK", "")
	repo := testsupport.NewRepo(t)
	repo.Write(declarationsPath, goPortalDeclarations)
	repo.Write("go.mod", "module example.com/portal\n\ngo 1.21\n\nrequire github.com/stricttools/strictcli/go v0.38.0\n")
	repo.Write("main.go", "package main\n\nimport \"fmt\"\n\nfunc main() { fmt.Print(`"+helpDocument+"`) }\n")
	repo.Write(".gitignore", "/go.work\n")
	repo.Commit("the project", declarationsPath, "go.mod", "main.go", ".gitignore")
	repo.Write("go.work", "go 1.21\n\nuse .\n")

	var result release.PipelineResult
	var checkoutPath string
	_, err := mutating(t, false, func(e *strictcli.Effects) error {
		live, err := git.Open(e, repo.Dir)
		if err != nil {
			return err
		}
		s, err := release.Enter(e, live, nil, release.EnterOptions{What: "The release", Rerun: "run the release again", OnWait: func(string) {}})
		if err != nil {
			return err
		}
		checkoutPath = s.Root
		ws, err := workspace.Load(s.Root)
		if err != nil {
			return errors.Join(err, s.Close())
		}
		r, err := git.Open(e, s.Root)
		if err != nil {
			return errors.Join(err, s.Close())
		}
		v, err := semver.Parse("0.5.0")
		if err != nil {
			return errors.Join(err, s.Close())
		}
		result, err = release.RunPipeline(e, release.PipelineInputs{
			Workspace: ws, Repo: r, Releasable: "portal", Representative: "root", Version: v,
			Hooks: release.HookContext{Version: "0.5.0"}, Environment: s.Checkout.Environment(),
			ProgramTimeout: time.Minute,
		})
		return errors.Join(err, s.Close())
	})
	mustNotFail(t, err)
	if len(result.Dumps) != 1 || result.Dumps[0].Program.EntryPoint != "." {
		t.Fatalf("the schema dumps: %+v", result.Dumps)
	}
	// The dump carries the version being released.
	want := strings.Replace(helpDocument, `"0.0.0"`, `"0.5.0"`, 1)
	if got := read(t, filepath.Join(checkoutPath, ".strictmetadata/.cli-schema/schema.json")); got != want {
		t.Fatalf("the dumped schema: %q", got)
	}
}
