"""Pre-push-check command that verifies CHANGELOG.md contains an entry for the current version before allowing a git push to proceed."""

import os
import re
import subprocess
import sys

from ..changelog import changes_dir_exists, get_changes_dir, list_versioned_files, parse_jsonl, read_unreleased, resolve_hashes
from ..changelog.validate import _is_autogenerated, _is_changelog_only_commit
from ..config import read_project_config
from ..git_util import get_commit_files, file_matches_project, filter_commits_for_project
from ..targets import TARGETS
from ..workspace import find_workspace_root, load_workspace

# Backward-compatible aliases (tests and internal callers use the underscore names)
_get_commit_files = get_commit_files
_file_matches_project = file_matches_project
_filter_commits_for_project = filter_commits_for_project


DEFAULT_RELEASE_BRANCHES = ["main", "master"]


def _get_release_branches(project_root):
    """Return the configured release-branch list.

    Reads ``release_branches`` from ``.rlsbl/config.json`` if present;
    falls back to ``["main", "master"]`` when the key is absent.

    Raises :class:`ValueError` if the key is present but malformed
    (empty list or non-list value). An empty list would silently
    disable the manual-release-push warning, which is almost never
    what the user wants; require explicit removal of the key instead.
    """
    config = read_project_config(project_root)
    if "release_branches" not in config:
        return list(DEFAULT_RELEASE_BRANCHES)
    branches = config["release_branches"]
    if not isinstance(branches, list):
        raise ValueError(
            "release_branches in .rlsbl/config.json must be a list of "
            f"branch names; got {type(branches).__name__}. "
            "Remove the key to use the default (main, master)."
        )
    if not branches:
        raise ValueError(
            "release_branches in .rlsbl/config.json is an empty list, "
            "which is not a valid value (it would disable the "
            "manual-release-push warning entirely). "
            "Remove the key to use the default (main, master), or list "
            "at least one branch name."
        )
    return [str(b) for b in branches]


def _warn_if_manual_release_push(stdin_lines, project_root):
    """Print a warning when a manual push targets a release branch.

    Fires only when ``RLSBL_RELEASE_PUSH`` is NOT set (i.e. the push didn't
    originate from ``rlsbl release run``/``rlsbl release undo``). Inspects the pushed
    refs and warns on any branch matching the configured release-branch
    list. Never blocks -- the warning is purely advisory.
    """
    if os.environ.get("RLSBL_RELEASE_PUSH") == "1":
        return
    if not stdin_lines:
        return

    release_branches = _get_release_branches(project_root)
    pushed_release_branches = []
    for line in stdin_lines:
        parts = line.split()
        if len(parts) < 4:
            continue
        local_ref = parts[0]
        if not local_ref.startswith("refs/heads/"):
            continue
        branch_name = local_ref[len("refs/heads/"):]
        if branch_name in release_branches:
            pushed_release_branches.append(branch_name)

    if not pushed_release_branches:
        return

    branches_str = ", ".join(sorted(set(pushed_release_branches)))
    print(
        f"WARNING: Manual push to release branch ({branches_str}) detected -- not via 'rlsbl release'.\n"
        "         This bypasses the release flow (no version bump, no tag, no GitHub Release).\n"
        "         If intentional, continue. Otherwise abort with Ctrl-C.",
        file=sys.stderr,
    )


def _detect_version(dir_path="."):
    """Detect version using registry adapters.

    Returns (version_string, registry_name) or (None, None) if undetectable.
    """
    for name in ("go", "npm", "pypi"):
        reg = TARGETS[name]
        if reg.check_project_exists(dir_path):
            return reg.read_version(dir_path), name
    return None, None


def _check_gitignore_guard(dir_path):
    """Check that rlsbl-managed files are not gitignored.

    Returns an error string listing gitignored paths, or None if all clear.
    """
    paths = [
        os.path.join(dir_path, ".rlsbl", "changes", "unreleased.jsonl"),
        os.path.join(dir_path, ".rlsbl", "changes", ".validated"),
        os.path.join(dir_path, "CHANGELOG.md"),
    ]
    gitignored = []
    for path in paths:
        try:
            result = subprocess.run(
                ["git", "check-ignore", "-q", path],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                gitignored.append(path)
            elif result.returncode == 128:
                # Not in a git repo -- skip gracefully
                return None
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            return None
    if gitignored:
        listed = ", ".join(gitignored)
        return f"rlsbl-managed files are gitignored (must be tracked): {listed}"
    return None



def _check_jsonl_changelog(dir_path, refs, pushed_commits=None):
    """Check JSONL changelog coverage for commits being pushed.

    Verifies that every commit in the push range exists in at least one
    unreleased.jsonl entry's commits list.

    When pushed_commits is provided, uses that set directly instead of
    calling _get_pushed_commits(refs). This allows callers (e.g. monorepo
    check) to pass a pre-filtered set of commits.

    Returns None on success, or an error message string on failure.
    """
    changes_dir = get_changes_dir(dir_path)
    entries = read_unreleased(changes_dir)

    # Also read all versioned JSONL files (e.g. 0.30.1.jsonl) so that
    # entries finalized by `rlsbl release` still provide coverage.
    for _version, filepath in list_versioned_files(changes_dir):
        entries.extend(parse_jsonl(filepath))

    # Get pushed commits from the refs, or use the provided set
    if pushed_commits is None:
        pushed_commits = _get_pushed_commits(refs)
    if pushed_commits is None:
        return None  # Could not determine pushed commits -- skip

    # Filter out autogenerated commits and changelog-only commits
    # (release infrastructure) -- these don't need JSONL coverage.
    commits_needing_coverage = {
        sha for sha in pushed_commits
        if not _is_autogenerated(sha) and not _is_changelog_only_commit(sha)
    }
    if not commits_needing_coverage:
        return None

    if not entries:
        return "no JSONL changelog entries found"

    # Collect all hashes from entries and resolve them
    all_hashes = []
    for entry in entries:
        all_hashes.extend(entry.commits)
    resolved = resolve_hashes(all_hashes)
    covered_shas = {full for full in resolved.values() if full is not None}

    missing = []
    for sha in commits_needing_coverage:
        if sha not in covered_shas:
            missing.append(sha[:12])

    if missing:
        return f"JSONL changelog missing coverage for {len(missing)} commit(s): {', '.join(missing[:5])}"

    return None


def _get_pushed_commits(refs):
    """Get the set of commit SHAs being pushed.

    Returns a set of full 40-char SHAs, or None on error.
    """
    zero_sha = "0" * 40
    commits = set()

    for local_sha, remote_sha in refs:
        if local_sha == zero_sha:
            continue  # Branch deletion

        try:
            if remote_sha == zero_sha:
                # New branch: commits not on any remote
                result = subprocess.run(
                    ["git", "log", "--format=%H", local_sha, "--not", "--remotes"],
                    capture_output=True, text=True, timeout=30,
                )
            else:
                result = subprocess.run(
                    ["git", "log", "--format=%H", f"{remote_sha}..{local_sha}"],
                    capture_output=True, text=True, timeout=30,
                )
            if result.returncode == 0:
                for line in result.stdout.strip().splitlines():
                    line = line.strip()
                    if line:
                        commits.add(line)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return None

    return commits


def _read_stdin_lines():
    """Read raw pre-push hook stdin lines.

    Returns a list of non-empty lines, or None if stdin is not readable
    or empty.
    """
    try:
        if sys.stdin.isatty():
            return None
        raw = sys.stdin.read().strip()
    except (AttributeError, OSError):
        return None

    if not raw:
        return None

    lines = [line for line in raw.splitlines() if line.strip()]
    return lines if lines else None


def _has_version_tag_push(stdin_lines):
    """Check whether any stdin line is pushing a version tag.

    Version tags match ``refs/tags/v*`` (single-project) or
    ``refs/tags/*@v*`` (monorepo scoped tags like ``mylib@v1.2.3``).

    Returns True if at least one line pushes a version tag.
    """
    pattern = re.compile(r"^refs/tags/(v\d|.+/v\d|[^/]+@v\d)")
    for line in stdin_lines:
        parts = line.split()
        if len(parts) >= 4:
            local_ref = parts[0]
            if pattern.match(local_ref):
                return True
    return False


def _parse_stdin_refs(stdin_lines=None):
    """Parse pre-push hook stdin to extract (local_sha, remote_sha) pairs.

    Each line is: <local ref> <local sha> <remote ref> <remote sha>

    When *stdin_lines* is provided (a list of raw lines), parses those
    directly instead of reading stdin.  When omitted, reads stdin via
    ``_read_stdin_lines()``.

    Returns a list of (local_sha, remote_sha) tuples, or None if the
    input is empty or unreadable.
    """
    if stdin_lines is None:
        stdin_lines = _read_stdin_lines()
    if stdin_lines is None:
        return None

    refs = []
    for line in stdin_lines:
        parts = line.split()
        if len(parts) >= 4:
            local_sha = parts[1]
            remote_sha = parts[3]
            refs.append((local_sha, remote_sha))
    return refs if refs else None


def _get_changed_files(refs):
    """Get the list of files changed across all pushed refs.

    Returns a set of file paths relative to the repo root.
    """
    zero_sha = "0" * 40
    changed = set()

    for local_sha, remote_sha in refs:
        if local_sha == zero_sha:
            # Branch being deleted -- nothing to check
            continue

        try:
            if remote_sha == zero_sha:
                # New branch: get files in commits not yet on any remote
                result = subprocess.run(
                    ["git", "log", "--name-only", "--pretty=format:", local_sha,
                     "--not", "--remotes"],
                    capture_output=True, text=True, timeout=30,
                )
            else:
                result = subprocess.run(
                    ["git", "diff", "--name-only", f"{remote_sha}..{local_sha}"],
                    capture_output=True, text=True, timeout=30,
                )
            if result.returncode == 0:
                for f in result.stdout.strip().splitlines():
                    f = f.strip()
                    if f:
                        changed.add(f)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            # If git fails, fall back to single-project behavior
            return None

    return changed



def _affected_projects(changed_files, projects):
    """Determine which projects are affected by the changed files.

    Returns a list of project dicts that have at least one changed file.
    """
    affected = []
    for proj in projects:
        for f in changed_files:
            if _file_matches_project(f, proj):
                affected.append(proj)
                break
    return affected


def _run_monorepo_check(workspace_root, projects, changed_files, refs=None):
    """Check changelogs for all affected monorepo projects.

    Filters pushed commits per project so that a commit touching only one
    project does not require changelog coverage in other projects.

    Returns exit code 0 on success, 1 if any project fails.
    """
    affected = _affected_projects(changed_files, projects)
    if not affected:
        sys.exit(0)

    if refs is None:
        sys.exit(0)

    # Get all pushed commits once, then filter per project
    all_pushed = _get_pushed_commits(refs)
    if all_pushed is None:
        sys.exit(0)

    failures = []
    for proj in affected:
        proj_dir = os.path.join(workspace_root, proj["path"])

        # Gitignore guard: block if rlsbl-managed files are gitignored
        gitignore_error = _check_gitignore_guard(proj_dir)
        if gitignore_error:
            failures.append((proj["name"], "?", gitignore_error))
            continue

        if not changes_dir_exists(proj_dir):
            continue  # JSONL not set up for this project -- skip

        # Filter to only commits that touch this project's files
        proj_commits = _filter_commits_for_project(all_pushed, proj)
        if not proj_commits:
            continue  # No commits relevant to this project

        error = _check_jsonl_changelog(proj_dir, refs, pushed_commits=proj_commits)

        if error:
            version, _ = _detect_version(proj_dir)
            failures.append((proj["name"], version or "?", error))

    if not failures:
        sys.exit(0)

    for name, version, error in failures:
        print(f"Error: {name}: {error}.", file=sys.stderr)
        print(f"Add JSONL changelog entries covering all pushed commits for {name}.",
              file=sys.stderr)
    sys.exit(1)


def run_cmd(registry, args, flags, project_root):
    """Check that CHANGELOG.md has an entry for the current project version.

    In monorepo mode (when a workspace root is detected), parses the pushed
    ref range from stdin to determine which projects are affected, then checks
    each affected project's changelog independently.

    In single-project mode, checks the current directory's changelog.

    Exits 1 if any changelog entry is missing; exits 0 silently on success.
    """
    root_str = str(project_root)

    # Read stdin once -- used for tag detection and ref parsing
    stdin_lines = _read_stdin_lines()

    # Optimisation: if the push includes a version tag, skip JSONL checks
    # entirely.  The release flow (rlsbl release) already validates
    # changelog coverage before pushing, so re-checking is redundant.
    if stdin_lines is not None and _has_version_tag_push(stdin_lines):
        sys.exit(0)

    # Warn if this looks like a manual push to a release branch (the env
    # marker is only set by `rlsbl release run` and `rlsbl release undo`). Non-blocking.
    _warn_if_manual_release_push(stdin_lines, project_root=project_root)

    # Detect monorepo context
    workspace_root = find_workspace_root(root_str)
    if workspace_root:
        refs = _parse_stdin_refs(stdin_lines)
        if refs is not None:
            changed_files = _get_changed_files(refs)
            if changed_files is not None:
                projects = load_workspace(workspace_root)
                _run_monorepo_check(workspace_root, projects, changed_files, refs=refs)
                # _run_monorepo_check always calls sys.exit, so this is unreachable

    # Single-project fallback

    # Gitignore guard: block push if rlsbl-managed files are gitignored
    gitignore_error = _check_gitignore_guard(root_str)
    if gitignore_error:
        print(f"Error: {gitignore_error}", file=sys.stderr)
        sys.exit(1)

    if not changes_dir_exists(root_str):
        # JSONL changelog not set up -- warn but don't block
        print("Warning: JSONL changelog not set up. Run 'rlsbl scaffold' to create .rlsbl/changes/", file=sys.stderr)
        sys.exit(0)

    # JSONL mode: check commit coverage
    refs = _parse_stdin_refs(stdin_lines)
    if refs is not None:
        error = _check_jsonl_changelog(root_str, refs)
        if error is None:
            sys.exit(0)
        print(f"Error: {error}.", file=sys.stderr)
        print("Add JSONL changelog entries covering all pushed commits.", file=sys.stderr)
        sys.exit(1)
    # No refs available (not called from pre-push hook) -- skip
    sys.exit(0)
