"""``rlsbl release backfill``: bring a repository's release archives into the fate model.

The engine is :mod:`rlsbl.release_backfill`; this module is the command around
it -- resolving which repository to work on, reading the operator's reviewed
descriptions, and running the observe/preview/apply skeleton so the plan a
``--dry-run`` prints is produced by exactly the code an apply then performs.

Two refusals fire only on an apply, after the whole plan has been rendered:
an unexplained tag, and a stash sitting in the repository.  A ``--dry-run``
shows both instead, because the point of the preview is to see what stands in
the way.
"""

import os
import sys

from ..preview_apply import Reconciler, reconcile
from ..release_backfill import (
    BackfillError,
    apply_item,
    build_plan,
    build_preview,
    commit_message,
    read_overrides,
    stash_error,
    unexplained_error,
)
from ..utils import commit_files


def run_cmd(flags, *, ctx):
    """Backfill this repository's release archives.

    Returns nothing; exits non-zero through :func:`sys.exit` on a refusal, so
    the failure is the process's, not a value a caller could ignore.
    """
    dry_run = flags.get("dry-run", False)
    auto_commit = flags.get("auto-commit", True)
    overrides_path = flags.get("overrides")

    # The whole repository, not one member: a workspace's releasables share one
    # tag namespace, and a pass that saw only one of them would report every
    # other releasable's tags as unexplained.
    repo = str(ctx.workspace_root or ctx.project_root)

    state = {}

    def _observe():
        overrides = read_overrides(overrides_path) if overrides_path else None
        plan = build_plan(repo, overrides=overrides)
        state["plan"] = plan
        if not dry_run:
            if plan.unexplained:
                raise BackfillError(unexplained_error(plan))
            if plan.stash:
                raise BackfillError(stash_error(plan))
        return build_preview(plan)

    def _apply(item):
        written = apply_item(item)
        if written:
            state.setdefault("written", []).append(written)
            print(f"{item.key}: wrote {os.path.relpath(written, repo)}")

    try:
        reconcile(
            Reconciler(observe=_observe, apply_item=_apply, show_keys=True),
            dry_run=dry_run,
        )
    except BackfillError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    plan = state["plan"]
    if dry_run:
        print(
            f"\nDry run: {len(plan.changed_versions)} archive(s) would be "
            f"written, {len(plan.unexplained)} unexplained tag(s) would refuse "
            f"the apply. Nothing was written."
        )
        return

    written = state.get("written") or []
    if not written:
        print(
            "\nNothing to do: every archive records a fate and carries every "
            "required field."
        )
        return

    relative = [os.path.relpath(p, repo) for p in written]
    print(f"\nWrote {len(relative)} archive(s).")
    if auto_commit:
        commit_files(
            commit_message(plan, relative), relative, autogenerated=True,
            cwd=repo,
        )
