"""Status command that displays a project summary including current version, branch, last tag, and changelog coverage for unreleased work."""

import json as _json
import os
import subprocess
import sys

from ..changelog import changes_dir_exists, get_changes_dir, read_unreleased, resolve_hashes
from ..changelog.resolve import _get_last_version_tag, _unreleased_range
from ..changelog.validate import filter_exempt_commits
from ..git_util import filter_commits_for_project
from ..targets import TARGETS, detect_targets
from ..errors import GitError
from ..utils import (
    extract_changelog_entry,
    get_current_branch,
    is_clean_tree,
    run,
)
from ..workspace import find_workspace_root, load_workspace, resolve_project


def _compare_versions(local, remote):
    """Compare two semver version strings.

    Returns "AHEAD" if local > remote, "BEHIND" if local < remote,
    "SAME" if equal, or "ERROR" if either version cannot be parsed.
    """
    import re
    pattern = re.compile(r"^(\d+)\.(\d+)\.(\d+)")
    m_local = pattern.match(local)
    m_remote = pattern.match(remote)
    if not m_local or not m_remote:
        return "ERROR"
    local_tuple = (int(m_local.group(1)), int(m_local.group(2)), int(m_local.group(3)))
    remote_tuple = (int(m_remote.group(1)), int(m_remote.group(2)), int(m_remote.group(3)))
    if local_tuple > remote_tuple:
        return "AHEAD"
    elif local_tuple < remote_tuple:
        return "BEHIND"
    return "SAME"


def _collect_status(registry, target_path=".", *, tag_glob=None, ctx, project=None, flags=None):
    """Collect status data as a dict.

    When tag_glob is set (monorepo mode), it is forwarded to
    _unreleased_range so coverage uses the correct scoped tag.

    When project is set (monorepo mode), unreleased commits are filtered
    to only those touching the project's files (by path prefix or watch
    globs), so the count reflects actual project-specific changes.

    When flags contains "registry": True, queries the package registry
    for the latest published version and computes drift.

    Returns None and prints an error if the project does not exist.
    """
    if flags is None:
        flags = {}
    reg = TARGETS[registry]

    if not reg.check_project_exists(target_path):
        print(f"No {registry} project found in current directory.", file=sys.stderr)
        sys.exit(1)

    version = reg.read_version(target_path)
    vars_dict = reg.template_vars(target_path, ctx)
    name = vars_dict.get("name") or "(unknown)"

    root_str = str(ctx.project_root)

    # Git branch
    try:
        branch = get_current_branch()
    except GitError:
        branch = "(detached HEAD)"
    except Exception as e:
        print(f"Warning: could not determine branch: {e}", file=sys.stderr)
        branch = None

    # Last tag
    try:
        tag = run("git", ["describe", "--tags", "--abbrev=0"])
    except Exception as e:
        print(f"Warning: could not determine last tag: {e}", file=sys.stderr)
        tag = None

    # Clean tree
    try:
        clean = is_clean_tree()
    except Exception as e:
        print(f"Warning: could not check working tree status: {e}", file=sys.stderr)
        clean = None

    # Changelog (generated from JSONL)
    changelog_path = os.path.join(root_str, "CHANGELOG.md")
    if os.path.exists(changelog_path):
        entry = extract_changelog_entry(changelog_path, version)
        changelog = bool(entry)
    else:
        changelog = None

    # Count unreleased commits since the last tag (excluding autogenerated
    # and changelog-only commits, consistent with validate's coverage check).
    # Computed independently of JSONL setup so the "commits ahead" warning
    # works for any project that has a previous tag.
    # Use the scoped tag (tag_glob-aware) so monorepo projects compare
    # against their own last release tag, not some other project's.
    commits_ahead = None
    unreleased_commits = None
    all_unreleased = None
    scoped_tag = _get_last_version_tag(tag_glob)
    try:
        range_spec = _unreleased_range(tag_glob=tag_glob)
        result = subprocess.run(
            ["git", "log", "--format=%H", range_spec],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            all_unreleased = [
                line.strip()
                for line in result.stdout.strip().splitlines()
                if line.strip()
            ]
            non_exempt, exempt_stats = filter_exempt_commits(all_unreleased)
            unreleased_commits = non_exempt
            # In monorepo mode, filter to commits touching this project's
            # files so the count reflects actual project-specific changes.
            if project and unreleased_commits:
                filtered = filter_commits_for_project(
                    set(unreleased_commits), project,
                )
                unreleased_commits = [
                    c for c in unreleased_commits if c in filtered
                ]
            # Only set commits_ahead when there's a prior tag — without
            # a tag, "ahead of nothing" is meaningless and we don't warn.
            if scoped_tag is not None:
                commits_ahead = len(unreleased_commits)
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass

    # JSONL changelog coverage (non-releasable projects don't use changelogs)
    is_non_releasable = project is not None and not project.is_releasable
    jsonl_coverage = "non-releasable -- no changelog" if is_non_releasable else "not set up"
    if not is_non_releasable and changes_dir_exists(target_path):
        try:
            changes_dir = get_changes_dir(target_path)
            entries = read_unreleased(changes_dir)
            # Count covered commits
            all_hashes = []
            for entry in entries:
                all_hashes.extend(entry.commits)
            resolved = resolve_hashes(all_hashes)
            covered_shas = {full for full in resolved.values() if full is not None}

            if unreleased_commits is not None and all_unreleased is not None:
                total = len(unreleased_commits)
                covered = sum(1 for c in unreleased_commits if c in covered_shas)
                exempted = exempt_stats.autogenerated + exempt_stats.changelog_only
                if exempted > 0:
                    jsonl_coverage = (
                        f"{covered}/{total} commits covered"
                        f" ({exempted} exempted)"
                    )
                else:
                    jsonl_coverage = f"{covered}/{total} commits covered"
            else:
                jsonl_coverage = f"{len(entries)} entries"
        except Exception as e:
            print(f"Warning: could not compute JSONL coverage: {e}", file=sys.stderr)

    # CI workflows
    ci = os.path.exists(os.path.join(root_str, ".github", "workflows", "ci.yml"))
    publish = os.path.exists(os.path.join(root_str, ".github", "workflows", "publish.yml")) or os.path.exists(
        os.path.join(root_str, ".github", "workflows", "workflow.yml")
    )

    # Registry version query (only when --registry flag is set)
    registry_version = None
    drift = None
    if flags.get("registry"):
        is_private = ctx.config.get("private", False)
        if is_private:
            drift = "PRIVATE"
        else:
            from ..registry import query_registry_version
            result = query_registry_version(name, registry)
            if result["status"] == "found":
                registry_version = result["version"]
                drift = _compare_versions(version, registry_version)
            elif result["status"] == "not_found":
                drift = "UNPUBLISHED"
            else:
                drift = "ERROR"

    return {
        "name": name,
        "version": version,
        "target": registry,
        "branch": branch,
        "tag": tag,
        "clean": clean,
        "changelog": changelog,
        "jsonl_coverage": jsonl_coverage,
        "commits_ahead": commits_ahead,
        "commits_ahead_tag": scoped_tag,
        "ci": ci,
        "publish": publish,
        "registry_version": registry_version,
        "drift": drift,
    }


def run_cmd(registry, args, flags, ctx):
    """Status command handler.

    Shows a quick 'where am I' summary: package info, git state, changelog, CI.
    With --json, outputs machine-readable JSON instead.
    """
    project_root = ctx.project_root
    root_str = str(project_root)

    # Detect monorepo context early so coverage uses scoped tags
    # and detect_targets can use releasable config inheritance
    monorepo_project = None
    monorepo_count = None
    releasable_info = None  # (releasable_name, tag_format, version) in explicit mode
    releasable_config_dir = None
    try:
        ws_root = find_workspace_root(root_str)
        if ws_root is not None:
            ws_projects = load_workspace(ws_root)
            monorepo_count = len(ws_projects)
            monorepo_project = resolve_project(ws_root, root_str)
            # Detect explicit releasable mode
            if monorepo_project:
                from ..workspace import is_explicit_mode, load_releasables, resolve_releasable_for_project, read_releasable_version
                if is_explicit_mode(ws_root):
                    releasables = load_releasables(ws_root, ws_projects)
                    rel = resolve_releasable_for_project(monorepo_project, releasables)
                    if rel:
                        try:
                            rel_ver = read_releasable_version(ws_root, rel.name)
                        except Exception:
                            rel_ver = None
                        releasable_info = (rel.name, rel.tag_format, rel_ver)
            if monorepo_project:
                from ..targets import resolve_releasable_config_dir
                releasable_config_dir = resolve_releasable_config_dir(monorepo_project, ws_root)
    except Exception as e:
        print(f"Warning: could not detect monorepo context: {e}", file=sys.stderr)

    # Build per-target path mapping from detect_targets
    target_entries = detect_targets(root_str, releasable_config_dir=releasable_config_dir)
    target_paths = {entry.name: entry.path for entry in target_entries}

    # Use per-target path for the primary registry
    primary_path = target_paths.get(registry, root_str)

    if releasable_info:
        # In explicit mode, use releasable's tag glob
        from ..commands.release.validate import _releasable_tag_glob
        tag_glob = _releasable_tag_glob(releasable_info[1], releasable_info[0])
    elif monorepo_project:
        target = TARGETS[registry]
        tag_glob = target.monorepo_tag_glob(monorepo_project["name"], path=monorepo_project["path"])
    else:
        tag_glob = None
    data = _collect_status(
        registry, primary_path, tag_glob=tag_glob,
        ctx=ctx, project=monorepo_project, flags=flags,
    )

    if flags.get("json"):
        print(_json.dumps(data, indent=2))
        return

    print(f"Package:   {data['name']}")

    # Show version info for all detected targets with per-target paths
    for entry_name, entry_path in target_paths.items():
        r_mod = TARGETS[entry_name]
        if r_mod.check_project_exists(entry_path):
            ver = r_mod.read_version(entry_path)
            file = r_mod.version_file() or "git tag"
            path_info = f", path={entry_path}" if entry_path != "." else ""
            print(f"Version:   {ver} ({entry_name}, {file}{path_info})")

    # Registry version (only when --registry flag is set)
    drift = data.get("drift")
    if drift is not None:
        reg_ver = data.get("registry_version")
        if drift == "PRIVATE":
            print("Registry:  (skipped, private project)")
        elif drift == "UNPUBLISHED":
            print(f"Registry:  (not found on {data['target']})")
        elif drift == "ERROR":
            print("Registry:  (query failed)")
        elif reg_ver is not None:
            print(f"Registry:  {reg_ver} ({data['target']}, {drift})")

    # Git info
    if data["branch"] is not None:
        print(f"Branch:    {data['branch']}")
    else:
        print("Branch:    (not a git repo)")

    # Last tag
    if data["tag"] is not None:
        print(f"Last tag:  {data['tag']}")
    else:
        print("Last tag:  (none)")

    # Clean tree
    if data["clean"] is not None:
        print(f"Clean:     {'yes' if data['clean'] else 'no'}")
    else:
        print("Clean:     (unknown)")

    # Changelog
    if data["changelog"] is None:
        print("Changelog: (not found)")
    elif data["changelog"]:
        print(f"Changelog: has entry for {data['version']}")
    else:
        print(f"Changelog: no entry for {data['version']}")

    # JSONL changelog coverage
    print(f"JSONL:     {data['jsonl_coverage']}")

    # CI workflows
    print(f"CI:        {'yes' if data['ci'] else 'missing'}")
    print(f"Publish:   {'yes' if data['publish'] else 'missing'}")

    # Commits-ahead warning: surfaces unreleased work that might otherwise
    # sit silently (e.g., post-release wrapper commits never released).
    # Only printed when there is a prior tag AND unreleased commits exist.
    commits_ahead = data.get("commits_ahead")
    commits_ahead_tag = data.get("commits_ahead_tag")
    if (
        commits_ahead is not None
        and commits_ahead > 0
        and commits_ahead_tag is not None
    ):
        plural = "commit" if commits_ahead == 1 else "commits"
        print(
            f"! {commits_ahead} {plural} ahead of {commits_ahead_tag} "
            f"— run `rlsbl release` or investigate"
        )

    # Monorepo awareness (detection already done above)
    if monorepo_count is not None:
        if releasable_info:
            rel_name, rel_tag_fmt, rel_ver = releasable_info
            print(f"Releasable: {rel_name}")
            if rel_ver:
                from ..commands.release.validate import _format_releasable_tag
                rel_tag = _format_releasable_tag(rel_tag_fmt, rel_name, rel_ver)
                print(f"Rel. version: {rel_ver}")
                print(f"Rel. tag:  {rel_tag}")
        elif monorepo_project is not None:
            target = TARGETS[registry]
            mono_tag = target.monorepo_tag_format(
                monorepo_project["name"], data["version"],
                path=monorepo_project["path"],
            )
            print(f"Mono tag:  {mono_tag}")
        print(f"Part of monorepo ({monorepo_count} project{'s' if monorepo_count != 1 else ''}). Run 'rlsbl monorepo status' for all.")
