"""Undo command that reverts a release.

The undo flow is plan-driven: an :class:`UndoPlan` is computed UPFRONT (for
both the latest-release path and the ``--version`` non-latest path) before
anything is mutated. The plan enumerates the release commits to revert,
companion tags to delete, whether a GitHub Release exists, and the registry
evidence verdict. ``--dry-run`` prints the plan and exits without touching
anything; a real run consumes the identical plan object.

The shape a release really leaves behind
----------------------------------------

Under main-as-candidate ordering the version-bump commit is the CANDIDATE: it
is pushed untagged, CI judges it, and only then is it tagged -- so the tag sits
at the BOTTOM of the release's commits and the finalization commits (changelog
rename, release-file archive, per-version .md) sit ABOVE it. A resumed release
moves the tag further still: after a fix-forward the verified commit is the tip
at resume time, several commits above the bump.

So the release commits are found from the LEDGER, not by walking down from the
tag: the archive for the version records the commit that was verified and
tagged (the anchor), the predecessor's archive records where the previous
release ended, and the release's own commits are the release-shaped commits
between those two. Walking down from the tag and stopping at the first
non-release-shaped subject collected ZERO commits on a resumed release, and
undo reported success with the version files still bumped.

What is reverted, and what is repaired
--------------------------------------

Reverted: the release's own commits at or below the anchor (always the version
bump; also the finalization commits on the older shape where they sat below the
tag). Repaired rather than reverted: the finalization ABOVE the anchor -- the
changelog is un-finalized and CHANGELOG.md regenerated, and the archived
release file is restored to ``unreleased.toml``. Foreign work in between (a
fix-forward that made CI green) is neither reverted nor repaired: it is
somebody's actual work and it stays.
"""

import dataclasses
import os
import re
import subprocess
import sys
import traceback
from types import SimpleNamespace

from ..changelog.files import get_changes_dir, unfinalize_version
from ..changelog.generate import generate_changelog
from ..errors import RlsblError
from ..evidence_gate import EvidenceKind, Verdict, run_evidence_gate, write_undo_audit
from ..member_context import resolve_member_context
from ..release_file import unfinalize_release_file
from ..targets import TARGETS
from ..utils import run, run_gh, check_gh_installed, check_gh_auth, get_push_timeout, get_current_branch, push_if_needed, is_clean_tree, working_tree_paths
from ..workspace import find_workspace_root, resolve_project

# Status constants for step results
OK = "OK"
FAILED = "FAILED"
SKIPPED = "SKIPPED"

# Release-commit message shapes. The version-bump commit is matched exactly
# against the expected message (tag string, or "<name>: release vX.Y.Z"); the
# remaining shapes are the chore commits the release flow emits after it. These
# are used to VALIDATE what the history walk finds, never as loop state.
_FINALIZE_CHANGELOG_RE = re.compile(r"^chore: finalize changelog for (.+)$")
_FINALIZE_RELEASE_FILE_RE = re.compile(r"^chore: finalize release file for (.+)$")
_CLEAN_STALE_RE = re.compile(r"^chore: clean \d+ stale batch exclusion\(s\) from config\.json$")
_REGEN_MD_RE = re.compile(r"^chore: regenerate (.+)\.md from archived release metadata$")
# The monorepo snapshot commit (autogenerated) is emitted pre-tag in the new
# step order, so it sits between the finalize commits and the tag and must be
# recognized (and reverted) by the release-commit walk.
_SNAPSHOT_RE = re.compile(r"^snapshot$")


@dataclasses.dataclass
class UndoPlan:
    """A fully-computed description of what an undo will do.

    Computed once, before any mutation. ``--dry-run`` prints it and exits;
    a real run executes it. ``revert_shas`` is a list of ``(sha, subject)``
    tuples ordered newest-first (the order they must be reverted in so each
    revert applies cleanly).
    """

    tag: str
    is_latest: bool
    version: str
    revert_shas: list
    companion_tags: list
    github_release_exists: bool
    gate_result: object
    project_path: str
    ws_root: object
    releasable_name: object
    monorepo_name: object
    monorepo_project_path: object
    audit_dir: str
    captured_finalize_changelog: bool = False
    captured_finalize_release_file: bool = False


def _resolve_undo_changelog_paths(project_path, ws_root, releasable_name):
    """Resolve the changes dir, regenerate callable, and git-add paths for
    changelog restoration -- releasable-aware.

    In explicit releasable mode the finalized JSONL lives in the releasable's
    changes dir and the canonical CHANGELOG.md in the releasable dir (plus
    the combined root CHANGELOG.md); otherwise everything is per-project.
    """
    if releasable_name and ws_root:
        from ..changelog.home import (
            generate_workspace_changelog,
            get_changelog_home,
            get_workspace_changelog_path,
        )
        from ..release_file import get_releases_dir
        from ..workspace import get_releasable_changes_dir, get_releasable_dir

        rel_dir = get_releasable_dir(str(ws_root), releasable_name)
        changes_dir = get_releasable_changes_dir(str(ws_root), releasable_name)
        canonical = get_changelog_home(project_path, releasable_dir=rel_dir)

        def regenerate():
            generate_changelog(
                project_path,
                changes_dir_override=changes_dir,
                changelog_output_path=canonical,
                releases_dir_override=get_releases_dir(
                    project_path, releasable_dir=rel_dir,
                ),
            )
            generate_workspace_changelog(str(ws_root))

        add_paths = [
            changes_dir, canonical, get_workspace_changelog_path(str(ws_root)),
        ]
        return changes_dir, regenerate, add_paths

    changes_dir = get_changes_dir(project_path)

    def regenerate():
        generate_changelog(project_path)

    add_paths = [changes_dir, os.path.join(project_path, "CHANGELOG.md")]
    return changes_dir, regenerate, add_paths


def _resolve_undo_releases_dir(project_path, ws_root, releasable_name):
    """Resolve the releases dir holding the release-file family -- releasable-aware.

    In explicit releasable mode the archived v{x}.toml (and unreleased.toml)
    live under the releasable's own releases dir; otherwise per-project.
    """
    from ..release_file import get_releases_dir

    rel_dir = None
    if releasable_name and ws_root:
        from ..workspace import get_releasable_dir
        rel_dir = get_releasable_dir(str(ws_root), releasable_name)
    return get_releases_dir(project_path, releasable_dir=rel_dir)


def _clear_release_state(project_path, ws_root):
    """Clear any in-progress release state after a successful rollback.

    A rolled-back release's preserved in-progress.json is meaningless and
    would hard-block the next `rlsbl release run`.
    """
    from .release.release_state import (
        clear_release_state,
        get_state_path,
        resolve_releasable_dir,
    )

    rel_dir = resolve_releasable_dir(project_path, ws_root) if ws_root else None
    clear_release_state(get_state_path(project_path, releasable_dir=rel_dir))


def _print_summary(results):
    """Print a summary table of step results. Only called when at least one step failed."""
    # Calculate column widths
    step_width = max(len(r[0]) for r in results)
    status_width = max(len(r[1]) for r in results)

    header = f"{'Step':<{step_width}}  {'Status':<{status_width}}  Remediation"
    print(f"\n{header}")
    print("-" * len(header))
    for step_name, status, remediation in results:
        print(f"{step_name:<{step_width}}  {status:<{status_width}}  {remediation}")


# ---------------------------------------------------------------------------
# Context + plan computation (no mutations)
# ---------------------------------------------------------------------------


def _resolve_context(ctx):
    """Detect the monorepo / releasable context shared by both undo paths."""
    monorepo_name = None
    monorepo_project_path = None
    releasable_name = None
    releasable_config_dir = None
    releasables = None
    start_path = str(ctx.project_root)
    ws_root = find_workspace_root(start_path)
    if ws_root:
        project = resolve_project(ws_root, start_path)
        if project is None:
            print("Error: current directory is inside a monorepo but not inside any project.", file=sys.stderr)
            sys.exit(1)
        monorepo_name = project["name"]
        monorepo_project_path = project["path"]
        from ..targets import resolve_releasable_config_dir
        releasable_config_dir = resolve_releasable_config_dir(project, ws_root)

        from ..workspace import load_releasables, load_workspace as _load_ws, resolve_releasable_for_project
        ws_projects = _load_ws(ws_root)
        releasables = load_releasables(ws_root, ws_projects)
        rel = resolve_releasable_for_project(project, releasables)
        if rel:
            releasable_name = rel.name

    project_path = os.path.join(ws_root, monorepo_project_path) if monorepo_name else str(ctx.project_root or ".")
    return SimpleNamespace(
        start_path=start_path,
        ws_root=ws_root,
        monorepo_name=monorepo_name,
        monorepo_project_path=monorepo_project_path,
        releasable_name=releasable_name,
        releasable_config_dir=releasable_config_dir,
        releasables=releasables,
        project_path=project_path,
    )


def _ledger_dir(uc):
    """The release archives for the project or releasable being undone."""
    return os.path.join(_audit_dir(uc), "releases")


def _find_latest_release(uc):
    """The version ``undo`` reverts, and its tag -- selected from the LEDGER.

    ``undo`` used to ask ``git describe --tags --abbrev=0`` which release was
    the latest, so a release whose tag had already been half-deleted was
    invisible to the command whose whole job is deleting it, and a hand-made
    tag could nominate a release that never happened. The archives answer
    which version is latest; the tag is then derived by translation
    (:func:`_build_tag_from_version`).

    Only the archive's EXISTENCE is read here, not its anchor: everything
    after this point -- the commit walk, the tag deletion, the revert --
    operates on the tag namespace, so undo is an observe-and-repair layer over
    tags in the same sense ``release reconcile`` is, and refusing to start
    because an anchor and a tag disagree would refuse exactly the repair the
    operator came for. The anchor IS read for the predecessor boundary, where
    it decides which commits belong to this release (see :func:`_build_plan`).

    Returns ``(version, tag)``, or exits when nothing is recorded.
    """
    from ..release_file import list_archived_versions

    versions = list_archived_versions(_ledger_dir(uc))
    if not versions:
        print("Error: no releases recorded. Nothing to undo.", file=sys.stderr)
        sys.exit(1)
    return versions[0], _build_tag_from_version(uc, versions[0])


def _version_and_msg(uc, tag):
    """Return (bare_version, expected_version_bump_message) for a tag."""
    if uc.releasable_name or uc.monorepo_name:
        from ..tag_glob import TagMode, parse_version_tag
        parsed = parse_version_tag(tag, mode=TagMode.PRERELEASE_INCLUSIVE)
        version_part = f"v{parsed.version}" if parsed else tag
        name = uc.releasable_name or uc.monorepo_name
        return version_part.lstrip("v"), f"{name}: release {version_part}"
    return tag.lstrip("v"), tag


def _build_tag_from_version(uc, version):
    """Build the release tag string for a given version (non-latest path)."""
    member = resolve_member_context(
        uc.start_path, releasable_config_dir=uc.releasable_config_dir,
    )
    entries = member.targets
    if not entries:
        return f"v{version}"
    target_obj = TARGETS[entries[0].name]
    if uc.releasable_name and uc.ws_root:
        from ..workspace import load_releasables as _lr, load_workspace as _lw
        _rels = _lr(uc.ws_root, _lw(uc.ws_root))
        _rel = next((r for r in _rels if r.name == uc.releasable_name), None)
        if _rel and _rel.effective_tag_format:
            from .release.validate import _format_releasable_tag
            return _format_releasable_tag(_rel.effective_tag_format, uc.releasable_name, version)
        return target_obj.monorepo_tag_format(uc.monorepo_name, version, path=uc.monorepo_project_path)
    if uc.monorepo_name:
        return target_obj.monorepo_tag_format(uc.monorepo_name, version, path=uc.monorepo_project_path)
    return target_obj.tag_format(version)


def _classify_release_commit(subject, expected_msg):
    """Return the shape of a release commit, or None if it is not one."""
    if subject == expected_msg:
        return "version_bump"
    if _FINALIZE_CHANGELOG_RE.match(subject):
        return "finalize_changelog"
    if _FINALIZE_RELEASE_FILE_RE.match(subject):
        return "finalize_release_file"
    if _CLEAN_STALE_RE.match(subject):
        return "clean_stale"
    if _REGEN_MD_RE.match(subject):
        return "regenerate_md"
    if _SNAPSHOT_RE.match(subject):
        return "snapshot"
    return None


def _die(*lines):
    """Print an operator-facing refusal and exit, having changed nothing."""
    for line in lines:
        print(line, file=sys.stderr)
    sys.exit(1)


def _release_anchor(uc, version, tag):
    """The commit the LEDGER records *version* as having shipped from.

    Read from the archive DIRECTLY rather than through
    :func:`rlsbl.ledger.read_entry`, which refuses when the version's tag and
    the anchor disagree. Undo is the repair path for exactly that state and is
    about to delete the tag, so a disagreement is reported as a warning and the
    ARCHIVE wins: it is written by the release flow, committed, and rewritten by
    rlsbl only through its own documented unlock paths, while a tag is a ref
    anyone can move.
    """
    from ..release_file import archived_release_path, read_release_file

    path = archived_release_path(_ledger_dir(uc), version)
    try:
        cfg = read_release_file(path)
    except Exception as exc:
        _die(
            f"Error: the release archive for {version} could not be read: {path}",
            f"  {exc}",
            "  Undo refused: nothing was destroyed. That archive is what records "
            "which commit the release shipped from.",
        )
    if getattr(cfg, "unanchorable", False) or not getattr(cfg, "candidate_sha", None):
        _die(
            f"Error: the release archive for {version} records no commit: {path}",
            "  Undo cannot find the release's own commits without it, and "
            "deleting the tag while",
            "  leaving the version files bumped is the half-undone state this "
            "command exists to avoid.",
            "  Backfill the anchor (scripts/backfill_release_anchors.py) and "
            "re-run.",
        )
    anchor = cfg.candidate_sha
    try:
        anchor = run("git", ["rev-parse", "--verify", f"{anchor}^{{commit}}"],
                     timeout=30).strip()
    except Exception:
        _die(
            f"Error: the commit the release archive records for {version} is not "
            f"in this repository: {cfg.candidate_sha}",
            f"  archive: {path}",
            "  Fetch the missing history (git fetch --unshallow) and re-run.",
        )

    tag_sha = ""
    try:
        tag_sha = run("git", ["rev-list", "-n", "1", tag], timeout=30).strip()
    except Exception:
        pass
    if tag_sha and tag_sha != anchor:
        print(
            f"warning: the tag {tag} points at {tag_sha[:12]} but the release "
            f"archive anchors {version} at {anchor[:12]}. The archive is what "
            f"undo reverts from; the tag is deleted either way.",
            file=sys.stderr,
        )
    return anchor


def _predecessor_anchor(uc, version):
    """The commit the release BELOW *version* shipped from, or None.

    The boundary survives that release's tag being deleted, because it is read
    from the archive rather than from ``git describe``.
    """
    from ..ledger import read_entry
    from ..release_file import list_archived_versions

    versions = list_archived_versions(_ledger_dir(uc))
    try:
        below = versions[versions.index(version) + 1:]
    except ValueError:
        below = []
    for prev in below:
        try:
            entry = read_entry(_ledger_dir(uc), prev, cwd=uc.project_path)
        except Exception as exc:
            # An unreadable predecessor archive (a tag that disagrees with its
            # anchor, say) only widens the search range, and the version-bump
            # subject is version-specific, so a wider range cannot match an
            # older release's bump. Said out loud rather than swallowed.
            print(
                f"warning: the release archive for {prev} could not be read "
                f"({exc}); looking further back for the boundary of "
                f"{version}'s commits.",
                file=sys.stderr,
            )
            continue
        if entry.anchored:
            return entry.candidate_sha
    return None


def _log_commits(range_spec):
    """``[(sha, subject)]`` for a git range, newest first."""
    try:
        out = run("git", ["log", "--format=%H%x1f%s", range_spec], timeout=60)
    except Exception:
        return None
    commits = []
    for line in out.splitlines():
        sha, _sep, subject = line.partition("\x1f")
        if sha.strip():
            commits.append((sha.strip(), subject.strip()))
    return commits


def _collect_release_commits(uc, version, tag, expected_msg):
    """The release's own commits, newest-first, located through the LEDGER.

    The search range is ``<predecessor's anchor>..<this release's anchor>``,
    both read from the archives. Inside it the version-bump commit is
    identified and everything release-shaped from the bump up to the anchor is
    collected; foreign commits in between (a fix-forward) are left alone, and
    the predecessor's own finalization commits are below the bump and so out of
    the collected set.

    Returns ``(revert_shas, captured_finalize_changelog,
    captured_finalize_release_file, anchor)``. Refuses -- loudly, before
    anything is destroyed -- when the version-bump commit cannot be found: a
    silent "no release commits found" is how undo used to delete a tag and a
    GitHub Release while leaving the version files bumped.
    """
    anchor = _release_anchor(uc, version, tag)
    predecessor = _predecessor_anchor(uc, version)
    range_spec = f"{predecessor}..{anchor}" if predecessor else anchor

    commits = _log_commits(range_spec)
    if commits is None:
        _die(
            f"Error: could not read the commits of release {tag}: "
            f"git log {range_spec} failed.",
            "  Undo refused: nothing was destroyed.",
        )

    bump_indexes = [
        i for i, (_sha, subject) in enumerate(commits)
        if _classify_release_commit(subject, expected_msg) == "version_bump"
    ]
    if not bump_indexes:
        anchor_subject = commits[0][1] if commits else "(no commits in range)"
        _die(
            f"Error: could not find the version-bump commit of {tag}.",
            f"  The release archive anchors {version} at {anchor[:12]} "
            f'("{anchor_subject}").',
            f"  Searched {range_spec} for a commit whose subject is exactly "
            f'"{expected_msg}"',
            f"  and found none among its {len(commits)} commit(s).",
            "  Undo refused: nothing was destroyed. Deleting the tag and the "
            "GitHub Release while",
            "  leaving the version files bumped is the half-undone state this "
            "command exists to avoid.",
            f"  Inspect the range (git log --oneline {range_spec}); if the "
            "release's commits were",
            "  rewritten, repair the ledger and the tags first "
            "(`rlsbl release reconcile`).",
        )
    if len(bump_indexes) > 1:
        shas = ", ".join(commits[i][0][:10] for i in bump_indexes)
        _die(
            f"Error: {len(bump_indexes)} commits in {range_spec} carry the "
            f'version-bump subject "{expected_msg}": {shas}.',
            "  Undo refused: nothing was destroyed. rlsbl will not guess which "
            "one shipped the release.",
        )

    # Everything release-shaped from the bump commit up to the anchor. The list
    # is newest-first, so the bump is the LAST element of the slice.
    span = commits[: bump_indexes[0] + 1]
    collected = []
    captured_cl = False
    captured_rf = False
    for sha, subject in span:
        shape = _classify_release_commit(subject, expected_msg)
        if shape is None:
            continue
        collected.append((sha, subject))
        if shape == "finalize_changelog":
            captured_cl = True
        elif shape == "finalize_release_file":
            captured_rf = True
    return collected, captured_cl, captured_rf, anchor


def _commit_paths(sha):
    """Every path a commit touches (empty for a merge, which shows no diff)."""
    try:
        out = run("git", ["show", "--pretty=format:", "--name-only", sha],
                  timeout=60)
    except Exception:
        return []
    return [p.strip() for p in out.splitlines() if p.strip()]


def _refuse_foreign_work_above_anchor(anchor, revert_shas, tag):
    """Refuse when work above the released commit endangers the revert.

    A commit between the anchor and HEAD is safe when either it is entirely
    rlsbl's own bookkeeping (the finalization commits, and anything else in the
    tool-owned set) or it touches none of the files the revert touches -- a
    post-release hook writing its own notes cannot conflict with reverting a
    version bump. Anything else is refused BEFORE the first deletion: reverting
    the bump underneath somebody's edit of the same file is how a rollback ends
    up mid-conflict, and by then the tag and the GitHub Release are gone.
    """
    from ..ownership import is_tool_owned_path

    if not revert_shas:
        return
    reverted_paths = set()
    for sha, _subject in revert_shas:
        reverted_paths.update(_commit_paths(sha))
    if not reverted_paths:
        return

    span = _log_commits(f"{anchor}..HEAD")
    if span is None:
        _die(
            f"Error: could not read the commits above the released commit "
            f"{anchor[:12]}.",
            "  Undo refused: nothing was destroyed.",
        )
    for sha, subject in span:
        paths = _commit_paths(sha)
        if paths and all(is_tool_owned_path(p) for p in paths):
            continue
        overlap = sorted(set(paths) & reverted_paths)
        if not overlap:
            continue
        _die(
            f"Error: cannot undo {tag} -- commit {sha[:12]} "
            f'("{subject}") sits above the released commit and changes files '
            f"the undo must revert:",
            *[f"    {p}" for p in overlap],
            "  Reverting the release underneath it would leave the rollback "
            "mid-conflict, with the",
            "  tag and the GitHub Release already deleted.",
            "  Undo refused: nothing was destroyed. Move that work aside (or "
            "revert it yourself)",
            "  and re-run.",
        )


def _plan_companion_tags(uc, tag, version):
    """Enumerate the version's non-primary refs to delete (releasable mode only).

    Asks the same ``expected_refs`` authority the release's tag step asked when
    it CREATED them, so undo cannot leave behind a ref the release made. A
    recorded alias is included: it addresses the version being undone.

    Degrades to an empty list on any failure, with the traceback printed. Undo
    is a repair path, and refusing to remove the primary tag because a member's
    config no longer resolves would strand the release entirely.
    """
    if not (uc.releasable_name and uc.ws_root):
        return []
    try:
        from ..commands.release.execute import release_ref_context
        from ..workspace import (
            get_releasable_dir,
            load_releasables,
            load_workspace,
            members_of,
        )

        ws_projects = load_workspace(uc.ws_root)
        member_paths = [p["path"] for p in members_of(uc.releasable_name, ws_projects)]
        rel_cfg_dir = get_releasable_dir(str(uc.ws_root), uc.releasable_name)

        rel = next(
            (r for r in load_releasables(uc.ws_root, ws_projects)
             if r.name == uc.releasable_name),
            None,
        )
        tag_fmt = rel.effective_tag_format if rel else None

        member = resolve_member_context(
            uc.start_path, releasable_config_dir=uc.releasable_config_dir,
        )
        entries = member.targets
        if not entries:
            return []
        expected = TARGETS[entries[0].name].expected_refs(
            version,
            release_ref_context(
                monorepo_root=uc.ws_root, git_root=uc.project_path,
                monorepo_name=uc.monorepo_name,
                monorepo_project_path=uc.monorepo_project_path,
                releasable_name=uc.releasable_name,
                releasable_tag_format=tag_fmt,
                member_package_paths=member_paths,
                releasable_config_dir=rel_cfg_dir,
            ),
        )
        return [t for t in expected.tags if t != tag]
    except Exception:
        traceback.print_exc()
        return []


def _gh_release_exists(tag, ctx):
    try:
        run_gh(["release", "view", tag], config=ctx.config)
        return True
    except Exception:
        return False


def _plan_gate(uc, ctx, version):
    """Run the registry evidence gate for the release (both paths).

    Resolution goes through MemberContext so targets/paths inherit
    releasable-level config. ``resolved_targets`` is available on the
    context for future per-pipeline evidence checks, but the evidence
    gate currently operates per-target-object only.
    """
    member = resolve_member_context(
        uc.start_path, releasable_config_dir=uc.releasable_config_dir,
    )
    try:
        entries = member.targets
    except Exception:
        entries = []
    target_objects = [TARGETS[e.name] for e in entries] if entries else []
    return run_evidence_gate(target_objects, uc.start_path, version, ctx)


def _audit_dir(uc):
    if uc.releasable_name and uc.ws_root:
        from ..workspace import get_releasable_dir
        return get_releasable_dir(str(uc.ws_root), uc.releasable_name)
    return os.path.join(uc.project_path, ".rlsbl")


def _build_plan(uc, flags, ctx):
    """Compute the full UndoPlan for either path, before any mutation."""
    version_flag = flags.get("version")
    is_latest = not version_flag
    if is_latest:
        version, tag = _find_latest_release(uc)
        _tag_version, expected_msg = _version_and_msg(uc, tag)
        revert_shas, cap_cl, cap_rf, anchor = _collect_release_commits(
            uc, version, tag, expected_msg,
        )
        # The one guard left, and it fires before anything is destroyed: work
        # above the released commit that touches what the revert touches.
        _refuse_foreign_work_above_anchor(anchor, revert_shas, tag)
    else:
        version = version_flag.lstrip("v")
        tag = _build_tag_from_version(uc, version)
        revert_shas, cap_cl, cap_rf = [], False, False

    return UndoPlan(
        tag=tag,
        is_latest=is_latest,
        version=version,
        revert_shas=revert_shas,
        companion_tags=_plan_companion_tags(uc, tag, version),
        github_release_exists=_gh_release_exists(tag, ctx),
        gate_result=_plan_gate(uc, ctx, version),
        project_path=uc.project_path,
        ws_root=uc.ws_root,
        releasable_name=uc.releasable_name,
        monorepo_name=uc.monorepo_name,
        monorepo_project_path=uc.monorepo_project_path,
        audit_dir=_audit_dir(uc),
        captured_finalize_changelog=cap_cl,
        captured_finalize_release_file=cap_rf,
    )


# ---------------------------------------------------------------------------
# Gate enforcement + plan display
# ---------------------------------------------------------------------------


def _enforce_gate(plan):
    """Refuse the undo when the evidence gate did not clear.

    PUBLISHED -> route to `release yank` / `release deprecate` (no bypass).
    INCONCLUSIVE / all-inconclusive -> hard block (same semantics as the
    non-latest path). Applies to BOTH the latest and non-latest paths.
    """
    gr = plan.gate_result
    if gr is None or gr.verdict == Verdict.CLEARED:
        return
    has_published = any(e.kind == EvidenceKind.PUBLISHED for e in gr.evidence)
    print(f"Error: cannot undo {plan.tag} -- {gr.reason}", file=sys.stderr)
    for e in gr.evidence:
        print(f"  {e.source}/{e.target}: {e.kind.value} -- {e.message}", file=sys.stderr)
    if has_published:
        v = plan.version
        print(
            "\nThis release appears to be PUBLISHED; undoing it is unsafe. "
            "Use a registry-aware removal instead:",
            file=sys.stderr,
        )
        print(f"  rlsbl release yank {v}       # remove it from registries", file=sys.stderr)
        print(f"  rlsbl release deprecate {v}  # mark it deprecated in place", file=sys.stderr)
    else:
        v = plan.version
        print(
            "\nVerify publication status manually and retry, or use "
            f"`rlsbl release yank {v}` / `rlsbl release deprecate {v}` "
            "if the version was published.",
            file=sys.stderr,
        )
    sys.exit(1)


def _print_plan(plan):
    """Print every write, deletion and commit the apply would perform.

    The plan used to name only the reverts, while the apply also wrote and
    committed the audit record, the restored changelog and the restored release
    file -- three commits a preview never mentioned. Steps whose commit is
    conditional say so rather than being left out.
    """
    kind = "latest" if plan.is_latest else "non-latest"
    print(f"Undo plan for {plan.tag} ({kind} release):")
    audit_path = os.path.join(plan.audit_dir, "undo-audit.json")
    print(f"  - Write {audit_path} and commit it "
          f'("chore: audit record for undo of {plan.tag}")')
    if plan.github_release_exists:
        print(f"  - Delete the GitHub Release for {plan.tag}")
    else:
        print(f"  - GitHub Release for {plan.tag}: none found (skip)")
    print(f"  - Delete git tag {plan.tag} (local + remote)")
    for ct in plan.companion_tags:
        print(f"  - Delete companion tag {ct} (local + remote)")
    if plan.revert_shas:
        print(f"  - Revert {len(plan.revert_shas)} release commit(s) (newest first):")
        for sha, subject in plan.revert_shas:
            print(f"      {sha[:10]}  {subject}")
    else:
        # Only the non-latest path gets here: the latest path refuses when it
        # cannot locate the release's version-bump commit.
        print("  - No commit revert (non-latest release -- history moved on)")
    print(f"  - Un-finalize {plan.version}.jsonl back into unreleased.jsonl "
          f"(merging anything added since) and regenerate CHANGELOG.md")
    print(f'  - Commit the restored changelog ("chore: restore changelog after '
          f'undo of {plan.tag}"), when it changed anything')
    if not plan.captured_finalize_release_file:
        print(f"  - Restore unreleased.toml from v{plan.version}.toml and commit "
              f'it ("chore: restore release file after undo of {plan.tag}"), '
              f"when it changed anything")
    print("  - Push the branch to the remote")
    print("  - Clear any in-progress release state")
    if plan.gate_result is not None:
        print("  Evidence:")
        for e in plan.gate_result.evidence:
            print(f"    {e.source}/{e.target}: {e.kind.value} -- {e.message}")


# ---------------------------------------------------------------------------
# Execution (consumes the plan)
# ---------------------------------------------------------------------------


def _delete_tag(tag, ctx, results):
    try:
        run("git", ["push", "--no-verify", "origin", f":{tag}"], timeout=get_push_timeout(ctx.config))
        results.append(("Delete remote tag", OK, "-"))
    except Exception:
        traceback.print_exc()
        results.append(("Delete remote tag", FAILED, f"git push origin :{tag}"))
    try:
        run("git", ["tag", "-d", tag])
        results.append(("Delete local tag", OK, "-"))
    except Exception:
        traceback.print_exc()
        results.append(("Delete local tag", FAILED, f"git tag -d {tag}"))


def _restore_changelog(plan, uc, results):
    """Reconcile CHANGELOG.md with the restored changelog state.

    Runs on BOTH paths. It first un-finalizes the version's JSONL (renaming
    ``{version}.jsonl`` back to ``unreleased.jsonl``; a no-op when a revert
    already restored it, and the repair when it didn't -- e.g. the non-latest
    path or a finalize commit outside the collected release commits). It then
    ALWAYS regenerates CHANGELOG.md so the generated file matches the restored
    ``unreleased.jsonl`` -- reverting the finalize commit restores the JSONL
    but leaves CHANGELOG.md showing the released version rather than
    ``## Unreleased``. Commits only when git reports an actual change, so it is
    idempotent.
    """
    try:
        changes_dir, regenerate_changelog, add_paths = _resolve_undo_changelog_paths(
            plan.project_path, uc.ws_root, plan.releasable_name,
        )
        unfinalize_version(changes_dir, plan.version)
        regenerate_changelog()
        if working_tree_paths(paths=add_paths):
            run("git", ["add", *add_paths])
            run("git", ["commit", "-m", f"chore: restore changelog after undo of {plan.tag}"])
            results.append(("Restore changelog", OK, "-"))
    except Exception:
        traceback.print_exc()
        results.append(("Restore changelog", FAILED, "manually restore the changes dir and regenerate CHANGELOG.md"))


def _restore_release_file(plan, uc, results):
    """Repair the release file when its finalize commit was NOT reverted.

    ``unfinalize_release_file`` is a no-op when the file is already restored
    (e.g. the finalize commit was reverted), so this is safe on both paths.
    """
    try:
        releases_dir = _resolve_undo_releases_dir(
            plan.project_path, uc.ws_root, plan.releasable_name,
        )
        changed = unfinalize_release_file(releases_dir, plan.version)
        if changed:
            run("git", ["add", releases_dir])
            run("git", ["commit", "-m", f"chore: restore release file after undo of {plan.tag}"])
            results.append(("Restore release file", OK, "-"))
    except Exception:
        traceback.print_exc()
        results.append(("Restore release file", FAILED, f"manually restore unreleased.toml from v{plan.version}.toml in the releases dir"))


def _stop_on_conflicted_revert(plan, sha, subject, done, results):
    """End the undo where a revert conflicted -- committing and pushing nothing.

    A failed revert used to record FAILED and CONTINUE, so the next ``git add``
    / ``git commit`` in the changelog restore CONCLUDED the in-progress revert:
    conflict markers and all, folded into "chore: restore changelog after undo
    of <tag>", and then pushed. The in-progress revert is aborted here instead,
    the operator is told exactly what already happened, and nothing further is
    written.
    """
    aborted = True
    try:
        run("git", ["revert", "--abort"], timeout=60)
    except Exception:
        aborted = False
    results.append(("Revert commits", FAILED, f"git revert {sha[:10]} (conflicted)"))

    print(
        f"\nError: git could not revert {sha[:12]} (\"{subject}\") -- a "
        f"conflict with later work is the usual cause -- so the undo of "
        f"{plan.tag} stopped there.",
        file=sys.stderr,
    )
    if aborted:
        print(
            "  The in-progress revert was aborted: the working tree is back "
            "where it was and nothing",
            file=sys.stderr,
        )
        print(
            "  was committed or pushed after it.",
            file=sys.stderr,
        )
    else:
        print(
            "  The in-progress revert could NOT be aborted -- resolve it by "
            "hand (git revert --abort)",
            file=sys.stderr,
        )
        print(
            "  before doing anything else. Nothing was committed or pushed "
            "after the conflict.",
            file=sys.stderr,
        )
    if done:
        print(
            f"  Already reverted (and left in place): "
            f"{', '.join(s[:10] for s in done)}",
            file=sys.stderr,
        )
    print(
        f"  Still in place: the release commit(s) of {plan.tag}, and the "
        f"finalized changelog for",
        file=sys.stderr,
    )
    print(
        f"  {plan.version}. The steps that DID complete are listed below and "
        f"were not rolled back.",
        file=sys.stderr,
    )
    print(
        "  Resolve the conflicting work above the release commit, then re-run "
        "`rlsbl release undo`.",
        file=sys.stderr,
    )
    _print_summary(results)
    sys.exit(1)


def _execute_plan(plan, uc, flags, ctx):
    """Execute a computed UndoPlan.

    Writes the audit journal BEFORE any deletion, on both the latest and the
    ``--version`` path (both reach here). If the journal cannot be written the
    undo is refused outright: no GitHub Release, tag or commit is touched.
    """
    results = []
    tag = plan.tag

    # 1. Audit journal -- written and committed BEFORE any destructive action
    #    on EVERY path, capturing the full plan (tag, target SHAs, evidence).
    #    This is a PRECONDITION, not a best-effort step: a failure here refuses
    #    the whole undo while everything it would destroy is still intact.
    #    Recording a FAILED row and destroying the release anyway produced the
    #    one outcome the journal exists to prevent -- a deleted GitHub Release,
    #    deleted tags and reverted commits with no record of any of it.
    try:
        audit_path = write_undo_audit(
            plan.audit_dir, plan.version, tag, plan.gate_result,
            operator_context={
                "is_latest": plan.is_latest,
                "revert_shas": [s for s, _ in plan.revert_shas],
                "companion_tags": list(plan.companion_tags),
                "github_release_deleted": plan.github_release_exists,
            },
        )
        run("git", ["add", audit_path])
        try:
            run("git", ["commit", "-m", f"chore: audit record for undo of {tag}"])
        except subprocess.CalledProcessError:
            pass  # nothing to commit (audit file unchanged) is acceptable
    except Exception as exc:
        expected = os.path.join(plan.audit_dir, "undo-audit.json")
        if not isinstance(exc, RlsblError):
            # An unexpected failure (a permission problem, a broken git) is a
            # bug rather than operator-facing text, so its trace is printed.
            traceback.print_exc()
        print(
            f"Error: the undo audit record for {tag} ({expected}) could not "
            f"be written: {exc}",
            file=sys.stderr,
        )
        print(
            f"Undo refused: nothing was destroyed. The GitHub Release, the "
            f"tag {tag} and the release commits are untouched. Repair or move "
            f"aside the audit file, then re-run.",
            file=sys.stderr,
        )
        sys.exit(1)
    results.append(("Write audit record", OK, "-"))

    # 2. Delete the GitHub Release
    if plan.github_release_exists:
        try:
            run_gh(["release", "delete", tag, "--yes"], config=ctx.config)
            results.append(("Delete GitHub Release", OK, "-"))
        except Exception:
            traceback.print_exc()
            results.append(("Delete GitHub Release", FAILED, f"gh release delete {tag} --yes"))
    else:
        results.append(("Delete GitHub Release", SKIPPED, "no GitHub Release found"))

    # 3. Delete the primary tag (remote + local)
    _delete_tag(tag, ctx, results)

    # 4. Delete companion tags (both paths)
    if plan.companion_tags:
        for ct in plan.companion_tags:
            try:
                run("git", ["push", "--no-verify", "origin", f":{ct}"], timeout=get_push_timeout(ctx.config))
            except Exception:
                pass  # remote tag may not exist
            try:
                run("git", ["tag", "-d", ct])
            except Exception:
                pass  # local tag may not exist
        results.append(("Delete companion tags", OK, f"deleted {len(plan.companion_tags)} companion tag(s)"))

    # 5. Revert release commits, newest-first, targeting the collected SHAs
    #    explicitly (never re-deriving from HEAD). Newest-first so each revert
    #    applies cleanly against the working tree.
    if plan.revert_shas:
        done = []
        for sha, subject in plan.revert_shas:
            try:
                run("git", ["revert", "--no-edit", sha])
            except Exception:
                traceback.print_exc()
                _stop_on_conflicted_revert(plan, sha, subject, done, results)
            done.append(sha)
        results.append(("Revert commits", OK, f"reverted {len(plan.revert_shas)} commit(s)"))

    # 6. Reconcile CHANGELOG.md with the restored JSONL (both paths; idempotent).
    #    Skipped only when the release has no changes dir at all.
    _restore_changelog(plan, uc, results)
    # Release-file repair: a no-op when the finalize-release-file commit was
    # reverted (its rename is already undone); the repair when it wasn't
    # (non-latest path, or a finalize commit outside the collected commits).
    if not plan.captured_finalize_release_file:
        _restore_release_file(plan, uc, results)

    # 7. Push the branch (revert + restore + audit commits) to remote
    # No second prompt: strictcli already confirmed this `consequential`
    # command before dispatch (--approve-consequential skips that one), and
    # asking again mid-rollback
    # left the remote holding the release this command had just undone
    # locally -- the half-undone state the rollback exists to avoid.
    try:
        branch = get_current_branch(cwd=plan.project_path)
        push_if_needed(branch, config=ctx.config, cwd=plan.project_path)
        results.append(("Push", OK, "-"))
    except Exception:
        traceback.print_exc()
        results.append(("Push", FAILED, "git push"))

    # 8. Summary + state cleanup
    has_failure = any(status == FAILED for _, status, _ in results)
    if not has_failure:
        # A rolled-back release's preserved in-progress.json is meaningless and
        # would hard-block the next `rlsbl release run`.
        _clear_release_state(plan.project_path, uc.ws_root)
        print(f"\nUndo of {tag} complete.")
    else:
        _print_summary(results)


def run_cmd(registry, args, flags, *, ctx):
    if not check_gh_installed():
        print("Error: gh CLI is not installed.", file=sys.stderr)
        sys.exit(1)
    if not check_gh_auth():
        print("Error: gh CLI is not authenticated.", file=sys.stderr)
        sys.exit(1)

    if not is_clean_tree():
        print("Error: working tree is not clean. Commit your changes first.", file=sys.stderr)
        sys.exit(1)

    uc = _resolve_context(ctx)
    plan = _build_plan(uc, flags, ctx)

    # Refuse the operation if the evidence gate did not clear (applies to both
    # paths, dry-run included -- a forbidden operation cannot be previewed).
    _enforce_gate(plan)

    _print_plan(plan)

    if flags.get("dry-run"):
        print("\n[dry-run] No changes were made.")
        return

    # The destructive-operation confirmation is the framework's: `release
    # undo` declares itself `consequential`, so strictcli prompts before
    # dispatch and --approve-consequential skips it.  A second prompt here
    # asked the same question in different words and had its own
    # non-interactive error text.

    _execute_plan(plan, uc, flags, ctx)
