package rewrite_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stricttools/strictcli/go/strictcli"
	"github.com/stricttools/strictspec/go/lifecycle"
	"github.com/stricttools/testisolation/go/hygiene"

	"github.com/stricttools/rlsbl/internal/releaserecord"
	"github.com/stricttools/rlsbl/internal/rewrite"
	"github.com/stricttools/rlsbl/internal/testsupport"
)

const standaloneDeclarations = `format_version = 1
repository_layout = "standalone"
release_branches = ["main"]

[[releasables]]
name = "portal"
tag_format = "v{version}"
publish_mode = "none"

[[members]]
path = "."
name = "root"
releasable = "portal"
`

const nextRelease = `format_version = 2
bump = "minor"
include = ["npm"]
exclude = []
description = "the next release"
`

var releaseFileRel = releaserecord.ReleaseFilePath("portal")

// portalProject is a committed standalone project named portal with an npm
// and a Go target.
func portalProject(t *testing.T) *testsupport.Repo {
	t.Helper()
	testsupport.FakeSafegit(t)
	repo := testsupport.NewRepo(t)
	files := map[string]string{
		".strictmetadata/releasables/releasables.toml": standaloneDeclarations,
		"package.json": "{\n  \"name\": \"portal\",\n  \"version\": \"0.1.0\",\n  \"bin\": {\"portal\": \"cli.js\"}\n}\n",
		"go.mod":       "module github.com/acme/portal\n\ngo 1.26\n",
		"VERSION":      "0.1.0\n",
		"main.go":      "package main\n\nimport _ \"github.com/acme/portal/internal/x\"\n\nfunc main() {}\n",
		releaseFileRel: nextRelease,
	}
	var rels []string
	for rel, content := range files {
		repo.Write(rel, content)
		rels = append(rels, rel)
	}
	repo.Commit("the project", rels...)
	return repo
}

// release records version 0.1.0 as released from HEAD.
func release(t *testing.T, repo *testsupport.Repo, fate string) {
	t.Helper()
	head := repo.Head()
	repo.Git("tag", "v0.1.0", head)
	body := nextRelease
	switch fate {
	case "recorded":
		body += "release_commit = \"" + head + "\"\n\n[released_trees]\n\".\" = \"" + repo.Git("rev-parse", "HEAD^{tree}") + "\"\n"
	case "unrecoverable":
		body += "unrecoverable = true\n"
	}
	rel := releaserecord.ArchiveDir("portal") + "/v0.1.0.toml"
	repo.CommitFile(rel, body, "archive 0.1.0")
}

func renameProject(t *testing.T, repo *testsupport.Repo, dryRun bool, from, to string) (strictcli.Result, error) {
	t.Helper()
	var runErr error
	res := run(t, dryRun, func(ctx *strictcli.Context) error {
		runErr = rewrite.RunProjectName(ctx, repo.Dir, from, to)
		return runErr
	})
	return res, runErr
}

func pendingOf(t *testing.T, root string) []lifecycle.Identity {
	t.Helper()
	rec, err := lifecycle.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	var out []lifecycle.Identity
	for _, id := range rec.Identities() {
		if id.Pending() {
			out = append(out, id)
		}
	}
	return out
}

func TestEveryIdentityIsRenamedAndRecordedAsPending(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	release(t, repo, "recorded")
	res, err := renameProject(t, repo, false, "portal", "gateway")
	if err != nil {
		t.Fatalf("%v\n%s", err, res.Stderr)
	}
	requireContains(t, read(t, repo.Path("package.json")), `"name": "gateway"`, `"bin": {"portal": "cli.js"}`)
	requireContains(t, read(t, repo.Path("go.mod")), "module github.com/acme/gateway")
	requireContains(t, read(t, repo.Path("main.go")), `"github.com/acme/gateway/internal/x"`)
	pending := pendingOf(t, repo.Dir)
	if len(pending) != 2 {
		t.Fatalf("%+v", pending)
	}
	byFacet := map[lifecycle.Facet]lifecycle.Identity{}
	for _, id := range pending {
		byFacet[id.Facet] = id
	}
	pkg, mod := byFacet[lifecycle.FacetPackageName], byFacet[lifecycle.FacetGoModulePath]
	if pkg.Value != "gateway" || pkg.Registry != "npm" || pkg.EffectiveVersion != "0.2.0" || strings.Join(pkg.TagPatterns, ",") != "v*" || pkg.Subject != "portal" {
		t.Errorf("package-name: %+v", pkg)
	}
	if mod.Value != "github.com/acme/gateway" || mod.Registry != "go" || mod.EffectiveVersion != "0.2.0" {
		t.Errorf("go-module-path: %+v", mod)
	}
	subjects := repo.Git("log", "--format=%s", "-2")
	if subjects != "rewrite: record the portal -> gateway pending identities\n"+rewrite.RenameCommitMessage("portal", "gateway") {
		t.Errorf("commits:\n%s", subjects)
	}
	if body := repo.Git("log", "-1", "--format=%B", "HEAD~1"); strings.Contains(body, "Autogenerated") {
		t.Errorf("the rename commit carries the trailer:\n%s", body)
	}
	if body := repo.Git("log", "-1", "--format=%B"); !strings.Contains(body, "Autogenerated: true") {
		t.Errorf("the record commit carries no trailer:\n%s", body)
	}
	renameCommit := repo.Git("rev-parse", "HEAD~1")
	requireContains(t, res.Stdout,
		"Renamed portal -> gateway in 3 files.",
		"Recorded the pending package-name gateway, effective 0.2.0.",
		"Remaining steps, in order:",
		"Decide the command name:",
		"Run `rlsbl scaffold`",
		"rlsbl changelog add --commits "+renameCommit[:12]+" --type breaking --description 'Renamed from portal to gateway: releases from 0.2.0 are published as gateway, and the Go module path is github.com/acme/gateway.'",
	)
	if out, _, code := testsupport.RunGit(t, repo.Dir, "status", "--porcelain"); code != 0 || out != "" {
		t.Errorf("the tree is not clean: %q", out)
	}

	// A second run finds everything renamed and recorded, and commits
	// nothing.
	head := repo.Head()
	res, err = renameProject(t, repo, false, "portal", "gateway")
	if err != nil {
		t.Fatalf("%v\n%s", err, res.Stderr)
	}
	requireContains(t, res.Stdout, "Already recorded: package-name gateway, effective 0.2.0.", "Renamed portal -> gateway in 0 files.")
	if repo.Head() != head {
		t.Error("a run with nothing to do committed")
	}
}

func TestTheDryRunWritesNothingAndReportsCounts(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	release(t, repo, "recorded")
	head := repo.Head()
	res, err := renameProject(t, repo, true, "portal", "gateway")
	if err != nil {
		t.Fatalf("%v\n%s", err, res.Stderr)
	}
	requireContains(t, res.Stdout,
		"package.json: rewrite: 1 occurrence in this npm manifest",
		"go.mod: rewrite: 1 occurrence in this go.mod",
		"(rename commit): commit: commit the 3 rewritten files as one commit",
		lifecycle.RecordFile+" go-module-path: record: pending go-module-path github.com/acme/gateway, effective 0.2.0",
		"(total): summary: 3 files to rewrite and 2 pending identities to record: portal -> gateway, effective 0.2.0",
		"<the rename commit>",
	)
	if repo.Head() != head || strings.Contains(read(t, repo.Path("package.json")), "gateway") {
		t.Error("the dry run wrote")
	}
	if _, err := os.Stat(repo.Path(lifecycle.RecordFile)); err == nil {
		t.Error("the dry run wrote the record")
	}
}

func TestANeverReleasedProjectTakesItsCurrentVersionAndRecordsNoModulePath(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	res, err := renameProject(t, repo, false, "portal", "gateway")
	if err != nil {
		t.Fatalf("%v\n%s", err, res.Stderr)
	}
	pending := pendingOf(t, repo.Dir)
	if len(pending) != 1 || pending[0].Facet != lifecycle.FacetPackageName || pending[0].EffectiveVersion != "0.1.0" {
		t.Fatalf("%+v", pending)
	}
	requireContains(t, res.Stdout, "Note: no pending go-module-path identity: this project has never released")
}

func TestARunAfterACrashBetweenTheCommitsRecordsWhatIsLeft(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	release(t, repo, "recorded")
	repo.Write("package.json", strings.Replace(read(t, repo.Path("package.json")), `"portal",`, `"gateway",`, 1))
	repo.Write("go.mod", "module github.com/acme/gateway\n\ngo 1.26\n")
	repo.Write("main.go", strings.Replace(read(t, repo.Path("main.go")), "acme/portal", "acme/gateway", 1))
	repo.Commit(rewrite.RenameCommitMessage("portal", "gateway"), "package.json", "go.mod", "main.go")
	renameCommit := repo.Head()
	res, err := renameProject(t, repo, false, "portal", "gateway")
	if err != nil {
		t.Fatalf("%v\n%s", err, res.Stderr)
	}
	if len(pendingOf(t, repo.Dir)) != 2 {
		t.Errorf("%+v", pendingOf(t, repo.Dir))
	}
	requireContains(t, res.Stdout, "--commits "+renameCommit[:12])
}

func TestAPendingIdentityOfAnotherValueRefusesUntilItIsRemoved(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	other := "format_version = 1\n\n[[identities]]\nsubject = \"portal\"\nfacet = \"package-name\"\nvalue = \"portal-next\"\nregistry = \"npm\"\ntag_patterns = [\"v*\"]\neffective_version = \"0.1.0\"\nreason = \"an earlier plan\"\n"
	repo.Write(lifecycle.ManifestFile, "owner = \"strictspec\"\n")
	repo.Write(lifecycle.RecordFile, other)
	repo.Commit("an earlier pending identity", lifecycle.ManifestFile, lifecycle.RecordFile)
	_, err := renameProject(t, repo, true, "portal", "gateway")
	if err == nil || !strings.Contains(err.Error(), `a pending package-name identity of portal, "portal-next" effective 0.1.0`) || !strings.Contains(err.Error(), "Delete that [[identities]] entry") {
		t.Fatalf("%v", err)
	}
	repo.CommitFile(lifecycle.RecordFile, "format_version = 1\n", "remove the earlier pending identity")
	if _, err := renameProject(t, repo, true, "portal", "gateway"); err != nil {
		t.Fatalf("the named fix did not clear the refusal: %v", err)
	}
}

func TestTheOpenIdentitysRegistryAndTagNamespaceAreKept(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	open := "format_version = 1\n\n[[identities]]\nsubject = \"portal\"\nfacet = \"package-name\"\nvalue = \"portal\"\nregistry = \"npm\"\ntag_patterns = [\"portal@v*\"]\nfrom = 2026-01-01\nreason = \"migrated\"\n"
	repo.Write(lifecycle.ManifestFile, "owner = \"strictspec\"\n")
	repo.Write(lifecycle.RecordFile, open)
	repo.Commit("the record", lifecycle.ManifestFile, lifecycle.RecordFile)
	if _, err := renameProject(t, repo, false, "portal", "gateway"); err != nil {
		t.Fatal(err)
	}
	pending := pendingOf(t, repo.Dir)
	if len(pending) != 1 || strings.Join(pending[0].TagPatterns, ",") != "portal@v*" {
		t.Errorf("%+v", pending)
	}
}

func TestRefusalsNameTheirFixAndTheFixClearsThem(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	refused := func(from, to string, wants ...string) {
		t.Helper()
		_, err := renameProject(t, repo, true, from, to)
		if err == nil {
			t.Fatalf("%s -> %s was not refused", from, to)
		}
		requireContains(t, err.Error(), wants...)
	}
	cleared := func(from, to string) {
		t.Helper()
		if _, err := renameProject(t, repo, true, from, to); err != nil {
			t.Fatalf("the fix did not clear the refusal: %v", err)
		}
	}

	refused("portal", "portal", "the same name")
	refused("portal", "_gateway", "is not a valid package name", "npm: an npm package name cannot start with an underscore")
	refused("gizmo", "gateway", `--from 'gizmo' does not match`, `package.json (package.json "name") declares "portal"`, "Run again with --from portal.")
	cleared("portal", "gateway")

	repo.Write("scratch.txt", "work in progress\n")
	refused("portal", "gateway", "uncommitted changes", "scratch.txt", "Commit them")
	repo.Commit("commit the work", "scratch.txt")
	cleared("portal", "gateway")

	repo.Git("rm", "-q", releaseFileRel)
	repo.Git("commit", "-q", "-m", "drop the release file")
	refused("portal", "gateway", "rlsbl release init")
	repo.CommitFile(releaseFileRel, nextRelease, "restore the release file")
	cleared("portal", "gateway")

	repo.CommitFile("go.mod", "module github.com/acme/portal-server\n\ngo 1.26\n", "a module path not ending in the name")
	refused("portal", "gateway", "whose last element 'portal-server' is not --from 'portal'", "rlsbl rewrite go-module-path --from-module github.com/acme/portal-server")
}

func TestAWorkspaceIsRefusedNamingRenameReleasable(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	repo.CommitFile(".strictmetadata/releasables/releasables.toml", strings.Replace(standaloneDeclarations, `"standalone"`, `"workspace"`, 1), "a workspace")
	_, err := renameProject(t, repo, true, "portal", "gateway")
	if err == nil || !strings.Contains(err.Error(), "rlsbl monorepo rename-releasable <old> <new>") {
		t.Fatalf("%v", err)
	}
}

func TestAnUnrecoverableLatestReleaseRefusesOnlyAGoTarget(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	release(t, repo, "unrecoverable")
	_, err := renameProject(t, repo, true, "portal", "gateway")
	if err == nil || !strings.Contains(err.Error(), "the latest release, 0.1.0, is marked unrecoverable") {
		t.Fatalf("%v", err)
	}
	repo.Git("rm", "-q", "go.mod", "main.go", "VERSION")
	repo.Git("commit", "-q", "-m", "no Go target")
	res, err := renameProject(t, repo, true, "portal", "gateway")
	if err != nil {
		t.Fatalf("%v\n%s", err, res.Stderr)
	}
	requireContains(t, res.Stdout, "effective 0.2.0")
}

func TestTheModeOfARenamedManifestIsKept(t *testing.T) {
	hygiene.Isolate(t)
	repo := portalProject(t)
	if err := os.Chmod(filepath.Join(repo.Dir, "package.json"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := renameProject(t, repo, false, "portal", "gateway"); err != nil {
		t.Fatal(err)
	}
	if info, err := os.Stat(filepath.Join(repo.Dir, "package.json")); err != nil || info.Mode().Perm() != 0o600 {
		t.Errorf("%v, %v", info.Mode(), err)
	}
}
