# strictspec document version gate (do not remove)
format_version = 2
# Version bump type: patch, minor, or major
bump = "patch"
# Short description of this release (required)
description = "Fix CI test failure when selfdoc not installed."
# Optional context explaining why these changes were made
context = ""
include = ["npm", "pypi"]
exclude = []
release_commit = "9e9974a239c0c4d850d9d33d132ecdae9fe057c8"
[released_trees]
"." = "07ed2f53d97cdb83b3830729417e709d6ad38aa5"
