# strictspec document version gate (do not remove)
format_version = 2
# Version bump type: patch, minor, or major
bump = "patch"
# Short description of this release (required)
description = "Pass RLSBL_DIST_DIR env var to custom_assets build commands."
include = ["npm", "pypi"]
exclude = []
release_commit = "2a2d71faf5447c18577dc60205dac26383581774"
[released_trees]
"." = "edd833fb467ccc2aa9b6655a61a2f451e0625775"
