# strictspec document version gate (do not remove)
format_version = 2
# Version bump type: patch, minor, or major
bump = "patch"
# Short description of this release (required)
description = "Pass RLSBL_DIST_DIR env var to custom_assets build commands."
include = ["npm", "pypi"]
exclude = []
release_commit = "4269c17304397a19fbb5bbf7e3d4b3e890b1ddb2"
[released_trees]
"." = "731065f80ff8e8b828d26dfaaac7627a9e46157c"
