#!/usr/bin/env python3
"""Fleet-wide migration sweep: archived release TOML ``bump = "hotfix"`` -> ``bump = "infra"``.

Background
----------
The ``hotfix`` bump type was renamed to ``infra``. Archived release-input TOMLs
(``.rlsbl/releases/v*.toml`` for standalone repos, ``.rlsbl-monorepo/releases/batch-*.toml``
for monorepo batch releases) still carry the legacy ``bump = "hotfix"`` value. The current
rlsbl hard-errors when its changelog generator reads a ``v{version}.toml`` with an unknown
bump value, so every affected standalone repo is stuck until migrated.

Per-repo flow (each repo isolated -- one repo's failure never aborts the sweep)
-------------------------------------------------------------------------------
  1. DIRTY CHECK: ``git status --porcelain`` non-empty -> SKIP (never commit over a
     concurrent session's work).
  2. Find archived TOMLs whose ``bump`` VALUE is ``"hotfix"`` (the comment line
     "# ... hotfix ..." is left untouched). None -> skip silently.
  3. For each: record file mode, chmod u+w if needed, surgically replace only the
     ``bump = "hotfix"`` value line, restore the original mode.
  4. REGENERATE (standalone repos only): ``rlsbl changelog generate --no-auto-commit``.
     Monorepo batch archives do NOT feed any changelog (the generator only reads
     ``v{version}.toml``), so no regeneration is performed for them.
  5. DIFF GUARD: the working-tree delta may contain ONLY the allowed lines
     (bump value swap; ``### Hotfix`` -> ``### Infrastructure``; and the benign
     ``## Unreleased`` / "No user-facing changes." placeholder the generator adds when a
     previously-stale CHANGELOG is regenerated). ANY other change -> HARD STOP: revert
     nothing, leave the repo dirty, report loudly, continue with other repos.
  6. SCAFFOLD (standalone repos only): ``rlsbl scaffold --no-auto-commit``. Monorepo
     roots refuse scaffold ("use rlsbl monorepo sync instead"), so it is skipped there.
     A conflict marker in any changed file -> HARD STOP + report (do not guess).
  7. COMMIT everything via ``rlsbl commit`` (adds an ``Autogenerated: true`` trailer,
     exempting the commit from changelog coverage checks).
  8. VERIFY: zero archived hotfix bumps remain; run ``rlsbl check --tag changelog``
     (informational -- pre-existing coverage debt is not a sweep failure).

Usage
-----
  sweep_infra_rename.py [--root DIR]            # report the plan only (no changes)
  sweep_infra_rename.py [--root DIR] --apply    # execute the sweep
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

BUMP_RE = re.compile(r'^(\s*)bump = "hotfix"\s*$', re.MULTILINE)

# Lines the diff guard permits (compared after rstrip).
ALLOWED_DEL = {'bump = "hotfix"', '### Hotfix'}
ALLOWED_ADD = {
    'bump = "infra"',
    '### Infrastructure',
    '## Unreleased',
    '- No user-facing changes.',
    '',
}

COMMIT_MSG_STANDALONE = "chore: migrate archived bump hotfix->infra + rescaffold"
COMMIT_MSG_MONOREPO = "chore: migrate archived bump hotfix->infra (batch archive)"


class RepoStop(Exception):
    """A recoverable, per-repo hard stop. The repo is left dirty and reported."""


def run(cmd: list[str], cwd: str, check: bool = True) -> subprocess.CompletedProcess:
    proc = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True,
    )
    if check and proc.returncode != 0:
        raise RepoStop(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )
    return proc


def find_repo_root(path: str) -> str | None:
    """Walk up from *path* until a directory containing .git is found."""
    cur = os.path.abspath(path)
    if os.path.isfile(cur):
        cur = os.path.dirname(cur)
    while True:
        if os.path.isdir(os.path.join(cur, ".git")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            return None
        cur = parent


def discover_tomls(root: str) -> list[str]:
    """Return absolute paths of archived release TOMLs with a hotfix bump VALUE."""
    proc = subprocess.run(
        [
            "grep", "-rl", "--include=*.toml",
            "--exclude-dir=node_modules", "--exclude-dir=.git",
            'bump = "hotfix"', root,
        ],
        capture_output=True, text=True,
    )
    hits = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        # Only archived release-input files under an rlsbl release directory.
        if "/releases/" not in line:
            continue
        if "/.rlsbl/releases/" not in line and "/.rlsbl-monorepo/" not in line:
            continue
        # Confirm the match is the bump VALUE, not the comment/help line.
        try:
            text = open(line, "r", encoding="utf-8").read()
        except OSError:
            continue
        if BUMP_RE.search(text):
            hits.append(os.path.abspath(line))
    return hits


def group_by_repo(tomls: list[str]) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {}
    for t in tomls:
        rr = find_repo_root(t)
        if rr is None:
            continue
        groups.setdefault(rr, []).append(t)
    return groups


def repo_is_monorepo(repo_root: str) -> bool:
    return os.path.isdir(os.path.join(repo_root, ".rlsbl-monorepo"))


def toml_feeds_changelog(rel_path: str) -> bool:
    """A v{version}.toml (standalone or releasable) feeds a generated CHANGELOG.

    Monorepo batch-*.toml archives do not (the generator only reads v{version}.toml).
    """
    base = os.path.basename(rel_path)
    return base.startswith("v") and base.endswith(".toml")


def git_status_porcelain(repo_root: str) -> str:
    return run(["git", "status", "--porcelain"], repo_root).stdout


def edit_toml(path: str) -> int:
    """Surgically replace the bump value line. Returns number of replacements."""
    orig_mode = os.stat(path).st_mode
    writable = orig_mode | 0o200
    if orig_mode != writable:
        os.chmod(path, writable)
    try:
        text = open(path, "r", encoding="utf-8").read()
        new_text, n = BUMP_RE.subn(r'\1bump = "infra"', text)
        if n == 0:
            raise RepoStop(f"no bump value line replaced in {path}")
        if new_text != text:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
    finally:
        os.chmod(path, orig_mode)
    return n


def is_allowed_changed_file(rel: str, edited_rel: set[str]) -> bool:
    if rel in edited_rel:
        return True
    if rel == "CHANGELOG.md":
        return True
    if rel.startswith(".rlsbl/changes/") and rel.endswith(".md"):
        return True
    return False


def diff_guard(repo_root: str, edited_rel: set[str], allow_changelog: bool) -> list[str]:
    """Return a list of violation strings (empty list = clean)."""
    violations: list[str] = []

    for line in git_status_porcelain(repo_root).splitlines():
        if line.startswith("??"):
            violations.append(f"untracked file appeared: {line[3:]}")

    diff = run(["git", "diff"], repo_root).stdout
    cur: str | None = None
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            cur = line[6:]
            if not allow_changelog:
                if cur not in edited_rel:
                    violations.append(f"unexpected changed file (monorepo, no regen): {cur}")
            elif not is_allowed_changed_file(cur, edited_rel):
                violations.append(f"unexpected changed file: {cur}")
            continue
        if line.startswith("--- ") or line.startswith("+++ "):
            continue
        if line.startswith("+"):
            content = line[1:].rstrip()
            if content not in ALLOWED_ADD:
                violations.append(f"{cur}: unexpected added line: {line[1:]!r}")
        elif line.startswith("-"):
            content = line[1:].rstrip()
            if content not in ALLOWED_DEL:
                violations.append(f"{cur}: unexpected removed line: {line[1:]!r}")
    return violations


def check_conflict_markers(repo_root: str, paths: list[str]) -> list[str]:
    bad = []
    for rel in paths:
        ap = os.path.join(repo_root, rel)
        if not os.path.isfile(ap):
            continue
        try:
            text = open(ap, "r", encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        if "<<<<<<<" in text or ">>>>>>>" in text:
            bad.append(rel)
    return bad


def changed_paths(repo_root: str) -> list[str]:
    out = run(["git", "status", "--porcelain", "-z"], repo_root).stdout
    paths = []
    for tok in out.split("\0"):
        if not tok:
            continue
        # Format: "XY <path>" (rename "XY <old>\0<new>" is not expected here).
        path = tok[3:] if len(tok) > 3 else tok
        paths.append(path)
    return paths


def process_repo(repo_root: str, tomls: list[str], apply: bool, results: dict) -> None:
    name = os.path.basename(repo_root)
    is_mono = repo_is_monorepo(repo_root)
    rel_tomls = [os.path.relpath(t, repo_root) for t in tomls]
    feeds = [r for r in rel_tomls if toml_feeds_changelog(r)]
    # Standalone repos regenerate the changelog; monorepo batch archives do not.
    do_regen = (not is_mono) and bool(feeds)
    do_scaffold = not is_mono  # scaffold refuses monorepo workspace roots

    if not apply:
        results["plan"].append({
            "repo": name,
            "type": "monorepo" if is_mono else "standalone",
            "tomls": rel_tomls,
            "regen": do_regen,
            "scaffold": do_scaffold,
        })
        return

    # 1. dirty check
    if git_status_porcelain(repo_root).strip():
        results["skipped_dirty"].append(name)
        print(f"[{name}] SKIP: working tree dirty (concurrent session?)")
        return

    try:
        # 3. edit TOMLs
        total = 0
        for t in tomls:
            total += edit_toml(t)

        # 4. regenerate (standalone only)
        if do_regen:
            run(["rlsbl", "changelog", "generate", "--no-auto-commit"], repo_root)

        # 5. diff guard
        violations = diff_guard(repo_root, set(rel_tomls), allow_changelog=do_regen)
        if violations:
            raise RepoStop(
                "diff guard failed -- unexpected changes; leaving repo dirty:\n  - "
                + "\n  - ".join(violations)
            )

        # 6. scaffold (standalone only)
        if do_scaffold:
            run(["rlsbl", "scaffold", "--no-auto-commit"], repo_root)
            bad = check_conflict_markers(repo_root, changed_paths(repo_root))
            if bad:
                raise RepoStop(
                    "scaffold produced conflict markers (needs manual resolution): "
                    + ", ".join(bad)
                )

        # 7. commit
        paths = changed_paths(repo_root)
        if not paths:
            raise RepoStop("nothing to commit after edits (unexpected)")
        msg = COMMIT_MSG_STANDALONE if do_scaffold else COMMIT_MSG_MONOREPO
        run(["rlsbl", "commit", "-m", msg, "--", *paths], repo_root)

        # 8. verify
        remaining = discover_tomls(repo_root)
        remaining = [r for r in remaining if find_repo_root(r) == repo_root]
        chk = run(["rlsbl", "check", "--tag", "changelog"], repo_root, check=False)
        chk_ok = chk.returncode == 0

        results["migrated"].append({
            "repo": name,
            "tomls": len(tomls),
            "type": "monorepo" if is_mono else "standalone",
            "hotfix_remaining": len(remaining),
            "changelog_check": "pass" if chk_ok else "fail (see note)",
        })
        status = "OK" if not remaining else f"WARNING {len(remaining)} hotfix bumps REMAIN"
        print(f"[{name}] migrated {total} bump line(s) across {len(tomls)} file(s); "
              f"changelog check {'pass' if chk_ok else 'fail'}; {status}")
    except RepoStop as exc:
        results["stopped"].append({"repo": name, "reason": str(exc)})
        print(f"[{name}] STOPPED: {exc}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", required=False, default="/home/m/Projects",
                    help="Fleet root directory to sweep (default: /home/m/Projects)")
    ap.add_argument("--apply", action="store_true",
                    help="Execute the sweep. Without this flag, only the plan is reported.")
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    tomls = discover_tomls(root)
    groups = group_by_repo(tomls)

    results = {
        "plan": [],
        "migrated": [],
        "skipped_dirty": [],
        "stopped": [],
    }

    print(f"Root: {root}")
    print(f"Affected archived TOMLs: {len(tomls)} across {len(groups)} repo(s)")
    print(f"Mode: {'APPLY' if args.apply else 'REPORT (no changes)'}\n")

    for repo_root in sorted(groups):
        process_repo(repo_root, groups[repo_root], args.apply, results)

    print("\n===== SUMMARY =====")
    if not args.apply:
        for p in results["plan"]:
            print(f"  {p['repo']:20s} {p['type']:10s} tomls={len(p['tomls'])} "
                  f"regen={p['regen']} scaffold={p['scaffold']}")
            for t in p["tomls"]:
                print(f"      - {t}")
        return 0

    print(f"Migrated: {len(results['migrated'])} repo(s)")
    for m in results["migrated"]:
        print(f"  {m['repo']:20s} {m['type']:10s} tomls={m['tomls']} "
              f"remaining={m['hotfix_remaining']} check={m['changelog_check']}")
    print(f"Skipped (dirty): {len(results['skipped_dirty'])}")
    for s in results["skipped_dirty"]:
        print(f"  {s}")
    print(f"Stopped (needs review): {len(results['stopped'])}")
    for s in results["stopped"]:
        print(f"  {s['repo']}:\n    {s['reason'].splitlines()[0]}")

    return 1 if results["stopped"] else 0


if __name__ == "__main__":
    sys.exit(main())
