package scaffold

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/stricttools/strictcli/go/strictcli"

	"github.com/stricttools/rlsbl/internal/git"
)

// Scaffold installs two git hooks where git runs them: pre-push, which runs
// `rlsbl failing-checks --hook pre-push` for a push to a branch, and
// post-rewrite, which remaps the changelog's commit ids after an amend or a
// rebase. A hook already installed is replaced only when its content is one
// rlsbl shipped; any other content is refused, because a hook that does not
// run rlsbl's checks lets a push through unchecked.

// PrePushHook is the pre-push hook. git feeds it one line per ref pushed;
// only branch pushes (refs/heads/*) are checked, because refs/tags/* and
// refs/backups/* are written by rlsbl's release and safegit, which own them.
const PrePushHook = `#!/usr/bin/env bash
# rlsbl pre-push hook. Enforces on refs/heads/* only; refs/tags/* and
# refs/backups/* are tool-owned namespaces and exit 0.
stdin_data="$(cat)"
enforce=0
while read -r _local_ref _local_sha remote_ref _remote_sha; do
  case "$remote_ref" in
    refs/heads/*) enforce=1 ;;
  esac
done <<< "$stdin_data"
if [ "$enforce" -eq 0 ]; then
  exit 0
fi
export RLSBL_PUSH_STDIN="$stdin_data"
exec rlsbl failing-checks --hook pre-push
`

// PostRewriteHook is the post-rewrite hook: git's old and new commit ids on
// stdin, piped to the changelog remap.
const PostRewriteHook = "#!/usr/bin/env bash\nexec rlsbl changelog remap --stdin\n"

// The pre-push hooks earlier rlsbl versions installed, word for word, so an
// unmodified one is recognized and upgraded.
var shippedPrePushHooks = []string{
	"#!/usr/bin/env bash\n# Pre-push hook: verify CHANGELOG.md has an entry for the current version.\n# Install: cp scripts/pre-push-hook.sh .git/hooks/pre-push && chmod +x .git/hooks/pre-push\n\nset -euo pipefail\n\n# Detect project type and extract version\nif [ -f package.json ]; then\n  VERSION=$(node -e \"console.log(require('./package.json').version)\" 2>/dev/null) || exit 0\nelif [ -f pyproject.toml ]; then\n  VERSION=$(grep -m1 '^version' pyproject.toml | sed 's/.*\"\\(.*\\)\".*/\\1/') || exit 0\nelse\n  exit 0\nfi\n\nif [ -z \"$VERSION\" ]; then\n  exit 0\nfi\n\n# Check CHANGELOG.md has an entry for this version\nif [ ! -f CHANGELOG.md ]; then\n  echo \"Warning: CHANGELOG.md not found.\"\n  exit 0\nfi\n\nif ! grep -q \"^## $VERSION\" CHANGELOG.md; then\n  echo \"Error: CHANGELOG.md has no entry for version $VERSION.\"\n  echo \"Add a '## $VERSION' section before pushing.\"\n  exit 1\nfi\n\n# Check scaffolding freshness\nif [ -f .rlsbl/version ]; then\n  SCAFFOLD_VER=$(cat .rlsbl/version | tr -d '[:space:]')\n  if command -v rlsbl &>/dev/null; then\n    CURRENT_VER=$(rlsbl --version 2>/dev/null | tr -d '[:space:]')\n    if [ -n \"$CURRENT_VER\" ] && [ \"$SCAFFOLD_VER\" != \"$CURRENT_VER\" ]; then\n      echo \"Warning: scaffolding was generated by rlsbl $SCAFFOLD_VER but you have $CURRENT_VER installed.\"\n      echo \"Run 'rlsbl scaffold' to update scaffolding.\"\n    fi\n  fi\nfi\n",
	"#!/usr/bin/env bash\n# Pre-push hook: verify CHANGELOG.md has an entry for the current version.\n# Install: cp scripts/pre-push-hook.sh .git/hooks/pre-push && chmod +x .git/hooks/pre-push\n\nset -euo pipefail\n\n# Detect project type and extract version\nif [ -f package.json ]; then\n  VERSION=$(node -e \"console.log(require('./package.json').version)\" 2>/dev/null) || exit 0\nelif [ -f pyproject.toml ]; then\n  VERSION=$(grep -m1 '^version' pyproject.toml | sed 's/.*\"\\(.*\\)\".*/\\1/') || exit 0\nelif [ -f VERSION ]; then\n  VERSION=$(tr -d '[:space:]' < VERSION) || exit 0\nelse\n  exit 0\nfi\n\nif [ -z \"$VERSION\" ]; then\n  exit 0\nfi\n\n# Check CHANGELOG.md has an entry for this version\nif [ ! -f CHANGELOG.md ]; then\n  echo \"Warning: CHANGELOG.md not found.\"\n  exit 0\nfi\n\nif ! grep -q \"^## $VERSION\" CHANGELOG.md; then\n  echo \"Error: CHANGELOG.md has no entry for version $VERSION.\"\n  echo \"Add a '## $VERSION' section before pushing.\"\n  exit 1\nfi\n\n# Check scaffolding freshness\nif [ -f .rlsbl/version ]; then\n  SCAFFOLD_VER=$(cat .rlsbl/version | tr -d '[:space:]')\n  if command -v rlsbl &>/dev/null; then\n    CURRENT_VER=$(rlsbl --version 2>/dev/null | tr -d '[:space:]')\n    if [ -n \"$CURRENT_VER\" ] && [ \"$SCAFFOLD_VER\" != \"$CURRENT_VER\" ]; then\n      echo \"Warning: scaffolding was generated by rlsbl $SCAFFOLD_VER but you have $CURRENT_VER installed.\"\n      echo \"Run 'rlsbl scaffold' to update scaffolding.\"\n    fi\n  fi\nfi\n",
	"#!/usr/bin/env bash\nexec rlsbl pre-push-check \"$@\"\n",
	"#!/usr/bin/env bash\nexec rlsbl pre-push-check\n",
	"#!/usr/bin/env bash\nexport RLSBL_PUSH_STDIN=\"$(cat)\"\nexec rlsbl check --tag prepush\n",
	strings.Replace(PrePushHook, "exec rlsbl failing-checks --hook pre-push", "exec rlsbl check --tag prepush", 1),
	PrePushHook,
}

// HookHash is the SHA-256 of a hook's content with trailing whitespace
// removed, so an editor's change to the final newline does not make a
// shipped hook look customized.
func HookHash(content string) string {
	sum := sha256.Sum256([]byte(strings.TrimRightFunc(content, unicode.IsSpace)))
	return hex.EncodeToString(sum[:])
}

// gitHook is one hook scaffold installs: its file name, its content, and
// every content rlsbl has shipped for it.
type gitHook struct {
	name    string
	content string
	shipped []string
}

var gitHooks = []gitHook{
	{name: "pre-push", content: PrePushHook, shipped: shippedPrePushHooks},
	{name: "post-rewrite", content: PostRewriteHook, shipped: []string{PostRewriteHook}},
}

// ShippedHook reports whether content is one rlsbl shipped for the named
// hook (the current one included).
func ShippedHook(name, content string) bool {
	for _, h := range gitHooks {
		if h.name != name {
			continue
		}
		hash := HookHash(content)
		for _, s := range h.shipped {
			if HookHash(s) == hash {
				return true
			}
		}
	}
	return false
}

// gitAnswer runs a git read in dir and returns its trimmed stdout; found is
// false when git exits non-zero.
func gitAnswer(r git.Runner, dir string, args ...string) (out string, found bool, err error) {
	argv := []interface{}{"git"}
	for _, a := range args {
		argv = append(argv, a)
	}
	c, err := r.Run(argv, strictcli.Cwd(dir), strictcli.Check(false))
	if err != nil {
		return "", false, fmt.Errorf("git %s in %s: %w", strings.Join(args, " "), dir, err)
	}
	if c.ExitCode() != 0 {
		return "", false, nil
	}
	return strings.TrimSpace(c.Stdout()), true, nil
}

// HooksDirectory is the directory git runs the repository's hooks from, as
// git itself answers it (core.hooksPath honored, a linked worktree's common
// directory). A core.hooksPath naming anything but the repository's own
// hooks directory is refused, naming the setting, where it is set, and the
// command that removes it: scaffold does not write hooks into a directory
// other repositories may share or the working tree may commit.
func HooksDirectory(r git.Runner, dir string) (string, error) {
	hooks, ok, err := gitAnswer(r, dir, "rev-parse", "--path-format=absolute", "--git-path", "hooks")
	if err != nil {
		return "", err
	}
	common, ok2, err := gitAnswer(r, dir, "rev-parse", "--path-format=absolute", "--git-common-dir")
	if err != nil {
		return "", err
	}
	if !ok || !ok2 || hooks == "" || common == "" {
		return "", fmt.Errorf("git could not say where %s runs its hooks from", dir)
	}
	standard := filepath.Join(common, "hooks")
	if samePath(hooks, standard) {
		return standard, nil
	}
	origin, _, err := gitAnswer(r, dir, "config", "--get", "--show-origin", "core.hooksPath")
	if err != nil {
		return "", err
	}
	source, value, _ := strings.Cut(origin, "\t")
	where, fix := "the git configuration", "removing it from the git configuration that sets it"
	if file, ok := strings.CutPrefix(source, "file:"); ok {
		where = file
		fix = "`git config --file " + file + " --unset core.hooksPath`"
	} else if source != "" {
		where = source
		fix = "removing it from " + source
	}
	if value == "" {
		value = "(unknown)"
	}
	return "", fmt.Errorf("core.hooksPath is set to %q (in %s), so git runs this repository's hooks from %s, not from %s; rlsbl scaffold installs its pre-push and post-rewrite hooks where git runs them and does not write into a directory core.hooksPath names. Remove the setting with %s, then run rlsbl scaffold again", value, where, hooks, standard, fix)
}

// samePath compares two paths after resolving symbolic links, falling back
// to the cleaned paths for one that does not exist yet.
func samePath(a, b string) bool {
	resolve := func(p string) string {
		if r, err := filepath.EvalSymlinks(p); err == nil {
			return r
		}
		return filepath.Clean(p)
	}
	return resolve(a) == resolve(b)
}

// hookChange is what installing one hook does.
type hookChange struct {
	name string
	path string
	// action is "install", "update", or "" when the hook is current.
	action  string
	content string
}

// planHooks reads the installed hooks under hooksDir and decides each one.
// A hook whose content rlsbl never shipped is refused before anything is
// written.
func planHooks(hooksDir string) ([]hookChange, error) {
	var changes []hookChange
	var refused []string
	for _, h := range gitHooks {
		path := filepath.Join(hooksDir, h.name)
		data, err := os.ReadFile(path)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			changes = append(changes, hookChange{name: h.name, path: path, action: "install", content: h.content})
			continue
		case err != nil:
			return nil, fmt.Errorf("reading the %s hook: %w", h.name, err)
		}
		installed := string(data)
		switch {
		case HookHash(installed) == HookHash(h.content):
			changes = append(changes, hookChange{name: h.name, path: path})
		case ShippedHook(h.name, installed):
			changes = append(changes, hookChange{name: h.name, path: path, action: "update", content: h.content})
		default:
			refused = append(refused, fmt.Sprintf("the %s hook at %s is not one rlsbl installed, and rlsbl does not overwrite it. rlsbl's hook is:\n%s", h.name, path, indent(h.content, "    ")))
		}
	}
	if len(refused) > 0 {
		return nil, fmt.Errorf("%s\nDelete the hook (saferm delete --on-error abort --description \"replace with rlsbl's hook\" <path>) and run rlsbl scaffold again; a check a hook of your own needs belongs in the project's checks, which the pre-push hook runs", strings.Join(refused, "\n"))
	}
	return changes, nil
}

// indent prefixes every non-empty line of text.
func indent(text, prefix string) string {
	lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
	for i, l := range lines {
		if l != "" {
			lines[i] = prefix + l
		}
	}
	return strings.Join(lines, "\n")
}

// installHooks writes the planned hooks, executable, and says what it did,
// or under --dry-run what it would do.
func installHooks(e *strictcli.Effects, changes []hookChange, dryRun bool, say func(string)) error {
	for _, c := range changes {
		if c.action == "" {
			continue
		}
		if _, err := e.Mkdir(filepath.Dir(c.path)); err != nil {
			return fmt.Errorf("creating %s: %w", filepath.Dir(c.path), err)
		}
		if _, err := e.Write(c.path, c.content, strictcli.Mode(0o755)); err != nil {
			return fmt.Errorf("writing the %s hook: %w", c.name, err)
		}
		switch {
		case dryRun && c.action == "install":
			say(fmt.Sprintf("Would install the %s hook (%s)", c.name, c.path))
		case dryRun:
			say(fmt.Sprintf("Would update the %s hook (%s), which is an earlier rlsbl version", c.name, c.path))
		case c.action == "install":
			say(fmt.Sprintf("Installed %s hook (%s)", c.name, c.path))
		default:
			say(fmt.Sprintf("Updated %s hook (%s), which was an earlier rlsbl version", c.name, c.path))
		}
	}
	return nil
}
