"""Generate a Markdown CHANGELOG.md from structured JSONL changelog entries, grouping them by version with configurable formatting."""

from __future__ import annotations

import os
import sys

import tomlkit

from .files import get_changes_dir, list_versioned_files, read_unreleased
from .schema import ChangelogEntry, parse_jsonl

_HEADER_COMMENT = "<!-- Generated by rlsbl from .rlsbl/changes/ — do not edit -->"

# Type name -> display header, in canonical order.
_TYPE_ORDER: list[tuple[str, str]] = [
    ("breaking", "Breaking"),
    ("feature", "Features"),
    ("fix", "Fixes"),
]


def _read_release_metadata(project_path: str, version: str) -> tuple[str, str]:
    """Read description and context from an archived release toml file.

    Looks for .rlsbl/releases/v{version}.toml and extracts the description
    and context fields. Returns ("", "") if the file doesn't exist or can't
    be parsed.
    """
    desc, ctx, _bump = _read_release_metadata_full(project_path, version)
    return (desc, ctx)


def _read_release_metadata_full(project_path: str, version: str) -> tuple[str, str, str]:
    """Read description, context, and bump type from an archived release toml file.

    Looks for .rlsbl/releases/v{version}.toml and extracts the description,
    context, and bump fields. Returns ("", "", "") if the file doesn't exist
    or can't be parsed.
    """
    toml_path = os.path.join(project_path, ".rlsbl", "releases", f"v{version}.toml")
    try:
        with open(toml_path, "r", encoding="utf-8") as f:
            data = tomlkit.load(f)
    except (OSError, tomlkit.exceptions.ParseError):
        return ("", "", "")

    description = data.get("description", "")
    context = data.get("context", "")
    bump = data.get("bump", "")
    if not isinstance(description, str):
        description = ""
    if not isinstance(context, str):
        context = ""
    if not isinstance(bump, str):
        bump = ""
    return (description.strip(), context.strip(), bump.strip())


def generate_version_section(
    version: str,
    entries: list[ChangelogEntry],
    *,
    description: str = "",
    context: str = "",
    bump_type: str | None = None,
) -> str:
    """Generate markdown for one version section.

    Only includes entries where user_facing=True. Groups by type under
    sub-headers (Breaking, Features, Fixes, Other). Empty groups are omitted.
    If no user-facing entries exist, emits a single "No user-facing changes." bullet.

    If all entries share a release_type (e.g., "ota" or "build"), a marker
    is appended to the version heading.

    When ``description`` is provided, it is added as a paragraph after the
    version heading and before the first type group. When ``context`` is
    provided, it is rendered as a collapsible ``<details>`` block after the
    description.
    """
    # Determine release type marker from entries
    release_types = {e.release_type for e in entries if e.release_type}
    release_marker = ""
    if len(release_types) == 1:
        rt = release_types.pop()
        release_marker = f" ({rt.upper()})"

    user_facing = [e for e in entries if e.user_facing]

    if not user_facing:
        section = f"## {version}{release_marker}\n\n"
        if description:
            section += f"{description}\n\n"
        if context:
            section += (
                "<details>\n<summary>Context</summary>\n\n"
                f"{context}\n\n</details>\n\n"
            )
        if bump_type == "hotfix" and description:
            section += f"### Hotfix\n\n- {description}\n"
        else:
            section += "- No user-facing changes.\n"
        return section

    # Bucket entries by type.
    buckets: dict[str, list[str]] = {}
    for entry in user_facing:
        key = entry.type if entry.type in ("breaking", "feature", "fix") else "_other"
        buckets.setdefault(key, []).append(entry.description or "")

    parts: list[str] = [f"## {version}{release_marker}"]

    if description:
        parts.append("")
        parts.append(description)

    if context:
        parts.append("")
        parts.append("<details>")
        parts.append("<summary>Context</summary>")
        parts.append("")
        parts.append(context)
        parts.append("")
        parts.append("</details>")

    for type_key, header in _TYPE_ORDER:
        descs = buckets.get(type_key)
        if not descs:
            continue
        parts.append("")
        parts.append(f"### {header}")
        parts.append("")
        for desc in descs:
            parts.append(f"- {desc}")

    other = buckets.get("_other")
    if other:
        parts.append("")
        parts.append("### Other")
        parts.append("")
        for desc in other:
            parts.append(f"- {desc}")

    parts.append("")  # trailing newline
    return "\n".join(parts)


def generate_version_file(
    changes_dir: str,
    version: str,
    write_to_disk: bool = True,
    *,
    description: str = "",
    context: str = "",
    bump_type: str | None = None,
) -> str:
    """Read the JSONL file for a version, generate markdown, optionally write .md alongside it.

    Returns the generated markdown text. When write_to_disk is False, computes the
    markdown without touching the filesystem (used to preview content before pre-checks).

    When ``description`` and ``context`` are provided, they are passed through to
    ``generate_version_section()`` so release metadata appears in the output.
    """
    jsonl_path = os.path.join(changes_dir, f"{version}.jsonl")
    entries = parse_jsonl(jsonl_path)
    md = generate_version_section(version, entries, description=description, context=context, bump_type=bump_type)

    if write_to_disk:
        md_path = os.path.join(changes_dir, f"{version}.md")
        # Skip the write when content is unchanged, so regeneration doesn't
        # needlessly dirty already-committed per-version files.
        existing = None
        if os.path.exists(md_path):
            with open(md_path, "r", encoding="utf-8") as f:
                existing = f.read()
        if existing != md:
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(md)

    return md


def _read_changelog_format(project_path: str) -> str:
    """Read changelog_format from project config, defaulting to 'grouped'."""
    config_path = os.path.join(project_path, ".rlsbl", "config.json")
    try:
        import json

        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    except (OSError, json.JSONDecodeError):
        return "grouped"

    fmt = config.get("changelog_format", "grouped")
    if fmt != "grouped":
        print(
            f"Warning: unrecognized changelog_format '{fmt}', falling back to 'grouped'",
            file=sys.stderr,
        )
        fmt = "grouped"
    return fmt


def generate_changelog(
    project_path: str,
    *,
    write_to_disk: bool = True,
    version_override: str | None = None,
    description: str = "",
    context: str = "",
    changes_dir_override: str | None = None,
    changelog_output_path: str | None = None,
    bump_type: str | None = None,
) -> str:
    """Generate the complete CHANGELOG.md from .rlsbl/changes/ JSONL files.

    1. Reads changelog_format from config (only "grouped" supported).
    2. Reads unreleased.jsonl (if non-empty) for an Unreleased section.
    3. Reads all versioned JSONL files sorted newest-first.
    4. Generates per-version .md files alongside the JSONL files (when write_to_disk).
    5. Writes CHANGELOG.md at project root (when write_to_disk).
    6. Returns the generated content.

    When write_to_disk is False, computes and returns the markdown content without
    modifying the filesystem. This lets callers preview the changelog before
    pre-release checks run, so an aborted release leaves a clean working tree.

    When version_override is provided AND unreleased entries exist, the section
    heading is "## {version_override}" instead of "## Unreleased". Versioned
    sections (from existing JSONL files) are unaffected. Default None preserves
    the original behaviour exactly.

    ``description`` and ``context`` are applied to the unreleased section only
    (the current release being prepared). Previously released version sections
    read their description and context from archived release files at
    ``.rlsbl/releases/v{version}.toml``.

    ``changes_dir_override`` overrides the default ``.rlsbl/changes/`` path.
    Used in explicit releasable mode where the changes dir lives under the
    releasable directory.

    ``changelog_output_path`` overrides the default CHANGELOG.md output location.
    Used in explicit releasable mode to write CHANGELOG.md into the releasable
    directory instead of the project root.

    ``bump_type`` is passed through to ``generate_version_section()`` for the
    unreleased section. For versioned sections, the bump type is read from the
    archived release file.
    """
    _read_changelog_format(project_path)

    changes_dir = changes_dir_override or get_changes_dir(project_path)
    sections: list[str] = []

    # Unreleased entries
    unreleased = read_unreleased(changes_dir)
    if unreleased:
        heading = version_override if version_override else "Unreleased"
        sections.append(generate_version_section(
            heading, unreleased, description=description, context=context,
            bump_type=bump_type,
        ))

    # Versioned entries (newest first)
    for version, jsonl_path in list_versioned_files(changes_dir):
        ver_desc, ver_ctx, ver_bump = _read_release_metadata_full(project_path, version)
        md = generate_version_file(
            changes_dir, version, write_to_disk=write_to_disk,
            description=ver_desc, context=ver_ctx,
            bump_type=ver_bump or None,
        )
        sections.append(md)

    body = "\n".join(sections)
    content = f"{_HEADER_COMMENT}\n\n# Changelog\n\n{body}"

    if write_to_disk:
        changelog_path = changelog_output_path or os.path.join(project_path, "CHANGELOG.md")
        with open(changelog_path, "w", encoding="utf-8") as f:
            f.write(content)

    return content
