"""Single source of truth for where generated CHANGELOG.md files live, resolving the correct directory for standalone, implicit, and releasable modes.

Three consumers previously disagreed about the changelog home in explicit
releasable mode: the release flow wrote CHANGELOG.md into the representative
member's directory, ``rlsbl changelog generate`` wrote it into the
releasable's directory, and the ``changelog-entry`` check expected the
releasable's directory.  This module is the ONE resolver all of them (plus
undo and the GitHub-Release-notes hint) must go through.

Semantics:

- Standalone projects (no releasable): the canonical CHANGELOG.md lives at
  the project root, exactly as before.
- Releasable members (explicit monorepo mode): the canonical CHANGELOG.md
  lives in the releasable's state directory
  (``.rlsbl-monorepo/releasables/<name>/CHANGELOG.md``).  Additionally, a
  combined root CHANGELOG.md at the workspace root covers ALL releasables
  of the workspace, one section per releasable in workspace.toml order.
"""

from __future__ import annotations

import os

_WORKSPACE_HEADER_COMMENT = (
    "<!-- Generated by rlsbl from .rlsbl-monorepo/releasables/ — do not edit -->"
)


def get_changelog_home(project_dir: str, *, releasable_dir: str | None = None) -> str:
    """Return the canonical CHANGELOG.md path.

    ``releasable_dir`` is the releasable's state directory
    (``.rlsbl-monorepo/releasables/<name>/``); when given, the canonical
    changelog lives there.  Otherwise it lives at the project root.
    """
    if releasable_dir:
        return os.path.join(releasable_dir, "CHANGELOG.md")
    return os.path.join(project_dir, "CHANGELOG.md")


def get_workspace_changelog_path(workspace_root: str) -> str:
    """Return the path of the combined root CHANGELOG.md for a workspace."""
    return os.path.join(str(workspace_root), "CHANGELOG.md")


def _strip_canonical_header(content: str) -> str:
    """Strip the generated-file comment and the '# Changelog' H1 from a
    canonical per-releasable changelog, leaving only the version sections."""
    lines = content.splitlines()
    body_start = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("<!--") or stripped == "# Changelog":
            body_start = i + 1
            continue
        body_start = i
        break
    return "\n".join(lines[body_start:]).strip("\n")


def generate_workspace_changelog(workspace_root: str, *, write_to_disk: bool = True) -> str:
    """Generate the combined root CHANGELOG.md covering all releasables.

    Reads each releasable's canonical CHANGELOG.md (in workspace.toml
    order), strips its header, and emits it under a top-level heading named
    after the releasable.  Releasables without a canonical changelog on
    disk are omitted.  For a single-releasable workspace this yields that
    releasable's changelog at the root (under its name heading).

    Returns the generated content.  When ``write_to_disk`` is True, writes
    it to the workspace root (skipping the write if content is unchanged).
    """
    from ..workspace import get_releasable_dir, load_releasables, load_workspace

    workspace_root = str(workspace_root)
    projects = load_workspace(workspace_root)
    releasables = load_releasables(workspace_root, projects=projects)

    sections = []
    for rel in releasables:
        canonical = get_changelog_home(
            workspace_root,
            releasable_dir=get_releasable_dir(workspace_root, rel.name),
        )
        if not os.path.isfile(canonical):
            continue
        with open(canonical, "r", encoding="utf-8") as f:
            body = _strip_canonical_header(f.read())
        sections.append(f"# {rel.name}\n\n{body}\n")

    content = _WORKSPACE_HEADER_COMMENT + "\n\n" + "\n".join(sections)

    if write_to_disk:
        out_path = get_workspace_changelog_path(workspace_root)
        existing = None
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as f:
                existing = f.read()
        if existing != content:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(content)

    return content
